#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 02. Introduction to Big History
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]]

* 02. Introduction to Big History
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/09/02/intro.org
:Created:  2018-04-24T11:58@Prek Leap (11.642600N-104.919210W)
:ID:       29343d16-9619-435e-ae31-1143dd958a1b
:VER:      577817958.265644731
:GEO:      48P-491193-1287029-15
:BXID:     proj:PIY4-4082
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

** Representing Time

Big History is pretty fucking cool.  The idea is to tell the
story of the universe (us included) from the perspective of
complexity thresholds since the Big Bang.

Before Big History is the masterful /Cosmos/ by Carl Sagan
which was both a book and television series.
 
Big History uses a timeline, whereas Sagan uses a /Cosmic
Calendar/citenum:wiki:2017cosmic-calendar which he first
used in his book /Dragon's of Eden/citenum:sagan:1986dragons
which presents the 13.7byr history of the universe as a
single calendar month.  This is a far better way for people
to understand the scale of the universe and our place in it.
The timeline needs to compress the space where there is
little information and expand the space where there is more
information which, like 2D map projections of a globe deform
time scales to be able to fit in a space that can be seen at
a glance.  This is not a bad thing, everything is a
tradeoff.  But Sagan's Calendar is better at helping us
understand how small and short a time we have been on the
cosmic stage.

Big History is brilliant, with fantastic graphics.  But the
text is a little dry, it doesn't have the poetry or passion
that Sagan brought to everything.  That's not entirely true,
David Christian's performance at TEDx was fantastic.

The just released /Little Book of Big History/ seems very
good, but it just doesn't have Sagan's genius.

Wait, But Why? has one of the best means of visualizing time
that I've ever seen:

  - [[https://waitbutwhy.com/2013/08/putting-time-in-perspective.html][Putting Time In Perspective]] | Wait But Why

He uses a series of growing timelines.  This works quite
well but doesn't have the same massive in your face impact
that Big History's massive timeline has (mostly because they
had a bigger graphics budget) or the simple but powerful
analogy that Sagan uses to be able to fit such mind blowing
numbers into something that our poor ape brains can grasp.

---

The manifesto was getting too long and un-manifesto like so
most of what I have now as the manifesto will move to the
prologomenon. 

The prologomenon will now serve several purposes: 

  - a collective model of the world for a community/movement
  - an apology and or thesis that the manifesto is based on
  - the foundation for our new liberal arts program
  - a framework that we can use as an outline of knowledge
    that replaces efforts like the traditional hierarchical
    /Propædia/ by Mortimer Adler.  

The Propædia never really caught on in the way that Alder
envisoned.  He saw it as a framework for all knowledge,
education and a model of the sum total of what we
collectively know as a species.  For a while, it was the
first of three parts of the Encyclopedia Briticannica.

The [[https://en.wikipedia.org/wiki/Prop%C3%A6dia][Propædia]] and [[https://en.wikipedia.org/wiki/Microp%C3%A6dia][Micropædia]] were intended to replace the
Index, and the [[https://en.wikipedia.org/wiki/Macrop%C3%A6dia][Macropædia]] was the main body of the
encyclopedia that was in turn made up of articles that
provided introductions and overviews to larger topics, which
would then point, in the references to all the papers and
works that make up the body of knowledge.

This concept was a big influence on many of my original
ideas in BMF.  Scope, Micro and Macro notes were intended to
work in the same way as Adler's vision for Britannica.

It turned out to be a clunky interface in physical print.
The [[https://en.wikipedia.org/wiki/Microp%C3%A6dia][Micropædia]] was a poor replacement for the index.  But it
might have been an excellent electronic interface, where the
Micropædia entries could be returned as search results, and
the Propædia be used as a framework for a thesaurus of terms
for everthing in the Micropædia which would become in effect
a graph database.

At first glance it would seem that Wikipedia has rendered
this vision obsolete, but I don't see it that way.  

Rather, wikipedia could be seen as a first, living draft of
a Macropædia that is always in the process of becoming
something else.  But it provides no /intellectus/, no way of
seeing how everything fits together.  It's just one dam
article after another.  And Wikipedia is poor at being a
gateway to all literature on a subject.  That's not a
criticism, it's just the way that it was designed.  But that
is very much needed.

** References

  - Behmand, M., Burke, T., & Simon, R. B., Teaching big history
    (2015), : University of California Press.
    cite:behmand:2015teaching
