#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Adhocracies (chapter)
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]


* Adhocracies (chapter)
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/10/55/ww-adhocracies.org
:Created:  2018-05-09T16:29@Prek Leap (11.642600N-104.919210W)
:ID:       23c808a9-cf72-4bda-bbf2-7879abd03842
:VER:      579130209.095549818
:GEO:      48P-491193-1287029-15
:BXID:     proj:LUH5-5607
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR

** Weber Quotes

#+begin_quote
These competencies are underpinned by rules, laws, or administrative
regulations. That means:

   1. A rigid division of labor is in place for the purpose of
      performing regular daily tasks as official duties in the
      functioning of the bureaucratically governed system.
   2. In order to fulfill these duties the necessary chains of command
      are firmly established and divided up [among the Beamte], and
      their capacity to coerce (physical, sacred, or other) is firmly
      restricted by regulation.
   3. Regular and continuous fulfillment of these assigned duties, and
      the execution of respective rights is systematically secured by
      hiring people with certified qualifications.

These three aspects constitute the essence of bureaucratic
administration of a Behörde in the public sector. In the private
sector, these three aspects constitute the essence of a bureaucratic
management of a private company [Betrieb]. Not until the emergence of
the modern state could this type of bureaucratic government Behörde be
fully realized in political and church organizations. And it was not
until the development of the most advanced forms of capitalism that
this kind of administration emerged in the private sector.

pdfview:../../../hoard/lib/waters:2015webers-rationalism.pdf::84
#+end_quote

#+begin_quote
Main principles (characteristics):

  1. Specialized roles
  2. Recruitment based on merit (e.g., tested through open
     competition)
  3. Uniform principles of placement, promotion, and transfer in an administrative system
  4. Careerism with systematic salary structure
  5. Hierarchy, responsibility and accountability
  6. Subjection of official conduct to strict rules of discipline and control
  7. Supremacy of abstract rules
  8. Impersonal authority (e.g., office bearer does not bring the office with him)
  9.  Political neutrality


— pdfview:../../../hoard/lib/waters:2015webers-rationalism.pdf::84 
  summarized in cite:wiki:2018max-weber
#+end_quote


** Toffler Quotes

#+begin_quote
For we are witnessing not the triumph, but the breakdown of
bureaucracy. We are, in fact, witnessing the arrival of a new
organizational system that will increasingly challenge, and ultimately
supplant bureaucracy. This is the organization of the future. I call
it "Ad-hocracy."

Man will encounter plenty of difficulty in adapting to this new style
organization. But instead of being trapped in some unchanging,
personality-smashing niche, man will find himself liberated, a
stranger in a new free-form world of kinetic organizations. In this
alien landscape, his position will be constantly changing, fluid, and
varied. And his organizational ties, like his ties with things, places
and people, will turn over at a frenetic and ever- accelerating rate.

pdfview:../../../hoard/lib/toffler:1971future-shock.pdf::71
#+end_quote

** References

  - Toffler, A., Future shock (1971), : Bantam Books. 
    cite:toffler:1971future-shock
  - Waters, T., & Waters, D., Weber’s rationalism and modern
    society: new translations on politics, bureaucracy, and
    social stratification (2015), : Palgrave Macmillan US.
    cite:waters:2015webers-rationalism
