#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Adhocracies (chapter)
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]


* Adhocracies (chapter)
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/10/55/ww-adhocracies.org
:Created:  2018-05-09T16:29@Prek Leap (11.642600N-104.919210W)
:ID:       23c808a9-cf72-4bda-bbf2-7879abd03842
:VER:      579130209.095549818
:GEO:      48P-491193-1287029-15
:BXID:     proj:LUH5-5607
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR

** Webber Quotes

#+begin_quote
These competencies are underpinned by rules, laws, or administrative
regulations. That means:

   1. A rigid division of labor is in place for the purpose of
      performing regular daily tasks as official duties in the
      functioning of the bureaucratically governed system.
   2. In order to fulfill these duties the necessary chains of command
      are firmly established and divided up [among the Beamte], and
      their capacity to coerce (physical, sacred, or other) is firmly
      restricted by regulation.
   3. Regular and continuous fulfillment of these assigned duties, and
      the execution of respective rights is systematically secured by
      hiring people with certified qualifications.

These three aspects constitute the essence of bureaucratic
administration of a Behörde in the public sector. In the private
sector, these three aspects constitute the essence of a bureaucratic
management of a private company [Betrieb]. Not until the emergence of
the modern state could this type of bureaucratic government Behörde be
fully realized in political and church organizations. And it was not
until the development of the most advanced forms of capitalism that
this kind of administration emerged in the private sector.

pdfview:../../../hoard/lib/waters:2015webers-rationalism.pdf::84
#+end_quote




** References


