#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Automation Economics 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Automation Economics
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/foundations/auto-eco.org
  :Created:   2018-06-29T07:35@Prek Leap (11.642600N-104.919210W)
  :ID:        b5013e60-12aa-48c9-882e-09930b952015
  :VER:       583504571.109998387
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:TBU8-1758
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope
** TL;DR

A Capitalist is literally someone who lives off of the growth of
capital as opposed to laborers who live off of their labor.  Another
term for a capitalist is an older word, rentier, someone who lives off
of rents and fees paid for use of someone elses capital.

In good times, spent one third of their income or less on rents in
the form of taxes to the state, rents paid for living quarters, or in
the form of loans and mortgages on borrowed capital for the purchase
of things like houses and automobiles.  In the late 20th century in
developed countries this started to change and a larger and larger
percentage of income began going to rents.  New types of rents
appeared for use of networks -- cable television and cell phone
networks.  Amazon Prime is effectively a rent as well -- and don't be
fooled, in time most people will feel as locked into paying their
Amazon Prime rent as they do their cable, and cell rents.

The higher percentage of rents you pay, the less control you have over
your life -- the more you can build up capital and live off that
capital the more control and agency you will have.  I believe that a
lot of the unease and desperation that middle class in advanced
economies feel is this loss of agency which their parents or
grandparents had some measure of.  This always was the demarcation
between the working and middle class, the working class lived
pay-check to pay-check, the middle-class spent their working life
building up a small amount of capital which could be used for
retirement.  Blue-collar factory work had, for a short time after
World War II when labor unions held-sway provided a version of this.
Workers were paid enough to accrue capital that was spent on educating
children, purchase of a house and saving for retirement.  This
encapsulates the so-called Post-War "American Dream."

The rise of nation-wide and global retail chain stores neatly wiped
out a large part of the merchant class who built up small and medium
sized shops, services and restaurants that was the model for the
employed-worker-based middle class.  An entire layer of the econonomy
that was a vital means of class mobility was eliminated leaving ever
more people trapped in a shrinking employed-worker middle class who
could no longer afford to build capital, replacing it with the
appearance of capital by paying rents.

---

But there was always another American Dream, the idea that in America
social mobility was somewhat fluid and it was possible to get rich
quick and move into the tycoon class.  A handful of families achieved
this with names that are as familiar as the furniture in the,
Vanderbilt, Carnegie, Rockefella, Morgan, Mellon and later Kennedy and
Getty who would make it into the same economic situation as the landed
gentry in europe who lived off of their accumulated capital.

In the late 20th and beginning of the 21st centuries, as the
middle-class saw their capital evaporate, three new means of getting
rich quick emerged, which manipulated information in order to build
capital. In each case, the capital was often used for status seeking
instead of long-term multi-generational investment.

The first, property speculation, certainly was nothing new.  But what
was new was that land and buildings were no longer seen as a means to
an end, but an end in themselves.  Buying a home was replaced with
buying a house.  With enough persistence and effort income earned
through employment could be used to buy property, not to live in, but
to sell and make enough money to invest the profits in more property.
In typical Chinese fashion, China has taken this model to an extreme,
with property develops understanding that people were looking to buy
property as an investment rather than as homes. And because of a quirk
in Chinese culture where it is not desirable to buy a house that
someone has lived in before, if you invested in property it could
either be rented out, or it could be sold again, but it would not sell
after it had been lived in. This has resulted in the space of less
than twenty years in the construction of vast ghost cities with whole
forests of 30 floor buildings, all sitting vacant, and all purchased
by the middle class as investments.  Chinese property developers are
now trying to export this business-model to other parts of east and
south-east Asian with mixed results.

The financial sector was the second get-rich-quick avenue.  It became
possible with little more than a Bachelor's degree to get a job in
financial trading companies where it was possible to accrue large
amounts of capital in a relatively short period of time.  The problem
with this model is that in many cases, the capital that was accrued
was not invested or saved, but spent on status seeking, to rent the
appearance of having more capital than you actually had.  This makes
possible a precarious life-style at a very high level, but is never
more than one or two bad trades away from being wiped out.

The third method was a variation on the /land-rush/ or /gold-rush/
model where being the first to enter a market that was reaching a
tipping point and was in the early stages of exponential grown when
the barrier to entry was very low.

[[https://www.youtube.com/watch?v=8-Sn2ZgfVqM][Tumbleweeds]] Cherokee Strip Land Rush scene
https://newsok.com/gallery/2497/pictures/51506

The 21st century incarnation of this was the Dot-Com boom, followed by
the Mobile-App boom.  The pioneers who developed the technology that
became the Internet and Web thought of what they were doing in the
same way that people would buy a home.  But early adopters only saw
the technology as a means to getting rich quickly.

None of three of these methods are sustainable.  First, they are seen
as zeo-sum where one person can not succeed unless someone else
looses.  This is physical true in the case of property speculation as
what is being speculated on is physical and finite.  Only one party
can profit from a single property.  In the case of financial and
technological greed, the finite resource that is fought over is
customers.  That there are a limited number of people you can sell
things to resulting in a hunger games environment where all players
are eliminated until there is only one, holding a monopoly.

---

All types of is a kind of capital and in that sense it is a form of
property.  Slavery is the original embodiment of this concept, where a
person is held captive and their labor is the property of the captor.
The industrial revolution made it clear that there was no need to hold
people captive to own their labor.  It was far cheaper to leave people
free when not working, so that workers are responsible for finding and
maintaining their own food and shelter.  So long as they maintained
conditions where workers had no alternative but to sell their labor to
an employer that in many cases there was no reason to keep people
physically captive indefinitately.  

This obviously is still not always the case.  Prison labor is the
slave-model write large.  Large companies, especially as seen today in
East Asia buy industrial giants who house workers, provide banking,
housing, company stores, medical care and education for workers on
company premises.  These are not perks, all of these services must be
paid for by workers from the salaries they receive and those services
are provided to make a profit.

This model was pioneered in the United States in the 19th century as
means of maintaining business models that had previously depended on
traditional slave labor.  The Nation-State system fully supports this
model in the form of restrictive visas that tie a worker to a specific
job or circumstance.  The State even provides runaway slave recapture
services at no cost.  Domestic help, the hospitality industry, farm
and plantations and labor intensive industrial factories all employ
this form of slavery.  In the event that what few rights these workers
have is violated, often in horrific fashion as in rape of domestic
help, and physical violence to others, the workers are deported from
the country before they can seek redress from courts.  This is one
dark side of shiny ultramodern bastions of capitalism such as Hong
Kong and Singapore and throughout the tiny oil-rich countries in the
Middle East.  In the film, /A Hologram for the King/, after the
protagonist observes a number of workers being ill-treated, asks his
driver what the trade-unions have to say about this.  The driver
shrugs and says, "we don't have unions, we have Filipinos."

In all cases, workers are dependent on their employer for day-to-day
existance, they have little to no agency, ability to choose where and
how they live, where they can send their children to school, buy food, 
clothing, etc.



Machine-cog is a form of labor which is also a form of property.

If machine-cog can work efficiently at small scales, then the
possibility of a new middle class emerging, who builds up capital they
can live on by leveraging machine-labour rather than land as property
and buildings as property or the accumulation of invested currency in
the form of stocks, bonds and other financial instuments.

** References

  - Piketty, T., & Goldhammer, A., Capital in the twenty-first century
    (2014), : Belknap Press.
    cite:piketty:2014capital-twenty-first
