#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Automation Economics 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Automation Economics
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/foundations/auto-eco.org
  :Created:   2018-06-29T07:35@Prek Leap (11.642600N-104.919210W)
  :ID:        b5013e60-12aa-48c9-882e-09930b952015
  :VER:       583504571.109998387
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:TBU8-1758
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope
** TL;DR

A Capitalist is literally someone who lives off of the growth of
capital as opposed to laborers who live off of their labor.  Another
term for a capitalist is an older word, rentier, someone who lives off
of rents and fees paid for use of someone elses capital.

In good times, spent one third of their income or less on rents in
the form of taxes to the state, rents paid for living quarters, or in
the form of loans and mortgages on borrowed capital for the purchase
of things like houses and automobiles.  In the late 20th century in
developed countries this started to change and a larger and larger
percentage of income began going to rents.  New types of rents
appeared for use of networks -- cable television and cell phone
networks.  Amazon Prime is effectively a rent as well -- and don't be
fooled, in time most people will feel as locked into paying their
Amazon Prime rent as they do their cable, and cell rents.

The higher percentage of rents you pay, the less control you have over
your life -- the more you can build up capital and live off that
capital the more control and agency you will have.  I believe that a
lot of the unease and desperation that middle class in advanced
economies feel is this loss of agency which their parents or
grandparents had some measure of.  This always was the demarcation
between the working and middle class, the working class lived
pay-check to pay-check, the middle-class spent their working life
building up a small amount of capital which could be used for
retirement.  Blue-collar factory work had, for a short time after
World War II when labor unions held-sway provided a version of this.
Workers were paid enough to accrue capital that was spent on educating
children, purchase of a house and saving for retirement.  This
encapsulates the so-called Post-War "American Dream."

The rise of nation-wide and global retail chain stores neatly wiped
out a large part of the merchant class who built up small and medium
sized shops, services and restaurants that was the model for the
employed-worker-based middle class.  An entire layer of the econonomy
that was a vital means of class mobility was eliminated leaving ever
more people trapped in a shrinking employed-worker middle class who
could no longer afford to build capital, replacing it with the
appearance of capital by paying rents.

---

But there was always another American Dream, the idea that in America
social mobility was somewhat fluid and it was possible to get rich
quick and move into the tycoon class.  A handful of families achieved
this with names that are as familiar as the furniture in the,
Vanderbilt, Carnegie, Rockefella, Morgan, Mellon and later Kennedy and
Getty who would make it into the same economic situation as the landed
gentry in europe who lived off of their accumulated capital.

In the late 20th and beginning of the 21st centuries, as the
middle-class saw their capital evaporate, three new means of getting
rich quick emerged, which manipulated information in order to build
capital. In each case, the capital was often used for status seeking
instead of long-term multi-generational investment.

The first, property speculation, certainly was nothing new.  But what
was new was that land and buildings were no longer seen as a means to
an end, but an end in themselves.  Buying a home was replaced with
buying a house.  With enough persistence and effort income earned
through employment could be used to buy property, not to live in, but
to sell and make enough money to invest the profits in more property.
In typical Chinese fashion, China has taken this model to an extreme,
with property develops understanding that people were looking to buy
property as an investment rather than as homes. And because of a quirk
in Chinese culture where it is not desirable to buy a house that
someone has lived in before, if you invested in property it could
either be rented out, or it could be sold again, but it would not sell
after it had been lived in. This has resulted in the space of less
than twenty years in the construction of vast ghost cities with whole
forests of 30 floor buildings, all sitting vacant, and all purchased
by the middle class as investments.  Chinese property developers are
now trying to export this business-model to other parts of east and
south-east Asian with mixed results.

The financial sector was the second get-rich-quick avenue.  It became
possible with little more than a Bachelor's degree to get a job in
financial trading companies where it was possible to accrue large
amounts of capital in a relatively short period of time.  The problem
with this model is that in many cases, the capital that was accrued
was not invested or saved, but spent on status seeking, to rent the
appearance of having more capital than you actually had.  This makes
possible a precarious life-style at a very high level, but is never
more than one or two bad trades away from being wiped out.

The third method was a variation on the /land-rush/ or /gold-rush/
model where being the first to enter a market that was reaching a
tipping point and was in the early stages of exponential grown when
the barrier to entry was very low.

[[https://www.youtube.com/watch?v=8-Sn2ZgfVqM][Tumbleweeds]] Cherokee Strip Land Rush scene
https://newsok.com/gallery/2497/pictures/51506

The 21st century incarnation of this was the Dot-Com boom, followed by
the Mobile-App boom.  The pioneers who developed the technology that
became the Internet and Web thought of what they were doing in the
same way that people would buy a home.  But early adopters only saw
the technology as a means to getting rich quickly.

None of three of these methods are sustainable.  First, they are seen
as zeo-sum where one person can not succeed unless someone else
looses.  This is physical true in the case of property speculation as
what is being speculated on is physical and finite.  Only one party
can profit from a single property.  In the case of financial and
technological greed, the finite resource that is fought over is
customers.  That there are a limited number of people you can sell
things to resulting in a hunger games environment where all players
are eliminated until there is only one, holding a monopoly.

---

All types of labor is a kind of capital and in that sense it is a form
of property.  Slavery is the original embodiment of this concept,
where a person is held captive and their labor is the property of the
captor.  The industrial revolution made it clear that there was no
need to hold people captive to own their labor.  It was far cheaper to
leave people free when not working, so that workers are responsible
for finding and maintaining their own food and shelter.  So long as
they maintained conditions where workers had no alternative but to
sell their labor to an employer that in many cases there was no reason
to keep people physically captive indefinitately.

This obviously is still not always the case.  Prison labor is the
slave-model write large.  Large companies, especially as seen today in
East Asia buy industrial giants who house workers, provide banking,
housing, company stores, medical care and education for workers on
company premises.  These are not perks, all of these services must be
paid for by workers from the salaries they receive and those services
are provided to make a profit.

This model was pioneered in the United States in the 19th century as
means of maintaining business models that had previously depended on
traditional slave labor.  The Nation-State system fully supports this
model in the form of restrictive visas that tie a worker to a specific
job or circumstance.  The State even provides runaway slave recapture
services at no cost.  Domestic help, the hospitality industry, farm
and plantations and labor intensive industrial factories all employ
this form of slavery.  In the event that what few rights these workers
have is violated, often in horrific fashion as in rape of domestic
help, and physical violence to others, the workers are deported from
the country before they can seek redress from courts.  This is one
dark side of shiny ultramodern bastions of capitalism such as Hong
Kong and Singapore and throughout the tiny oil-rich countries in the
Middle East.  In the film, /A Hologram for the King/, after the
protagonist observes a number of workers being ill-treated, asks his
driver what the trade-unions have to say about this.  The driver
shrugs and says, "we don't have unions, we have Filipinos."

In all cases, workers are dependent on their employer for day-to-day
existance, they have little to no agency, ability to choose where and
how they live, where they can send their children to school, buy food, 
clothing, etc.

Moral and ethical questions of slavery aside, this is a terrible waste
of cognitive resources.  Properly educated and trained, a human being
is a remarkable combination of general purpose cognition in a highly
flexible and adaptive body that can manipulate and shape the world
around them in remarkably subtle and beautiful ways.  Using a human to
rake leaves, or assemble iPhones is like using a Cray Supercomputer to
sent Tweets.  It will do the job, but it's overkill.

---

This leads us to the next problem.  Why are we wasting all of that
cognitive and motor capacity on repetitive and menial tasks?  To
support a small number of people can dedicate themselves to fully
using all of their cognitive powers.


Most innovation in the sciences, philosophy, engineering, the arts and
so on done by a very small percentage of people who don't have to
worry about physical survival and have the freedom and free time to
devote all of the energies to creative pursuits.  It is these people
that all other human advances stem from.  As Abraham Flexner said in
his 1939 essay, "The Incredible Usefulness of Useless Knowledge,"




#+begin_quote
I recall a conversation which I had some years ago with Mr. George
Eastman on the subject of use. Mr. Eastman, a wise and gentle
farseeing man, gifted with taste in music and art, had been saying to
me that he meant to devote his vast fortune to the promotion of
education in useful subjects. I ventured to ask him whom he regarded
as the most useful worker in science in the world. He replied
instantaneously: “Marconi.” I surprised him by saying, “Whatever
pleasure we derive from the radio or however wireless and the radio
may have added to human life, Marconi’s share was practically
negligible.”

I shall not forget his astonishment on this occasion. He asked me to
explain. I replied to him somewhat as follows: “Mr. Eastman, Marconi
was inevitable. The real credit for everything that has been done in
the field of wireless belongs, as far as such fundamental credit can
be definitely assigned to anyone, to Professor Clerk Maxwell, who in
1865 carried out certain abstruse and remote calculations in the field
of magnetism and electricity. Maxwell reproduced his abstract
equations in a treatise published in 1873. At the next meeting of the
British Association Professor H. S. Smith of Oxford declared that ‘no
mathematician can turn over the pages of these volumes without
realizing that they contain a theory which has already added largely
to the methods and resources of pure mathematics.’ Other discoveries
supplemented Maxwell's theoretical work during the next fifteen
years. Finally in 1887 and 1888 the scientific problem still
remaining—the detection and demonstration of the electromagnetic waves
which are the carriers of wireless signals—was solved by Heinrich
Hertz, a worker in Helmholtz’s laboratory in Berlin. Neither Maxwell
nor Hertz had any concern about the utility of their work; no such
thought ever entered their minds. They had no practical objective. The
inventor in the legal sense was of course Marconi, but what did
Marconi invent? Merely the last technical detail, mainly the now
obsolete receiving device called coherer, almost universally
discarded.”

Hertz and Maxwell could invent nothing, but it was their useless
theoretical work which was seized upon by a clever technician and
which has created new means for communication, utility, and amusement
by which men whose merits are relatively slight have obtained fame and
earned millions. Who were the useful men? Not Marconi, but Clerk
Maxwell and Heinrich Hertz. Hertz and Maxwell were geniuses without
thought of use. Marconi was a clever inventor with no thought but use.

— Abraham Flexner, The Usefulness of Useless Knowledge (1939)
  cite:flexner:1939usefulness
#+end_quote

Looking back at great intellectual and scientific advances throughout
human history, the vast majority of them were directly or indirectly
possible by accumulating capital through labor as property.

The classical Greek thinkers all had free time because of their social
position as elites who owned property and slaves.


Darwin lived off capital from his family and a dowery from his wife's
family.  Marx and later Einstein were exception, who had to scrape
through on little or nothing through the early parts of their careers
but eventually were supported by the labor as capital regieme.
Einstein found a home in his later years at the Center for Advanced
Study in Princeton New Jersey, an institution founded by fortunes from
19th century tycoons and robber barons.

Robber Barons especially like to endow great public works, all wishing
they they be remembered for their philanthropy than the ruthlesses and
swaths of carnage left behind as they built their fortunes.  Carnegie,
Mellon, Rockafella and most recently Bill Gates all took the
philanthropic route, as if they were buy indulgences to buy their way
into heaven for their sins.  Refreshingly, a few went to their graves
unrepentent and proud of their achievements, J Paul Getty and Steve
Jobs both come to mind.  The Getty name, now famous for the foundation
and art museum bearing his name, had nothing to do with Paul, who must
be turning over in his grave every time the foundation funded by his
wealth does anything that doesn't make a profit.  Getty was so cheap,
that he kept a public pay-telephone booth in his caverous mansion so
that he wouldn't have to pay for guest's telephone calls.  At least
his butler made change for free.  In the case of Jobs it's clear that
he believed that his fortune was built making the world a better
place, rather than by turning the power and flexibility of general
purpose personal computers into kitschy over-priced consumer
life-style appliances that lock users in his idea of how people should
think and create.

Many of the great painters had wealthy, patrons from industry, state
or church including Michelangelo, DeVinci etc.  Others like Piccaso
made fortunes selling art to the wealthy.  This is far from being a
hard and fast rule. There are countless exceptions from Edvard Munck,
and Van Gogh.  Philip K. Dick spent all but the last few years of his
life made a precarious livelihood selling a steady stream of work for
pulp magazine and paperback markets.  James Joyce lived an even more
precarious life off bits from friends and family.  

Most great intellectual achievements are roads that lead back to
accumulated capital and slavery in some incarnation and it all boils
down to the fact that creative and intellectual works need large
periods of time, often years and decades of study, contemplation and
relentless grinding dedication to work without having to worry about
where their next meal would come.

Virginia Woolfe laid this out clearly in "A Room of One's Own"

#+begin_quote
As I leant against the wall the University indeed seemed a sanctuary
in which are preserved rare types which would soon be obsolete if left
to fight for existence on the pavement of the Strand. Old stories of
old deans and old dons came back to mind, but before I had summoned up
courage to whistle – it used to be said that at the sound of a whistle
old Professor — instantly broke into a gallop – the venerable
congregation had gone inside. The outside of the chapel remained. As
you know, its high domes and pinnacles can be seen, like a
sailing-ship always voyaging never arriving, lit up at night and
visible for miles, far away across the hills. Once, presumably, this
quadrangle with its smooth lawns, its massive buildings, and the
chapel itself was marsh too, where the grasses waved and the swine
rootled. Teams of horses and oxen, I thought, must have hauled the
stone in wagons from far counties, and then with infinite labour the
grey blocks in whose shade I was now standing were poised in order one
on top of another, and then the painters brought their glass for the
windows and the masons were busy for centuries up on that roof with
putty and cement, spade and trowel. Every Saturday somebody must have
poured gold and silver out of a leathern purse into their ancient
fists, for they had their beer and skittles presumably of an
evening. An unending stream of gold and silver, I thought, must have
flowed into this court perpetually to keep the stones coming and the
masons working; to level, to ditch, to dig, and to drain. But it was
then the age of faith, and money was poured liberally to set these
stones on a deep foundation, and when the stones were raised, still
more money was poured in from the coffers of kings and queens and
great nobles to ensure that hymns should be sung here and scholars
taught. Lands were granted; tithes were paid. And when the age of
faith was over and the age of reason had come, still the same flow of
gold and silver went on; fellowships were founded; lectureships
endowed; only the gold and silver flowed now, not from the coffers of
the king, but from the chests of merchants and manufacturers, from the
purses of men who had made, say, a fortune from industry, and
returned, in their wills, a bounteous share of it to endow more
chairs, more lectureships, more fellowships in the university where
they had learnt their craft. Hence the libraries and laboratories; the
observatories; the splendid equipment of costly and delicate
instruments which now stands on glass shelves, where centuries ago the
grasses waved and the swine rootled. Certainly, as I strolled round
the court, the foundation of gold and silver seemed deep enough; the
pavement laid solidly over the wild grasses. Men with trays on their
heads went busily from staircase to staircase. Gaudy blossoms flowered
in window-boxes. The strains of the gramophone blared out from the
rooms within.

— Virginia Woolfe, A Room of One's Own
  cite:woolf:2004room

#+end_quote

#+begin_quote
And one gathers from this enormous modern literature of confession and
self-analysis that to write a work of genius is almost always a feat
of prodigious difficulty. Everything is against the likelihood that it
will come from the writer’s mind whole and entire. Generally material
circumstances are against it. Dogs will bark; people will interrupt;
money must be made; health will break down. Further, accentuating all
these difficulties and making them harder to bear is the world’s
notorious indifference. It does not ask people to write poems and
novels and histories; it does not need them. It does not care whether
Flaubert finds the right word or whether Carlyle scrupulously verifies
this or that fact. Naturally, it will not pay for what it does not
want.

— Virginia Woolfe, A Room of One's Own
  cite:woolf:2004room
#+end_quote

#+begin_quote
The slave was precious to his master because of the money he had cost
him ... They were worth at least as much as they could be sold for in
the market ... It is the impossibility of living by any other means
that compels our farm labourers to till the soil whose fruits they
will not eat and our masons to construct buildings in which they will
not live ... It is want that compels them to go down on their knees to
the rich man in order to get from him permission to enrich him
... what effective gain [has] the suppression of slavery brought [him
?] He is free, you say. Ah! That is his misfortune ... These men
... [have] the most terrible, the most imperious of masters, that is,
need. ... They must therefore find someone to hire them, or die of
hunger. Is that to be free?

— Linguet, Théorie des lois civiles, etc., Londres, 1767.
  Quoted In Karl Marx, Theories of Surplus Value, 1861
  https://www.marxists.org/archive/marx/works/1863/theories-surplus-value/ch07.htm
  cite:marx:1968surplus-value
#+end_quote

#+begin_quote
Next I think that you may object that in all this I have
made too much of the importance of material things. Even
allowing a generous margin for symbolism, that five hundred
a year stands for the power to contemplate, that a lock on
the door means the power to think for oneself, still you may
say that the mind should rise above such things; and that
great poets have often been poor men. Let me then quote to
you the words of your own Professor of Literature, who knows
better than I do what goes to the making of a poet. Sir
Arthur Quiller-Couch writes


   What are the great poetical names of the last hundred
   years or so? Coleridge, Wordsworth, Byron, Shelley,
   Landor, Keats, Tennyson, Browning, Arnold, Morris,
   Rossetti, Swinburne – we may stop there. Of these, all
   but Keats, Browning, Rossetti were University men; and of
   these three, Keats, who died young, cut off in his prime,
   was the only one not fairly well-to-do. It may seem a
   brutal thing to say, and it is a sad thing to say: but,
   as a matter of hard fact, the theory that poetical genius
   bloweth where it listeth, and equally in poor and rich,
   holds little truth. As a matter of hard fact, nine out of
   those twelve were University men: which means that
   somehow or other they procured the means to get the best
   education England can give. As a matter of hard fact, of
   the remaining three you know that Browning was
   well-to-do, and I challenge you that, if he had not been
   well-to-do, he would no more have attained to write Saul
   or The Ring and the Book than Ruskin would have attained
   to writing Modern Painters if his father had not dealt
   prosperously in business. Rossetti had a small private
   income; and, moreover, he painted. There remains but
   Keats; whom Atropos slew young, as she slew John Clare in
   a mad-house, and James Thomson by the laudanum he took to
   drug disappointment. These are dreadful facts, but let us
   face them. It is – however dishonouring to us as a nation
   – certain that, by some fault in our commonwealth, the
   poor poet has not in these days, nor has had for two
   hundred years, a dog’s chance. Believe me – and I have
   spent a great part of ten years in watching some three
   hundred and twenty elementary schools – we may prate of
   democracy, but actually, a poor child in England has
   little more hope than had the son of an Athenian slave to
   be emancipated into that intellectual freedom of which
   great writings are born.cite:quiller-couch:1916art-writing

— A room of one's own
  cite:woolf:2004room
#+end_quote


---

Machine-cog is a form of labor which is also a form of
property.

If machine-cog can work efficiently at small scales, then
the possibility of a new middle class emerging, who builds
up capital they can live on by leveraging machine-labour
rather than land as property and buildings as property or
the accumulation of invested currency in the form of stocks,
bonds and other financial instuments.

---

Think of it this way.  Instead of thinking of wealth as
accumulated property, think of it sort of like the way we
calculate the power of an engine, in horse power, or how
many horses would it take to achieve the same amount of work
as a particular engine.

Machine cognition doesn't replace horses it replaces
thinking people doing repetitive and menial tasks that
require relatively low amounts of cognition.  Since this
works out to be a many as two-thirds of jobs, then is stands
to reason that minimum one person working together with
machine-cog systems will be able to do the same work as
several people can today.

How many will that actually be?  It's not as simple as
dividing the number of people who have lost jobs among the
ones with jobs.

In some cases, as in the case of heavy industry there are
now factories in Europe run less than a dozen people who
have replaced 150 workers.  In many cases, entire classes of
employment will simply be swallowed by network services.  So
it is difficult to work up from jobs being replaced to
number of people that a person working with machine-cog will
have.  Let's call it jobpower.  These are such early days
that it's almost a meaningless question to ask.  We simply
don't know at this point in time.  There is no data.

But we can think about how many jobpower it takes to
generate enough capital for a person, and their family, to
accumulate enough capital to live off of that capital, while
coordinating a human-machine-cog system.

We have numbers for that, I need to do a lot more thinking
and study and research to work out those numbers and what
the mean, so for now I need a back-of-napkin model to see if
this might work out....

Our goal is for each working person to be as productive as
xx number of people in order to generate the equivilent of
$40K/year from capital created by that labor.  I want that
to be the base minimum income.  But that's basically only
cash -- in addition everyone owns their own house and
property they live on, debt-free, and that 60% of food and
energy will be grown/generated on-premise in non-urban
settings.  I still have to work out how this will work in
highly oncentrated urban environments.

The number I pulled out of thin air before was around 20
jobpower -- put another way, if you had twenty slaves that
didn't have to be paid, how much capital would be generated
by their labor?  Instead of feeding and housing slaves,
you'd be paying for energy to run the machine-cog systems
and maintain them and replace them periodically.  If we take
a different approach to manufacturing so that everything is
designed to last decades, and to be repairable and
upgradable, the fixed upfront costs could be spread over
10-20 years.

It could be as simple as simply adding up the those of those
people in terms of wages and benifits -- but of course it
won't be.

At the low end and labor is minimum wage, twenty people at
say $15 an hour is about $30k * 20 = $600K  even you gave
yourself $100K in salary and benifits from that, you'd still
have $500K a year of capital added to your hoard each year.

If we then pool about 15 people together into a couple of
shops that shares land, houses and fixed costs for running
those shops you would be generating as a group perhaps as
much as $10M/Yr in capital.  If that capital is invested
into making new shop-clusters, who in turn do the same, you
are adding value to your shop because the value-chains
becomes more valuable with every new node added to the
network.

The system will be designed so that for every person that is
working, another 10 non-working people will be supported at
large.

The goals of production is not to maximize profit but to
meet the maximum amount of human needs.  Salaries for those
working are capped at what Piketty suggests -- $500K/Yr and
anything above that is taxed at %80.

Piketty shows that the present system, when working properly
always results in low-growth and massive inequality, that
keeps most people poor.  If we aren't careful, the
machine-cog revolution will just be more of the same if we
let those in power now try to repress the system becoming
distributed, which it will naturally do.

So my gut feeling at the moment is that this model could
work if -- IF -- we can make production and supply chains
highly distributed, and that automation will make these
systems competitive with large scale production which I
think is possible.

** References

  - Piketty, T., & Goldhammer, A., Capital in the twenty-first century
    (2014), : Belknap Press.
    cite:piketty:2014capital-twenty-first
  - Woolf, V., A room of one's own (2004), : Penguin Books.
    cite:woolf:2004room
  - Marx, K., Theories of surplus value (1968), : Progress Publishers.
    cite:marx:1968surplus-value
