#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Automation Economics 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Automation Economics
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/foundations/auto-eco.org
  :Created:   2018-06-29T07:35@Prek Leap (11.642600N-104.919210W)
  :ID:        b5013e60-12aa-48c9-882e-09930b952015
  :VER:       583504571.109998387
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:TBU8-1758
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope
** TL;DR

A Capitalist is literally someone who lives off of the growth of
capital as opposed to laborers who live off of their labor.  Another
term for a capitalist is an older word, rentier, someone who lives off
of rents and fees paid for use of someone elses capital.

In good times, spent one third of their income or less on rents in
the form of taxes to the state, rents paid for living quarters, or in
the form of loans and mortgages on borrowed capital for the purchase
of things like houses and automobiles.  In the late 20th century in
developed countries this started to change and a larger and larger
percentage of income began going to rents.  New types of rents
appeared for use of networks -- cable television and cell phone
networks.  Amazon Prime is effectively a rent as well -- and don't be
fooled, in time most people will feel as locked into paying their
Amazon Prime rent as they do their cable, and cell rents.

The higher percentage of rents you pay, the less control you have over
your life -- the more you can build up capital and live off that
capital the more control and agency you will have.  I believe that a
lot of the unease and desperation that middle class in advanced
economies feel is this loss of agency which their parents or
grandparents had some measure of.  This always was the demarcation
between the working and middle class, the working class lived
pay-check to pay-check, the middle-class spent their working life
building up a small amount of capital which could be used for
retirement.  Blue-collar factory work had, for a short time after
World War II when labor unions held-sway provided a version of this.
Workers were paid enough to accrue capital that was spent on educating
children, purchase of a house and saving for retirement.  This
encapsulates the so-called Post-War "American Dream."

The rise of nation-wide and global retail chain stores neatly wiped
out a large part of the merchant class who built up small and medium
sized shops, services and restaurants that was the model for the
employed-worker-based middle class.  An entire layer of the econonomy
that was a vital means of class mobility was eliminated leaving ever
more people trapped in a shrinking employed-worker middle class who
could no longer afford to build capital, replacing it with the
appearance of capital by paying rents.

But there was always another American Dream, the idea that in America
social mobility was somewhat fluid and it was possible to get rich
quick and move into the tycoon class.  A handful of families achieved
this with names that are as familiar as the furniture in the,
Vanderbilt, Carnegie, Rockefella, Morgan, Mellon and later Kennedy and
Getty who would make it into the same economic situation as the landed
gentry in europe who lived off of their accumulated capital.

In the late 20th and beginning of the 21st centuries, as the
middle-class saw their capital evaporate, three new means of getting
rich quick emerged, which manipulated information in order build capital.

The first, property speculation, certainly was nothing new.  But what
was new was that land and buildings were no longer seen as a means to
an end, but an end in themselves.  Buying a home was replaced with
buying a house.  With enough persistence and effort income earned
through employment could be used to buy property, not to live in, but
to sell and make enough money to invest the profits in more property.
In typical Chinese fashion, China has taken this model to an extreme,
with property develops understanding that people were looking to buy
property as an investment rather than as homes. And because of a quirk
in Chinese culture where it is not desirable to buy a house that
someone has lived in before, if you invested in property it could
either be rented out, or it could be sold again, but it would not sell
after it had been lived in. This has resulted in the space of less
than twenty years in the construction of vast ghost cities with whole
forests of 30 floor buildings, all sitting vacant, and all purchased
by the middle class as investments.  Chinese property developers are
now trying to export this business-model to other parts of east and
south-east Asian with mixed results.

The financial sector was the second get-rich-quick avenue.  It became
possible with little more than a Bachelor's degree to get a job in
financial trading companies where it was possible to accrue large
amounts of capital in a relatively short period of time.  The problem
with this model is that in many cases, the capital that was accrued
was not invested or saved, but spent on status seeking, to rent the
appearance of having more capital than you actually had.  This makes
possible a precarious life-style at a very high level, but is never
more than one or two bad trades away from being wiped out.


Labor and employment is, in itself, a kind of capital and in that
sense it is a form of slavery, where a person's labor is owned by
another and treated as a form of property.

Machine-cog is a form of labor which is also a form of property.

If machine-cog can work efficiently at small scales, then the
possibility of a new middle class emerging, who builds up capital they
can live on by leveraging machine-labour rather than land as property
and buildings as property or the accumulation of invested currency in
the form of stocks, bonds and other financial tools.q

** References

  - Piketty, T., & Goldhammer, A., Capital in the twenty-first century
    (2014), : Belknap Press.
    cite:piketty:2014capital-twenty-first
