#   -*- mode: org; fill-column: 60 -*-

#+TITLE: I. Foundations Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] [[[./index.org][up]]] 

#+begin_quote
Let me pick up by way of the polis.  Socrates put it sharply
when he explained his choice of suicide over exile to his
afflicted friends; he pointed out that in his suicide,
Athens committed suicide.  And we don't need the history of
Athens to know he was right.  He was right (and could not
choose exile) because he had rested his case throughout his
life on the identity of the citizen with the polis.  This is
the truism, that the polis disappeared, but another
possibility as been left out, that what we are dealing with
is not its loss but a change in its size (and the omission
of this possibility has played increasing hob with the
individual & society since the 18th Century at least).
Socrates could circle Athens every day, he could speak for
man because he could know all the men that mattered in the
polis concept, yr own fellow city citizens.  In other words,
the organism of society was actually knowable daily to the
organism which also mattered, the individual.  Literally.

The question, now is: what is our polis (even allowing that
no such thing can be considered as possible to exist when
such homogeneity as any Greek city was has been displaced by
such heterogenity as modern cities and nations are)?  It is
a point worth making, simply that it will expose the
thinking of all community, cooperative, colony people, as
well as false premises by which the present political-social
System imposes itself on all of us.  I ask what polis we
have other than the very whole world?  It is true we each
have extrications from it, suburbs of birth or jobs or
passport rights or cultural allegiances etc. But in the
actual fact of the reality of a society as society now bears
on us, is it at all a bit smaller than the whole damn thing?

— Charles Olson, Totality: The Methodology Is the Form (1952)
  Intent, Vol.1 No.1, Spring 1989.
  cite:olson:1989methodology-form
#+end_quote

#+begin_quote
Thinking as a planet is what climate change is forcing us to
do; thinking as /a/ civilization rather than just a society
or a nation but as a civilization. People in this century
get to live in a century where humanity discovers itself as
the keeper of life now on the whole planet.  What an amazing
realization, what an amazing job, what an amazing thing to
work out how that actually works.  But all the tools are
already in place to do that.  To make it Earth Natural Park
in the city you want to live in and a society that continues
to become ever more amazing from year to year and decade to
decade in a non-destructive way.  That's going to happen in
this century.

— Stewart Brand, Interview 2018
  cite:brand:2018interview
#+end_quote




* I. Foundations Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-intro-vol-1.org
:Created:  2018-04-11T18:19@Prek Leap (11.642600N-104.919210W)
:ID:       bef42709-757a-4e2e-873c-41175c9c456a
:VER:      576717614.262601171
:GEO:      48P-491193-1287029-15
:BXID:     proj:DIM5-7235
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Introduction

These bones of civilization, of thresholds crossed, of
collapses half forgotten, of the stale boredom of
stagnation, of ashes melting into the soil with the first
rains of the season that fuel both rebirth and renaissance,
even as we forget where the bodies are buried that just leads
to more bodies that need burying.

There is no getting around learning things the hard way.  No
short-cuts.  Each generation must learn the same damn things
again for themselves.  Our species is a bone-headed lot that
has to chew through everything anew, making the same
mistakes afresh before taking even a single step forward,
only to pass the torch to the next generation which promptly
takes two step back.

The news is actually good, but it's beyond our ability to
believe it.  A monograph here, a slide-deck there, the
numbers are clean and clear and show what is really
happening but we continue to wallow in the muck and stench
of that narrow bandwidth of human scale. That good news
falls outside the teetering stack of cognitive biases that
make us what we are, warts and all.

Life during a revolution is still life.  We still wake up in
the morning, shrug on some clothes, stumble to the toilet to
take a piss before putting on the kettle, all without a
thought in our heads.  We seldom notice the ground shifting
beneath our feet, too slowly to break routine, and even when
we do, it barely registers,  discarded as outliers that
muddy the curve.

It's all happening faster now, and yet we persist in not
seeing what is squating fat and fiercely in front of us.
Which brings us back to the bones and wny it's so important
to get them right.  Push through the fog of the familiar,
strip down everything so that nothing is left but bleached
white calcium ground to powder, dissolved into solution and
used to grow something stronger, braver and more resilient.



----
We all have to learn some things the hard way, both as
individuals and as societies.  You learn to avoid direct
contact with a flame by getting burned.  Some things we
need to experience in order for some lessons to become
registered in our limbic system.  This is especially true
for the young.  But existential mistakes that result in
systemic failure and even collapse of civilizations should
not be something anyone needs to repeat.  And over the long
term, Mankind is getting better at not repeating those kinds
of mistakes.  War has been in steady decline since the end
of WWII.  We don't murder each other as much, and states
aren't murdering their own people for minor offences as
much.  There is still a long ways to go, but we're generally
headed in the right direction.

We should be concerned that the dizzying acceleration of the
rate of change as the global population will top out at
nearly 10 billion before beginning to decline.  The rate of
change increases in lockstep with rises in population.
Adding more parts to a system makes it more complex, more
chaotic.  But each person added to the population also
increases the number of people who put our large cerebral
cortext to good use to innovate and solve problems.  The
more people we can dedicate to solving problems, the faster
things will change.  But also, the faster that things will
improve in the aggregate over time.

That increasing rate of change gives us less time to absorb
and acclimate to what has changed, there is less time to
observe, experiment and contemplate options before we are
forcecd to take action.  The increase in the number of
people innovating offsets this to some extend, but it's
still not clear if it compensates enough for man to solve
the potentially existential problems that face us over the
next fity to a hundred years.

For these reasons it makes sense to occasionally take a long
hard look at principles and assumptions that we are building
civilization on top of.  

Then what do we mean by first principles? In a word, it is
what Paul Graham called, when describing the design of the
programming laguage Arc, that theree would be "no onions in
the varnish":

#+begin_quote
In /The Periodic Table/,[fn:1] Primo Levi tells a story that
happened when he was working in a varnish factory. He was a
chemist, and he was fascinated by the fact that the varnish
recipe included a raw onion. What could it be for? No one
knew; it was just part of the recipe. So he investigated,
and eventually discovered that they had started throwing the
onion in years ago to test the temperature of the varnish:
if it was hot enough, the onion would fry.

We're going to try not to include any onions in Arc.

— [[http://www.paulgraham.com/arcll1.html][Arc at 3 Weeks]] | Paul Graham, 2001
#+end_quote

This is not meant to discard the past, as much as ensure
that what is included from the past is fully understood and
has a purpose that is no longer have any meaning or use.
We can accuse many things in traditional cultures of being
onions, and this has been used as an excuse to toss out
everything and begin clean, /tabla rasa/  This is not our
intention at all.  There are very good reasons for many
traditions and rituals that have been carried
down the centuries and millennia to the present.  Many of
these practices connect ground us in a shared cultural
narrative that grounds us, and connects us to the land and
to each other.  It's important that these things are not
lost.  However there are many onions that should be at least
understood if they are to be retained, and discard them if
they do more harm than good.

The practice in the sciences of starting from first
principles is that many times we are led down false paths
from the initial assumptions that they are based on.  For
this reason we must ensure that the civilization we build is
on a solid rational and empirical foundation.

#+begin_quote
A sound house needs a firm foundation, a good roof, and
tight walls.  No amount of rennovation will compensate for a
crumbling foundation.  It makes absolutely no sense to
remodel the interior of a house without first making sure
that the house stands on solid ground....

Structural work is the starting pint of a logical chain.
For example, changing the foundation will affect any work
done inside the house.  Wall finishes will crack, doors and
windows will stick or skew open, partitions and loors will
go out of level and plumb.  Also, structural work frequently
results in the exposure of the vitals of the house to the
elements....

[A] psychological factor... must never be underestimated. An
unwholesome amount of drudge labor and great sums of money
can be poured into a mud-filled fondation hole.  When the
job is finished and the hole is backfilled after weeks of
had work, nothing has visibly changed.  Of course you have
the satisfaction of knowing that at least your house will
stand safely and that whatever else you do rests on a firm
footing.  But it isn't /dramatic/ enough.

— Old Houses: A Rebuilder's Manual | George Nash
  cite:nash:1980old-houses p.24-25
#+end_quote

This is challange that Warp & Woof takes up, to have put in
the "drudge labor" needed to set things on a solid footing.
If at times as you labor through these seemingly
interminable six volumes that it will never end, imagine the
effort it took to put this together.  But just as you can't
rebuild an old house without replacing a rottom foundation,
we must take stock of our civilization an its foundations
and ensure that they are placed on a strong and durable
footing.

** References

  - Levi, P., The Periodic Table (1995), : Schocken.
    cite:levi:1995periodic-table
  - Nash, G., Old houses, a rebuilder's manual (1980), :
    Prentice Hall Direct. p.24-25
    cite:nash:1980old-houses 


* Footnotes

[fn:1] "I started to tell the story of the onion in the
boiled linseed oil. This, in fact, was a dining room for a
company of varnish manufacturers, and it is well known that
boiled linseed oil has for many centuries constituted the
fundamental raw material of our art. It is an ancient art
and therefore noble: its most remote testimony is in Genesis
6:14, where it is told how, in conformity with a precise
specification of the Almighty, Noah coated (probably with a
brush) the Ark’s interior and exterior with melted
pitch. But it is also a subtly fraudulent art, like that
which aims at concealing the substratum by conferring on it
the color and appearance of what it is not: from this point
of view it is related to cosmetics and adornment, which are
equally ambiguous and almost equally ancient arts (Isaiah
3:16). Given therefore its pluri-millenial origins, it is
not so strange that the trade of manufacturing varnishes
retains in its crannies (despite the innumerable
solicitations it modernly receives from kindred techniques)
rudiments of customs and procedures abandoned for a long
time now.  So, returning to boiled linseed oil, I told my
companions at table that in a prescription book published
about 1942 I had found the advice to introduce into the oil,
toward the end of the boiling, two slices of onion, without
any comment on the purpose of this curious additive. I had
spoken about it in 1949 with Signor Giacomasso Olindo, my
predecessor and teacher, who was then more than seventy and
had been making varnishes for fifty years, and he, smiling
benevolently behind his thick white mustache, had explained
to me that in actual fact, when he was young and boiled the
oil personally, thermometers had not yet come into use: one
judged the temperature of the batch by observing the smoke,
or spitting into it, or, more efficiently, immersing a slice
of onion in the oil on the point of a skewer; when the onion
began to fry, the boiling was finished.  Evidently, with the
passing of the years, what had been a crude measuring
operation had lost its significance and was transformed into
a mysterious and magical practice.

— Levi, P., The Periodic Table (1995), : Schocken.
  cite:levi:1995periodic-table

