#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Fifty Year Window 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Fifty Year Window
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/foundations/window.org
  :Created:   2018-06-28T16:42@Prek Leap (11.642600N-104.919210W)
  :ID:        0cc73277-4ef7-4f4d-979b-6309e2288fe3
  :VER:       583451030.079521578
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:QIB6-0265
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope
** TL;DR

Population

Population will top out at 10B -- but that still means we need food,
energy, shelter etc for 3-4 Billion people that we have today while
still working to raise the standard of living for the billions at the
bottom that are alive today.  This is not optional, the faster we
raise the standard of living the faster population will go down.

There isn't any reason to believe that Man will get it's act together
on climate change before some really bad things happen.  The United
States appears intent to embark on a slide into authoritarianism and
possibly civil war that likely trigger a world resession, and other
civil wars sprinkled around the planet.  So assume that the World
Economy will be chaotic over the next 10-20 years.

Climate change will not be stopped in time for sea-level rises of
8M/YK which will result in at least a 40 meter rise in sea levels over
xxx years.  We will soon have to come to terms with that and prepare
for such a scenario -- fully a quarter of the world's populations will
be underwater in less than a century.  But that is just the
beginning.  It could be a LOT worse, as in the P–T extinction event
that saw the loss of 96% of marine species, 70% of vertebrates and at
least eight or nine orders of insect species vanishing.  We will not
survive on this planet through such an event.  However, a two hundred
year plan to first get carbon emmisions down to pre-industrial levels
and then a prolonged carbon capture effort to reduce atmospheric
carbon to pre-industrial levels could at least make it possible to
avoid a human-causes P–T scale extinction.

Machine-cog will result in 60% job loss over the next 20 years (or
less), cutting off the entry-level industrial jobs that developing
economies need to move up the economic ladder.  We have to ensure that
there  is a way up the ladder for these people or the present problems
we have with mass migration will, along with dislocation from climate
change could well be catastrophic.  And remember, if we can't raise
people's standard of living, then population growth will return to
rates we haven't seen since the 1970's.  

Machine-cog will result, at least initially, in breaking up existing
centralized power structures and moving power to the edges.  It will
transform logistics and supply chains allowing them to work as
efficiently at small scales as the present system that uses the ISO 40'
modal shipping container as the base unit.

Machine-cog will disrupt all aspects of civilization from the nature
and organization of families, the structure of States, it will
threaten and likely be the end of the Nation-State system to be
replaced by a world-order where cities become the base political unit.

During this period we will see a cotinuation of populism, nationalism,
extremism and authoritarian regimes.  All such manifestations maximize
destruction and destabilization and as such will not last long.  But
the damage done will be at least as large as WWII.  Plan for two
decades for things to fall apart before people are able to start
picking up the pieces.  By then, most of the people who caused all of
this, who are now in power but will soon be too old and start to die
off, or get diluted -- these are the people desperate to hold on to
the existing and imagined past world-order.

Rise of space-based industry and eventually permanent settlements on
moon, mars and in habitats in asteroids.  Most heavy industry will
move into space where resources are for practical puposes infinite at
human scales, and automation will do all of this without humans
needing to be much in the loop.

Genetic engineering will mature and allow Man full control over
shaping and creating life.

Life-extension -- it's expected that within 20 years that most causes
of aging and disease will be curable ad reversible.  Once this becomes
available to the middle-class it will dramatically change population
growth models.  It's impossible to know how this will play out.

** References


