#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Succecssion Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[.;/index.org][up]]]

* Succecssion Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/05/10/intro.org
:Created:  2018-05-03T09:38@Prek Leap (11.642600N-104.919210W)
:ID:       d0bcd51e-826f-44e0-bc74-3a13e011fb02
:VER:      578587164.589052977
:GEO:      48P-491193-1287029-15
:BXID:     proj:TJM8-4540
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR

We have already introduced the Successon Model, as one of
our core Scaffolds but it's important to start introducing
some example Succession implementations that could be used in
building civilizations.

The succession models here are very much first drafts and
will change radically as we learn more and work continues.

The examples used here are NOT normative.  Succession models
will be defined as Succession Patterns in APPL which will be
adapted for use in Hoards to generate Primers.

This Part is meant to be a practicum in taking the
principles and sructures that we have explored thus far and
see how they can be used to create actual Succession models
that could be deployed.

As the Succession Patterns are developed and changed, these
examples will be updated as well.  Please refer to the
succession patterns in the latest version of APPL 
** References

  - Smith, S., & Mark, S., The historical roots of the
    nature conservancy in the northwest indiana/chicagoland
    region: from science to preservation, South Shore
    Journal, 3(), (2009).
    cite:smith:2009historical
  - Walker, L. R., & Moral, R. d., Primary succession and
    ecosystem rehabilitation (2003), : Cambridge University
    Press.
    cite:walker:2003primary-succession 
  - West, D. C., Shugart, H. H., Botkin, D. B., Darrell
    C. West, H. H. S., & Botkin, D. B., Forest succession:
    concepts and application (1981), : Springer-Verlag New
    York.
    cite:west:1981forest-succession 

  - Kelly, K., The inevitable: understanding the 12
    technological forces that will shape our future
    (2016), : Viking.
    cite:kelly:2016inevitable 




