#   -*- mode: org; fill-column: 60 -*-

#+TITLE: The Way Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* The Way Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/04/26/intro.org
:Created:  2018-05-03T10:05@Prek Leap (11.642600N-104.919210W)
:ID:       0e582b40-a5c7-4810-b60c-f0304c5ec6aa
:VER:      578588800.584477263
:GEO:      48P-491193-1287029-15
:BXID:     proj:NSJ2-0620
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR

When you watch a bird build a nest, the entire process seems
random at first.  The bird will pick up twigs almost at
random, drop them then pick up another and take flight to a
branching in a tree.  It will consider the tree and move
it's head this way and that, as if checking to see if the
twig in its beak, is a match for the branch in the tree.
Often the answer is no, and the trig is dropped and the
process strarts again, with another twig and another
branching of another tree.  But eventally something feels
right and the bird places the twig in the branch and returns
with another.  Sometimes rearranging the twigs a bit,
someone times just seeming to drop them in at random.  But
in each case the bird doesn't have any preconcieved notion
of what the nest will look like, what the other birds will
think if it other than, if it's a male, building a nest to
attract a female if it feels right or not.  Is this
something that a female would find impressive or not.  But
it's a gut feeling, there is no plan, there is no design --
just a step by step process of aggregation and adjustment
until it feels right.

This, is what The Way is all about, it's a process of
fulfilling a need by instinct, not as a rational goal driven
process with an invisioned future outcome that will satisfy
all sorts of other goals that will determine your
reputation, how much you will be rewarded or how you hope
others will percieve you.  It's taking the ego out of the
process and just aggregating a series of steps, each of
which feels right and makes what you are building stronger
or more beautiful or just leaves you with a feeling content
and at peace.

This is why we separate the Way from the process of
fabrication -- beause unlike birds, we have to use abstract
and very concrete methodologies to ensure that a roof won't
cave in under the load of a heavy snow, or blow off during a
Typhoon, or collapse during an earthquake.  We need to
ensure that our software does what the user intends it to
do, add up a column of numbers correctly, show you the next
screen of text that the link pointed to.  All of these
things are deterministic and based on many generations of
other engineers learning throgh trial and error, and
countless experiements and failures.  Either the wall will
bear the load you put on it or not, there is no feeling
about that, it's binary -- it does or does not, as Master
Yoda would say, there is no try.

And yet, if we ignore our instinctual understanding of what
feels right and what is right and leave that out of the
process, then we get the software, design and structures
that we've been getting since the industrial revolution
literally picked up a full head of steam.  We are then what
we build is determined by things that the tools we use and
the production processes that are geared for maximum
efficiency in terms of material use and production.  In
modern times this has been a large part of the estrangement
that we experience from ourselves as we are cut off from
what we know instinctually feels right, and makes it
impossible to connect you we are from other people and the
natural environment that we live in.

The challenge is to bring the two together, the natural
aggregation and rearrangement of the bird, married with the
metis, the practical knowledge of how to build things within
the constraints that classical physics places on us.

---

Like in TWB's part of the same name, The Way describes how
to put everything together from the first six Parts as a way
of parsing the world, and putting what you have learned
together to understand things, to build and maintain complex
societies, build structures and settlements, protect and
shepard ecosystems, industrial production, build software
and networks and not least, live a Good Life.

The thing is, that there is no one methodology to
this. That's hard, but W&W is a generative grammer and
toolkit for creating methodologies for building and using
pattern languages to build and use Primers.

you can use w&w to build any number of methodologies -- so
long as you are aware that they are living processes that
are not set in stone -- they must designed to adapt to
changes, to encourage experimentation and careful adoption
of what is found to work.  They are not to be chiseled in
stone or codified or turned into dogma -- like Pirate Law,
in /Pirates of the Caribbean/, they are more guidelines than
laws.

---

Build iteratively bottom up, understand and manage top down.

No beginning or end, start anywhere, create infrastructure
between nodes and grow until everything is connected.


** References

 - Alexander, C., The timeless way of building (1979), :
   Oxford University Press.
   cite:alexander:1979timeless
 - McHarg, I., Design with nature (1969), : Doubleday.
   cite:mcharg:1969design
 - Alexander, C., Neis, H. J., & Alexander, M. M., The
   battle for the life and beauty of the earth: a struggle
   between two world-systems (2012), : Oxford University
   Press.
   cite:alexander:2012battle
 - Alexander, C., Ishikawa, S., & Silverstein, M., A pattern
   language: towns, buildings, construction (1977), : Oxford
   University Press.
   cite:alexander:1977pattern
 - Alexander, C., The oregon experiment (1975), : Oxford
   University Press.
   cite:alexander:1975oregon
 - Alexander, C., & Mumford, L., A city is not a tree, In ,
   Architectural forum (pp. 58–62) (1965). : .
   cite:alexander:1965city
 - Alexander, C., Notes on the synthesis of form (1964), :
   Harvard University Press.
   cite:alexander:1964notes
 - Alexander, C., Neis, H. J., & Alexander, M. M., The
   battle for the life and beauty of the earth: a struggle
   between two world-systems (2012), : Oxford University
   Press.
   cite:alexander:2012battle
 - Alexander, C., A vision of a living world: the nature of
   order, book 3: an essay on the art of building and the
   nature of the universe (the nature of order) (2004), :
   Center for Environmental Structure.
   cite:alexander:2004vision
 - Alexander, C., The process of creating life: nature of
   order, book 2: an essay on the art of building and the
   nature of the universe (the nature of order) (2004), :
   Center for Environmental Structure.
   cite:alexander:2004process
 - Alexander, C., The phenomenon of life: nature of order,
   book 1: an essay on the art of building and the nature of
   the universe (the nature of order) (2004), : CES
   Publishing.
    cite:alexander:2004phenomenon
 - Alexander, C., The luminous ground: the nature of order,
   book 4: an essay on the art of building and the nature of
   the universe (the nature of order) (2003), : CES
   Publishing.
   cite:alexander:2004luminous

