#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 4. First Principles Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [next]


* 4. First Principles Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/04/intro.org
:Created:  2018-04-21T17:04@Prek Leap (11.642600N-104.919210W)
:ID:       21c2adbb-30d9-475f-ba9f-f80612467e67
:VER:      577577122.409021248
:GEO:      48P-491193-1287029-15
:BXID:     proj:VRM2-4234
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR

#+begin_quote
I should have desired, in the first place, to explain in it what
philosophy is, by commencing with the most common matters, as, for
example, that the word philosophy signifies the study of wisdom, and
that by wisdom is to be understood not merely prudence in the
management of affairs, but a perfect knowledge of all that man can
know, as well for the conduct of his life as for the preservation of
his health and the discovery of all the arts, and that knowledge to
subserve these ends must necessarily be deduced from first causes; so
that in order to study the acquisition of it (which is properly called
[284] philosophizing), we must commence with the investigation of
those first causes which are called Principles. Now these principles
must possess two conditions: in the first place, they must be so clear
and evident that the human mind, when it attentively considers them,
cannot doubt of their truth; in the second place, the knowledge of
other things must be so dependent on them as that though the
principles themselves may indeed be known apart from what depends on
them, the latter cannot nevertheless be known apart from the
former. It will accordingly be necessary thereafter to endeavor so to
deduce from those principles the knowledge of the things that depend
on them, as that there may be nothing in the whole series of
deductions which is not perfectly manifest.

— Decartes, Preface, Principles of Philosophy (1644)
  cite:descartes:2010principles
#+end_quote




-----

Next, what do we mean by building from first principles --

  - start with no assumptions, only what can be observed and
    repeated and understood

  - build on what we have learned along the way -- don't
    throw away the baby with the bathwater.  so no zero-day
    tabla rasa, instead we start from scratch and decide
    what works and what hasn't and then build from there.

  - don't be hasty -- we can only change so quickly, and
    change is measured in generations, not decades, we can
    not give in to half-baked schemes that don't work, and
    then when they don't work because the assumptions they
    were based on were wrong, try to change people to fit
    the model, rather than changing the model to fit people.

  - be consistent, persistent and resiliant -- many changes
    take time, sometimes very long periods of time to take
    hold and work -- keep at it, even though you may not see
    the desired results in your lifetime, or even dramatic
    results in your children's lifetime -- playing the long
    game means playing for a very long time -- you and i
    will not see the promised land, and our fate is to
    wander the desert -- that's not an easy thing to say to
    a generation that is used to instant gratification.  the
    reward is that a lot of interesting things happen while
    wandering the desert -- paradise, as well as utopias are
    overrated, they are a horizon and you can never reach a
    horizon because it's constantly retreating.  So cherish
    the challenges in front of you today and that lie ahead
    and forget the destination, it will never live up the
    the hype anyway.

-----

Why civilization, let alone rethink it from first priniple?

  - exponential increase in rate of change is forcing slower
    pace-layers to change at rates they are not good at.
    This does not end well.
  - we are undergoing systemic changes that normally would
    have centuries to play out that are now happening in a
    decade or less that we don't even understant let along
    be able to percolate down to the lower layers before
    another systemic shock to the system comes along, and
    then another -- global-value chain, internet, biotech
    and soon ai and robotics.
  - we are fast approaching the edge of the petri dish, and
    in doing so have impacted the climate to the extent that
    we will see systemic change to the planets environment
    -- things are about to get far more chaotic, less
    predictable and this will result in massive shock after
    shock after shock.  This will require a significant
    amount of our surpluss resources to mitigate that needs
    to be spent on ensuring that a planet with 10 billion
    people can be fed and live at an acceptable standard of
    living.
  - in less than a 100 years, if nothing else goes wrong
    that 10 billion population will start to shrink,
    dramatically and there is no way of knowing what that
    will mean -- some projections put the population 200
    years from now at being as low as half of what it is
    today.  that large population is responsible for
    exponential change, but also in expoential discovery and
    innovation.  what happens when we return to a population
    that we haven't seen since the 1950's but still have all
    of the same problems that demand solutions that require
    a far higher percentage of people innovating than we
    have today?    cite:kremer:1993population
  - progress in terms of human civilization is measured in
    the number of specializions that a society requires to
    function.  the larger the territory of an ecosystem, the
    larger the capacity it has to increase the complexity of
    that ecosystem -- civilization is a kind of ecosystem,
    and we have now run out of space for that ecosystem to
    expand on earth.  if we plateau then that marks the
    highwater mark and we will only be able to tread water,
    but the thing is, systems are never static, they are
    always dynamically changing and if you aren't growing,
    you are dying.  we either progress or adjust our
    expectations for humanity and give in to the inevitable.




** References

  - Descartes, R., Principles of philosophy, the (2010), :
    Kessinger Publishing, LLC.
    cite:descartes:2010principles
  - Wikipedia, , /First principle --- Wikipedia, the free
    encyclopedia/ (2018).
    cite:wiki:2018first-principles

