#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 1.1.1 Civilis  Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [next]

* 1.1.1 Civilis Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/01/intro.org
:Created:  2018-03-29T09:15@Prek Leap (11.642600N-104.919210W)
:ID:       dcebab12-82b3-4757-834a-289a23414c58
:VER:      575561807.552927464
:GEO:      48P-491193-1287029-15
:BXID:     proj:IBK3-5173
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

There has been so much written about civilization, as
history, as a concept, what it says about what we are, the
heights of human achievements and the terrible depths that
we are guilty of and likely will be guilty of again and
again.  But this is not a history.  Whether we like it or
not, we as individuals and are a species are creatures of
this strange construction that we call civilization.  It
speaks to every part of who we are now, and whether or not
we are going to be around much longer or not.

I personally think that if we do survive and learn to thrive
rather than exterminating ourselves or overrunning the
carrying capacity of our environment and wipe ourselves out
by destroying the very thing that allows us to live in the
first place, the story that will be written will be how we
were civilized by civilization and became something far more
than a pack species that learned to scale and dominate the
entire planet.

Mankind is an experiment being played out by DNA on a grand
scale.  It is an experiement that holds out the
possibility of Life on Earth freeing itself from the random
hit and miss process of random mutation and natural
selection and becoming self-determinisitic.  

   expand on self-determination -- consciously manipulate
   matter, dna, energy -- but understand how it all works.
   entropy understands nothing, it is a force.  But Life has
   a memory, can store information, can replicate, can
   mutate -- but still relied on random variation to
   progress.  Man has learned to jump over millions of years
   of random progress in a few thousand years.  And since
   1800 that rate of change is increasing at an astonishing
   rate to the point that we are now nearing a threshold
   where the ROC is not fast enough to be within human
   scales -- and that we can make evolutionary scale changes
   to the world in human timescales.  We couldn't comprehend
   what Life was doing or even what we were doing up until
   the last 100 years or so -- and now because we can change
   things at a ROC that can happen not only in human time
   scales but the time scale of the impact of a single
   scientific career -- which is about 50 years all bets are
   off.  We've moved into completely uncharted territory
   here.  Which means that we are living in the most
   interesting place at the most interesting time in the
   history of the universe.  Right now, right here.  Because
   it could all take off right here and now, in our
   lifetimes...  That is how big this potentially is.  And
   the very things that are making this possible are also
   the very things that make this the most dangerous time as
   well.  In the larger scheme of things, our little
   experiment has such a slim chance of suceeding it is
   beyond computation.

   So let's not screw this up.  And as one slightly clever
   hairless ape to another, get it through your simple
   simian neo-cortex that the pack, the tribe we belong to
   is not some human group, it's not even human at all.
   It's biological Life on this planet.  That's our pack,
   our tribe, our team, our nation.  And there is an Other,
   and it's in the process of trying to kill us, all of us
   every second of every day and it has a name, Entropy.


Man can not take credit for that, we are just one small part
in a process that has lasted at least three and a half
billion years.  Man is not the pinnacle of that process, and
we are not the end of it either.  Whether Man survives or
thrives is of no importance to the larger scheme of things.
We might be bit players, but at this moment in time, we are
the keystone species on the planet with the potential of
being instrumental in the most momentous change since the
evolution of multi-celluar life.  Yes, it really is that big
a deal.  Life creates order from the one-way inevitibility
of entropy.  Entropy gives time a direction, it gives us
information, but it's ultimately a great winding down of
order, complexity, and beauty.  And entropy, just like
Darwinian natural selection is governed by random chance.
And because entropy only works in one direction, that
direction is relentlessly towards randomness, and anything
that that makes our universe unique or special or
interesting.

But if Life with a capital L, can escape that trap of
randomness and become not just self-organizing and
self-replicating but also self-directing -- that is an
astonishing counterforce against entropy and it's power over
the universe.  That all sounds very grand, when you consider
how small, short lived and fragile we are, as a species and
even all of Life combined.  But it's an astonishing thing to
contemplate.  And we are fortunate to be the first attempt
that life has made that is at the brink of being able to do
so.

And all of this hinges on our ability to get better at
civilizing ourselves and not destroying our own life support
systems or destroying ourselves becuase we can't rise above
the programing that evolution has given us and that has
gotten us to where we are today.




Civilization -> comes from the word civitis meaning city.
The ancient greeks used the word polis to mean city, but it
was also the closest thing they had to the concept of
civilization.  This is a good place to start as any and
grounds us at human scales.


** Notes

#+begin_comment
Tainter argues that civilizations hit maximum complexity and
can't sustain itself -- rather civs max out their ability to
innovate and change the parameters of the petri dish -- they
hit the edge of the petri dish because they could not find a
way to grow.
#+end_comment

