#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 1.4.1 Estrangement Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]]

* 1.4.1 Estrangement Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/04/intro.org
:Created:  2018-03-21T18:52@Prek Leap (11.642600N-104.919210W)
:ID:       20b34386-119b-40ba-b668-8a885192ca53
:VER:      574905186.480630274
:GEO:      48P-491193-1287029-15
:BXID:     proj:BWB2-1148
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR




 - quality -- beauty    -- connectedness
 - caring  -- integrity -- control


Alexander's QWAN and Pirsig's Quality are framed by Olson at
that is that which we are estranged estranged from which is
most familar.

In different ways they seem to dump the estrangement at the
feet of Aristotle  ---

They all seem to agree that if we can get back what we lost,
that everything else will come together.  Of course this is
a old meme.  If we can just restore ourselves to what we
were in the Garden before Eve bit the apple, if we can
return to an agrarian utopian past that never existed etc.

But that's not what Alexander and Pirsig and Olson are
talking about here -- it's not returning to a romanticized
fictional past which never existed, it's finding the part of
ourselves that we left behind when man developed spoken
languages and then written languages and so on and so forth
-- at each stage we added layers of mediation between us and
the world to the point where we are disfunctional and deeply
unhappy.

I think they have the right idea -- it's not returning to
anything but reconnecting to what the world is, that we
can't see any longer.

There is a whole raft of different books that are focused on
the different aspects of what is missing, mastery, rest --
hell, epicurus was the first to get at the roots of the
problem so very long ago -- fear.  The stoics said to face
your fear and then it had no power -- epicurus wanted to
eliminate it so that you didn't have to face it.

I'm still not sure, but perhaps process philosophy is a good
fit here -- if everything is the present -- time is not a
line and there is no past or future, then there can be no
retribution or reward in an afterlife.  Though, actually PP
doesn't preclude heaven and hell, it would just be part of
the present, hmm... stick with epicurus on that.

I hope we can include the TEDTalk from the brain scientist
who had a stroke -- which presents the concept from a
biological AND personal perspective.

Her experience explains a lot -- that self-consciousness is
a brain function, and a very useful one.  If a living
organism can not differentiate itself from the rest of the
universe it can not function -- it becomes an
undifferentiated part of the continuum of the universe.  The
problem is that we have let it go to our heads (bad pun) and
have not kept a healthy balance between self and world, our
map is trapped in the delusion that it is the territory and
forgotten that we are also part of a territory far bigger
than ourselves...

Even worse, we have built up concentric layers of collective
maps around us to the point where we don't know what is
real and what isn't.

We need to reconnect to the world and find a balance between
being a part or being a part of a whole.


#+begin_comment
[2018-03-10 Sat] Tried to explain some of this to Mike
tonight when I was in Phnom Penh today, but I think he
didn't understand what I was trying to say.  I called it
mediation rather than explain map-territory.

Am I on the right track here?  I still think so.  But that's
the problem of working on this stuff for so long on my own,
I need more feedback to make sure I'm on track.
#+end_comment



** References

Enlightenment

  - Pinker, S., The blank slate: the modern denial of human
    nature (2003), : Penguin Books.
    cite:pinker:2003blank
  - Pinker, S., The better angels of our nature: why
    violence has declined (2012), : Penguin Books.
    cite:pinker:2012better-angels
  - Pinker, S., The cognitive niche: coevolution of
    intelligence, sociality, and language, Proceedings of
    the National Academy of Sciences, 107(Supplement 2),
    8993–8999 (2010).
    http://dx.doi.org/10.1073/pnas.0914630107
    cite:pinker:2010cognitive

  - Havelock, E. A., Preface to plato (history of the greek
    mind) (1963), : Harvard University Press.
    cite:havelock:1963preface

High Modernism

  - Saul, J. R., Voltaire's bastards: the dictatorship of
    reason in the west (1993), : Vintage.
    cite:saul:1993voltaires-bastards
  - Scott, J. C., Seeing like a state: how certain schemes
    to improve the human condition have failed (1998), :
    Yale University Press.
    cite:scott:1998seeing
  - [[http://calnewport.com/blog/2018/04/11/the-disturbing-high-modernism-of-silicon-valley/][The Disturbing High Modernism of Silicon Valley]] | Cal
    Newport 2018
  - [[https://archive.nytimes.com/www.nytimes.com/books/98/04/19/reviews/980419.19graylt.html][The Best-Laid Plans]] |  John Gray, NYT April 19, 1998


Alienation? 
  - [[https://aeon.co/essays/in-the-1950s-everybody-cool-was-a-little-alienated-what-changed][A History of Alienation]] | Aeon cite:jay:2018alienation
  - Marcuse, H., & Kellner, D., One-dimensional man :
    studies in the ideology of advanced industrial society
    (2002), : Routledge.
    cite:marcuse:2002one-dimensional
  - Pirsig, R. M., Zen and the art of motorcycle
    maintenance: an inquiry into values (2008), : Harper
    Perennial Modern Classics.
    cite:pirsig:2008zen
  - Mills, C. W., White collar: the american middle classes
    (1951), : Oxford University Press.
    cite:mills:1951white
  - Wikipedia, , /White collar: the american middle classes
    --- wikipedia, the free encyclopedia/ (2017).
    cite:wiki:2017white-collar-book
  - Wikipedia, , /Social alienation --- wikipedia, the free
    encyclopedia/ (2018).
    cite:wiki:2018social-alienation



  - https://en.wikipedia.org/wiki/Self-estrangement
  - https://en.wikipedia.org/wiki/Marx%27s_theory_of_alienation 

