#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Learning Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Learning Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/09/50/intro.org
:Created:  2018-05-05T18:50@Prek Leap (11.642600N-104.919210W)
:ID:       93956f55-64d1-4176-adfb-593f278c836c
:VER:      578793089.404002186
:GEO:      48P-491193-1287029-15
:BXID:     proj:LTX5-8538
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR

What I'm trying to get at here is a build very simple toy
model for learning that we can build a system around.

How do we learn?  For that matter what is learning in the
first place?  Acquiring new knowledge, behaviors, skills etc
is just not going to cut it.

What does it mean to aquire new knowledge?  It's not just
recording information into memory, like adding a file to a
file system in a storage device.  The device doesn't /know/
what is stored, it is just a bunch of bits that are
organized into a hierarchical file system of files and
directories. Each file has a pointer to somewhere in the tree.

Memory is not learning, but it is part of it.  A memory is a
variety of different bit sensory data that has been
processed through a hierarchy of pattern matchers which link
different things together.

The more time that you are exposed to similar things, the
more /familiar/ it becomes.  You build up a composite mental
image of something by repeated exposure -- the more times,
the more detailed the model and the more links to other
patterns and memories -- it is then that you can say you
have learned something, that it has become knowledge.

You can know /about/ something and you can /know/ something
-- that your model is strong enough to give you confidence
that you understand the thing.  That doesn't mean you are
right or that what you know is even real, in fact learning
is not about truth, or reality or lies and delusions.  It's
just a mental model that has enough connections to
constitute knowledge.

If pattern matchers see the same pattern long enough then
they constitute a an abstract concept 

When you go about learning something, it doesn't matter
what, from making your bed, to building a pagoda you do it
by observing through experimentation or a demonstration of
what is to be learned.

Then you try to duplicate it.  This is very complex and
requires different parts of the brain, from the limbic
system telling you to fear beign burnt when dealing with
fire, to the muscle memory of your placing your fingers on
the fret board of a ukulele.  This allows your concsious
mind to hand off different kinds of memories and
knowledge to different parts of your brain.  This frees up
cognitive resources to do complex things.

We are not consciously aware of most of the lower level
pattern matchers but only the 'final' conclusion of the
hierarchy in giving a confidence that you know what you are
looking at.

So when we teach people, we provide them with multiple
exposures, which might only require a few repitition or tens
of thousands of repititions to master something very
complex.

The number of repititions required depend on how many
different connections you can make to what is being learned.
So if you teach someone something, you should teach the same
thing from slightly different perspectives and contexts with
each repitition.  So, multiple exposure, with each exposure
incrementally different from the last exposure in order to
establish a wider variety information to connect to
different memories and pattern recognizers in your brain.

We have a good idea not only how we remember things, but
also how we forget.  Spaced repitition is a technique for
reinforcing memory just before we forget it.

So we need multiple repititions, spaced correctly with each
repetition slightly different from the last.


Life-long learning must be woven into the fabric and
workflow of our day to day lives -- so our externalized
cognitive infrastructure must keep track of what we know and
what we don't know and expose us to things we need to
remember at just the right time. This applies to individuals
as well as to groups.



** References



