#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Volume IX Articles Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]]

* XII. Governance Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/12/intro.org
:Created:  2018-04-24T10:14@Prek Leap (11.642600N-104.919210W)
:ID:       c2803cbe-e131-42de-a794-0a8c3ef35495
:VER:      577811710.843989301
:GEO:      48P-491193-1287029-15
:BXID:     proj:HUB3-7112
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


** Scope

Governance outlines the broad requirements for constructing a
generative grammar for building organizational and legal
governance frameworks for a distributed, federated human
civilization.  It must scale, so that it can handle a global
or pan-solar civilization, and that subsets of the framework
can then be used to generate a framework for governance of
any corporate body, public and private large and small.

This is both feasible and desirable as over the past two
hundred years we're getting better and better at building
systems of governance.  Mankind has been refining
democractic, egalitarian state and corporate structures that
build on their predecessors rather than starting from
scratch.  The exceptions have always been autocractic,
ideological extremist, theocratic states that have /all/
failed which have not just failed but failed spectacularly,
causing untold misery and suffering.

There are a few caveats -- we need to address how present
systems fail, and the fact that there is a built-in scaling
problem that result from hard-coded human cognitive and
social limitations.  In other words, humans don't scale
well.  But we are very good at building networks that /can/
scale which largely are limited by propagation, by physics
-- how fast information, people and goods can propagate
through a network.

The idea of a network of states under one broad flexible
system of governance is far from a new idea.  It was not
only tried, but some argue that it was the most successful
system of pluralistic governance in history.  I am talking,
of course, about the Mongol Empire.

So, if we can combine the two, keeping organizations at
human scale, and network them together, we will only be
limited, quite literally by the speed of light.  This means
that such a civilization spanning the entire solar system is
practical.

Piece of cake, huh?

** TL;DR

For a decentralized system to work, it must also have
negative feedback loops in place that keep it decentralized
and egalitarian, this has to be voluntary, with the members
who agree, getting in return a better life and would.  It
must be affirmed and reinforced every day or it will be
lost.

That in the heart of the new social contract. No more zero
sum anything, the only zero sum game is the biggest one of
all, humanity and civilization we all win together or we all
fail together.  And anyone who thinks we're not in it
together is delusional.

This why the theses, rule sets and articles are so
important, we all get rights, but we all equally except that
we also have a duty to each other and to our future.  You
will loose your rights if you neglect your duty.

Mindless consumerism only has selfish gratification at its
core, no purpose or meaning, and the lie that gratification
is the same as happiness

** References

  - American Humanist Association, /Humanism and its aspirations: humanist
    manifesto iii./ (2003).
    cite:aha:2003humanism
  - United Nations, Universal declaration of human rights, UN General
    Assembly, (), (1948).
    cite:un:1948udhr
  - Wikipedia, /Universal declaration of human rights --- Wikipedia,
    the free encyclopedia/ (2018).
    cite:wiki:2018universal-declaration
  - Keen, A., How to fix the future: staying human in the digital age
    (2018), : Atlantic Monthly Press.
    cite:keen:2018fix-future 

*** Mondragon System

  - Bradley, K., & Gelb, A., Cooperation at work: the
    mondragon experience (1983), : Heinemann Educational
    Books.  cite:bradley:1983cooperation
  - Cheney, G., Values at work: employee participation meets
    market pressure at mondragón (1999), : ILR Press.
    cite:cheney:1999values
  - Greenwood, D. J., & Santos, J. L. G., Industrial
    democracy as process: participatory action in the fagor
    cooperative group of mondragon (1992), : Van Gorcum.
    cite:greenwood:1992industrial
  - ICA, , /Co-operative identity, values & principles/
    (1995).
    cite:ica:1995co-op-identity
  - Kasmir, S., The myth of mondragon: cooperatives,
    politics, and working-class life in a basque town
    (1996), : State University of New York Press.
    cite:kasmir:1996myth-mondragon
  - Roelants, B., & Bajo, C. S., Capital and the debt trap:
    learning from cooperatives in the global crisis
    (2011), : Palgrave Macmillan.
    cite:roelants:2011debt-trap
  - Thomas, H., & Logan, C., Mondragon: an economic analysis
    (1982), : G. Allen & Unwin.  cite:thomas:1982mondragon
  - Whyte, W., Making mondragon: the growth and dynamics of
    the worker cooperative complex (1991), : ILR Press.
    cite:whyte:1991making
  - Wikipedia, , /Autarky --- Wikipedia, the free
    encyclopedia/ (2018).
    cite:wiki:2018autarky
  - Wikipedia, , /Rochdale principles --- Wikipedia, the
    free encyclopedia/ (2018).
    cite:wiki:2018rochdale-principles
  - Wikipedia, , /Mondragon corporation --- Wikipedia, the
    free encyclopedia/ (2018).
    cite:wiki:2018mondragon-corp
