#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 01 What is a Point of View?
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [[[./intro.org][prev]]] [[[./02-cognitive-pov.org][next]]]

* 01 What is a Point of View?
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/02/01-what-is-pov.org
:Created:  2018-04-20T17:47@Prek Leap (11.642600N-104.919210W)
:ID:       d8da4ae7-94c0-46f3-a0e8-f04c9d14fa46
:VER:      577493293.598233270
:GEO:      48P-491193-1287029-15
:BXID:     proj:BNI8-6001
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

In philosophy a point of view (POV) is a "stated matter of
consideration", taken from an individual's vantage point. In
this sense a POV is entirely subjective.  But a POV can also
be seen as something that at least theoretically is
objective.

In physics, and in particular, the Theory of Relativity,
everything is understood to what can be observed from a
particular time and place, or more specifically an /inertial
frame of reference/.

    https://en.wikipedia.org/wiki/Inertial_frame_of_reference

This is the point in time or space where the observer is
looking and everything that is observed is relative to that
position.  If something is close or far away, or fast or
slow all depends on if the observer is traveling at the same
speed and direction as what is being observed, which means
that from that POV both the observer and the observed are
stationary relative to each other.


#+begin_quote
New proofs would come much easier if there were a single
universal coordinate system that worked for every problem
and every configuration of space-time. But as Einstein
discovered during those fraught, wandering years, the
universe doesn’t admit any one privileged choice of
coordinates.

“It’s not just that we don’t have such a choice,” said
Weatherall. “It’s that one of the things we take Einstein to
have taught us is that it would be a mistake to expect there
to be such a choice.”

— [[https://www.quantamagazine.org/how-einstein-lost-his-bearings-and-with-them-general-relativity-20180314/][How Einstein Lost His Bearings, and With Them, General Relativity]]
#+end_quote


From wikipedia -- Propositional attitudes:

  The internal structure of a point of view may be analysed
  similarly to the concept of a propositional attitude. A
  propositional attitude is an attitude, i.e., a mental
  state held by an agent toward a proposition.  --
  https://en.wikipedia.org/wiki/Point_of_view_(philosophy)

POVs are critical to the concept of a worldview.

A World View is a mental model of the world that establishes
cognitive orientation for where you are relative to the
world.  Worldviews are a mixture of memories of things
observed and experenced, assertations of what those things
are and mean, and conjecture that fill in the blanks in that
model.  If you are in a room that has a door that you have
never seen opened, you will include in your mental model the
conjecture that there is either a room leading to another
room or corrider in the building or that it is an outside
wall that will take you outside the building.  There is also
the possibility that it is a fake door that doesn't open or
lead to anywhere.  Worldviews are full of such conjectures
that are constantly being updated and expanded as more
information is added to the model.

The maker of the model is always at the center of the model
-- I am here and the rest of the universe radiates out from
where I am at any given moment.

This is the case for pretty much anything animal that has a
brain, as well as groups, an ant colony has a collective
worldview as much as a group of close friends, a department
in a company, a government, a church congregation or even a
religion that spans the globe.

Collective POVs are, by definition, limited to a specific
way of looking at something -- without this, communication
and cooperation is at best difficult and in many cases,
impossible.

When we make rules for a group to follow, those rules first
define the POV that all members choose to observe from.
Without this, agreeing on what is right or wrong, or even
what is true or false is not possible.

Different cultures are based in part on their relationship
that that culture has to the environment.  For someone
living in a cold climate with harsh winters and short
intense summers, they will have a very different view of
nature than someone who has grown up in a mild semi-tropical
climate where the ocean is calm, and the night pleasant and
the the length of the day and night seldom differs over the
year more than an hour or so.  These POVs shape not only how
you feel about nature, but how you design a house, what
kinds of clothes you wear, the kinds of food that you will
have access to and how you can cook it.  Before
refridgeration, it was, and still is common to overcook food
so that it can survive longer in the heat.  People from cold
countries or who have refridgerators don't undertand why
people in the tropics would cook a piece of meat until it
approached the toughness of shoe leather.  But this makes
perfect sense if you want to cook for many people who may
eat at different times of the day.  You need cooked food
that won't go bad in severe heat in a couple of hours or
overnight.

** POVs as filters

A point of view is a kind of filter.  From a vantage point
on top of a hill looking down at a village below, the
observer's point of view is not only their position in time
and space, but the limitations of what they can observe
given what they use to observe and conditions under which
the observation is made.  So if the observer is a human,
then what they can observe visually is limited to a specific
spectrum of light.  If they are near sighted, their
observation will be different if they are wearing corrective
lenses or not.  Is the observer color-blind?  Is the
observation made using a pair of binoculars, or using a
camera with a zoom lense?  Is it night or day, sunny or
cloudy.  Is the observer a local who has grown up in the
area and is familiar with everything in the village or is
the observer a traveler who has never been to the village
before?

Filters are important ways of recognizing patterns, by
reducing what is being shown.  This is a powerful tool, but
needs to be used with care.  What the filter doesn't show is
as important as what it shows.

Ideologies are especially prone to filter bias.  An ideology
is a filter for creating a worldview that only recognizes
things seen through the filter and often ignore anything
that is filtered out as not important, false and at the far
end of the spectrum, as a threat.  Ideologies are attractive
to many people because they simplify their point of view and
give the illusion of certainty.  It's hard work trying to
understand complex things and to take into account different
POVs and different ways of looking at the world.  It's
comforting to many when everything is reduced to a filter
that renders the world as a simple model with short
unambiguous rules where everything is black and white.

Point of View is a powerful tool, but it is a general
purpose tool, which in the hands of a master can be used to
achieve spectacular results.  But like a knife that can be
used both to cut bread or to cut someone's throat, it has
been used to justify some truly horrifying things.

The take-away here is that the Perspective Toolbox is the
cornerstone of Information Literacy, because the more tools
you have for looking at the world, the more difficult it
will be for others to manipulate and decieve you.

It's like the old proverb that when the only tool you have
is a hammer, everything starts looking like a nail. 

Every tool you have mastered and added to your toolbox adds
value to all of the other tools you use.  They are far more
powerful than the sum of their parts.

---

#+begin_comment
I believe that the Big History approach is a good start --
but it needs to be expanded to become the foundation for 
liberal arts education -- and that Information Literacy,
which, in a way echo's the indent of the Medieval Trivium,
which taught student how to reason and communicate -- which
is to say, teaching students how to learn is the single most
important skill for life in world that is changing too fast
to assimilate.
#+end_comment

** POVs as a Cognitive Tool

A POV is a useful way of understanding the world -- in fact
it is important to always consciously considered things from
different perspectives.  In colloquial english it's common
to hear phrases such as:

  - Thinking out of the box
  - Put yourself in my shoes
  - From where I am sitting....

These are all different ways of telling others or reminding
yourself that your POV is not the only way of seeing
something, and that it is useful to see things from a
different perspective.

It's one things to say this, but it's another to actually do
it.  How do you think out of the box?  How do you put
yourself in another person's shoes and see the world as they
do?

The answer you will get, more often than not, is to use your
imagination to create a different model based on how you
imagine someone else might see the world and put yourself at
the center of it and extrapolate how that POV would differ
from yours.

This goes to the heart of empathy -- as a general rule,
unless you are unfortunate to be a sociopath or psychopath,
empathy makes human relationships possible.  In fact, the
very definition of a person who is totally disfunctional in
a society is a sociopath or psychopath which are defined as
persons who can not feel empathy.

Problem solving in large part is a skill that requires a
person to understand a problem from different perspectives
-- thinking out of the box is the process of creating a
mental model of something and imagining how it looks from
multiple POVs.  Pretty much every innovation or advancement
in human understanding has been the result of this process.


** References

