#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 02.Point of View as a Cognitive Tool
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [[[./01-what-is-pov.org][prev]]] [[[./03-objective-pov.org][next]]]

* 02. Point of View as a Cognitive Tool
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/03/01/02-cognitive-pov.org
:Created:  2018-04-20T17:58@Prek Leap (11.642600N-104.919210W)
:ID:       f6c16a62-bfe2-4710-ad09-ea78102c9184
:VER:      577493990.546836828
:GEO:      48P-491193-1287029-15
:BXID:     proj:QIO2-1605
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


A POV is a useful way of understanding the world -- in fact
it is important to always consciously considered things from
different perspectives.  In colloquial english it's common
to hear phrases such as:

  - Thinking out of the box
  - Put yourself in my shoes
  - From where I am sitting....

These are all different ways of telling others or reminding
yourself that your POV is not the only way of seeing
something, and that it is useful to see things from a
different perspective.

It's one things to say this, but it's another to actually do
it.  How do you think out of the box?  How do you put
yourself in another person's shoes and see the world as they
do?

The answer you will get, more often than not, is to use your
imagination to create a different model based on how you
imagine someone else might see the world and put yourself at
the center of it and extrapolate how that POV would differ
from yours.

This goes to the heart of empathy -- as a general rule,
unless you are unfortunate to be a sociopath or psychopath,
empathy makes human relationships possible.  In fact, the
very definition of a person who is totally disfunctional in
a society is a sociopath or psychopath which are defined as
persons who can not feel empathy.

Problem solving in large part is a skill that requires a
person to understand a problem from different perspectives
-- thinking out of the box is the process of creating a
mental model of something and imagining how it looks from
multiple POVs.  Pretty much every innovation or advancement
in human understanding has been the result of this process.

** References

