#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 03. Defining Objective Point of Views
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [[[./02-cognitive-pov.org][prev]]] [[[./04-lod.org][next]]]

* 03. Defining Objective Point of Views
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/02/03-objective-pov.org
:Created:  2018-04-20T18:02@Prek Leap (11.642600N-104.919210W)
:ID:       dfee203e-a433-4eaf-a098-86df09b8d3d2
:VER:      577494197.144944568
:GEO:      48P-491193-1287029-15
:BXID:     proj:XTX6-4568
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

It would be helpful if generic POVs could be objectively
defined in a way that they could be used to understand and
used by anyone without having to resort to subjective
imagination or empathy which are often so intertwined with
emotional states, cognitive limitations and biases that they
are difficult to use as general purpose empirical-based
cognitive tools.

We have identified what we believe to be three fundamentally
important types of POVs which can do just that.  And because
of the importance that POVs have in the survival of a
species, and as a culture and civilization we are putting
these three POVs at the center of understanding who we are,
where we came from, how to overcome cognitive limits and
bias, problem solving, communication, conflict resolution
and cooperation.

But before we can introduce the three core POVs we will need
to introduce three concepts, each of which will be the core
of a Core POV, but also are critical understanding any one
of the three POVS.  These are, Level of Detail, Rate of
Change, and Process of Change.
