#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 04. Level of Detail (LOD)
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [[[./03-objective-pov.org][prev]]] [[[./05-roc.org][next]]]

* 04. Level of Detail (LOD)
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/03/01/04-lod.org
:Created:  2018-04-20T18:04@Prek Leap (11.642600N-104.919210W)
:ID:       332bafb1-30ca-4685-85e9-19d2b12902d8
:VER:      577494330.563866074
:GEO:      48P-491193-1287029-15
:BXID:     proj:KKU3-1117
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


LOD is a concept and technique used in 3D modeling that
involves decreasing the complexity of a model as it moves
away from the viewer, or physical POV relative to the model.

We use the term LOD rather than distance because distance is
a relative term -- is distance the space traveled by light
in a given time?  Is distence a measure of units, and if so
what units?  What is the accuracy of those units?  Is a
day's walk, the same as 10 kilometers?

#+begin_quote
Mount Everest’s height seems to be subject to two competing
forces. On the one hand, the collision of two continental
plates (Asia and India) causes a certain amount of uplift
each year, perhaps about a centimeter or so, although there
seems to be some disagreement. On the other hand, other
forces, such as erosion and melting glaciers, can cause a
decrease in height. While it’s unclear how much it changes
each year, we now know for certain that the height is never
exactly constant. We also know that Mount Everest is moving
laterally at quite a nice clip: six centimeters per year,
making its location also a mesofact, one of those slowly
changing pieces of knowledge.

-- Half-Life of Facts cite:arbesman:2012half-life
#+end_quote


LOD clears away all of that and is simply the amount of
detail that can be observed from a given frame of reference.
The less detail, the farther away it is, the closer the more
detail that can be observed.

LOD is a useful way of looking at anything in terms of how
much detail can be displayed or understood.

  - we think of threats in terms of distance and the amount of detail
    you can take in -- don't fire until you see the whites of their
    eyes.  Storm clouds on the horizon, or the threat is right on top
    of us.  The farther away a threat is the more time you have to
    react, the more time to plan and model the problem because the
    farther away it is, the less information you have to deal with in
    evaluating the threat and how to react to it.  The closer it
    becomes the more information you have to content with and the less
    time you have to process all of that information.

    This becomes very important because of the concept of discounting
    -- we discount things that are far away -- we put off dealing with
    anything that is not percieved as an immediate threat -- we can
    plan for the future, which is one of the things that sets us apart
    from other animals, but we're still not very good at it.  The
    lower the detail, the lower the threat the less weight we give to
    it.  The larger something is, the more we pay attention to it, and
    that includes very small threats like a poisonous spider, the
    spider itself is small, but the pain or even threat of death is
    very large and detailed.

    So LOD is at the heart of how we determine what is and what isn't
    important -- spending a dollar on a bag of crispes is small,
    relative to how much money the average person in the developed
    world spends every month or in a lifetime, but buying a car is
    somethiing that will impact your life for years.  Buying a house
    will impact your life for decades or even the rest of your life.

The forest and the trees -- a low LOD allows us to see the big
picture, uncluttered by detail -- a high LOD immerses us in detail
making it difficult or impossible to see larger or longer processes at
work.


Think of information in a physical Library in terms of LOD.  Standing
outside the building you can gauge very roughly how large a library it
is by the size of the building.  Entering the building you apprach the
catalog file drawers.  The more drawers the more books and other
material in the library.  If the library is openstack, you can then
walk into the stacks and see the library in terms of floors of rows of
shelves, step slower and you are in a single row and you can see the
different shelves of books.  Step closer and you can read the spines
of the books on the shelf in front you and you see more detail, the
type of book, cloth, papeback, library binding etc.  And you can see
the title of the book, the authors name and the publishers logo or
imprint.  You can also see roughly how big the book is, in terms of
thickness (number of pages) and the height of the book.  Take down a
book and you open to the title and copyright pages and you see more
metadata that gives you an idea of who created the book, when and
where it was published and perhaps the library catalog entry that you
would have seen in the library catalog file drawers.  Turn to the
Table of contents and you see an outline of the book and get an idea
of it's structure -- leaf through the book and you'll have an idea of
the size of the font and how much information is on each page, are
there illustations? footnotes?  Then, finally turn to the first page
of the first chapter and you've come to the highest level of detail in
the book.  When you are reading, you an no longer see the book in
lower detail -- though your mental model that you made when looking at
the book from lower LODs provides you with a means of understanding
where you are reading, relative to the whole book.

Now we need an example of temporal LOD

We mix and match things when we compare different things together --
we don't always compare two things at the same LOD -- this is very
useful.

A low LOD in a short scientific paper might be very different from the
short LOD in a book.  So a paper that is mentioned in passing a larger
work describes that paper from a low LOD, which is useful
understanding that paper in context with other related papers.  But
you might then place that paper beside the book and refer to it in
order to see in detail how the paper might provide even more context
with the larger picture in the book.

The concept of the length of the coast of England -- you can always
add or subtract one from something -- zeno's paradox -- you can always
cut something in half.  So setting an LOD is also a means of defining
something.  A definition is as much a description of what something is
as it excludes what something is not.

LOD is key to understanding the part-whole relationship which we will
discuss in it's own chapter.

LOD is key to the Map-Territory relationship, which we will discuss in
more detail in it's own chapter.


** References


- https://en.wikipedia.org/wiki/Level_of_detail
