#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 08. Scale
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [[[./07-as-povs.org][prev]]] [[[./09-narrative.org][next]]]

* 08. Scale
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/02/08-scale.org
:Created:  2018-04-20T18:16@Prek Leap (11.642600N-104.919210W)
:ID:       c05a43db-57c3-4b8c-929e-b940582b248e
:VER:      577495046.304270980
:GEO:      48P-491193-1287029-15
:BXID:     proj:KKN3-2515
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

Scale determines POV relative to the distance from a given frame of
reference, the distence determines the LOD from any given distence.

Scale works separately in space or in time or as one or the other
depending on if your POV is a Process or a Narrative.

Since we use the concept of LOD, rather than any specific standard of
measurement -- it doesn't require an ideal references meter stick kept
in a environmentally stable vault, or sophisticated light sources and
timing equipment to measure how far light travels in a given period of
time.  These are important concepts and tools, but as a universal
means of understanding a POV they don't help.

Is Scale a POV in its own right?


Different things work differently at different scales -- some things
scale from small to large like a vector graphic -- but other things
are creatures of specific scales they only work within narrow ranges.

The importance of being the right size cite:haldane:1928being

things like water tension and gravity relative to mass means that most
things won't scale

Things that can truly scale from very small to very large are rare but
very important -- in fact this is a useful metric, the larger that
something can scale the more usefull it is.

over and over again, we will see that there are many aspects about how
humans are designed and wired leads us to the conclusion that sapiens
only work within a scale that has a narrow range -- I would argue that
most if not all of the problems that we face as a species today stem
from our attempts to scale sapiens beyond what we are capable of.

The interesting thing is that it's doubtful that sapiens would have
been able to achieve what we have done today unless we had so
relentlessly tried to scale beyond our boundries in terms of climatic
environments, our social structures, or cognitive limitations etc.

This is what has made us successful as well as what has screwed us up
so terribly.  In many respects, this work is an attempt to find a
balance for us to be able to live within those limits, while still
pushing the boundries and expanding those limits.  That's the
balanceing act we need to learn to do better -- that's what keeps us
within the limits of our petri dish, and gives us the time to keep
expanding the size of that petri dish before we overrun it and destroy
ourselves.


** References


