#   -*- mode: org; fill-column: 60 -*-

#+TITLE: II. Points of View Abstract 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* II. Points of View Abstract
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/02/abstract.org
:Created:  2018-05-17T17:24@Prek Leap (11.642600N-104.919210W)
:ID:       c7cdab96-a62f-480d-871d-910e64374e58
:VER:      579824758.935035633
:GEO:      48P-491193-1287029-15
:BXID:     proj:WSG5-3108
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
 - POV
 - Perspective
 - Observer
 - Context

We construct POVs by combining one or more of the /five
cardinal vantage points/ which establishes where an observer
is relative to what is being observed 

Each vantage point is a range used to manipulate the
perspective like a slider on a sound mixing board that
changes the level of the vantage point.

This provides us with a cognitive tool box to help us
/think outside the box/, as well as to capture or model the
surrounding context of something as seen from different POVs.

This also helps to be aware of when we are mapping one POV
onto something in the past, for example, that existed in a
context quite different from today

ROC for example is useful to understand how buildings can be
thought of as made up of shearing layers -- and that
different parts of buildings change at different rates, or
as a different way of of looking at Big History other than
from a linear timeline divided into complexity thresholds.
The Big Bang is not something that happened in the past, it
is a process that is still going on today, or how change
propagates at different speeds in different places --
Gibon's famous "the future is already here, it's just not
evenly distributed".

These are not abstract, academic distinctions, they apply to
every part of our lives, the societies we live in.  They can
be used in education, in design, in production, commerce and
governanace.  These are tools that law enforcement officer
can use when evaluating a domestic dispute as well as to
piece together what had happened at a crime scene.

Ideally we want to encode our toolbox into machine
understandable and executible code.

----

It's important that we explain these concepts as tools for
building civilization -- so we need to show not only how
these tools work, but how to use them.


** TL;DR

[2018-05-22 Tue 09:52] This might be a good place to
consider why we need all this mishegoss.  Most of us reading
this will have grown up in a middle class background with a
standard liberal education that makes many assumptions about
how we see the world as being universal or even desirable.

I hope to establish a new paradigm that replaces the
assumptions that have been imposed on us by the evololution
of state legibility and high modernism which in practice
simplifies complexity down to a map showing a handfel of
parameters, axis and scale.  We forget that there is a very
real distinction between local and synoptic knowledge.  The
laster is by definition has less detail, less knowledge in
it because it needs to take something that can't load into
our heads because they exceed human cognitive and memory
limits.  The bigger the territory you try to fit in your
head the lower the LOD, the lower the LOD the more lossy it
becomes.

The modern world is becomming increasingly complex, but we
can't handle all of that complexity so we create ever more
simplfied maps to get around that only makes this worse.

The tools we use to understand the world are far too
simplisitic to be of much use any longer -- we need broader
range of tools to make sense of the world.  The problem with
this is that simplicity is "user friendly" and fast.
Complexity has a steep learning curve and slows us down.  We
trade speed and easy for depth, malleability, wisdom and
familiarity and efficiency.  Let's consider the last two,
familiarity and efficiency because that is the biggest thing
we loose when we spend most of our time in a epistimic,
synoptic contex.

It's long been understood that small farms are far more
productive hectare for hectare than large farms.  This is
because a small farm is familiar to the farmer, it is at a
scale small enough to fit in his head, Bill Mollison said
that he is often asked how large a farm should be, and his
answer was always "as large as you can handle".  You can
only handle what you can fit in your head, and in a farm
there is a lot to fit in.  Something becomes familiar when
it has been encountered so many times that it becomes
something like muscle memory, your brain understands and and
use that massive nexus of links to all the times that you
have encountered it so that it can be accessed sub
consciously.  We all use this in one form or another.  If
you commute to work every day, or go to the same market at
the same time every day, when waking or driving at the time
and you become distracted or lost in thought, you will
suddenly realize that you have gone to that place or at
least started to go there automatically, even if you
intended to go somewhere else.  Familiarity allows us to go
on autopilot so we can concentrate conscious efforts on
other things.  This is the goal of Mastery of anything, to
become so familiar with something that you can don't need to
pay attention to the larger sequence so that you can notice
and control the small details that a beginner can not see or
control because they need to pay attention to to things that
are familiar to the master.  In a small farm, the farmer
intimately knows the local climate, where the wind blows
from in the winter or summer.  Knows all of the plants and
animals both domestic and wild on the farm, their
charateristics their behaviors and how they compliment each
other.  The farmer knows the soil, and what plants need to
be grown to replace nitrogen, or which plants act to repell
insects which each the crops that can be sold.  The list is
almost endless, the tools, techniques that have worked and
which ones don't work, the countless experiments to see if a
new variety or breen works better or not.   This constitutes
a vast storehouse of knowledge that can't scale beyond what
the farmer can control.  Once this threshold has been
crossed, the farm might become larger but it will
increasingly become less efficient as the farmer will have
to reduce the complexity level to be able to control it.
Systemic problems will begin to appear, slowly at first and
then frequently and more severely.  Pests, soil depletion,
waster and waste management, disease and the less
flexibility there will be when a crop is ready to go to
market.  When everyting is in basket, you only need to have
one failure that will destroy everything.  In a small farm,
there are many baskets, so the failure of one thing will not
be catastrophic.



One of the big advantages of a role-based identity model is
that it perserves the contextual contextual three letter
soup that we will be introducing in Cantos II, III and IV,
that we call the /5 Cardinal Perspectives/: rate-of-change
(ROC), level-of-detail (LOD), level-of-abstraction (LOA),
level-of-change (LOC) and the process-of-change (POC).  When
we switch roles, our knowledge workshop swaps out the model
and information we use in that role for a different model
that uses a different contexual mix of perspectives that
constitutes a Point of View which constitutes a
context-based WorldView.



#+begin_comment
This obviously has to be rewritten so that it is a summary
rather than given as an specific example used as summary. 
#+end_comment

The premise is that it is helpful to always understand the
Point of View (POV) -- or perspective that you are looking
at something because when you change your POV you change the
context of what you are seeing and will often see things you
didn't see before, or even see things in a completely
different way than you saw before.

We define five Cardinal Perspectives (CP):

  - LOD : Level of Detail      - near <--> far
  - ROC : Rate of Change       - slow <--> fast
  - LOA : Level of Abstraction - specific <--> abstract
  - LOC : Level of Complexity  - simple <--> complex 
  - POC : Process of Change    - start <--> finish

These five Perspectives form the foundation for how
everything else *everything* in APPL, Primer & Hoard are
understood.

Each CP becomes increasingly more complex and abstract, but
each builds on the one before and let's you see the same
thing from a different perspective.  It does not negate the
other POVs so much as enriches them and provides a more
powerful toolbox for modeling and understanding.

For example, let's look at the Origin Story that will start
the Primer.

The Origin LOD is basically Big History -- a linear timeline
with a beginning (big bang) middle (from BB to now) and the
end (projected heat death of the universe).  The narrative
is organized around tipping points where complexity reaches
a critical mass that changes the nature of the universe, and
then later life on earth and eventually us.  This is a
fantastic narrative and is a perfect way of easing people
into the origin story which can be understood like any other
origin story.

The Origin ROC is basically a finer grained version of Big
History that uses the concept of causal propagation (think
Light Cones) to understand that different things change at
different speeds and that all of these things are mixed
together.  It's the embodiment of Gibson's the future is
already here isn't just not evenly distributed.  Brand's
Pace-Layers is a good way of understanding this, as well as
Light Cones and causal propagation of change happening at
the speed of light but making the point that the speed of
light is the maximum speed that things can propagate, most
things are propagating far slower.

--------

Taken together these three models will give us a set of
powerful tools for understanding, planning, building, and
maintaining civilizations.


