#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   Bead Game Contents
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Bead Game Contents
  :PROPERTIES:
  :CUSTOM_ID:
  :Name:      /home/deerpig/proj/chenla/warp/dex.org
  :Created:   2018-09-01T17:32@Prek Leap (11.642600N-104.919210W)
  :ID:        d0605fec-e7e8-48a8-8742-dc28f39cdb01
  :VER:       589069993.268590117
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:OPD7-3180
  :Class:     primer
  :Entity:    toc
  :Status:    wip 
  :Licence:   MIT/CC BY-SA 4.0
  :END:

Before we can begin defining the patterns for building a human scale
distributed civilization we will need to define the primitives that
will be combined to create the tools for making that language as well
as the generative processes that constitute the structures of every
day life which are manifest in everything from a bedside table, to
industrial production, to family life and social structures of
cooperation that we agree to abide by.

#+begin_quote
... the real structure of the environment comes from
overlapping sets of interconnected rules — rules
representing relationships between patterns in the
environment and which when properly adapted, correspond to
the holistic perception of structure..."

— Grabow p68. cite:grabow:1983christopher 
#+end_quote

Humans experience the world by recognizing patterns that we percieve
as things that are distinct from other things.  We instinctively know
when these patterns are calming, jarring, peacful, joyous, just
plain broken or even sinister.

A young girl throwing a frisbee to a golden retriever in a sunny
summer field bordered by forests of rich browns and green.  A simple
house on stilts that seems to grow out of a ridge line of palm trees
in silhouette behind a checker board of browing october rice paddies
waiting to be harvested, a single plain sheet of creamy white paper
weighted down by an old fountain pen on a broad polished wooden
desktop illuminated by a green glass bankers lamp -- a clean slate
inviting you to write on it.

Almost anything can be thought of as a pattern.  A pattern
is essence that identifies and bonds together any number of discrete
parts into a whole.  
