#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   Bead Game
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/
#+HTML_HEAD: <link rel="stylesheet" href="tufte.css" type="text/css" />
#+HTML_HEAD: <link rel="stylesheet" href="latex.css" type="text/css" />
#+OPTIONS: toc:nil num:nil H:4 ^:nil pri:t
#+OPTIONS: html-preamble:nil
#+OPTIONS: html-postamble:nil
#+OPTIONS: html-style:nil


Before we can begin defining the patterns for building a
human scale distributed civilization we will need to define
the primitives that will be combined to create the tools for
making that language as well as the generative processes
that constitute the structures of every day life which are
manifest in everything from a bedside table, to industrial
production, to family life and social structures of
cooperation that we agree to abide by.

#+begin_quote
... the real structure of the environment comes from
overlapping sets of interconnected rules — rules
representing relationships between patterns in the
environment and which when properly adapted, correspond to
the holistic perception of structure..."

— Steven Grabow cite:grabow:1983christopher p68.
#+end_quote

Humans experience the world by recognizing patterns that we
percieve as things that are distinct from other things.  We
instinctively know when these patterns are calming, jarring,
peacful and joyous; a young girl in a flower-print dress
throwing a frisbee to a golden retriever in a sunny summer
field bordered by a rich brown and green conifer forest.  A
simple house on stilts that seems to grow out of a ridge
line of palm trees in silhouette behind a checker board of
browing october rice paddies waiting to be harvested, a
single plain sheet of creamy white paper weighted down by an
old fountain pen on a broad polished wooden desktop
illuminated by a green glass bankers lamp -- a clean slate
inviting you to write on it.

We also know when something isn't right, jarring, just plain
broken or even downright sinister; a brutal industrial
building, with smokestacks belching smoke that you not only
can see, but deeply /feel/ that is off-color and poisonous
as hangs in the still air above the factory with an ominous
heaviness.  A crumpled wreck of a car surrounded by tiny
jagged shards of broken glass sparkling blue on the black
asphalt.  A sparrow, laying still and lifeless, on its back
-- death having sucked the shine from its now dull brown and
white feathers.  The ragged gash of a pot hole in a grimy
back alley, filled with fetid water with an oily soap bubble
sheen broken only by white styrofoam shards from a discarded
rice box.

There is nothing subjective in any of this.  These are
objective recognitions triggered in any of us when seeing
life and beauty or death, disfunction and ugliness.

And yet in the past two centuries Man has progressively
increased the amount of disorder, ugliness and sterility of
the environment we construct to live and work in and has
lost the ability to build towns, buildings, furniture,
appliances, houses, workplaces, and social structures that
are at best cold uninviting, sterile, meaningless and empty.
The fabric of post-modern daily life is dominated by
cookie-cutter mass-produced objects that at best somewhat do
what they were designed to do with a built-in half-life
measured in months or a few years at most before they need
to be discarded and replaced.  A civilization can be
measured by it's architecture and the quality of it's
tools. Industrial civilization has failed miserably on both
counts. Appliances such as washing machines and fridges that
used to last generations now are designed to break every 3-4
years.

--- *patterns* Almost anything can be thought of as a
pattern.  A pattern is an essence that identifies and bonds
together any number of discrete parts into a whole.

--- patterns that we percieve as objects are all physically
actualized social interpersonal and socio-economic
relationships.

--- patterns in turn can be externalized and modeled as
directed graphs which is serialized as a tuple that is made
of edges and vertices.

--- a map of relationships forms a graph which in turn
represent objects, concepts, and memories

--- we now can observe and manipulate these graphs using
four tools that can then be used to understand and create
anything from a hen's egg to copper kettle, a hula-hoop the
Isse shrine to the UN Declaration of Human Rights to a
shopping list or airline boarding pass.  In effect this
constitutes a toolbox that we can use to build a human scale
living distributed civilization.
 
--- we treat these as tools -- an extension and
externalization of mind and hand as a means of building
progressively more complex abstractions.  Complexity is
inherently nested into hierarchies, stages, levels and
layers.  These are the building blocks that all complexity
ad life is built on. They are the foundation that everything
from galaxies to human embryos are built on.  The four core
tools are: /form/, /process/, /chunking/ and /propagation/.

*form* is geometric -- both shape of patterns/things and
the differentiation of space; positive and negative -- it is
how collections of things take shape, become living wholes.

*process* is energy which fuels change both positive
adding, and negative difusion -- the continuous becoming of
one thing to another.  But it is also manifest as systems
governed by self-regulating negative and positive feedback
loops. Process is violence, when too much energy rips things
apart so they can recombine.  Process is about maintaining
goldilocks zones -- equilibria.  Process is about
dissipation; entropy, as things cool and wind down towards
an ultimate heat death.

*chunking* is simplification -- manifest in the
map-territory relationship -- it combines and compresses, it
is how we break large difficult problems into many small
easy parts -- it is the mechanism for creating hierarchy,
holarchies and directed graphs.  It's how small things are
grouped together to create larger things.

*propagation* is time -- more importantly is it about
how change moves through time -- change is not simultaneous
it has an origin, be it the big bang, the chemical reaction
when striking a match, or punching a button that connects a
electrical circuit powers up a laptop.  Propagation is how
information spreads through networks, how light travels
between stars, how infections spreads through a body or
population. 

---

Civilization

  - Scattered Multi-Planet Civilization 
  - 
  - 
  - 
  - 
  - Independent Bioregions


bibliography:~/proj/chenla/hoard/bib.bib
