#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   Warp & Woof Contents

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

#+BEGIN_SRC sh :dir ~/proj/chenla/warp :results org drawer
  words=$(find ./ -type f -name '*.org' -exec wc -w {} \; | awk '{ sum += $1 } END { print sum }')
  pages=$(($words / 250))
  echo "|dir|words|pages"
  echo "|-"
  echo "|" ${PWD##*/} "|" $words  "|" $pages
  #+END_SRC

#+RESULTS:
:RESULTS:
| dir  |  words | pages |
|------+--------+-------|
| warp | 180966 |   723 |
:END:

[top]

* Warp & Woof Contents
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/index.org
:Created:  2018-03-14T18:05@Prek Leap (11.642600N-104.919210W)
:ID:       b6aaf7e8-a17e-4733-872a-73183277fc8c
:VER:      574297587.456120402
:GEO:      48P-491193-1287029-15
:BXID:     proj:NKO5-1361
:Class:    primer
:Entity:   toc
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:
 - [[./title.org][Title Page]]
 - Copyright Page
 - [[./epigraph.org][Epigraph]]
 - Dedication
 - Acknowledgments
 - Preface
 - [[./preamble.org][Preamble]]
 - [[./intro.org][Introduction]]
 - [[./plan.org][Plan of the Work]]
 - [[./synopsis.org][Synopsis]]
 - Prolegomenon

* A Bead Game

#+begin_quote
There was a passionate craving among all the intellectuals
... for a means to express their new concepts. They longed
for philosophy, for synthesis. The erstwhile happiness of
pure withdrawal each into his own discipline was now felt to
be inadequate. Here and there a scholar broke through the
barriers of his specialty and tried to advance into the
terrain of universality. Some dreamed of a new alphabet, a
new language of symbols through which they could formulate
and exchange their new intellectual experiences.

— cite:hesse:1957magister-ludi
#+end_quote

#+begin_quote
He invented for the Glass Bead Game the principles of a new
language, a language of symbols and formulas, in which
mathematics and music played an equal part, so that it
became possible to combine astronomical and musical
formulas, to reduce mathematics and music to a common
denominator, as it were. ...

— cite:hesse:1957magister-ludi
#+end_quote

#+begin_quote
The Glass Bead Game, formerly the specialized entertainment
of mathematicians in one era, philologists or musicians in
another era, now more and more cast its spell upon all true
intellectuals. ... After Joculator Basiliensis' grand
accomplishment, the Game rapidly evolved into what it is
today: the quintessence of intellectuality and art, the
sublime cult, the unio mystica of all separate members of
the Universitas Litterarum. In our lives it has partially
taken over the role of art, partially that of speculative
philosophy.

— cite:hesse:1957magister-ludi
#+end_quote

#+begin_quote
That it is possible to invent a unifying concept of
structures within which all the various concepts of
strucuture now current in different fields of art and
science, can be seen from a single point of view.  This
conjecture is not new.  In one form or another people have
been wondering about it, as long as they have been wondering
about structure itself; but in our world, confused and
fragmented by specialization, the conjecture takes on
special significance.  If our grasp of the world is to
remain coherent, we need a bead game; and it is therefore
vital for us to ask ourselves whether or not a bead game can
be invented.

— cite:alexander:1968bead
  Quoted in cite:grabow:1983christopher p188.
#+end_quote

Alexander was concerned with buildings and how they impact
human individuals as well social structures that they live
in.  The first pattern, INDEPENDENT REGIONS, even touched on
a global structure.  He was also painfully aware of the fact
that architecture can not be separate from the process of
building so that you can't change architecture without
changing the economics of building buildings which goes hand
in hand with changing the political systems that regulate
buildings and public spaces.  He also touched on education.
Some patterns talked of the workplace and how shops, and
offices and even industrial production can not be separated
from other aspects of human life.

What he had put on his plate was already so big that he
really wasn't in a position to go the rest of the way --
that the entire nature of work, production and market
economics.  Alexander's vision was not compatible with
anything that was outside of human scale.  This implies that
mass-[anything], be it production, travel, communication,
education etc was not compatible with his vision of human
scale, living structures -- that modern industrial
societies in almost every aspect was anathema to the quality
of human life which constitutes the great estrangment.


Our Bead Game is designed to provide a grammar and structure
that can be used across disciplines -- 

  - Chunking    : *SPACE*  heirarchy, relationships, concepts,
                           holons, rhizomes, graphs, maps
                           patterns.
  - Propagation : *TIME*   pace/shearing-layers, light-cone
  - Process     : *ENERGY* change, entropy, information
  - Form        : *MATTER* geomtry and differentiation of space

---

The Cardinal POVs are a toolbox for observation and
understanding the Bead Game.

  - POV  : LOD • ROC • POC • LOA • LOC

I'm finding that I use LOD and ROC almost constantly but not
POC, LOA or LOC....

---

Combine these things together in the right way and we get
generative grammers that spit out antifragile complex
structures and systems that are greater than the sum of
their parts.

---

  - QWAN : Beauty -- an innate ability that humans and other
                     complex life are designed to recognize
                     and respond to.
  -  • Meaning • Purpose

---

#+begin_quote
According to Koyré, it was not the experimental or empirical
nature of Galileo's and Newton's discoveries that carried
the Scientific Revolution of the 16th and 17th centuries,
but a shift in perspective, a change in theoretical outlook
toward the world. Koyré strongly criticized what he called
the "positivist" notion that science should only discover
given phenomena, the relations between them and certain laws
that would help to describe or predict them. To Koyré
science was, at its heart, theory: an aspiration to know the
truth of the world, of uncovering the essential structures
from which phenomena, and the basic laws that relate them,
spring.

— Wikipedia: Alexandre Koyré
  https://en.wikipedia.org/wiki/Alexandre_Koyr%C3%A9
#+end_quote

Koyre, A., From the closed world to the infinite universe
(1957), : Johns Hopkins Press.  cite:grabow:1983christopher

#+begin_quote
This scientific and philosophical revolution — it is indeed
impossible to separate the philosophical from the purely
scientific aspects of this process: they are interdependent
and closely linked together — can be described roughly as
bringing forth the destruction of the Cosmos, that is, the
disappearance, from philosophically and scientifically valid
concepts, of the conception of the world as a finite,
closed, and hierarchically ordered whole (a whole in which
the hierarchy of value deterlnined the hierarchy and
structure of being, rising from the dark, heavy and
imperfect earth to the higher and higher perfection of the
stars and heavenly spheres), and its replacement by an
indefinite and even infinite universe which is bound
together by the identity of its fundamental components and
laws, and in which all these components are placed on the
same level of being. This, in turn, implies the discarding
by scientific thought of all considerations based upon
value-concepts, such as perfection, harmony, meaning and
aim, and finally the utter devalorization of being, the
divorce of the world of value and the world of facts.

— cite:koyre:1957closed-world p4.
#+end_quote


#+begin_quote
Last but not least, the world-clock made by the Divine
Artifex was much better than Newton had thought it to be.
Every progress of Newtonian science brought new proofs for
Leibniz's contention : the moving force of the universe, its
vis viva, did not decrease; the world-clock needed neither
rewinding, nor mending.

The Divine Artifex had therefore less and less to do in the
world. He did not e ven need to conserve it, as the world,
more and more, became able to dispense with this service.

Thus the mighty, energetic God of Newton who actually" ran
"the universe according to His free will and decision,
became, in quick succession, a conservative power, an
/intelligentia supra-mundana/, a " Dieu faineant."

Laplace who, a hundred years after Newton, brought the New
Cosmology to its final perfection, told Napoleon, who asked
him about the role of God in his /System of the World/:
"Sire, jen'ai pas eu besoin de cette hypothese." But it was
not Laplace's /System/, it was the world described in it
that no longer needed the hypothesis God.

The infinite Universe of the New Cosmology, infinite in
Duration as well as in Extension, in which eternal matter in
accordance with eternal and necessary laws moves endlessly
and aimlessly in eternal space, inherited all the
ontological attributes of Divinity. Yet only those — all
the others the departed God took away with Him.

— cite:koyre:1957closed-world p276.
#+end_quote

Koyre, A., From the closed world to the infinite universe
(1957), : Johns Hopkins Press.  cite:koyre:1957closed-world

#+begin_quote
Prior to the 17th century, God served as a reference point
at which mind and matter followed the same laws; indeed
their congruence provided the only rational explanation for
the existence of an absolute standard of values.  But the
removal of divinity from the analysis of the laws of the
universe in the 17th and 18th centuries resulted in the
separation of the world of facts from the world of values,
leaving values stranded in a sea of "contingency."  By the
19th century "positivism" had dominated scientific thought.
But the victory was a hollow.  A universe without values only
leads to a contingency of perception, a subjectivity against
which both "productive necessity" and ordinary consciousness
rebels, demanding the restoration of an objective, absolute
standard of values. (cf Huxley's "Religion with
revelation.")  By the 20th century, phenomenology reveals
that positivism uncorrectly obscures the "real" real
relationship between mind and matter, "bifurcating" nature
into an artificial duality.

— cite:koyre:1957closed-world p.81
#+end_quote

Grabow, S., Christopher alexander: the search for a new
paradigm in architecture (1983), : Routledge Kegan \& Paul.
cite:grabow:1983christopher

---

Value, meaning and beauty had all been striped from the
universe and gradually from human life as well.

Alexander worked to demonstrate that beauty was not a
subjective, or a value judgement -- that it was objective
and was the same and repeatable for everyone.

Just as /high modernism/ and even more extreme incarnations
such as the aptly names /brutalism/ aimed to strip beauty
and meaning from architecture and design, so have
repressive, totalitarian and extremist political movements
sought to do the same for /truth/.  At the time of writing
(circa 2018) Rudi Guliani, speaking as a lwayer representing
the President of the United States went full Orwell,
claiming that "truth isn't truth."  If every opinion is
subjective and of equal value then there is no difference
between truth and lies.  This can be explained as cognitive
dissonance or willful misdirection and bald-face lies which
they are but they are also a manifestion of intellectual and
scientific thought having relegated value to the dustbin.  I
retrospect it was likely the only way to break the lock that
superstition and religious dogma had on collective thought
and it opened the way for the scientific revolution -- but
we need to return and restore value as having.... value and
place it back where it belongs, at the core of what it means
to be a human without having to return to an age where
everyone was required to wear dogmatic manacles that
rejected what we have learned about how the world works.

To do this we first must confront the limits of human
cognition and physical perception of the the world around
us.  The world we can touch, hear, see, feel and smell is
constrained by our limits of sensory organs and our brain's
ability to make turn sensory inputs into a model of the
external world that matches the world closely enough to keep
us alive from moment to moment.  This can all be summed up
in the concept of understanding "human scale."

Once we know our limitations, we need to look at what our
capabilities truly are.  This is still not fully known,
understood or appreciated, especially when talking about the
human capacity for recognizing physical and even symbolic
aesthetic beauty.  In fact, science has not addressed the
problem of beauty at all except in a cursory manner.

Alexander's work has led to the hypothesis that humans (as
do other animals) have an innate ability to identify certain
groupings of overlapping patterns that constitute a
"holistic perception of structure."
cite:grabow:1983christopher p.68.  And what we percieve as
beauty is when that holistic perception of beautiful
structure is optimum or not and the human well being is
largely determined on this perception and locating ourselves
as individuals, groups and as societies within environments
that are beautiful.  This is not subjective -- it's
objective and reproducible.

#+begin_quote
... the real structure of the environment comes from
overlapping sets of interconnected rules — rules
representing relationships between patterns in the
environment and which when properly adapted, correspond to
the holistic perception of structure..."

— Grabow p68. cite:grabow:1983christopher 
#+end_quote


I now want to take this further and extend this concept to
all aspects of human life and understanding of the universe
which will require a framework that bridges all disciplines
and heals the rift between the arts and sciences so that
they become a continuum.  We are not at the center of that
continuum, except as far as any observer is at the center of
what is being observed.  But that we are part of the world
around it -- and that the universe and life is a
manifestation of overlapping patterns that we perceive as
wholes.  And that when these wholes combine into patterns
that transcend the sum of their parts they come alive and in
a very sense are living.  Survival favours those who can
recognize and single out such patterns which we percieve as
beauty.

A framework for systematically recognizing such patterns and
synthesizing them and creating them is the Bead Game that we
are trying to build.

As Alexander said, we don't even know it is possible, but it
is a game worth inventing and not only learning to play, but
mastering in all of its complexity, nuance, majesty and
mystery -- not because it is a glammer or surface that hides
something that is unknowable -- but because we have the
capacity to recognize beauty in a deep and essential way
that is at the very core of our being and that what we
percieve is and understand as the universe itself and our
place in it.

* Foundations
 - [[./foundations/index.org][Contents]]
 - [[./foundations/abstract.org][Abstract]]
 - [[./foundations/intro.org][Introduction]]
 - [[./foundations/window.org][Fifty-Year Window]]
** Natures
 - Contents
 - Abstract
 - Introduction
 - 00. Physics
 - 05. [[./foundations/05/index.org][Nature of Order]]
 - 00. Life
 - 00. Biosphere
 - 00. Savannah, Primates, Apes
 - 03. [[./foundations/03/index.org][Sapiens]]
 - 00. Human Nature (limitations)
 - 02. [[./foundations/02/index.org][Mind]]
 - 01. [[./foundations/01/index.org][Mētis]]

 - 04. [[./foundations/04/index.org][Civilization]]
 - 06. [[./foundations/06/index.org][Estrangement]]
 - 07. [[./foundations/07/index.org][Human Scale]]

 - 08. [[./foundations/08/index.org][Boundries]]  -- need to break up and add to different chapters

 - [[./strawberries.org][strawberries]] — notes

** Principles
 - [[./fdn-principles/index.org][Contents]]
 - [[./fdn-principles/abstract.org][Abstract]]
 - [[./fdn-principles/intro.org][Introduction]]
 - 00. Ethics
   - as foundation for principles
   - ethics as social standards of behavior
   - morals as internalized social standards
   - codification in governance rules & laws
   - secular arguments for ethical stances
   - moral hazzard anti-pattern (eg. same as seatbelts)    
 - 00. Principles
** 02. Points of View
 - [[./02/index.org][Contents]]
 - [[./02/abstract.org][Abstract]]
 -[[./02/intro.org][ Introduction]]
 - 01. [[./02/01/index.org][Point of View]]
 - 02. [[./02/02/index.org][Cardinal Perspectives]]
 - 03. [[./02/03/index.org][Level of Detail]]
 - 04. [[./02/04/index.org][Rate of Change]]
 - 05. [[./02/05/index.org][Level of Abstraction]]
 - 06. [[./02/06/index.org][Level of Complexity]]
 - 07. [[./02/07/index.org][Process of Change]]
 - 08. [[./02/08/index.org][Creating POVs]]
 - 09. [[./02/09/index.org][Scale]]
 - 10. [[./02/10/index.org][Narrative]]
 - 11. [[./02/11/index.org][Propagation]]
 - 12. [[./02/12/index.org][Process]]
** 03. Frameworks
 - [[./03/index.org][Contents]]
 - [[./03/abstract.org][Abstract]]
 - [[./03/intro.org][Introduction]]
 - 01. [[./03/01/index.org][Dualities]]
 - 02. [[./03/02/index.org][Generators]]
 - 03. [[./03/03/index.org][Systems]]
 - 04. [[./03/04/index.org][Patterns]]
 - 05. [[./03/05/index.org][Standards]]
 - 06. [[./03/06/index.org][Legibility]]
** 04. Scaffolds
 - [[./04/index.org][Contents]]
 - [[./04/abstract.org][Abstract]]
 - [[./04/intro.org][Introduction]]
 - 01. [[./04/01/index.org][Metadata]]
 - 02. [[./04/02/index.org][Entity Model]]
 - 03. [[./04/03/index.org][Ontology Model]]
 - 04. [[./04/04/index.org][Pace-Layer Model]]
 - 05. [[./04/05/index.org][Succession Model]]
 - 06. [[./04/06/index.org][Goldilocks-Thresholds]]
 - 07. [[./04/07/index.org][Hard Soft Wet]]
 - 08. [[./04/08/index.org][World Models]]
** 05. Extensions
 - [[./05/index.org][Contents]]
 - [[./05/abstract.org][Abstract]]
 - [[./05/intro.org][Introduction]]
 - 01. [[./05/01/index.org][Identity]]
 - 02. [[./05/02/index.org][Citizens]]
 - 03. [[./05/03/index.org][Polis]]
 - 04. [[./05/04/index.org][Tools]]
 - 05. [[./05/05/index.org][Machines]]
 - 06. [[./05/06/index.org][Energy]] (Fire)
 - 07. [[./05/07/index.org][Structures]]
 - 08. [[./05/08/index.org][Surpluses]]
 - 09. [[./05/09/index.org][Distribution]]
 - 10. [[./05/10/index.org][Succession]]
 - 11. [[./05/11/index.org][Infrastructure]]
** 06. Methodologies
 - [[./06/index.org][Contents]]
 - [[./06/intro.org][Introduction]]
 - [[./06/abstract.org][Abstract]]
 - 01. [[./06/01/index.org][The Way]]
 - 02. [[./06/02/index.org][Cycles]]
 - 03. [[./06/03/index.org][Rules]]
 - 04. [[./06/04/index.org][Workflow]]
 - 05. [[./06/05/index.org][Replicatiors]]
 - 06. [[./06/06/index.org][Fabrication]]
 - 07. [[./06/06/index.org][Agency]] 
 - 08. [[./06/08/index.org][Iteration]]
** 07. Interfaces
 - [[./07/index.org][Contents]]
 - [[./07/abstract.org][Abstract]]
 - [[./07/intro.org][Introduction]]
* Components
** 08. Heliosphere
 - [[./08/index.org][Contents]]
 - [[./08/abstract.org][Abstract]]
 - [[./08/intro.org][Introduction]]
 - 01. [[./08/01/index.org][Habitats]]
 - 02. [[./08/02/index.org][Heliosphere]]
 - 03. [[./08/03/index.org][Biospheres]]
** 09. Origins
 - [[./09/index.org][Contents]]
 - [[./09/abstract.org][Abstract]]
 - [[./09/intro.org][Introduction]]
 - 01. [[./09/01/index.org][Preamble]]
 - 02. [[./09/02/index.org][Big History]]
 - 03. [[./09/03/index.org][Regimes]]
 - 04. [[./09/04/index.org][Stack]]
** 10. Lingua Franca
 - [[./10/index.org][Contents]]
 - [[./10/abstract.org][Abstract]]
 - [[./10/index.org][Introduction]]
 - 01. [[./10/01/index.org][Languages]]
 - 02. [[./10/02/index.org][Writing Systems]]
 - 03. [[./10/04/index.org][Incantation]]
 - 04. [[./10/04/index.org][Interoperability]]
 - 05. [[./10/05/index.org][A Common Language]]
** XX. Horcrux

The document manifests itself in many guises; as scroll,
codex, web page, or ebook.  But in every case its primacy is
unchallenged.  Documents reflect how our brains process
information, both as a linear narrative and a hierarchical
structure.

In all their manifestations a document is externalized shard
of the mind/s that created it.  And since a document can
exist outside of and independent of the mind, that part of
mind is immortal, so long as a copy exists.

The web has blured this distinction -- with web-applications
replacing web pages, or collections of pages into web sites.

We need to reclaim the document and put it back at the
center where it belongs, as a natural extension and
externalization of mind, which can gracefully degrade, be
serialized in countless encodings and recorded on countless
types of physical media.

But documents are not simply extensions and externalizations
of memories, they allow us to offload and extend information
from working, medium term and long memory.  In this way,
documents are an extension and externalization of cognition.

Jupyter Notebooks and Org Babel make it possible to combine
both narrative text and running code in documents in what is
called literate computing.

---

We think of documents as immutable objects -- physical
media; a paper book, magazine or newspaper, a pdf or epub
file.  This is largely a good thing, because an immutable
object is an exact copy, it can be transported, transfered
to another person, locked up in a box etc.

But there are other things we could do with documents.  They
could be dynamic, as in =literate computing=, where code runs
in the document that can accept manual input or pull in live
streaming data from outside sources that dynamically update
the document.  We could then flip this so that code in the
document makes changes and runs things elsewhere as in
=literate DevOps=.

Last night I was reading a new term =GitOps= which uses push
and merge requests to trigger testing and deployment
pipelines as part of =continuous integration=.

We can also create hierarchical libraries of documents which
inherit properties from other documents.  A book can be
thought of in this way, if each chapter is considered to
also be a stand-alone document.

We do this using a CSS-like cascading model of inheritance,
where properties are set and inherited be those underneath
it in the hierarchy unless it is explicitly (and-or
conditionally) overridden locally.

This is an especially powerful model because you can take a
document and plug it into different hierarchies that provide
different contexts.  Say you have a personal context at your
desk that includes all of your notes, contacts, messages and
personal library of documents.  You then want to present it
at a meeting.  So you take the document to the meeting, plug
in the document into the meeting context and each person in
the meeting is able to see a group context, as well as plug
it into their personal context at the same time.  Each
person can then share context from their personl context and
it becomes part of the group context.

Now let's expand the concept of the reader.  We assume that
documents have human readers, but over the next few years AI
systems will read and interact with documents as well.  So
we need documents that can be both human understandable, as
hierarchical linear narratives that are made up of text,
binary images, tables of data and live code.  But at the
same time, the document is also represented as a Quad Store
(triples + provenance) which is machine understandable.

In this way, your AI personal assistant will not only respond
to commands, but understand and interactively collaborate
with documents.

So let's rethink the document as a stack:


  - Human Consumer format -- html
  - Machine Consumer format -- QuadStore
  - Source -- Org syntax
  - -------------------------------------
  - index -- graph db -- 
  - 
  




** XX. Force

#+begin_quote
Yet among the numberless possibilities, the three sources of
power symbolized in the western movie—violence, wealth, and
knowledge—turn out to be most important. Each takes many
different forms in power play. Violence, for example, need not
be actual; the threat of its use is often enough to bring
compliance. The threat of violence can also lurk behind the
law. (We use the term violence in these pages in a figurative,
rather than literal, sense—to include force as well as physical
coercion.)

Indeed, not only modern movies but also ancient myths
support the view that violence, wealth, and knowledge are
the ultimate sources of social power. Thus Japanese legend
tells of sanshu no jingi—the three sacred objects given to
the great sun goddess, Amaterasu-omi-kami—which to this day
are still the symbols of imperial power. These are the
sword, the jewel, and the mirror.

The power implications of sword and jewel are clear enough;
the mirror's, a bit less so. But the mirror, in which
Amaterasu-omi- kami saw her own visage—or gained knowledge
of herself— also reflects power. It came to symbolize her
divinity, but it is not unreasonable to regard it as a
symbol of imagination, consciousness, and knowledge as well.

Furthermore, the sword or muscle, the jewel or money, and
the mirror or mind together form a single interactive
system.  Under certain conditions each can be converted int
o the other. A gun can get you money or can force secret
information from the lips of a victim. Money can buy you
information—or a gun.  Information can be used to increase
either the money available to you (as Ivan Boesky knew) or
to multiply the force at your command (which is why Klaus
Fuchs stole nuclear secrets).

— Powershift cite:toffler:1990power :p30
#+end_quote

#+begin_quote
Power comes in varying grades, and some power is decidedly
low in octane. In the fierce struggles soon to sweep through
our schools, hospitals, businesses, trade unions, and
governments, those who understand "quality" will gain a
strategic edge.

No one doubts that violence—embodied in a mugger's
switchblade or a nuclear missile—can yield awesome results.
The shadow of violence or force, embedded in the law, stands
behind every act of government, and in the end every
government relies on soldiers and police to enforce its
will. This ever-present and necessary threat of official
violence in society helps keep the system operating, making
ordinary business contracts enforceable, reducing crime,
providing machinery for the peaceful settlement of
disputes. In this paradoxical sense, it is the veiled threat
of violence that helps make daily life nonviolent.  But
violence in general suffers from important drawbacks.  To
begin with, it encourages us to carry a can of Mace, or to
crank up an arms race that increases risks to everyone. Even
when it "works," violence produces resistance. Its victims
or their survivors look for the first chance to strike back.
The main weakness of brute force or violence, however, is
its sheer inflexibility. It can only be used to punish. It
is, in short, low-quality power.

Wealth, by contrast, is a far better tool of power. A fat
wallet is much more versatile. Instead of just threatening
or delivering punishment, it can also offer finely graded
rewards— payments and payoffs, in cash or kind. Wealth can
be used in either a positive or a negative way. It is,
therefore, much more flexible than force. Wealth yields
medium-quality power.  The highest-quality power, however,
comes from the application of knowledge. Actor Sean Connery,
in a movie set in Cuba during the reign of the dictator
Batista, plays a British mercenary. In one memorable scene
the tyrant's military chief says: "Major, tell what your
favorite weapon is, and I'll get it for you." To which
Connery replies: "Brains."

— Powershift cite:toffler:1990power :p32
#+end_quote

The threat of physical force underpins pretty much all of
nature.  Predation goes to the core of all ecosystems,
living things feed off of each other, with a base layer of
living things that purely transmute the elements, light and
heat into living matter.  Each layer of complexity feeds off
of the layer below it.

Human societies are ecoystems as well, with predation
becoming the norm as group size grows larger than human
scales are designed for.  Even when group sizes are not
exceeded intergroup violence becomes the norm when groups
become sedantary.  It would seem that the only scenario
where humans don't do violence to each other is when groups
are within human scales and groups are at least semi-nomadic
and are not competing with other groups for resources.

Modern societies are getting less violent, but again, only
when resources are available to meet everyone's physical,
material needs.  But, unlike our nomadic ancestors this is a
false peace, as all societies are ultimate built on a
foundation that can deliver physical force against members
in the group.  Currencies are backed up, ultimately, by
someone with a gun.

If we can return to a mode of living within human scales and
allows us to be semi-nomadic without the need to compete for
material resources, I believe that we could build a society
that minimizes the need for that threat backing everything
up.  I say minimize, because it's nearly inconceivable to
contemplate any society that didn't require physical force
as final resort.  We will never be rid of the gun, not
completely.  It will still still be there, even it, like the
garrison of PLA soldiers in Hong Kong, it is never seen.

But what bothers me more about force is how much of it is
need to establish new economies and societies.  This has
been keeping me awake nights.  In one respect it's obvious
-- money, and lots of it.  Money is backed by threat of
physical force and can buy a lot of it.  But that only works
so far.  I'm starting to get a fuzzy sense of how it might
be done, using a combination of nudging, money, and
co-opting existing institutions to provide that backing if
or when it is needed.  In corrupt societies (all societies
are corrupt, just to different degrees) if you build
something that is valuable it is almost certain that someone
will take notice and put a gun to your head and take it from
you, unless you have the backing of another corrupt entity
that has your back.  The trick is to build a network of such
reltionships in which is mututally benificial.  Perhaps you
can trade information for force.  Information is far more
flexible a tool than force, and those with force need that
flexiblility to maintain control of their domain.

---

If hierarchy == chunking -- then what about Toffler's three
grades of power?  Information is an abstraction of symbolic
wealth -- wealth as in goods and resources that hold value.
Money then becomes a kind of battery of potential
eergy/force -- a rock at the top of a hill.  Force is
kinetic, in the process of being expended.  To maintain the
threat of violence one must have active agents and resources
which can be deployed at any time -- police, soldiers,
weapons, battlements and barbed wire.  This is very
expensive to maintain.  Anyone who has served in the
military or on the set of a movie being filmed know that
most of your time is sitting around, with brief bursts of
activity and terror.  For every minute spent between the
director calling "action" and then "cut" there are tens of
minutes sitting around waiting for lights and cameras to be
moved or changes in wardrobe and makeup..  Force is online,
money is nearline, and information is often offline.

So back to my question -- how does physical force chunk into
symbolic power -- money.  Money is exchanged for the
resources that are needed to inflict force -- food, shelter,
weapons, intelligence etc. So you are chunking potential
energy that can be converted indirectly into force.

I've always liked the idea of the volunteer fire department
-- it is the closest you can come to maintaining kinetic
force as potential force.  Instead of people waiting around
they are engaged in other, unreleated activities.

In our toy model civilization Culture is information, Middle
is money and SC is force -- though SC always leverages
information and money before resorting to force.

The bottom line is that there is no real power unless you
have resources that can be converted to or backed up by
physical force.

---

So how can we use the volunteer fire department model as a
core part infrastructure?  Will automation and augmentation
give people enough of an edge to replace full time expertise
with part time comptency?  Can telepresence be leveraged to
bring in specialists on a just-in-time basis that together
with part-timers with experience can replace many of these
power structures?  Fire, Police, Military etc.  In small
towns, of course, because that's what's there now, or at
least was there up till recently.

At national scales there is the concept of the national
guard, and if we employ ideas from Mollison and Alexandar we
could do it in large urban areas as well. 

This doesnt' answer my question -- but it's important all
the same.....

** 11. Curriculum
 - [[./11/index.org][Contents]]
 - [[./11/abstract.org][Abstract]]
 - [[./11/intro.org][Introduction]]
 - 01. [[./11/01/index.org][Learning]]
 - 02. [[./11/02/index.org][Pedagogy]]
 - 03. [[./11/03/index.org][Methods]]
 - 04. [[./11/04/index.org][Mastery]]
 - 05. [[./11/05/index.org][Curriculum]]
** 12. Governance
 -[[./12/index.org][ Contents]]
 - [[./12/abstract.org][Abstract]]
 - [[./12/intro.org][Introduction]]
 - 01. [[./12/01/index.org][Distributed Governance]]
 - 02. [[./12/02/index.org][Articles]]
 - 03. [[./12/03/index.org][Declaration]]
 - 04. [[./12/04/index.org][Rights]]
 - 05. [[./12/05/index.org][Duties]]
 - 06. [[./12/06/index.org][Constitution]]
 - 07. [[./12/07/index.org][Statutes]]
 - 08. [[./12/08/index.org][Electoral System]]
** 13. Infrastructure
 - [[./13/index.org][Contents]]
 - Abstract
 - [[./13/intro.org][Introduction]]
 - 01. [[./13/01/index.org][Commons]]
 - 02. [[./13/02/index.org][Systems]]
 - 03. [[./13/03/index.org][Natural]]
 - 04. [[./13/04/index.org][Material]]
 - 05. [[./13/05/index.org][Economic]]
 - 06. [[./13/06/index.org][Social]]
 - 07. [[./13/07/index.org][Health]]
 - 08. [[./13/08/index.org][Cultural]]
 - 09. [[./13/09/index.org][Individual]]
** 14. Economy
 - [[./14/index.org][Contents]]
 - [[./14/abstract.org][Abstract]]
 - [[./14/intro.org][Introduction]]
 - 00. Systems & Concepts
 - 00. Markets
 - 00. Chains
 - 00. Value
 - 00. Currencies
 - 00. [[./14/ww-gift.org][Gift Economies]]
 - 00. [[./14/ww-barter.org][Barter]]
 - 00. Supply
 - 00. Production
 - 00. Logistics
 - 00. Commerce
 - 00. Consumption
 - 00. Recycling
** 15. Culture
 - [[./15/index.org][Contents]]
 - [[./15/abstract.org][Abstract]]
 - [[./15/intro.org][Introduction]]
 - 00. Slow infrastructure
 - 00. Slow governance
 - 00. Long term investment
 - 00. Memory
 - 00. Commons
 - 00. Continuity
** 16. Canon
 - [[./21/index.org][Contents]]
 - [[./21/abstract.org][Abstract]]
 - [[./21/intro.org][Introduction]] 
 - 00. Canon
 - 00. 
 - 00. Biographical
 - 00. Dictionary
 - 00. Encyclopedia

  - epic narrative?
  - 
** 17. Origin Story
 - [[./22/index.org][Contents]]
 - [[./22/abstract.org][Abstract]]
 - [[./22/intro.org][Introduction]]

 - Parables
** 23. Archetypes
 - [[./23/index.org][Contents]]
 - [[./23/abstract.org][Abstract]]
 - [[./23/intro.org][Introduction]]
 - 00. Archetypes
 - 00. Events
 - 00. Figures
 - 00. Motifs
** 24. Time
 - [[./24/index.org][Contents]]
 - [[./24/abstract.org][Abstract]]
 - [[./24/intro.org][Introduction]]
 - Time and ROC
 - Terrestrial
 - Martian Time slip 
 - Meridians
 - Measurement
 - Units
   - Seconds
   - Minutes
   - Hours
   - Days
   - Months
   - Years
 - Epochs

** 25. Calendar
 - [[./25/index.org][Contents]]
 - [[./25/abstract.org][Abstract]]
 - [[./25/intro.org][Introduction]]
 - 00. Reckoning
 - 00. Rituals
 - 00. Convocations
 - 00. Elections
 - 00. Stages of Life
 - 00. Seasons & Microseasons
 - 00. Festivals

** 26. Space
 - euclidean, cartesian, hilbert
 - distances and time-to-destination (propagation)
** 27. Maps
 - [[./27/index.org][Contents]]
 - [[./27/abstract.org][Abstract]]
 - [[./27/intro.org][Introduction]]
 - 00. Spherical Cows 
 - 00. Projections
 - 00. Coordinate Systems
 - 00. Abstractions
 - 00. Metaphors
 - 00. Interoperability
 - 00. Territories
** 28. Population
 - [[./28/index.org][Contents]]
 - [[./28/abstract.org][Abstract]]
 - [[./28/intro.org][Introduction]]
 - Growth
 - Standard of Living
** 29. Stages of Life
 - Contents
 - Abstract
 - Introduction
 - childhood
 - adolescence
 - adulthood
 - old age

** 00. Standard of Living
** 30. Family
 - [[./30/index.org][Contents]]
 - [[./30/abstract.org][Abstract]]
 - [[./30/intro.org][Introduction]] 
 - 00. Imperatives
 - 00. Interpersonal
 - 00. Marriage
 - 00. Divorce
 - 00. Family
 - 00. Family Structures
** 31. Tribe
 - Territorial
** 00. Home
** 32. Commerce
** 33. Work
** 34. Place
** 35. Commerce
** 36. Polis
* Assembly
** 16. Branches
 - [[./16/index.org][Contents]]
 - [[./16/abtract.org][Abstract]]
 - [[./16/intro.org][Introduction]]
 - 00. Middle
 - 00. Culture
 - 00. Scope
** 17. Stages
 - [[./17/index.org][Contents]]
 - [[./17/abstract.org][Abstract]]
 - [[./17/intro.org][Introduction]]
** 18. Provisioning
 - [[./18/index.org][Contents]]
 - [[./18/abstract.org][Abstract]]
 - [[./18/intro.org][Introduction]]
 - 01. [[./18/01/index.org][APPL]]
 - 02. [[./18/02/index.org][Hoard]]
 - 03. [[./18/03/index.org][Primer]]
 - 04. [[./18/04/index.org][The OS]]
 - 05. [[./18/05/index.org][Arc]]
 - 06. Toolchain
** 19. Scenarios
 - Contents
 - Abstract
 - Introduction
 - 00. [[./19/ww-scenarios.org][Scenarios]]
** 20. Window
 - [[./20/index.org][Contents]]
 - Abstract
 - [[./17/intro.org][Introduction]]
 - 00. Inevitibility
 - 00. Milestones
 - 00. Threats
 - 00. Setbacks
 - 00. Canaries
 - 00. Boundries
 - 00. Metrics
 - 00. Models
 - 00. [[./17/ww-window.org][Window]]
 - 00. [[./17/ww-roadmap.org][Roadmap]]
* APPL
   - Patterns
   - Parameters
   - Theses
   - Keystones
   - Entities
   - Concepts

** Polity
We outlined broad concepts and structures for governance now
we can put together an actual working polity -- the polity
in our case is both public and private.

We have to merge them together at appropriate scales.

Once we have polity worked out, then we have a foundation
for the three branches: middle, scope and culture.
** Middle

MIDDLE is infrastructure -- up till now we've had public
infrastructure and private infrastructure -- which we need
to merge into a commons

MIDDLE boils down to three things -- process management,
feedback loops and physical stuff -- assets

** Culture 

  Domus  -> unit of local organization
  Shop   -> unit of local organization 
  Polis  -> unit of regional organization

  CULTURE
  ARC

** Scope
:PROPERTIES:
:ID:       910fbbdc-f293-499e-af39-3b583bfceab1
:END:

  Guild   -> unit of global organization
  CONTACT
  SPECIAL CIRCUMSTANCES

** Arc

ARC is part of Culture, but is so big it deserves it's own
major grouping.

  Distributed - system
  discovery
  MAP -- the distributed index
  succession stages
  dark arcs & local libraries
* Back Matter 
 - Appendix
   - W&W meta
     - specification -- format
     - markup language
     - conventions
     - media formats & layout
 - Bibliography
 - Ontography
 - Index
 - Colophon


