#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Warp & Woof Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[./index.org][top]]] prev [[[./plan.org][next]]]

* Warp & Woof Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/intro.org
:Created:  2018-02-15T20:19@Prek Leap (11.642600N-104.919210W)
:ID:       f8ae9d01-083a-4598-84e7-249d560fca6c
:VER:      571972838.678903093
:GEO:      48P-491193-1287029-15
:BXID:     proj:OKM3-3142
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


** Intro Second Draft
[2018-05-22 Tue 17:14]

Why we need all this mishegoss?  Most of us reading this
will have grown up in a middle class background with a
standard liberal education that makes many assumptions about
how we see the world as being universal or even desirable.

I hope to establish a new paradigm that replaces the
assumptions that have been imposed on us by the evololution
of state legibility and high modernism which in practice
simplifies complexity down to a map showing a handful of
parameters, axis and scale.  We forget that there is a very
real distinction between local and synoptic knowledge.  The
laster is by definition has less detail, less knowledge in
it because it needs to take something that can't load into
our heads because they exceed human cognitive and memory
limits.  The bigger the territory you try to fit in your
head the lower the LOD, the lower the LOD the more lossy it
becomes.

The modern world is becomming increasingly complex, but we
can't handle all of that complexity so we create ever more
simplfied maps to get around that only makes this worse.

The tools we use to understand the world are far too
simplisitic to be of much use any longer -- we need broader
range of tools to make sense of the world.  The problem with
this is that simplicity is "user friendly" and fast.
Complexity has a steep learning curve and slows us down.  We
trade speed and easy for depth, malleability, wisdom and
familiarity and efficiency.  Let's consider the last two,
familiarity and efficiency because that is the biggest thing
we loose when we spend most of our time in a epistimic,
synoptic contex.

It's long been understood that small farms are far more
productive hectare for hectare than large farms.  This is
because a small farm is familiar to the farmer, it is at a
scale small enough to fit in his head, Bill Mollison said
that he is often asked how large a farm should be, and his
answer was always "as large as you can handle".  You can
only handle what you can fit in your head, and in a farm
there is a lot to fit in.  Something becomes familiar when
it has been encountered so many times that it becomes
something like muscle memory, your brain understands and and
use that massive nexus of links to all the times that you
have encountered it so that it can be accessed sub
consciously.  We all use this in one form or another.  If
you commute to work every day, or go to the same market at
the same time every day, when waking or driving at the time
and you become distracted or lost in thought, you will
suddenly realize that you have gone to that place or at
least started to go there automatically, even if you
intended to go somewhere else.  Familiarity allows us to go
on autopilot so we can concentrate conscious efforts on
other things.  This is the goal of Mastery of anything, to
become so familiar with something that you can don't need to
pay attention to the larger sequence so that you can notice
and control the small details that a beginner can not see or
control because they need to pay attention to to things that
are familiar to the master.  In a small farm, the farmer
intimately knows the local climate, where the wind blows
from in the winter or summer.  Knows all of the plants and
animals both domestic and wild on the farm, their
charateristics their behaviors and how they compliment each
other.  The farmer knows the soil, and what plants need to
be grown to replace nitrogen, or which plants act to repell
insects which each the crops that can be sold.  The list is
almost endless, the tools, techniques that have worked and
which ones don't work, the countless experiments to see if a
new variety or breen works better or not.   This constitutes
a vast storehouse of knowledge that can't scale beyond what
the farmer can control.  Once this threshold has been
crossed, the farm might become larger but it will
increasingly become less efficient as the farmer will have
to reduce the complexity level to be able to control it.
Systemic problems will begin to appear, slowly at first and
then frequently and more severely.  Pests, soil depletion,
waster and waste management, disease and the less
flexibility there will be when a crop is ready to go to
market.  When everyting is in basket, you only need to have
one failure that will destroy everything.  In a small farm,
there are many baskets, so the failure of one thing will not
be catastrophic.

The difference bewtween farms in Thailand and Cambodia can
often be dramatic.  Thailand has not experienced war or
civil unrest that has had any real impact on farmers for
more than a century.  Next door in Cambodia the country is
still rebuilding from the temporary insantity of the Khmer
Rogue who systematically wiped out all local knowledge,
often by killing those with that knowledge, and trying to
replace it with a legible state system based on a very
simplistic model that did not take into account local
conditions, human nature and limitations, or much of
anything that wasn't contained in a single slender book that
was little more than a pamplet.  Human civilization can not
be reduced to something that can fit in your pocket.
Decades later the farmers in Cambodia are still going
through the slow process of becoming familiar with their
farms and how to farm them.  This is a process that takes
generations and decades.  And it doesn't help that most
outside help has been in the form of forcing them to adopt
epistemic techniques used by large farms rather than to
reinvent what had been lost.  They are not being allowed to
go back to reclaim what they have lost before being allowed
to go forward. The difference is visible even to the
untrained observer.

We've been quite hard on the epistemic and synoptic so far
but that doesn't mean they should or even can be abandoned.
Most human progress in the past two hundred years has come
from developing epistemic and synoptic forms of knowledge
and seeing.  

Familiarity and isolation often go hand in hand.  One may
have mastered the local, but have no knowledge of the
global.  More often this traps people in one place and
context.  The epistemic and synoptic opens up the entire
world to us, something that most of humanity up until recent
times has been trapped in.  The local becomes a barrier
where outside knowledge takes a very long time to
penetrate.  News from outside the familiar is filtered only
through filters that change at a slower rate of change in
the faster global pace-layers.  The result is often ignorance,
stagnation and a mistrust of outsiders.  And why not?
Strangers are locally illiterate and don't share enough
common knowledge to make effective knowledge possible.  It
is only when a handful of local people, by accident or
extreme acts of bravery venture beyond their zone of
familiarity and come back to translate what they have
learned.  This is often a failure.  The locals don't want to
hear about anything from outside, and the new experiences
outside had changed the travelers to the point where they
find their old homes to be claustrophobic and confining and
the people their inflexible and incapable of change.

The synoptic and epistemic are a find of lingua franca, a
simple maps that is relatively easy to learn and integrate.
It has to be be simple in order to work at large scales.
This lingua franca only works when it is based comminality
shared between everyone, on universals that anyone can
easily recognize and comprehend.

In this way, we make what Steward Branch called "the
progress... from hick to metropolitan to cosmopolitan,
and everything the dictionary says that cosmopolitan means:
multicultural, multiracial, global, worldly-wise, well
traveled, experienced, unprovincial, cultivated, cultured,
sophisticated, suave, urbane." cite:brand:2010whole-earth-discipline

They synopic has made possible for over 7 billion people,
heading towards 10 billions to be able to live together on
this planet with increasingly less bloodshed and at an
increasingly better standard of living.  This has allowed
humans to cooperate on a scale that would have been
unimaginable two hundred years ago.  It has greatly reduced
the threat of war, nearly doubled our lifespans, wiped out
pain and disease and discomfort to a degree that our
ancestors could not have imagined.  The average person
living above the poverty line has, in many respects a far
better standard of living and wealth than the rich and most
powerful monarches in past Ages.  Even in the nineteenth
century, Queen Victoria, arguably the richest and most
powerful person on the planet at the time was terrified at
the prospect of first getting pregnant because of the
dangers of childbirth.

But living only the at the global strips us of much of what
it is to be human it denies us participing in any
substantive community, fragments relationships with parents,
children, friends and lovers.  It leaves us living in a
sterile environment striped of meaning, purpose, intimacy
and belonging.  The admonition to "think localy and act
globally" doesn't cut it.  The stupidity comes in when it's
thought that this needs to be a zero-sum choice, that
everything has to be either metic or epistimic, thinking
that they can't exist at the same time and reinforce each
other rather than forcing us to be smart locally and dumb
and lost globally, or smart globally but any familiarity
that as Olson said, quoting Heraclitus, leaves us estranged
from what we are most familar.  If anything this work is an
attempt to reconcile those two extremes in a way that we can
embrace the advantages of both.

We must all learn to become holons with a dual nature that,
allow us to be both local and familiar wholes /and/ global
and cosmopolitan parts of something larger than ourselves.

Now here comes the catch, this all sounds wonderful, but the
truth is that not many people can do this.  Most of us can
be local and isolated or global and connected and largely
miserable.  We can grok the idea of having two natures, but
to be able to internalize and switch between them is pushing
the envelope on humam cognitive limits.  it would seem that
this leaves humantity in a conundrum where we have to choose
between two different modes of living which are moth
limiting and liberating in different ways.

What we haven't factored into this dilemma our unique human
ability to extend and externalize both our mind and bodies.
This process started with our ability to make tools, then
reached a complexity threshold when speech emerged, and then
another when writing systems emerged and then again when we
learned to connect complex tools (machines) to external
power sources that could be turned on and off at will, first
steam, then petrochemical and finally electrical.  Most
recently we crossed the remarkable threshold of being able
to combine all of these things in machines that could think,
by employing a primitive form of reading and writing which
gave us computers which are not being used to control
machines on our behalf.  And as if this wasn't monumental
enough we have learned not only to read our own genetic code
which has evolved over billions of years using a brutal
random mechananism and will soon be able to rewrite that
code as easily as we now write a rant on facebook.  Humanity
is a storu of steady progression of learning to extend and
externalize ourselves and in doing so connecting us together
and soon reconnecting us to the world around us.

Warp & Woof is an attempt to bring the formidable array of
cognitive tools, knowledge and technology to make it
possible for most people to be able have dual metic and
epistemic natures.  We believe that this could result in the
crossing of another complexity threshold that will allow us
to fix many of the problems of industrial civilization and
begin building a post-industrial and post-scarcity
civiliztion that makes us not just more prosperous, but to
return to a life of purpose and meaning that was lost in the
psychological barrens of industrial civilization.

Moreover this is still only part of the story, because if we
can restore the local without having to abandon the global
we can learn to put mastery and familiarity back into common
practice and make a decentralized antifragile network of
many locals more efficient than our present fragile
centralized system that favors the few over the many.

This is a vision for a better future, not a utopian
paradise.  I suspect that paradise is not what it's cracked
up to be any way.  No matter how much we try to improve
things humans are quirky and more often than not, complete
flakes.  The bones of the universe only promise uncertainty,
entropy and chaos as the norm with order and life as they
exception.  We need to learn to accept that and get on as
best as we can.  That doesn't mean that we can't make
progress, just that we progress towards an infinite horizon
that we can never reach.  Personally I wouldn't have it any
other way.

This is the vision that informs and guides this work. Now,
follow the bouncing ball, altogether...




** Intro First Draft
*** Table of Contents

  - A Generative Genome for Mankind
  - From First Principles
  - Extension & Externalization
  - inevitable but unpredictible: anticipating post-scarcity 
  - Enlightenment Rebooted
  - Fifty Year Window

*** Introduction

At present. civilization is still at the whim of
evolutionary natural selection, random mutations happening,
with the successful ones replacing older ones.  We might
think we are in charge, but only as individuals, and even
then... not so much.

Mankind is at the brink of being able to take conscious
control over dna -- within a few decades we will be in
complete control of the design of all biological systems --
but that is mucking with individual genomes -- there are
larger meta structures of how these organisms organize and
interact to form large complex systems.  These systems exist
outside of human scale -- either too small or too large and
slow for us to easily see, let along understand, let along
change or control in any meaningful way.

Civilization is one such system -- and our clumsy attempts
at steering civilization or even understanding it is not
enough.  Collectively we are making a mess of things -- we
need to start understanding how civilization works, and how
we can shape and eventually manage it before we overrun the
petri-dish and trigger a massive die-off and collapse.

We need to work out a genome for human civilization and then
a CRISPR type mechanism for fixing things and test new ideas
in controlled ways.

This will never work if we take a top-down command and
control approach -- we need to understand how to inject
changes from the bottom up and when they've been tested and
work, then let them propagate.

We'll never be able to control civilization in the same way
that say you can control a car when driving down the road.
Complex systems make that impossible -- but I believe we can
learn to shape civilization slowly over time towards desired
outcomes -- as Kevin Kelly observed, you can tell what will
be inevitable but now the specific form that that
inevitibility will take. cite:kelly:2016inevitable

What this works sets out to do is to create methodologies
for understanding and modeling civilization and then work to
make desired outcomes inevitable -- once they become
inevitable they can be shaped to some extent -- thought
there is no way of knowing what form that will eventually
take.

I am, personally, a extremely pessimistic person, I have
never seen much hope for the human enterprise in any short
term and I still believe that we are all too capable of
derailing the progress man has made since 1800.

But that doesn't mean that I'm not going to try.  I've
always personally believed that the only way you can truly
fail is if you give up.  Steven Pinker's relentless optimism
about the reality of human progress and that it can continue
to not only improve but that improvement can continue to
accelerate has worn me down to the point where I admit that
he has a made a very good case.

But this will not happen unless all of us work together to
make sure that this happens.  The challenges ahead of
humanity just in this century alone almost beggers the
imagination.  It will take every ounce of imagination,
strength and as Pirsig said, gumption to make it happen.

A framework for understanding and changing the genome for
human civilization would be a very useful part of this
effort -- if successful it would make it possible to
coordinate our efforts better, identify what things are
being worked on and what areas aren't getting enough
attention.  It could help provide metrics for understanding
where we stand, where we are going and provide clues of how
to correct mistakes and move more clearly in the right
direction.

This is an audacious undertaking -- and something that I
have been working on full time for nearly two decades.  The
project has now come to the point where all the pieces are
coming together and the broad outline is visible.

Now that I've reached this stage, the project needs to make
the transition from being a solo effort to a building a team
to begin filling in the blanks, run experiments in the form
of projects that are designed to make practical improvements
in people's lives today, while learning to map out the
genome, how it works and how to improve it.  Some of this
work will be traditional R&D, some NGO projects.  But the
vast majority of the projects will be designed to be
not-for-profit.  In other words they will be designed to
make a profit, and be self-sustaining, but the larger goal
for each project will be to materially improve people's
lives first, and making a profit second.

The entire zero-sum mantra of "maximizing shareholder value"
is nothing short of obscene, and growing at all costs, when
growth is simply making a small group of people wealthy
should be considered to be the lowest of human activities
and should be held in the same contempt and a crime against
humanity.  The problem is that the system has so corrupted
us, that most people can't understand that the world was not
always this way, and it doesn't have to be in the future.
We can all strive to give everyone a high standard of
living, a life with purpose, without fear, or pain.

We can not tolerate zero-sum anything any longer.
Everything we do must be designed to be positive sum --
things that help me as much as they help you and everyone
else.

Any time someone tells you, that you have to suffer in order
to achieve an important goal is selling you a lie.  If
something doesn't make financial and economic sense, there
is something wrong, because it won't work, and the only
people who will subscribe to it are well-meaning chumps.
What DOES work is to teach people how to change their
behavior to do things in ways that improve their lives --
this is difficult, we aren't very good at changing -- and
this is why it won't happen overnight.  The older you are
the less capacity you have to change.

For this reason, it's good that we we still have time enough
to teach the next generation positive-sum habits.  It's very
likely that human lifespans will increase to hundreds of
years or even longer in the next few decades.  That is good
news, because it still gives most of the zero-sum generation
time to die before we start sticking around for significant
fractions of millenia.

And as these new generations grow older and older, they will
be old enough to have seen and understand much longer term
processes than we short-timers can today.  This will be
crucial to the long term survival of our species and
successful stewardship of our planet, and eventually the
rest of the solar system as humanities childshood ends and
take the first steps towards becoming a a mature
technological species.

The most terrible crimes against mankind since the 20th
century were the Year-Zero men

It is hoped that we are nearing a time when it will become
impossible for another of these monsters to take control.

The next step is to eradicate the Zero-Sum men and women
whose whole existence is to take from you to profit me.

Building a positive-sum genome for human civilization from
first principles would be a good first step.

Can we pull this off?  The pessimist in me is shouting in
one ear that it's a real long shot.  But then, the tiny
optimist's voice is whispering in my other ear is saying,
"hey, that loudmouth might be right, but what have you got
to loose.  It's worth a shot, isn't it?"

*** Extension & Externalization

If pressed to sum up Mankind in a few sentences I would say
that Sapiens (the sub species of Man that we belong to)
history is no different from any other species on this
planet except for a single thing.

Sapien's large cerebral cortex makes it possible for us to
be goal driven, we can think abstractly out how to achieve
goals that might take many intermediate steps to achieve.
Not even any of our other other primate cousins can do this.
It enables us to think of time as linear, with a past, a
present and a future.  All other creatures live in a
perpetual present with no future, and a past that are made
up of memories of past events, but are not ordered into
causal chains.

This one ability to understand abstract concepts that
require multiple steps and imagine potential outcomes at the
end of all of those steps set all of human prehistory, and
with the invention of written languages, history in motion.

It made it possible for us to take an innate ability to be
able to ,modify and manipulate things in the environment
into tools.  But with with the addition of our ability to
envision multiple stage goals, these tools became
increasingly refined to the point where they became
extensions and eventually externalizations of our mind and
muscle.

Our entire history is the story of extending and
externalizing our mind to reshape the world around us.  The
first step was to externalize our mental abilities to be
able to communicate these abstract ideas with others.  This
gave us spoken language.  Taking this a step further we
learned to create symbol systems that could transcribe
concepts and human speech into clay, stone and parchment
that could be duplicated and sent to distant places both in
space and literally into the future without the person who
first recorded those ideas ever meeting or knowing who wouid
later encounter them.

The invention of moveable type and the printing press made
it possible to make countless and exact copies of written
messages which vastly reduced copying errors, which are the
bane of all communications, and potentially be read not only
by every living person alive when it was written, but every
living person who would ever live in the future.  It took
blind evolutionary processes billions of years to evolve
RNA/DNA to be able to do that.  Sapiens did it in the
evolutionary heartbeat of a humming bird on crystal meth.

Think about that for a second, Man can now do the same thing
that the blind chance mutation and natural selection process
of evolution as deterministic goals and we soon will be able
to do this in human time scales.

It's that last part which is particularly important, because
Sapiens don't scale, or at least we really suck at it.  All
of human progress has been a double edge sword that has
reaped astonishing achievements, while at the same time
making other things worse, and often much much worse.

When I talk about human scales I am /not/ talking strictly
about Rousseau's return the the original state of nature.
Though the idea of prosperous egalitarian bands of hunter
gatherers wandering the planet and living a pretty good
life, in comparison to that of the sedantary farmers and
urbanites who replaced runs counter to a growing body of
evidence that it is little more than a secular myth adapted
from the Christian meme of a man's fall from grace and being
driven from the garden is simply not supported by the
archeological evidence.  That said, group sizes that
correspond to bands (15-40) are human scales where groups
can function well.


All of Sapien's brainy achievements were only possible
because surpluses of food, and material goods needed for
survival could be produced that allowed a small portion of
the population to do things that were not directly related
to immediate survival.  Those surpluses let a small number
of people spend most of their time thinking.  That's the
good news.  The bad news is that in oder to do this,
hierarchical societies were needed that were based on
inequalities that took the surpluses created by some members
of the group and gave them to a few people who were in power
and a handful of others whose job it was to think.  That
system is called slavery.


*** Enlightenment Rebooted


#+begin_quote
More-over, this is classic motte and bailey. The motte is
"The US consitution was not unique" with the bailey being
"The US government was not unique". The later is simply and
totally false, a revival of the ancient idea of democracy
coupled with a strong rule of law and a respect for
individualism and the inalienable rights of man was a
completely radical thing at this point in history. The parts
were not first invented here, but they were first put
together into a coherent whole.

....

The Enlightenment (the movement) was based on
empericism[sic] and experimentation far more than pure
rationalism, even though enlightenment (the philosophical
concept) might have been formulated in different terms.

— /r/j9461: [[https://www.wsj.com/articles/the-dark-side-of-the-enlightenment-1523050206][Comment on The Dark Side of the Enlightenment]] | WSJ
  https://www.reddit.com/r/slatestarcodex/comments/8azimq/the_dark_side_of_the_enlightenment/dx3axmb/
#+end_quote


#+begin_quote
How can we help our brains to realise that things are
getting better? Think of the world as a very sick premature
baby in an incubator. After a week, she is improving, but
she has to stay in the incubator because her health is still
critical. Does it make sense to say that the infant’s
situation is improving? Yes. Does it make sense to say it is
bad? Yes, absolutely. Does saying “things are improving”
imply that everything is fine, and we should all not worry?
Not at all: it’s both bad and better. That is how we must
think about the current state of the world.

— [[https://www.theguardian.com/world/commentisfree/2018/apr/11/good-news-at-last-the-world-isnt-as-horrific-as-you-think][Good news at last: the world isn’t as horrific as you
think]] | Hans Rosling, The Guardian 2018
#+end_quote





* Notes

#+begin_comment
Didn't know where else to put this....

Today, thinking about the end game for.... all of this I
started to ask the question "what the fuck are we really
building here?"  Fair question.

Is it an AI?  No, an AI will have it's own organization,
internal memories, abstractions and world view -- just as we
do.  But, I realized, an AI will still need to extend and
externalize in the same way that we do.  AIs will need to
cooperate with people and with other AIs -- this has nothing
to do with the great AI freakout or consciousness or super
intelligence -- that all could be fantasy or grim reality --
that remains to be seen -- but what is clear is that AIs
will have to solve many of the problems humans are trying to
solve which how is to communicate and cooperate to achieve
goals as a group which are larger than the sum of their
parts.

What we're building here is a means for pulling all
extension and externalization into a single distributed,
federated interoperable system so we work together, not
against each other, while still allowing individual agency
and self-determination (a whole other kettle of fish).

Perhaps, just maybe, warp & woof holds the potential of
staving off the existential AI threat that has a lot of very
smart people today very worried.  Because if we all learn
how to play together according to the same humanist
principles, not just people, but machines too, and evolve
together as partners so that those principles become an
integral part of who we are, then perhaps we will have
passed the Great Filter that has been suggested as an answer
to Fermi's Paradox.
#+end_comment


** Notes on APL and TWB


W&W will be to APPL that /A Timeless Way of Building/ 
(TWB) cite:alexander:1979timeless is to APL. cite:alexander:1977pattern


TWB starts with this:

#+begin_quote
/The Timeless Way of Building/ is the first in a series of
books which describe an entirely new attitude to
architecture and planning.  The books are intended to
provide a complete working alternative to our present ideas
about architecture, building, and planning—an alternative
which will, we hope, gradually replace current ideas and
practices.

— A Timeless Way of Building
  cite:alexander:1979timeless
#+end_quote

#+begin_comment
Replace architecture and building with civilization and it's
not a bad description of W&W and APPL.

TWB was published two years after APL, which answers the
chicken and egg question, but it also makes sense.  TWB
couldn't have been written until after they had all but
completed APL.

TWB is divided into three Parts: The Quality, The Gate, and
The Way.

   - /Quality/ is QWAN.
   - /The Gate/ is the Patterns.
   - /The Way/ is how to get QWAN using the patterns.

The organization of the book also is design to work at
multiple LODs, like /The Plan of St. Gall/ with an outline
of the entire work, and then detailed TOCs at the beginning
of each volume.



TWB is almost mystical -- it does not come across as a
practical text on how to build according to his philosophy
and methodology.  It's almost a manifesto.  This was on
purpose, but as some reviews have noted, it could be one
reason that it hasn't been treated as seriously as it
should.  It's too outside of the mainstream, too easy to
dismiss and doesn't provide a bridge for architects and
builders to cross from their world into his.

The Oregon Experiment (which I still haven't seen) seems to
be where he shows a concrete example of how to plan, design,
and build.

So what about W&W?  We don't need to build the same bridges
that Alexandar should have, but at the same time we need to
bridge the gulf of how civilization is today, how the
present attempts at change are useless and all but
worthless.  So I suppose we do need bridges.  But is W&W to
be a bridge or manifesto?

I don't want to be too mystical, but I also don't want to be
too concrete which is why I'm so attracted to the Plan of St
Gall (PSG).  St Gall was never built -- so the designs based
on the plan are -- as the title says -- paradigmatic. PSG
delves deep providing historical, social, economic and
archaeological context and evidence.

So I suppose that W&W needs to blaze a path between the two
-- so that it's part Timeless Way and Part Plan of Arc Nong
Pao.

In fact that's about right -- first volume should be closer
to TWB and the following volumes should provide three Plans
-- two on earth and one on mars.

In that respect I suppose we can borrow many things from
Mollison's Designer's Manual -- which is, in many respects,
a path between TWB and PSG.

The whole pace-layer model will take a bit to lay out -- and
we will have to make a case for why we are on the wrong
path, and how we have no choice but to start from first
principles.
#+end_comment


** References
