#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Plan of The Work
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[./index.org][top]]] [[[./intro.org][prev]]] [[[./synopsis.org][next]]] 

* Plan of The Work
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/00/ww-plan.org
:Created:  2018-04-21T08:55@Prek Leap (11.642600N-104.919210W)
:ID:       c054aa11-d974-428c-9324-e084a91cc4d7
:VER:      577547780.266428921
:GEO:      48P-491193-1287029-15
:BXID:     proj:OYK7-7861
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Table of Contents

- [[id:0ed7184f-ba2a-45f5-9460-efde6ff00081][Introduction]]
- [[id:62eb03eb-fa14-42be-be07-a97dd195396f][Works]]
  - [[id:911ca1c6-3c31-45ea-80b8-cf582c940f65][Warp & Woof]]
  - [[id:72728741-9f9c-4b4f-9dff-6eba95bf77b3][A Pace-Layer Pattern Language]]
- [[id:6fbd41ac-9947-4358-875e-5d2b798a8f93][Hoard]]
- [[id:18e41791-cb01-4114-943d-a26bc95c1099][Primer]]
- [[id:6fcee20c-2777-47e5-8724-f5bae317394e][Middle]]
- [[id:401aaec4-899d-4972-b500-ea222cef7c2c][Arc]] 
- [[id:682f45da-1356-4b4a-a911-8abb845cc9a7][Projects]]
- [[id:7466a761-d9a2-4a2a-aeb9-10aa36963509][Programs]]
- [[id:34865dc8-5986-4f88-bb7b-c5eda8675fd4][Initiatives]]

** Introduction
:PROPERTIES:
:ID:       0ed7184f-ba2a-45f5-9460-efde6ff00081
:END:

#+begin_quote
Everything that is not forbidden by laws of nature is
achievable, given the right knowledge.

— David Deutsch 
#+end_quote


Chenla is a series of works, projects, programs and initiatives that
aim to demonstrate a way for Mankind to build advanced distributed and
stable technological civilization from first principles. Chenla is not
proposing the design of any specific civilization, rather, the goal is
to provide a generative framework for the present and future
generations to make any number of civilizations.  The history of human
civilization is iterative and bottom up, building on the civilizations
that came before them.  With each iteration we learn a little more,
and do a little better.  It is hoped that these works will be of use
in making that process a little less random, a little more focused,
and a lot less disruptive and destructive as it has all too often been
in the past.

#+begin_ascii
            Warp & Woof   <---------\
                 \/                 |
                APPL      <---------| 
                 \/                 |
               Hoard      <---------|      ------ A R C --------- 
                 \/                 |          Dark Archives 
    ---------- Primer ----------    |      .......................
            M I D D L E             |       Nearline Repositories
    ............................    |      .......................
      Pattern Recognition Layer <---|<--->    Online Libaries
    ............................    |      =======================
          Discovery Layer       <---|         Map-Index Layer
    ............................    |      .......................
          Rule Set Layer        <---|        Collection Layer
    ............................    |      -----------------------
         Process Chain Layer    <---|              / \
    ............................    |               |
           Physical Layer       <---|               '----- W O R L D
    ----------------------------

#+end_ascii

** Works
:PROPERTIES:
:ID:       62eb03eb-fa14-42be-be07-a97dd195396f
:END:
*** Warp & Woof
:PROPERTIES:
:ID:       911ca1c6-3c31-45ea-80b8-cf582c940f65
:END:

An introduction to the concepts used in *A Pace-Layer Pattern
Language* and *A Primer*

*** A Pace-Layer Pattern Language (APPL)
:PROPERTIES:
:ID:       72728741-9f9c-4b4f-9dff-6eba95bf77b3
:END:


APPL is meant to expand on the world in Christopher Alexander's A
Pattern Language (APL) which was published in 1977
cite:alexander:1977pattern

Where APL focused on towns, cities and the architecture of builds, the
scope of APPL will be to encompass as aspects of civilization and
human existence.

In addition to /APL/-like Patterns, APPL will include the following
categories:

  - Patterns :: Archetypal Design Patterns for structures,
                settlements, social organization and systems. 
  - Parameters :: Constants and Variables.
  - Theses :: Assertions that may be moral or ethical but
              may not be justified purely on logical or
              evidence-based grounds. 
  - Keystones :: Key Reference Designs and Specifications.

Another departure from APL will be that APPL will be what is called a
/literate program/ which combines text together with computer software
code.  The code is executed when the pattern is generated.  This makes
it possible for patterns to be machine understandable.  This will be
important in the next work in the series, /The Hoard/ which will is a
group of /generative grammars/ which are expressed as both a text
narrative and code.

APPL will establish the broad patterns that can be used to construct
generative grammars that will be adapted to account for local context
(conditions) in the /Hoard/.

** Hoard
:PROPERTIES:
:ID:       6fbd41ac-9947-4358-875e-5d2b798a8f93
:END:

A hoard is a collection of treasured goods and information.  In Old
English, the word for dictionary was a /worde hord/.

It is a combination repository under version control that contains the
source code for generating Primers.  In a Platonic sense, APPL is the
world of archetypes and the Hoard are the shadows on the wall that we
can see and interact with. The APPL is a way of thinking globally, and
a hoard pragmatically thinks and acts locally.

Hoards are organized using two different models, the /Pace-Layer/
model, and a /Succession-Stage/ model.

As in the previous two works, the Hoard is not a prescriptive design
for civilization.  Rather it is meant to create generate grammars that
can be used to create very long term civilizations from first
principles that are distributed /and/ antifragile.

A Hoard includes plans, designs, standards, specifications based on
/keystone/ reference designs and patterns from the APPL which are
adapted for a range specific needs of a ecological, economic,
technological, and cultural niches of any given civilization.

** Primer
:PROPERTIES:
:ID:       18e41791-cb01-4114-943d-a26bc95c1099
:END:

A Primer is a collection of prescriptive and descriptive
knowledge needed to build a specific civilization.

In many cases the only way to develop a keystone reference design is
by building a number of designs for specific needs.  So in order for
us to come up with many of the patterns, generative grammars and
keystone designs, we will start with specific designs, identify what
makes it work and what can be used as a universal principle and then
work backwards.  The Primer will include all of this specific design
and development work that was done to develop patterns and keystone
designs.

** Middle
:PROPERTIES:
:ID:       6fcee20c-2777-47e5-8724-f5bae317394e
:END:
** Arc
:PROPERTIES:
:ID:       401aaec4-899d-4972-b500-ea222cef7c2c
:END:
The Archive, or Arc for short, is collection of digital data, texts,
images, audio video, 2D and 3D vector graphics and code that
represents the a subset of Mankind's recorded memory and experience
that provides the context and background needed to build and maintain
a civilization.

** Projects
:PROPERTIES:
:ID:       682f45da-1356-4b4a-a911-8abb845cc9a7
:END:
** Programs
:PROPERTIES:
:ID:       7466a761-d9a2-4a2a-aeb9-10aa36963509
:END:

*** Women in Cambodian IT

Women have found it challenging to enter the IT industry.
The industry is well known for being male dominated, and at
times is hostile to women entering the field.  Employers
generally understand that this is something that has to
change, but there aren't as many women graduating from IT
programs as men, in large part because the hostility to
women is endemic to IT educational programs as well.

In addition to the the challenges that women face in
developed ecconomies, women in developing economies have
additional challenges and responsbilities and expectations
from their families.  The nuclear family is predominant in
developed countries where after finishing school people are
not expected to take as large a role in the day to day life
of their parents and grand parents.  Cambodia is
predominately made up of traditional extended families who
place much of the burden for taking care of 2-3 generations
and earning money for the family.

Cambodian IT education is focused on providing skills in
technologies that are traditionally low paying and
considered to be low skill.  This includes web application
development, low-end mobile application development, and
Windows based middle-ware that is only used in large and
medium sized corporate environments.  The technologies that
are being used by startups the tech giants like Facebook,
Google and Amazon use cutting edge technologies which are
not being taught in Cambodia.  This is holding back foreign
investment in the country because there is no labor pool of
people with the skills that IT companies need to locate in
Cambodia.  This also means that companies which are already
in Cambodia are not able to adopt these new technologies
which would make them competitive with foreign companies
because no one is qualified to support those technologies.

We believe that the solution to these challenges is to teach
the latest technolgies to Cambodian women and take advantage
of the trend towards Remote Work Companies.  There are now a
number of companies that are worth hundreds of millions of
dollars that have hundreds of employees who all work
entirely from wherever they live.  These are progressive
companies who pay market rate or higher salaries and
benifits as any other IT company, but they have no offices.

Our challenge will be to provide women with the skills that
these companies need, place them in these companies, and
provide what Virginia Woolf called, "a room of one's own",
so that Cambodian Remote workers have a place where at or
near home where they can keep flexible hours that allow them
to take care of their families expectations, and provide a
quite, professional place them them to work.

Objectives:

Establish a four year pilot program that will be based at
Prek Leap National College of Agriculture which is located
outside of Phnom Penh.

That will prepare Cambodian women with the knowledge and
skills that will be required for well paying and flexible
jobs for the technologies that will be in most demand at the
time they graduate.  These technologies are where the jobs
are and will be in the next decade throughout the world.

The program is broken into three parts: Communication,
Critical Thinking and Problem Solving and finally
specialization in two different fields that are in high
demand worldwide.

The first two years will concentrate on building basic
skills needed before they can begin advanced studies but
will prepare students so that at the end of the first two
years they will be qualified to work as interns, or part
time.

The second two years, students will split their time between
working as a part time remote intern for a foreign or
possibly local IT company.  These will be paid positions,
and the program will place students in companies with the
understanding that while they are working they will be
continuing their studies.  The pilot program will provide
advanced training in either DevOps and Machine-Learning.

At the end of the program they will either be placed in full
time positions at companies they have interned at, or they
will have the option of forming their own Remote work
startup companies either here in Cambodia or abroad.

Currently there are thought to be 22,000 qualified people
in Machine Learning, and there are are over 125,000 jobs
available in the field.  Over the next four years the
available jobs in AI is expected to grow to be as high has a
million positions worldwide, but the number of people
qualified for these positions will be less than half of
that.

The other specialty is called DevOps, which is a combination
of Software Development, and Systems management and
Operations.  Companies are moving from the traditional
software development practice of developing software in
incremental releases that are periodically rolled out to
customers to what is known as continious development.
Software is developed and deployed as soon as a fix or
feature is complete.  Some companies deploy changes to
production systems as much as 20 or more times every day.
To do this a new job category has emerged, DevOps which
works to coordinate between development teams, and
operations teams, management and customers.  DevOps
positions require interdisciplinary skills that combine
software development and systems administration.  There are
far more DevOps positions available than can be filled, and
demand for these skills is expected to grow dramatically
over the next 10 years.

First Two Year Curriculum Outline:

  - Communications:
    - Technical English; Conversation, Reading, Writing
  - Learning How To Learn:
    - Critical Thinking
    - Introduction to Logic
    - Algorithms
    - Statistics
    - Mathematics for Programers
    - Search & Research Methodologies
  - Practicum 
    - Linux Operating System
    - Introduction to Programing
    - Introduction to System Administration,
    - Introduction to the Web Stack
    - Programing II: Python, Ruby, R, Rust, Go
    - Introduction to Machine Learning & Neural Networks

Status:

A number of Remote Work companies have been approached with
the concept and they are all open to participating in the
program and are enthusiastic about the prospect of being
able to hire qualified women in their companies.

We will ask these companies to sponsor individual students,
and provide tuition, a laptop and female mentors from their
companies who will work with sponsored students during the
first two years of the program.  If the student completes
the program, the sponsor will have the option of taking on
that student as an intern for the second two years of the
program. 

We are in the initial stages of developing the materials for
the curriculum for the first two years.

The program will use a system called /blended/ learning
which records lectures as a series of ten minute long videos
which students watch outside of class, as well as read
course materials.  When they come to class, instructors and
volunteers who will be largely made up of IT professionals
who are visiting Cambodia for a couple of weeks or months,
to spend some of their time working with students one-on-one
in class to practice what they have learned in the videos
and other material.  Blended learning has been a highly
successful method of teaching that gives students access to
teachers when they are actually what would be considered
homework instead of sitting and listening to a lecture.

We intend to finish the base curriculum for the first year
and begin our first pilot class in the semester starting in
October of 2018.

We are seeking funds to continue to develop course
materials, produce videos, establish formal agreements with
participating companies and recruit online mentors and
visiting volunteers and coordinate when they come to
Cambodia and how they will work with students.

*** Chenla d9d Services


*** Slow AI


*** Doorstep Agriculture




** Initiatives
:PROPERTIES:
:ID:       34865dc8-5986-4f88-bb7b-c5eda8675fd4
:END:


