#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Plan of The Work
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[./index.org][top]]] [[[./intro.org][prev]]] [[[./synopsis.org][next]]] 

* Plan of The Work
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/00/ww-plan.org
:Created:  2018-04-21T08:55@Prek Leap (11.642600N-104.919210W)
:ID:       c054aa11-d974-428c-9324-e084a91cc4d7
:VER:      577547780.266428921
:GEO:      48P-491193-1287029-15
:BXID:     proj:OYK7-7861
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Table of Contents
- [[id:0ed7184f-ba2a-45f5-9460-efde6ff00081][Introduction]]
- [[id:911ca1c6-3c31-45ea-80b8-cf582c940f65][principles]]
- [[id:72728741-9f9c-4b4f-9dff-6eba95bf77b3][patterns]]
- [[id:6fbd41ac-9947-4358-875e-5d2b798a8f93][source]]
- [[id:18e41791-cb01-4114-943d-a26bc95c1099][kernal]]
- [[id:401aaec4-899d-4972-b500-ea222cef7c2c][storage]] 
** Introduction
:PROPERTIES:
:ID:       0ed7184f-ba2a-45f5-9460-efde6ff00081
:END:

#+begin_quote
Everything that is not forbidden by laws of nature is
achievable, given the right knowledge.

— David Deutsch 
#+end_quote


The Warp & Woof is a generative grammar for 21st century
Civilization.  

Civilization is iterative and bottom up, building on the
civilizations that came before them.  With each iteration we
learn a little more, do a little better.  It is hoped that
these works will be of use in making that process a little
less random, a little more focused, and a lot less
disruptive and destructive as it all too often has been in
the past.

#+begin_comment
Even the term history has been extended and externalized.
History literally means /what was written/.  We add to human
writing systems, what was written in the radio isotopes in
rock and the chemical signitures in ice and the
electromagneic spectrum from objects so far away that they
have takes thousands, millions and billions of years to
reach us.
#+end_comment

Chenla is not proposing the design of any specific
civilization, rather, the goal is to provide a generative
framework for the present and future generations to make any
number of civilizations.  

The history of 

#+begin_ascii
             Principles   <---------\
                 \/                 |
              Patterns    <---------| 
                 \/                 |
               Source     <---------|      ------ A R C ---------- 
                 \/                 |          Dark Archives 
    ---------- Kernal ----------    |      .......................
            M I D D L E             |       Near-line Repositories
    ............................    |      .......................
      Pattern Recognition Layer <---|--->    On-line Libaries
    ............................    |      =======================
          Discovery Layer       <---|          Map-Index Layer
    ............................    |      .......................
          Rule Set Layer        <---|         Collection Layer
    ............................    |      -----------------------
         Process Chain Layer    <---|              / \
    ............................    |               |
           Physical Layer       <---|               '----- W O R L D
    ----------------------------

#+end_ascii
** Principles
:PROPERTIES:
:ID:       911ca1c6-3c31-45ea-80b8-cf582c940f65
:END:

An introduction to the concepts used in *A Pace-Layer Pattern
Language* and *A Primer*

** Patterns
:PROPERTIES:
:ID:       72728741-9f9c-4b4f-9dff-6eba95bf77b3
:END:


APPL is meant to expand on the world in Christopher Alexander's A
Pattern Language (APL) which was published in 1977
cite:alexander:1977pattern

Where APL focused on towns, cities and the architecture of builds, the
scope of APPL will be to encompass as aspects of civilization and
human existence.

In addition to /APL/-like Patterns, APPL will include the following
categories:

  - Patterns :: Archetypal Design Patterns for structures,
                settlements, social organization and systems. 
  - Parameters :: Constants and Variables.
  - Theses :: Assertions that may be moral or ethical but
              may not be justified purely on logical or
              evidence-based grounds. 
  - Keystones :: Key Reference Designs and Specifications.

Another departure from APL will be that APPL will be what is called a
/literate program/ which combines text together with computer software
code.  The code is executed when the pattern is generated.  This makes
it possible for patterns to be machine understandable.  This will be
important in the next work in the series, /The Hoard/ which will is a
group of /generative grammars/ which are expressed as both a text
narrative and code.

APPL will establish the broad patterns that can be used to construct
generative grammars that will be adapted to account for local context
(conditions) in the /Hoard/.

** source
:PROPERTIES:
:ID:       6fbd41ac-9947-4358-875e-5d2b798a8f93
:END:

A hoard is a collection of treasured goods and information.  In Old
English, the word for dictionary was a /worde hord/.

It is a combination repository under version control that contains the
source code for generating Primers.  In a Platonic sense, APPL is the
world of archetypes and the Hoard are the shadows on the wall that we
can see and interact with. The APPL is a way of thinking globally, and
a hoard pragmatically thinks and acts locally.

Hoards are organized using two different models, the /Pace-Layer/
model, and a /Succession-Stage/ model.

As in the previous two works, the Hoard is not a prescriptive design
for civilization.  Rather it is meant to create generate grammars that
can be used to create very long term civilizations from first
principles that are distributed /and/ antifragile.

A Hoard includes plans, designs, standards, specifications based on
/keystone/ reference designs and patterns from the APPL which are
adapted for a range specific needs of a ecological, economic,
technological, and cultural niches of any given civilization.

** kernal
:PROPERTIES:
:ID:       18e41791-cb01-4114-943d-a26bc95c1099
:END:

A Primer is a collection of prescriptive and descriptive
knowledge needed to build a specific civilization.

In many cases the only way to develop a keystone reference design is
by building a number of designs for specific needs.  So in order for
us to come up with many of the patterns, generative grammars and
keystone designs, we will start with specific designs, identify what
makes it work and what can be used as a universal principle and then
work backwards.  The Primer will include all of this specific design
and development work that was done to develop patterns and keystone
designs.

** storage
:PROPERTIES:
:ID:       401aaec4-899d-4972-b500-ea222cef7c2c
:END:
The Archive, or Arc for short, is collection of digital
data, texts, images, audio video, 2D and 3D vector graphics
and code that represents a subset of Mankind's recorded
memory and experience that provides the context and
background needed to build and maintain a civilization.


