#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Plan of The Work
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[./index.org][top]]] [[[./intro.org][prev]]] [[[./synopsis.org][next]]] 

* Plan of The Work
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/00/ww-plan.org
:Created:  2018-04-21T08:55@Prek Leap (11.642600N-104.919210W)
:ID:       c054aa11-d974-428c-9324-e084a91cc4d7
:VER:      577547780.266428921
:GEO:      48P-491193-1287029-15
:BXID:     proj:OYK7-7861
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Table of Contents

- [[id:0ed7184f-ba2a-45f5-9460-efde6ff00081][Introduction]]
- [[id:62eb03eb-fa14-42be-be07-a97dd195396f][Works]]
  - [[id:911ca1c6-3c31-45ea-80b8-cf582c940f65][Warp & Woof]]
  - [[id:72728741-9f9c-4b4f-9dff-6eba95bf77b3][A Pace-Layer Pattern Language]]
- [[id:6fbd41ac-9947-4358-875e-5d2b798a8f93][Hoard]]
- [[id:18e41791-cb01-4114-943d-a26bc95c1099][Primer]]
- [[id:401aaec4-899d-4972-b500-ea222cef7c2c][Arc]] 
- [[id:682f45da-1356-4b4a-a911-8abb845cc9a7][Projects]]
- [[id:7466a761-d9a2-4a2a-aeb9-10aa36963509][Programs]]
- [[id:34865dc8-5986-4f88-bb7b-c5eda8675fd4][Initiatives]]

** Introduction
:PROPERTIES:
:ID:       0ed7184f-ba2a-45f5-9460-efde6ff00081
:END:

#+begin_quote
Everything that is not forbidden by laws of nature is
achievable, given the right knowledge.

— David Deutsch 
#+end_quote


The Warp & Woof is a generative grammar for 21st century
Civilization.  The history of our species is that of
extension and externalization of both mind and body. 

Mind was first extended by speech, then externalized by
writing systems, followed by techiques for the capture and
replay of sound and light.  The hand was first extended by
tools, then externalized by machines.  Now cognitive
machines are emerging; a combination of externalized mind
and body.  This process is rapidly changing and we still
have no idea where this will take us.

Our knowledge of the world around us has always been
woefully incomplete.  Even though we have managed to tease a
comprehensive understanding of how the world works at human
scales, that knowledge has led us far beyond human scales
both vastly greater and smaller than ourselves, and the
realization that there is still more we don't know than what
we know.  And because of this, our knowledge is still
sparse, with enormous gaps in our maps, only filled by
speculation; little better than our ancestor's annotating
the blank spaces in their maps with the admonition, "here
there be dragons".

Uncertainty is hard coded into the rules that govern our
universe, that complexity and order which makes everything
from galaxies and stars to the weeds threatening to overtake
a vegitable bed are the exception rather than the rule.

Each of us reacts differently to that unassailable
uncertainty and the unknown.  As Olson said, "some men ride
on such space, others have to fasten themselves like a tent
stake to survive... They are the alternatives."  The first
people, the nomads learned to ride like a surfer, taking the
inevitable falls in stride, breaking camp and moving with
the seasons.  Those who stopped their wandering replaced
their tent stakes with walls and roofs that blocks out the
sky, pretending that this separated and protected them from
the uncertainty of the elements, attacks from predators and
from each other.  

Timidity won and we become a sedantary and dominantly urban
species.  That call to ride space and face the world on its
own terms is still there in all of us, though it has been
squeezed down until it... went to sleep.  We have built
walls higher, taller and ever thicker which within we have
complete control.  When the sun bears down, we cool the air
within.  When the days grow short and ever colder, we heat
the air and seldom even look outside and called it
Civilization.  

The nomads moved on when they wished, the wind at their
backs, following the sun, following the game and greener
pastures just over the next hill.  Sendantary man didn't
move so much as grow incrementally like a fungus creeping
growth that devoured what resources they encountered as they
went.  Over millennia they overtook the nomads and left them
with no place to wander.  In this way we kept expanding, and
increasing in numbers until there was no where left to
expand and we found ourselves back where we had started
from to devour and pave over the very savvanahs where we had
begun. 



Civilization is iterative and bottom up, building on the
civilizations that came before them.  With each iteration we
learn a little more, and do a little better.  It is hoped
that these works will be of use in making that process a
little less random, a little more focused, and a lot less
disruptive and destructive as it has all too often been in
the past.




Even the term history has been extended and externalized.
History literally means /what was written/.  We add to human
writing systems, what was written in the radio isotopes in
rock and the chemical signitures in ice and the
electromagneic spectrum from objects so far away that they
have takes thousands, millions and billions of years to
reach us.




Chenla is not proposing the design of any specific
civilization, rather, the goal is to provide a generative
framework for the present and future generations to make any
number of civilizations.  

The history of 

#+begin_ascii
            Warp & Woof   <---------\
                 \/                 |
                APPL      <---------| 
                 \/                 |
               Hoard      <---------|      ------ A R C --------- 
                 \/                 |          Dark Archives 
    ---------- Primer ----------    |      .......................
            M I D D L E             |       Nearline Repositories
    ............................    |      .......................
      Pattern Recognition Layer <---|<--->    Online Libaries
    ............................    |      =======================
          Discovery Layer       <---|         Map-Index Layer
    ............................    |      .......................
          Rule Set Layer        <---|        Collection Layer
    ............................    |      -----------------------
         Process Chain Layer    <---|              / \
    ............................    |               |
           Physical Layer       <---|               '----- W O R L D
    ----------------------------

#+end_ascii

** Works
:PROPERTIES:
:ID:       62eb03eb-fa14-42be-be07-a97dd195396f
:END:
*** Warp & Woof
:PROPERTIES:
:ID:       911ca1c6-3c31-45ea-80b8-cf582c940f65
:END:

An introduction to the concepts used in *A Pace-Layer Pattern
Language* and *A Primer*

*** A Pace-Layer Pattern Language (APPL)
:PROPERTIES:
:ID:       72728741-9f9c-4b4f-9dff-6eba95bf77b3
:END:


APPL is meant to expand on the world in Christopher Alexander's A
Pattern Language (APL) which was published in 1977
cite:alexander:1977pattern

Where APL focused on towns, cities and the architecture of builds, the
scope of APPL will be to encompass as aspects of civilization and
human existence.

In addition to /APL/-like Patterns, APPL will include the following
categories:

  - Patterns :: Archetypal Design Patterns for structures,
                settlements, social organization and systems. 
  - Parameters :: Constants and Variables.
  - Theses :: Assertions that may be moral or ethical but
              may not be justified purely on logical or
              evidence-based grounds. 
  - Keystones :: Key Reference Designs and Specifications.

Another departure from APL will be that APPL will be what is called a
/literate program/ which combines text together with computer software
code.  The code is executed when the pattern is generated.  This makes
it possible for patterns to be machine understandable.  This will be
important in the next work in the series, /The Hoard/ which will is a
group of /generative grammars/ which are expressed as both a text
narrative and code.

APPL will establish the broad patterns that can be used to construct
generative grammars that will be adapted to account for local context
(conditions) in the /Hoard/.

** Hoard
:PROPERTIES:
:ID:       6fbd41ac-9947-4358-875e-5d2b798a8f93
:END:

A hoard is a collection of treasured goods and information.  In Old
English, the word for dictionary was a /worde hord/.

It is a combination repository under version control that contains the
source code for generating Primers.  In a Platonic sense, APPL is the
world of archetypes and the Hoard are the shadows on the wall that we
can see and interact with. The APPL is a way of thinking globally, and
a hoard pragmatically thinks and acts locally.

Hoards are organized using two different models, the /Pace-Layer/
model, and a /Succession-Stage/ model.

As in the previous two works, the Hoard is not a prescriptive design
for civilization.  Rather it is meant to create generate grammars that
can be used to create very long term civilizations from first
principles that are distributed /and/ antifragile.

A Hoard includes plans, designs, standards, specifications based on
/keystone/ reference designs and patterns from the APPL which are
adapted for a range specific needs of a ecological, economic,
technological, and cultural niches of any given civilization.

** Primer
:PROPERTIES:
:ID:       18e41791-cb01-4114-943d-a26bc95c1099
:END:

A Primer is a collection of prescriptive and descriptive
knowledge needed to build a specific civilization.

In many cases the only way to develop a keystone reference design is
by building a number of designs for specific needs.  So in order for
us to come up with many of the patterns, generative grammars and
keystone designs, we will start with specific designs, identify what
makes it work and what can be used as a universal principle and then
work backwards.  The Primer will include all of this specific design
and development work that was done to develop patterns and keystone
designs.

** Arc
:PROPERTIES:
:ID:       401aaec4-899d-4972-b500-ea222cef7c2c
:END:
The Archive, or Arc for short, is collection of digital
data, texts, images, audio video, 2D and 3D vector graphics
and code that represents a subset of Mankind's recorded
memory and experience that provides the context and
background needed to build and maintain a civilization.

** Projects
:PROPERTIES:
:ID:       682f45da-1356-4b4a-a911-8abb845cc9a7
:END:


Elon Musk has said many times that he is always looking for
industries where there are enormous inefficiencies and if
you can reduce those inefficiencies by orders of magnitude
you will make a lot of money and transform an industry.

This is exactly what he has done with SpaceX.  He is
transforming the space launch industry building that use
rockets tht cost 500-600 million and thrown away after the
first use to a system that reuses most of the rocket many
times and reduce launch costs to under US$60 million.  That
is today.  Within 10 years the rockets will be one hundred
percent reusable and can be refueled within a couple of
hours and flown again like a commercial jet.

The same opportunity exists today with ERP software which
potentially could be used by every company on the planet.

Enterprise Resource Planning (ERP) software is a broad class
of software that manages nearly all aspects of a business.
Typical ERP modules include:

  - Procurement
  - Production
  - Distribution
  - Accounting 
  - Human Resources
  - Customer Services (CRM)
  - Sales

The software that provides these modules is typically made
up of a separate database for each module, a schema that
hardcodes the fields in each database and some business
logic for generating reports and monitoring the performance
of the company.  ERP is arguably the single most important
software application that any company uses and after looking
over a number of of these products and having seen the
source code for two different ERP systems I can say that
they are desperately outdated and provide only a fraction of
what a well designed ERP system could deliver.

Just a single module CRM turned Salesforce into a multi
billion dollar company.  ERP presents an enormous
opportunity to build a Google scale business.

This hasn't been done because the people who use ERP and
write ERP software see ERP as a number of completely
separate silos where little information passes between the
silos.

But those silos only exist because of the way that companies
structure their information.  And as the saying goes, the
way you organize information is how power is organized in an
organization.

But in reality everything in ERP or anything that is done in
any organization can be modeled very simply.  Everything is
a process chain, where a process is created to do
something.  The process is broken down into different steps
that are handled by different specialists in an
organization.  These processes are governed by rules the
specify how the task is done, and what each step needs to
acomplish.  Processes and each step of each process is
handled by different people with different levels of
authority and responsibility.  Different people are allowed
to see different aspects of a process and in many cases only
upper management is allowed to see all parts of a process as
it moves through different departments.

That's it, everything is a process broken into steps, steps
are governed by rules, called business logic, and there are
different levels of authority, and access for each person
working on any particular step.

To give the illusion of traditional corporate silos, people
in different departments with different levels of access
will each see a different view of the company from their
perspective within the context of what they do in the
company.  We call this a worldview.  An accountant's
worldview of a company is vastly different from customer
service or the people running production, which has it's own
software applications specific to what they are producing.
The CEO or President has god like powers to see everything
but they couldn't function if they did -- so oddly enough
the higher someone is in the power structure the more
abstract and summarized their worldview is.  This allows
them to see the entire company at a glance and see patterns
of where things are working and where they aren't.

This would provide companies with very flexible and
customizable ways of shaping the way processes are handled
in their ERP system, largely by customizing their
worldviews to match their specific way of doing and seeing
things.

Designing an ERP system this way would be transformative,
but it is only part of what's possible.  Because all
information in the company is in one large graph database,
we eliminate places in the system where the same information
is stored in multiple places.  This will reduce many errors
that cause so many problems in large or even small
organizations.  The second thing that becomes possible is
that it becomes relatively easy to automate a significant
amount of the business logic using rulesets managed by
machine-learning subsystems (sometimes called artificial
intelligence).  This will ensure that processes are carried
out consistently, almost instantly and reduce the number of
people needed to manage information in a large organization.

But this is only the beginning.  So far we have only
considered ERP as a monolithic inhouse software application.
One company, one ERP system.  This is even how cloud-based
ERP systems on the market are done.  One company one account
-- each company is a silo in its right.

Douglas Engelbart (who invented the mouse and the windows
interface) recognized this as an enormous problem as far
back as the late 1950's. At the time Englebart worked for
one of the big military areospace companies, I think it was
Northrop or Grumman.  When a something large like a bomber
or fighter aircraft is made, or even a car or toaster, no
one company makes all of it.  Raw materials come from some
companies, other companies build sub assemblies, many sub
assemblies are made up of other sub assemblies.  Building
anything today is a complex chain of different companies
doing different parts that are all pulled together by one
comapny who puts their logo on it and markets and sells it.
It's the same reason that it takes $30-100 million to make a
hollywood movie, everything is outsourced and everyone is
taking a cut in between everyone else.

This is enormously complex and between most of each company
in the chain are a lot of other companies providing
logistics, banking services, sourcing, outsourcing
etc. etc.  So if a change is needed or something isn't
working, it is a long slow complicated and expensive process
that has to propagate through all of the contractors and
middlemen, all taking a cut in between.  The vast majority of
these things done in the middle are simple, so simple that
within the next 5-10 years machine-learning systems will be
smart enough to do this better, faster and cheaper than
people.

Now imagine a distributed ERP system that treats these vast
constellations of contractors and subcontractors and
middlemen as single parts or departments in a single
company.  And all goods and services are treated as little
lego bricks that are stuck together to accomplish one thing,
and then broken back up into separate bricks and reassembled
into a different configuration to do something else.

If all ERP software is designed to be modular, scalable and
distributed so that everything becomes a one-time virtual
supply-production-delivery chain with most of the tasks
between automated by machine-learning systems -- if
everyone's ERP system can be interoperable with all other
ERP software at all other companies, then all of this
becomes possible.  This would be the single biggest change
that AI would bring to the global-value chain and would have
an impact on the world that is almost beyond imagining.

The building blocks are fairly simple.  Machine learning is
increasing in power at a tremendous pace.  What is needed is
a vision like the one I have outlined to pull all of these
together and get it to market.

The advantages would sell the system itself.  What was the
value of the first fax machine that rolled off the assembly
line?  Zero.  Because there was no one you could send a fax
to.  But everytime someone bought a fax machine it increased
the value of your fax machine, so people would push other
people to buy fax machines because it made their fax machine
more valuable.  This triggers the network effect and you get
exponential growth of networks.

So, to build this, we write up a business plan and find a
VC, raise a pile of money and build it?  No. You might be
able to pull it off and take your place beside Google,
Amazon, Facebook and Alibaba, but that isn't what the world
needs.  The last thing we need is another monster company
that owns us.

A system like this has to start small, and almost off the
grid in places where no one will think to pay attention.
Cambodia is perfect.  Start very small, very cheap and
network together a couple of supply production chains while
you are developing the system.  Eventually the network will
grow to the point that it will start spreading around the
world and reach a tipping point before the big companies
have a chance to stop it.

Safeguards need to be put in place to ensure that the
systems stays distributed, stays federated and open so that
everyone is doing business with each other on a level
playing field.

ERP is only a small part of what such a system is capable
of, governments, scientific reasearch, education, management
of long term resources like ground water and work on climate
change could all use the same system to make the exchange of
informtion, goods and services something that works on the
very smallest scales up to the very largest.

This is the system that we are starting to design and will
build.  To do this we need some seed money to get things
started, but the beautiful thing about this approach is that
if it works, then you make money, right away.  If it doesn't
then the system isn't working.

In addition we need people with the skills to help build
this.  That is what the Women's IT program is for.  To train
the people we need to build this system.  If we start the
program this year the first graduates, in a couple years time,
will be ready when we need them.

And second we need to build out a distributed network of
processing and storage that will become the backbone for the
new network.  While we are building out the ERP network,
this service can generate money traditionally through
renting out virtual machines and docker containers to other
companies.  This is the reason that we started Kinto.  It
will be profitable within 18 months at which time the ERP
network will become it's biggest customer and it will then
grow as fast as the ERP network grows.

So to start out, we need to get the Women's IT program
started, get Kinto up and running and making money, and form
a small development team of 3-4 people to work on building
the prototype ERP system.  The development team should have
a working system networking together several hundred
companies about the time that the first class graduates and
we will be ready to scale.

This is a positive-sum system we want to build, everyone
wins, everyone improves their lives because the more we
automate the more more wealth is being generated using fewer
resources.  We get rid of the middlemen, and then each
producer in a chain get's a better life.  This will be the
same for the smallest dirt farmer to companies like Boeing
building jumbojets.  That's the vision.

Please help us make this happen.


** Programs
:PROPERTIES:
:ID:       7466a761-d9a2-4a2a-aeb9-10aa36963509
:END:

*** Women in Cambodian IT

[[./ww-studyhall-pilot.org][Chalkhall Pilot Program]]


Women have find it challenging to enter the IT industry.
The industry is well known for being male dominated, and is
often hostile to women entering the field.  Employers
generally understand that this is something that has to
change, but there aren't as many women graduating from IT
programs as men, in large part because the hostility to
women is endemic to IT educational programs as well.

In addition to the the challenges that women face in
developed ecconomies, women in developing economies have
additional challenges and responsbilities and expectations
from their families.  The nuclear family is predominant in
developed countries where after finishing school people are
not expected to take as large a role in the day to day life
of their parents and grand parents.  Cambodia is
predominately made up of traditional extended families who
place much of the burden for taking care of 2-3 generations
and earning money for the family.

Cambodian IT education is focused on providing skills in
technologies that are traditionally low paying and
considered to be low skill.  This includes web application
development, low-end mobile application development, and
Windows based middle-ware that is only used in large and
medium sized corporate environments.  The technologies that
are being used by startups the tech giants like Facebook,
Google and Amazon use cutting edge technologies which are
not being taught in Cambodia.  This is holding back foreign
investment in the country because there is no labor pool of
people with the skills that IT companies need to locate in
Cambodia.  This also means that companies which are already
in Cambodia are not able to adopt these new technologies
which would make them competitive with foreign companies
because no one is qualified to support those technologies.

We believe that the solution to these challenges is to teach
the latest technolgies to Cambodian women and take advantage
of the trend towards Remote Work Companies.  There are now a
number of companies that are worth hundreds of millions of
dollars that have hundreds of employees who all work
entirely from wherever they live.  These are progressive
companies who pay market rate or higher salaries and
benifits as any other IT company, but they have no offices.

Our challenge will be to provide women with the skills that
these companies need, place them in these companies, and
provide what Virginia Woolf called, "a room of one's own",
so that Cambodian Remote workers have a place where at or
near home where they can keep flexible hours that allow them
to take care of their families expectations, and provide a
quite, professional place them them to work.

Objectives:

Establish a four year pilot program that will be based at
Prek Leap National College of Agriculture which is located
outside of Phnom Penh.

That will prepare Cambodian women with the knowledge and
skills that will be required for well paying and flexible
jobs for the technologies that will be in most demand at the
time they graduate.  These technologies are where the jobs
are and will be in the next decade throughout the world.

The program is broken into three parts: Communication,
Critical Thinking, Problem Solving and specialization in one
of two fields that are in high demand worldwide; DevOps and
Machine Learning.

The first two years will concentrate on building basic
skills needed before they can begin advanced studies but
will prepare students so that at the end of the first two
years they will be qualified to work as interns, or part
time.

The second two years, students will split their time between
working as a part time remote intern for a foreign or
possibly local IT company.  These will be paid positions,
and the program will place students in companies with the
understanding that while they are working they will be
continuing their studies.  The pilot program will provide
advanced training in either DevOps and Machine-Learning.

At the end of the program they will either be placed in full
time positions at companies they have interned at, or they
will have the option of forming their own Remote work
startup companies either here in Cambodia or abroad.

Currently there are estimated to be 22,000 qualified people
in Machine Learning, and there are are over 125,000 jobs
available in the field at the time this is being written.
Over the next four years the available jobs in AI is
expected to grow to be as high has a million positions
worldwide, but the number of people qualified for these
positions will be less than half of that.

The other specialty is called DevOps, which is a combination
of Software Development, and Systems management and
Operations.  Companies are moving from the traditional
software development practice of developing software in
incremental releases that are periodically rolled out to
customers to what is known as continious development.
Software is developed and deployed as soon as a fix or
feature is complete.  Some companies deploy changes to
production systems as much as 20 or more times every day.
To do this a new job category has emerged, DevOps which
works to coordinate between development teams, and
operations teams, management and customers.  DevOps
positions require interdisciplinary skills that combine
software development and systems administration.  There are
far more DevOps positions available than can be filled, and
demand for these skills is expected to grow dramatically
over the next 10 years.

First Two Year Curriculum Outline:

  - Communications:
    - Technical English; Conversation, Reading, Writing
  - Learning How To Learn:
    - Critical Thinking
    - Introduction to Logic
    - Algorithms
    - Statistics
    - Mathematics for Programers
    - Search & Research Methodologies
  - Practicum 
    - Linux Operating System
    - Introduction to Programing
    - Introduction to System Administration,
    - Introduction to the Web Stack
    - Programing II: Python, Ruby, R, Rust, Go
    - Introduction to Machine Learning & Neural Networks

Status and Pilot Program

A number of Remote Work companies have been approached with
the concept and they are all open to participating in the
program and are enthusiastic about the prospect of being
able to hire qualified women in their companies.

We will ask these companies to sponsor individual students,
and provide tuition, a laptop and female mentors from their
companies who will work with sponsored students during the
first two years of the program.  If the student completes
the program, the sponsor will have the option of taking on
that student as an intern for the second two years of the
program. 

We are in the initial stages of developing the materials for
the curriculum for the first two years.

The program will use a system called /blended/ learning
which records lectures as a series of ten minute long videos
which students watch outside of class, as well as read
course materials.  When they come to class, instructors and
volunteers who will be largely made up of IT professionals
who are visiting Cambodia for a couple of weeks or months,
to spend some of their time working with students one-on-one
in class to practice what they have learned in the videos
and other material.  Blended learning has been a highly
successful method of teaching that gives students access to
teachers when they are actually what would be considered
homework instead of sitting and listening to a lecture.

We intend to finish the base curriculum for the first year
and begin our first pilot class in the semester starting in
October of 2018 with about 15 students.  We will create a
new class every year and expand the program when it is
appropriate. 

All course material will be released under Open Source
Licences and the entire curriculum will be  designed to
be used as a template that can be used to establish other
programs around the world.

We are seeking funds to continue to develop course
materials, produce videos, establish formal agreements with
participating companies and recruit online mentors and
visiting volunteers and coordinate when they come to
Cambodia and how they will work with students.

*** Chenla d9d Services
*** Slow AI
*** Doorstep Homestead Pilot Farm

 - 

 - 40-60% of familiy food from half hectare
 - off grid fuel and electricity
 - hot water, gray water, septic systems
 - food preservation and storage
 - water capture and storage
 - leverage animals to do most work

 - family revenue half hectare for own consumption
 - part-time business, 2-3 hours a day
 - seasonal businesses
 - production farming for rest of farm


** Initiatives
:PROPERTIES:
:ID:       34865dc8-5986-4f88-bb7b-c5eda8675fd4
:END:


