#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall

* Scopic Trivium
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/trivium/README.org
  :Created:   2017-06-22T11:40@Prek Leap (11.642600N-104.919210W)
  :ID:        517edd0b-ff6e-4c72-92eb-2225f1a1b979
  :VER:       551378475.398582288
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:INT6-8808
  :Class:     primer
  :Type:      readme
  :Status:    wip 
  :Licence:   MIT/CC BY-SA 4.0
  :END:

<https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square>
<https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square>
<https://img.shields.io/badge/type-readme-0072B2.svg?style=flat-square>
<https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square>
<https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square>


The Trivium will provide students with the intellectual and rational
tools to be able to understand and contribute to the development of
the /Primer/.  

It is hoped that eventually it will become the foundation for a
comprehensive cradle-to-grave educational framework needed to become a
purposeful and meaningful part of a distributed technological scopic
civilization.

Education c.2017 is still a product of the late stages of the
industrial revolution, where most people only needed basic reading,
writing and arithmetic skills and trained to stay in one place for
long periods of time and perform a narrow range of tasks when ordered.
Industrial societies changed quickly, compared to agriculture
societies before them, but change was still measured in generations
and that each new generation needed to learn new skills, but they were
still recognizably an iteration of what came before.  Education was
thought of as a place that one went to for a set period of time and
that what was learned there would serve you for the entire productive
years of your life.

Education will need to prepare people for a world that changes more in
a decade than their grand parents experienced in a lifetime.  Learning
must become a part of adult life throughout a person's entire life.
So is is more important for children to learn how to learn, think and
communicate so that they will find it easier to learn new things and
quickly become skilled in new disciplines and specialties as they
emerge.  They will also need the intellectual tools to evaluate new
information as it comes in, which happens so quickly now that all of
us are drinking directly from the firehose rather than being able to
rely on trusted institutional filters to be able to evaluate is
something is true, false or patently deceptive.

The medieval Trivium, which prepared students for studies at the
university level, and completed by the time a student was 15 years old
is broken into three /subjects/ which teach thinking and logic as well as
spoken and written communication.
