#   -*- mode: org; fill-column: 60 -*-

#+TITLE: A Pace-Layer Pattern Language
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* A Pace-Layer Pattern Language
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww/appl.org
:Created:  2018-04-10T10:57@Prek Leap (11.642600N-104.919210W)
:ID:       9eabb218-75d0-4a23-a358-00c13fe7d021
:VER:      576604703.780441407
:GEO:      48P-491193-1287029-15
:BXID:     proj:LUX7-3152
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

APPL makes up the reference building blocks for building any
given civilization at a given succession stage


** Table of Contents

  - Development Stage
    - Stub (S)
    - Proposed (P)
    - Draft (D)
    - Recommendation (R)

  - Entity Models
    - Patterns (con)            -> APPL  
      - Variation (exp)         -> APPL
        - Implementation (man)  -> Hoard
          - Localization (inst) -> Primer: applied
    - Parameter (con)           -> APPL
      - Definition (exp)        -> APPL: define/method/unit
        - Source (man)          -> Hoard
          - Variable (inst)     -> Primer: applied
    - Theses (con)              -> APPL
      - Declaration (exp)       -> APPL 
        - Rule (man)            -> Hoard: algorithm
          - Code (inst)         -> Primer: applied
    - Keystones (con)           -> APPL
      - Variation (exp)         -> Hoard
        - Design (man)          -> Primer 
          - Prototype (inst)    -> IRL : applied


** APPL

#+begin_comment
It took me a long time to really grok patterns.  The first
time I saw the book I was hooked instantly.  But how you got
from patterns to actual buildings wasn't so clear.  Even
today, after reading /The Nature of Order/
cite:alexander:2004phenomenon it still wasn't clear.  I
understood what he was proposing, but implementation is
still too fuzzy -- it's almost as if the gulf is too great
between the past and present -- we are so estranged and
broken that building things from a deep sense of
connectedness to the world is an alien concept.  I don't
agree that people still have an innate ability to do this.
This faculty has been so degraded that we don't even know
what we've lost any longer.

Alexander has come up with a methodology that provides a
crude method that's sort of like trying to teach deaf people
to create not just music but /beautiful/ music that they can
not understand or experience.

We need to teach people how to be connected to the world and
give them the cognitive tools to see and appreciate beauty,
then Alexander's approach will follow naturally.

This goes to the core of the problem of quality and
craftsmanship.  And in both cases I don't think we make any
progress until we can at the cultural layer, to reinvent
both quality and craftsmanship.  This is a
multi-generational undertaking and my gut feeling is that we
first need to figure out how to stop crushing children's
natural ability to see and understand beauty.  And I have a
hunch that this can't be done unless we also stop crushing
things like curiosity, or training people to think that
uniformity is the synonymous with quality -- that's an
industrial revolution thing.  

And post-industrial revolution civilization is just getting
worse.  We now have a significant percentage of a generation
who don't experience anything directly -- they are too busy
pointing a camera at things instead of experiencing it and
contemplating on what they are seeing.  Instead they
experience things as a side effect of their peer group in
social media.  That's bad enough, but we then are going
further and feel the need to include ourselves in most and
sometimes nearly all of those photos.  Selfies put ourselves
at the center of everything we experience.  We don't watch a
beautiful sunset, we take a picture of ourselves in front of
a beautiful sunset and by the time you've sent the picture
to social media the sun is down.  We need to understand that
we are part of the world, at the center of that world and
this is something that is being lost.  There are any number
of people who take great umbridge to this argument and say
that taking pictures is how they experience things.  That
doesn't hold up, the act of recording requires that most of
your attention is spent in the mechanics of making that
recording.  Saying that you can multitask and enjoy the sun
set as fully through a view finder as you fiddle with the
settings and frame and take the shot is not the same as
quietly sitting and watching a sun set.  Adding insult to
injury by putting yourself into that shot is pure
narcissism.  It is not a bad thing to take pictures of a
sunset, but this should be the exception rather than the
rule.  If you haven't spent many many sunsets watching them
and trying to understand what you are seeing and how that
relates to you and your place in the world then you don't
have the experience to know how to capture all of that in a
photograph.  This is the difference between art and whatever
it is people are doing with selfie sticks.

When we produce millions of exact copies of things be they
tea pots or copies of a sound recording we have stripped
things of their uniqueness and life imperfections are the
only way we can know when we see something that is perfect.
When everything is the same, there is no good or bad,
nothing is better than anything else which strips things of
their beauty, if nothing is ugly, then nothing is beautiful.
Beauty only exists as part of a spectrum with things that
are ugly at the opposite end.

We have to discard a lot of industrial revolution baggage to
do this and we will never see it, nor out children.  But
perhaps our grandchildren and great grandchilren, if we work
hard enough at it and make it a priority.

But this still doesn't answer my original question of how to
use patterns -- I don't see them as a crutch, as see them as
an important means of embodying an aspect of knowledge that
until now hasn't been recorded in any meaningful way.

Patterns record fuzzy things that we use terms like
traditional, or custom or vernacular that boils down to
being collective, often informal knowledge -- it works
because it has evolved over many generations and tempered
over time through constant tweaking and experimentation.
It's often difficult, and even impossible to boil such
knowledge down into exact specifications or designs.
Patterns are able to capture that and as such are very
powerful, though more than a little nebulous.  Patterns are
not machine understandable because they are all within a
continuum of possible manifestations.  This is why it's so
difficult to use traditional building and financing methods
to do such construction because it is a process that doesn't
lead to a specific pre-defined conclusion.  The process
determines the finished product, not the desgin.  This is
what happened to the Web -- the original Web wasn't supposed
to look the same everywhere -- web pages were supposed to be
rendered differently according to the different types of
software and hardware that was being used.  Today's web
which is designed to work on multiple display sizes is not
what I'm talking about.  Web pages were not meant to be
'designed' they were meant to be interpreted.  Modern man
can't handle that kind of plasticity and uncertainty -- we
are too indoctrinated with the industrial concept that
everything has to be exactly the same to be of high
quality.  There can be no ambiguity, no influence from
outside -- everything must be static cookie cutter identical
copies where the designer has the power of controlling
everything for good or bad.

This also means that we've lost the ability to adapt the
world around us to the specific circumstances and needs that
they are put to use.  Emacs is completely the opposite from
this -- no two .emacs are the same, and after a while, the
customizations that go into your config may well make it
unusable for other people to be able to understand or use.
To someone like Steve Jobs this is nothing short of
horrifying.  He wants to cramp /his/ vision and /his/ design
down your throat and he doesn't give a shit if this works or
not.  Apple products require you to conform in ways that
Microsoft was never clever enough to pull off.  But
microsoft achieved the same thing from a completely
different direction.  Microsoft products are designed for
large corporate environments that require general purpose
tools that are identical.  Microsoft is the electronic
embodiment of industrial information processing.  The tools
don't need to be great, they only need to be good enough,
because the workers and the work done doesn't need to be
great it only needs to be good enough.  Excellence,
ingenuity and imagination doesn't scale and must be
eradicated where ever it is encountered.  That is why
Microsoft was so successful, Gates understood that in his
bones.  Apple then became a sort of fake alternative to
Microsoft.  Apple was supposed to be about individuality and
unconformity and thinking outside of the box, but that was
all window dressing.  It had the effect of catching all of
the people who did have a spark of imagination and crushed
it by reducing it to a lifestyle choice.  So you had the
choice of Microsoft, or Apple's way or the highway.  In the
end both Microsoft and Apple were doing the same thing.

Emacs out-of-the-box isn't emacs.  Emacs only become emacs
after it has rewired your brain and you have rewired emacs.

That is the potential that the web originally had and was
lost in the browser wars.
#+end_comment

Patterns are repeating themes in nature, design and human
behavior that when combined with other patterns strengthen
each other and create things that are larger than the sum of
their parts.

APL was divided into three parts, Towns, Buildings and
Construction.  But APL is a pattern language for
architecture and buildings.  For this to work it had to
define many patterns that more properly belonged to urban
planning, culture and governance though these were patterns
that supported the construction of beautiful buildings.

Our pattern language has a far broader scope; building an
antifragile civilization for mankind. 

Patterns alone will not be enough to build a civilization
on.  For this reason in addition to Patters

** Patterns

** Parameter (was constants)

Constants are bedrock variables that define things that can
not be changed like the speed of light or dunbar's number.
They supercede what we want or what we would like and
provide empirical design limits.  No theses can =violate= or
contradict a =constant=.

#+begin_comment
The following files are in ~/proj/manifesto/  they need to
be moved to APPL, once we have worked out the structure and
file naming conventions.
#+end_comment

 - [[./manifesto/constant-speed-of-light.org][Speed of Light]]
 - [[./manifesto/constant-dunbar.org][Dunbar's Number]]
 - [[./manifesto/constant-millers-law.org][Miller's Law]] (7 plus or minus 2)
 - [[./manifesto/constant-divided-concurrent-goals.org][Divided Concurrent Goals]]
 - [[./manifesto/constant--shared_intentionality.org][Shared Intentionality]]

** Theses

Scopic Theses are declarations that provide a foundation for
a =civil ruleset= for people to live and cooperate with each
other.  Our theses is a social fiction that defines how we
/want/ to live and behave with each other.

 - [[./manifesto/theses-preamble.org][Preamble]]
 - [[./manifesto/theses-notes.org][Theses Notes]]

** Pace-Layer Model

APPL is organized around Steward Brand's six-layer /Pace
Layer/ model which is based on the observation that
different things change at different speeds.  The model
began as an observation that buildings can be thought of as
being made of multiple layers with each changing over time
at different speeds.

Brand's model was made up of six parts:

  - 6 Fashion
  - 5 Commerce
  - 4 Infrastructure
  - 3 Governance
  - 2 Culture
  - 1 Nature 


Our language will be called /A Pace-Layer Pattern Language/
(APPL), which will be made up of 9 parts that combine
Brand's and Saffo's Pace Layer models into one.

This table shows slow to fast as pace layers, but it should
be remembered that layers 1-4 are nested within each other
and the Anthros layers are a subgroup of bios.

  |----------+------------------+-------------|
  |          | 9 Fashion        | agora       |
  |          | 8 Commerce       | stoa        |
  | Anthros* | 7 Infrastructure | polis       |
  |          | 6 Governance     | pynx & bema |
  |          | 5 Culture        | muthos      |
  |----------+------------------+-------------|
  |          | 4 Anthros*       |             |
  |          | 3 Bios           |             |
  | Natura   | 2 Lithos         |             |
  |          | 1 Helios         |             |
  |          | 0 Cosmos         |             |
  |----------+------------------+-------------|


This is only one POV, we need to present this as how these
different things form a hierarchy so that it's understood
that anthros is a subset of bios and not seperate.

The 9th group called /0 Meta/ contains patterns that apply to
all layers which will be given the number 0 below /1 cosmos/
which is number 1.

Each layer has a different =Rate of Change= (ROC) with
/Cosmos/ at the bottom being the slowest and /Fashion/ at
the top in a constant state of churn, changing at a staccato
rapid-fire beat.


*** Pattern Keys

Patterns will have keys (unique ids) in the form of:

   APPL[layer#]:[Pattern#]

So the first pattern in the Meta group would have the key
APPL0:0001.

*** Steward Brand and Paul Saffo: Pace Layers Thinking -- notes

 - [[http://longnow.org/seminars/02015/jan/27/pace-layers-thinking/][Pace Layers Thinking]] | Stewart Brand & Paul Saffo | SALT
 - [[Painted.Woman.2017][Pace Layering: How Complex Systems Learn and Keep Learning]]

  slippage between layers, negative feedback looks

    - turbulence
    - viscosity

  young are concerned with fast layers -- especially fashion


  | Fast layers              | Slow layers          |
  |--------------------------+----------------------|
  | learns                   | remembers            |
  | proposes                 | disposes             |
  | absorbs shocks           | integrates shocks    |
  | discontinious            | continious           |
  | innovation/revolution    | constrainy/constancy |
  | *gets all the attention* | *has all the power*  |
 
I find it interesting that Alexander seems to be aware of
all of this, but never takes it on directly.  He has always
been focused on creating new buildings where you can start
with a clean slate and do things the right way.  But most of
the time that's not what you can do.  He always talks of
gradually moving from what is existing to how you want
things to be but doesn't address any of that in APL as much
as he could have.  We build on top of what came before.
There is no clean slate -- thinking that you can is the
architect's hubris.

The moments when you can do tabla rosa are few and far
between.  The great fire of london, a tsunami in Japan or SE
Asia wipe everything out, even cadastral maps (because the
property holders are gone as well as the buildings).  We
should fear such opportunities more than wish for them,
because unless you start small and grow bottom up in an
organic manner we will /always/ fuck it up.

But it's even worse than that because when say Myanmar or
Dubai backed by a mountain of cash have tried to clean slate
things they try to jump over all of the intermediate steps
that leads to functional, beautiful human settlements.

Alexander has essentially made the case to abolish the whole
class of architects and architecture as we know it today and
go back to the older concept of the master builder.

The big name architects are too focused on originality and
have largely forgotten craft and that structures are a part
of the environment (context) that they are built in and are
built for mostly pedestrian functions.  They put the focus
of vision on originality rather than achieving the purpose
the building is meant to fill.  The small name architects
are often just as bad or worse because they are just
knocking out structures at a distence according to
specifications provided by a customer that are based on
lowest common demoninator metrics and contruction financing
and practices that are estranged from the purpose that the
building is meant to fulfill.


**** Paul Saffo's Pace Layers

 - Anthros
 - Bios
 - Lithos
 - Cosmos

So if we combine this with Brand's model we get:

A General Theory Of Bureaucracy (1961)
Elliott Jaques

https://en.wikipedia.org/wiki/Elliott_Jaques

/Time span of discretion/ that a manager can be ranked 

seven layers on timespan of 

time from formulate a plan to it's execute

the lower the number the shorter the timespan



**** Japanese mayor (story from audience member)

An classic example of long term application of /timespan of
discretion/.

http://www.dailymail.co.uk/news/article-1386978/The-Japanese-mayor-laughed-building-huge-sea-wall--village-left-untouched-tsunami.html
http://blog.nihongo-pro.com/2011/04/mayors-vision-saves-japanese-village.html

Was mayor for over 40 years and in that time went against and fought
to build a tsunami barrier for this town.  He died before it was ever
used but the barrier saved the town.

**** Rice on Chessboard

People don't grok exponential growth

pace layers turn Hockey Sticks into S-Curves

**** The Apsara of Context, Scale, Time and Change

Though not discussed in the talk, the other two things that
we can't grok are /size/ and /time/ at scales that are
outside of human empirical limits.

Taken together /rate-of-change/ (ROC), /level-detail/ (LOC)
and /point-of-view/ (POV) are the three things that define
the context of almost anything.  They are also are our
biggest blindspots when any of the three fall outside of
human scales and comprehension.

Is blindspot the right term?  Failure of imagination?
Cognitive limitation?  hmmm.

Relativity is based on the concept that what is real is
dependent on the context of the observer -- this is just
another formulation of that concept from a different POV.

One of the Meta goals of our project is to find ways to help
us as individuals and collectively to make these things
comprehensible so that we act on them when it is necessary.

Climate Change is a problem because we can not comprehend
the problem that we have created for ourselves.  The Long
Now Foundation focuses on long term thinking and
perspectives but scale and change are equally important.  I
know that they think that's baked into their mission but its
worth spelling out.

*** Nature

We divide nature into the /1 cosmos/, /2 lithos/ (as in the
lithosphere) and /3 bios/ as in the biosphere.

Cosmos includes everything in the universe down to planetary
or planetoid scales.

Lithos (meaning rock) is any planet or planetoid where
mankind might end up hanging his hat or exploiting in some
manner.  Lithos includes artificial planetoids that are
meant to be habitats including everything from the ISS to
large scale habitats housing thousands or even millions of
people.

Bios is any biosphere that supports life that is contained
in a /lithos/.

Putting it all together:

The Universe is the Cosmos.  But more practically, the
pattern language will be concerned with our Solar System as
a /system/ which includes the Sun, planets, planetoids
orbiting it and the mechanics of moving around in it and
dealing with things like solar and cosmic radiation, light,
heat and electromagnetism and how all of this pertains to
building and maintaining an life and specifically an
antifragile distributed civilization.

The lithos is any physical inanimate natural or manmade body
that is exploited or used to create a habitat irrespective
of whether the body is habitable.

On earth the core, mantel and crust would be the lithosphere
and the biosphere is the thin envelop made up of an
atmosphere and a hydrosphere where life can exist.

The structure and shell of the ISS would be the lithos and
the atmosphere within and the machinery for maintaining
pressure, temperature and scrubbing C0^2 would be its
biosphere.

/Anthros/ layers are anything within a biosphere and follows
Steward Brand's five layers, culture, governance,
infrastructure, commerce and fashion.  There is always a
tradeoff when you define models like this because you are
indicating organization for the purpose of understanding
something that doesn't exist.  The layers are a useful way
of understanding how different aspects of civilization that
change at different speeds interact with each other.



----

We are a part of both realms and we impact and are impacted
by both realms.  We are part of nature, there is no them and
us.  This is very difficult concept for modern man to
comprehend because we have convinced ourselves that we are
exceptional and outside of nature.  Gravity applies to us
the same way as every other thing in the universe.  Jump out
of a airplane without something to slow us down like a
parachute and we will splat just like a watermelon.

A city is part of nature as much as the most isolated meadow
in on the Tibetan Plateau.  Both belong to and depend on the
same pressurized atmosphere, and protection from solar and
cosmic radiation to support life.  You can say that the
meadow is nature uneffected by man, but that isn't exactly
true either.  Mankind has been shaping the world for tens of
thousands of years using fire, long before the first
civlizations emerged in the alluvial wetlands of Mesopotamia
that fundementally changed the biodiversity of broad swaths
of the planet, especially megafuana.  Cliff paintings
overlooking the Mekong River portray a number of different
types of megafauna that are now long extinct.  The most
likely explanation for the extinction of species like pygmy
rhinos and the giant sloth is man.  Other megafauna, which
could reproduce quickly and were more fleet of foot than the
sloth such as antelope, deer, caribou and elk flourished as
a reliable food source managed by using fire to shape
habitats which encouraged those species.  It can be argued
that mankind terraformed the planet with fire.

/Nature/ patterns are concerned with Mankind's interaction
with nature, both physical and living.

The degree of that interaction can be divided into wild and
cultivated.  We used to be quite good at managing the wild,
but got lost when we turned to pure cultivation and
eventually began to see the wild as something in opposition
to and an enemy of the cultivated.  In modern times, those
who call themselves environmentalists and conservationists
are no less guilty of this false dichotomy.  We need to stop
thinking in terms of us vs them, nature knows no such
divisions.  We can not become one with nature, because we
were never apart from nature in the first place.

When talking about the realm of life we will use the concept
of /habitats/ that contain /biospheres/ that are sometimes
divided into /biomes/ that contain life.  At the time that
this is being written there are only two biospheres that we
are aware of, the planetary biosphere that envelops Earth
and a tiny biosphere in low earth orbit called the ISS
(International Space Station).  Eventually there will be
more biospheres, a handful at planetary scales and many
smaller artificial ones.  The nature of how mankind shapes
and manages those biospheres is the subject of this pattern
pace-layer.

Change at planetary scales both physical and biological take
place in geological time scales.  The tectonic plates of the
Earth inch together and apart so slowly even the Ents would
consider them to be slow.  The evolution of life largely
takes place in time scales that dwarf any one species.
Occasionally something like an asteroid impact, the eruption
of a supervolcano or other event triggers massive change,
but the impact of that event often takes far longer than we
might think.  The dinosaurs didn't all die off within days
or months or even centuries after the asteroid hit the
Yuccatan.  A true planet killing event has yet to happen to
Earth.  We know this because we are here to talk about it.
But there were a couple of times that things were close.

