#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Alienation
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Alienation
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-alienation.org
:Created:  2018-04-04T11:11@Prek Leap (11.642600N-104.919210W)
:ID:       3d44545c-d199-4b2c-9685-006c3f096d5d
:VER:      576087164.792241791
:GEO:      48P-491193-1287029-15
:BXID:     proj:QUQ4-3676
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR
** Table of Contents


  - Start with Olson cite:olson:1970special 

  - Then estrangment described by Havelock cite:havelock:1963preface

  - next dislocation was Copernicus, and Darwin together with
    industrialization -- cut us off from our connection to the natural
    world.  not in a romantic sense, but physically cut us off

  - man saw himself in opposition to nature.  that the natural was
    trying to kill you, and strove to bring it under control, our
    urban environments eschewed natural materials -- replacing them
    with paint, and stone and tile that was clearly under man's thumb

  - the enlightenment ushered in rationality and prosperity but it
    left us adrift and apart we desperately wanted to be at the center
    of things -- we inately understood that we could see the world
    very differently from other animals and that we had a sense of
    ourselves and the future that they lacked -- and we were
    constantly grasping for ways to understand this power our minds
    had -- it was lonely -- but if it was part of a divine plan,
    because god too was as lonely and as conscious as we were, then it
    must be all right.

  - Ford's assembly line created perfect copies of things numbered in
    the millions -- each the same as every other -- our material world
    was not something we as individuals had control over, our instinct
    to adapt the world around us had been destroyed by perfect
    identical copies.   There were no subtle variations, each adapted
    slightly differently and in harmony with each other -- Walmart had
    none this -- just stacks and row after row of identical copies in
    the windowless warrens illuminated by harsh fluorescents.



  - Then Alexander
  - The bleak alien minimalism of Modernism
  - quote's from ZAMM cite:pirsig:2008zen
  - Then Soleri cite:soleri:1999arcology
  - Then Mills White Collar cite:mills:1951white

  - quote Beckett "I can't go on. I'll go on."

  - Then about how alienation has become internalized cite:jay:2018alienation
  - Marx's theory of alienation cite:wiki:2018marx-theory-of-alienation

  - One Dimensional Man cite:marcuse:2002one-dimensional
  
  - Gray cite:gray:2010uncivilization

** References

 - Gray, J., Uncivilization: the dark mountain manifesto, New
   Statesman, 10(), (2010).
   cite:gray:2010uncivilization
 - Havelock, E. A., Preface to plato (history of the greek mind)
   (1963), : Harvard University Press.
   cite:havelock:1963preface
 - Jay, M., /A history of alienation/ (2018).
   cite:jay:2018alienation 
 - Marcuse, H., & Kellner, D., One-dimensional man : studies in the
   ideology of advanced industrial society (2002), : Routledge.
   cite:marcuse:2002one-dimensional
 - Mills, C. W., White collar: the american middle classes (1951), :
   Oxford University Press.
   cite:mills:1951white
 - Olson, C., The special view of history edited with an introduction
   by ann charters (1970), : Berkeley CA: Oyez.
   cite:olson:1970special
 - Pirsig, R. M., Zen and the art of motorcycle maintenance: an inquiry
   into values (2008), : Harper Perennial Modern Classics.
   cite:pirsig:2008zen
 - Wikipedia, /Marx's theory of alienation --- wikipedia, the free
   encyclopedia/ (2018).  cite:wiki:2018marx-theory-of-alienation
 - Wikipedia, /Social alienation --- wikipedia, the free
  encyclopedia/ (2018).
  cite:wiki:2018social-alienation
 - Wikipedia, /White collar: the american middle classes ---
   wikipedia, the free encyclopedia/ (2017).
   cite:wiki:2017white-collar-book 
 - Soleri, P., Arcology: the city in the image of man (1999), :
   Bridgewood Press,.
   cite:soleri:1999arcology
 - Soleri, P., Kim, Y., Anderson, C., Nordfors, A., Riley, S., &
   Tamura, T., /Lean linear city: arterial arcology/ (2012).
   cite:soleri:2012lean-linear-city
