#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Civilis
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Civilis
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-civilization.org
:Created:  2018-03-29T09:15@Prek Leap (11.642600N-104.919210W)
:ID:       dcebab12-82b3-4757-834a-289a23414c58
:VER:      575561807.552927464
:GEO:      48P-491193-1287029-15
:BXID:     proj:IBK3-5173
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

Civilization -> comes from the word civitis meaning city.
The ancient greeks used the word polis to mean city, but it
was also the closest thing they had to the concept of
civilization.  This is a good place to start -- and grounds
us at human scales.

** Table of Contents
  - 01. Definitions I. One or many?
  - 02. Definitions II. Historical
    - Ba Ba Ba: Us vs. the Other
    - A Clash of cultures, states, religions, or ideologies
    - A Parade of Great Men
    - Human Nature as Social Drivers
  - 03. Definitions III. Complex System
    - DNA's Grand Experiment 
    - Cerebral Cortex: Extended and Externalized 
    - Holarchy
      - Self-Organizing Holarchic Open System (SOHO)
      - Civilization is a sub-holon of the bios-layer 
    - A Fabric of Process
    - A Very Slow AI
  - 00. [[./ww-narrative-synopsis.org][A Narrative Synopsis]]
  - 04. Specialization
  - 05. Polis as Building Block
    - Of Nations and States
  - 06. Carrying Capacity
  - 07. Holding it together
    - propagation, linguistic, cultural
  - 08. Complex Societies as Systems
  - 09. Pace-Layer Model
    - *Bios Layer* :Civilizations have seldom been
      understood as being a layer that we inhabit in a
      larger biosphere -- that the ecosystem we belong to is
      as much a part of civilization as anything else.
      Pretty much everything written about civilization only
      talks about ecosystems in terms of resources -- as if
      resources were external to the system.  A civilization
      in the middle of an Ice Age will be very different
      from a civilization during an era with a clement
      climate.  It is not enough to only talk in terms of
      carrying capacity, but also climate patterns,
      biodiversity, how difficult or easy is it to extract
      raw materials from the lithosphere.
    - *Anthros Layer*
    - *Culture Layer*
    - *Governance Layer*
    - *Infrastructure Layer*
    - *Commerce Layer* 
    - *Fashion Layer* 
  - 10. Civilization As Generative Genome
  - 11. Cherry Picking: Towards Civilization From First Principles
    - All Things Apply To Everyone
    - Only Human Scales
    - Adjusting for Human Nature
    - More Eggs in More Baskets
    - Never Evenly Distributed
    - Rejoicing in Diversity
    - Embracing Uncertainty
    - Generative Plans, Designs, and Management 
    - One Step Forward, Two Steps Back

** Getting up to speed

Getting up to Date:

   - Before the enlightenment the big shift was first
     development of spoken language.  But memory was still
     RAM, that only existed in living memory.  But this was
     enough to create permanent settlements, agriculture and
     scale communities that made it possible to increase the
     complexity of human societies by several orders of
     magnitude.  This was the beginning of the concept of
     property, and extending that concept from land, to
     material goods and to other people.  The slave era was
     a paradox, subjecting most people to wretched lives
     where the wealth they created propagated to an elite
     few, and did not improve the lives of those creating
     the wealth.  But it also created surpluses that
     extended the elite to a new class of people people
     whose only job was to think, solve problems and come up
     with new ideas.  But this was an oral tradition, the
     surplus's had a ceiling which was essentially that of
     the memory of individual humans -- this was the world
     of Homer.

   - Those surpluses allowed people to solve the memory
     problem by inventing written language -- which extended
     human cognition, externalized human memory and made it
     possible to communicate to places that the author had
     never been and into the future.  This triggered a
     cognitive revolution that was not to be matched until
     the industrial revolution -- The industrial revolution
     began earlier than many thought, and a number of
     keystone inventions laid the groundwork for it over
     several centuries -- including the printing press, the
     concept of external power sources such as wind and
     water (not as propulsive power, but to power tools,
     laying the groundwork for machines).  Other keystone
     inventions included standardization of measures, time
     measurement, the printing press, etc.

   - The steam revolution was at the heart of the industrial
     revolution -- 

     steam was crude and wasteful, which was replaced by the
     internal combustion engine which bypassed steam and
     moved fire directly into the engine.

   - The electric revolution vastly reduced the number of
     moving parts and replaced fire completely and was far
     more flexible.

   - electricity made machines very large and very small --
     which meant that muscle was not only replaced at very
     large scales, but human scales with machines at human
     scales and machines that worked at scales far smaller
     than human scales -- this which made possible the first
     cognitive machines.  It not only created machine
     cognition, but machine memory -- memory that could be
     used to think internally within cognitive machines.

----------------

   - a few pockets of civilization, in ancient Greece, India and
     China laid the initial groundwork that solidified
     mankind's transition from spoken language to be able
     to externalize and extend mind and memory using
     written language.
     - scientific revolution kicked it off
     - based on rationality, science, and progress (Pinker's def)
     - Bacon, Decartes, Locke and Spinoza
     - place in the universe
       - the Copernican revolution -> we are not at the center
       - the Darwinian revolution -> we are not apart from nature
   - mechanization extended the hand using tools, to
     machines leveraging hand and muscle.  This
     fundamentally transformed man from beasts of burden
     controlled by an elite, to thinking slaves operating
     machines -- machines replaces human muscle.


   - combined with Industrial Revolution, began, in 1800 a
     transformation in human existence.
     - war, violence, poverty, education, human rights
       etc. all began a massive upwards curve that we are
       still in the middle of.


