#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Fabrication
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Fabrication
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-fabrication.org
:Created:  2018-04-16T12:31@Prek Leap (11.642600N-104.919210W)
:ID:       f67b6411-1e2b-4fe7-a4b9-aa5543da2118
:VER:      577128773.320555408
:GEO:      48P-491193-1287029-15
:BXID:     proj:DFG1-2416
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

I originally was going to call this part 'Development' or perhaps
'Methodology" but neither felt right.  They are too fixed and formal
and don't match the process that I want to convey.

When you watch a bird build a nest, the entire process seems random at
first.  The bird will pick up twigs almost at random, drop them then
pick up another and take flight to a branching in a tree.  It will
consider the tree and move it's head this way and that, as if checking
to see if the twig in its beak, is a match for the branch in the
tree.  Often the answer is no, and the trig is dropped and the process
strarts again, with another twig and another branching of another
tree.  But eventally something feels right and the bird places the
twig in the branch and returns with another.  Sometimes rearranging
the twigs a bit, someone times just seeming to drop them in at
random.  But in each case the bird doesn't have any preconcieved
notion of what the nest will look like, what the other birds will
think if it other than, if it's a male, building a nest to attract a
female if it feels right or not.  Is this something that a female
would find impressive or not.  But it's a gut feeling, there is no
plan, there is no design -- just a step by step process of aggregation
and adjustment until it feels right.

This, is what The Way is all about, it's a process of fulfilling a
need by instinct, not as a rational goal driven process with an
invisioned future outcome that will satisfy all sorts of other goals
that will determine your reputation, how much you will be rewarded or
how you hope others will percieve you.  It's taking the ego out of the
process and just aggregating a series of steps, each of which feels
right and makes what you are building stronger or more beautiful or
just leaves you with a feeling content and at peace.

This is why we separate the Way from the process of fabrication --
beause unlike birds, we have to use abstract and very concrete
methodologies to ensure that a roof won't cave in under the load of a
heavy snow, or blow off during a Typhoon, or collapse during an
earthquake.  We need to ensure that our software does what the user
intends it to do, add up a column of numbers correctly, show you the
next screen of text that the link pointed to.   All of these things
are deterministic and based on many generations of other engineers
learning throgh trial and error, and countless experiements and
failures.  Either the wall will bear the load you put on it or not,
there is no feeling about that, it's binary -- it does or does not, as
Master Yoda would say, there is no try.

And yet, if we ignore our instinctual understanding of what feels
right and what is right and leave that out of the process, then we get
the software, design and structures that we've been getting since the
industrial revolution literally picked up a full head of steam.  We
are then what we build is determined by things that the tools we use
and the production processes that are geared for maximum efficiency in
terms of material use and production.  In modern times this has been a
large part of the estrangement that we experience from ourselves as we
are cut off from what we know instinctually feels right, and makes it
impossible to connect you we are from other people and the natural
environment that we live in.

The challenge is to bring the two together, the natural aggregation
and rearrangement of the bird, married with the metis, the practical
knowledge of how to build things within the constraints that classical
physics places on us.


** Table of Contents

