#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Warp & Woof Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Warp & Woof Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-intro.org
:Created:  2018-02-15T20:19@Prek Leap (11.642600N-104.919210W)
:ID:       f8ae9d01-083a-4598-84e7-249d560fca6c
:VER:      571972838.678903093
:GEO:      48P-491193-1287029-15
:BXID:     proj:OKM3-3142
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

No shit, a tl;dr for an introduction

** Table of Contents

  - a generative genome for Mankind
  - /ab initio/ on the shoulders of giants
  - of a history of extension & externalization
  - inevitable but unpredictible: anticipating post-scarcity 
  - the enlightenment rebooted
  - the fifty year window


** Introduction

At present. civilization is still at the whim of
evolutionary natural selection, random mutations happening,
with the successful ones replacing older ones.  We might
think we are in charge, but only as individuals, and even
then... not so much.

Mankind is at the brink of being able to take conscious
control over dna -- within a few decades we will be in
complete control of the design of all biological systems --
but that is mucking with individual genomes -- there are
larger meta structures of how these organisms organize and
interact to form large complex systems.  These systems exist
outside of human scale -- either too small or too large and
slow for us to easily see, let along understand, let along
change or control in any meaningful way.

Civilization is one such system -- and our clumsy attempts
at steering civilization or even understanding it is not
enough.  Collectively we are making a mess of things -- we
need to start understanding how civilization works, and how
we can shape and eventually manage it before we overrun the
petri-dish and trigger a massive die-off and collapse.

We need to work out a genome for human civilization and then
a CRISPR type mechanism for fixing things and test new ideas
in controlled ways.

This will never work if we take a top-down command and
control approach -- we need to understand how to inject
changes from the bottom up and when they've been tested and
work, then let them propagate.

We'll never be able to control civilization in the same way
that say you can control a car when driving down the road.
Complex systems make that impossible -- but I believe we can
learn to shape civilization slowly over time towards desired
outcomes -- as Kevin Kelly observed, you can tell what will
be inevitable but now the specific form that that
inevitibility will take. cite:kelly:2016inevitable

What this works sets out to do is to create methodologies
for understanding and modeling civilization and then work to
make desired outcomes inevitable -- once they become
inevitable they can be shaped to some extent -- thought
there is no way of knowing what form that will eventually
take.

I am, personally, a extremely pessimistic person, I have
never seen much hope for the human enterprise in any short
term and I still believe that we are all too capable of
derailing the progress man has made since 1800.

But that doesn't mean that I'm not going to try.  I've
always personally believed that the only way you can truly
fail is if you give up.  Steven Pinker's relentless optimism
about the reality of human progress and that it can continue
to not only improve but that improvement can continue to
accelerate has worn me down to the point where I admit that
he has a made a very good case.

But this will not happen unless all of us work together to
make sure that this happens.  The challenges ahead of
humanity just in this century alone almost beggers the
imagination.  It will take every ounce of imagination,
strength and as Pirsig said, gumption to make it happen.

A framework for understanding and changing the genome for
human civilization would be a very useful part of this
effort -- if successful it would make it possible to
coordinate our efforts better, identify what things are
being worked on and what areas aren't getting enough
attention.  It could help provide metrics for understanding
where we stand, where we are going and provide clues of how
to correct mistakes and move more clearly in the right
direction.

This is an audacious undertaking -- and something that I
have been working on full time for nearly two decades.  The
project has now come to the point where all the pieces are
coming together and the broad outline is visible.

Now that I've reached this stage, the project needs to make
the transition from being a solo effort to a building a team
to begin filling in the blanks, run experiments in the form
of projects that are designed to make practical improvements
in people's lives today, while learning to map out the
genome, how it works and how to improve it.  Some of this
work will be traditional R&D, some NGO projects.  But the
vast majority of the projects will be designed to be
not-for-profit.  In other words they will be designed to
make a profit, and be self-sustaining, but the larger goal
for each project will be to materially improve people's
lives first, and making a profit second.

The entire zero-sum mantra of "maximizing shareholder value"
is nothing short of obscene, and growing at all costs, when
growth is simply making a small group of people wealthy
should be considered to be the lowest of human activities
and should be held in the same contempt and a crime against
humanity.  The problem is that the system has so corrupted
us, that most people can't understand that the world was not
always this way, and it doesn't have to be in the future.
We can all strive to give everyone a high standard of
living, a life with purpose, without fear, or pain.

We can not tolerate zero-sum anything any longer.
Everything we do must be designed to be positive sum --
things that help me as much as they help you and everyone
else.

Any time someone tells you, that you have to suffer in order
to achieve an important goal is selling you a lie.  If
something doesn't make financial and economic sense, there
is something wrong, because it won't work, and the only
people who will subscribe to it are well-meaning chumps.
What DOES work is to teach people how to change their
behavior to do things in ways that improve their lives --
this is difficult, we aren't very good at changing -- and
this is why it won't happen overnight.  The older you are
the less capacity you have to change.

For this reason, it's good that we we still have time enough
to teach the next generation positive-sum habits.  It's very
likely that human lifespans will increase to hundreds of
years or even longer in the next few decades.  That is good
news, because it still gives most of the zero-sum generation
time to die before we start sticking around for significant
fractions of millenia.

And as these new generations grow older and older, they will
be old enough to have seen and understand much longer term
processes than we short-timers can today.  This will be
crucial to the long term survival of our species and
successful stewardship of our planet, and eventually the
rest of the solar system as humanities childshood ends and
take the first steps towards becoming a a mature
technological species.

The most terrible crimes against mankind since the 20th
century were the Year-Zero men

It is hoped that we are nearing a time when it will become
impossible for another of these monsters to take control.

The next step is to eradicate the Zero-Sum men and women
whose whole existence is to take from you to profit me.

Building a positive-sum genome for human civilization from
first principles would be a good first step.

Can we pull this off?  The pessimist in me is shouting in
one ear that it's a real long shot.  But then, the tiny
optimist's voice is whispering in my other ear is saying,
"hey, that loudmouth might be right, but what have you got
to loose.  It's worth a shot, isn't it?"


** of a history of extension & externalization

If pressed to sum up Mankind in a few sentences I would say
that Sapiens (the sub species of Man that we belong to)
history is no different from any other species on this
planet except for a single thing.

Sapien's large cerebral cortex makes it possible for us to
be goal driven, we can think abstractly out how to achieve
goals that might take many intermediate steps to achieve.
Not even any of our other other primate cousins can do this.
It enables us to think of time as linear, with a past, a
present and a future.  All other creatures live in a
perpetual present with no future, and a past that are made
up of memories of past events, but are not ordered into
causal chains.

This one ability to understand abstract concepts that
require multiple steps and imagine potential outcomes at the
end of all of those steps set all of human prehistory, and
with the invention of written languages, history in motion.

It made it possible for us to take an innate ability to be
able to ,modify and manipulate things in the environment
into tools.  But with with the addition of our ability to
envision multiple stage goals, these tools became
increasingly refined to the point where they became
extensions and eventually externalizations of our mind and
muscle.

Our entire history is the story of extending and
externalizing our mind to reshape the world around us.  The
first step was to externalize our mental abilities to be
able to communicate these abstract ideas with others.  This
gave us spoken language.  Taking this a step further we
learned to create symbol systems that could transcribe
concepts and human speech into clay, stone and parchment
that could be duplicated and sent to distant places both in
space and literally into the future without the person who
first recorded those ideas ever meeting or knowing who wouid
later encounter them.

The invention of moveable type and the printing press made
it possible to make countless and exact copies of written
messages which vastly reduced copying errors, which are the
bane of all communications, and potentially be read not only
by every living person alive when it was written, but every
living person who would ever live in the future.  It took
blind evolutionary processes billions of years to evolve
RNA/DNA to be able to do that.  Sapiens did it in the
evolutionary heartbeat of a humming bird on crystal meth.

Think about that for a second, Man can now do the same thing
that the blind chance mutation and natural selection process
of evolution as deterministic goals and we soon will be able
to do this in human time scales.

It's that last part which is particularly important, because
Sapiens don't scale, or at least we really suck at it.  All
of human progress has been a double edge sword that has
reaped astonishing achievements, while at the same time
making other things worse, and often much much worse.

When I talk about human scales I am /not/ talking strictly
about Rousseau's return the the original state of nature.
Though the idea of prosperous egalitarian bands of hunter
gatherers wandering the planet and living a pretty good
life, in comparison to that of the sedantary farmers and
urbanites who replaced runs counter to a growing body of
evidence that it is little more than a secular myth adapted
from the Christian meme of a man's fall from grace and being
driven from the garden is simply not supported by the
archeological evidence.  That said, group sizes that
correspond to bands (15-40) are human scales where groups
can function well.


All of Sapien's brainy achievements were only possible
because surpluses of food, and material goods needed for
survival could be produced that allowed a small portion of
the population to do things that were not directly related
to immediate survival.  Those surpluses let a small number
of people spend most of their time thinking.  That's the
good news.  The bad news is that in oder to do this,
hierarchical societies were needed that were based on
inequalities that took the surpluses created by some members
of the group and gave them to a few people who were in power
and a handful of others whose job it was to think.  That
system is called slavery.


** the enlightenment rebooted


#+begin_quote
More-over, this is classic motte and bailey. The motte is
"The US consitution was not unique" with the bailey being
"The US government was not unique". The later is simply and
totally false, a revival of the ancient idea of democracy
coupled with a strong rule of law and a respect for
individualism and the inalienable rights of man was a
completely radical thing at this point in history. The parts
were not first invented here, but they were first put
together into a coherent whole.

....

The Enlightenment (the movement) was based on
empericism[sic] and experimentation far more than pure
rationalism, even though enlightenment (the philosophical
concept) might have been formulated in different terms.

— /r/j9461: [[https://www.wsj.com/articles/the-dark-side-of-the-enlightenment-1523050206][Comment on The Dark Side of the Enlightenment]] | WSJ
  https://www.reddit.com/r/slatestarcodex/comments/8azimq/the_dark_side_of_the_enlightenment/dx3axmb/
#+end_quote




* Notes


W&W will be to APPL that /A Timeless Way of Building/ 
(TWB) cite:alexander:1979timeless is to APL. cite:alexander:1977pattern


TWB starts with this:

#+begin_quote
/The Timeless Way of Building/ is the first in a series of
books which describe an entirely new attitude to
architecture and planning.  The books are intended to
provide a complete working alternative to our present ideas
about architecture, building, and planning—an alternative
which will, we hope, gradually replace current ideas and
practices.

— A Timeless Way of Building
  cite:alexander:1979timeless
#+end_quote

#+begin_comment
Replace architecture and building with civilization and it's
not a bad description of W&W and APPL.

TWB was published two years after APL, which answers the
chicken and egg question, but it also makes sense.  TWB
couldn't have been written until after they had all but
completed APL.

TWB is divided into three Parts: The Quality, The Gate, and
The Way.

   - /Quality/ is QWAN.
   - /The Gate/ is the Patterns.
   - /The Way/ is how to get QWAN using the patterns.

The organization of the book also is design to work at
multiple LODs, like /The Plan of St. Gall/ with an outline
of the entire work, and then detailed TOCs at the beginning
of each volume.



TWB is almost mystical -- it does not come across as a
practical text on how to build according to his philosophy
and methodology.  It's almost a manifesto.  This was on
purpose, but as some reviews have noted, it could be one
reason that it hasn't been treated as seriously as it
should.  It's too outside of the mainstream, too easy to
dismiss and doesn't provide a bridge for architects and
builders to cross from their world into his.

The Oregon Experiment (which I still haven't seen) seems to
be where he shows a concrete example of how to plan, design,
and build.

So what about W&W?  We don't need to build the same bridges
that Alexandar should have, but at the same time we need to
bridge the gulf of how civilization is today, how the
present attempts at change are useless and all but
worthless.  So I suppose we do need bridges.  But is W&W to
be a bridge or manifesto?

I don't want to be too mystical, but I also don't want to be
too concrete which is why I'm so attracted to the Plan of St
Gall (PSG).  St Gall was never built -- so the designs based
on the plan are -- as the title says -- paradigmatic. PSG
delves deep providing historical, social, economic and
archaeological context and evidence.

So I suppose that W&W needs to blaze a path between the two
-- so that it's part Timeless Way and Part Plan of Arc Nong
Pao.

In fact that's about right -- first volume should be closer
to TWB and the following volumes should provide three Plans
-- two on earth and one on mars.

In that respect I suppose we can borrow many things from
Mollison's Designer's Manual -- which is, in many respects,
a path between TWB and PSG.

The whole pace-layer model will take a bit to lay out -- and
we will have to make a case for why we are on the wrong
path, and how we have no choice but to start from first
principles.
#+end_comment

** Warp & Woof




*** Part 1: Three Point of Views



*** Part 2: Dualities
 - part     <>  whole (holon)
 - map      <>  territory
 - metadata <>  data


Part-Whole


map-territory and metdata-data are types of part-whole relationships

---

Map-Territory 

is an more of an LOD than part-whole relationship

a map is not a part, and a territory is not always a whole

a map contains the structure of what it maps at a lower LOD

---

Metadata-Data 

metadata describes threads or patterns in a whole but does
not attempt to map the whole

metadata can describe a data set, but can also be used as data
depending on the POV


*** Part 3. Structures
 - graphs
 - lists
 - trees

I suppose we can talk about narratives -- linear structures,
rhizomatic structures where everthing is connected to
everything, which I suppose is a graph, and then
hierarchical structures which are tress.

Humans think all three ways -- we think linearly as stories and
we think as paths snaking through rhizomatic structures

and I think this is how we need to put it:

  - complexity is best suited to rhizomatic structures
  - sets are lists for threads winding through those
    structures these are ideal for modeling deterministic
    processes. lists can be:
    - bag -- intentionally unordered -- the order is not significant.
    - seq -- ordered -- the order may be by time, number,
      alphabet, magnitude or class.
    - alt -- which is a branching list in which only a
      single item can be chosen -- this is taken from user
      interfaces but also multiple choice tests etc.
  - trees for creating hierarchies -- which are nature for
    pack animals -- trees are partial rhizomes that show a
    specific set of causal, command and control type
    structures.  



*** Part 4. Boundries

 - physical and cognitive limits

   sensual limits
     - light & color
     - sound
     - smell
     - touch
   cognitive limits
   cognitive bias
   memory limits
   social limits
     - number of friends
     - group size
     - generational
     - change thresholds
   temporal limits
   biological
     - atmosphere
     - temperature
     - food
     - sleep -- diurnal cycles 
     - size
     - age  

*** Part 5. Estrangement
:PROPERTIES:
:ID:       31a5d7c9-9685-4ec3-9d1f-ea60810b7ebb
:END:

 - quality -- beauty    -- connectedness
 - caring  -- integrity -- control


Alexander's QWAN and Pirsig's Quality are framed by Olson at
that is that which we are estranged estranged from which is
most familar.

In different ways they seem to dump the estrangement at the
feet of Aristotle  ---

They all seem to agree that if we can get back what we lost,
that everything else will come together.  Of course this is
a old meme.  If we can just restore ourselves to what we
were in the Garden before Eve bit the apple, if we can
return to an agrarian utopian past that never existed etc.

But that's not what Alexander and Pirsig and Olson are
talking about here -- it's not returning to a romanticized
fictional past which never existed, it's finding the part of
ourselves that we left behind when man developed spoken
languages and then written languages and so on and so forth
-- at each stage we added layers of mediation between us and
the world to the point where we are disfunctional and deeply
unhappy.

I think they have the right idea -- it's not returning to
anything but reconnecting to what the world is, that we
can't see any longer.

There is a whole raft of different books that are focused on
the different aspects of what is missing, mastery, rest --
hell, epicurus was the first to get at the roots of the
problem so very long ago -- fear.  The stoics said to face
your fear and then it had no power -- epicurus wanted to
eliminate it so that you didn't have to face it.

I'm still not sure, but perhaps process philosophy is a good
fit here -- if everything is the present -- time is not a
line and there is no past or future, then there can be no
retribution or reward in an afterlife.  Though, actually PP
doesn't preclude heaven and hell, it would just be part of
the present, hmm... stick with epicurus on that.

I hope we can include the TEDTalk from the brain scientist
who had a stroke -- which presents the concept from a
biological AND personal perspective.

Her experience explains a lot -- that self-consciousness is
a brain function, and a very useful one.  If a living
organism can not differentiate itself from the rest of the
universe it can not function -- it becomes an
undifferentiated part of the continuum of the universe.  The
problem is that we have let it go to our heads (bad pun) and
have not kept a healthy balance between self and world, our
map is trapped in the delusion that it is the territory and
forgotten that we are also part of a territory far bigger
than ourselves...

Even worse, we have built up concentric layers of collective
maps around us to the point where we don't know what is
real and what isn't.

We need to reconnect to the world and find a balance between
being a part or being a part of a whole.


#+begin_comment
[2018-03-10 Sat] Tried to explain some of this to Mike
tonight when I was in Phnom Penh today, but I think he
didn't understand what I was trying to say.  I called it
mediation rather than explain map-territory.

Am I on the right track here?  I still think so.  But that's
the problem of working on this stuff for so long on my own,
I need more feedback to make sure I'm on track.
#+end_comment


*** Part 6. Pattern Languages

What are pattern languages -- how they work, how to make
them, how to use them.

Need a chapter on what patterns are NOT.  Many of the
pattern languages and there are a lot of them, do not seem
to understand that patterns are not simply another
methodology you use in software or construction projects,
they are meant to reveal sets of complex relationships which
defy description.  They work on a nonverbal level as much as
the verbal, they are not classification systems.  Patterns
are only useful if those patterns have been woven into your
brain, you have to master them through conscious practice,
experiment and contemplation.  If you don't they are just
another checklist of attributes or features to add to a
design or project.  Patterns are not snap together modular
Lego Bricks.  When they have been used that way people
wonder why they don't work.



*** Part 7. The Way (placeholder)

Like in TWB's part of the same name, The Way describes how
to put everything together from the first six Parts as a way
of parsing the world, and putting what you have learned
together to understand things, to build and maintain complex
societies, build structures and settlements, protect and
shepard ecosystems, industrial production, build software
and networks and not least, live a Good Life.

The thing is, that there is no one methodology to
this. That's hard, but W&W is a generative grammer and
toolkit for creating methodologies for building and using
pattern languages to build and use Primers.

you can use w&w to build any number of methodologies -- so
long as you are aware that they are living processes that
are not set in stone -- they must designed to adapt to
changes, to encourage experimentation and careful adoption
of what is found to work.  They are not to be chiseled in
stone or codified or turned into dogma -- like Pirate Law,
in /Pirates of the Caribbean/, they are more guidelines than
laws.



** APPL

#+begin_comment
It took me a long time to really grok patterns.  The first
time I saw the book I was hooked instantly.  But how you got
from patterns to actual buildings wasn't so clear.  Even
today, after reading /The Nature of Order/
cite:alexander:2004phenomenon it still wasn't clear.  I
understood what he was proposing, but implementation is
still too fuzzy -- it's almost as if the gulf is too great
between the past and present -- we are so estranged and
broken that building things from a deep sense of
connectedness to the world is an alien concept.  I don't
agree that people still have an innate ability to do this.
This faculty has been so degraded that we don't even know
what we've lost any longer.

Alexander has come up with a methodology that provides a
crude method that's sort of like trying to teach deaf people
to create not just music but /beautiful/ music that they can
not understand or experience.

We need to teach people how to be connected to the world and
give them the cognitive tools to see and appreciate beauty,
then Alexander's approach will follow naturally.

This goes to the core of the problem of quality and
craftsmanship.  And in both cases I don't think we make any
progress until we can at the cultural layer, to reinvent
both quality and craftsmanship.  This is a
multi-generational undertaking and my gut feeling is that we
first need to figure out how to stop crushing children's
natural ability to see and understand beauty.  And I have a
hunch that this can't be done unless we also stop crushing
things like curiosity, or training people to think that
uniformity is the synonymous with quality -- that's an
industrial revolution thing.  

And post-industrial revolution civilization is just getting
worse.  We now have a significant percentage of a generation
who don't experience anything directly -- they are too busy
pointing a camera at things instead of experiencing it and
contemplating on what they are seeing.  Instead they
experience things as a side effect of their peer group in
social media.  That's bad enough, but we then are going
further and feel the need to include ourselves in most and
sometimes nearly all of those photos.  Selfies put ourselves
at the center of everything we experience.  We don't watch a
beautiful sunset, we take a picture of ourselves in front of
a beautiful sunset and by the time you've sent the picture
to social media the sun is down.  We need to understand that
we are part of the world, at the center of that world and
this is something that is being lost.  There are any number
of people who take great umbridge to this argument and say
that taking pictures is how they experience things.  That
doesn't hold up, the act of recording requires that most of
your attention is spent in the mechanics of making that
recording.  Saying that you can multitask and enjoy the sun
set as fully through a view finder as you fiddle with the
settings and frame and take the shot is not the same as
quietly sitting and watching a sun set.  Adding insult to
injury by putting yourself into that shot is pure
narcissism.  It is not a bad thing to take pictures of a
sunset, but this should be the exception rather than the
rule.  If you haven't spent many many sunsets watching them
and trying to understand what you are seeing and how that
relates to you and your place in the world then you don't
have the experience to know how to capture all of that in a
photograph.  This is the difference between art and whatever
it is people are doing with selfie sticks.

When we produce millions of exact copies of things be they
tea pots or copies of a sound recording we have stripped
things of their uniqueness and life imperfections are the
only way we can know when we see something that is perfect.
When everything is the same, there is no good or bad,
nothing is better than anything else which strips things of
their beauty, if nothing is ugly, then nothing is beautiful.
Beauty only exists as part of a spectrum with things that
are ugly at the opposite end.

We have to discard a lot of industrial revolution baggage to
do this and we will never see it, nor out children.  But
perhaps our grandchildren and great grandchilren, if we work
hard enough at it and make it a priority.

But this still doesn't answer my original question of how to
use patterns -- I don't see them as a crutch, as see them as
an important means of embodying an aspect of knowledge that
until now hasn't been recorded in any meaningful way.

Patterns record fuzzy things that we use terms like
traditional, or custom or vernacular that boils down to
being collective, often informal knowledge -- it works
because it has evolved over many generations and tempered
over time through constant tweaking and experimentation.
It's often difficult, and even impossible to boil such
knowledge down into exact specifications or designs.
Patterns are able to capture that and as such are very
powerful, though more than a little nebulous.  Patterns are
not machine understandable because they are all within a
continuum of possible manifestations.  This is why it's so
difficult to use traditional building and financing methods
to do such construction because it is a process that doesn't
lead to a specific pre-defined conclusion.  The process
determines the finished product, not the desgin.  This is
what happened to the Web -- the original Web wasn't supposed
to look the same everywhere -- web pages were supposed to be
rendered differently according to the different types of
software and hardware that was being used.  Today's web
which is designed to work on multiple display sizes is not
what I'm talking about.  Web pages were not meant to be
'designed' they were meant to be interpreted.  Modern man
can't handle that kind of plasticity and uncertainty -- we
are too indoctrinated with the industrial concept that
everything has to be exactly the same to be of high
quality.  There can be no ambiguity, no influence from
outside -- everything must be static cookie cutter identical
copies where the designer has the power of controlling
everything for good or bad.

This also means that we've lost the ability to adapt the
world around us to the specific circumstances and needs that
they are put to use.  Emacs is completely the opposite from
this -- no two .emacs are the same, and after a while, the
customizations that go into your config may well make it
unusable for other people to be able to understand or use.
To someone like Steve Jobs this is nothing short of
horrifying.  He wants to cramp /his/ vision and /his/ design
down your throat and he doesn't give a shit if this works or
not.  Apple products require you to conform in ways that
Microsoft was never clever enough to pull off.  But
microsoft achieved the same thing from a completely
different direction.  Microsoft products are designed for
large corporate environments that require general purpose
tools that are identical.  Microsoft is the electronic
embodiment of industrial information processing.  The tools
don't need to be great, they only need to be good enough,
because the workers and the work done doesn't need to be
great it only needs to be good enough.  Excellence,
ingenuity and imagination doesn't scale and must be
eradicated where ever it is encountered.  That is why
Microsoft was so successful, Gates understood that in his
bones.  Apple then became a sort of fake alternative to
Microsoft.  Apple was supposed to be about individuality and
unconformity and thinking outside of the box, but that was
all window dressing.  It had the effect of catching all of
the people who did have a spark of imagination and crushed
it by reducing it to a lifestyle choice.  So you had the
choice of Microsoft, or Apple's way or the highway.  In the
end both Microsoft and Apple were doing the same thing.

Emacs out-of-the-box isn't emacs.  Emacs only become emacs
after it has rewired your brain and you have rewired emacs.

That is the potential that the web originally had and was
lost in the browser wars.
#+end_comment

Patterns are repeating themes in nature, design and human
behavior that when combined with other patterns strengthen
each other and create things that are larger than the sum of
their parts.

APL was divided into three parts, Towns, Buildings and
Construction.  But APL is a pattern language for
architecture and buildings.  For this to work it had to
define many patterns that more properly belonged to urban
planning, culture and governance though these were patterns
that supported the construction of beautiful buildings.

Our pattern language has a far broader scope; building an
antifragile civilization for mankind.  It is such a broad,
and ambitious scope that it borders on hubris.  After all we
barely agree on what civilization is, let alone how to build
one from first principles.  Though the undertaking is
assuredly fated to fall far short of it's goals, it is
important to instigate a tradition of people and
institutions to try.  Over many generations such
investigations could well become the foundation for and
roadmap for our survival and hopefully, prosperity.

But if Mankind is to become antifragile, we must become as
distributed as possible.  That means, among other things we
need to be thinking beyond our own planet and how we can
leverage the mind boggling wealth that we have in our solar
system.  We have outgrown the carrying capacity of our
fragile pale blue dot and we need to start tapping
extraterrestrial resources or perish, certainly as a
civilization and eventually as a species.

The pattern language is organized around Steward Brand's
six-layer /Pace Layer/ model which is based on the
observation that different things change at different
speeds.  The model began as an observation that buildings
can be thought of as being made of multiple layers with each
changing over time at different speeds.

Brand's model was made up of six parts:

  - 6 Fashion
  - 5 Commerce
  - 4 Infrastructure
  - 3 Governance
  - 2 Culture
  - 1 Nature 


Our language will be called /A Pace-Layer Pattern Language/
(APPL), which will be made up of 9 parts that combine
Brand's and Saffo's Pace Layer models into one.

This table shows slow to fast as pace layers, but it should
be remembered that layers 1-4 are nested within each other
and the Anthros layers are a subgroup of bios.

  |----------+------------------+-------------|
  |          | 9 Fashion        | agora       |
  |          | 8 Commerce       | stoa        |
  | Anthros* | 7 Infrastructure | polis       |
  |          | 6 Governance     | pynx & bema |
  |          | 5 Culture        | muthos      |
  |----------+------------------+-------------|
  |          | 4 Anthros*       |             |
  |          | 3 Bios           |             |
  | Natura   | 2 Lithos         |             |
  |          | 1 Helios         |             |
  |          | 0 Cosmos         |             |
  |----------+------------------+-------------|


This is only one POV, we need to present this as how these
different things form a hierarchy so that it's understood
that anthros is a subset of bios and not seperate.

The 9th group called /0 Meta/ contains patterns that apply to
all layers which will be given the number 0 below /1 cosmos/
which is number 1.

Each layer has a different =Rate of Change= (ROC) with
/Cosmos/ at the bottom being the slowest and /Fashion/ at
the top in a constant state of churn, changing at a staccato
rapid-fire beat.


*** Pattern Keys

Patterns will have keys (unique ids) in the form of:

   APPL[layer#]:[Pattern#]

So the first pattern in the Meta group would have the key
APPL0:0001.

*** Steward Brand and Paul Saffo: Pace Layers Thinking -- notes

 - [[http://longnow.org/seminars/02015/jan/27/pace-layers-thinking/][Pace Layers Thinking]] | Stewart Brand & Paul Saffo | SALT
 - [[Painted.Woman.2017][Pace Layering: How Complex Systems Learn and Keep Learning]]

  slippage between layers, negative feedback looks

    - turbulence
    - viscosity

  young are concerned with fast layers -- especially fashion


  | Fast layers              | Slow layers          |
  |--------------------------+----------------------|
  | learns                   | remembers            |
  | proposes                 | disposes             |
  | absorbs shocks           | integrates shocks    |
  | discontinious            | continious           |
  | innovation/revolution    | constrainy/constancy |
  | *gets all the attention* | *has all the power*  |
 
I find it interesting that Alexander seems to be aware of
all of this, but never takes it on directly.  He has always
been focused on creating new buildings where you can start
with a clean slate and do things the right way.  But most of
the time that's not what you can do.  He always talks of
gradually moving from what is existing to how you want
things to be but doesn't address any of that in APL as much
as he could have.  We build on top of what came before.
There is no clean slate -- thinking that you can is the
architect's hubris.

The moments when you can do tabla rosa are few and far
between.  The great fire of london, a tsunami in Japan or SE
Asia wipe everything out, even cadastral maps (because the
property holders are gone as well as the buildings).  We
should fear such opportunities more than wish for them,
because unless you start small and grow bottom up in an
organic manner we will /always/ fuck it up.

But it's even worse than that because when say Myanmar or
Dubai backed by a mountain of cash have tried to clean slate
things they try to jump over all of the intermediate steps
that leads to functional, beautiful human settlements.

Alexander has essentially made the case to abolish the whole
class of architects and architecture as we know it today and
go back to the older concept of the master builder.

The big name architects are too focused on originality and
have largely forgotten craft and that structures are a part
of the environment (context) that they are built in and are
built for mostly pedestrian functions.  They put the focus
of vision on originality rather than achieving the purpose
the building is meant to fill.  The small name architects
are often just as bad or worse because they are just
knocking out structures at a distence according to
specifications provided by a customer that are based on
lowest common demoninator metrics and contruction financing
and practices that are estranged from the purpose that the
building is meant to fulfill.


**** Paul Saffo's Pace Layers

 - Anthros
 - Bios
 - Lithos
 - Cosmos

So if we combine this with Brand's model we get:

A General Theory Of Bureaucracy (1961)
Elliott Jaques

https://en.wikipedia.org/wiki/Elliott_Jaques

/Time span of discretion/ that a manager can be ranked 

seven layers on timespan of 

time from formulate a plan to it's execute

the lower the number the shorter the timespan



**** Japanese mayor (story from audience member)

An classic example of long term application of /timespan of
discretion/.

http://www.dailymail.co.uk/news/article-1386978/The-Japanese-mayor-laughed-building-huge-sea-wall--village-left-untouched-tsunami.html
http://blog.nihongo-pro.com/2011/04/mayors-vision-saves-japanese-village.html

Was mayor for over 40 years and in that time went against and fought
to build a tsunami barrier for this town.  He died before it was ever
used but the barrier saved the town.

**** Rice on Chessboard

People don't grok exponential growth

pace layers turn Hockey Sticks into S-Curves

**** The Apsara of Context, Scale, Time and Change

Though not discussed in the talk, the other two things that
we can't grok are /size/ and /time/ at scales that are
outside of human empirical limits.

Taken together /rate-of-change/ (ROC), /level-detail/ (LOC)
and /point-of-view/ (POV) are the three things that define
the context of almost anything.  They are also are our
biggest blindspots when any of the three fall outside of
human scales and comprehension.

Is blindspot the right term?  Failure of imagination?
Cognitive limitation?  hmmm.

Relativity is based on the concept that what is real is
dependent on the context of the observer -- this is just
another formulation of that concept from a different POV.

One of the Meta goals of our project is to find ways to help
us as individuals and collectively to make these things
comprehensible so that we act on them when it is necessary.

Climate Change is a problem because we can not comprehend
the problem that we have created for ourselves.  The Long
Now Foundation focuses on long term thinking and
perspectives but scale and change are equally important.  I
know that they think that's baked into their mission but its
worth spelling out.

*** Nature

We divide nature into the /1 cosmos/, /2 lithos/ (as in the
lithosphere) and /3 bios/ as in the biosphere.

Cosmos includes everything in the universe down to planetary
or planetoid scales.

Lithos (meaning rock) is any planet or planetoid where
mankind might end up hanging his hat or exploiting in some
manner.  Lithos includes artificial planetoids that are
meant to be habitats including everything from the ISS to
large scale habitats housing thousands or even millions of
people.

Bios is any biosphere that supports life that is contained
in a /lithos/.

Putting it all together:

The Universe is the Cosmos.  But more practically, the
pattern language will be concerned with our Solar System as
a /system/ which includes the Sun, planets, planetoids
orbiting it and the mechanics of moving around in it and
dealing with things like solar and cosmic radiation, light,
heat and electromagnetism and how all of this pertains to
building and maintaining an life and specifically an
antifragile distributed civilization.

The lithos is any physical inanimate natural or manmade body
that is exploited or used to create a habitat irrespective
of whether the body is habitable.

On earth the core, mantel and crust would be the lithosphere
and the biosphere is the thin envelop made up of an
atmosphere and a hydrosphere where life can exist.

The structure and shell of the ISS would be the lithos and
the atmosphere within and the machinery for maintaining
pressure, temperature and scrubbing C0^2 would be its
biosphere.

/Anthros/ layers are anything within a biosphere and follows
Steward Brand's five layers, culture, governance,
infrastructure, commerce and fashion.  There is always a
tradeoff when you define models like this because you are
indicating organization for the purpose of understanding
something that doesn't exist.  The layers are a useful way
of understanding how different aspects of civilization that
change at different speeds interact with each other.



----

We are a part of both realms and we impact and are impacted
by both realms.  We are part of nature, there is no them and
us.  This is very difficult concept for modern man to
comprehend because we have convinced ourselves that we are
exceptional and outside of nature.  Gravity applies to us
the same way as every other thing in the universe.  Jump out
of a airplane without something to slow us down like a
parachute and we will splat just like a watermelon.

A city is part of nature as much as the most isolated meadow
in on the Tibetan Plateau.  Both belong to and depend on the
same pressurized atmosphere, and protection from solar and
cosmic radiation to support life.  You can say that the
meadow is nature uneffected by man, but that isn't exactly
true either.  Mankind has been shaping the world for tens of
thousands of years using fire, long before the first
civlizations emerged in the alluvial wetlands of Mesopotamia
that fundementally changed the biodiversity of broad swaths
of the planet, especially megafuana.  Cliff paintings
overlooking the Mekong River portray a number of different
types of megafauna that are now long extinct.  The most
likely explanation for the extinction of species like pygmy
rhinos and the giant sloth is man.  Other megafauna, which
could reproduce quickly and were more fleet of foot than the
sloth such as antelope, deer, caribou and elk flourished as
a reliable food source managed by using fire to shape
habitats which encouraged those species.  It can be argued
that mankind terraformed the planet with fire.

/Nature/ patterns are concerned with Mankind's interaction
with nature, both physical and living.

The degree of that interaction can be divided into wild and
cultivated.  We used to be quite good at managing the wild,
but got lost when we turned to pure cultivation and
eventually began to see the wild as something in opposition
to and an enemy of the cultivated.  In modern times, those
who call themselves environmentalists and conservationists
are no less guilty of this false dichotomy.  We need to stop
thinking in terms of us vs them, nature knows no such
divisions.  We can not become one with nature, because we
were never apart from nature in the first place.

When talking about the realm of life we will use the concept
of /habitats/ that contain /biospheres/ that are sometimes
divided into /biomes/ that contain life.  At the time that
this is being written there are only two biospheres that we
are aware of, the planetary biosphere that envelops Earth
and a tiny biosphere in low earth orbit called the ISS
(International Space Station).  Eventually there will be
more biospheres, a handful at planetary scales and many
smaller artificial ones.  The nature of how mankind shapes
and manages those biospheres is the subject of this pattern
pace-layer.

Change at planetary scales both physical and biological take
place in geological time scales.  The tectonic plates of the
Earth inch together and apart so slowly even the Ents would
consider them to be slow.  The evolution of life largely
takes place in time scales that dwarf any one species.
Occasionally something like an asteroid impact, the eruption
of a supervolcano or other event triggers massive change,
but the impact of that event often takes far longer than we
might think.  The dinosaurs didn't all die off within days
or months or even centuries after the asteroid hit the
Yuccatan.  A true planet killing event has yet to happen to
Earth.  We know this because we are here to talk about it.
But there were a couple of times that things were close.

** Primer

*** Origin Story
  - Filters

  - 1. The Big Bang
  - 2. Stars Light Up
  - 3. New Chemical Elements
  - 4. Earth and the Solar System

  - Life
  - 5. Life on Earth
  - 6. Collective Learning
  - 7. Agricuture
  - 8. The Modern Revolution




The origin story is the first part of the primer,[fn:1]
followed by the theses (declarations), then education (triv,
quad, laurea etc), then the shops and guilds, then the
value-chain, then bioregions, and finally production.

Man started out just as any other animal on the savannah,
but development of tools, then speech and finally writing
resulted in an estrangement that in our minds that estranged
us from the world and who we were that seemed to have
started with Aristotle and all of those god damned lists and
categories.  It wasn't until the Copernican Revolution which
showed that there was nothing special about where we were in
the universe that we began the slow process of decentering.
The Darwinian Revolution was the second decentering which
taught us that we are just one more creature in a vast
fabric of life and that all of the rules apply to all of us,
we are no exception. I believe that we are at the brink of a
third which will teach us that our minds and our
intelligence is nothing special either.  We've fallen a long
way and we are still falling.  And as anyone who has jumped
out of an airplane could tell you, the fall is nothing to be
afraid of, it's when the ground breaks your fall that you
have to worry about. Intelligence is all around us, we are
simply too caught up in ourselves to notice.  I hope that
when Man does hit bottom that it will leave us humbled and
capable of living within the limits of the ecosystems that
we are part of.  That doesn't mean we will stop hacking them
and shaping them for our own purposes, but it will have to
be with an understanding that we either find a way of living
within the carrying capacity of where we live, or we die.
You can not increase carrying capacity by using up or
abusing resources faster than they can be replaced.  If you
can hack nature to increase sustainible carrying capacity
great -- but that is not what Man is doing now.

  - social contract   
  - origin
  - theses
  - education
  - shops & guilds
  - value-chain
  - 
  - bioregions/ecosystems
  - production & surpluses

    - slavery/mass labour -> machinery -> cognitive machines

*** Slavery and Civilization

All employment at scale has at its roots, human slavery. I
realize that at first this sounds like an inflammatory
statement, but it's not.  Once you grow a group beyond the
scale of a band or small tribe, you slavery begins to
emerge.  This is universal, it cuts across all human
societies and religions and ideologies (tho religion is a
subset of ideology).

---

Two sides to slavery; surplus mind and muscle, you need both
to create a surplus that leads to surpluses that free a
proportion of the population to pursue intellectual pursuits
that result in advancements in technology, sciences and the
arts.

This follows toffler: 

    force -> wealth -> knowledge

Human labour at scale mirrors this perfectly: 

    slave/convict -> indenture/conscript -> employee

At each level labour becomes more abstract, flexible and
more powerful, but at base it's jelly beans, they might all
have different pretty colors but inside it's all made up of
the same sugary crap.

My argument here is that labour does not and can not scale
without it becoming a manifestation of slavery.


  - domesticated animals had the muscle but not the mind so
    you still needed slaves who were compelled through
    physical force to direct the beasts.  people submited to
    slavery because of fear of physical force.

  - machines had the muscle but not the mind so you needed
    captive labour in the form of factory workers who were
    economically compelled to work to direct the machines.
    This system is more flexible and scalable than slavery.
    people submited to industrial factory jobs because of
    fear of poverty.  after poverty was largely taken out of
    the equation other fears were leverages -- leveraing
    fear is how to keep slaves in line.  keep them dumb,
    control what information they have access to, keep them
    scared and then give them cheap consumer goods so that
    they produce and consume as they are told.

  - when you use machine cognition to direct the machines
    you get robots which does not require compelled human
    labor.  Ths system is more flexible and scalable than
    mass indusitural human labor.

So when you hear claims that it was machines that were responsible for
ending slavery they are both right and wrong.  The nature of slavery
simply changed from a model based on physical force, to a model based
on symbolic wealth.  The work force might have the illusion of being
free but for all practical purposes it was still slavery.  This then
frames the other claim that it was the development of moral and
ethical motivations that ended slavery.  Those moral arguements were
used to change the nature of slavery, not to end it.  And in so doing
was able to scale slavery to proportions that couldn't have been
dreamed of in the wildest dreams of the most barbaric banna
plantation in central America or Cotton farm in the old south.

However, even before 1800 it's difficult to know how many slaves there
were because not all slaves were called slaves.  Serf's, indentured
labor etc. are all forms of the same shade.  This is also true in the
modern industrial era where incarceration in many places is little
more than another form of legal slavery.  Conscription has also taken
forms that are little different from slavery as well.
*** Constants

Constants are bedrock variables that define things that can
not be changed like the speed of light or dunbar's number.
They supercede what we want or what we would like and
provide empirical design limits.  No theses can =violate= or
contradict a =constant=.

 - [[./constant-speed-of-light.org][Speed of Light]]
 - [[./constant-dunbar.org][Dunbar's Number]]
 - [[./constant-millers-law.org][Miller's Law]] (7 plus or minus 2)
 - [[./constant-divided-concurrent-goals.org][Divided Concurrent Goals]]
 - [[./constant--shared_intentionality.org][Shared Intentionality]]

*** Theses

Scopic Theses are declarations that provide a foundation for
a =civil ruleset= for people to live and cooperate with each
other.  Our theses is a social fiction that defines how we
/want/ to live and behave with each other.

 - [[./theses-preamble.org][Preamble]]
 - [[./theses-notes.org][Theses Notes]]






** Hoard

After the primer is the Hoard -- the library of descriptive
and prescriptive knowledge.  This will be a map but a very
detailed map whose territory is the archive.

This will be the knowledge that is assembled to build a
civilization from first principles -- this will include
designs, standards, recipes, facts, proceedures, best
practices.

The idea is that you will pick out your patterns and create
your pattern language which is at the core of a master
generative plan -- then you use the knowledge from the Hoard
to build it.

A pattern might be for outdoor windows, and what they must
incorporate to work.  The Hoard will provide the information
for obtaining or creating the building material, wooden,
plastic or metal frame, plate glass, glazing, screws,
caulking and all of the tools needed to build it and then
more general proscriptive steps that make up the art of
glass making, and window framing.

The Archive will be all of the primary documents that the
Hoard is built on.

----

But don't forget that the Hoard has two parts -- map and
territory, so the graph database that weaves it together is
just as important as the items in it.



** Archive

After that is the Archive of all recorded memory and
experience.

Arcs are designed to collect, organize and filter material
over very long time frames.  At set intervals, material in
collections is evaluated and filtered.  This could be
something like every 1, 10, 100 and 1,000 years.

Arcs can be either public or dark -- dark arcs are not
directly accessible and will only respond to requests for
things that have been lost.  Dark arcs will also monitor
public arcs to see what is missing and make that material
available to be found and added.

Dark arcs will be part of the slow internet -- running at
negative bandwidth speeds -- -1G, -2G, -3G etc speeds, as
slow as -5G.

After a massive loss of recorded knowledge after a disaster,
war or other temporary sanity, dark arcs will determine when
people are ready to have that lost knowledge restored.


** Window & Roadmap

A Roadmap for Mankind over the next 50 years to move from
being a centralized global civilization, with crtical
knowledge, infrastructure and wealth pooled in a handful of
people, places, and organizations, to a distributed
multiplanetary civilization reflecting the needs of a
rapidly shrinking population on earth and an increasingly
hostile climate.




** Scenarios
*** The Plan of Arc Indradevi

A bioregion in n.e. cambodia.  Rather than my original
concept of doing the plan for the Arc itself like PSG, we do
a plan for an entire bioregion and ecosystem for of 2
million people all living and working as part of a global
distributed micro-value-chain.

The Arc will be just one part of the larger plan -- that
will include infrastructure, agriculture, production,
economic, education, governance and culture.

I suppose the plan would be a master plan, and we would
create three different 100 year scenarios of how that plan
might be realized depending on different climate change,
political, and economic scenarios globally and regionally.

My original idea was to do three scenario histories over a
100 year period.  The scenarios would show how generative
designs would create very different things given different
circumstances.

Without this it would be easy to think that this was a
traditional top-down static plan.  We need to show that
generative designs are natural -- for some reason they scare
people, but most of that is because generative plans are
things that happen in the moment, they are processes rather
than plans.  Plans are linear, with a beginning middle and
end -- processes can be linear -- but they can also be
open-ended and they certainly are not deterministic it's not
always clear where a process will lead.  In reality we don't
know where plans lead either -- but in the case of building
physical infrastructure the goal is usually to know what you
are building and ensure it get's built according to plan.
In the case of something like a suspension bridge this is a
good thing.  But not the vast majority of constructions.
The great european cathedrals were not built in the same way
as modern buildings they were generative processes that
took, in some cases, centuries to complete.  There's no
little irony that ESR's famous essay used the catherdral as
the symbol of top down planning, design and construction.

Adaptive processes are better in the long term, but static
processes are percieved to be better in the short term (even
though this is not true) and the modern system from the
ground up is designed to work that way.

This is not to say that generative is all chips and gravy.
Generative is as hard as distributed -- biological evolution
is a blind generative process and is mind blowingly
inefficient.  But when generative works, the payoff is all
of Life in all of its diversity, complexity and beauty.  We
are coded to work this way, even if that coding is working
very deep in the bios pace-layer.  And the thing is,
deterministic processes are almost always bad and if they
aren't, it's little more than chance.  Okay, I take that
back, deterministic processes work at individual human
timescales.  We can get up in the morning, eat breakfast and
go to work.  That's a deterministic process.  We make a plan
and follow it for day to day life.  We can do that and often
do it very well.  But we then try to apply the same approach
to processes in pace-layers that are beyond individuals, and
even beyond collective human pace-layers.  That's where is
all falls apart.

Business plans are a good example.  Business plans are
complete bullshit if they are for longer than a few months.
Five or ten year business plans are meaningless fantasy in
world whose ROC in fashion and commerce pace-layers is as
fast as it is today.  But we persist in thinking that they
are useful and waste enormous amounts of time writing them
and as soon as something changes, they are forgotten in a
drawer.



*** The Plan of Barsoom Dor

Basically the same thing as Indradevi, but how the same
thing might be achieved on Mars.

A man-made underground river (not a tunnel, but a river with
banks and air above) that runs from south towards the
equator that is fed by ice from antarctic to domes in warmer
climes.  The river feed domes that create atmosphere, and
hydrosphere that make up a distributed biosphere.

*** Dubai Martian City

I'd like to approach the Dubai Mars City project with the
proposal to do three scenarios for them as well -- one will
be our Barsoom Dor scenarios but in addition two others that
explore what a traditional top down design and construction
process might look like and how they would compare to our
generative approach.

This would be done by holding scenario conclaves where we
invite different traditional architects, engineers and
builders and work out the long term consequences of top down
approaches.

To keep participants honest, all scenarios will follow
examples from history of what has happened to planned urban
areas in the past.  We ask them first to come up with a
design and 20 year master plan in brief and then we see how
the plan will adapt over time to things that they didn't
plan for.

But how to do that?  I suppose we have two teams the design
teams, the governance teams and then the historical teams
who would through events at them which came from historical
examples.

One of the scenarios is that after 50 years, Mars is cut off
from Earth for the next 50 years.  This might mean being
physically cut from all contact, or or economically cut off
when funding dries up for support.

We will also throw at them things that will basically force
them to abandon a lot of their initial assumptions after the
settlement is essentially built.  Can they adapt, and in
order to adapt how will it impact their original designs?


** Footnotes

[fn:1] What about language?  Origins lays out our history which is
tells what our metaphysics and physics.  The nuts and bolts of laguage
will be in the Triv.  but I'm talking about something deeper, more
structural -- language both spoken, written and executable -- a
language of the long now that will change far slower than language at
the upper pace layers -- it will change, but over centuries and
milennia not years and decades.  It should be something that is stable
for long periods of time.  Different pace-layers will have different
versions of it, the fashion layer tries out new ideas which are
filtered and refined until they change the lowest layers.


** References

  - Kelly, K., The inevitable: understanding the 12
    technological forces that will shape our future
    (2016), : Viking.
    cite:kelly:2016inevitable
