#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Introduction Volume I
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Introduction Volume I
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-intro-vol-1.org
:Created:  2018-04-11T18:19@Prek Leap (11.642600N-104.919210W)
:ID:       bef42709-757a-4e2e-873c-41175c9c456a
:VER:      576717614.262601171
:GEO:      48P-491193-1287029-15
:BXID:     proj:DIM5-7235
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

The first volume lays out the broad foundation for the work,
what is civilization, how did it emerge, what forms has it
taken throughout history, what are the driving forces behind
it.  This lays the groundwork for understanding different
ways that civilization might work in a technologically
advanced post-scarcity future that we are starting to see
the beginnings of today which we will get into in detail in
Volume III.

Then what do we mean by first principles? In a word, it is
what Paul Graham called, when describing the design of the
programming laguage Arc,  "no onions in the varnish":

#+begin_quote
In /The Periodic Table/,[fn:1] Primo Levi tells a story that
happened when he was working in a varnish factory. He was a
chemist, and he was fascinated by the fact that the varnish
recipe included a raw onion. What could it be for? No one
knew; it was just part of the recipe. So he investigated,
and eventually discovered that they had started throwing the
onion in years ago to test the temperature of the varnish:
if it was hot enough, the onion would fry.

We're going to try not to include any onions in Arc.

— [[http://www.paulgraham.com/arcll1.html][Arc at 3 Weeks]] | Paul Graham, 2001
#+end_quote


** Table of Contents
 - [[./ww-epigraph.org][Epigraph]]
 - [[./ww-intro.org][Introduction]]
 - 00. [[../wip/wip-plan.org][Plan of the Work]] - prolegomenon
 - 00. [[../wip/wip-ww-synopsis.org][Synopsis]]
 - 00. Contents Volume I
 - 00. [[./ww-intro-vol-1.org][Introduction]] Volume I
 - 01. [[./ww-civilization.org][Civilis]]
 - 02. [[./ww-ab-initio.org][Ab initio]] 
 - 03. [[./ww-order.org][Nature of Order]]
 - 04. [[./ww-boundries.org][Boundries]]
 - 05. [[./ww-estrangement.org][Estrangement]]
 - 06. [[./ww-principles.org][Principles]]


** References

  - Levi, P., The Periodic Table (1995), : Schocken.
    cite:levi:1995periodic-table

* Footnotes

[fn:1] "I started to tell the story of the onion in the
boiled linseed oil. This, in fact, was a dining room for a
company of varnish manufacturers, and it is well known that
boiled linseed oil has for many centuries constituted the
fundamental raw material of our art. It is an ancient art
and therefore noble: its most remote testimony is in Genesis
6:14, where it is told how, in conformity with a precise
specification of the Almighty, Noah coated (probably with a
brush) the Ark’s interior and exterior with melted
pitch. But it is also a subtly fraudulent art, like that
which aims at concealing the substratum by conferring on it
the color and appearance of what it is not: from this point
of view it is related to cosmetics and adornment, which are
equally ambiguous and almost equally ancient arts (Isaiah
3:16). Given therefore its pluri-millenial origins, it is
not so strange that the trade of manufacturing varnishes
retains in its crannies (despite the innumerable
solicitations it modernly receives from kindred techniques)
rudiments of customs and procedures abandoned for a long
time now.  So, returning to boiled linseed oil, I told my
companions at table that in a prescription book published
about 1942 I had found the advice to introduce into the oil,
toward the end of the boiling, two slices of onion, without
any comment on the purpose of this curious additive. I had
spoken about it in 1949 with Signor Giacomasso Olindo, my
predecessor and teacher, who was then more than seventy and
had been making varnishes for fifty years, and he, smiling
benevolently behind his thick white mustache, had explained
to me that in actual fact, when he was young and boiled the
oil personally, thermometers had not yet come into use: one
judged the temperature of the batch by observing the smoke,
or spitting into it, or, more efficiently, immersing a slice
of onion in the oil on the point of a skewer; when the onion
began to fry, the boiling was finished.  Evidently, with the
passing of the years, what had been a crude measuring
operation had lost its significance and was transformed into
a mysterious and magical practice.

— Levi, P., The Periodic Table (1995), : Schocken.
  cite:levi:1995periodic-table

