#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Introduction Volume II
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Introduction Volume II Frameworks
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-intro-vol-2.org
:Created:  2018-04-11T18:17@Prek Leap (11.642600N-104.919210W)
:ID:       c09d0ee2-7ca0-41ac-a338-8d2a8bc4254b
:VER:      576717511.853335291
:GEO:      48P-491193-1287029-15
:BXID:     proj:APP5-4181
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

There are few absolutes.  And even when there are, even
those are subject to any number of ways of looking and
understanding them depending on when, where and how they are
observed or measured.

In too many cases, we form opinions, make judgements or jump
to conclusions on the basis of a specific context in which
we observe something.  It's hard enough to get through the
day and manage to make measured, rational choices in the
little time we have from a single context.  There just isn't
time to take in more than one or two different
perspectives.  But for things that stick around long enough
to be observed repeatedly over time, the accumulation of
experience of observing from different perspectives gives us
an increasingly complex and detailed understanding of the
world around us.  The familiar is something that is built up
over time, the unfamiliar is too new to yet be trusted or
fully understood.

We need to build up a collection of tools for understanding
how the world works and is organized as a means of
understanding, making decisions and building a civilization.

This Volume is all about building up a cognitive toolbox of
techniques that can be used to build a /familiar/
civilization that can be looked at from every possible angle
in contexts that are natural and understandable.  And then
once it is built continue to use our full arsenal of tools
to monitor, measure and mange it properly.

We start with four concepts that are in many respects the
most important for our entire undertaking, it's as simple as
the R.E.M. song, /Stand/:

#+begin_verse
Your feet are going to be on the ground
Your head is there to move you around
If wishes were trees, the trees would be falling
Listen to reason, season is calling

Stand in the place where you live
Now face north
Think about direction
Wonder why you haven't before

Now stand in the place where you work
Now face west
Think about the place where you live
Wonder why you haven't before

If wishes were trees, the trees would be falling
Listen to reason, reason is calling
Your feet are going to be on the ground
Your head is there to move you around

— Stand | Green, R.E.M (1988)
#+end_verse

We start from what we can observe from where we are
standing, this is perspective, or your /Point of View/
(POV).  Work out what direction you are looking in, and how
far or close something is relative to where you are
standing.  We call this Level of Detail (LOD).  Now watch
for things changing.  Get a feel for how fast or slow things
are changing relative to the steady beat of your heart where
you are standing.  Use a metronome, stopwatch or even a
calendar if it will help you along.  This is the /Rate of
Change/ (ROC).  Now comes the one that has become difficult
for some people, but is how things really are.  Understand
that everything around you, near and far, fast and slow are
in a constant complex dance of change.  The past doesn't
recede behind you and the future doesn't stretch off before
you.  Everything is right where you are, where everything is
in the process of becoming something else.  The past is not
gone, it's still right here in the present, but is changed
as entropy wears things down, cools things off and scatters
everything to the wind.  This is the Process of Change
(POC).

We can understand the world using these three different
Points of Views, as LOD -- how close or far something is.
Or as ROC -- how fast or slow things change and how fast or
slow that change propagates towards or away from you.  And
finally how all of these things are all happening at the
same time, near and far, hot and cold, slow and fast as a
single relentless irreversible process.  You can't unstir
milk poured into a cup of coffee and you can never stand in
the same river twice.

Save ourselves, this is how pretty much all creatures on our
plant see and experience the world.  We are not wrong and
they are also right.  But we are alone in having the
cognitive ability to understand goal oriented behavior.  We
can see that one thing leads to another which leads to
another which causes something to happen.  Your dog can't do
that.  Our close cousins the Chimpanzee's can't do that.
And that small thing has made possible everything Sapiens
(the sub species of Man that we belong to) possible.  But it
also leads to the illusion that time is a road with a
beginning, middle and end, with us at any given time in the
walking in the middle of the road towards a endlessly
receding horizon.

Understanding what we observe in the world as a different
Points of View with different combinations of LOD, ROC, and
LOC are the footings, or pilings sunk deep in the earth on
which we can build the walls of our foundations.

Nature is awash in dualities.  In 1801 Thomas Young
performed an experient that demonstrated that light has a
/wave-particle/ duality.  Light, as well as electrons and
even molecules can be observed as a wave, or it can be
observed as a series of particles, but you can only measure
it as one or the other.  Observing as a wave means you can't
observe it as a particle and vice versa.  Richard Feynman
called it "a phenomenon which is impossible […] to explain
in any classical way, and which has in it the heart of
quantum mechanics. In reality, it contains the only mystery
[of quantum mechanics]."[fn:1]

Dualities can be found almost everywhere you look, from the
Taoist 陰陽(ying-yang) ☯ duality[fn:2] of dualistic-monism
where condradictory opposites such as dark-bright,
good-evil, negative-positive, fire-water intertangle and can
exist as a single unity existing as both contradictory
things simutaneousely.  But these contradictions can also be
thought of as a spectrum with each opposite existing on each
extreme end from the other.  But as a spectrum, there is no
place where one becomes the other.  In formulating his
theory of evolution, Darwin disliked the concept of a
species.  After decades of careful observation of barnacles
and other living things he understood that there rather than
life being made up of different species, there were only a
near infinite number of variations from one individual to
the next.  Where does one draw the line and call one
variation one species, and another variation a different
one?




** Table of Contents
 - 07. [[./ww-points-of-view.org][Points of View]]
 - 08. [[./ww-dualities.org][Dualities]]
 - 09. [[./ww-generators.org][Generators]]
 - 10. [[./ww-scaffolds.org][Scaffolds]]
 - 11. [[./ww-specializations.org][Specializations]]
 - 12. [[./ww-patterns.org][Patterns]]
 - 13. [[./ww-standards.org][Standards]]
 - 14. [[./ww-legibility.org][Legibility]]

* Footnotes

[fn:2] https://www.fileformat.info/info/unicode/char/262f/index.htm

[fn:1]  Feynman, Richard P.; Robert B. Leighton; Matthew
Sands (1965). The Feynman Lectures on Physics,
Vol. 3. Addison-Wesley. pp. 1.1–1.8. ISBN 0201021188.
