#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Introduction Volume II
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Introduction Volume II Frameworks
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-intro-vol-2.org
:Created:  2018-04-11T18:17@Prek Leap (11.642600N-104.919210W)
:ID:       c09d0ee2-7ca0-41ac-a338-8d2a8bc4254b
:VER:      576717511.853335291
:GEO:      48P-491193-1287029-15
:BXID:     proj:APP5-4181
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

There are few absolutes.  And even when there are, even
those are subject to any number of ways of looking and
understanding them depending on when, where and how they are
observed or measured.

In too many cases, we form opinions, make judgements or jump
to conclusions on the basis of a specific context in which
we observe something.  It's hard enough to get through the
day and manage to make measured, rational choices in the
little time we have from a single context.  There just isn't
time to take in more than one or two different
perspectives.  But for things that stick around long enough
to be observed repeatedly over time, the accumulation of
experience of observing from different perspectives gives us
an increasingly complex and detailed understanding of the
world around us.  The familiar is something that is built up
over time, the unfamiliar is too new to yet be trusted or
fully understood.

We need to build up a collection of tools for understanding
how the world works and is organized as a means of
understanding, making decsions and building a civilization.

This Volume is all about building up a toolbox of such
techniques.  But it is also about 


** Table of Contents
 - 07. [[./ww-points-of-view.org][Points of View]]
 - 08. [[./ww-dualities.org][Dualities]]
 - 09. [[./ww-generators.org][Generators]]
 - 10. [[./ww-scaffolds.org][Scaffolds]]
 - 11. [[./ww-specializations.org][Specializations]]
 - 12. [[./ww-patterns.org][Patterns]]
 - 13. [[./ww-standards.org][Standards]]
 - 14. [[./ww-legibility.org][Legibility]]
