#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Warp & Woof Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Warp & Woof Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-intro.org
:Created:  2018-02-15T20:19@Prek Leap (11.642600N-104.919210W)
:ID:       f8ae9d01-083a-4598-84e7-249d560fca6c
:VER:      571972838.678903093
:GEO:      48P-491193-1287029-15
:BXID:     proj:OKM3-3142
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

No shit, a tl;dr for an introduction

** Table of Contents

  - a generative genome for Mankind
  - /ab initio/ on the shoulders of giants
  - of a history of extension & externalization
  - inevitable but unpredictible: anticipating post-scarcity 
  - the enlightenment rebooted
  - the fifty year window


** Introduction

At present. civilization is still at the whim of
evolutionary natural selection, random mutations happening,
with the successful ones replacing older ones.  We might
think we are in charge, but only as individuals, and even
then... not so much.

Mankind is at the brink of being able to take conscious
control over dna -- within a few decades we will be in
complete control of the design of all biological systems --
but that is mucking with individual genomes -- there are
larger meta structures of how these organisms organize and
interact to form large complex systems.  These systems exist
outside of human scale -- either too small or too large and
slow for us to easily see, let along understand, let along
change or control in any meaningful way.

Civilization is one such system -- and our clumsy attempts
at steering civilization or even understanding it is not
enough.  Collectively we are making a mess of things -- we
need to start understanding how civilization works, and how
we can shape and eventually manage it before we overrun the
petri-dish and trigger a massive die-off and collapse.

We need to work out a genome for human civilization and then
a CRISPR type mechanism for fixing things and test new ideas
in controlled ways.

This will never work if we take a top-down command and
control approach -- we need to understand how to inject
changes from the bottom up and when they've been tested and
work, then let them propagate.

We'll never be able to control civilization in the same way
that say you can control a car when driving down the road.
Complex systems make that impossible -- but I believe we can
learn to shape civilization slowly over time towards desired
outcomes -- as Kevin Kelly observed, you can tell what will
be inevitable but now the specific form that that
inevitibility will take. cite:kelly:2016inevitable

What this works sets out to do is to create methodologies
for understanding and modeling civilization and then work to
make desired outcomes inevitable -- once they become
inevitable they can be shaped to some extent -- thought
there is no way of knowing what form that will eventually
take.

I am, personally, a extremely pessimistic person, I have
never seen much hope for the human enterprise in any short
term and I still believe that we are all too capable of
derailing the progress man has made since 1800.

But that doesn't mean that I'm not going to try.  I've
always personally believed that the only way you can truly
fail is if you give up.  Steven Pinker's relentless optimism
about the reality of human progress and that it can continue
to not only improve but that improvement can continue to
accelerate has worn me down to the point where I admit that
he has a made a very good case.

But this will not happen unless all of us work together to
make sure that this happens.  The challenges ahead of
humanity just in this century alone almost beggers the
imagination.  It will take every ounce of imagination,
strength and as Pirsig said, gumption to make it happen.

A framework for understanding and changing the genome for
human civilization would be a very useful part of this
effort -- if successful it would make it possible to
coordinate our efforts better, identify what things are
being worked on and what areas aren't getting enough
attention.  It could help provide metrics for understanding
where we stand, where we are going and provide clues of how
to correct mistakes and move more clearly in the right
direction.

This is an audacious undertaking -- and something that I
have been working on full time for nearly two decades.  The
project has now come to the point where all the pieces are
coming together and the broad outline is visible.

Now that I've reached this stage, the project needs to make
the transition from being a solo effort to a building a team
to begin filling in the blanks, run experiments in the form
of projects that are designed to make practical improvements
in people's lives today, while learning to map out the
genome, how it works and how to improve it.  Some of this
work will be traditional R&D, some NGO projects.  But the
vast majority of the projects will be designed to be
not-for-profit.  In other words they will be designed to
make a profit, and be self-sustaining, but the larger goal
for each project will be to materially improve people's
lives first, and making a profit second.

The entire zero-sum mantra of "maximizing shareholder value"
is nothing short of obscene, and growing at all costs, when
growth is simply making a small group of people wealthy
should be considered to be the lowest of human activities
and should be held in the same contempt and a crime against
humanity.  The problem is that the system has so corrupted
us, that most people can't understand that the world was not
always this way, and it doesn't have to be in the future.
We can all strive to give everyone a high standard of
living, a life with purpose, without fear, or pain.

We can not tolerate zero-sum anything any longer.
Everything we do must be designed to be positive sum --
things that help me as much as they help you and everyone
else.

Any time someone tells you, that you have to suffer in order
to achieve an important goal is selling you a lie.  If
something doesn't make financial and economic sense, there
is something wrong, because it won't work, and the only
people who will subscribe to it are well-meaning chumps.
What DOES work is to teach people how to change their
behavior to do things in ways that improve their lives --
this is difficult, we aren't very good at changing -- and
this is why it won't happen overnight.  The older you are
the less capacity you have to change.

For this reason, it's good that we we still have time enough
to teach the next generation positive-sum habits.  It's very
likely that human lifespans will increase to hundreds of
years or even longer in the next few decades.  That is good
news, because it still gives most of the zero-sum generation
time to die before we start sticking around for significant
fractions of millenia.

And as these new generations grow older and older, they will
be old enough to have seen and understand much longer term
processes than we short-timers can today.  This will be
crucial to the long term survival of our species and
successful stewardship of our planet, and eventually the
rest of the solar system as humanities childshood ends and
take the first steps towards becoming a a mature
technological species.

The most terrible crimes against mankind since the 20th
century were the Year-Zero men

It is hoped that we are nearing a time when it will become
impossible for another of these monsters to take control.

The next step is to eradicate the Zero-Sum men and women
whose whole existence is to take from you to profit me.

Building a positive-sum genome for human civilization from
first principles would be a good first step.

Can we pull this off?  The pessimist in me is shouting in
one ear that it's a real long shot.  But then, the tiny
optimist's voice is whispering in my other ear is saying,
"hey, that loudmouth might be right, but what have you got
to loose.  It's worth a shot, isn't it?"


** of a history of extension & externalization

If pressed to sum up Mankind in a few sentences I would say
that Sapiens (the sub species of Man that we belong to)
history is no different from any other species on this
planet except for a single thing.

Sapien's large cerebral cortex makes it possible for us to
be goal driven, we can think abstractly out how to achieve
goals that might take many intermediate steps to achieve.
Not even any of our other other primate cousins can do this.
It enables us to think of time as linear, with a past, a
present and a future.  All other creatures live in a
perpetual present with no future, and a past that are made
up of memories of past events, but are not ordered into
causal chains.

This one ability to understand abstract concepts that
require multiple steps and imagine potential outcomes at the
end of all of those steps set all of human prehistory, and
with the invention of written languages, history in motion.

It made it possible for us to take an innate ability to be
able to ,modify and manipulate things in the environment
into tools.  But with with the addition of our ability to
envision multiple stage goals, these tools became
increasingly refined to the point where they became
extensions and eventually externalizations of our mind and
muscle.

Our entire history is the story of extending and
externalizing our mind to reshape the world around us.  The
first step was to externalize our mental abilities to be
able to communicate these abstract ideas with others.  This
gave us spoken language.  Taking this a step further we
learned to create symbol systems that could transcribe
concepts and human speech into clay, stone and parchment
that could be duplicated and sent to distant places both in
space and literally into the future without the person who
first recorded those ideas ever meeting or knowing who wouid
later encounter them.

The invention of moveable type and the printing press made
it possible to make countless and exact copies of written
messages which vastly reduced copying errors, which are the
bane of all communications, and potentially be read not only
by every living person alive when it was written, but every
living person who would ever live in the future.  It took
blind evolutionary processes billions of years to evolve
RNA/DNA to be able to do that.  Sapiens did it in the
evolutionary heartbeat of a humming bird on crystal meth.

Think about that for a second, Man can now do the same thing
that the blind chance mutation and natural selection process
of evolution as deterministic goals and we soon will be able
to do this in human time scales.

It's that last part which is particularly important, because
Sapiens don't scale, or at least we really suck at it.  All
of human progress has been a double edge sword that has
reaped astonishing achievements, while at the same time
making other things worse, and often much much worse.

When I talk about human scales I am /not/ talking strictly
about Rousseau's return the the original state of nature.
Though the idea of prosperous egalitarian bands of hunter
gatherers wandering the planet and living a pretty good
life, in comparison to that of the sedantary farmers and
urbanites who replaced runs counter to a growing body of
evidence that it is little more than a secular myth adapted
from the Christian meme of a man's fall from grace and being
driven from the garden is simply not supported by the
archeological evidence.  That said, group sizes that
correspond to bands (15-40) are human scales where groups
can function well.


All of Sapien's brainy achievements were only possible
because surpluses of food, and material goods needed for
survival could be produced that allowed a small portion of
the population to do things that were not directly related
to immediate survival.  Those surpluses let a small number
of people spend most of their time thinking.  That's the
good news.  The bad news is that in oder to do this,
hierarchical societies were needed that were based on
inequalities that took the surpluses created by some members
of the group and gave them to a few people who were in power
and a handful of others whose job it was to think.  That
system is called slavery.


** the enlightenment rebooted


#+begin_quote
More-over, this is classic motte and bailey. The motte is
"The US consitution was not unique" with the bailey being
"The US government was not unique". The later is simply and
totally false, a revival of the ancient idea of democracy
coupled with a strong rule of law and a respect for
individualism and the inalienable rights of man was a
completely radical thing at this point in history. The parts
were not first invented here, but they were first put
together into a coherent whole.

....

The Enlightenment (the movement) was based on
empericism[sic] and experimentation far more than pure
rationalism, even though enlightenment (the philosophical
concept) might have been formulated in different terms.

— /r/j9461: [[https://www.wsj.com/articles/the-dark-side-of-the-enlightenment-1523050206][Comment on The Dark Side of the Enlightenment]] | WSJ
  https://www.reddit.com/r/slatestarcodex/comments/8azimq/the_dark_side_of_the_enlightenment/dx3axmb/
#+end_quote




* Notes

** Notes on APL and TWB


W&W will be to APPL that /A Timeless Way of Building/ 
(TWB) cite:alexander:1979timeless is to APL. cite:alexander:1977pattern


TWB starts with this:

#+begin_quote
/The Timeless Way of Building/ is the first in a series of
books which describe an entirely new attitude to
architecture and planning.  The books are intended to
provide a complete working alternative to our present ideas
about architecture, building, and planning—an alternative
which will, we hope, gradually replace current ideas and
practices.

— A Timeless Way of Building
  cite:alexander:1979timeless
#+end_quote

#+begin_comment
Replace architecture and building with civilization and it's
not a bad description of W&W and APPL.

TWB was published two years after APL, which answers the
chicken and egg question, but it also makes sense.  TWB
couldn't have been written until after they had all but
completed APL.

TWB is divided into three Parts: The Quality, The Gate, and
The Way.

   - /Quality/ is QWAN.
   - /The Gate/ is the Patterns.
   - /The Way/ is how to get QWAN using the patterns.

The organization of the book also is design to work at
multiple LODs, like /The Plan of St. Gall/ with an outline
of the entire work, and then detailed TOCs at the beginning
of each volume.



TWB is almost mystical -- it does not come across as a
practical text on how to build according to his philosophy
and methodology.  It's almost a manifesto.  This was on
purpose, but as some reviews have noted, it could be one
reason that it hasn't been treated as seriously as it
should.  It's too outside of the mainstream, too easy to
dismiss and doesn't provide a bridge for architects and
builders to cross from their world into his.

The Oregon Experiment (which I still haven't seen) seems to
be where he shows a concrete example of how to plan, design,
and build.

So what about W&W?  We don't need to build the same bridges
that Alexandar should have, but at the same time we need to
bridge the gulf of how civilization is today, how the
present attempts at change are useless and all but
worthless.  So I suppose we do need bridges.  But is W&W to
be a bridge or manifesto?

I don't want to be too mystical, but I also don't want to be
too concrete which is why I'm so attracted to the Plan of St
Gall (PSG).  St Gall was never built -- so the designs based
on the plan are -- as the title says -- paradigmatic. PSG
delves deep providing historical, social, economic and
archaeological context and evidence.

So I suppose that W&W needs to blaze a path between the two
-- so that it's part Timeless Way and Part Plan of Arc Nong
Pao.

In fact that's about right -- first volume should be closer
to TWB and the following volumes should provide three Plans
-- two on earth and one on mars.

In that respect I suppose we can borrow many things from
Mollison's Designer's Manual -- which is, in many respects,
a path between TWB and PSG.

The whole pace-layer model will take a bit to lay out -- and
we will have to make a case for why we are on the wrong
path, and how we have no choice but to start from first
principles.
#+end_comment


** Window & Roadmap

A Roadmap for Mankind over the next 50 years to move from
being a centralized global civilization, with crtical
knowledge, infrastructure and wealth pooled in a handful of
people, places, and organizations, to a distributed
multiplanetary civilization reflecting the needs of a
rapidly shrinking population on earth and an increasingly
hostile climate.

** Scenarios
*** The Plan of Arc Indradevi

A bioregion in n.e. cambodia.  Rather than my original
concept of doing the plan for the Arc itself like PSG, we do
a plan for an entire bioregion and ecosystem for of 2
million people all living and working as part of a global
distributed micro-value-chain.

The Arc will be just one part of the larger plan -- that
will include infrastructure, agriculture, production,
economic, education, governance and culture.

I suppose the plan would be a master plan, and we would
create three different 100 year scenarios of how that plan
might be realized depending on different climate change,
political, and economic scenarios globally and regionally.

My original idea was to do three scenario histories over a
100 year period.  The scenarios would show how generative
designs would create very different things given different
circumstances.

Without this it would be easy to think that this was a
traditional top-down static plan.  We need to show that
generative designs are natural -- for some reason they scare
people, but most of that is because generative plans are
things that happen in the moment, they are processes rather
than plans.  Plans are linear, with a beginning middle and
end -- processes can be linear -- but they can also be
open-ended and they certainly are not deterministic it's not
always clear where a process will lead.  In reality we don't
know where plans lead either -- but in the case of building
physical infrastructure the goal is usually to know what you
are building and ensure it get's built according to plan.
In the case of something like a suspension bridge this is a
good thing.  But not the vast majority of constructions.
The great european cathedrals were not built in the same way
as modern buildings they were generative processes that
took, in some cases, centuries to complete.  There's no
little irony that ESR's famous essay used the catherdral as
the symbol of top down planning, design and construction.

Adaptive processes are better in the long term, but static
processes are percieved to be better in the short term (even
though this is not true) and the modern system from the
ground up is designed to work that way.

This is not to say that generative is all chips and gravy.
Generative is as hard as distributed -- biological evolution
is a blind generative process and is mind blowingly
inefficient.  But when generative works, the payoff is all
of Life in all of its diversity, complexity and beauty.  We
are coded to work this way, even if that coding is working
very deep in the bios pace-layer.  And the thing is,
deterministic processes are almost always bad and if they
aren't, it's little more than chance.  Okay, I take that
back, deterministic processes work at individual human
timescales.  We can get up in the morning, eat breakfast and
go to work.  That's a deterministic process.  We make a plan
and follow it for day to day life.  We can do that and often
do it very well.  But we then try to apply the same approach
to processes in pace-layers that are beyond individuals, and
even beyond collective human pace-layers.  That's where is
all falls apart.

Business plans are a good example.  Business plans are
complete bullshit if they are for longer than a few months.
Five or ten year business plans are meaningless fantasy in
world whose ROC in fashion and commerce pace-layers is as
fast as it is today.  But we persist in thinking that they
are useful and waste enormous amounts of time writing them
and as soon as something changes, they are forgotten in a
drawer.



*** The Plan of Barsoom Dor

Basically the same thing as Indradevi, but how the same
thing might be achieved on Mars.

A man-made underground river (not a tunnel, but a river with
banks and air above) that runs from south towards the
equator that is fed by ice from antarctic to domes in warmer
climes.  The river feed domes that create atmosphere, and
hydrosphere that make up a distributed biosphere.

*** Dubai Martian City

I'd like to approach the Dubai Mars City project with the
proposal to do three scenarios for them as well -- one will
be our Barsoom Dor scenarios but in addition two others that
explore what a traditional top down design and construction
process might look like and how they would compare to our
generative approach.

This would be done by holding scenario conclaves where we
invite different traditional architects, engineers and
builders and work out the long term consequences of top down
approaches.

To keep participants honest, all scenarios will follow
examples from history of what has happened to planned urban
areas in the past.  We ask them first to come up with a
design and 20 year master plan in brief and then we see how
the plan will adapt over time to things that they didn't
plan for.

But how to do that?  I suppose we have two teams the design
teams, the governance teams and then the historical teams
who would through events at them which came from historical
examples.

One of the scenarios is that after 50 years, Mars is cut off
from Earth for the next 50 years.  This might mean being
physically cut from all contact, or or economically cut off
when funding dries up for support.

We will also throw at them things that will basically force
them to abandon a lot of their initial assumptions after the
settlement is essentially built.  Can they adapt, and in
order to adapt how will it impact their original designs?




** References

  - Kelly, K., The inevitable: understanding the 12
    technological forces that will shape our future
    (2016), : Viking.
    cite:kelly:2016inevitable
