#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Machines
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Machines
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-machines.org
:Created:  2018-04-15T17:21@Prek Leap (11.642600N-104.919210W)
:ID:       c3c0543f-1102-404c-94cf-9bcf5251a1a5
:VER:      577059736.555374828
:GEO:      48P-491193-1287029-15
:BXID:     proj:MJK3-3131
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

There is a lot of overlap between a tool and machine.

A tool is generally an extension of the human body that is powered by
human muscle and typically directly comes into contact with the
material it is working with.

Machines are often complex externally powered mechanisms that provide
an infrastructure (as does the human body for a tool) that directs and
controls it.

We divide machines into two classes, machine-clockwork (or clockwork
machines) and machine-cognition (or cognitive machines).
Machine-clockwork require the direction or operation of a
self-directed agent.  Machine-cog is a machine which is semi-or-fully
self-directed, can recognize patterns, make decsions and learn.

*** Clockwork
**** Matter
Just as with tools, there are machines which are used to manipulate
and shape phyisical things.  There are machines for moving matter from
one place to another.
**** Energy
There are machines for generating power by capturing it in one form
and transfering it to another form.
**** Information
There are also machines that manipulate information.  These are
divided into, transmission, computation and memory.  We call these
types of information machines machine-clockwork because they require
direction from a cognitive agent.
*** Cognitive
A human is a combination clock-work and cognitive-machine.  A Cray
Supercomputer running machine learning applications is a cognitive
machine.  A self-contained robot is, like a human, both clockwork and
self-directed.




** Table of Contents

