#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Middle
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Middle
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-middle.org
:Created:  2018-04-11T10:02@Prek Leap (11.642600N-104.919210W)
:ID:       98e7fb2e-aad4-48dc-974b-2391215c0bd6
:VER:      576687835.335944509
:GEO:      48P-491193-1287029-15
:BXID:     proj:CVJ0-2265
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

In a nutshell, Middle is automated infrastructure, everything in the
middle of everything else.

In fact, my conception of it as it stands is to take over a large part
of what government, utilities, logistics, and the financial sector do
today.

If it works -- Middle is infastructure that makes fine-grained
distributed systems possible for both its and bits.

Middle is simply an infrastructure for creating just-in-time
single-use adhoc value chains it doesn't matter if it's an email, or a
container-ship, a process is created, broken into steps, agents
located to complete each step and and ensure that each step is done
correctly.

Each step only has to deal with the step they have contracted to do.

So if you have a pizza shop, all you have to do is make the pizzas.
You don't have to buy ingrediants, or do accounting, or take orders,
make deliveries -- just take the order, the system will ensure you
have the ingrediants (at the quality and quantity you need) tell the
system when the pizza will be ready, and as it's put in the box there
will be an agent to pick it up.

Even the cardboard in the box, will be part of it's own chain -- that
starts with making the corregated cardboard, die-cutting the
cardboard, printing the box, getting it to the pizza shop, and then
eventually collecting the empty box (along with all other cardboard)
and sending it to a company who recycles cardboard which is then sent
to cardboard companies as raw material for making more pizza boxes.


** Table of Contents

