#   -*- mode: org; fill-column: 60 -*-

#+TITLE: A Narrative Synopsis
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* A Narrative Synopsis
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-narrative-synopsis.org
:Created:  2018-04-08T10:22@Prek Leap (11.642600N-104.919210W)
:ID:       6f150e05-954c-4cac-a155-a5eebf85169b
:VER:      576429803.946697214
:GEO:      48P-491193-1287029-15
:BXID:     proj:PLY1-5537
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

The very term /civilization/ has so many different definitions,
connotations, misdirections, and assumptions that it's become
increasingly common for professionals in the sciences and academia to
shy away from the word altogether and use terms such as "complex
societies" that don't carry the semantic and ideological baggage and
the attending myriad of agendas that has been associated with the word
at any given time in history.

But rather than playing it safe, we feel that these other terms are
either too watered down or specific to encompass the diversity,
enormity and complexity that the concept of civilization includes.
Better that we embrace the entire messy history of the word and
provide a clear and concise narrative that lays out how /we/
understand it and how it will be used throughout /this/ work.

This chapter is /not/ intended to be an origin story. We will present
an origin story in all the gory detail that it deserves, but this
properly belongs in the /Primer/, and not here in /The Warp & Woof/.
So this chapter will sketch out our attempt at a broad narrative that
the work can hang it's hat on, and then detail the origin story in the
/Primer/ after the foundational concepts for building a civilization
have been laid out here in w&w and then identify the core patterns for
building a civilization from first principles in /A Pace-Layer Pattern
Language/.



