#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Polis
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Polis
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-polis.org
:Created:  2018-04-05T08:19@Prek Leap (11.642600N-104.919210W)
:ID:       6fb9e83c-4ab9-4857-afe3-5b0900daa8c2
:VER:      576163214.745875692
:GEO:      48P-491193-1287029-15
:BXID:     proj:YRY1-0838
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

The way that we organize information, matter and energy is
how we organize power.

We have already discussed how the concept of civilization is
rooted in the concept of cities, the polis, from where we
also get the word politics.

Now that we have a clear understanding of what a citizen is,
we can move from being a migratory or wandering
hunter-gatherer to a sedentary urbanite.  A band of
hunter-gatherers resolved conflicts by either moving or
fighting.  Urban Man makes moving difficult without
significant disruption and social and material loss.  So
urban Man needed to find ways of non-violently resolving
conflicts between neighbors -- from where we get words like
negotiation, which come from the word /negotium/, the
opposite of /otium/ which is a time of quiet contemplation.
Negotium encompused the social, the day to day business and
intercourse with her neighbors.

We need a model for the concept of polis as the atomic unit
of civilization as a physical and social fabric that makes
politics and commerce possible.

We will then discuss the relationship between the urban and
rural, as an economic relationship that creates tensions
because of the inequality between the two sides in terms of
wealth (urban areas have a higher concentration of wealth),
access to and quality of services, which we will see can be
understood as a problem of propagation of information,
wealth and logistics.

Finally we will look at mechanisms for how all of these
problems can be solved and how they have been solved in the
past.

In the end, as we have seen over and over, is that the
limiting factor for any of these solutions is scale.  Once
we move to scales larger than humans are designed for, we
see systemic problems emerge that can never be resolved
because the solutions simply don't scale.

** Table of Contents


HARD
  - rural, urban, cosmopolitan
  - ancient greek city-states
  - town-gown
    - polis and nones
  - monastic estates - familia intus & familia foris
    cite:horn:1979plan v1.p341
  - [[./ww-settlement-hierarchies.org][Settlement Hierarchies]]
  - Agora, Stoa & Pynx cite:sennett:2016pynx
  - Neighborhood and identity cite:hubka:1984big-house
WET
  - Social Structures
    - Nature
      - Mates
      - Hives, Colonies
      - Packs
      - Herds, Flocks, Schools 
    - Kinship
      - mated pair = couple - economic unit
      - pair + children = nuclear family
      - pair + children, and parents = extended family
      - band = base hunter-gather unit, human equiv of a pack
      - clan = band that are made up of members who are blood
        relations.
      - Barkota (polynesia)
    - Polities
      - chiefdom
      - tribe
      - nation
      - city-state
      - state
      - nation-state
    - Corporate Structures
      - Cooperatives -> partnerships, clubs, etc
      - Corporations -> virtual person
      - States       -> sovereign groups

  - Proposed

    The goal here is to create the most flexible structure possible.

    - Person     -> Individual person (person is member of
                    Mankind), corporation. Has rights, but
                    no liability, equity or group membership
    - Citizen    -> Person who has rights, obligations and
                    equity in group.
    - Ward       -> Persons lacking cognitive ability for self
                    determination.
    - Union      -> legal collective between 2 or more Persons
    - Domus      -> Household/Workshop (typically a
                    corporate person) no larger than 40 Persons.
    - Guild      -> Corporate person, who can not hold
                    property, take part in poltical
                    activities but may have powers such as 
                    judicial, or security or credidation.
    - Polis      -> (polis + nomes)
    - Federation -> group of polis and or guilds -- may be
                    permanent or for a project.  Do not have
                    same rights as a Polis (can not control 
                    territory) or other functions
                    that super powers hold today.

SOFT

   Basically this is what I'm calling MIDDLE, which makes up
   all of the automation that links all of the Hard and Wet
   parts of Polis together.

   To paraphrase Einstein, MIDDLE has to be as complicated as it
   needs to be but not more.

   MIDDLE is hardware (machines) and Software (cognitive and
   clockwork) that is meant to replace middlemen in the
   system, which reduces inefficiencies and opportunities
   for rent seeking, replaces slavery with sub-cognitive AI
   and clockwork processes.  The MIDDLE is especially
   designed to provide machine-cog that manages processes
   that are too fast and small or large and slow for humans
   to be able to do themselves.


** References

  - Downing, F., & Hubka, T. C., Diagramming: a visual
    language, Perspectives in Vernacular Architecture, 2(),
    44–52 (1986).
    http://dx.doi.org/10.2307/3514315publisherJSTOR
    cite:downing:1986diagramming
  - Horn, W., Born, E., Jones, C. W., & Dupree, A. H., The
    plan of st. gall: a study of the architecture \& economy
    of, \& life in a paradigmatic carolingian monastery
    (1979), : University of California Press Berkeley, Los
    Angeles and London.
    cite:horn:1979plan v1.p341
  - Hubka, T., Big house, little house, back house, barn:
    the connected farm buildings of new england., , (),
    (1984).
    cite:hubka:1984big-house
  - Wikipedia, , /Settlement hierarchy --- wikipedia, the
    free encyclopedia/ (2018).
    cite:wiki:2018settlement-hierarchy
  - Sennett, R., The pnyx and the agora, In (Eds.),
    Designing Politics: the limits of design (pp. 6–9)
    (2016). : London School of Economics and Political
    Science.
    cite:sennett:2016pynx
