#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Polis, Nomes
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Polis, Nomes
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-polis-nomes.org
:Created:  2018-04-08T16:03@Prek Leap (11.642600N-104.919210W)
:ID:       09acf54e-3d01-44e6-b6de-c74c43702a64
:VER:      576450283.087603613
:GEO:      48P-491193-1287029-15
:BXID:     proj:JAH7-8338
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

This is actually a Pattern -- do we want to put this here or
move it to APPL?

** Table of Contents

  - Polis
    - As Atomic Unit
    - Human Scale Settlement
    - Urban Population Range
    - Public and Private Life
    - Governance
    - Commerce
    - Infrastructure 

  - Nomes 
    - As Regional Atomic Unit
    - As Bioregion
    - As Part of a Polis Administration & Infrastructure


** Urban Population Range

We define here the broad outlines of what an ideal Polis is
as a legal, physical, and social entity according to first
principles.

#+begin_quote
If we turn back in history we find, however, that,
throughout the long evolution of human settlements, people
in all parts of the world tended to build an urban
settlement which reached an optimum size of 50,000 people
and physical dimensions such that everyone was within a
10-minute distance from the center. There is no question
that, for people who depend on walking as a means of
locomotion, this unit is the optimum one from th e point of
view of movement and social interaction through direct
contacts between people.  Also, experience has shown that,
for people who can walk, it is a maximum one from the
standpoint of aesthetics; for example, creation of the Place
de la Concorde in Paris cut from the total 3500-meter length
of the Champs Elysees a length of 2100 meters, a distance
from which one can reach, and enjoy, the Arc de Triomphe on
foot. It is also perhaps an optimum one from the social
point of view; for example, Pericles in ancient Athens could
get a reasonable sample of public opinion by meet ing 100 to
150 people while walking from his home to the Assembly.

-- Ekistics, the Science of Human Settlements
   Constantinos A. Doxiadis
#+end_quote
