#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Primer
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Primer
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-primer.org
:Created:  2018-04-10T11:03@Prek Leap (11.642600N-104.919210W)
:ID:       3e6205e9-f41b-4320-8fb8-f82616149612
:VER:      576605078.415659344
:GEO:      48P-491193-1287029-15
:BXID:     proj:PUL4-6101
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR
** Table of Contents

** Primer

*** Origin Story
  - Filters

  - 1. The Big Bang
  - 2. Stars Light Up
  - 3. New Chemical Elements
  - 4. Earth and the Solar System

  - Life
  - 5. Life on Earth
  - 6. Collective Learning
  - 7. Agricuture
  - 8. The Modern Revolution




The origin story is the first part of the primer,[fn:1]
followed by the theses (declarations), then education (triv,
quad, laurea etc), then the shops and guilds, then the
value-chain, then bioregions, and finally production.

Man started out just as any other animal on the savannah,
but development of tools, then speech and finally writing
resulted in an estrangement that in our minds that estranged
us from the world and who we were that seemed to have
started with Aristotle and all of those god damned lists and
categories.  It wasn't until the Copernican Revolution which
showed that there was nothing special about where we were in
the universe that we began the slow process of decentering.
The Darwinian Revolution was the second decentering which
taught us that we are just one more creature in a vast
fabric of life and that all of the rules apply to all of us,
we are no exception. I believe that we are at the brink of a
third which will teach us that our minds and our
intelligence is nothing special either.  We've fallen a long
way and we are still falling.  And as anyone who has jumped
out of an airplane could tell you, the fall is nothing to be
afraid of, it's when the ground breaks your fall that you
have to worry about. Intelligence is all around us, we are
simply too caught up in ourselves to notice.  I hope that
when Man does hit bottom that it will leave us humbled and
capable of living within the limits of the ecosystems that
we are part of.  That doesn't mean we will stop hacking them
and shaping them for our own purposes, but it will have to
be with an understanding that we either find a way of living
within the carrying capacity of where we live, or we die.
You can not increase carrying capacity by using up or
abusing resources faster than they can be replaced.  If you
can hack nature to increase sustainible carrying capacity
great -- but that is not what Man is doing now.

  - social contract   
  - origin
  - theses
  - education
  - shops & guilds
  - value-chain
  - 
  - bioregions/ecosystems
  - production & surpluses

    - slavery/mass labour -> machinery -> cognitive machines

*** Slavery and Civilization

All employment at scale has at its roots, human slavery. I
realize that at first this sounds like an inflammatory
statement, but it's not.  Once you grow a group beyond the
scale of a band or small tribe, you slavery begins to
emerge.  This is universal, it cuts across all human
societies and religions and ideologies (tho religion is a
subset of ideology).

---

Two sides to slavery; surplus mind and muscle, you need both
to create a surplus that leads to surpluses that free a
proportion of the population to pursue intellectual pursuits
that result in advancements in technology, sciences and the
arts.

This follows toffler: 

    force -> wealth -> knowledge

Human labour at scale mirrors this perfectly: 

    slave/convict -> indenture/conscript -> employee

At each level labour becomes more abstract, flexible and
more powerful, but at base it's jelly beans, they might all
have different pretty colors but inside it's all made up of
the same sugary crap.

My argument here is that labour does not and can not scale
without it becoming a manifestation of slavery.


  - domesticated animals had the muscle but not the mind so
    you still needed slaves who were compelled through
    physical force to direct the beasts.  people submited to
    slavery because of fear of physical force.

  - machines had the muscle but not the mind so you needed
    captive labour in the form of factory workers who were
    economically compelled to work to direct the machines.
    This system is more flexible and scalable than slavery.
    people submited to industrial factory jobs because of
    fear of poverty.  after poverty was largely taken out of
    the equation other fears were leverages -- leveraing
    fear is how to keep slaves in line.  keep them dumb,
    control what information they have access to, keep them
    scared and then give them cheap consumer goods so that
    they produce and consume as they are told.

  - when you use machine cognition to direct the machines
    you get robots which does not require compelled human
    labor.  Ths system is more flexible and scalable than
    mass indusitural human labor.

So when you hear claims that it was machines that were responsible for
ending slavery they are both right and wrong.  The nature of slavery
simply changed from a model based on physical force, to a model based
on symbolic wealth.  The work force might have the illusion of being
free but for all practical purposes it was still slavery.  This then
frames the other claim that it was the development of moral and
ethical motivations that ended slavery.  Those moral arguements were
used to change the nature of slavery, not to end it.  And in so doing
was able to scale slavery to proportions that couldn't have been
dreamed of in the wildest dreams of the most barbaric banna
plantation in central America or Cotton farm in the old south.

However, even before 1800 it's difficult to know how many slaves there
were because not all slaves were called slaves.  Serf's, indentured
labor etc. are all forms of the same shade.  This is also true in the
modern industrial era where incarceration in many places is little
more than another form of legal slavery.  Conscription has also taken
forms that are little different from slavery as well.
*** Constants

Constants are bedrock variables that define things that can
not be changed like the speed of light or dunbar's number.
They supercede what we want or what we would like and
provide empirical design limits.  No theses can =violate= or
contradict a =constant=.

 - [[./constant-speed-of-light.org][Speed of Light]]
 - [[./constant-dunbar.org][Dunbar's Number]]
 - [[./constant-millers-law.org][Miller's Law]] (7 plus or minus 2)
 - [[./constant-divided-concurrent-goals.org][Divided Concurrent Goals]]
 - [[./constant--shared_intentionality.org][Shared Intentionality]]

*** Theses

Scopic Theses are declarations that provide a foundation for
a =civil ruleset= for people to live and cooperate with each
other.  Our theses is a social fiction that defines how we
/want/ to live and behave with each other.

 - [[./theses-preamble.org][Preamble]]
 - [[./theses-notes.org][Theses Notes]]






