#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Primer
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Primer
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-primer.org
:Created:  2018-04-10T11:03@Prek Leap (11.642600N-104.919210W)
:ID:       3e6205e9-f41b-4320-8fb8-f82616149612
:VER:      576605078.415659344
:GEO:      48P-491193-1287029-15
:BXID:     proj:PUL4-6101
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


** TL;DR

The Primer is the Hoard after it has been compiled, deployed
running production.

In our case, this will take a number of physical and
electronic forms depending on the succession stage the that
reader belongs to.

The primer is structured like a multi-level labyrinth, with
no Minotaur in the middle.  Each level is designed so that
it forms the foundational prerequisites for the next level.
This is not a quest or a game, the reason for this structure
is both pedantic and pragmatic.  You can't build an AI until
you have a computer, you can't build a computer (with
apologies to Babbage) unless you have integrated circuits,
you can't have integrated circuits unless you have an
electrified mechanical industrial infrastructure, you can't
have an electrified mechanical infrastructure unless you
have an industrial infrastructure to electrify and you can
build that ingrastructure without a base pre-electrical
civilization, with a stable means of providing the base
levels of Maslow's hierarchy; food, shelter, health, saftey
and the free time to learn and experiment.

So each level will be designed using media appropriate to
that succession stage.  Stone and etched metal for basic
pictoral information to get one started and stay alive,
paper for those who have basic literate and numerative
skills, and eventually dynamic machine graphical interfaces
and perhaps more advanced types of interfaces when the
technology becomes available.

If we think of the Primer as being a milti-layered fabric
made up of threads that compromise its warp and woof, then
the Primer is the mechanism that acts as a skein, a thread
or path through each layer of fabric and then from layer to
layer.

** Table of Contents


  - The Young Ladies Illustrative Primer
  - Formats and structure for each Succession Stage
    - Pre-tool
    - Tool
    - Clockwork
      - Electric
      - Electronic
      - Cognitive

  - Dimensions of each State
    - Cultural Mythos as framework derived from, built on
      top of an eventually displacing existing systms.  This
      is how religions have spread throughout time -- Islam,
      Christianity and Buddhism didn't replace previous
      religions, they displaced them and appropriated
      local cultural systems, language and beliefs.
    - Social and family structures reflect economic level of
      development more than than culture.  Each stage will
      have it's own social and family structures.
    - 
** 
