#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Primer
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Primer
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-primer.org
:Created:  2018-04-10T11:03@Prek Leap (11.642600N-104.919210W)
:ID:       3e6205e9-f41b-4320-8fb8-f82616149612
:VER:      576605078.415659344
:GEO:      48P-491193-1287029-15
:BXID:     proj:PUL4-6101
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


** TL;DR

After the primer is the Hoard -- the library of descriptive
and prescriptive knowledge.  This will be a map but a very
detailed map whose territory is the archive.

This will be the knowledge that is assembled to build a
civilization from first principles -- this will include
designs, standards, recipes, facts, proceedures, best
practices.

The idea is that you will pick out your patterns and create
your pattern language which is at the core of a master
generative plan -- then you use the knowledge from the Hoard
to build it.

A pattern might be for outdoor windows, and what they must
incorporate to work.  The Hoard will provide the information
for obtaining or creating the building material, wooden,
plastic or metal frame, plate glass, glazing, screws,
caulking and all of the tools needed to build it and then
more general proscriptive steps that make up the art of
glass making, and window framing.

The Archive will be all of the primary documents that the
Hoard is built on.

----

But don't forget that the Hoard has two parts -- map and
territory, so the graph database that weaves it together is
just as important as the items in it.


** Table of Contents
