#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Primer
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Primer
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-primer.org
:Created:  2018-04-10T11:03@Prek Leap (11.642600N-104.919210W)
:ID:       3e6205e9-f41b-4320-8fb8-f82616149612
:VER:      576605078.415659344
:GEO:      48P-491193-1287029-15
:BXID:     proj:PUL4-6101
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

The Primer, despite its name, is not actually meant for use
by end-users.  The Primer builds Pattern Language for
generating a Hoard which will be a sort of Application
(tho that term is to be used extremely loosely that will
start from the assumption that the user has nothing, not
even the means for basic survival.

It will start as simple pictographs asking basic questions
such as, do you have food?  Can you make fire? Do you have a
shelter? Can you read? etc. and then guide the user through
eachh step until they have mastered basic survival and have
surplus time to learn more.  The system will be, in some
respects similar to "The Young Ladies Illustrated Primer" in
Neal Stephenson's novel /The Diamond Age/, but instead of
targeting pre-teen girls, it will target anyone, even if
they are living through a Mad Max post-apocolypse scenario.

The system will determine what level of civilization that
you are currently living in, and unlock all levels up to the
level that you are in and start from there.

The Hoard, which is generated from the Primer, is not merely
an instructional device, but a complete infrastructure for
building and maintaining a post-scarcity distributed
multi-planet civilization. If you are laughing right now,
good.  As I write this, of course we don't have a
post-scarcity distributed multi-planet civilization.  You
might well imagine a collapse that will leave you living in
a Mad Max type scenario, but we aren't suggesting to rebuild
things back to the way they were and pack things up, saying
Mission Accomplished.  Look how well that turned out for
George W. Bush?

We are looking ahead to what is possible, using known
science and the bleeding edge technology and base what we
are capable of building on that.

This is a moving target, most things that are true as I
write this today will be outdated or at least superceded by
new disoveries in a decade or less.  So this is why we are
building this in the way we are.  We are not providing an
instruction manual for building a future civilization, but a
toolkit that will constantly be improved and evolve as
things change, for generating successive iterative stages of
civilization with the goal of creating a stable multi-planet
post-scarcity civilization for Mankind that will be a place
that we will want our children's children to live in.

Is this aspirational?  In part, yes.  But it is an
experiement as a first step down a very long road to make a
better world for future generations.

So think of the Primer as a tool for building a genome for
generating a series of civilizations, that will improve with
each iteration, a framework to help us continue to progress,
steer us away from pitfalls and collapse scenarios.  If
there is a collapse, it will be there to help pick up the
pieces and start rebuilding the next day as quickly as
possible.

Our approach is a process not a plan, it is a generator that
can take a vision on one side, and build it on the other.

But a word of caution, this is a road for you to take, not a
destination that you will likely live to arrive at.  And
even if you do live to see it, there will be all sorts of
new problems and dangers and things that we will have
screwed up that will need to be fixed that we can't even
imagine today.  But you have to start somewhere and this is
where we have chosen to start.

** Table of Contents

  - Origin Story
    - Origin as Narrative
      - Big History
        - 01. The Big Bang
        - 02. Stars Light Up
        - 03. New Chemical Elements
        - 04. Earth and the Solar System
        - Life
          - 05. Life on Earth
          - 06. Collective Learning
          - 07. Agricuture
          - 08. The Modern Revolution
    - Origin as Model
      - Maps
      - Time Line
      - Graph (places, events, people, things, ideas) 
      - Dictionary : defines every word used in primer, and canon.
      - Canon : library
  - Calendar
  - Curriculum
    - Primer for a Distributed Civilization
    - Study Succession Model
      - Foundations
      - Trivium :: cognitive toolbox
        - grammar
        - logic
        - rhetoric
      - Laurea  :: equiv of a PHD (everyone)
  - Keystones (reference standards, techniques, and designs)
    - Succession Model
      - Survival  : staying alive long enough to learn
      - Tools     : hand tools, wind, water, and domesticed
                    plants & animals).
      - Clockwork : enlightened edwardian civilization
      - Electric  : electrified & electronic enlightened edwardian
      - Cognitive : cognitive machines, robotics, bio & nano-tech 
    - Entity Model
      - Keystone (concept)
        - Variation (expression)
          - Design (manifestation)
            - Prototype (instance)
    - Pace-Layer Model
      - Cosmos
        - Helios
          - Lithos
            - Bios
              - Anthros
                - Culture           
                - Governance
                - Infrastructure
                - Commerce
                - Fashion
  - Navigation: Ariadne's Gates (or Pandora's Lid?)
    - learning threads
    - level completion
    - code-base
      - operating-system
      - core languages
      - core applications
      - libraries  
  - Build Process
    - Deployment
    - Propagation
    - Continious Releases
    - Rollback Contingencies

** Primer

Every Primer should begin with an origin story -- not all
Primers will cover as large a canvas as all of civilization,
so scale your LOD to the scope of what your Primer will cover.

** Origin Story
  - Filters

  - 1. The Big Bang
  - 2. Stars Light Up
  - 3. New Chemical Elements
  - 4. Earth and the Solar System

  - Life
  - 5. Life on Earth
  - 6. Collective Learning
  - 7. Agricuture
  - 8. The Modern Revolution

The origin story is the first part of the primer,[fn:1]
followed by the theses (declarations), then education (triv,
quad, laurea etc), then the shops and guilds, then the
value-chain, then bioregions, and finally production.

Man started out just as any other animal on the savannah,
but development of tools, then speech and finally writing
resulted in an estrangement that in our minds that estranged
us from the world and who we were that seemed to have
started with Aristotle and all of those god damned lists and
categories.  It wasn't until the Copernican Revolution which
showed that there was nothing special about where we were in
the universe that we began the slow process of decentering.
The Darwinian Revolution was the second decentering which
taught us that we are just one more creature in a vast
fabric of life and that all of the rules apply to all of us,
we are no exception. I believe that we are at the brink of a
third which will teach us that our minds and our
intelligence is nothing special either.  We've fallen a long
way and we are still falling.  And as anyone who has jumped
out of an airplane could tell you, the fall is nothing to be
afraid of, it's when the ground breaks your fall that you
have to worry about. Intelligence is all around us, we are
simply too caught up in ourselves to notice.  I hope that
when Man does hit bottom that it will leave us humbled and
capable of living within the limits of the ecosystems that
we are part of.  That doesn't mean we will stop hacking them
and shaping them for our own purposes, but it will have to
be with an understanding that we either find a way of living
within the carrying capacity of where we live, or we die.
You can not increase carrying capacity by using up or
abusing resources faster than they can be replaced.  If you
can hack nature to increase sustainible carrying capacity
great -- but that is not what Man is doing now.

  - social contract   
  - origin
  - theses
  - education
  - shops & guilds
  - value-chain
  - 
  - bioregions/ecosystems
  - production & surpluses

    - slavery/mass labour -> machinery -> cognitive machines



** Succession Model

The Succession model is designed so that Hoards can be
generated to work at specific technological and sociel
levels of development.

Giving someone lessons in quantum mechanics and CAD files
for building a molten salt battery is not going to be of
much help to someone who is trying to survive in a
post-collapse survival scenario.

For this reason Primers are designed for five different
succession stages:

  - Survival 
  - Tools 
  - Clockwork
  - Electric
  - Cognitive

Each stage is designed to build on the foundation of the
stage before it.  Because of this, you can't jump from a
Tool Stage directly to the Electric State beause you will
not have the industrial infrasructure, knowledge or
experience to be able to do so.

In fact, we expect that in many cases, people today will
have to refer back to many things in earlier stages because
a lot of knowledge has been lost of how to do mahy things
less than inustrial scales.

This will be the first big challenge for our present
civilizaton, to take centralized massive scale industrial
processes and adapting them to smaller distributed
production systems that are part of a fine-grained supply
and production chain that works as efficiently at small
scales as our present system can only do at massive scales.

Another requirement will be for all stages to be able to
gracefully degrade.  In the event of a collapse, a cognitive
stage region who has suffered a catastrophe should be able
to revert without too much hardship to a lower stage of
production and existence either temporaily or for protracted
periods of time.  So each stage must be reversible.  A
washing machine that runs at the Cognitive Stage must be
able to degrade as far back as to the Clockwork stage and
still be functional until infrastructure is restored.

For this to work, all designs and production must produce
things that are durable, use-repairable, up-gradeable and
down-gradeable.

*** Survival

This stage could actually be designed to work in two broad
scenarios.  We will not decide which or if both of these
scenarios will be supported.

The first scenario is to provide instructions on rebuilding
a civilization that has collapsed.  In Lewis Dartnell's
book, /The Knowledge/ he lays out the initial conditions:

#+begin_quote
Of course, even in one of the extreme doomsday scenarios,
groups of survivors would not need to become self-sufficient
immediately. If the great majority of the population
succumbed to an aggressive virus, there would still be vast
resources left behind. The supermarkets would remain stocked
with plentiful food, and you could pick up a fine new set of
designer clothes from the deserted department stores or
liberate from the showroom the sports car you’ve always
dreamed about. Find an abandoned mansion, and with a little
foraging it wouldn’t be too hard to salvage some mobile
diesel generators to keep the lighting, heating, and
appliances running.  Underground lakes of fuel remain
beneath gas stations, sufficient to keep your new home and
car functioning for a significant period. In fact, small
groups of survivors could probably live pretty comfortably
in the immediate aftermath of the Fall. For a while,
civilization could coast on its own momentum. The survivors
would find themselves surrounded by a wealth of resources
there for the taking: a bountiful Garden of Eden.  

But the Garden is rotting.  

Food, clothes, medicines, machinery, and other technology
inexorably decompose, decay, deteriorate, and degrade over
time. The survivors are provided with nothing more than a
grace period. With the collapse of civilization and the
sudden arrest of key processes— gathering raw materials,
refining and manufacturing, transportation and
distribution—the hourglass is inverted and the sand steadily
drains away. The remnants provide nothing more than a safety
buffer to ease the transition to the moment when harvesting
and manufacturing must begin anew.

— cite:dartnell:2014knowledge

#+end_quote

All sorts of other assumptions can also be made of
survivors.  We can expect them to be literate, have a basic,
if tenuous grasp of basic classical mechanics and physics
and tools (though not as many as one would expect or even
hope).  All sorts of raw materials including metals and even
plastics can be recovered and recycled.  It's far easier to
melt down a pile of aluminium cans and recast the aluminium
for other purposes.  It's extremely difficult to find
bauxite deposits, refine the ore into alumina and get
aluminum that can be used to make things.  Less than two
hundred years ago, despite bauxite being one of the most
plentiful and easily mined minerals on the planet,
aluminimum was far more expensive than gold or platinum
because of the enormous energy and chemical requirements to
refine aluminimum.

The second scenario is to provide a second survival level
Hoard for those who don't stumble across the Hoard for
hundreds or even thousands of years, long after our
industrial civilization has rotted and decayed into
scattered remnants of ruins and relics.  Their path is many
orders of magnitude longer and more difficult than survivors
rebuilding from a recent collapse.

I believe, as does Dartnell, that it's more prudent to
provide a starting point for recent surviors, as a practical
matter of urgency, since this is a far more likely and
immediate scenario we may have to contend with.

#+begin_comment
I want to expand this and explore both in more detail,
including things that can be done to help jumpstart from
scratch -- by leaving caches of raw materials or other
approaches that could get them off the ground sooner.  Such
caches need to be hidden, and forgotten unless there is such
a long term collapse and will only be found by reading the
from-scratch Hoard -- that means that the Hoard must not be
accessable to anyone unless there has been a collapse that
has lasted hundreds or thousands of years.  It's an
interesting problem.
#+end_comment


*** Tools
hand tools, wind, water, and domesticed plants & animals.
*** Clockwork 
enlightened edwardian civilization
*** Electric
electrified & electronic enlightened edwardian
*** Cognitive
cognitive machines, robotics, bio & nano-tech






** Keystone Entity Model

The bulk of the Primer will be made up of keystone reference
items.

Many of these will be prescriptive and descriptive designs
and processes.  They will be organized using the following
Entity Model.

#+begin_example
  - Keystone (concept)
    - Variation (expression)
      - Design (manifestation)
        - Prototype (instance)
#+end_example

We hope to avoid the committee rat trap, and ensure that
keystones are as free of jargan as possible, be an iterative
approach, rather than a committee concensus based approach
with each change or correction or addition slowed down by
politics and different motivations.

A lot of the problems with standards developement will
actually be made easier using the entity model, because
different groups can develop their own Variations, even fork
variations without permission and proceed however they wish.
Then, hopefully we will have a mechanism for choosing the
the best variations as normative references for developing
designs.

A good way of thinking about the development model is as a
GitHub/GitLab type collection of repositories which anyone
can contribute to.  All repos will be under an open licence
and can be forked and adapted in any way people wish.

*** Keystone (concept)

A Keystone is a concept representing the design or process.
Like the Work entity in FRBR.  Unlike the Work entity the
Keystone entity will be closer to a working specification
for what it describes, along similar lines that you see in
W3W early stages of specification development.  The keystone
should be clear, jargon free and include the following
elements:

  - description
  - functional requirements 
  - use-case scenarios
  - data sets for use for testing to see if a
    variation/design/prototype meets those requirements
  - code for running tests based on that data.

*** Variation (expression)

A Variation is an expression of a Keystone which can take
any approach it wants to epressing the keystone so long as
it is compliant with the functional requirements and is
working towards meeting all use-case scenarios.

In many cases, the early variation iterations will fall far
short of the initial goal and will remain as a
work-in-progress, or draft, before finally becomeing a
recommendation.

A Variation is not an actual design, designs can be used to
build something that works in the real world.  Rather, a
Variation is sort of like a patent application that shows
how something is supposed to work.

*** Design (manifestation)

A manifestation is an actual design that can be used to
build something.

All designs are meant to be part of a specific base-line
succession stage, this means that the design must include
everything needed to be built at that stage.  Separate
menifestations will be created for more advanced stages.

So for example, a design for a hammer that will work at the
tool stage (and an early stage of the tool stage) will need
a pictorial design that can be understood by an illiterate
person.  Another design manifestion will be for a literate
person with access to acurate measuring devices, better
quality materials and manufacturing processes for use in the
clockwork and electric stages.  Finally, a design
manigestation will be required that include CAD files, as
well as the software for an automated system system to build
the hammer will be required as well.

Since there will differences in the media used for each type
of manifestation, each design will include documentation for
the correct and safe use of the built design.

*** Prototype

The prototype will mostly be documentation for showing the
end results of building the design using these different
design manifestations for each stage.

** Footnotes

[fn:1] What about language?  Origins lays out our history which is
tells what our metaphysics and physics.  The nuts and bolts of laguage
will be in the Triv.  but I'm talking about something deeper, more
structural -- language both spoken, written and executable -- a
language of the long now that will change far slower than language at
the upper pace layers -- it will change, but over centuries and
milennia not years and decades.  It should be something that is stable
for long periods of time.  Different pace-layers will have different
versions of it, the fashion layer tries out new ideas which are
filtered and refined until they change the lowest layers.




