#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Pace-Layers
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Pace-Layers
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-pace-layers.org
:Created:  2018-03-22T16:57@Prek Leap (11.642600N-104.919210W)
:ID:       8541b0ba-95c5-462c-bc26-63ea275cbb3a
:VER:      574984730.876076307
:GEO:      48P-491193-1287029-15
:BXID:     proj:HBU0-0687
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR
** Table of Contents

- Pace-Layers
  - Complex Societies
  - Biospheres
  - Geological
  - Stellar
  - Shearing-Layers -> for made things

#+begin_comment
Questions:

What are the equivelent of the Nitrogen Cycle or Groundwater
Recharge Cycle for civilizations?

Pace-Layers are relative to each other -- but is there
another way of looking at that?  Do p-layers need to employ
units of measure?
#+end_comment

Shearing layers are not only for buildings

An axe has a shearing layer of a head and a handle, the
handle has a separate life from the head.

But this is only when a made thing follows the REPAIRABLE
and UPGRADABLE patterns

Machines -- let's use three examples:
  - Cars
  - Washing Machines
  - Computers


** Braudel

#+begin_quote
The first part is devoted to a history whose passage is
almost imperceptible, that of man in his relationship to the
environment, a history in which all change is slow, a
history of constant repetition, ever-recurring cycles. I
could not neglect this almost timeless history, the story of
man's contact with the inanimate, neither could I be
satisfied with the traditional geographical introduction to
history that often figures to little purpose at the
beginning of so many books, with its descriptions of the
mineral deposits, types of agriculture, and typical flora,
briefly listed and never mentioned again, as if the flowers
did not come back every spring, the flocks of sheep migrate
every year, or the ships sail on a real sea that changes
with the seasons.

On a different level from the first there can be
distinguished another history, this time with slow but
perceptible rhythms. If the expression had had not been
diverted from its full meaning, one could call it social
history, the history of groups and groupings. How did these
swelling-currents affect Mediterranean life in general --
this was the question I asked myself in the second part of
the book, studying in turn economic systems, states,
societies, civilizations and finally, in order to convey
more clearly my conception of history, attempting to show
how all these deep-seated forces were at work in the complex
arena of warfare. For war, as we know, is not an arena
governed purely by individual responsibilities.

Lastly, the third part gives a hearing to traditional
history - history, one might say, on the scale not of man,
but of individual men, what Paul Lacombe and Francois
Simiand called /'l'histoire événementielle'/, that is, the
history of events: surface disturbances, crests of foam that
the tides of history carry on their strong backs. A history
of brief, rapid, nervous fluctuations, by definition
ultra-sensitive; the least tremor sets all its antennae
quivering. But as such it is the most exciting of all, the
richest in human interest, and also the most dangerous. We
must learn to distrust this history with its still burning
passions, as it was felt, described, and lived by
contemporaries whose lives were as short and as
short-sighted as ours. It has the dimensions of their anger,
dreams, or illusions. In the sixteenth century, after the
true Renaissance, came the Renaissance ofthe poor, the
humble, eager to write, to talk of themselves and of
others. This 'precious mass of paper distorts, filling up
the lost hours and assuming a false importance. The
historian who takes a seat in Philip II's chair and reads
his papers finds himself transported into a strange
one-dimensional world, a world of strong passions certainly,
blind like any other living world, our own included, and
unconscious of the deeper realities of history, of the
running waters on which our frail barks are tossed like
cockleshells. A dangerous world, but one whose spells and
enchantments we shall have exorcised by making sure first to
chart those underlyingcurrents, often noiseless, whose
direction can only be discerned by watching them over long
periods of time. Resounding events are often only momentary
outbursts, surface manifestations of these larger movements
and explicable only in terms of them.

— cite:braudel:1972mediterranean-1 p.21-22


#+end_quote 




** References

  - 
    cite:braudel:1972mediterranean-1 p.21-22
