#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Polis, Nomes
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

* Polis, Nomes
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-polis-nomes.org
:Created:  2018-04-08T16:03@Prek Leap (11.642600N-104.919210W)
:ID:       09acf54e-3d01-44e6-b6de-c74c43702a64
:VER:      576450283.087603613
:GEO:      48P-491193-1287029-15
:BXID:     proj:JAH7-8338
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

#+begin_comment
So how much of this, if any, should be in w&w and how much
in APPL?  The thing is, there are lot of things in the TOC
do not belong in the patterns -- I want to show the whole
heirarchy from person to federation and how that fits
together -- and the points that tie them together and then
the specifics be put into the patterns...

The cool thing for me as I write this is that this is the
level at which we drill down into w&w where we begin to make
the cross-over into APPL.  At this level, about three levels
down from the top, where the distinction gets blurry.

w&w should show in the how patterns form larger abstract
patterns on this side, but then on the other side of APPL
you'll see the same abstract pattern in the Primer which
outlines the reference specifications and the nuts and bolts
of how it fits together and works, but in that case it will
be a manifestation, where it will be an instance in the
hoard.  The hoard, remember, is the information and running
code for a specific instance of a civilization.
#+end_comment


** Table of Contents

  - Polis
    - As Atomic Unit
    - Human Scale Settlement
    - Urban Population Range
    - Public and Private Life
    - Governance
    - Commerce
    - Infrastructure 

  - Nomes 
    - As Regional Atomic Unit
    - As Bioregion
    - As Part of a Polis Administration & Infrastructure



** Bioregion

#+begin_quote
The [bio]region is our home address, the place where we
develop our culture, and take part in bioregional networks.
Through global associations and "families of common
interest" we cross not only the regional but also state and
national borders to set up multicultural alliances.

— Permaculture Designer's Manual cite:mollison:1988designers p.510
#+end_quote

The quote is mostly to point to  Mollison's section on
bioregions as a base unit which becomes the nones to the
polis in the bioregion.



** Urban Population Range

We define here the broad outlines of what an ideal Polis is
as a legal, physical, and social entity according to first
principles.

#+begin_quote
If we turn back in history we find, however, that,
throughout the long evolution of human settlements, people
in all parts of the world tended to build an urban
settlement which reached an optimum size of 50,000 people
and physical dimensions such that everyone was within a
10-minute distance from the center. There is no question
that, for people who depend on walking as a means of
locomotion, this unit is the optimum one from th e point of
view of movement and social interaction through direct
contacts between people.  Also, experience has shown that,
for people who can walk, it is a maximum one from the
standpoint of aesthetics; for example, creation of the Place
de la Concorde in Paris cut from the total 3500-meter length
of the Champs Elysees a length of 2100 meters, a distance
from which one can reach, and enjoy, the Arc de Triomphe on
foot. It is also perhaps an optimum one from the social
point of view; for example, Pericles in ancient Athens could
get a reasonable sample of public opinion by meet ing 100 to
150 people while walking from his home to the Assembly.

-- Ekistics, the Science of Human Settlements
   Constantinos A. Doxiadis cite:doxiadis:1972ekistics
#+end_quote


#+begin_quote
And just as there is a best size for every animal, so the
same is true for every human institution. In the Greek type
of democracy all the citizens could listen to a series of
orators and vote directly on questions of legislation. Hence
or philosophers held that a small city was the largest
possible democratic state. The English invention of
representative government made a democratic nation possible,
and the possibility was first realized in the United States,
and later elsewhere. With the development of broadcasting it
has once more become possible for every citizen to listen to
the political views of representative orators, and the
future may perhaps see the return of the national state to
the Greek form of democracy. Even the referendum has been
made possible only by the institution of daily newspapers.

— On Being the Right Size cite:haldane:1928being
#+end_quote

#+begin_quote
WORLD FEDERATION: A THOUSAND STATES . . the essential
foundation stone for world federation on a democratic basis
consists of regionalization within centralized
government. This argument rests on the idea that world
government is lacking in moral authority unless each
delegate represents an approximately equal portion of the
world's population. Working backward from an estimate of the
global population in the year 2000, which is anticipated to
rise to the 10,000 million mark, I suggest that we should be
thinking in terms of an ideal regional state at something
around ten million, or between five and fifteen million, to
give greater flexibility. This would furnish the U.N. with
an assembly of equals of 1000 regional representatives: a
body that would be justified in claiming to be truly
representative of the world's population.

— Lord Weymouth of Warminster, England, in a letter to the
  New York Times, March 15, 1973
  Quoted in: cite:alexander:1977pattern
#+end_quote



** References 

   - Alexander, C., Ishikawa, S., & Silverstein, M., A
     pattern language: towns, buildings, construction
     (1977), : Oxford University Press.
     cite:alexander:1977pattern
   - Borras-Alomar, S., Christiansen, T., & Rodriguez-Pose,
     A., Towards a ‘europe of the regions'? visions and
     reality from a critical perspective, Regional \&
     Federal Studies, 4(2), 1–27 (1994).
     cite:borras:1994towards
   - Doxiadis, C. A., Ekistics, the science of human
     settlements, Ekistics, (), 237–247 (1972).
     cite:doxiadis:1972ekistics
   - Haldane, J. B. S., On being the right size, Harpers,
     (), (1928).
     cite:haldane:1928being
   - Mollison, B., Permaculture: a designers' manual
     (1988), : Tagari.
     cite:mollison:1988designers
