#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Principles
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Principles
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-principles.org
:Created:  2018-03-21T15:54@Prek Leap (11.642600N-104.919210W)
:ID:       89567717-54f9-4114-93b4-5079795d2170
:VER:      574894558.545678422
:GEO:      48P-491193-1287029-15
:BXID:     proj:BVP7-1402
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

Principles are organized along the same lines as the
Pace-Layer model that is explained
/Part 8. Scaffords/Pace-Layers/ and in /APPL/A Summary of
the Language/.

** Table of Contents

Getting up to Date:

   - Before the enlightenment the big shift was first
     development of spoken language.  But memory was still
     RAM, that only existed in living memory.  But this was
     enough to create permanent settlements, agriculture and
     scale communities that made it possible to increase the
     complexity of human societies by several orders of
     magnitude.  This was the beginning of the concept of
     property, and extending that concept from land, to
     material goods and to other people.  The slave era was
     a paradox, subjecting most people to wretched lives
     where the wealth they created propagated to an elite
     few, and did not improve the lives of those creating
     the wealth.  But it also created surpluses that
     extended the elite to a new class of people people
     whose only job was to think, solve problems and come up
     with new ideas.  But this was an oral tradition, the
     surplus's had a ceiling which was essentially that of
     the memory of individual humans -- this was the world
     of Homer.

   - Those surpluses allowed people to solve the memory
     problem by inventing written language -- which extended
     human cognition, externalized human memory and made it
     possible to communicate to places that the author had
     never been and into the future.  This triggered a
     cognitive revolution that was not to be matched until
     the industrial revolution -- The industrial revolution
     began earlier than many thought, and a number of
     keystone inventions laid the groundwork for it over
     several centuries -- including the printing press, the
     concept of external power sources such as wind and
     water (not as propulsive power, but to power tools,
     laying the groundwork for machines).  Other keystone
     inventions included standardization of measures, time
     measurement, the printing press, etc.

   - The steam revolution was at the heart of the industrial
     revolution -- 

     steam was crude and wasteful, which was replaced by the
     internal combustion engine which bypassed steam and
     moved fire directly into the engine.

   - The electric revolution vastlly reduced the number of
     moving parts and replaced fire completely and was far
     more flexible.

   - electricity made machines very large and very small --
     which meant that muscle was not only replaced at very
     large scales, but human scales with machines at human
     scales and machines that worked at scales far smaller
     than human scales -- this which made possible the first
     cognitive machines.


   - Enlightenment
     - a few pockets of civilization, in ancient Greece, India and
       China laid the initial groundwork that solidified
       mankind's transition from spoken language to be able
       to externalize and extend mind and memory using
       written language.
     - scientific revolution kicked it off
     - based on rationality, science, and progress (Pinker's def)
     - Bacon, Decartes, Locke and Spinoza
     - place in the universe
       - the Copernican revolution -> we are not at the center
       - the Darwinian revolution -> we are not apart from nature
     - mechanization extended the hand using tools, to
       machines leveraging hand and muscle.  This
       fundamentally transformed man from beasts of burden
       controlled by an elite, to thinking slaves operating
       machines -- machines replaces human muscle.


     - combined with Industrial Revolution, began, in 1800 a
       transformation in human existence.
       - war, violence, poverty, education, human rights
         etc. all began a massive upwards curve that we are
         still in the middle of.


     - not Romantic
   - Rationality
     - appealing to empirical based reasoning

     - intuition/deduction (a priori/a postereriori)

     - methodology in which truth is not sensory
     - skepticism 

     - utilitarian
     - pragmatic
     - secular
     - humanist

     - Enlightened Self Interest
     - Empathic Reciprocity

   - Democratic Process
     - As goldilock zone between violence of anarchy and
       violence of popularism/totalitarianism/oligarchies
     - Egalitarian
   - Human Scales: Self, Domus/Band, Polis
   - Scientific Process
     https://en.wikipedia.org/wiki/File:The_Scientific_Method_as_an_Ongoing_Process.svg
     - Empirical 
       - evidence based
     - Hypothesis development
     - Prediction
     - Testable and repeatable
     - Record/Document and Share
     - Analysis
     - External Review
     - Consensus
   - Progress
     - not same as growth


#+begin_comment
Tainter argues that civilizations hit maximum complexity and
can't sustain itself -- rather civs max out their ability to
innovate and change the parameters of the petri dish -- they
hit the edge of the petri dish because they could not find a
way to grow.
#+end_comment

