#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Specializations
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Specializations
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-specializations.org
:Created:  2018-04-11T23:17@Prek Leap (11.642600N-104.919210W)
:ID:       20ea1ca3-d723-431d-9c8e-7b1b83b01430
:VER:      576735489.296135798
:GEO:      48P-491193-1287029-15
:BXID:     proj:UCV1-1046
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

how we divide things and increase complexity

systems are made up of different components that are filled
by specialized sub-processes.  The larger the system, the
more it tends to become more complex, by larger processess
to become finer-grained in order to adapt to variations in
the larger territory/population.

A sub process could be a plant or animal in an ecosystem, or
it could be a specialization in a society/civilization.

Several things happen to specialists -- first, the domain of
a specialist process is called a niche.  If the specialist
that fills that niche dies or the parameters for that niche
change so that the specialist no longer has the ability to
fulfill the needs of that process you get an empty niche
which eventually is filled by a new specialist that evolves
to fill that niche.

when two ecosystems come into contact and effectively merge,
and there are now two different specialists that fill the
same niche, over time, one of the two specialists is found
to be better than the other and takes over that niche.  We
see this over and over in natural history and in societies.

** Table of Contents

