#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Succession
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Succession
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-succession.org
:Created:  2018-04-17T12:28@Prek Leap (11.642600N-104.919210W)
:ID:       12b23860-380a-454a-bd52-51068e214e20
:VER:      577214948.262552646
:GEO:      48P-491193-1287029-15
:BXID:     proj:HJY2-4437
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

We have already introduced the Successon Model, as one of
our core Scaffolds but it's important to start introducing
some example Succession implementations that could be used in
building civilizations.

The succession models here are very much first drafts and
will change radically as we learn more and work continues.

The examples used here are NOT normative.  Succession models
will be used in Hoards to generate Primers will be defined
as Succession Patterns in APPL.

This Part is meant to be a practicum in taking the
principles and sructures that we have explored thus far and
see how they can be used to create actual Succession models
that could be deployed.

As the Succession Patterns are developed and changed, these
examples will be updated as well.  Please refer to the
succession patterns in the latest version of APPL 

** Table of Contents

  - ecological
  - civilization
  - education
  - stages of life
  - governance
  - shops
  - guilds

  - mars
