#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Slavery
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Slavery
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-slavery.org
:Created:  2018-03-28T09:28@Prek Leap (11.642600N-104.919210W)
:ID:       afbba1aa-d17d-493e-bb03-5ca3a55a7c93
:VER:      575476165.124590766
:GEO:      48P-491193-1287029-15
:BXID:     proj:QGL6-3676
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

** Table of Contents

 - Definition of slavery :: Any semi, or self-directed
   entity capable of producing wealth that is controlled
   or effectively owned by another entity whose wealth
   self-propagates to the controlling entity.

 - Institutional Slavery (physical, crude, inflexible, scales)

 - Free Market Industrial Slavery (semi-skilled, physical
   but flexible, scales).

 - Free Market Knowledge-Worker Slavery (skilled,
   semi-physical, highly flexible, scales).

 - 


 - Machine-Cog Slaves and cognitive thresholds.

 - The Right to a Life According to your Nature -- Salitan,
   and omnivore's dilemma.cite:pollan:2007omnivore 

   the thing is though, that ultimately, we human's, by
   accepting this principle, are not exempt from it being
   applied to us in the future -- I'm not talking about
   those that have used this tact to justify slavery, by
   claiming that the enslaved are too stupid to know better
   and are content being enslaved -- it would have to work
   at the level where humans would be free to do pretty much
   anything they want, not be limmited by what others claim
   is what they want.



---

Any semi, or self-directed entity capable of producing
wealth that is controlled or effectively owned by another
entity whose wealth self-propagates to the controlling
entity.

In this sense, a slave is functionally no different from an
employee except in degree.  State supported slavery, is only
different from incarcerated people in that a person in
prison, in theory is only enslaved for a proscribed period
of time, which is also the case for indenture, tennent
farmers etc.

This system was very crude and not very flexible.  The
industrial age changed this because production was depended
solely on human labour with the use of tools.  Industrial
labor had machines which are largely large expensive fixed
assets.  Such production needed a more flexible workforce to
operate these machines, and since slavery was based largely on
unskilled labor, didn't work with  semi-skilled labor
required to operate machinery.  In many cases, this creates
a captive labor pool where whole towns and even cities are
dependent on one or more factories.  Workers are not
educated enough to move up the ladder to white collar work,
and family pressure keeps them from moving to another city.

---

The problem is that unless a factory is effectively owned by
it's workers, there is no mechanism for workers to be able
to not effectively be slaves. The wealth they create is not
theirs.

Famously, the person who invented the Post-It made millions
for 3M, but didn't receive so much as a salary bonus from
the company.

--- 

This is the opposite of egalitarian systems, where wealth
created by individuals in a group is shared, but those who
create the wealth benifit from it.  This is fair because
pooling your efforts you will benifit when say, you are sick
and can't produce, or your hunting party was unable to find
any prey that day, but another party did.




  - A brief history of slavery

  - The Slave Paradox




  - cultivation -- plant slaves
  - domestication -- slave species
  - slavery -- state-supported human slaves
  - workers -- machine+worker defacto slaves
  - robots -- machine-cog-robot slaves

** References

 - Pollan, M., The omnivore's dilemma: a natural history of
   four meals (2007), : Penguin Books.
   cite:pollan:2007omnivore 

