#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Strucutures
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Strucutures
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-structures.org
:Created:  2018-03-21T18:34@Prek Leap (11.642600N-104.919210W)
:ID:       c76b2682-c6c4-4f2b-91b5-d564f2918890
:VER:      574904163.914123690
:GEO:      48P-491193-1287029-15
:BXID:     proj:VON6-5866
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR
** Table of Contents

*** Data Structures
 - atoms       -> symbol, string, integer
 - ????        -> k-v, triple
 - rhizomes    -> graphs
 - sets        -> lists: bag, seq, alt
 - trees       -> branching lists
 - layers      -> What about arrays?

*** Social Structures

individual is atomic unit

*** Egalitarian Structures
  - mated pair = couple - economic unite
  - pair + children = nuclear family
  - pair + children, and parents = extended family
  - band = base hunter-gather unit, human equiv of a pack
  - clan = band that are made up of members who are blood
    relations.

*** Corporate Structures

Corporate -- a virtual person that operates according to a
set of rules, that may or may not be owned by other
entities.

*** Sovereign Structures

Corporation + sovereignty = state

Sovereignty is typically justified by supernatural 

It is common for royals to claim that they hold their
positions by the authority of a deity, who backs up their
position with the force of that deity (in this life or the
next) -- with the implication that if you do not recognize
their authority you are challenging God.

This has morphed into moving authority from a deity to an
ethnic group with squatter rights.  That if you go against
the authority that lays claim to representing that ethnic,
religious or cultural group you are attacking everyone in
that group.

The enlightenment morphed this still further to define a
nation as a collection of any group with a shared national
identity that can participate in elections that choose
leaders.

In all cases, the benifits of property and wealth controlled
(owned) by a group self-propagates to the leaders.  This
self-propagation is an important concept because if people
are considered property, then the wealth that they produce
is owned by those who have control or claim ownership.
