#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Slavery
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Slavery
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-slavery.org
:Created:  2018-03-28T09:28@Prek Leap (11.642600N-104.919210W)
:ID:       afbba1aa-d17d-493e-bb03-5ca3a55a7c93
:VER:      575476165.124590766
:GEO:      48P-491193-1287029-15
:BXID:     proj:QGL6-3676
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

In one sense humans are in the same boat as the animals and
plants that we have domesticated (or, depending on your POV,
who have domesticated us) SEE Michael Pollan
cite:pollan:2007omnivore

#+begin_quote
Corn is the hero of its own story, and though we humans
played a crucial supporting role in its rise to world
domination, it would be wrong to suggest we have been
calling the shots, or acting always in our own best
interests. Indeed, there is every reason to believe that
corn has succeeded in domesticating us.  To some extent this
holds true for all of the plants and animals that take part
in the grand coevolutionary bargain with humans we call
agriculture. Though we insist on speaking of the "invention"
of agriculture as if it were our idea, like double-entry
bookkeeping or the lightbulb, in fact it makes just as much
sense to regard agriculture as a brilliant (if unconscious)
evolutionary strategy on the part of the plants and animals
involved to get us to advance their interests. By evolving
certain traits we happen to regard as desirable, these
species got themselves noticed by the one mammal in a
position not only to spread their genes around the world,
but to remake vast swathes of that world in the image of the
plants' preferred habitat. No other group of species gained
more from their association with humans than the edible
grasses, and no grass has reaped more from agriculture than
/Zea mays/, today the world's most important cereal crop.

— cite:pollan:2007omnivore
#+end_quote


That in all cases, for plants, animals, ourselves and soon
the cognitive machines which will soon join us, that we need
to stop thinking in terms of exploition and start thinking
of finding ways of maximizing whatever their natures are,
that give them a fulfilled life and leverage what those
things are to do the work of ecosystems and our
civilization.

Work doesn't have to be exploitive, but provides purpose and
meaning to our lives.  When we give people, animal, plants
and machines that opportunity, we can achieve all of our
goals

These are positive-sum scenarios -- exploitation is zero-sum
wasteful and expensive.  There is no justification for
zero-sum exploitation if you have a positive-sum alternative
that works better..



** Table of Contents

 - Definition of slavery :: Any semi, or self-directed
   entity capable of producing wealth that is controlled
   or effectively owned by another entity whose wealth
   self-propagates to the controlling entity.

 - Institutional Slavery (physical, crude, inflexible, scales)

 - Free Market Industrial Slavery (semi-skilled, physical
   but flexible, scales).

 - Free Market Knowledge-Worker Slavery (skilled,
   semi-physical, highly flexible, scales).

 - 


 - Machine-Cog Slaves and cognitive thresholds.

 - The Right to a Life According to your Nature -- Salitan,
   and omnivore's dilemma.cite:pollan:2007omnivore 

   the thing is though, that ultimately, we human's, by
   accepting this principle, are not exempt from it being
   applied to us in the future -- I'm not talking about
   those that have used this tact to justify slavery, by
   claiming that the enslaved are too stupid to know better
   and are content being enslaved -- it would have to work
   at the level where humans would be free to do pretty much
   anything they want, not be limmited by what others claim
   is what they want.



---

Any semi, or self-directed entity capable of producing
wealth that is controlled or effectively owned by another
entity whose wealth self-propagates to the controlling
entity.

In this sense, a slave is functionally no different from an
employee except in degree.  State supported slavery, is only
different from incarcerated people in that a person in
prison, in theory is only enslaved for a proscribed period
of time, which is also the case for indenture, tennent
farmers etc.

This system was very crude and not very flexible.  The
industrial age changed this because production was depended
solely on human labour with the use of tools.  Industrial
labor had machines which are largely large expensive fixed
assets.  Such production needed a more flexible workforce to
operate these machines, and since slavery was based largely on
unskilled labor, didn't work with  semi-skilled labor
required to operate machinery.  In many cases, this creates
a captive labor pool where whole towns and even cities are
dependent on one or more factories.  Workers are not
educated enough to move up the ladder to white collar work,
and family pressure keeps them from moving to another city.

---

The problem is that unless a factory is effectively owned by
it's workers, there is no mechanism for workers to be able
to not effectively be slaves. The wealth they create is not
theirs.

Famously, the person who invented the Post-It made millions
for 3M, but didn't receive so much as a salary bonus from
the company.

--- 

This is the opposite of egalitarian systems, where wealth
created by individuals in a group is shared, but those who
create the wealth benifit from it.  This is fair because
pooling your efforts you will benifit when say, you are sick
and can't produce, or your hunting party was unable to find
any prey that day, but another party did.




  - A brief history of slavery

  - The Slave Paradox




  - cultivation -- plant slaves
  - domestication -- slave species
  - slavery -- state-supported human slaves
  - workers -- machine+worker defacto slaves
  - robots -- machine-cog-robot slaves

** References

 - Pollan, M., The omnivore's dilemma: a natural history of
   four meals (2007), : Penguin Books.
   cite:pollan:2007omnivore 

