#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Specializations
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Specializations
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-specializations.org
:Created:  2018-04-11T23:17@Prek Leap (11.642600N-104.919210W)
:ID:       20ea1ca3-d723-431d-9c8e-7b1b83b01430
:VER:      576735489.296135798
:GEO:      48P-491193-1287029-15
:BXID:     proj:UCV1-1046
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

how we divide things and increase complexity

systems are made up of different components that are filled
by specialized sub-processes.  The larger the system, the
more it tends to become more complex, by larger processess
to become finer-grained in order to adapt to variations in
the larger territory/population.

A sub process could be a plant or animal in an ecosystem, or
it could be a specialization in a society/civilization.

Several things happen to specialists -- first, the domain of
a specialist process is called a niche.  If the specialist
that fills that niche dies or the parameters for that niche
change so that the specialist no longer has the ability to
fulfill the needs of that process you get an empty niche
which eventually is filled by a new specialist that evolves
to fill that niche.

when two ecosystems come into contact and effectively merge,
and there are now two different specialists that fill the
same niche, over time, one of the two specialists is found
to be better than the other and takes over that niche.  We
see this over and over in natural history and in societies.

** Table of Contents

 - Systems Thinking
   - Relationships between different parts of a system
   - flows of energy and resources, needs and opportunities

   - processes that can be thought of as a series of steps
     in which the result of one event triggers another event
     etc.  In computer science this is called Input and
     Output.  Input introduces something into a process that
     does something with the input and the output is then
     fed into another process which does does something that
     produces an output until the process is complete, or
     loops back to start again.  If there is a loop, a
     feedback system is then required to determine if or
     when a loop is terminated.

   - positive feedback loops reinforce unchecked growth

   - negative feedback loops have upper and lower boundries
     and a trigger (sensor) that trips if growth should
     start or stop in order to remain within those
     boundries.


 - positive vs negative space
   - in architecture 
     -- negative is what surrounds what is built
     -- positive is what is built
     -- we move through negative spaces
     -- we dwell in positive spaces
   - in ecology
     -- negative is where there are no resources 
     -- positive is where resources are distributed
     -- species fill ecological niches through adaptation to
        dynamics of the niche, climate, how to access
        resources, shelter, countermeasures against
        predators etc.
   - in cooperative social systems
     -- positive is created by breaking up knowledge and
        tasks into sizes that an individual can handle.  The
        more complex the task, the more knowledge and skills
        required to complete the task.  As systems scales,
        the need for a task is larger than a single person
        can fill, so the task is duplicated so that more than
        one person is filling the same task.
     -- negative is created between knowledge and skill
        domains which require different skills,  tools
        resources and knowledge.
   - in market economies
     -- negative is where there are no needs or opportunities
     -- positive is where there are opportunities to fill
        needs
     -- people develop methods to fill needs to survive
        where there is less competition, if the people
        filling a need outnumber the demand for the need
        then the cost (reward) goes down through competition
     -- markets are a flexible means of distributing
        specialization because they don't require
        hierarchical coordination -- planned economies fail
        because of top-down command and control which is not
        flexible enough to meet the needs of unpredictible complexity.
