#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Succession
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Succession
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-succession.org
:Created:  2018-03-22T12:02@Prek Leap (11.642600N-104.919210W)
:ID:       1a0e2740-9b50-4db2-9c17-7e3601374b2d
:VER:      574967007.402589543
:GEO:      48P-491193-1287029-15
:BXID:     proj:TNA7-1268
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR
** Table of Contents
 - Succession models
 - Reversibility
   - upgrade & degrade
 - Keystones
   - species
   - concepts
   - niches
   - specializations
   - standards
   - designs
 - Stages
   - ecological
   - economic
   - technological
   - cultural
   - ages of man  cite:wiki:2018ages-of-man
     - Hesiod -- golden, silver, bronze, heroic, iron
     - Ovid -- golden, silver, bronze, iron
     - Vico - ages of man, heros, gods
     
#+begin_quote
Vico, the father of historicism, discovered that the nature
of man changes: the archaic man feels, thinks, acts in a way
completely different from modern man. In Vico's scheme of
the necessary evolution of every culture, three phases are
distinguished: the age of gods, the age of heroes, and the
age of men. The age of gods is characterized by a theocratic
government: it is anterior to any differentiation of the
various aspects of curlture such as religion, politics, or
art. The age of heroes, on the other hand, is dominated by
the conflict between classes, the heroes and the
plebeians. This age does not yet have a state; therefore,
force and violence reign. The right of the stronger is the
main ground of legitimacy. Two types of relations are
characteristic of this age: the relation between enemies who
fight each other, risking their own lives and those of their
combatants, and the relation between master and servant. The
duel, a fight between two heroes accompanied by their
servants, is the symbolic action of the heroic age. In it
the value of a person is proved, even constituted. Relations
toward wives in the age of heroes are clearly asymmetric:
women are not yet recognized as having the same human nature
as men. "Love of ease, tenderness toward children, love of
women, and desire of life" are alien to the heroes, so Vico
once sums up his view of the heroic age.

— https://ataleofatribe.blogspot.com/2011/05/vicos-age-of-heroes-and-age-of-men.html
#+end_quote

#+begin_quote
Vico believed in a cyclical philosophy of history where
human history is created by man. His term for the cyclical
nature of history was "corsi e ricorsi". Most importantly,
man and society move in parallel from barbarism to
civilization.

    As societies become more developed socially, human
    nature also develops, and both manifest their
    development in changes in language, myth, folklore,
    economy, etc.; in short, social change produces cultural
    change.

Vico is therefore using an original organic idea that
culture is a system of socially produced and structured
elements.[1] Hence, knowledge of any society comes from the
social structure of that society, explicable, therefore,
only in terms of its own language. As such, one may find a
dialectical relationship between language, knowledge and
social structure.[1]

Relying on a complex etymology, Vico argues in the Scienza
Nuova that civilization develops in a recurring cycle
(ricorso) of three ages: the divine, the heroic, and the
human. Each age exhibits distinct political and social
features and can be characterized by master tropes or
figures of language. The giganti of the divine age rely on
metaphor to compare, and thus comprehend, human and natural
phenomena. In the heroic age, metonymy and synecdoche
support the development of feudal or monarchic institutions
embodied by idealized figures. The final age is
characterized by popular democracy and reflection via irony;
in this epoch, the rise of rationality leads to barbarie
della reflessione or barbarism of reflection, and
civilization descends once more into the poetic era. Taken
together, the recurring cycle of three ages – common to
every nation – constitutes for Vico a storia ideale eterna
or ideal eternal history. Therefore, it can be said that all
history is the history of the rise and fall of
civilizations, for which Vico provides evidence (up until,
and including the Graeco-Roman historians).

— cite:wiki:2018the-new-science
#+end_quote

 - Succession stacks
   use POC so that succession is treated as a stack, not
   one stage replacing another.  This is useful to apply LOD
   to a text, so that you can read a layer at a low LOD (say
   for beginners, and then move down to progressively more
   detailed and more advanced material.
    
** Succession Models

This works the same as in [[https://en.wikipedia.org/wiki/Ecological_succession][ecological succession]] but for
civilization:

  - terrestrial 
    - nomadic hunter-gather
    - semi-nomadic
    - sedantary 
      - agricultural -> villages and towns
      - industrial   -> cities and states
      - info-network 
      - machine-cog  -> machine-cognition controlling machines
  - extra-terrestrial
    - nomadic -> exploritory  -> robotic then human
    - sedantary
      - stations
      - colonies
      - solar civilizations 
  - extra-solar

Sucession can be linear or cyclical.  Any stage can move on
to the seceeding stage or revert to previous stages.  It's
possible to jump stages -- but as a general rule this should
be avoided.  Just as a human embyro passed through different
evolutionary stages in the womb, jumping to an advanced
stage directly is both difficult and runs the risk that it
will not be complete.  This holds for both ecological
succession as well as societal succession and technological
succession.  It's not a good idea for human societies to try
and jump stages -- the changes are too traumatic and will
result in disruption that will cause irreparable damage to
the society.  The same is true of humans, but is a different
way.  People can only change so much in a lifetime, unless
they have been able to learn to internalize change massive
change.  And even then it's limited.


stages of the primer will provide generative grammars for
each layer as well as all of the knowledge needed to build
that stage and lay the groundwork for the next stage.

The primer is focused on expressions of civilization rather
than manifestions or instances.

In this respect, the primer is prescriptive more than
descriptive.

The primer will include specific recomendations for
standards -- weights and measures, standard things like
screw and bolt thread specifications, guages of wire etc.

It will provide keystone designs for things like electrical
sockets, hinges, electric motors.

It will provide keystone designs for processes and keystones
for building them for different succession layers.

*** Terms

- succession stage --
- keystone designs -- reference designs 
** Reversibility

When possible everything in the primer should at least try
to be capable of gracefully degrading, so that if there is a
problem that knocks you back to a previous stage, you are
not screwed.

If this is designed into the system from day one, then some
interesting things become possible -- we can provide
keystone designs which can be upgraded years or decades
later.

    Let's use a washing machine as an example. An agitating
    clothes washer can be build that will work mechanically,
    with any power source from using water or even a biycle
    as well as an electrical motor.  Controls for the
    washing machine can be mechanical, or electronic.  You
    could also create an API and a network interface and
    install sensors in the washing machine so that the
    machine could me controlled remotely via software or
    machine-cog.  Since washing machines can have used to be
    built that lasted decades with little or no maintenance,
    there is no reason why we can't have design where you
    can upgrade a machine for electricity then electronics
    and then network controllable.  And this should then
    work in reverse.  If the network is down, it should work
    electronically, if the electronics are down it should
    work mechnically with electricity, if electricity is
    down you should be able to reconnect the belt to a
    mechanical power source.

Such designs are not as easy to build as designs that are
built for a single succession stage -- but because a washing
machine, if well designed and built, should easily last a
half century, then it makes sense to take the extra effort
to make it both upgradable and degradable
