#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Tools
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Tools
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-tools.org
:Created:  2018-04-07T18:12@Prek Leap (11.642600N-104.919210W)
:ID:       4cc37cda-30b3-430c-b333-d0e813668a74
:VER:      576371633.617733192
:GEO:      48P-491193-1287029-15
:BXID:     proj:RRU1-5336
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

A tool is anything that has been adapted or fashioned to extend the
the limitations of mind or body.  That covers an enormous amount of
ground and as such makes it difficult to create a model for tools and
tool use.

Jane Goodall's famous observation of a chimpanzee adapting a twig to
become a tool for extracting termites from a termite mound was a
revelation and made it clear that Man is not the only tool builder on
the planet.  And this extends beyond primates with Otters using tools
to open shellfish, and Crows and Ravens being adapt at fashioning a
number of found items to complete tasks.

But Man is still unique in the sheer number and complexity of the
tools created and uses.

The Wikipedia page for tools wasn't much help and is surprising both
how little it has to say on the subject as well as its brevity,
considering how critical tools are to our day to day survival and
success as a species.



** Table of Contents


  - Tools are an extension of the hand -- as a general rule.

  - Simply tools are more powerful and flexible than complex tools,
    but more difficult to master.

  - A Master is marked as someone who fashions customized tools as
    part of their methodology and workflow.  Painters used to now only
    make their own canvases, but their own brushes and paints as well.

  - Standardization of tools is important -- they become parts of
    larger technological cultures.

  - Specialization of tools let to a sort of Cambrian explosion of
    different types of specialized tools at the beginning of the
    Industrial revolution.  This was, in part, because specialized
    tools were easier to create using industrial processes.  It might
    also be because it allowed a larger number of less skilled people
    to be able to do work that was before the sole domain of Master
    craftsman.



  - Unix philosophy that each tool should do one task very well and
    then have a standardized system where every tool took standard
    input in the form of text, and returned standard output which
    could be used as input to another tool using a concept called
    Pipes. This created a modular toolchain that could be repurposed
    in a multitude of different ways.  Scripting languages extended
    this even further making it relatively easy to both create missing
    tools in a chain, or to aggreate toolchains into single script
    that behaved as a tool in it's own right.

  - another important advancement was standardized attatchments, so
    that a drill could use any number of different "drill" bits of
    different sizes that cold be swapped out so that one drill could
    be used to make a wide variety of different sized holes.

    - socket wrenches
    - screw drivers
    - saw blades
    - sandpaper
    - fishing rods, reels, hooks, lures, sinkers


  - standard connectors and plugs for power sources -- electrical,
    both socket and battery as well as pneumatic tools.

  - Tool Categories
    - Woodworking
    - Metalworking
    - Agriculuture
    - Cooking  
    - Warfare

  - Classes of tools
    - Cutting -> shearing, sawing
    - Pounding -> hammers, maul
    - Clasping, clamping and holding things together
    - Pincing, squeezing, crimping
    - Torque -- Twisting things
    - Chemical -- temperature, ignition
    - Produce Light
    - Move air (fans, and suction)
    - Fastening tools -- welding, riveting, nails, screws)
    - application of material flow -> pens, glue gun, 
    - Shaping tools (molds, jigs, trowels)
    - Moving tools -- shovels, rakes,
    - Information tools
    - Weaving tools
    - Guiding tools -> measures, chalk lines, t-squares, calipers
    - Opitcs -> telescope, microscope
    - Measuring -> pedometer, osciliscope
    - Sleds -> sliding things
    - Bearings ->
    - Wheeled tools -> barrows and most vehicles 
    - Excavating ->
    - Compression -> rollers
    - Pulleys
    - Gears
    - Ropes, Belts and Cables
    - Shields -> welding mask, gloves, safety glasses
    - Biological -> proteins etc
    - 
