#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Three Points of View
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Three Points of View
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww.points-of-view.org
:Created:  2018-03-19T19:09@Prek Leap (11.642600N-104.919210W)
:ID:       cceb8184-21ef-4fb0-9b5f-933e484f7e9f
:VER:      574733452.681672429
:GEO:      48P-491193-1287029-15
:BXID:     proj:FVG7-8542
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

   - Point of View
   - Level of Detail (LOD)   -> scale
   - Rate of Change (ROC)    -> velocity and direction
   - Process of Change (POC) -> as a system


*** What is a point of View?


In philosophy a point of view (POV) is a "stated matter of
consideration", taken from an individual's perspective. In this sense
a POV is entirely subjective.  But a POV can also be seen as something
that at least theoretically is objective.

In physics, and in particular, the Theory of Relativity, everything is
understood to what can be observed from a particular time and place,
or more specifically an /inertial frame of reference/.  

    https://en.wikipedia.org/wiki/Inertial_frame_of_reference

This is the point in time or space where the observer is looking and
everything that is observed is relative to that position.  If
something is close or far away, or fast or slow all depends on if the
observer is traveling at the same speed and direction as what is being
observed, which means that from that POV both the observer and the
observed are stationary relative to each other.


From wikipedia -- Propositional attitudes:

  The internal structure of a point of view may be analysed similarly
  to the concept of a propositional attitude. A propositional attitude
  is an attitude, i.e., a mental state held by an agent toward a
  proposition.
   -- https://en.wikipedia.org/wiki/Point_of_view_(philosophy)

POVs are critical to the concept of a worldview.

A World View is a mental model of the world that establishes cognitive
orientation for where you are relative to the world.  Worldviews are a
mixture of memories of things observed and experenced, assertations of
what those things are and mean, and conjecture that fill in the blanks
in that model.  If you are in a room that has a door that you have
never seen opened, you will include in your mental model the
conjecture that there is either a room leading to another room or
corrider in the building or that it is an outside wall that will take
you outside the building.  There is also the possibility that it is a
fake door that doesn't open or lead to anywhere.  Worldviews are full
of such conjectures that are constantly being updated and expanded as
more information is added to the model.

The maker of the model is always at the center of the model -- I am
here and the rest of the universe radiates out from where I am at any
given moment.

This is the case for pretty much anything animal that has a brain, as
well as groups, an ant colony has a collective worldview as much as
a group of close friends, a department in a company, a government, a
church congregation or even a religion that spans the globe.

Collective POVs are, by definition, limited to a specific way of
looking at something -- without this, communication and cooperation is
at best difficult and in many cases, impossible.

When we make rules for a group to follow, those rules first define the
POV that all members choose to observe from.  Without this, agreeing
on what is right or wrong, or even what is true or false is not
possible.

Different cultures are based in part on their relationship that that
culture has to the environment.  For someone living in a cold climate
with harsh winters and short intense summers, they will have a very
different view of nature than someone who has grown up in a mild
semi-tropical climate where the ocean is calm, and the night pleasant
and the the length of the day and night seldom differs over the year
more than an hour or so.  These POVs shape not only how you feel about
nature, but how you design a house, what kinds of clothes you wear,
the kinds of food that you will have access to and how you can cook
it.  Before refridgeration, it was, and still is common to overcook
food so that it can survive longer in the heat.  People from cold
countries or who have refridgerators don't undertand why people in the
tropics would cook a piece of meat until it approached the toughness
of shoe leather.  But this makes perfect sense if you want to cook for
many people who may eat at different times of the day.  You need
cooked food that won't go bad in severe heat in a couple of hours or
overnight.


*** POV as a cognitive tool

A POV is a useful way of understanding the world -- in fact it is
important to always consciously considered things from different
perspectives.  In colloquial english it's common to hear phrases such
as:

  - Thinking out of the box
  - Put yourself in my shoes
  - From where I am sitting....

These are all different ways of telling others or reminding yourself
that your POV is not the only way of seeing something, and that it is
useful to see things from a different perspective.

It's one things to say this, but it's another to actually do it.  How
do you think out of the box?  How do you put yourself in another
person's shoes and see the world as they do?

The answer you will get, more often than not, is to use your
imagination to create a different model based on how you imagine
someone else might see the world and put yourself at the center of it
and extrapolate how that POV would differ from yours.

This goes to the heart of empathy -- as a general rule, unless you are
unfortunate to be a sociopath or psychopath, empathy makes human
relationships possible.  In fact, the very definition of a person who
is totally disfunctional in a society is a sociopath or psychopath
which are defined as persons who can not feel empathy.

Problem solving in large part is a skill that requires a person to
understand a problem from different perspectives -- thinking out of
the box is the process of creating a mental model of something and
imagining how it looks from multiple POVs.  Pretty much every
innovation or advancement in human understanding has been the result
of this process.

*** Defining objective POVs

It would be helpful if generic POVs could be objectively defined in a
way that they could be used to understand and used by anyone without
having to resort to subjective imagination or empathy which are often
so intertwined with emotional states, cognitive limitations and biases
that they are difficult to use as general purpose empirical-based
cognitive tools.

We have identified what we believe to be three fundamentally important
types of POVs which can do just that.  And because of the importance
that POVs have in the survival of a species, and as a culture and
civilization we are putting these three POVs at the center of
understanding who we are, where we came from, how to overcome
cognitive limits and bias, problem solving, communication, conflict
resolution and cooperation.

But before we can introduce the three core POVs we will need to
introduce three concepts, each of which will be the core of a Core
POV, but also are critical understanding any one of the three POVS.
These are, Level of Detail, Rate of Change, and Process of Change.

*** Level of Detail (LOD)

https://en.wikipedia.org/wiki/Level_of_detail

LOD is a concept and technique used in 3D modeling that involves
decreasing the complexity of a model as it moves away from the viewer,
or physical POV relative to the model.

LOD is a useful way of looking at anything in terms of how much detail
can be displayed or understood.

  - we think of threats in terms of distance and the amount of detail
    you can take in -- don't fire until you see the whites of their
    eyes.  Storm clouds on the horizon, or the threat is right on top
    of us.  The farther away a threat is the more time you have to
    react, the more time to plan and model the problem because the
    farther away it is, the less information you have to deal with in
    evaluating the threat and how to react to it.  The closer it
    becomes the more information you have to content with and the less
    time you have to process all of that information.

Think of information in a physical Library in terms of LOD.  Standing
outside the building you can gauge very roughly how large a library it
is by the size of the building.  Entering the building you apprach the
catalog file drawers.  The more drawers the more books and other
material in the library.  If the library is openstack, you can then
walk into the stacks and see the library in terms of floors of
rows of shelves, step slower and you are in a single row and you can
see the different shelves of books.  Step closer and you can read the
spines of the books on the shelf in front you and you see more detail,
the type of book, cloth, papeback, library binding etc.  And you can
see the title of the book, the authors name and the publishers logo or
imprint.  You can also see roughly how big the book is, in terms of
thickness (number of pages) and the height of the book.  Take down a
book and you open to the title and copyright pages and you see more
metadata that gives you an idea of who created the book, when and
where it was published and perhaps the library catalog entry that you
would have seen in the library catalog file drawers.  Turn to the
Table of contents and you see an outline of the book and get an idea
of it's structure -- leaf through the book and you'll have an idea of
the size of the font and how much information is on each page, are
there illustations? footnotes?  Then, finally turn to the first page
of the first chapter and you've come to the highest level of detail in
the book.  When you are reading, you an no longer see the book in
lower detail -- though your mental model that you made when looking at
the book from lower LODs provides you with a means of understanding
where you are reading, relative to the whole book.

On the Internet search engines are a means of scanning a large number
of things at a lower level of detail so that you can decide which one
might be closer to what you are looking for.

*** Rate of Change (ROC)

Alvin Toffler's concept of ROC 

The concept of the Half-Life -- how long it takes for half of
something to change.

Linear growth, Steady Growth vs Exponential Growth

ROC is relative to the age of something -- time is experienced
relative to how long something is relative to how long your have
lived.  When I was a child, as many children in school do, life is
measured relative to when the next major holiday or vacation is.
Growing up in the United States in the 1970's, summer holidays lasted
from late May or early June to the Memorial Day federal holiday at the
beginning of September.  Those three months seemed to last a
lifetime.  When school let out in June, it the start of the next
school year seemed impossibly distent in the future.  Now that I am in
my mid-fifties, three months can pass in seamingly a hearbeat if your
aren't paying attention.

Complexity and Rate of Change

Size of a Territory and Rate of Change

Size of a Population and Rate of Change

Distance/LOD and Rate of Change

Scientific knowledge and Rate of Change

Limits on human ability to change and Rate of Change, 

Pace-Layers -- different things change at different rates

  Rates of change that the universe (cosmic expansion) institutions,
  language, culture, fashion.  

  Different parts of buildings change at different rates -- what Brand
  called shearing layers.

Will talk about Pace-layers in more detail in it Part XX.

