#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Surpluses
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Surpluses
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/www-surpluses.org
:Created:  2018-03-28T09:26@Prek Leap (11.642600N-104.919210W)
:ID:       b9308444-6373-4863-9048-94908f7497c3
:VER:      575476039.252820558
:GEO:      48P-491193-1287029-15
:BXID:     proj:HJO6-7124
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

Civilization is based on the assumption that it can produce
more goods and services than are required for physical
surival.  Homer would not have been able to write anything
if he was too busy trying to find food everyday, maintain
his shelter and help protect this from nature, natural
predators and other people trying to take those things from
him.

This makes it possible to increase the number of
specializations in a group to include specialties that are
indirectly related to survival, or support the complexity of
a group with a large number of specializations.

Surplus explosion since 1800 -- history of surpluses, there
were almost none before 1800, and what surpluses there were
supported a very very small elite.  Most surpluses in
history came from slavery or other class equiviliants --
serfs, peasants, indentiture, prisoners

Then the industrial revolution came along and changed
everything -- agriculture got the tractor, which changed
agriculture forever allowing a small rural population to
grow food for a largely urban mass population -- the
assembly line, palletization, containerization -- the fork
life and shipping container effectively wiped out dock
workers and workers loading trucks and railroad cars.
Electric hand tools, loaders, crains and dozers, transformed
construction -- and vastly reducing the amount of labor
needed to construct buildings.  The assembly line, and a
vast number of industrial machines reduced the labor
required before to a handful of semi-skilled people.  Life
was still hard -- but it was better.

** Table of Contents

Types of surpluses:
  - production (labor, energy)
  - goods (grain, tinned food)
  - services (unused capacity)
  - History

  - Muscle -- tools extended the hand, machines extended
    muscle.
 
  - Time -- environmental surplus.  The electric light bulb
    freed man from day-night cycles.  Insulated, heated and
    cooled buildings made it possible to extend working
    hours into times that were too cold or too hot to work.
    The time honored Siesta is dead or dieing.  Growing
    seasons are extended through the use of green houses etc.
  - [[./ww-slavery.org][Slavery]]
  - Stores
    - natural -- groundwater, oil, gas & coal, carbon
    - stockpiles -- 
    - caches -- are temporary stores used to even out
      propagation in distributed systems.
  - Capacity -- is a potential store.
    also a kind of cache, that is usually used
    to even out the difference between low and high loads on
    a system.
    - transporation
    - processing
    - transmission

Centralised and Distributed Surpluses
