#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XXVIII. Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* XXVIII. Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/28/abstract.org
  :Created:   2018-06-13T09:41@Prek Leap (11.642600N-104.919210W)
  :ID:        1095b823-7740-4ba0-97a0-f18af26e3455
  :VER:       582129736.739982704
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:JEU2-1177
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope

** TL;DR


The demographic transition

In the village married women are under the thumb if her
husband's mother.  In the city, "the mother in-law is not
around." This is an important insight that I hadn't really
considered before.

  Interview with Stewart Brand
  https://boingboing.net/2018/06/21/interview-with-stewart-brand-o.html

On the whole I have looked at the negative side of nuclear
families, but once you think about it, there are plenty of
negative things about extended families, especially lack of
mobility, and pressure to conform.  It's not the small
village that traps people, it's the extended family and the
power structures in them.  When you move to an nuclear
family model many of those presures are gone, giving people
far more freedom.  But this comes at the expense of social
support in the form of child care, and sharing domestic
chores.

---

Barry Commoner 1968  The Closing Circle — was right on
Climate, and demographic transition.

https://en.wikipedia.org/wiki/Barry_Commoner

---

Brand's Whole Earth insight can from Bucky who said that the
reason people behaved so terribly was that they thought the
world was flat and resources were infinite, but if they saw
that the world was a sphere they would realize that
resources were finite and would change their
behavior.cite:brand:2018interview


#+begin_quote
Space Vehicle Earth was so superbly well designed, equipped
and supplied as to have been able to sustain human life
aboard it for at least two million years — despite
humanity’s comprehensive ignorance which permitted a
fearfully opinionated assumption of an infinitely extensive
planar World.

— Buckminster Fuller, Earth Inc. (1972)
#+end_quote
SEE: https://web.archive.org/web/20160420125812/enthea.org/author/paul/page/24/



---

#+begin_quote
Thinking as a planet is what climate change is forcing us to
do; thinking as /a/ civilization rather than just a society
or a nation but as a civilization. People in this century
get to live in a century where humanity discovers itself as
the keeper of life now on the whole planet.  What an amazing
realization, what an amazing job, what an amazing thing to
work at how that actually works.  But all the tools are
already in place to do that.  To make it Earth Natural Park
and the city you want to live in and a society that
continues to become ever more amazing from year to year and
decade to decade in a non-destructive way.  That's going to
happen in this century.

— Stewart Brand, Interview 2018
  cite:brand:2018interview
#+end_quote
