#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XXVIII. Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* XXVIII. Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/28/abstract.org
  :Created:   2018-06-13T09:41@Prek Leap (11.642600N-104.919210W)
  :ID:        1095b823-7740-4ba0-97a0-f18af26e3455
  :VER:       582129736.739982704
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:JEU2-1177
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope

** TL;DR


The demographic transition

In the village married women are under the thumb if her
husband's mother.  In the city, "the mother in-law is not
around." This is an important insight that I hadn't really
considered before.

  Interview with Stewart Brand
  https://boingboing.net/2018/06/21/interview-with-stewart-brand-o.html

On the whole I have looked at the negative side of nuclear
families, but once you think about it, there are plenty of
negative things about extended families, especially lack of
mobility, and pressure to conform.  It's not the small
village that traps people, it's the extended family and the
power structures in them.  When you move to an nuclear
family model many of those presures are gone, giving people
far more freedom.  But this comes at the expense of social
support in the form of child care, and sharing domestic
chores.

---

Barry Commoner 1968  The Closing Circle — was right on
Climate, and demographic transition.

https://en.wikipedia.org/wiki/Barry_Commoner

---




