#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XXVIII. Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* XXVIII. Introduction
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/28/intro.org
  :Created:   2018-06-13T09:42@Prek Leap (11.642600N-104.919210W)
  :ID:        461f60c0-807c-4c35-8ac8-b5eca6659f6e
  :VER:       582129795.261059722
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:RWL0-8440
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

#+begin_quote
When a population increases, its relationship to the space it occupies
and the wealth at its disposal is alterted.  It crosses 'critical
thresholds' and at each one its enture structure is questioned afresh.

-- cite:braudel:1992civilization-capitalism-1 [[pdf:braudel:1992civilization-capitalism-1.pdf::33][p.33]]
#+end_quote

  - population since 1800 has steadily increased
  - 15th-18th centuries population doubled
  - after that doubling every 30-40 years
  - population growth is not uniformly distributed -- increase leads
    to deteriation of standard of living
  - nation-state borders are blocking natural migration during war and
    famine -- resulting in people not getting to where they are
    needed, because existing populations don't want them, even though
    they need them.

  - healthcare, public health principles that resulted from discovery
    of microscopic world, togethere with agricultural advances is good
    from the perspective of human well-being.  But these were also
    negative feeback loops that naturally kept human  population in
    check.

    This is compounded by the fact that the average lifespan has now
    doubled since 1800.

    It is only recently that education and reduction of child-hood
    mortality creates a kind of feedback loop that lowers birthrates.
    We have become Pandas who can't be bothered to reproduce.

** References


  - Braudel, F., Civilization and capitalism, 15th-18th century,
    volume i: the structure of everyday life: the limits of the
    possible (1992), : University of California Press.
    cite:braudel:1992civilization-capitalism-1
  - Ehrlich, P. R., The Population Bomb (1986), : Ballantine Books.
    cite:ehrlich:1986population-bomb 
  - Pinker, S., The better angels of our nature: why violence has
    declined (2012), : Penguin Books.
    cite:pinker:2012better-angels
  - Pinker, S., Enlightenment now: the case for reason, science,
    humanism, and progress (2018), : Viking.
    cite:pinker:2018enlightenment 
  - Meadows, D. H., Randers, J., & Meadows, D. L., Limits to growth:
    the 30-year update (2004), : Chelsea Green.
    cite:meadows:2004limits-30 
  - Economic, D. o., & Social Affairs, P. D. ., /World population
    prospects 2017 revision/ (2017).
    cite:un:2017population-prospects
  - Gritzner, C. F., The human population (global connections)
    (2009), : Chelsea House Publications.
    cite:gritzner:2009global-connection
  - Bashford, A., Global population: history, geopolitics, and life on
    earth (2014), : Columbia University Press.
    cite:bashford:2014global-population

  - Malthus, T. R., An essay on the principle of population: or, a
    view of its past and present effects on human happiness (1888), :
    Reeves \& Turner.
    cite:malthus:1888essay
