#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Ages of Man
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

* Ages of Man
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/04/ww-ages-of-man.org
:Created:  2018-04-06T12:52@Prek Leap (11.642600N-104.919210W)
:ID:       ae2e5b3b-ac13-440f-8dea-c3b2e170e920
:VER:      576266024.956080350
:GEO:      48P-491193-1287029-15
:BXID:     proj:LSS2-8520
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR
** Table of Contents


  - Ancient
    - Hesiod -- golden, silver, bronze, heroic, iron
    - Ovid -- golden, silver, bronze, iron
  - Medieval
    - Vico - ages of man, heroes, gods

-------------

  - The Axial Age -> global transition to monothesim
    cite:jaspers:1977origin-goal,wiki:2018axial-age

** Vico

The thing I like most about Vico's cyclical ages is that
it's all about entropy, but in reverse.

In the Age of Man we have all the facts, we know people's
names, when they were born, what they wrote, who they knew
and where they were buried.

But most of this information is lost by the time of the Age
of Heroes.  We only know very roughly when that person was
alive or died.  We can't be sure of their name, or indeed,
if their deeds were in fact the work of a single man, or
acts of several people that were attributed to that person.
The edges of the stories get worn down smooth, with no
ambiguity and anything that isn't required by the story has
been forgotten.  By the time we reach the Age of Gods, ther
heroes have been so worn down that they become amplified
into myths -- pure story, where the person behind it has
been evaporated like the Cheshire Cat, leaving only the
story behind.  The Age of Gods always comes last, it is the
Age we are always living in, looking back at the shadows of
the Age of Man.
     
#+begin_quote
Vico, the father of historicism, discovered that the nature
of man changes: the archaic man feels, thinks, acts in a way
completely different from modern man. In Vico's scheme of
the necessary evolution of every culture, three phases are
distinguished: the age of gods, the age of heroes, and the
age of men. The age of gods is characterized by a theocratic
government: it is anterior to any differentiation of the
various aspects of curlture such as religion, politics, or
art. The age of heroes, on the other hand, is dominated by
the conflict between classes, the heroes and the
plebeians. This age does not yet have a state; therefore,
force and violence reign. The right of the stronger is the
main ground of legitimacy. Two types of relations are
characteristic of this age: the relation between enemies who
fight each other, risking their own lives and those of their
combatants, and the relation between master and servant. The
duel, a fight between two heroes accompanied by their
servants, is the symbolic action of the heroic age. In it
the value of a person is proved, even constituted. Relations
toward wives in the age of heroes are clearly asymmetric:
women are not yet recognized as having the same human nature
as men. "Love of ease, tenderness toward children, love of
women, and desire of life" are alien to the heroes, so Vico
once sums up his view of the heroic age.

— https://ataleofatribe.blogspot.com/2011/05/vicos-age-of-heroes-and-age-of-men.html
#+end_quote

#+begin_quote
Vico believed in a cyclical philosophy of history where
human history is created by man. His term for the cyclical
nature of history was "corsi e ricorsi". Most importantly,
man and society move in parallel from barbarism to
civilization.

    As societies become more developed socially, human
    nature also develops, and both manifest their
    development in changes in language, myth, folklore,
    economy, etc.; in short, social change produces cultural
    change.

Vico is therefore using an original organic idea that
culture is a system of socially produced and structured
elements.[1] Hence, knowledge of any society comes from the
social structure of that society, explicable, therefore,
only in terms of its own language. As such, one may find a
dialectical relationship between language, knowledge and
social structure.[1]

Relying on a complex etymology, Vico argues in the Scienza
Nuova that civilization develops in a recurring cycle
(ricorso) of three ages: the divine, the heroic, and the
human. Each age exhibits distinct political and social
features and can be characterized by master tropes or
figures of language. The giganti of the divine age rely on
metaphor to compare, and thus comprehend, human and natural
phenomena. In the heroic age, metonymy and synecdoche
support the development of feudal or monarchic institutions
embodied by idealized figures. The final age is
characterized by popular democracy and reflection via irony;
in this epoch, the rise of rationality leads to barbarie
della reflessione or barbarism of reflection, and
civilization descends once more into the poetic era. Taken
together, the recurring cycle of three ages – common to
every nation – constitutes for Vico a storia ideale eterna
or ideal eternal history. Therefore, it can be said that all
history is the history of the rise and fall of
civilizations, for which Vico provides evidence (up until,
and including the Graeco-Roman historians).

— cite:wiki:2018the-new-science
#+end_quote

** References

  - Wikipedia, , /Ages of man --- wikipedia, the free
    encyclopedia/ (2018).
    cite:wiki:2018ages-of-man
  - Wikipedia, , /Axial age --- wikipedia, the free encyclopedia/ (2018).
    cite:wiki:2018axial-age
  - Jaspers, K., The origin and goal of history (1977), :
    Greenwood Press Reprint.  cite:jaspers:1977origin-goal

