#   -*- mode: org; fill-column: 60 -*-

#+TITLE: III. Frameworks Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] | [[[./index.org][index]]]

* III. Frameworks Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-intro-vol-2.org
:Created:  2018-04-11T18:17@Prek Leap (11.642600N-104.919210W)
:ID:       c09d0ee2-7ca0-41ac-a338-8d2a8bc4254b
:VER:      576717511.853335291
:GEO:      48P-491193-1287029-15
:BXID:     proj:APP5-4181
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

There are few absolutes.  And even when there are, even
those are subject to any number of ways of looking and
understanding them depending on when, where and how they are
observed or measured.

In too many cases, we form opinions, make judgements or jump
to conclusions on the basis of a specific context in which
we observe something.  It's hard enough to get through the
day and manage to make measured, rational choices in the
little time we have from a single context.  There just isn't
time to take in more than one or two different
perspectives.  But for things that stick around long enough
to be observed repeatedly over time, the accumulation of
experience of observing from different perspectives gives us
an increasingly complex and detailed understanding of the
world around us.  The familiar is something that is built up
over time, the unfamiliar is too new to yet be trusted or
fully understood.

We need to build up a collection of tools for understanding
how the world works and is organized as a means of
understanding, making decisions and building a civilization.

This Volume is all about building up a cognitive toolbox of
techniques that can be used to build a /familiar/
civilization that can be looked at from every possible angle
in contexts that are natural and understandable.  And then
once it is built continue to use our full arsenal of tools
to monitor, measure and mange it properly.

*** Point of Views

We start with four concepts that are in many respects the
most important for our entire undertaking, it's as simple as
the R.E.M. song, /Stand/:

#+begin_verse
Your feet are going to be on the ground
Your head is there to move you around
If wishes were trees, the trees would be falling
Listen to reason, season is calling

Stand in the place where you live
Now face north
Think about direction
Wonder why you haven't before

Now stand in the place where you work
Now face west
Think about the place where you live
Wonder why you haven't before

If wishes were trees, the trees would be falling
Listen to reason, reason is calling
Your feet are going to be on the ground
Your head is there to move you around

— Stand | Green, R.E.M (1988)
#+end_verse

We start from what we can observe from where we are
standing, this is perspective, or your /Point of View/
(POV).  Work out what direction you are looking in, and how
far or close something is relative to where you are
standing.  We call this Level of Detail (LOD).  Now watch
for things changing.  Get a feel for how fast or slow things
are changing relative to the steady beat of your heart where
you are standing.  Use a metronome, stopwatch or even a
calendar if it will help you along.  This is the /Rate of
Change/ (ROC).  Now comes the one that has become difficult
for some people, but is how things really are.  Understand
that everything around you, near and far, fast and slow are
in a constant complex dance of change.  The past doesn't
recede behind you and the future doesn't stretch off before
you.  Everything is right where you are, where everything is
in the process of becoming something else.  The past is not
gone, it's still right here in the present, but is changed
as entropy wears things down, cools things off and scatters
everything to the wind.  This is the Process of Change
(POC).

We can understand the world using these three different
Points of Views, as LOD -- how close or far something is.
Or as ROC -- how fast or slow things change and how fast or
slow that change propagates towards or away from you.  And
finally how all of these things are all happening at the
same time, near and far, hot and cold, slow and fast as a
single relentless irreversible process.  You can't unstir
milk poured into a cup of coffee and you can never stand in
the same river twice.

Save ourselves, this is how pretty much all creatures on our
plant see and experience the world.  We are not wrong and
they are also right.  But we are alone in having the
cognitive ability to understand goal oriented behavior.  We
can see that one thing leads to another which leads to
another which causes something to happen.  Your dog can't do
that.  Our close cousins the Chimpanzee's can't do that.
And that small thing has made possible everything Sapiens
(the sub species of Man that we belong to) possible.  But it
also leads to the illusion that time is a road with a
beginning, middle and end, with us at any given time in the
walking in the middle of the road towards a endlessly
receding horizon.

Understanding what we observe in the world as a different
Points of View with different combinations of LOD, ROC, and
LOC are the footings, or pilings sunk deep in the earth on
which we can build the walls of our foundations.

  *EXAMPLES*

*** Dualities

Nature is awash in dualities.  In 1801 Thomas Young
performed an experient that demonstrated that light has a
/wave-particle/ duality.  Light, as well as electrons and
even molecules can be observed as a wave, or it can be
observed as a series of particles, but you can only measure
it as one or the other.  Observing as a wave means you can't
observe it as a particle and vice versa.  Richard Feynman
called it "a phenomenon which is impossible […] to explain
in any classical way, and which has in it the heart of
quantum mechanics. In reality, it contains the only mystery
[of quantum mechanics]."[fn:1]

Dualities can be found almost everywhere you look, from the
Taoist 陰陽(ying-yang) ☯ duality[fn:2] of dualistic-monism
where condradictory opposites such as dark-bright,
good-evil, negative-positive, fire-water intertangle and can
exist as a single unity existing as both contradictory
things simutaneousely.  But these contradictions can also be
thought of as a spectrum with each opposite existing on each
extreme end from the other.  But as a spectrum, there is no
place where one becomes the other.  In formulating his
theory of evolution, Darwin disliked the concept of a
species.  After decades of careful observation of barnacles
and other living things he understood that there rather than
life being made up of different species, there were only a
near infinite number of variations from one individual to
the next.  Where does one draw the line and call one
variation one species, and another variation a different
one?

If this is still too abstract to seem of much practical use
we can turn to Arthur Koestler's concept of the holon which
he introduced in his book, The ghost in the machine.
cite:koestler:1989ghost  A holon is a struture that has a
dual nature in which every part can be seen as a single
whole, as well as a part of a larger structure.  The human
heart is a single whole structure which is also a part of
the larger human body.  Looking into a holon you see things
as wholes, but looking out, they are seen as parts.  A tree
is a whole, which is also part of a larger forrest.  A car
battery is a whole, which is part of a larger automobile,
which might in turn be a part of a larger fleet of cars
owned by a company.  Civilizations and Ecosystems are large
scale holarchies made up of countless overlapping and nested
holonic structures.

  *EXAMPLES*

*** Map-Territory

Another important duality, which the Map-Territory
relationship.  A map is a simplified representation of a
larger territory.  For example, a territory might be a city,
which has maps made of it showing streets, trains lines,
buildings, monuments and rivers.  Topographic maps represent
the three-dimensional geography of city, showing hills and
depressions as well as geological and man made features.

But a map is always a subset of a territory, the more
information that is included in a map, the less useful it
becomes.  So an abstract representation of the commuter
subway system for the city of Osaka is very useful even
though it's a poor means of showing the spatial
realtionships and distances between stations.  While a
detailed city map with roads and train stations is a poor
means of understanding how to navigate the train system,
there is no way of seeing the train system as a whole in the
clutter of the territory.

A map is a territory that is seen from far away where you
can't see as much detail as when you are close.  In this
sense it is an epression of the Level of Detail Point of
View (LOD POV).

Taken to an extreme, a map that has been made at a scale of
1:1 is perfectly detailed, and perfectly useless.

#+begin_quote
“In this empire, the art of cartography was taken to such a
peak of perfection that the map of a single province took up
an entire city and the map of the empire, an entire
province. In time, these oversize maps outlived their
usefulness and the college of cartographers drew a map of
the empire equal in format to the empire itself, coinciding
with it point by point. The following generations, less
obsessed with the study of cartography, decided that this
overblown map was useless and somewhat impiously abandoned
it to the tender mercies of the sun and seasons. There are
still some remains of this map in the western desert, though
in very poor shape, the abode of beasts and beggars. No
other traces of the geographical disciplines are to be seen
throughout the land.”

— Jorge Luis Borges, /A Universal History of Infamy/, 1946
#+end_quote

The map-territory is different from a holon duality in that
a map is not a part of a whole, but a representation of a
part or aspect of a whole.  This is a useful tool which can
be seen in the Data-Metadata duality.

Metadata is ostensibly, data that describes data.  In this
sense it is type of  map of the data.  But metadata can also
be seen as a subset of the data and like the Map-Territory
relationship is another expession of the Level of Detail
Point of View (LOD POV).  But in many cases, metadata can be
treated as data in its own right in some contexts and
metadata in another.  A card catalog of metadata describing
books in a library is both a collection of data, but also
can be seen as a data describing individual volumes in the
library.  There is no useful distinction in between the two,
only the context of how it is used detemines the a
distinction.

From considering dualities we can consider the processes and
mechanisms that determine how things become something else.
We call these /generators/

  *EXAMPLES*

*** Generators

Generators are extremely important to understanding POC as a
process of the evolution of everything from ants, to
cathedrals and social networks.  Complex systems which
encompus any number of dualistic natures are inheriently
unpredictible in the instance, but predictible in the
aggregate.  In mathematics the Possion distribution states
that if you create an equal grid of a hundred squares and
then drop pebbles from above onto the grid, with an equal
chance of any one pebble landing on any one grid, that you
can reliably predict how squares will have no pebbles, how
many will have three pebbles, how many will have 10 pebbles
etc.  But there is no way of knowing which squares will
contain which number of pebbles in advance.

Generators can be thought of as machines that drop those
pebbles on the grid.  You know what the grid looks like, the
preconditions, and you know the characteristics of the
pebbles and understand when it's complete you won't know
what it will look like, but you'll have a very clear idea
that it will work the way it's needed, so long as what you
need is that specific distribution of pebbles on a grid of a
specific size.  In other words, the distribution is
inevitble but the exact arrangement is not.

The important thing to understand about this process is that
it is far better than a top down, command and control
approach to design, finance and construction because it will
make allowances for variations that weren't taken into
account in the initial planning and development stage.  It
will adapt to those unknowns and become closer to what you
need, rather than the preconcieved notion of what you
thought you wanted when you began the exercise.

In this way, generators are not determinisitic -- they are
not plans or blueprints that specify exactly how something
will look or be constructed -- they only provide the basic
list of ingrediants and the desired features and
characteristics of what is to be made and ensure that the
process determines that it will meet the goals of the
project, rather than the initial planning of the project
that was done without full knowledge of what would be needed
to complete it.  Top down planning and construction is blind
and largely ego driven.  Bottom up design and construction
is adaptive, collaborative and responsive to change and
needs.

  *EXAMPLES*

*** Scaffolds

Now we turn to the enormous topic of scaffolds which will
make up the bulk of this volume.  A scaffold is a structure
that is put into place to provide support for a structure
that is under construction until that new structure can
stand on it's own.  Some scaffolds, such as bamboo or metal
scaffolds which are errected on a construction site are
removed at the end of the project.  But most scaffolds for
information structures remain after construction is
complete, even though they can not be seen, or may never
even be referred to afterwards.  We will examine six broad
types of scaffolds that will be important to building
civilizations, hierarchical-entity models, ontologies,
pace-layers, succession layers and stacks, goldilocks
thresholds or zones, and finally the division between hard,
wet and soft.

*** Entity Models

Entity models have their roots in a rather dry document
called /Functional Requirements for Bibliographic Records/
which is commonly called FRBR (pronounced furbur).  The
problem that FRBR was meant to solve was the profusion of
variations, editions, print runs etc of individual works.  A
work like Charles Dicken's /A Christmas Carol/ has been
reprinted by hundreds of different publishers, in different
formats with different typographical design, illustrations,
annotations, line-numbers, running commentary etc. Add to
this that the novella has been translated into hundreds of
different languages and has been turned into radio plays,
has audio books editions which are recordings of a person
reading the book, television and full length movie
adaptations and so on and so forth. But the story, and in
most cases the text and arrangment of words is the same.
How can you catalog and organize this great mass of
variations on the same story that Charles Dickens wrote?

The FRBR model does this by breaking up all variations into
a hierarchy of what they call /entities/.  The top most
entity is a work, which is a concept that represents the
work and all it's incarnations as a whole.  This work then
has multiple /expressions/ of that work.  An expression is
the arrangement of words or other media in a specific order.
An expression might be Dicken's original text of the work.
There are some who say that a translation into another
language constitutes a new work, and others that the
translation is a separate expression of the same work.  I
support the latter.  Each expression is then divided into
different /manifestations/ of the book.  A manifestation is
a specific formating and design of an expression.  There
might be a hard cover manifesetion, a paperback
manifestation, a large print version, a version with
illustrations and another without.  Again, there is
disagreement on the specifics of how these are determined
but the general principle still holds.  Finally, copies or
instances of a manifestation are made.  This might be a copy
of the paperback book sitting on your desk, or it might be a
digital copy of an epub file in a ebook reader.

The Entity-model of concept, expression, manifestation and
instance can be applied to a wide number of different
applications and is an imporant means of organizing any
concept or design that is replicated in many different forms
and formats by different groups for different purposes.

  *EXAMPLES*

*** Ontologies

In information science an ontology is a kind of knowledge
graph (also known as a thesaurus) that provides a formal
naming scheme for terms for concepts that defines those
terms by their relationship to other terms.

A dictionary defines terms using words, so that a duck might
be defined as "Any bird of the subfamily Anatin[ae], family
Anatid[ae]."

In a thesaurus a duck would be defined relative to broader,
narrower and related terms.  In the following example:

  | TT | Top Term       |
  | BT | Broader Term   |
  | PT | Preferred Term |
  | UF | USED For       |
  | NT | Narrower Term  |

#+begin_example
  - TT Bird
    - BT Water Fowl 
    - BT Anatin[ae] (Subfamily), Anatid[ae] (Family)
      - PT Duck
      - UF duke, doke (Old English)
        - NT River Ducks, Sea Ducks
        - NT Common Domestic Duck (Anas boschas)
#+end_example

An ontology using relationships can easily be represented as
a directed graph and has the added advantage of being
machine understandable.  This can be achieved by using XXX
notation to represent each relationship as a triple that has
a object, subject and predicate.

#+begin_example

#+end_example


Such a graph can be imported into a Graph Database and used
by machine learning software applications.

  *EXAMPLES*

*** Pace-Layers

The Pace-Layer model was first developed by Stewart Brand as
a means of showing how different layers in civilization
changed at different rates of
change.cite:brand:2000clock-long-now The concept was a
generalization of the idea in a previous book
cite:brand:1995how-buildings that buildings are made up of
different layers which change, maintained or rennovated at
different rates of change, which he called /shearing
layers/.

Brand used a six layer model:

  | Fashion        | The fastest and most erratic scale, measured in minutes, hours and days |
  | Commerce       |                                                                         |
  | Infrastructure |                                                                         |
  | Governance     |                                                                         |
  | Culture        | Slowest Human Scales in hundreds and thousands of years                 |
  | Nature         | Slowest, working at evolutionary and geological times scales            |


The pace-layer model is one of the most powerful scaffolds
that we will use in building and manageing human societies
and civilizations.  Our pace-layer model expands on Brand's
model as we will later see in A Pace-Layer Pattern Language
(APPL) in a later volume.

  *EXAMPLES*

*** Succession Stages

  *EXAMPLES*

*** Goldilocks Thresholds

  *EXAMPLES*

*** Hard Soft Wet

  *EXAMPLES*

*** Specializations

** References 

  - Brand, S., How buildings learn: what happens after
    they’re built (1995), : Penguin Books.
    cite:brand:1995how-buildings
  - Brand, S., Clock of the long now: time and
    responsibility: the ideas behind the world's slowest
    computer (2000), : Basic Books.
    cite:brand:2000clock-long-now
  - Brand, S., Whole Earth Discipline (2010), : Penguin Books.
    cite:brand:2010whole-earth-discipline
  - Koestler, A., The ghost in the machine (1989), : Arkama
    Books. 
    cite:koestler:1989ghost
  - Turner, F., From counterculture to cyberculture: stewart
    brand, the whole earth network, and the rise of digital
    utopianism (2006), : University of Chicago Press.
    cite:turner:2006counterculture-cyberculture

* Footnotes

[fn:2] https://www.fileformat.info/info/unicode/char/262f/index.htm

[fn:1]  Feynman, Richard P.; Robert B. Leighton; Matthew
Sands (1965). The Feynman Lectures on Physics,
Vol. 3. Addison-Wesley. pp. 1.1–1.8. ISBN 0201021188.
