#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Polis
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Polis
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-polis.org
:Created:  2018-04-05T08:19@Prek Leap (11.642600N-104.919210W)
:ID:       6fb9e83c-4ab9-4857-afe3-5b0900daa8c2
:VER:      576163214.745875692
:GEO:      48P-491193-1287029-15
:BXID:     proj:YRY1-0838
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

The way that we organize information, matter and energy is
how we organize power.

We have already discussed how the concept of civilization is
rooted in the concept of cities, the polis, from where we
also get the word politics.

Now that we have a clear understanding of what a citizen is,
we can move from being a migratory or wandering
hunter-gatherer to a sedentary urbanite.  A band of
hunter-gatherers resolved conflicts by either moving or
fighting.  Urban Man makes moving difficult without
significant disruption and social and material loss.  So
urban Man needed to find ways of non-violently resolving
conflicts between neighbors -- from where we get words like
negotiation, which come from the word /negotium/, the
opposite of /otium/ which is a time of quiet contemplation.
Negotium encompused the social, the day to day business and
intercourse with her neighbors.

We need a model for the concept of polis as the atomic unit
of civilization as a physical and social fabric that makes
politics and commerce possible.

We will then discuss the relationship between the urban and
rural, as an economic relationship that creates tensions
because of the inequality between the two sides in terms of
wealth (urban areas have a higher concentration of wealth),
access to and quality of services, which we will see can be
understood as a problem of propagation of information,
wealth and logistics.

Finally we will look at mechanisms for how all of these
problems can be solved and how they have been solved in the
past.

In the end, as we have seen over and over, is that the
limiting factor for any of these solutions is scale.  Once
we move to scales larger than humans are designed for, we
see systemic problems emerge that can never be resolved
because the solutions simply don't scale.

** Table of Contents


HARD
  - rural, urban, cosmopolitan -> 
  - ancient greek city-states
  - town-gown
    - polis and nones
  - monastic estates - /familia intus/ & /familia foris/
    cite:horn:1979plan v1.p341
  - [[./ww-settlement-hierarchies.org][Settlement Hierarchies]]
  - Agora, Stoa & Pynx cite:sennett:2016pynx
  - Neighborhood and identity cite:hubka:1984big-house
WET
  - Social Structures
    - Nature
      - Mates
      - Hives, Colonies
      - Packs
      - Herds, Flocks, Schools 
    - Kinship
      - mated pair = couple - economic unit
      - pair + children = nuclear family
      - pair + children, and parents = extended family
      - band = base hunter-gather unit, human equiv of a pack
      - clan = band that are made up of members who are blood
        relations.
      - Barkota (polynesia)
    - Polities
      - chiefdom
      - tribe
      - nation
      - city-state
      - state
      - nation-state

      ---
      SEE: https://www.eurozine.com/change-course-human-history/

      - seasonal polities -> harvest, birthing (as in
        sheep), political meetings.
      - hunting parties -> adhoc single purpose temporary groups
      - choose leaders who don't want the job, there is
        something wrong with the ones who want the job.
      - adhoc supply/production chains
      - combine nomadism, with sedantary systems

      the idea here is that you start and organize over the
      network long before you physically get together to
      work, and you continue to work after you return home.

      keeping multiple residences is not a bad idea everyone
      has a primary residence, but the domus will keep group
      residences in urban centers (or urban domus will keep
      rural residences) that can be used by members.

      a domus will always maintain a third of residential
      capacity for visting students, apprentices, and people
      who have come to work on a project together.

      people will maintain different roles in different
      locations, and as in some traditional societies even
      have different names in different roles.

      minimize liquid currencies whenever possible. money
      for many stops being a flexible means to an end and
      becomes an end in its own right.

      People will change the patterns of moving or staying
      in different stages of their lives.

      I don't yet agree that the roots of inequality are
      from small groups (say in family structures) -- the
      smaller the group, the smaller the number of
      specializations and specializations are a better
      candidate for fostering inequality and subjugation.

      Gender inequality and repression still puzzles me.  I
      don't understand the roots -- other than the mismatch
      in physical size, and the fact that the person who
      creates the wealth in the family is typically the
      person with the most power.  Is that all there is too
      it?

    - Legitimacy -> claim to power
      - Sovereignty
      - Claim
        - Heredity
        - Divine (monarch or theocratic),
        - Populist or Fascist
        - Ideological (rule by isms)
        - Elected Representitive
      - Mandate
        - Force of Arms      -> least flexible
        - Populist Mandate   
        - Democratic Mandate -> most flexible
    - Corporate Structures
      - Cooperatives -> partnerships, clubs, etc
      - Corporations -> virtual person
      - States       -> sovereign groups

SOFT

Anything on paper, rules, proceedures, constitutions etc are
in essence software that use human agents to execute their
code -- code is written in a special language designed to be
unambigious in meaning and intent of how it is to be executed.

    - Branches of State
      - Executive
      - Judicial
      - Legislative
      - Journalistic
    - State Layers
      - Office Holders
      - Departments & Ministries
      - Bureaucratic -> Mandarins
    - Contractual
      - Declarations and Compacts
      - Constitutions
      - Laws

---------

  - Proposed -> to be divided between w&w, appl, primer and
    hoard. 

    The goal here is to create the most flexible structure
    possible.

    - Person     -> Individual person (person is member of
                    Mankind), corporation. Has rights, but
                    no liability, equity or group membership
    - Citizen    -> Person who has rights, obligations and
                    equity in group.
    - Ward       -> Persons lacking cognitive ability for self
                    determination.
    - Union      -> legal collective between 2 or more Persons
    - Domus      -> Household/Workshop (typically a
                    corporate person) no larger than 40 Persons.
    - Guild      -> Corporate person, who can not hold
                    property, take part in poltical
                    activities but may have powers such as 
                    judicial, or security or credidation.
    - [[./ww-polis-nomes.org][Polis]]      -> (polis + nomes)
    - Federation -> group of polis and or guilds -- may be
                    permanent or for a project.  Do not have
                    same rights as a Polis (can not control 
                    territory) or other functions
                    that super powers hold today.

    - Where possible, all software should be made machine
      understandable and single focus machine executible
      software applications that can't be tampered with (hey
      blockchain) used to replace human agents.

      In the *hoard* this is will be called MIDDLE, which
      makes up all of the automation that links all of the
      Hard and Wet parts of Polis together.

      To paraphrase Einstein, MIDDLE has to be as complicated
      as it needs to be but not more.

      MIDDLE is hardware (machines) and Software (cognitive
      and clockwork) that is meant to replace middlemen in
      the system, which reduces inefficiencies and
      opportunities for rent seeking, replaces slavery with
      sub-cognitive AI and clockwork processes.  The MIDDLE
      is especially designed to provide machine-cog that
      manages processes that are too fast and small or large
      and slow for humans to be able to do themselves.


** Sovereign Structures

Corporation + sovereignty = state

Sovereignty is typically justified by supernatural 

It is common for royals to claim that they hold their
positions by the authority of a deity, who backs up their
position with the force of that deity (in this life or the
next) -- with the implication that if you do not recognize
their authority you are challenging God.

This has morphed into moving authority from a deity to an
ethnic group with squatter rights.  That if you go against
the authority that lays claim to representing that ethnic,
religious or cultural group you are attacking everyone in
that group.

The enlightenment morphed this still further to define a
nation as a collection of any group with a shared national
identity that can participate in elections that choose
leaders.

In all cases, the benifits of property and wealth controlled
(owned) by a group self-propagates to the leaders.  This
self-propagation is an important concept because if people
are considered property, then the wealth that they produce
is owned by those who have control or claim ownership.

The reality of sovereignty is that the only thing that makes
it possible is if you can fight off any outsiders who want
to take it away from you.

This has morphed into the modern nation-state system where
instead of going to war, states support the claim of
sovereignty of their neighbors so long as they reciprocate.

The drawback of this system is that since WWII state borders
have largely been frozen which in recent years has been
coupled with a tendency of states to restrict migration of
people over state borders.  There are any number of
scenarios where this breaks down.  In the case of famine,
war or other calamities, people get dislocated.  In many
cases it that happens they are now trapped where they are
and face great hardship and often death.

The nation-state system could collapse if there is a
/perfect-storm/ of calamities that trigger mass migration of
people that will overwhelm state borders.  This is now
happening on a small scale in Europe with EU countries
stopping people from the middle east and north africa from
migrating to their countries.

Long term, if the EU doesn't actively work to solve those
problems, they will be responsible for the deaths of the
people who could have survived by going to the EU.

In the modern nation-state system nations are responsible
and liable for the well being of their neighbors.  When they
aren't, they are putting the peaceful nation-state system in
danger.


** References

  - Downing, F., & Hubka, T. C., Diagramming: a visual
    language, Perspectives in Vernacular Architecture, 2(),
    44–52 (1986).
    http://dx.doi.org/10.2307/3514315publisherJSTOR
    cite:downing:1986diagramming
  - Horn, W., Born, E., Jones, C. W., & Dupree, A. H., The
    plan of st. gall: a study of the architecture \& economy
    of, \& life in a paradigmatic carolingian monastery
    (1979), : University of California Press Berkeley, Los
    Angeles and London.
    cite:horn:1979plan v1.p341
  - Hubka, T., Big house, little house, back house, barn:
    the connected farm buildings of new england., , (),
    (1984).
    cite:hubka:1984big-house
  - Wikipedia, , /Settlement hierarchy --- wikipedia, the
    free encyclopedia/ (2018).
    cite:wiki:2018settlement-hierarchy
  - Sennett, R., The pnyx and the agora, In (Eds.),
    Designing Politics: the limits of design (pp. 6–9)
    (2016). : London School of Economics and Political
    Science.
    cite:sennett:2016pynx
