#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Succession
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] | [[[./index.org][index]]]

* Succession
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-succession.org
:Created:  2018-04-17T12:28@Prek Leap (11.642600N-104.919210W)
:ID:       12b23860-380a-454a-bd52-51068e214e20
:VER:      577214948.262552646
:GEO:      48P-491193-1287029-15
:BXID:     proj:HJY2-4437
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

We have already introduced the Successon Model, as one of
our core Scaffolds but it's important to start introducing
some example Succession implementations that could be used in
building civilizations.

The succession models here are very much first drafts and
will change radically as we learn more and work continues.

The examples used here are NOT normative.  Succession models
will be defined as Succession Patterns in APPL which will be
adapted for use in Hoards to generate Primers.

This Part is meant to be a practicum in taking the
principles and sructures that we have explored thus far and
see how they can be used to create actual Succession models
that could be deployed.

As the Succession Patterns are developed and changed, these
examples will be updated as well.  Please refer to the
succession patterns in the latest version of APPL 

** Table of Contents

*** Thresholds
We've already explained what succession models are and how
tey work.  Now we need to put them into use, and how to
understand their role in human civilization

 - 00. Inevitibility
   - uncertainty -> change is certain, outcome is not
 - 00. Phase Changes  -> from one state to another
 - 00. Tipping-Point -> trigger cascades
*** Ecological
 - Primary, secondary
   SEE:  [[https://en.wikipedia.org/wiki/Ecological_succession#cite_note-southshorejournal.org-3][Ecological Successsion]] | Wikipedia
   - Primary: Colonization, pioneer species
   - disturbance -> pioneer -> bushes, scrub -> faster
     growing trees shade out bushes -> larger longer
     lived trees shade out fast growin acacia and
     evergreen
   - cyclic succession -> disturbance, disease, fire, man
     triggers the cycle again.

   - a savannah is a stage between grass/bushes and
     longer growing trees that is stablized by sparse
     disturbance by megafauna.
*** Civilization
  - Survival: Pre-Tool
  - Tool
  - Machine
    - Clockwork
    - Electronic
    - Electric
  - Cognitive (includes bio and nano)  
  - Education
  - Stages of life
  - Governance
  - Domus & Shops
  - Guilds
*** Habitats
  - Earth
  - Mars
    - Human Settlement
      - beach head
      - base
      - colony
      - civilization
        - dependent
        - independent
    - Teraforming 
  - Habitats & Planetoids
** References

  - Smith, S., & Mark, S., The historical roots of the
    nature conservancy in the northwest indiana/chicagoland
    region: from science to preservation, South Shore
    Journal, 3(), (2009).
    cite:smith:2009historical
  - Walker, L. R., & Moral, R. d., Primary succession and
    ecosystem rehabilitation (2003), : Cambridge University
    Press.
    cite:walker:2003primary-succession 
  - West, D. C., Shugart, H. H., Botkin, D. B., Darrell
    C. West, H. H. S., & Botkin, D. B., Forest succession:
    concepts and application (1981), : Springer-Verlag New
    York.
    cite:west:1981forest-succession 

