#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Surpluses
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Surpluses
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/www-surpluses.org
:Created:  2018-03-28T09:26@Prek Leap (11.642600N-104.919210W)
:ID:       b9308444-6373-4863-9048-94908f7497c3
:VER:      575476039.252820558
:GEO:      48P-491193-1287029-15
:BXID:     proj:HJO6-7124
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

Civilization is based on the assumption that it can produce
more goods and services than are required for physical
surival.  Homer would not have been able to write anything
if he was too busy trying to find food everyday, maintain
his shelter and help protect this from nature, natural
predators and other people trying to take those things from
him.

This makes it possible to increase the number of
specializations in a group to include specialties that are
indirectly related to survival, or support the complexity of
a group with a large number of specializations.

Surplus explosion since 1800 -- history of surpluses, there
were almost none before 1800, and what surpluses there were
supported a very very small elite.  Most surpluses in
history came from slavery or other class equiviliants --
serfs, peasants, indentiture, prisoners

Then the industrial revolution came along and changed
everything -- agriculture got the tractor, which changed
agriculture forever allowing a small rural population to
grow food for a largely urban mass population -- the
assembly line, palletization, containerization -- the fork
life and shipping container effectively wiped out dock
workers and workers loading trucks and railroad cars.
Electric hand tools, loaders, crains and dozers, transformed
construction -- and vastly reducing the amount of labor
needed to construct buildings.  The assembly line, and a
vast number of industrial machines reduced the labor
required before to a handful of semi-skilled people.  Life
was still hard -- but it was better.

** Table of Contents

  - Potential & Kinetic Stores
    - Stockpiled -> subject to entropy, has a shelf life
    - Potential  -> surplus capacity
    - kinetic    -> on the hoof, battery charge, in-transit
  - Types of Supluses:
    - Production
      - Sun shines, Wind blows, Water flows, Gravity pulls
      - Chemical -> Fire burns
      - Atomic & Nuclear
      - Animal -> burden, leveraging their natures
      - Plant  -> leverging their natures
      - [[./ww-slavery.org][Slavery]]
      - Machine clockwork
      - Machine cognition
      - Time
        - speed (communication and transporation)
        - light (extra time from electric light) 
    - Stores, Reserves & Stockpiles
      - goods (grain, tinned food)
      - services (unused capacity)
    - Caches (network)
    - Capacity

** Capacity

#+begin_quote
I recognize that idea is jarring – that “my property” would
be free for the taking just because I was not using it. But
do you recognize why the idea is jarring? The assumption
that fuels the dissonance about property “free for the
taking” is that the taken property is exhaustible. I may not
be using my car at the moment, but that doesn’t mean you
should have the right to take it since your use of my car
will, to some degree, deplete the property I have. Cars are
exhaustible resources. Spectrum is not. When I use a bit of
spectrum at a particular moment in time, that spectrum is
just as good after I’m finished as it was before. My use in
no way exhausts the resource. And more important, when
spectrum is not used, its value as a resource is not
saved. Unused spectrum, like an empty seat on an airplane,
is a resource that is lost forever.

— cite:lessig:2001future-of-ideas
#+end_quote

This is a good argument for potential capacity.  However I
thought that it was a bit odd to use spectrum as an example
because it is not an infinite resource, it has a maximum
carrying capacity -- unlike network bandwidth, which can be
increased by adding more network cables and improving
technology to increase carrying capacity.

It's always more efficient to use something at close to
maximum carrying capacity -- in many cases, like a computer,
running a small load on the machine uses the same
electricity as running it at full capacity, and does not
shorten it's lifespan.  So the heavier the load, the lower
the cost of the server over its lifetime.

