#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XXIII. Archetypes Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* XXIII. Archetypes Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/23/abstract.org
  :Created:   2018-06-04T17:58@Prek Leap (11.642600N-104.919210W)
  :ID:        1b17cf18-ef85-4ecc-b91b-ef01f7f1df0f
  :VER:       581381954.792324620
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:TIF6-4036
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope

Jung, of course but need to broaden this out -- 

Golden Bough,

Lévi-Strauss, 

Hero with a thousand faces,

 - [X] Roland Barthes' Mythologies
 - [ ] Caillois, Roger. Le Mythe et l'homme. 1938. Paris: Gallimard, 1987.
 - [X] Cassirer, Ernst. Language and Myth. Trans. Susanne K. Langer. New York: Dover, 1946.
 - [ ] Chase, Richard. The Quest for Myth. Baton Rouge: Louisiana State UP, 1949.
 - [X] Coupe, Laurence. Myth. (The New Critical Idiom). London: Routledge, 1997.*
 - [ ] Csapo, Eric. Theories of Mythology. (Ancient Culture). Oxford: Blackwell, 2004.
 - [X] Eliade, Mircea. Myth and Reality. Trans. Willard R. Trask. New York: Harper, 1963.
 - [X] Fromm, Erich. The Forgotten Language: An Introduction to an Understanding of Dreams, Fairy Tales and Myths. New York, 1951.
 - [X] Frye, Northrop. Anatomy of Criticism: Four Essays. Princeton (NJ): Princeton UP, 1957.*
 - [X] Jung, C. G., and C. Kerényi. Introduction to a Science of Mythology. Trans. R. F. C. Hull. London, 1951.
 - [ ] Lévi-Strauss, Claude. The Raw and the Cooked: Introduction to a Science of Mythology. Vol. 1. Trans. John and Doreen Weightman. New York: Harper and Row, 1969; London: Cape, 1970.


** TL;DR

