#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XXIII. Archetypes Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* XXIII. Archetypes Introduction
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/23/intro.org
  :Created:   2018-06-04T17:58@Prek Leap (11.642600N-104.919210W)
  :ID:        8d63b7f9-5933-4b11-b467-153e93716f80
  :VER:       581381972.297308310
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:SKC1-4141
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

#+begin_quote
My views about the 'archaic remnants', which I call
'archetypes' or 'primordial images,' have been constantly
criticized by people who lack a sufficient knowledge of the
psychology of dreams and of mythology. The term 'archetype'
is often misunderstood as meaning certain definite
mythological images or motifs, but these are nothing more
than conscious representations. Such variable
representations cannot be inherited. The archetype is a
tendency to form such representations of a
motif—representations that can vary a great deal in detail
without losing their basic pattern.

— Carl Jung, Man and His Symbols
  cite:carl:1968man-symbols
#+end_quote


** References

  - Barthes, R., & Lavers, A., Mythologies (1972), : Farrar,
    Straus and Giroux.
    cite:barthes1972mythologies
  - Cassirer, E., Language and myth (1953), : Dover Publications.
    cite:cassirer:1953language-myth
  - Coupe, L., Myth (2008), : Routledge.
    cite:coupe:2008myth
  - Eliade, M., Myth and reality (1963), : Harper & Row.
    cite:eliade:1963myth-reality
  - Fromm, E., Forgotten language : an introduction to the
    understanding of dreams, fairy tales, and myths
    (2013), : Open Road Intregated Media.
    cite:fromm:2013forgotten
  - Frye, N., Anatomy of criticism: four essays (2000), :
    Princeton University Press.
    cite:frye:2000anatomy
  - Jung, C. G., McGuire, W., Read, H., Fordham, M., &
    Adler, G., The archetypes and the collective unconscious
    (1980), : Princeton University Press.
    cite:jung:1980collected-9-1
  - Jung, C. G., Man and his symbols (1968), : Dell.
    cite:jung:1968man-symbols
  - Jung, C. G., Adler, G., & Hill, R. F. C., Two essays on
    analytical psychology (1966), : Princeton University
    Press.
    cite:jung:1966collected-7
  - Jung, C. G., & Kerenyi, C., Essays on a science of
    mythology: the myth of the divine child and the
    mysteries of eleusis (1969), : Princeton University
    Press.  cite:jung1969science-mythology
  - Levi-Strauss, C., Totemism (1991), : Merlin Press.
    cite:lévi-strauss:1991totemism 
  - Lévi-Strauss, C., Myth and meaning (2001), : Routledge.
    cite:lévi-strauss:2001myth-meaning
  - Mark, M., & Pearson, C. S., The hero and the outlaw:
    building extraordinary brands through the power of
    archetypes (2001), : McGraw-Hill Education.
    cite:mark:2001hero-outlaw
  - Mark, M., & Pearson, C. S., The hero and the outlaw:
    building extraordinary brands through the power of
    archetypes (2001), : McGraw-Hill Education.
    cite:mark:2001hero-outlaw
