#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 2. Hoard Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 2. Hoard Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/18/02/abstract.org
  :Created:   2018-06-18T18:21@Prek Leap (11.642600N-104.919210W)
  :ID:        9a366b7c-c8c6-4198-99ac-60120512add5
  :VER:       582592936.652048606
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:XNN3-1816
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope



** TL;DR

Before getting into structure — what goes /into/ a hoard —
we should talk a bit about files, formats, interfaces and
such.

Since there will be different media and interfaces for
different succession stages, I suppose we should start
there.  For the lower succession stages it's a no brainer to
choose the codex as the media of choice.  A codex is one of
Man's great inventions and it has served us well over the
past two centuries.

We've only had electronic displays for a short period of
time, a couple of decades really.  And it's only been in the
last decade that displays can be thought of having /begun/
to mature in terms of quality and resolution.  We likely
still have a long ways to go, but at least we now have the
beginning of high end displays which can hold their own
against printed text and images on physical media.  We are
no longer tied to large, heavy, hot and flickering CRTs.  We
now have displays that can fit in a pocket and in form
factors that are the same as a book.

What we don't have is the interface -- the electronic
equivalent of a codex just is not here yet.

Of course we ask more of our displays than we ever did our
books.  Books just needed to formated once and you were done
with it.  Diplays, /screens/, are different.  A screen is an
interface that can display static and moving images.  Add
speakers and you have audio and video.  Add a pointing
device, be it arrow keys and a cursor, or a mouse, and more
recently a finger and you have a means of manipulating
images on the screeen.  You can create widgets which use
pixels to create controls that work in a simular way as
physical mechanical controls; switches, buttons, dials,
counters, sliders, knobs, levers, indicator lights, audio
alarms etc.  The fact that no one brings up the fact that
the only electronic interface we have is little more than
recreate 19th century industrial mechanical interfaces is
more than a little disturbing.  Steampunk interfaces were
and are clunky, clumsy and crude.  Turning screen interfaces
full of pull down menus, slider bars, buttons and text
fields are really terrible.  Tarting them up with sleeker
looking widgets doesn't change the fact that this is simply
not very good.  They have made mobile devices very limited
interfaces.

One problem is that we let the wrong people design our
interfaces.  Interface design was taken over by graphic
designers who are trained to create text and image layouts
for print media.  That hasn't really changed.  What
designers are not trained in, is cybernetics — man-machine
interfaces.

There is, however, a mature computer interface that predates
the Window's metaphor -- the command line and key-chording.
Such interfaces do not clutter the screen with clunky
widgets.  The amount of navigational crud on the typical web
page is astonishingly ugly and crude.  The command line has
a learning curve, which puts off a lot of people. It's not
something you can pick up and use in a few minutes.  But
then if you've never used a mobile device before, there is a
learning curve, just as there is a learning curve for
windows GUIs.

A shallow learning curve allows new users to get up to speed
quickly, but then it plateaus giving people who would like a
more powerful interface out of luck.  Windows is great for
the majority of people who only do a few things.  But it is
a terrible interface for people who are using it for
professional work.

There are some exceptions -- 3D software like Power Animator
(now called Maya) and SoftImage had a powerful graphical
interface that didn't require all of the clunky widgets from
the windows world.  Sadly as more people from the windows
gui world can on board, the interfaces have been dumbed down
to accomadate them.  The graphical editing program Gimp met
with the same fate.  People wanted it to be a clone of
photoshop and not require the use of the keyboard for
anything.  So it was dumbed down.  Graphic designers have
been a terrible influence on interfaces and the Web.


A book has very little in terms of interface.  There is a
table of contents, which outline the structure of the book
into pages, chapters etc, a index at the back of the book,
page numbers and links to footnotes, endnotes and to other
books.  It's elegant and it it's out of your way.  Mobile
interfaces are almost entirely made up of widgets, leaving
little room for content.  Since mobile devices do not have
input peripherals we are stuck with fingers and thumbs.  We
swipe and tap and sometimes we can pinch to scale.  But it's
weak beer.  It's too simple to do much of anything each
screen can only do a very small range of things so we have
to jump through multiple screens to get anything done.



