#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 2. Hoard Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 2. Hoard Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/18/02/abstract.org
  :Created:   2018-06-18T18:21@Prek Leap (11.642600N-104.919210W)
  :ID:        9a366b7c-c8c6-4198-99ac-60120512add5
  :VER:       582592936.652048606
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:XNN3-1816
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope



** TL;DR

Before getting into structure — what goes /into/ a hoard —
we should talk a bit about files, formats, interfaces and
such.

Since there will be different media and interfaces for
different succession stages, I suppose we should start
there.  For the lower succession stages it's a no brainer to
choose the codex as the media of choice.  A codex is one of
Man's great inventions and it has served us well over the
past two centuries.

We've only had electronic displays for a short period of
time, a couple of decades really.  And it's only been in the
last decade that displays can be thought of having /begun/
to mature in terms of quality and resolution.  We likely
still have a long ways to go, but at least we now have the
beginning of high end displays which can hold their own
against printed text and images on physical media.  We are
no longer tied to large, heavy, hot and flickering CRTs.  We
now have displays that can fit in a pocket and in form
factors that are the same as a book.

What we don't have is the interface -- the electronic
equivalent of a codex just is not here yet.

Of course we ask more of our displays than we ever did our
books.  Books just needed to formated once and you were done
with it.  Diplays, /screens/, are different.  A screen is an
interface that can display static and moving images.  Add
speakers and you have audio and video.  Add a pointing
device, be it arrow keys and a cursor, or a mouse, and more
recently a finger and you have a means of manipulating
images on the screeen.  You can create widgets which use
pixels to create controls that work in a simular way as
physical mechanical controls; switches, buttons, dials,
counters, sliders, knobs, levers, indicator lights, audio
alarms etc.  The fact that no one brings up the fact that
the only electronic interface we have is little more than
recreate 19th century industrial mechanical interfaces is
more than a little disturbing.  Steampunk interfaces were
and are clunky, clumsy and crude.  Turning screen interfaces
full of pull down menus, slider bars, buttons and text
fields are really terrible.  Tarting them up with sleeker
looking widgets doesn't change the fact that this is simply
not very good.  They have made mobile devices very limited
interfaces.
