#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Scenarios
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] | [[[./index.org][index]]]

* Scenarios
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/19/ww-scenarios.org
:Created:  2018-04-10T11:17@Prek Leap (11.642600N-104.919210W)
:ID:       fb62d65e-a9cc-4091-8ced-da9999196f27
:VER:      576605944.525345437
:GEO:      48P-491193-1287029-15
:BXID:     proj:IOI3-5370
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Table of Contents

 - New Civilization Scenarios
   - Hot        -> +4°
   - Cold       -> +2° (Paris Accord)
   - Just Right -> -2° (Half-Earth)
     
 - Three 100 Year Hoards
   - Northwest North America (Oregan?)
   - Lower Mekong Subregion
   - Mars (how effected by support from earth by climate change)
   - Control 
 
** TL;DR
This may well be split into a separate volume.  My fear is
that the scenarios are misunderstood in the way that
Soleri's fantastic 30 designs for arcologies were
misunderstood -- my myself most of all.

Because his theory and argument for Argology was so short,
dense and graphical and the bulk of the book was made up of
the designs most people focused on the designs as top down
structures that were intended to be built and look to be
exactly what he drew.  This is not surprising because this
is how modern architecture does things.  The architect
designs something on paper and then hands it over to
engineers to build it. That isn't what Soleri indended at
all.

#+begin_quote
This work has a critical part and a constructive part.  They
are treated concurrently in the first section, where
criticism is coupled with what in my view is a perspective
suggesting a greater coherance.  To help focus this problem
I have amplified it greatly.  I do not feel this invalidates
the resultss because the argument is kept in the context
that a peach not being a potato and not a peach being yellow
or peachy; and the results are not a blueprint for a
city-civilization but only a guideline toward a new option.
After this first part follows the development of thirty
schemes based on theoretical propositions and then a
proposed microexperiment in Arcosanti by the Cosanti
Foundation.

-- Paolo Soleri, 1969  cite:soleri:1999arcology
#+end_quote

And it could be seen in the work done on Arcosanti.  The
design was, you could say, aspirational and as construction
took place the design radically changed as they gained
experience and took into account things on the ground.

What they missed, is what Alexandar keeps trying to teach us
-- is that if you are going to build something bottom up, it
can't be done if you only change what the architect does, it
also needs to change how a project is financed and how it is
built.  Soleri understood this, but was unable to develop
models for actually accomplishing it.

You can't build a town, let alone a city by selling bells.
And despite his understanding that the process /had/ to be
bottom up, he was still too much part of the old school, and
influenced by people like Frank Loyld Wright who was mister
command and control from the top and work down -- Soleri had
an aestetic vision that he wanted to instill in Arcosanti
which is unique and beautiful, but it comes at the cost of
being truly a bottom up generative process.  He almost
pulled it off, if he'd only been able to understand that the
ideas were powerful enough to hold together and take on a
life of their own if he only gave up control.  That's an
astonishingly difficult thing to do, especially for an
architect -- whose whole modern persona is based around the
idea of being absolute master and commander -- shepard of
vision, and leader through the wilderness.

I do not want to make that same mistake here.

** Table of Contents

** The Plan of Arc Indradevi

A bioregion in n.e. cambodia.  Rather than my original
concept of doing the plan for the Arc itself like PSG, we do
a plan for an entire bioregion and ecosystem for of 2
million people all living and working as part of a global
distributed micro-value-chain.

The Arc will be just one part of the larger plan -- that
will include infrastructure, agriculture, production,
economic, education, governance and culture.

I suppose the plan would be a master plan, and we would
create three different 100 year scenarios of how that plan
might be realized depending on different climate change,
political, and economic scenarios globally and regionally.

My original idea was to do three scenario histories over a
100 year period.  The scenarios would show how generative
designs would create very different things given different
circumstances.

Without this it would be easy to think that this was a
traditional top-down static plan.  We need to show that
generative designs are natural -- for some reason they scare
people, but most of that is because generative plans are
things that happen in the moment, they are processes rather
than plans.  Plans are linear, with a beginning middle and
end -- processes can be linear -- but they can also be
open-ended and they certainly are not deterministic it's not
always clear where a process will lead.  In reality we don't
know where plans lead either -- but in the case of building
physical infrastructure the goal is usually to know what you
are building and ensure it get's built according to plan.
In the case of something like a suspension bridge this is a
good thing.  But not the vast majority of constructions.
The great european cathedrals were not built in the same way
as modern buildings they were generative processes that
took, in some cases, centuries to complete.  There's no
little irony that ESR's famous essay used the catherdral as
the symbol of top down planning, design and construction.

Adaptive processes are better in the long term, but static
processes are percieved to be better in the short term (even
though this is not true) and the modern system from the
ground up is designed to work that way.

This is not to say that generative is all chips and gravy.
Generative is as hard as distributed -- biological evolution
is a blind generative process and is mind blowingly
inefficient.  But when generative works, the payoff is all
of Life in all of its diversity, complexity and beauty.  We
are coded to work this way, even if that coding is working
very deep in the bios pace-layer.  And the thing is,
deterministic processes are almost always bad and if they
aren't, it's little more than chance.  Okay, I take that
back, deterministic processes work at individual human
timescales.  We can get up in the morning, eat breakfast and
go to work.  That's a deterministic process.  We make a plan
and follow it for day to day life.  We can do that and often
do it very well.  But we then try to apply the same approach
to processes in pace-layers that are beyond individuals, and
even beyond collective human pace-layers.  That's where is
all falls apart.

Business plans are a good example.  Business plans are
complete bullshit if they are for longer than a few months.
Five or ten year business plans are meaningless fantasy in
world whose ROC in fashion and commerce pace-layers is as
fast as it is today.  But we persist in thinking that they
are useful and waste enormous amounts of time writing them
and as soon as something changes, they are forgotten in a
drawer.



** The Plan of Barsoom Dor

Basically the same thing as Indradevi, but how the same
thing might be achieved on Mars.

A man-made underground river (not a tunnel, but a river with
banks and air above) that runs from south towards the
equator that is fed by ice from antarctic to domes in warmer
climes.  The river feed domes that create atmosphere, and
hydrosphere that make up a distributed biosphere.

** Dubai Martian City

I'd like to approach the Dubai Mars City project with the
proposal to do three scenarios for them as well -- one will
be our Barsoom Dor scenarios but in addition two others that
explore what a traditional top down design and construction
process might look like and how they would compare to our
generative approach.

This would be done by holding scenario conclaves where we
invite different traditional architects, engineers and
builders and work out the long term consequences of top down
approaches.

To keep participants honest, all scenarios will follow
examples from history of what has happened to planned urban
areas in the past.  We ask them first to come up with a
design and 20 year master plan in brief and then we see how
the plan will adapt over time to things that they didn't
plan for.

But how to do that?  I suppose we have two teams the design
teams, the governance teams and then the historical teams
who would through events at them which came from historical
examples.

One of the scenarios is that after 50 years, Mars is cut off
from Earth for the next 50 years.  This might mean being
physically cut from all contact, or or economically cut off
when funding dries up for support.

We will also throw at them things that will basically force
them to abandon a lot of their initial assumptions after the
settlement is essentially built.  Can they adapt, and in
order to adapt how will it impact their original designs?

---

It remains to be seen how useful this exercise will be as it
will be based on conjecture of how complex systems will
evolve over time.  It's like predicting the weather, once
you get past a few days, it's all rubbish except as long
term trends.

Each scenario will have a timeline of events and metrics.

We can classify each scenario as within a goldilocks
spectrum with a too hot, too cold and just right scenarios
for each of the three /Plans/.

We will need to put restraints on the parameters of each
scenario that are based on empirical metrics that we have to
date.

Each Plan will start with a base design, an intended
generatative succession plan broken into stages and then
take those plans and subject them to the events in the
scenario and how the plans have to be adapted over time and
what the outcomes are.

Ideally we should also have a fourth un-plan which acts as a
control and uses the present as a starting /plan/ and see
how continuing on as we are now compares to the our
generative designs.

Finally, we will have to do all this as a group project,
that bring together people with a wide range of expertise in
different fields -- who meet together to do this in person,
but will also be backed up with computational models, and
possibly crowd sourcing scenarios over the internet in the
form of multiple small games to see how people might really
react in such situations.

** References

  - Soleri, P., Arcology: the city in the image of man
    (1999), : Bridgewood Press,.
   cite:soleri:1999arcology
