#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 3. Paradigm Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 3. Paradigm Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/01/03/intro.org
:Created:  2018-05-26T18:55@Prek Leap (11.642600N-104.919210W)
:ID:       59d578ee-2e90-4bb4-a3f1-ad38c21a8865
:VER:      580607772.032204960
:GEO:      48P-491193-1287029-15
:BXID:     proj:UCE6-4061
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:





So how do we degin a paradigm that is machine
understandable?

First let's think of a paradigm in terms of succession
stages.  No paradigm exists outside of the paradigm that it
is replacing, or the idea that kuhn uses of different people
coming up with lists of observations and coming up with
different schemes of getting them to work together as a
theory.  Each paradigm is built on top of the paradigm that
cam before it.  It inherits terminology from the previous
paradigm, and then goes on not to replace what came before
it but expand on it and provide a finer grained
understanding of it.  As in Physics, each paradigm doesn't
replace, it refines it and allows it to work at deeper and
deeper scales.  Newtonian Physics still work fine at
specific scopes -- when you venture outside of that scope,
Relativity kicks in and provides a deeper explanation and
provides a fix for anomolies in Newton.

  - Classical Mechanics
    - Relativity
     - Quantum Theory

A paradigm is made up of work done by a number of different
people at different times.  Relativity provided the
framework for the new paradigm then others came in and
expanded horizontially filling in the bits, often in the
form of verification, that wasn't included in the first
iteration.

Part of a paradigm's scope is its community  

The most difficult part is that there is no single set of
rules that define the paradigm -- but there are theories,
parameters.

A paradigm is a bit like knowledge -- knowledge is not
information, it is what happens when you take information
and weave it into your head, knowledge is all of the
connections and patterns and memories that that information
becomes part of.  The sum of all knowledge in a person's
head constitutes a map, a worldview.

A paradigm could be thought of as knowledge within a
community -- a community is made up of individuals, so
members have to externalize what is in their head, divide
that knowledge into specialities that are kept in living
memory by different parts of the community

To learn a paradigm all members in the community have to
load all or at least a critical amount of the externally
recorded information that is part of the paradigm into your
their heads and through deliberate practice -- where each
repetition is slightly different than the last, this is why
there are exercises at the back of chapters -- so you can
reinforce memory and gain a broader feeling for how
something works and the limits of how it can be used.





** References


- Masterman, M., The nature of a paradigm, In (Eds.),
  Criticism and the Growth of Knowledge (pp. 59–89)
  (1970). : Cambridge University Press.
  cite:margaret:1970nature
- Shapere, D., The structure of scientific revolutions, The
  Philosophical Review, 73(3), 383 (1964).
  http://dx.doi.org/10.2307/2183664
  cite:shapere:1964structure
