#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Health Infrastructure Introduction 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Health Infrastructure Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/13/07/intro.org
:Created:  2018-05-08T19:42@Prek Leap (11.642600N-104.919210W)
:ID:       6977cee4-cff9-4582-9d74-2fa852bca40d
:VER:      579055424.034446553
:GEO:      48P-491193-1287029-15
:BXID:     proj:WHB3-0157
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
It's always been a mystery to me that the single most important type
of infrastructure, that impacts every person who has ever or will ever
live has recieved in many ways the least amount of attention.  With
the exception of a handful of relatively small countries, healthcare
infrastructure is a mess.  It is withheld from a large part of the
population or is made so expensive to effectively withhold it from a
large number of people.  Ignoring it or not dealing with it has
resulted in massive social disruption -- from mass incarceration of
people because of substance abuse and the black market economy that
exists to meet the demand.  Dealing with a public health issue as a
moral or judicial issue is nothing short of madness.

We need to rethink healthcare infrastructure from the ground up as a
top priority because solving this problem will make enormous social
and economic problems not only be manageable but solvable.  This will
save enormous amounts of resources that could be spent elsewhere and
causes untold pain and misery.
** TL;DR
** References


