#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Adhocracies (chapter)
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]


* Adhocracies (chapter)
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/10/55/ww-adhocracies.org
:Created:  2018-05-09T16:29@Prek Leap (11.642600N-104.919210W)
:ID:       23c808a9-cf72-4bda-bbf2-7879abd03842
:VER:      579130209.095549818
:GEO:      48P-491193-1287029-15
:BXID:     proj:LUH5-5607
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR

It just hit me that the way want implement adhocracies is
different from the way that Toffler and others used the term
back in the 1970's or even in the last ten years.  In most
cases, it is used as an alternative structure to a
bureaucracy.  A bureaucracy is usually a system that is used
to manage large industrial or goverment ministry scale
organizations. The word invokes mountains of red tape, of
labryinths of compartmentalized offices with different
requirements and agendas.  These are hierarchical top down
command organizational structures.

What I am envisioning is almost the opposite. The idea is to
create a bottom up adhocracy network, that pulls together a
diverse collection of resources, services, equipment,
information and knowledge so that all of these small atomic
single purpose operators can assembly on-the-fly to achieve
one thing, and then disband and then reform in another
configuration to do something else.  And that this is all
done as a more flexible means of production at scale which
is far more flexible and efficient.  All of this needs to be
done as an automated network where you go to advertise what
you need or want, and the network will pull together
everythiing to do it and then coordinate between each party
in doing their specific step in the process.  This will be a
very large complex service to be able to provide but with
advances in machine-cognition, it is likely that traditional
top down industrial organizations will break up and become
distributed, the production happening as close to the
customer as possible.  It will work like a Dabba Wallah
delivery network where a lunch box is passed from person to
person until it reaches it's destination.  The system is
bottom up and self-routing.  But in our proposed network,
a step in production takes place as it moves closer and
closer to the end user.  After each step is complete, the
network will then pass on a new job in a different
production chain.  This makes it possible to create higher
quality goods and services at scales and efficiencies that
match traditional centralized industrial systems.

The big challenge here is not creating and coordinating
these chains, but to build ways for sparse networks of
people, and teams who have never worked together before and
may not work together again to work and communicate with
each other as efficiently as if they were in the same
factory or office.  We have text, voice and video networks
for people to communicate today, but the quality of the
communication is lossy and doesn't in many cases doesn't
work.   Ad hoc teams must feel like they are working
together in the same room.  There will be problems with time
zones, but that can be compensated for -- people are good at
finding a time that both parties are awake and working at
the same time enough to make this viable -- but we need far
better communication tools to make it work.


** Weber Quotes

#+begin_quote
These competencies are underpinned by rules, laws, or administrative
regulations. That means:

   1. A rigid division of labor is in place for the purpose of
      performing regular daily tasks as official duties in the
      functioning of the bureaucratically governed system.
   2. In order to fulfill these duties the necessary chains of command
      are firmly established and divided up [among the Beamte], and
      their capacity to coerce (physical, sacred, or other) is firmly
      restricted by regulation.
   3. Regular and continuous fulfillment of these assigned duties, and
      the execution of respective rights is systematically secured by
      hiring people with certified qualifications.

These three aspects constitute the essence of bureaucratic
administration of a Behörde in the public sector. In the private
sector, these three aspects constitute the essence of a bureaucratic
management of a private company [Betrieb]. Not until the emergence of
the modern state could this type of bureaucratic government Behörde be
fully realized in political and church organizations. And it was not
until the development of the most advanced forms of capitalism that
this kind of administration emerged in the private sector.

pdfview:../../../hoard/lib/waters:2015webers-rationalism.pdf::84
#+end_quote

#+begin_quote
Main principles (characteristics):

  1. Specialized roles
  2. Recruitment based on merit (e.g., tested through open
     competition)
  3. Uniform principles of placement, promotion, and transfer in an administrative system
  4. Careerism with systematic salary structure
  5. Hierarchy, responsibility and accountability
  6. Subjection of official conduct to strict rules of discipline and control
  7. Supremacy of abstract rules
  8. Impersonal authority (e.g., office bearer does not bring the office with him)
  9.  Political neutrality


— pdfview:../../../hoard/lib/waters:2015webers-rationalism.pdf::84 
  summarized in cite:wiki:2018max-weber
#+end_quote


** Toffler Quotes

#+begin_quote
For we are witnessing not the triumph, but the breakdown of
bureaucracy. We are, in fact, witnessing the arrival of a
new organizational system that will increasingly challenge,
and ultimately supplant bureaucracy. This is the
organization of the future. I call it "Ad-hocracy."

Man will encounter plenty of difficulty in adapting to this
new style organization. But instead of being trapped in some
unchanging, personality-smashing niche, man will find
himself liberated, a stranger in a new free-form world of
kinetic organizations. In this alien landscape, his position
will be constantly changing, fluid, and varied. And his
organizational ties, like his ties with things, places and
people, will turn over at a frenetic and ever- accelerating
rate.

pdfview:../../../hoard/lib/toffler:1971future-shock.pdf::71
#+end_quote

#+begin_quote
First, in this particular system of organization, the
individual has traditionally occupied a sharply defined slot
in a division of labor. Second, he fit into a vertical
hierarchy, a chain of command running from the boss down to
the lowliest menial. Third, his organizational
relationships, as Weber emphasized, tended toward
permanence.

Each individual, therefore, filled a precisely positioned
slot, a fixed position in a more or less fixed
environment. He knew exactly where his department ended and
the next began; the lines between organizations and their
sub-structures were anchored firmly in place. In joining an
organization, the individual accepted a set of fixed
obligations in return for a specified set of rewards. These
obligations and rewards remained the same over relatively
long spans of time. The individual thus stepped into a
comparatively permanent web of relationships—not merely with
other people (who also tended to remain in their slots for a
long time)—but with the organizational framework, the
structure, itself.

Some of these structures are more durable than others. The
Catholic Church is a steel frame that has lasted for 2000
years, with some of its internal sub-structures virtually
unchanged for centuries at a time. In contrast, the Nazi
Party of Germany managed to bathe Europe in blood, yet it
existed as a formal organization for less than a quarter of
a century.  In turn, just as organizations endure for longer
or shorter periods, so, too, does an individual's
relationship with any specific organizational
structure. Thus man's tie to a particular department,
division, political party, regiment, club, or other such
unit has a beginning and an end in time. The same is true of
his membership in informal organizations—cliques, factions,
coffee-break groups and the like. His tie begins when he
assumes the obligations of membership by joining or being
conscripted into an organization.  His tie ends when he
quits or is discharged from it—or when the organization,
itself, ceases to be.

— pdfview:../../../hoard/lib/toffler:1971future-shock.pdf::72
#+end_quote

#+begin_quote
When Lockheed Aircraft Corporation won a controversial
contract to build fifty-eight giant C-5A military air
transports, it created a whole new 11,000-man organization
specifically for that purpose. To complete the
multi-billion-dollar job, Lockheed had to coordinate the
work not only of its own people, but of hundreds of
subcontracting firms. In all, 6000 companies are involved in
producing the more than 120,000 parts needed for each of
these enormous airplanes. The Lockheed project organization
created for this purpose has its own management and its own
complex internal structure.

The first of the C-5A's rolled out of the shop exactly on
schedule in March, 1969, twenty-nine months after award of
the contract. The last of the fifty-eight transports was due
to be delivered two years later. This meant that the entire
imposing organization created for this job had a planned
life span of five years. What we see here is nothing less
than the creation of a disposable division—the
organizational equivalent of paper dresses or throw-away
tissues.

— pdfview:../../../hoard/lib/toffler:1971future-shock.pdf::75
#+end_quote

This is exactly what Englebart was talking about 



#+begin_quote
When a leading manufacturer set out to win a certain large
contract from the National Aeronautics and Space Agency, it
assembled a team of approximately one hundred people
borrowed from various functional divisions of the
company. The project team worked for about a year and a half
to gather data and analyze the job even before the
government formally requested bids. When the time came to
prepare a formal bid—a "proposal," as it is known in the
industry—the "pre- proposal project team" was dissolved and
its members sent back to their functional divisions.  A new
team was brought into being to write the actual proposal.

Proposal-writing teams often work together for a few
weeks. Once the proposal is submitted, however, the proposal
team is also disbanded. When the contract is won (if it is),
new teams are successively established for development, and,
ultimately, production of the goods required. Some
individuals may move along with the job, joining each
successive project team

— pdfview:../../../hoard/lib/toffler:1971future-shock.pdf::75
#+end_quote

#+begin_quote
Task forces and other ad hoc groups are now proliferating
throughout the government and business bureaucracies, both
in the United States and abroad. Transient teams, whose
members come together to solve a specific problem and then
separate, are particularly characteristic of science and
help account for the kinetic quality of the scientific
community.  Its members are constantly on the move,
organizationally, if not geographically.

— pdfview:../../../hoard/lib/toffler:1971future-shock.pdf::75-76
#+end_quote

#+begin_quote
We shall shortly see that this process, repeated often
enough, alters the loyalties of the people involved; shakes
up lines of authority; and accelerates the rate at which
individuals are forced to adapt to organizational
change. For the moment, however, it is important to
recognize that the rise of ad hoc organization is a direct
effect of the speed-up of change in society as a whole.

— pdfview:../../../hoard/lib/toffler:1971future-shock.pdf::76
#+end_quote

#+begin_quote
So long as a society is relatively stable and unchanging,
the problems it presents to men tend to be routine and
predictable. Organizations in such an environment can be
relatively permanent. But when change is accelerated, more
and more novel first-time problems arise, and traditional
forms of organization prove inadequate to the new
conditions. They can no longer cope. As long as this is so,
says Dr. Donald A. Schon, president of the Organization for
Social and Technical Innovation, we need to create
"self-destroying organizations ... lots of autonomous,
semi-attached units which can be spun off, destroyed, sold
bye-bye, when the need for them has disappeared."

— pdfview:../../../hoard/lib/toffler:1971future-shock.pdf::76
#+end_quote

** References

  - Birkinshaw, J., & Ridderstråle, J., Adhocracy for an
    agile age, McKinsey Quarterly, (), (2015).
    cite:birkinshaw:2015adhocracy
  - Dolan, T. E., Revisiting adhocracy: from rhetorical
    revisionism to smart mobs, Journal of Futures Studies,
    15(2), 33–50 (2010).
    cite:dolan:2010revisiting
  - Fesler, J. W., The Bureaucratic Phenomenon,
    Administrative Science Quarterly, 10(2), 261–266 (1965).
    http://dx.doi.org/10.2307/2391417
    cite:fesler:1965bureaucratic 
  - Toffler, A., Future shock (1971), : Bantam Books. 
    cite:toffler:1971future-shock
  - Waters, T., & Waters, D., Weber’s rationalism and modern
    society: new translations on politics, bureaucracy, and
    social stratification (2015), : Palgrave Macmillan US.
    cite:waters:2015webers-rationalism
  - Wikipedia, , /Max weber --- Wikipedia, the free
    encyclopedia/ (2018).
    cite:wiki:2018max-weber 
