#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 3. Ontologies Introduction 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 3. Ontologies Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/04/03/intro.org
:Created:  2018-05-18T09:04@Prek Leap (11.642600N-104.919210W)
:ID:       363354f9-4283-4479-9c6e-640d1f4f4006
:VER:      579881150.839522928
:GEO:      48P-491193-1287029-15
:BXID:     proj:GJQ5-5331
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


** Keeping the five POV models straight

 - entity
 - succession
 - LOD
 - ROC
 - POC

Thinking about this more I don't think we need to go outside of the
Entity model to include the other models.  All metadata will be within
the entity model, so Succession, LOD, ROC and POC will be incorporated
into it.

In many cases it will simply including a link to which Pace-Layer or
LOD that a burr belongs to.

Perhaps they could be combined as well, we need to have namespaces for
each model no matter what it is, so adding the prefix and then point
to the link is not difficult.  It would be great to be able to do
multiple ones at the same time.

So you pull up a helm list, a choose items and they get added to the
property box at point.

** thesaurus relationships encoding

As a key-value pair:

  :bt: per:charles_dickens--19c_novelist

  #+BT: per:charles_dickens--19c_novelist

  BT: Charles Dickens (19c_novelist)  | Person tspace

** whole/part relationships

 - BTI, NTI : Instantive
 - BTP, NTP : Partitive

** next/prev reltionships

 - BTF, NTF : forward
 - BTB, BTB : back (previous) 

I prefer Next and Previous but we're already using P for partitive.

** How to reduce verbosity in file headers?

Use VAL to set the  value for the burr and then a list of
relationships:

   #+LAYER:   VAL=civ:culture BT=civ:governance
   #+STAGE:   VAL=civ:tools  NT=civ:clockwork 
   #+LOD:     VAL=lod:min
   #+ENTITY:  VAL=exp:Christmas_Carol--novela RT=exp:Christmas_Carol--play

Do we want to use entities as tspaces?  I suppose there is no reason
why any burr can't belong to multiple tspaces so long as they are
unique to that tspace.
    
This gives us a relatively compact way of setting a number of values
for each type of model that allows us to create some very interesting
structures.

** References

  - Durkheim, E., Mauss, M., & Needham, R., Primitive
    Classification (2010), : Routledge.
    cite:durkheim:2010primitive
  - IFLA, , Functional requirements of authority data: a conceptual
    model, , (), (2008).
    cite:ifla:2008frad
  - IFLA, , Functional requirements for bibliographic records: final
    report, , (), (1997).
    cite:ifla:1997frbr
  - NISO, , & ANSI, , /Niso z39. 19-2005 guidelines for the
    construction, format, and management of monolingual controlled
    vocabularies/ (2010).
    cite:ansi:2010ansi-z39.19
