#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 8.1 Introduction Volume VIII Curriculum
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] [[[./index.org][up]]]

* 8.1 Introduction Volume VIII Curriculum
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/08/intro.org
:Created:  2018-04-24T11:06@Prek Leap (11.642600N-104.919210W)
:ID:       69d19e03-c646-4813-b123-712e3572ab76
:VER:      577814843.463742983
:GEO:      48P-491193-1287029-15
:BXID:     proj:YTR3-6048
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


** Epigraph

#+begin_quote
    Vita brevis,
    ars longa,
    occasio praeceps,
    experimentum periculosum,
    iudicium difficile.

    Life is short,
    and art long,
    opportunity fleeting,
    experimentations perilous,
    and judgment difficult. 

--  Hippocrates 


"The lyf so short, the craft so long to lerne" -- Chaucer

    [[https://en.wikipedia.org/wiki/Ars_longa%2C_vita_brevis][Ars longa, vita brevis]] - Wikipedia
#+end_quote

** Scope

This volume is concerned with how we learn as individuals
and as societies.  How do we learn.  How do we pass
knowledge and skills on to others.

The idea is that because of the exponential ROC, knowledge
becomes obsolete very quickly.  How to keep up?  While
disciplines and technologies are born and vanish in a
fraction of a person's career.  Learning must change from
being a place, as it became in the industrial revolution,
where schools became factories for providing basic skills
that people needed to drive the indusrial engine.  The base
skill set was not the high, so it really didn't take that
long to teach it.  That doesn't explain why education became
such a long process.  That happened because once child labor
was effectively banned, and parents were at work in
factories and offices for the majority of the day, children
really had no supervision or purpose in the home any
longer.  So schools became day care for children.

Children need to be reintegrated into society, not
sequestered for the better part of two decades in Lord of
the Flies cultures that were separated from the rest of the
world.

Learning needs to become an activity that happens
everywhere, starts at birth and ends in the grave.

This volume is about building generative learning frameworks
that prepare people to become useful citizens in society
(the goal of a liberal education) and then provide the
cognitive skills, cognitive tools, core knowledge and
practical skills that are mastered to become part of society
and provide meaning and purpose to people's lives.

** TL;DR

This section is broken into four parts:

  - Mastery  :: Deals with the larger concepts of mastering a
                discipline and a basic philosophy of life
                work, learning and balance.
  - Practice :: The deliberate regular practice of anything
                that is one of the two pillars of work and
                learning.
  - Otium    :: The flip side of Practice which is
                deliberate, rest and contemplation.
  - Negotium :: Dealing with a person's public roles and
                interactions with people, family, collective
                projects, business, management roles etc.

Mastery is the process of lifelong learning.  The Trivium
can be thought of as a means of establishing underlying
habits of thought and technique that are part of the process
of mastering any skill or subject.  As such Mastery is a
unspoken subject of the Trivium that is not formally given a
name but is taught indirectly.

This doesn't mean that Mastery is an un-spoken process.  The
process of mastering a subject or skill is well known.  It
is not an easy process, and there are no short-cuts, but it
is deeply fulfilling.  In many respects Mastery is the
foundation that civilization is built on.

Mastery comes down to three things:

   - knowledge
   - technique
   - process

** George Leonard's Outline

5 keys to long-term success:

  - Instruction;
  - Practice;
  - Surrender;
  - Intentionality; and,
  - The Edge - Push the envelop.

Mastery is:

  - The process where what was difficult becomes both easier and
    more pleasurable;
  - Long-term dedication to the journey - not the bottom line;
  - Gaining mental discipline to travel further on your journey;
  - Being goalless;
  - Realizing that the pleasure of practice is intensified;
  - Creating deep roots;
  - Knowing that you will never reach a final destination;
  - Being diligent with the process of mastery;
  - Your commitment to hone your skills;
  - After you have reached the top of the mountain, climb
    another one;
  - Being willing to practice, even when you seem to be getting
    no where;
  - Making this a life process;
  - Being patient, while you apply long-term efforts;
  - Appreciating and even enjoying the plateau, as much as you do
    the progress;
  - Practicing for the sake of practice;
  - Winning graciously, and losing with equal grace;
  - Placing practice, discipline, conditioning and character
    development before winning;
  - Being courageous;
  - Being fully in the present moment;
  - Realizing that the ultimate goal is not the medal, or the
    ribbon, but the path to mastery its self (The "I am" stage);
  - Being willing to look foolish;
  - Maintaining flexibility in your strategy, and in your
    actions;
  - A journey; and,
  - Determination


** References

Backward Design

  - Grant Wiggins, J. M., The understanding by design: guide
    to creating high-quality units (2011), : Association for
    Supervision & Curriculum Development.
    cite:grant:2011understanding-design
  - Wiggins, G., & McTighe, J., What is backward design,
    Understanding by design, 1(), 7–19 (1998).
    cite:wiggins:1998backward
  - Wikipedia, , /Backward design --- Wikipedia, the free
    encyclopedia/ (2018).  cite:wiki:2018backward-design

Mastery

  - Sennett, R., The Craftsman (2009), : Penguin.
    cite:sennett:2008craftsman 
  - Pang, A. S., /Darwin was a slacker and you should be
    too/ (2017).  cite:pang:2017darwin-slacker
  - Pang, A. S., Rest: why you get more done when you work
    less (2016), : Basic Books.  cite:pang:2016rest
  - Leonard, G., Mastery. the keys to success and long term
    fulfillment (1992), : Plume.  cite:leonard:1992mastery
  - Greene, R., Mastery (2012), : Viking Adult.
    cite:greene:2012mastery 
  - Davis, J., Two awesome hours: science-based strategies
    to harness your best time and get your most important
    work done (2015), : HarperOne.
    cite:davis:2105two
