#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Volume XI. Infrastructure Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]] | [[[./index.org][index]]]


* Volume XI. Infrastructure Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/11/intro.org
:Created:  2018-04-30T20:47@Prek Leap (11.642600N-104.919210W)
:ID:       4e8d7fda-ee2a-4a2f-9c3a-929caff6e1ee
:VER:      578368094.905205042
:GEO:      48P-491193-1287029-15
:BXID:     proj:GWA6-3885
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

Almost everything is a kind of infrastructure.  Governance, education,
production, law, electrical grids, road systems, airports, petrol
stations, post offices, courts, banks, telephone networks etc.  In
most cases infrastructure is made up of networks that are systems that
connect things together.

And because infrastructure's purpose is to connect things together it
is a pace-layer that is dead in the middle; it can't change to fast or
too slow.  It must adapt and be maintained fast enough to support the
faster pace-layers, but slow enough to ensure that it's around long
enough for the lower layers to provide their functions.

Infrastructure is as much in the public as the private sector.
Commerce taking the form of private sector corporate bodies might be
given the task of managing parts of infrastructure, but they are not
private, they must be accessible to everyone to be infrastructure.

A lot of infrastructure is even slower to change than the cultural
layer.  This is clearly seen in the layout of roads in cities.  The
structures in cities may change at wildly different rates of
change, the roads remain in place for centuries or even millennia.

#+begin_quote
They say the cows laid out Boston.  Well,there are worse surveyors.
#+end_quote

To some degree this is true of most cities that grew organically
rather than were centrally planned.  And most of the centrally planned
city layouts only happened after major catastrophes such as fire and
war raised large swaths of a city and needed to be rebuilt quickly.
Megafauna often do a better job than central planners.  Megafauna will
find the easiest route from one point to another and will follow the
same paths as they become beaten down and easier to follow.  Humans
follow the megafauna when they are hunters, and when man settled down
and became farmers those paths were formed by domesticated megafauna
which were easier to walk on that blazing a trail through grass and
brush.  Those paths eventually were broadend over time to allow more
traffic and eventually became roads.  And many roads, once laid out
stay in place for very very long times.


** TL;DR
** References

