#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XXII. Origin Story Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* XXII. Origin Story Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/22/abstract.org
  :Created:   2018-06-03T18:32@Prek Leap (11.642600N-104.919210W)
  :ID:        0b43058e-ab37-4291-a3b9-4033ffa5ee90
  :VER:       581297602.563251229
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:DGV4-6100
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope

** TL;DR


Not entirely sure how to do this.  Big Hisory has some
fantastic works, but they are not really narratives in the
sense that origin stories are structured.  Cosmos comes
somewhat close in that it starts with us, zooms out to the
big bang and then works back to us -- later it shrinks
down.  At each step, there is a story of how each discovery
came about, the human story of the person/people behind it
and how it changed the paradigm that came before it.  This
is the way we teach science -- but is it the way we teach an
origin story?

The Bible too is structured somewhat the same way, starting
with creation, then the first people, and how things got
increasingly complex as societies grew more complex, as more
generations passed, with an increasingly complex history
behind them.

Pure origin stories are rather brief, little more than a
chapter in most myths.

The next problem is the very problem of universality -- it's
difficult to relate to a story where most of the key figures
will not be from your culture, and where large parts of the
story takes place far from where you live.

This is why that until two thousand years ago, when the
great monothesitic religions emerged around growing urban
centers under control of ever larger states, that religion
was very local, very specific, very personal.  There might
be some big gods, but most people worships their local gods,
rooted in their geography and experience.

We don't want our meta-origin story to tread on local
systems too much, otherwise it will come across as being
imperialisitic and foreign.

So in a sense, we should structure the origin story so that
it can be adapted to each locale, so the story maps to the
local, merging the local and the global.  This is how
religions spread.

There will be a number of different ways that this can be
shaped.  First around broad ethnic traditions, there are
cultural bands as you move from east to west, each is a
little more like it's neighbor on one side and a little less
than the other neighboring culture on the other.

SE Asia is a good model for this -- You have China on one
side, and India on the other, and all of the countries in
between are a spectrum between the two larger cultures.
Nepal is closer to India.  Burma is more Indian, than
Chinese.  Thailand is about in the middle equally influenced
by India and China.  Cambodia is slightly more Indian than
Siam as it held on to it's Hindu phase of history longer than
the Thai's who moved to Buddhism earlier.  Vietnam is as
close to China as Nepal is to India.

So we can have at least five different versions of the
origin story, with each being centered in a different
cultural tradition.

We then adapt for climate -- the climate where you live
shapes your relationship to the world and your attitude
towards it.  Cold climates produce very different cultures
from mild climates.  Cultures along the Pacific Rim have to
contend with earthquakes, volcanos, tsunamis and typhoons.
Polynesian culture is based around small islands that act
the same as oasis in desert climates -- nature is big, and
places for man are small.

The other side of climate is that flora and fauna are
different as is the geography, plains, savannah, rainforest,
hot dry desert, tundra, mountains etc.  All of these things
are the raw materials that go into the creation of a
mythological vocabulary. Our cultural archetypes map to what
is around us.

Next is to map to level of economic development that a
culture is in -- a lot of what we think of as a local
culture is actually part of a universal series of succession
stages that every culuture moves through as it develops.

Finally, we need to work out how to map technology to all of
this -- the concept of magic is universal and is closely
tied to cultural mythos it is practiced in.  This can become
a powerful interface to relating to and controlling
increasingly autonomous and ubiquitous technology that is
woven into our lives.

This is now getting away from this Canto which is the origin
story.

Putting this all together, the base story is the same, but
maps to different locales in the following ways:

  - Relative to Major Cultures: Chinese, Indian, Middle
    Eastern, European, Polynesian.
  - Map to local climate, flora, fauna and geography and
    cycles of nature.
  - Map to level of economic development
  - Map to technological processes and services as a magical
    interface.


