#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XXII. Origin Story Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* XXII. Origin Story Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/22/abstract.org
  :Created:   2018-06-03T18:32@Prek Leap (11.642600N-104.919210W)
  :ID:        0b43058e-ab37-4291-a3b9-4033ffa5ee90
  :VER:       581297602.563251229
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:DGV4-6100
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope


Our origin story will encompass Big History as a meta-origin
and history as a template which is then combined with a
local map that puts the story into a local context that
people can relate to.  This will not contradict the meta
story, but will put empasis on local POV and mētis.

It seems to be common practice of begining where you happen
to be.  But religious and cutural origin stories start at
the beginning and work up to where you are.

But to start from the beginning, you need to have a number
of concepts under your belt to understand it, especially if
you are starting from the big bang, which is /a/ beginning,
the beginning of what we can know through empirical
evidence.  We'll have to cover speculation of what came
before it.

I wonder if we start with the concept of infinity -- with
the simple mathematical principle that you can add something
to any set of numbers, and you can divide anything, not
matter how small.  There is no beginning and end -- just one
very large middle.  So we are introducing a very remedial
concept of set theory...

And everything you know about the world is relative to where
you are observing it.  So all observers see themselves as
being at the center of the universe.

We need a structure for this -- an LOD so that there is
relatively short narrative the sweeps through the big
picture, but you can then drill down in more detail.

I like parables and gedankenexperiments.  There is no reason
that thought experiments can't be done as fictional stories
like parables.

And if we make these parables universal, they can be
remapped on top of local cultural mythos and iconography.

#+begin_quote
George Fyler Townsend, in his translator's preface to
Aesop's Fables (Belford, Clarke & Co., 1887), defined the
parable as being "purposely intended to convey a hidden and
secret meaning other than that contained in the words
themselves, and which may or may not bear a special
reference to the hearer or reader." However, Townsend may
have been influenced by the 19th century expression, "to
speak in parables", connoting obscurity.
#+end_quote

Frank Burton has put together a collection of secular
parablesm called the Parables of Reason.
http://www.circleofreason.org/

We don't need to mimic 19th century verse for this.  Yes it
makes it feel biblical, but that actually just translates
into, "sounds like the King James Bible."



** TL;DR

Not entirely sure how to do this.  Big Hisory has some
fantastic works, but they are not really narratives in the
sense that origin stories are structured.  Cosmos comes
somewhat close in that it starts with us, zooms out to the
big bang and then works back to us -- later it shrinks
down.  At each step, there is a story of how each discovery
came about, the human story of the person/people behind it
and how it changed the paradigm that came before it.  This
is the way we teach science -- but is it the way we teach an
origin story?

The Bible too is structured somewhat the same way, starting
with creation, then the first people, and how things got
increasingly complex as societies grew more complex, as more
generations passed, with an increasingly complex history
behind them.

Pure origin stories are rather brief, little more than a
chapter in most myths.

The next problem is the very problem of universality -- it's
difficult to relate to a story where most of the key figures
will not be from your culture, and where large parts of the
story takes place far from where you live.

This is why that until two thousand years ago, when the
great monothesitic religions emerged around growing urban
centers under control of ever larger states, that religion
was very local, very specific, very personal.  There might
be some big gods, but most people worships their local gods,
rooted in their geography and experience.

We don't want our meta-origin story to tread on local
systems too much, otherwise it will come across as being
imperialisitic and foreign.

So in a sense, we should structure the origin story so that
it can be adapted to each locale, so the story maps to the
local, merging the local and the global.  This is how
religions spread.

There will be a number of different ways that this can be
shaped.  First around broad ethnic traditions, there are
cultural bands as you move from east to west, each is a
little more like it's neighbor on one side and a little less
than the other neighboring culture on the other.

SE Asia is a good model for this -- You have China on one
side, and India on the other, and all of the countries in
between are a spectrum between the two larger cultures.
Nepal is closer to India.  Burma is more Indian, than
Chinese.  Thailand is about in the middle equally influenced
by India and China.  Cambodia is slightly more Indian than
Siam as it held on to it's Hindu phase of history longer than
the Thai's who moved to Buddhism earlier.  Vietnam is as
close to China as Nepal is to India.

So we can have at least five different versions of the
origin story, with each being centered in a different
cultural tradition.

We then adapt for climate -- the climate where you live
shapes your relationship to the world and your attitude
towards it.  Cold climates produce very different cultures
from mild climates.  Cultures along the Pacific Rim have to
contend with earthquakes, volcanos, tsunamis and typhoons.
Polynesian culture is based around small islands that act
the same as oasis in desert climates -- nature is big, and
places for man are small.

The other side of climate is that flora and fauna are
different as is the geography, plains, savannah, rainforest,
hot dry desert, tundra, mountains etc.  All of these things
are the raw materials that go into the creation of a
mythological vocabulary. Our cultural archetypes map to what
is around us.

Next is to map to level of economic development that a
culture is in -- a lot of what we think of as a local
culture is actually part of a universal series of succession
stages that every culuture moves through as it develops.

Finally, we need to work out how to map technology to all of
this -- the concept of magic is universal and is closely
tied to cultural mythos it is practiced in.  This can become
a powerful interface to relating to and controlling
increasingly autonomous and ubiquitous technology that is
woven into our lives.

This is now getting away from this Canto which is the origin
story.

Putting this all together, the base story is the same, but
maps to different locales in the following ways:

  - Relative to Major Cultures: Chinese, Indian, Middle
    Eastern, European, Polynesian.
  - Map to local climate, flora, fauna and geography and
    cycles of nature.
  - Map to level of economic development
  - Map to technological processes and services as a magical
    interface.


----

I imagine that the text I write here is designed as a
template that can be generated with different local maps.

There will also be a universal culturally agnostic map for
people like me, who have no tribe or culture any longer.

I wonder how far this could be taken?  Could you create a
LOTR, Harry Potter or Star Trek map?  What about edge cases
of cultures which live in extreme environments which are
outside of the major cultural influences?  

How much do we allow maps to the monotheistic religions?
Monothesim is all about scale, generality and control and
change radically when adopted by cultures with highly
localized mētis.  The Japanese are buddhist, but have
retained a lot of Shinto animism.  The chinese also are
buddhist but strongly shaped by taoist/confucian traditions.

The Philippines adopted christianity, but their form of
Catholicism is very different from that in Europe.

My feeling at the moment is to emphasis to local, over the
invasive alien monothestic religion -- map to the deeper
parts of each culture that was there before they converted
and I think we will have something that will be very
attractive and natural to many people, non-threatening
(except to the fundementalists) and provide an alternative
to the extremists and fundementalists.  Over time it should
increasingly displace them.
