#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XXII. Origin Story Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* XXII. Origin Story Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/22/abstract.org
  :Created:   2018-06-03T18:32@Prek Leap (11.642600N-104.919210W)
  :ID:        0b43058e-ab37-4291-a3b9-4033ffa5ee90
  :VER:       581297602.563251229
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:DGV4-6100
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope

** TL;DR


Not entirely sure how to do this.  Big Hisory has some
fantastic works, but they are not really narratives in the
sense that origin stories are structured.  Cosmos comes
somewhat close in that it starts with us, zooms out to the
big bang and then works back to us -- later it shrinks
down.  At each step, there is a story of how each discovery
came about, the human story of the person/people behind it
and how it changed the paradigm that came before it.  This
is the way we teach science -- but is it the way we teach an
origin story?

The Bible too is structured somewhat the same way, starting
with creation, then the first people, and how things got
increasingly complex as societies grew more complex, as more
generations passed, with an increasingly complex history
behind them.
