#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 01. APPL Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 01. APPL Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/07/33/intro.org
:Created:  2018-05-04T18:28@Prek Leap (11.642600N-104.919210W)
:ID:       b6d16b7f-2393-40be-b18d-e8677479be42
:VER:      578705358.453190400
:GEO:      48P-491193-1287029-15
:BXID:     proj:OPG3-6422
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR

APPL makes up the reference building blocks for building any
given civilization at a given succession stage

Patterns are repeating themes in nature, design and human
behavior that when combined with other patterns strengthen
each other and create things that are larger than the sum of
their parts.

APL was divided into three parts, Towns, Buildings and
Construction.  But APL is a pattern language for
architecture and buildings.  For this to work it had to
define many patterns that more properly belonged to urban
planning, culture and governance though these were patterns
that supported the construction of beautiful buildings.

Our pattern language has a far broader scope; building an
antifragile civilization for mankind. 

APL style Patterns alone will not be enough to build a
civilization on.  For this reason we have five different
types of Patterns:

  - Metastructure : infrastructure as system
  - Pattern
  - Parameter
  - Thesis
  - Keystone
  - Entity   : person, place, event, object, concept, material
  - Element  : 
** Patterns
** Metastructure

Metastructures are infrastructure systems.  The global
value-chain is built on the Intermodal-Container
metastructure which uses standardized shipping containers as
an base-unit of regional and global transportation,
logistics, finance and interstate border crossing.  The
Internet using the TCP/IP protocol and the DNS & Bind address
resolution system is another metastructure.

Typically a Hoard combines and adapts a number of
Metastructure patterns for the scope and succession stage of
what the pattern is meant to cover.

This provides the big picture for infrastructure that all
other types of patterns fit within.

The tricky part is to ensure interoperability between
metastructures at different succession stages.

** Parameter

Constants are bedrock variables that define things that can
not be changed like the speed of light or dunbar's number.
They supercede what we want or what we would like and
provide empirical design limits.  No theses can =violate= or
contradict a =constant=.

#+begin_comment
The following files are in ~/proj/manifesto/  they need to
be moved to APPL, once we have worked out the structure and
file naming conventions.
#+end_comment

 - [[./manifesto/constant-speed-of-light.org][Speed of Light]]
 - [[./manifesto/constant-dunbar.org][Dunbar's Number]]
 - [[./manifesto/constant-millers-law.org][Miller's Law]] (7 plus or minus 2)
 - [[./manifesto/constant-divided-concurrent-goals.org][Divided Concurrent Goals]]
 - [[./manifesto/constant--shared_intentionality.org][Shared Intentionality]]

** Theses

Scopic Theses are declarations that provide a foundation for
a =civil ruleset= for people to live and cooperate with each
other.  Our theses is a social fiction that defines how we
/want/ to live and behave with each other.

 - [[./manifesto/theses-preamble.org][Preamble]]
 - [[./manifesto/theses-notes.org][Theses Notes]]


** Entity Models
** Keystone Entity Model

The bulk of the Primer will be made up of keystone reference
items.

Many of these will be prescriptive and descriptive designs
and processes.  They will be organized using the following
Entity Model.

#+begin_example
  - Keystone (concept)
    - Variation (expression)
      - Design (manifestation)
        - Prototype (instance)
#+end_example

We hope to avoid the committee rat trap, and ensure that
keystones are as free of jargan as possible, be an iterative
approach, rather than a committee concensus based approach
with each change or correction or addition slowed down by
politics and different motivations.

A lot of the problems with standards developement will
actually be made easier using the entity model, because
different groups can develop their own Variations, even fork
variations without permission and proceed however they wish.
Then, hopefully we will have a mechanism for choosing the
the best variations as normative references for developing
designs.

A good way of thinking about the development model is as a
GitHub/GitLab type collection of repositories which anyone
can contribute to.  All repos will be under an open licence
and can be forked and adapted in any way people wish.

*** Keystone (concept)

A Keystone is a concept representing the design or process.
Like the Work entity in FRBR.  Unlike the Work entity the
Keystone entity will be closer to a working specification
for what it describes, along similar lines that you see in
W3W early stages of specification development.  The keystone
should be clear, jargon free and include the following
elements:

  - description
  - functional requirements 
  - use-case scenarios
  - data sets for use for testing to see if a
    variation/design/prototype meets those requirements
  - code for running tests based on that data.

*** Variation (expression)

A Variation is an expression of a Keystone which can take
any approach it wants to epressing the keystone so long as
it is compliant with the functional requirements and is
working towards meeting all use-case scenarios.

In many cases, the early variation iterations will fall far
short of the initial goal and will remain as a
work-in-progress, or draft, before finally becomeing a
recommendation.

A Variation is not an actual design, designs can be used to
build something that works in the real world.  Rather, a
Variation is sort of like a patent application that shows
how something is supposed to work.

*** Design (manifestation)

A manifestation is an actual design that can be used to
build something.

All designs are meant to be part of a specific base-line
succession stage, this means that the design must include
everything needed to be built at that stage.  Separate
menifestations will be created for more advanced stages.

So for example, a design for a hammer that will work at the
tool stage (and an early stage of the tool stage) will need
a pictorial design that can be understood by an illiterate
person.  Another design manifestion will be for a literate
person with access to acurate measuring devices, better
quality materials and manufacturing processes for use in the
clockwork and electric stages.  Finally, a design
manigestation will be required that include CAD files, as
well as the software for an automated system system to build
the hammer will be required as well.

Since there will differences in the media used for each type
of manifestation, each design will include documentation for
the correct and safe use of the built design.

*** Prototype

The prototype will mostly be documentation for showing the
end results of building the design using these different
design manifestations for each stage.


** Pace-Layer Model

APPL is organized around Steward Brand's six-layer /Pace
Layer/ model which is based on the observation that
different things change at different speeds.  The model
began as an observation that buildings can be thought of as
being made of multiple layers with each changing over time
at different speeds.

Brand's model was made up of six parts:

  - 6 Fashion
  - 5 Commerce
  - 4 Infrastructure
  - 3 Governance
  - 2 Culture
  - 1 Nature 


Our language will be called /A Pace-Layer Pattern Language/
(APPL), which will be made up of 9 parts that combine
Brand's and Saffo's Pace Layer models into one.

This table shows slow to fast as pace layers, but it should
be remembered that layers 1-4 are nested within each other
and the Anthros layers are a subgroup of bios.

  |----------+------------------+-------------|
  |          | 9 Fashion        | agora       |
  |          | 8 Commerce       | stoa        |
  | Anthros* | 7 Infrastructure | polis       |
  |          | 6 Governance     | pynx & bema |
  |          | 5 Culture        | muthos      |
  |----------+------------------+-------------|
  |          | 4 Anthros*       |             |
  |          | 3 Bios           |             |
  | Natura   | 2 Lithos         |             |
  |          | 1 Helios         |             |
  |          | 0 Cosmos         |             |
  |----------+------------------+-------------|


This is only one POV, we need to present this as how these
different things form a hierarchy so that it's understood
that anthros is a subset of bios and not seperate.

The 9th group called /0 Meta/ contains patterns that apply to
all layers which will be given the number 0 below /1 cosmos/
which is number 1.

Each layer has a different =Rate of Change= (ROC) with
/Cosmos/ at the bottom being the slowest and /Fashion/ at
the top in a constant state of churn, changing at a staccato
rapid-fire beat.


*** Pattern Keys

Patterns will have keys (unique ids) in the form of:

   APPL[layer#]:[Pattern#]

So the first pattern in the Meta group would have the key
APPL0:0001.

*** Steward Brand and Paul Saffo: Pace Layers Thinking -- notes

 - [[http://longnow.org/seminars/02015/jan/27/pace-layers-thinking/][Pace Layers Thinking]] | Stewart Brand & Paul Saffo | SALT
 - [[Painted.Woman.2017][Pace Layering: How Complex Systems Learn and Keep Learning]]

  slippage between layers, negative feedback looks

    - turbulence
    - viscosity

  young are concerned with fast layers -- especially fashion


  | Fast layers              | Slow layers          |
  |--------------------------+----------------------|
  | learns                   | remembers            |
  | proposes                 | disposes             |
  | absorbs shocks           | integrates shocks    |
  | discontinious            | continious           |
  | innovation/revolution    | constrainy/constancy |
  | *gets all the attention* | *has all the power*  |
 
I find it interesting that Alexander seems to be aware of
all of this, but never takes it on directly.  He has always
been focused on creating new buildings where you can start
with a clean slate and do things the right way.  But most of
the time that's not what you can do.  He always talks of
gradually moving from what is existing to how you want
things to be but doesn't address any of that in APL as much
as he could have.  We build on top of what came before.
There is no clean slate -- thinking that you can is the
architect's hubris.

The moments when you can do tabla rosa are few and far
between.  The great fire of london, a tsunami in Japan or SE
Asia wipe everything out, even cadastral maps (because the
property holders are gone as well as the buildings).  We
should fear such opportunities more than wish for them,
because unless you start small and grow bottom up in an
organic manner we will /always/ fuck it up.

But it's even worse than that because when say Myanmar or
Dubai backed by a mountain of cash have tried to clean slate
things they try to jump over all of the intermediate steps
that leads to functional, beautiful human settlements.

Alexander has essentially made the case to abolish the whole
class of architects and architecture as we know it today and
go back to the older concept of the master builder.

The big name architects are too focused on originality and
have largely forgotten craft and that structures are a part
of the environment (context) that they are built in and are
built for mostly pedestrian functions.  They put the focus
of vision on originality rather than achieving the purpose
the building is meant to fill.  The small name architects
are often just as bad or worse because they are just
knocking out structures at a distence according to
specifications provided by a customer that are based on
lowest common demoninator metrics and contruction financing
and practices that are estranged from the purpose that the
building is meant to fulfill.


**** Paul Saffo's Pace Layers

 - Anthros
 - Bios
 - Lithos
 - Cosmos

So if we combine this with Brand's model we get:

A General Theory Of Bureaucracy (1961)
Elliott Jaques

https://en.wikipedia.org/wiki/Elliott_Jaques

/Time span of discretion/ that a manager can be ranked 

seven layers on timespan of 

time from formulate a plan to it's execute

the lower the number the shorter the timespan



**** Japanese mayor (story from audience member)

An classic example of long term application of /timespan of
discretion/.

http://www.dailymail.co.uk/news/article-1386978/The-Japanese-mayor-laughed-building-huge-sea-wall--village-left-untouched-tsunami.html
http://blog.nihongo-pro.com/2011/04/mayors-vision-saves-japanese-village.html

Was mayor for over 40 years and in that time went against and fought
to build a tsunami barrier for this town.  He died before it was ever
used but the barrier saved the town.

**** Rice on Chessboard

People don't grok exponential growth

pace layers turn Hockey Sticks into S-Curves

**** The Apsara of Context, Scale, Time and Change

Though not discussed in the talk, the other two things that
we can't grok are /size/ and /time/ at scales that are
outside of human empirical limits.

Taken together /rate-of-change/ (ROC), /level-detail/ (LOC)
and /point-of-view/ (POV) are the three things that define
the context of almost anything.  They are also are our
biggest blindspots when any of the three fall outside of
human scales and comprehension.

Is blindspot the right term?  Failure of imagination?
Cognitive limitation?  hmmm.

Relativity is based on the concept that what is real is
dependent on the context of the observer -- this is just
another formulation of that concept from a different POV.

One of the Meta goals of our project is to find ways to help
us as individuals and collectively to make these things
comprehensible so that we act on them when it is necessary.

Climate Change is a problem because we can not comprehend
the problem that we have created for ourselves.  The Long
Now Foundation focuses on long term thinking and
perspectives but scale and change are equally important.  I
know that they think that's baked into their mission but its
worth spelling out.

*** Nature

We divide nature into the /1 cosmos/, /2 lithos/ (as in the
lithosphere) and /3 bios/ as in the biosphere.

Cosmos includes everything in the universe down to planetary
or planetoid scales.

Lithos (meaning rock) is any planet or planetoid where
mankind might end up hanging his hat or exploiting in some
manner.  Lithos includes artificial planetoids that are
meant to be habitats including everything from the ISS to
large scale habitats housing thousands or even millions of
people.

Bios is any biosphere that supports life that is contained
in a /lithos/.

Putting it all together:

The Universe is the Cosmos.  But more practically, the
pattern language will be concerned with our Solar System as
a /system/ which includes the Sun, planets, planetoids
orbiting it and the mechanics of moving around in it and
dealing with things like solar and cosmic radiation, light,
heat and electromagnetism and how all of this pertains to
building and maintaining an life and specifically an
antifragile distributed civilization.

The lithos is any physical inanimate natural or manmade body
that is exploited or used to create a habitat irrespective
of whether the body is habitable.

On earth the core, mantel and crust would be the lithosphere
and the biosphere is the thin envelop made up of an
atmosphere and a hydrosphere where life can exist.

The structure and shell of the ISS would be the lithos and
the atmosphere within and the machinery for maintaining
pressure, temperature and scrubbing C0^2 would be its
biosphere.

/Anthros/ layers are anything within a biosphere and follows
Steward Brand's five layers, culture, governance,
infrastructure, commerce and fashion.  There is always a
tradeoff when you define models like this because you are
indicating organization for the purpose of understanding
something that doesn't exist.  The layers are a useful way
of understanding how different aspects of civilization that
change at different speeds interact with each other.



----

We are a part of both realms and we impact and are impacted
by both realms.  We are part of nature, there is no them and
us.  This is very difficult concept for modern man to
comprehend because we have convinced ourselves that we are
exceptional and outside of nature.  Gravity applies to us
the same way as every other thing in the universe.  Jump out
of a airplane without something to slow us down like a
parachute and we will splat just like a watermelon.

A city is part of nature as much as the most isolated meadow
in on the Tibetan Plateau.  Both belong to and depend on the
same pressurized atmosphere, and protection from solar and
cosmic radiation to support life.  You can say that the
meadow is nature uneffected by man, but that isn't exactly
true either.  Mankind has been shaping the world for tens of
thousands of years using fire, long before the first
civlizations emerged in the alluvial wetlands of Mesopotamia
that fundementally changed the biodiversity of broad swaths
of the planet, especially megafuana.  Cliff paintings
overlooking the Mekong River portray a number of different
types of megafauna that are now long extinct.  The most
likely explanation for the extinction of species like pygmy
rhinos and the giant sloth is man.  Other megafauna, which
could reproduce quickly and were more fleet of foot than the
sloth such as antelope, deer, caribou and elk flourished as
a reliable food source managed by using fire to shape
habitats which encouraged those species.  It can be argued
that mankind terraformed the planet with fire.

/Nature/ patterns are concerned with Mankind's interaction
with nature, both physical and living.

The degree of that interaction can be divided into wild and
cultivated.  We used to be quite good at managing the wild,
but got lost when we turned to pure cultivation and
eventually began to see the wild as something in opposition
to and an enemy of the cultivated.  In modern times, those
who call themselves environmentalists and conservationists
are no less guilty of this false dichotomy.  We need to stop
thinking in terms of us vs them, nature knows no such
divisions.  We can not become one with nature, because we
were never apart from nature in the first place.

When talking about the realm of life we will use the concept
of /habitats/ that contain /biospheres/ that are sometimes
divided into /biomes/ that contain life.  At the time that
this is being written there are only two biospheres that we
are aware of, the planetary biosphere that envelops Earth
and a tiny biosphere in low earth orbit called the ISS
(International Space Station).  Eventually there will be
more biospheres, a handful at planetary scales and many
smaller artificial ones.  The nature of how mankind shapes
and manages those biospheres is the subject of this pattern
pace-layer.

Change at planetary scales both physical and biological take
place in geological time scales.  The tectonic plates of the
Earth inch together and apart so slowly even the Ents would
consider them to be slow.  The evolution of life largely
takes place in time scales that dwarf any one species.
Occasionally something like an asteroid impact, the eruption
of a supervolcano or other event triggers massive change,
but the impact of that event often takes far longer than we
might think.  The dinosaurs didn't all die off within days
or months or even centuries after the asteroid hit the
Yuccatan.  A true planet killing event has yet to happen to
Earth.  We know this because we are here to talk about it.
But there were a couple of times that things were close.



 

** References

