#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 6. Boundries Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]]


* 6. Boundries Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/06/intro.org
:Created:  2018-05-01T17:27@Prek Leap (11.642600N-104.919210W)
:ID:       993594f2-9332-4da3-b9d6-84fcb5800c8b
:VER:      578442504.546867026
:GEO:      48P-491193-1287029-15
:BXID:     proj:YRA3-4585
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

From here we can then begin to discuss the limitations of Sapiens and
of the greater Mankind.  There are no shortage of planned utopian
visions for the future of Mankind.  Most are build on little more than
cardboard foundations, or are little more than flights of fancy.  As
thought experiments such uttopian visions are both useful and
illustrative tools.  But every so often some of these Utopian visions
have been taken quite literally to be built verbatim, dogmatically
constructing them according the letter of whatever visionary scripture
they were based on.  Most have been religious, but some secular
utopias which are one -ism or another are often even worse.  In each
case, the utopian vision was not built on a solid foundation that made
allowances for and respected man's nature.  We are clever apes, who in
evolutionary terms have barely left the savvanah from where we evolved
and the ecological niche we are designed to inhabit through blind
evolutionary forces.  We are capable of being rational, but all too
often are not.  We have the capacity for great empathy, love and
compassion but easily give in to primal instincts based on fear and
threat through fight or flight.  We still are in the very early stages
of beginning to discover what we are, our weaknesses and strengths,
our bias's and cognitive and phyisical limitations.  In short, we are
very much a work in process and are not capable of living in any
Paradise or Utopia no matter how pleasant -- we'll manage to screw it
up.  So we must constantly strive to understand ourselves better, and
to design social structures which take these hard facts about
ourselves into account and protect ourselves from our less than noble
natures.

** TL;DR
** References

