#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Purpose (chapter) 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Purpose (chapter)
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/01/06/ww-purpose.org
  :Created:   2018-06-07T08:43@Prek Leap (11.642600N-104.919210W)
  :ID:        f3abe01d-a345-4de8-9967-62f6d8a003f8
  :VER:       581607892.703214635
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:OLX7-3537
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

   - Care
   - Practice
   - Rest

Taylor-style factories which strip workers down to little more than
single-task human machines.  Humans aren't designed to stay in one
place and do the same repetitive task over and over for days, years
and careers.  Just as animals in captivity, humans in industrial
production, be it in the factory or the office, are deprived of
stimulous, confined to a small space, are deprived of normal social
intercourse, removed for most of their waking hours from family and
community, and removed from nature.

This results in 

#+begin_quote
I was in Africa last year and saw a lot of animals in the wild that
I'd only seen in zoos before. It was remarkable how different they
seemed. Particularly lions. Lions in the wild seem about ten times
more alive. They're like different animals. I suspect that working for
oneself feels better to humans in much the same way that living in the
wild must feel better to a wide-ranging predator like a lion. Life in
a zoo is easier, but it isn't the life they were designed for.

— cite:graham:2008boss
#+end_quote

