#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Purpose (chapter) 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Purpose (chapter)
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/01/06/ww-purpose.org
  :Created:   2018-06-07T08:43@Prek Leap (11.642600N-104.919210W)
  :ID:        f3abe01d-a345-4de8-9967-62f6d8a003f8
  :VER:       581607892.703214635
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:OLX7-3537
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

   - Care
   - Practice
   - Rest

Taylor-style factories which strip workers down to little more than
single-task human machines.  Humans aren't designed to stay in one
place and do the same repetitive task over and over for days, years
and careers.  Just as animals in captivity, humans in industrial
production, be it in the factory or the office, are deprived of
stimulous, confined to a small space, are deprived of normal social
intercourse, removed for most of their waking hours from family and
community, and removed from nature.

This results in 

#+begin_quote
I was in Africa last year and saw a lot of animals in the wild that
I'd only seen in zoos before. It was remarkable how different they
seemed. Particularly lions. Lions in the wild seem about ten times
more alive. They're like different animals. I suspect that working for
oneself feels better to humans in much the same way that living in the
wild must feel better to a wide-ranging predator like a lion. Life in
a zoo is easier, but it isn't the life they were designed for.

— cite:graham:2008boss
#+end_quote



** References 
  *Occupational Stress*

  - Branton, P., A field study of repetitive manual work in
    relation to accidents at the work place, International
    Journal of Production Research, 8(2), 93–107 (1970).
    http://dx.doi.org/10.1080/00207547008929833
    cite:branton:1970repetitive-work
  - Kossek, E., Ellen, , Ozeki, , & Cynthia, , Work-family
    conflict, policies, and the job-life satisfaction
    relationship: a review and directions for organizational
    behavior-human resources research., Journal of Applied
    Psychology, 83(2), 139–149 (1998).
    http://dx.doi.org/10.1037/0021-9010.83.2.139
    cite:kossek:1998work-family

  *Boredom*

  - Hill, A. B., Work variety and individual differences in
    occupational boredom., Journal of Applied Psychology,
    60(1), 128–131 (1975).
    http://dx.doi.org/10.1037/h0076346
    cite:hill:1975work-variety
  - Toohey, P., Boredom: a lively history (2012), : Yale
    University Press.
    cite:toohey:2012boredom
  - Pezze, B. D., & Salzani, C., Essays on boredom and
    modernity (2009), : Rodopi.
    cite:pezze:2009bordom
  - Hooff, M. L. v., & Hooft, E. A. v., Boredom at work:
    proximal and distal consequences of affective
    work-related boredom., Journal of occupational health
    psychology, 19(3), 348 (2014). 
    cite:vanhoof:2014boredom
  - Fisherl, C. D., Boredom at work: a neglected concept,
    Human Relations, 46(3), 395–417 (1993).
    cite:fisherl:1993boredom
  - Mann, S., /Boredom at work/ (2007).
    cite:mann:2007boredom
  - Brissett, D., & Snow, R. P., Boredom: where the future
    isn’t, Symbolic Interaction, 16(3), 237–256 (1993).
    http://dx.doi.org/10.1525/si.1993.16.3.237
    cite:brissett:1993boredom
  - Hill, A. B., & Perkins, R. E., Towards a model of
    boredom, British Journal of Psychology, 76(2), 235–240
    (1985).
    http://dx.doi.org/10.1111/j.2044-8295.1985.tb01947.x
    cite:hill:1985theory-boredom

  *Human Captivity*

  - Massoglia, M., & Pridemore, W. A., Incarceration and health,
    Annual Review of Sociology, 41(1), 291–310 (2015).
    http://dx.doi.org/10.1146/annurev-soc-073014-112326
    cite:massoglia:2015incarcertation
  - Wildeman, C., Incarceration and health, Emerging Trends
    in the Social and Behavioral Sciences, (), 1–9 (2015).
    http://dx.doi.org/10.1002/9781118900772.etrds0179
    cite:wildeman:2015incarceration
  - Heron, W., The pathology of boredom, Scientific
    American, 196(1), 52–56 (1957).
    http://dx.doi.org/10.1038/scientificamerican0157-52
    cite:heron:1957boredom
  - McKenzie, I. K., The Stockholm Syndrome Revisited,
    Journal of Police Crisis Negotiations, 4(1), 5–21
    (2004).  http://dx.doi.org/10.1300/j173v04n01_02
    cite:mckenzie:2004stockholm

  *Animal Captivity*

  - Clubb, R., & Mason, G., Animal welfare: captivity effects on
    wide-ranging carnivores, Nature, 425(6957), 473 (2003).
    cite:clubb:2003animal-welfare
  - Erwin, J., Mitchell, G., & Maple, T., Abnormal behavior in
    non-isolate-reared rhesus monkeys, Psychological Reports, 33(2),
    515–523 (1973).  http://dx.doi.org/10.2466/pr0.1973.33.2.515
    cite:erwin:1973abnormal
  - Hosey, G. R., & Skyner, L. J., Self-injurious behavior in zoo
    primates, International Journal of Primatology, 28(6), 1431–1437
    (2007).  http://dx.doi.org/10.1007/s10764-007-9203-z
    cite:hosey:2007self-injurious
  - Haque, A., Depression in caged animals: a study at the national
    zoo, kuala lumpur, malaysia, Zoo’s Print Magazine, 26(11), 25–29
    (2011).
    cite:haque:2011depression
  - Hediger, H., Wild animals in captivity (1950), :
    Butterworth-Heinemann.
    cite:hediger:1950wild-animals
  - Kleiman, D. G., V., K., Thompson, , & Baer, C. K., Wild mammals in
    captivity: principles and techniques for zoo management (2010), :
    University Of Chicago Press.
    cite:kleiman:2010mammal-captivity
  - Meagher, R. K., & Mason, G. J., Environmental enrichment reduces
    signs of boredom in caged mink, PLoS ONE, 7(11), 49180 (2012).
    http://dx.doi.org/10.1371/journal.pone.0049180
    cite:meagher:2012environmental
  - Pitsko, L. E., /Wild tigers in captivity: a study of the effects
    of the captive environment on tiger behavior/ (2003).
    cite:pitsko:2003wild
  - Wells, D. L., A note on the influence of visitors on the behaviour
    and welfare of zoo-housed gorillas, Applied Animal Behaviour
    Science, 93(1-2), 13–17 (2005).
    http://dx.doi.org/10.1016/j.applanim.2005.06.019
    cite:wells:2005influence
