#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Volume IX Articles Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]]


* Volume IX Articles Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/09/09/intro.org
:Created:  2018-04-24T10:14@Prek Leap (11.642600N-104.919210W)
:ID:       c2803cbe-e131-42de-a794-0a8c3ef35495
:VER:      577811710.843989301
:GEO:      48P-491193-1287029-15
:BXID:     proj:HUB3-7112
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

For a decentralized system to work, it must also have negative
feedback loops in place that keep it decentralized and egalitarian,
this has to be voluntary, with the members who agree, getting in
return a better life and would.  It must be affirmed and reinforced
every day or it will be lost.

That in the heart of the new social contract. No more zero sum
anything, the only zero sum game is the biggest one of all, humanity
and civilization we all win together or we all fail together.  And
anyone who thinks we're not in it together is delusional.

This why the theses, rule sets and articles are so important, we all
get rights, but we all equally except that we also have a duty to each
other and to our future.  You will loose your rights if you neglect
your duty.

Mindless consumerism only has selfish gratification at its core, no
purpose or meaning, and the lie that gratification is the same as
happiness

** References

  - American Humanist Association, /Humanism and its aspirations: humanist
    manifesto iii./ (2003).
    cite:aha:2003humanism
  - United Nations, Universal declaration of human rights, UN General
    Assembly, (), (1948).
    cite:un:1948udhr
  - Wikipedia, /Universal declaration of human rights --- Wikipedia,
    the free encyclopedia/ (2018).
    cite:wiki:2018universal-declaration
  - Keen, A., How to fix the future: staying human in the digital age
    (2018), : Atlantic Monthly Press.
    cite:keen:2018fix-future 

