#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 8.1 Introduction Volume VIII Curriculum
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] [[[./index.org][up]]]

* 8.1 Introduction Volume VIII Curriculum
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/08/intro.org
:Created:  2018-04-24T11:06@Prek Leap (11.642600N-104.919210W)
:ID:       69d19e03-c646-4813-b123-712e3572ab76
:VER:      577814843.463742983
:GEO:      48P-491193-1287029-15
:BXID:     proj:YTR3-6048
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

This volume is concerned with how we learn as individuals
and as societies.  How do we learn.  How do we pass
knowledge and skills on to others.

The idea is that because of the exponential ROC, knowledge
becomes obsolete very quickly.  How to keep up?  While
disciplines and technologies are born and vanish in a
fraction of a person's career.  Learning must change from
being a place, as it became in the industrial revolution,
where schools became factories for providing basic skills
that people needed to drive the indusrial engine.  The base
skill set was not the high, so it really didn't take that
long to teach it.  That doesn't explain why education became
such a long process.  That happened because once child labor
was effectively banned, and parents were at work in
factories and offices for the majority of the day, children
really had no supervision or purpose in the home any
longer.  So schools became day care for children.

Children need to be reintegrated into society, not
sequestered for the better part of two decades in Lord of
the Flies cultures that were separated from the rest of the
world.

Learning needs to become an activity that happens
everywhere, starts at birth and ends in the grave.

This volume is about building generative learning frameworks
that prepare people to become useful citizens in society
(the goal of a liberal education) and then provide the
cognitive skills, cognitive tools, core knowledge and
practical skills that are mastered to become part of society
and provide meaning and purpose to people's lives.

** TL;DR


** References

Backward Design

  - Grant Wiggins, J. M., The understanding by design: guide
    to creating high-quality units (2011), : Association for
    Supervision & Curriculum Development.
    cite:grant:2011understanding-design
  - Wiggins, G., & McTighe, J., What is backward design,
    Understanding by design, 1(), 7–19 (1998).
    cite:wiggins:1998backward
  - Wikipedia, , /Backward design --- Wikipedia, the free
    encyclopedia/ (2018).  cite:wiki:2018backward-design
