#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Awe (Chapter)
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Awe (Chapter)
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/07/ww-awe.org
:Created:  2018-05-11T16:40@Prek Leap (11.642600N-104.919210W)
:ID:       dfc40678-8cfb-4060-b36d-cf017656cf7c
:VER:      579303670.590707272
:GEO:      48P-491193-1287029-15
:BXID:     proj:HRX2-6446
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

Awe is a kind of recognition mechanism.  It stops us cold,
forced to confront things that are beyond our comprehension,
reminding us of just how small and fragile we are in the
larger context of things.

Sometimes awe invoke fear, even terror.  I remember going to
a pleasant white sand beach in Phuket with someone who had
grown up inland and had never been in physical proximity
with the ocean before.  For me, who had grown up not too far
from the cold, chaotic and often violent Atlanic ocean, the
Andaman Sea was soothing and calm.  For her, the vast
potential power she could feel in the gentle waves lapping
her feet unnerved her.  That same beach some five years
later bore the impact of a 5-6 meter high wave in the 2004
Indian Ocean Tsunami that killed in total over 230,000
oeioke abd displaced another 1.74 million.  My friend was
right.

But awe just as often invokes wonder and an overwhelming
sense of the sublime.

In this sense, awe is an important mechanism for reorienting
ourselves and our perspective of the world around us.

Religion's are deft at invoking awe in both senses of
sublimity and terror.  It is an important function that is
largely lost in an increasingly secular civilization which
gives tends to give people the impression that Man has
conquered Nature and has nothing to fear.  It's only
periodic natural catasrophies that shake us from our
complacency but it's not enough.  Except for those directly
effected, hollywood special effects in disaster films have
dulled the impact of watching natural disasters unfold in
real time in online videos and television.

This is dangerous, as it discounts the very real threats in
our lives, and amplifies other threats that are taken far
more seriously.

A key goal when invoking awe should always be to make a
connection between what is recognized and what is personal
that fosters both reflection, empathy and humility.

Religions are good at leveraging the mechanism to at the
least reinforce dogmatic belief and at best instill ethical
a moral values and behavior.

But spiritial contexts are only a part of the role that awe
plays in our lives and in societies.  Awe is important to
understand and integrate scientific truths, to connect
narratives that make up liberal arts education that prepares
people to be equiped to live and participate in a free
society.

There is a spiritual dimension in all human lives and belief
systems, including secular and non relgious or epecially
atheists.  

States institutions invoke awe in a variety of contexts
through the show of force, both through the collective will
demonstrated by people wearing identical uniforms and
displaying weapons, marching in lock step.  There is no
question that provoke one, will provoke them all.

Institutional architecture is chock full of devices to
instill awe, from Christian Catherdrials, Egyption Pyramids,
to the lofty Parthenon standing tall above the city for all
to see.  Executive, judicial and legislative buildings are
all made on grand scales that make the individual feel
small, but also a sense of belonging and safety.  Museums,
opera houses, statues and monuments, grand bridges and even
tunnels all are designed to invoke some sense of awe.

Costume and furniture contribute as well.  Uniforms not only
indicate collective will of armies, but hierarchy within
organizations as well, from the judges whig and robes, to
crowns and sceptors of monarchs to big hats, medals,
medallions a shimmer in bright color, the sparkle of gem
stones and metallic reflection of precious metals.

Most institutional structures leverage awe to some degree.
Banks buildings, even if they are relatively small rural
branches in Thailand are often large structures that might
be bland but still employ sweeping staircase entrances, and
cathedral ceilings to project authority, power and trust in
their ability to safeguard the wealth entrusted to them.

Finally, awe fosters both empathy for others and humility.



** TL;DR

#+begin_quote
Social psychologists Dacher Keltner and Jonathan Haidt
assert that two fundamental features are present in all
cases of awe: perceived vastness and accommodation.
Vastness applies obviously to such things as the immensity
of the scale of the universe, a central interest of Big
History, but also to anything that appears larger than the
self, or the self ’s ordinary frame of reference. This
includes unequal social status, such as awe of royalty and
fame, seen today in our cult of celebrity. The second
characteristic of awe identified by Keltner and Haidt,
accommodation, refers to the necessity created by “an
inability to assimilate an experience into current mental
structures.

— Neal Wolfe, The Case for Awe (2015)  p.338
  cite:behmand:2015teaching
#+end_quote


#+begin_quote
Job’s direct challenge regarding God’s existence and ethical
intentions is thus met with an indirect response, wherein
the deity goes on at length about how little humans know of
anything. Fragile, limited creatures that they are, how can
they possibly understand the ways of God?  he demands. And
given their ignorance, what right do they have to use such
words as undeserved and unmerited? There are untold things
about the galaxy that mankind cannot properly interpret and
upon which, therefore, it ought not presume to impose its
flawed logic. Human beings did not bring the cosmos into
being and, despite their occasional feelings to the
contrary, they do not control or own it. God tries to shake
Job out of his preoccupation with the events in his own life
by drawing his attention to the immensity and variety of
nature. He evokes a sweeping vision of the totality of
existence, from the foundation of the earth to the tracks of
the constellations, from the heights attained by a hawk in
flight to the labour pains of a mountain goat, in the hope
of instilling in the man from Uz a redeeming sense of awe.

The strategy works: Job is reminded of the scale of all that
surpasses him and of the age, size and mystery of
space. God’s whirlwind, and the sonorous, sublime words he
speaks, excite a pleasing terror in his audience, a sense of
how petty are man’s disasters in comparison with the ways of
eternity, leaving Job – and the rest of us, perhaps – a
little readier to bow to the incomprehensible and morally
obscure tragedies that every life entails.

— cite:botton:2013religion-atheists
#+end_quote


** References

  - Behmand, M., Burke, T., & Simon, R. B., Teaching big
    history (2015), : University of California Press.
    cite:behmand:2015teaching
  - Buber, M., & Smith, R. G., I and thou, New York:
    Scribner, (), 11 (1958).  cite:buber:1958i-and-thou
  - Elkins, D. N., Reflections on mystery and awe, The
    Psychotherapy Patient, 11(3-4), 163–168 (2001).
    http://dx.doi.org/10.1300/j358v11n03_12
    cite:slkins:2001reflections
  - Keltner, D., & Haidt, J., Approaching awe, a moral,
    spiritual, and aesthetic emotion, Cognition \& emotion,
    17(2), 297–314 (2003).
    cite:keltner:2003approaching
  - Andresen, J., Awe and the transforming of awarenesses,
    Contemporary Psychoanalysis, 35(3), 507–521 (1999).
    http://dx.doi.org/10.1080/00107530.1999.10746397
    cite:andresen:1999awe
  - Shiota, M. N., Keltner, D., & Mossman, A., The nature of
    awe: elicitors, appraisals, and effects on self-concept,
    Cognition & Emotion, 21(5), 944–963 (2007).
    http://dx.doi.org/10.1080/02699930600923668
    cite:shiota:2007nature-awe
  - de Botton, A., Religion for atheists : a non-believer's
    guide to the uses of religion (2013), : Knopf Doubleday
    Publishing Group;Signal.
    cite:botton:2013religion-atheists
