#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Arc
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

* Arc
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-arc.org
:Created:  2018-04-10T11:10@Prek Leap (11.642600N-104.919210W)
:ID:       4ff49df1-cc2e-4d08-bc05-abbd3dbc5c66
:VER:      576605474.319722695
:GEO:      48P-491193-1287029-15
:BXID:     proj:JKO7-1781
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

After that is the Archive of all recorded memory and
experience.

Arcs are designed to collect, organize and filter material
over very long time frames.  At set intervals, material in
collections is evaluated and filtered.  This could be
something like every 1, 10, 100 and 1,000 years.

Arcs can be either public or dark -- dark arcs are not
directly accessible and will only respond to requests for
things that have been lost.  Dark arcs will also monitor
public arcs to see what is missing and make that material
available to be found and added.

Dark arcs will be part of the slow internet -- running at
negative bandwidth speeds -- -1G, -2G, -3G etc speeds, as
slow as -5G.

After a massive loss of recorded knowledge after a disaster,
war or other temporary sanity, dark arcs will determine when
people are ready to have that lost knowledge restored.


** Table of Contents

