#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Introduction Volume V
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] | [[[./index.org][index]]]

* Introduction Volume V
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-intro-vol-5.org
:Created:  2018-04-11T18:12@Prek Leap (11.642600N-104.919210W)
:ID:       2e0c6679-005a-4e1e-b1ec-29c5b045c693
:VER:      576717236.153570038
:GEO:      48P-491193-1287029-15
:BXID:     proj:HEV0-7834
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

Volume V outlines the major components in the process of
building a civilization and the workflow between each
component.


*** Warp & Woof
Warp & Woof defines the principles, assumptions and
concepts that the system is based on.

*** A Pace-Layer Pattern Language (APPL)
A Pace-Layer Pattern Language defines archetypal patterns
that can be combined and adapted to build a civilization.

*** Hoard
Hoard is the source-code, which pulls together all of
the pieces from APPL adapts them into a system that
works together.

A Hoard doesn't only pull elements from APPL, but it should
be basing it's overall organization on Metasystems,
Patterns, Parameters, Theses and Keystones.  And if new ones
are developed that can be broadly applied they should added
to APPL and the derive specific variations in the Hoard.

But not everything is a Pattern or fits belongs in APPL.
There will be large components that will be based on broad
patterns but will be large composed works in their own
right.  Some of these might be of use in one or more Hoards.

Where are these in the larger scheme of things.  The two big
ones that come to mind are the first two parts of a Hoard,
an origin story and curriculum.  These should be based on 



*** Primer
Primer is the compiled, running production version of the
Hoard.  Changes are made to the Hoard and then merged with
the Primer using a rolling continious release mechanism.
The primer is a bit like a genome, the RNA that translates
the DNA into the Hoard into what it describes.

*** Middle
Middle is the larger physical and informational
infrastructure that is generated from the Primer. Middle is
the day to day operation and management.  You can think of
Middle as being the body that was generated from your DNA.
In most cases, things that happen in your body don't have
any effect on your DNA, but in rate instances it might,
especially when you combine your DNA with someone elses to
produce offspring.

*** Arc
Arc is designed to be outside of the entire system, which
contains the collected recorded memory and experience of a
civilization.  All the books, news stories, software,
tweets, emails, transaction logs, pictures, medical records
etc. are all collected by ARC.  Over time, ARC consolidates,
summarizes, discarding duplicates and identifying things
that are important to be remembered indefinately.  But this
is a very slow process measured in decades, centuries and
millennia.  Arc is the memory of all civilizations and so is
an intimate inseparable part of any civilization but it is
also outside and above it and designed to survive every
possible threat that can be concieved.  ARC is
self-replicating, self-supporting, it is both completely
open and transparent but it is also secret so that it can
survive everything from natural catastrophes, benign
neglect, temporary instanity of those who want to destroy or
rewrite the past.
