#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XXIV. Time Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* XXIV. Time Introduction
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/34/intro.org
  :Created:   2018-06-04T18:04@Prek Leap (11.642600N-104.919210W)
  :ID:        d087d4b8-4bb0-4ef1-922b-f524e1e63009
  :VER:       581382331.496705127
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:ETF4-7548
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

#+begin_quote
Our units of temporal measurement, from seconds on up to months, are
so complicated, asymmetrical and disjunctive so as to make coherent
mental reckoning in time all but impossible.  Indeed, had some
tyrannical god contrived to enslave our minds to time, to make it all
but impossible for us to escape subjection to sodden routines and
unpleasant surprises, he could hardly have done better than handing
down our present system.  It is like a set of trapezoidal building
blocks, with no vertical or horizontal surfaces, like a language in
which the simplest thought demands ornate constructions, useless
particles and lengthy circumlocutions.  Unlike the more successful
patterns of language and science, which enable us to face experience
boldly or at least level-headedly, our system of temporal calculation
silently and persistently encourages our terror of time.

… It is as though architects had to measure length in feet, width in
meters and height in ells; as though basic instruction manuals
demanded a knowledge of five different languages.  It is no wonder
then that we often look into our own immediate past or future, last
Tuesday or a week from Sunday, with feelings of helpless confusion.  …

— Robert Grudin, ‘Time and the Art of Living’.
  [[info:coreutils#Date%20input%20formats][info:coreutils#Date input formats]]

#+end_quote

** References



