#   -*- mode: org; fill-column: 60 -*-

#+TITLE:   7. Process of Change Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../..index.org][top]]] [[[./index.org][up]]] [[[./05-roc.org][prev]]] [[[./07-as-povs.org][next]]]

* 7. Process of Change Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/02/07/intro.org
:Created:  2018-04-20T18:11@Prek Leap (11.642600N-104.919210W)
:ID:       151fc0fd-2a47-4214-9194-9c4b7375f986
:VER:      577494732.237826365
:GEO:      48P-491193-1287029-15
:BXID:     proj:TGM5-5360
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

#+begin_quote
The distinction between past, present and future is only a
stubbornly persistent illusion.

— Albert Einstein
#+end_quote

When we talk about LOD and ROC we are talking about
substance (as the term is used in philosophy) that from the
time of Aristotle has claimed as the only way to understand
and argue about the world.  Sustance changes over time, but
that change is accidental and does not change form so that
it still remains essentially the same thing.

But things can also be thought of as processes that are in a
constant state of changing and becoming something else.  The
NYC as substance assumes that it may change over time but it
is still the same NYC from when it was a small settlement
called New Amsterdam till today.

Darwin didn't like the idea of taxonomies with distinct
species -- he understood that since evolution is process of
each individual changing and passing on those changes to
future generations, that each change represents a variation
(in plants this is called a variety) in animals (a breed)
and that the traditional distinction made between species
that a new species is created when they can no longer
reproduce with the species that the evolved from.  But where
do you draw that line.  Because each variation inbetween
species can breed with the variation that can before and the
one that came after it....

Process philosophy argues that it is not the same city even
from one moment to the next -- ala you can never step in the
same river twice.  So when you compare POC with ROC you are
considering not only how fast things change, but the
substance of how substances transform over time.

Understanding things as process and that things change over
time to become completely different things is important --
we tend to use words, events and historical figures as if
they were contemporaries from our own present understanding
of the world -- they were not what we think of them today --
we have reinvented them and are continually reinventing
everything around us -- history is what is written -- what
was said -- which is a moving target as we write new things.

The past is not a static fixed thing because out
understanding is not a static fixed thing.  This is
important in so many different areas.  For example, in USA,
when people argue that interpretation of the constitution
must be in done as it was intended when it was written in
the 18th century.  Is this even possible?  We can not know
what their original intend was because our understanding of
what we think their original intent was is constantly
changing.

The past is always an invention of the present.  This does
not mean that it's not important to strive to understand
what that original intent is, it's just that our
understanding is changing and will never stop changing,
which in some respects negates the original intention of
what we set out to do in the first place.  POC has enormous
implications for everything from contracts to education to
agriculture to business.

Systems best thought of as ongoing processes rather than
something with a beginning or end -- which has historic
interest, but most of life is taken up with the present --



** References


