#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 2.7 Points of View
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] | [[[./index.org][index]]]

* 2.7 Points of View
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww.points-of-view.org
:Created:  2018-03-19T19:09@Prek Leap (11.642600N-104.919210W)
:ID:       cceb8184-21ef-4fb0-9b5f-933e484f7e9f
:VER:      574733452.681672429
:GEO:      48P-491193-1287029-15
:BXID:     proj:FVG7-8542
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

#+begin_comment
This obviously has to be rewritten so that it is a summary
rather than given as an specific example used as summary. 
#+end_comment

The premise is that it is helpful to always understand the
Point of View (POV) -- or perspective that you are looking
at something because when you change your POV you change the
context of what you are seeing and will often see things you
didn't see before, or even see things in a completely
different way than you saw before.

We define three different perspectives:

  - LOD : Level of Detail
  - ROC : Rate of Change
  - POC : Process of Change

These three POVs form the foundation for how everything else
*everything* in APPL, Primer & Hoard are understood.

Each POV becomes increasingly more complex and abstract, but
each builds on the one before and let's you see the same
thing from a different perspective.  It does not negate the
other POVs so much as enriches them and provides a more
powerful toolbox for modeling and understanding.

For example, let's look at the Origin Story that will start
the Primer.

The Origin LOD is basically Big History -- a linear timeline
with a beginning (big bang) middle (from BB to now) and the
end (projected heat death of the universe).  The narrative
is organized around tipping points where complexity reaches
a critical mass that changes the nature of the universe, and
then later life on earth and eventually us.  This is a
fantastic narrative and is a perfect way of easing people
into the origin story which can be understood like any other
origin story.

The Origin ROC is basically a finer grained version of Big
History that uses the concept of causal propagation (think
Light Cones) to understand that different things change at
different speeds and that all of these things are mixed
together.  It's the embodiment of Gibson's the future is
already here isn't just not evenly distributed.  Brand's
Pace-Layers is a good way of understanding this, as well as
Light Cones and causal propagation of change happening at
the speed of light but making the point that the speed of
light is the maximum speed that things can propagate, most
things are propagating far slower.

--------

Taken together these three models will give us a set of
powerful tools for understanding, planning, building, and
maintaining civilizations.

** Introduction | Points of View



*** Defining objective POVs

It would be helpful if generic POVs could be objectively
defined in a way that they could be used to understand and
used by anyone without having to resort to subjective
imagination or empathy which are often so intertwined with
emotional states, cognitive limitations and biases that they
are difficult to use as general purpose empirical-based
cognitive tools.

We have identified what we believe to be three fundamentally
important types of POVs which can do just that.  And because
of the importance that POVs have in the survival of a
species, and as a culture and civilization we are putting
these three POVs at the center of understanding who we are,
where we came from, how to overcome cognitive limits and
bias, problem solving, communication, conflict resolution
and cooperation.

But before we can introduce the three core POVs we will need
to introduce three concepts, each of which will be the core
of a Core POV, but also are critical understanding any one
of the three POVS.  These are, Level of Detail, Rate of
Change, and Process of Change.

*** Level of Detail (LOD)

https://en.wikipedia.org/wiki/Level_of_detail

LOD is a concept and technique used in 3D modeling that
involves decreasing the complexity of a model as it moves
away from the viewer, or physical POV relative to the model.

We use the term LOD rather than distance because distance is
a relative term -- is distance the space traveled by light
in a given time?  Is distence a measure of units, and if so
what units?  What is the accuracy of those units?  Is a
day's walk, the same as 10 kilometers?

#+begin_quote
Mount Everest’s height seems to be subject to two competing
forces. On the one hand, the collision of two continental
plates (Asia and India) causes a certain amount of uplift
each year, perhaps about a centimeter or so, although there
seems to be some disagreement. On the other hand, other
forces, such as erosion and melting glaciers, can cause a
decrease in height. While it’s unclear how much it changes
each year, we now know for certain that the height is never
exactly constant. We also know that Mount Everest is moving
laterally at quite a nice clip: six centimeters per year,
making its location also a mesofact, one of those slowly
changing pieces of knowledge.

-- Half-Life of Facts cite:arbesman:2012half-life
#+end_quote


LOD clears away all of that and is simply the amount of
detail that can be observed from a given frame of reference.
The less detail, the farther away it is, the closer the more
detail that can be observed.

LOD is a useful way of looking at anything in terms of how
much detail can be displayed or understood.

  - we think of threats in terms of distance and the amount
    of detail you can take in -- don't fire until you see
    the whites of their eyes.  Storm clouds on the horizon,
    or the threat is right on top of us.  The farther away a
    threat is the more time you have to react, the more time
    to plan and model the problem because the farther away
    it is, the less information you have to deal with in
    evaluating the threat and how to react to it.  The
    closer it becomes the more information you have to
    content with and the less time you have to process all
    of that information.

    This becomes very important because of the concept of
    discounting -- we discount things that are far away --
    we put off dealing with anything that is not percieved
    as an immediate threat -- we can plan for the future,
    which is one of the things that sets us apart from other
    animals, but we're still not very good at it.  The lower
    the detail, the lower the threat the less weight we give
    to it.  The larger something is, the more we pay
    attention to it, and that includes very small threats
    like a poisonous spider, the spider itself is small, but
    the pain or even threat of death is very large and
    detailed.

    So LOD is at the heart of how we determine what is and
    what isn't important -- spending a dollar on a bag of
    crispes is small, relative to how much money the average
    person in the developed world spends every month or in a
    lifetime, but buying a car is somethiing that will
    impact your life for years.  Buying a house will impact
    your life for decades or even the rest of your life.

The forest and the trees -- a low LOD allows us to see the
big picture, uncluttered by detail -- a high LOD immerses us
in detail making it difficult or impossible to see larger or
longer processes at work.


Think of information in a physical Library in terms of LOD.
Standing outside the building you can gauge very roughly how
large a library it is by the size of the building.  Entering
the building you apprach the catalog file drawers.  The more
drawers the more books and other material in the library.
If the library is openstack, you can then walk into the
stacks and see the library in terms of floors of rows of
shelves, step slower and you are in a single row and you can
see the different shelves of books.  Step closer and you can
read the spines of the books on the shelf in front you and
you see more detail, the type of book, cloth, papeback,
library binding etc.  And you can see the title of the book,
the authors name and the publishers logo or imprint.  You
can also see roughly how big the book is, in terms of
thickness (number of pages) and the height of the book.
Take down a book and you open to the title and copyright
pages and you see more metadata that gives you an idea of
who created the book, when and where it was published and
perhaps the library catalog entry that you would have seen
in the library catalog file drawers.  Turn to the Table of
contents and you see an outline of the book and get an idea
of it's structure -- leaf through the book and you'll have
an idea of the size of the font and how much information is
on each page, are there illustations? footnotes?  Then,
finally turn to the first page of the first chapter and
you've come to the highest level of detail in the book.
When you are reading, you an no longer see the book in lower
detail -- though your mental model that you made when
looking at the book from lower LODs provides you with a
means of understanding where you are reading, relative to
the whole book.

Now we need an example of temporal LOD

We mix and match things when we compare different things
together -- we don't always compare two things at the same
LOD -- this is very useful.

A low LOD in a short scientific paper might be very
different from the short LOD in a book.  So a paper that is
mentioned in passing a larger work describes that paper from
a low LOD, which is useful understanding that paper in
context with other related papers.  But you might then place
that paper beside the book and refer to it in order to see
in detail how the paper might provide even more context with
the larger picture in the book.

The concept of the length of the coast of England -- you can
always add or subtract one from something -- zeno's paradox
-- you can always cut something in half.  So setting an LOD
is also a means of defining something.  A definition is as
much a description of what something is as it excludes what
something is not.

LOD is key to understanding the part-whole relationship
which we will discuss in it's own chapter.

LOD is key to the Map-Territory relationship, which we will
discuss in more detail in it's own chapter.


*** Rate of Change (ROC)

Alvin Toffler's concept of ROC 

The concept of the Half-Life -- how long it takes for half
of something to change.

Linear growth, Steady Growth vs Exponential Growth

ROC is relative to the age of something -- time is
experienced relative to how long something is relative to
how long your have lived.  When I was a child, as many
children in school do, life is measured relative to when the
next major holiday or vacation is.  Growing up in the United
States in the 1970's, summer holidays lasted from late May
or early June to the Memorial Day federal holiday at the
beginning of September.  Those three months seemed to last a
lifetime.  When school let out in June, it the start of the
next school year seemed impossibly distent in the future.
Now that I am in my mid-fifties, three months can pass in
seamingly a hearbeat if your aren't paying attention.

Complexity and Rate of Change

Size of a Territory and Rate of Change

Size of a Population and Rate of Change

Distance/LOD and Rate of Change

Scientific knowledge and Rate of Change

Limits on human ability to change and Rate of Change, 

Pace-Layers -- different things change at different rates

  Rates of change that the universe (cosmic expansion)
  institutions, language, culture, fashion.

  Different parts of buildings change at different rates --
  what Brand called shearing layers.

Will talk about Pace-layers in more detail in it Part XX.

*** Process of Change (POC)

#+begin_quote
The distinction between past, present and future is only a
stubbornly persistent illusion.

— Albert Einstein
#+end_quote

When we talk about LOD and ROC we are talking about
substance (as the term is used in philosophy) that from the
time of Aristotle has claimed as the only way to understand
and argue about the world.  Sustance changes over time, but
that change is accidental and does not change form so that
it still remains essentially the same thing.

But things can also be thought of as processes that are in a
constant state of changing and becoming something else.  The
NYC as substance assumes that it may change over time but it
is still the same NYC from when it was a small settlement
called New Amsterdam till today.

Darwin didn't like the idea of taxonomies with distinct
species -- he understood that since evolution is process of
each individual changing and passing on those changes to
future generations, that each change represents a variation
(in plants this is called a variety) in animals (a breed)
and that the traditional distinction made between species
that a new species is created when they can no longer
reproduce with the species that the evolved from.  But where
do you draw that line.  Because each variation inbetween
species can breed with the variation that can before and the
one that came after it....

Process philosophy argues that it is not the same city even
from one moment to the next -- ala you can never step in the
same river twice.  So when you compare POC with ROC you are
considering not only how fast things change, but the
substance of how substances transform over time.

Understanding things as process and that things change over
time to become completely different things is important --
we tend to use words, events and historical figures as if
they were contemporaries from our own present understanding
of the world -- they were not what we think of them today --
we have reinvented them and are continually reinventing
everything around us -- history is what is written -- what
was said -- which is a moving target as we write new things.

The past is not a static fixed thing because out
understanding is not a static fixed thing.  This is
important in so many different areas.  For example, in USA,
when people argue that interpretation of the constitution
must be in done as it was intended when it was written in
the 18th century.  Is this even possible?  We can not know
what their original intend was because our understanding of
what we think their original intent was is constantly
changing.

The past is always an invention of the present.  This does
not mean that it's not important to strive to understand
what that original intent is, it's just that our
understanding is changing and will never stop changing,
which in some respects negates the original intention of
what we set out to do in the first place.  POC has enormous
implications for everything from contracts to education to
agriculture to business.

Systems best thought of as ongoing processes rather than
something with a beginning or end -- which has historic
interest, but most of life is taken up with the present --


*** LOD, ROC and POC as Point of Views

Now that we understand what a Point of View is, and it's
importance and the three concepts of LOD, ROC and POC we can
build the three Core POVs that will be at the heart of our
understanding of the universe, who and what we are and how
to build a civilization from first principles.

Originally I planned on jumping straight in and describing
each of these as a POV, but the concept of LOD is nt the
same as an LOD POV.  You can't understand LOD as a POV
without understanding ROC and POC.  Each of these things as
a POC only can be understood in relation to the other two.

The first is the Scale Point of View which is dominated by
LOD and distance.  The second is Propagation, which is based
on ROC. And finally the Process Point of View is based on
the concept of everything being in the process of becoming
something else.

In the same way, the three POVs are not meant to be used
separately, each builds on the other and hybrid Points of
Views that combine them to different degrees will be the
rule rather than the exception.
 
So you can think of LOD, ROC and POC and building blocks for
describing context as a POV.  It's important to understand
them as different POVs but in practice we will almost always
be talking in terms of LOD, ROC and POC.

You can mix and match these three to create any number of
POVs, but we will focus on four which will provide a jumping
off point for creating a wide variety of POVs that we will
use over and over.

*** Scale

Scale determines POV relative to the distance from a given
frame of reference, the distence determines the LOD from any
given distence.

Scale works separately in space or in time or as one or the
other depending on if your POV is a Process or a Narrative.

Since we use the concept of LOD, rather than any specific
standard of measurement -- it doesn't require an ideal
references meter stick kept in a environmentally stable
vault, or sophisticated light sources and timing equipment
to measure how far light travels in a given period of time.
These are important concepts and tools, but as a universal
means of understanding a POV they don't help.

Is Scale a POV in its own right?


Different things work differently at different scales --
some things scale from small to large like a vector graphic
-- but other things are creatures of specific scales they
only work within narrow ranges.

The importance of being the right size cite:haldane:1928being

things like water tension and gravity relative to mass means
that most things won't scale

Things that can truly scale from very small to very large
are rare but very important -- in fact this is a useful
metric, the larger that something can scale the more usefull
it is.

over and over again, we will see that there are many aspects
about how humans are designed and wired leads us to the
conclusion that sapiens only work within a scale that has a
narrow range -- I would argue that most if not all of the
problems that we face as a species today stem from our
attempts to scale sapiens beyond what we are capable of.

The interesting thing is that it's doubtful that sapiens
would have been able to achieve what we have done today
unless we had so relentlessly tried to scale beyond our
boundries in terms of climatic environments, our social
structures, or cognitive limitations etc.

This is what has made us successful as well as what has
screwed us up so terribly.  In many respects, this work is
an attempt to find a balance for us to be able to live
within those limits, while still pushing the boundries and
expanding those limits.  That's the balanceing act we need
to learn to do better -- that's what keeps us within the
limits of our petri dish, and gives us the time to keep
expanding the size of that petri dish before we overrun it
and destroy ourselves.


*** Narrative

Unlike process, a narrative POV views things as continuum of
snapshots of different states of the present.  Each snapshot
becomes a point in time where the state is frozen.  When you
move forward or backward in time you move to previous or
future frozen states.  When understood this way, the whole
idea of time as a place doesn't work very well.

Entropy gives time a direction, it is a one-way process --
you can't unstir a cup of coffee.

This is where we get the illusion of time as a lie -- we
think in terms of a present relative to a past, an illusion
created my memories of when the present was not the same as
it is now.

Narratives are an effective means of modeling the world
where there are memories of things that are no longer the
same as in the present.

Narratives move in a single direction, from past to present
and from present to future.  You can zoom in and out of
narratives to see more or less LOD, and narratives can be
sped up or slowed down at different rates than the events
are happening in the narrative by zooming in and out to
provide more temporal LOD.

Now -- what about non-linear narritives -- aka arthurian
prose cycles.  these are branching narratives, rhizomatic
structures, which are essentially graphs -- and we need to
think of narratives as a broader set of structures than
beginning middle end.

That might be right -- of the four POVs here we don't have a
graph-based POV -- narratives are stuck with entropic one
way processes but they don't have to be one damn thing after
another they don't have to be Ariadne's thread through the
maze, they can encompass the maze and the threads that weave
through them.

Sapiens are story tellers -- but we are constant riffing on
stories -- there is no one story, we always are looking at
tweaking the story to give different outcomes -- this goes
to the core of how we understand and model the world -- but
today we have the printing press and perfect copies of
things that don't change.  in fact we can be punished if we
change things -- but that's not how things really are or how
things have been -- we are ALL story tellers we tell
stories, not just repeat other people's stories

that is what a narrative really is and this is key to
understanding narrative as a POV!

*** Propagation

Specifically causal propagation -- 

How is Causal Propagation a POV?  That's what we have to
explain here.

Perhaps it is what has or hasn't changed in one place
relative to what has or hasn't changed in another.  So that
from one POV in space in time the observer sees X but on the
other side of the galaxy at the same time but different
place the observer sees Y because change has does not
propagate at the same rate.

Propagation, like timem is a one-way process.

Change is not instantaneous, it is tied to the physical laws
of the universe.  Change can only change as fast as those
physical laws allow.

Propagation is the speed that change moves through time and
space.

  Light Cone

So the maximum ROC at relative scales is limited by the speed of
light.

The exception is quantum entanglement -- but at the moment this isn't
important unless we develop tech that leverages 

Change is also relative to the distance between two things -- the
shorter the distence the faster things change between them -- at
microscopic and atomic scales this is very important.

As we will see in the Pace-Layer model, the maximum ROC
(speed of light) might be important at very large scales,
but there are all sorts of scales -- different things happen
at different temporal scales in a society -- there are
processes that happen slower or faster or even vary,
changing at different rates at different times depending on
what is changing.

*** Process

When thinking of the present as process, you are in the
moment -- there is no past or future -- the past and future
are only real when you have a surplus of time to think about
them -- if you are being chased by a bear, you aren't going
to be thinking about where you are going to eat lunch, you
are too busy not becoming the bear's lunch.

But when thinking of systems we are looking at a process
from a lower LOD.

When we think about something like Moore's Law, we are
looking at ROC at a lower LOD.

We're not very good at thinking of the past as being in the
present, but it is -- the past is still with us, it's just
decayed and overwritten by other things --

the big bang is something that can be understood as one big
present -- because light travels at a fixed speed, when we
look at distant objects we are looking at light that has
taken a long time to get here -- we are effectively looking
at things that happened long in the past -- but there is no
way of seeing how they are now in the present -- and in the
same way, the light from what we are doing now, will travel
through space at a set speed and might be seen by others in
the distant future -- but they will be seeing us as we are
now, not as we are when they see us.


  - Systems as process
  - ERP -- business processes
  - Education as lifelong process

