#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 2.7 Points of View
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] | [[[./index.org][index]]]

* 2.7 Points of View
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww.points-of-view.org
:Created:  2018-03-19T19:09@Prek Leap (11.642600N-104.919210W)
:ID:       cceb8184-21ef-4fb0-9b5f-933e484f7e9f
:VER:      574733452.681672429
:GEO:      48P-491193-1287029-15
:BXID:     proj:FVG7-8542
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

#+begin_comment
This obviously has to be rewritten so that it is a summary
rather than given as an specific example used as summary. 
#+end_comment

The premise is that it is helpful to always understand the
Point of View (POV) -- or perspective that you are looking
at something because when you change your POV you change the
context of what you are seeing and will often see things you
didn't see before, or even see things in a completely
different way than you saw before.

We define three different perspectives:

  - LOD : Level of Detail
  - ROC : Rate of Change
  - POC : Process of Change

These three POVs form the foundation for how everything else
*everything* in APPL, Primer & Hoard are understood.

Each POV becomes increasingly more complex and abstract, but
each builds on the one before and let's you see the same
thing from a different perspective.  It does not negate the
other POVs so much as enriches them and provides a more
powerful toolbox for modeling and understanding.

For example, let's look at the Origin Story that will start
the Primer.

The Origin LOD is basically Big History -- a linear timeline
with a beginning (big bang) middle (from BB to now) and the
end (projected heat death of the universe).  The narrative
is organized around tipping points where complexity reaches
a critical mass that changes the nature of the universe, and
then later life on earth and eventually us.  This is a
fantastic narrative and is a perfect way of easing people
into the origin story which can be understood like any other
origin story.

The Origin ROC is basically a finer grained version of Big
History that uses the concept of causal propagation (think
Light Cones) to understand that different things change at
different speeds and that all of these things are mixed
together.  It's the embodiment of Gibson's the future is
already here isn't just not evenly distributed.  Brand's
Pace-Layers is a good way of understanding this, as well as
Light Cones and causal propagation of change happening at
the speed of light but making the point that the speed of
light is the maximum speed that things can propagate, most
things are propagating far slower.

--------

Taken together these three models will give us a set of
powerful tools for understanding, planning, building, and
maintaining civilizations.

** Introduction | Points of View



*** Scale



*** Narrative


*** Propagation



*** Process

When thinking of the present as process, you are in the
moment -- there is no past or future -- the past and future
are only real when you have a surplus of time to think about
them -- if you are being chased by a bear, you aren't going
to be thinking about where you are going to eat lunch, you
are too busy not becoming the bear's lunch.

But when thinking of systems we are looking at a process
from a lower LOD.

When we think about something like Moore's Law, we are
looking at ROC at a lower LOD.

We're not very good at thinking of the past as being in the
present, but it is -- the past is still with us, it's just
decayed and overwritten by other things --

the big bang is something that can be understood as one big
present -- because light travels at a fixed speed, when we
look at distant objects we are looking at light that has
taken a long time to get here -- we are effectively looking
at things that happened long in the past -- but there is no
way of seeing how they are now in the present -- and in the
same way, the light from what we are doing now, will travel
through space at a set speed and might be seen by others in
the distant future -- but they will be seeing us as we are
now, not as we are when they see us.


  - Systems as process
  - ERP -- business processes
  - Education as lifelong process

