#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 2.7 Points of View
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] | [[[./index.org][index]]]

* 2.7 Points of View
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww.points-of-view.org
:Created:  2018-03-19T19:09@Prek Leap (11.642600N-104.919210W)
:ID:       cceb8184-21ef-4fb0-9b5f-933e484f7e9f
:VER:      574733452.681672429
:GEO:      48P-491193-1287029-15
:BXID:     proj:FVG7-8542
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

#+begin_comment
This obviously has to be rewritten so that it is a summary
rather than given as an specific example used as summary. 
#+end_comment

The premise is that it is helpful to always understand the
Point of View (POV) -- or perspective that you are looking
at something because when you change your POV you change the
context of what you are seeing and will often see things you
didn't see before, or even see things in a completely
different way than you saw before.

We define three different perspectives:

  - LOD : Level of Detail
  - ROC : Rate of Change
  - POC : Process of Change

These three POVs form the foundation for how everything else
*everything* in APPL, Primer & Hoard are understood.

Each POV becomes increasingly more complex and abstract, but
each builds on the one before and let's you see the same
thing from a different perspective.  It does not negate the
other POVs so much as enriches them and provides a more
powerful toolbox for modeling and understanding.

For example, let's look at the Origin Story that will start
the Primer.

The Origin LOD is basically Big History -- a linear timeline
with a beginning (big bang) middle (from BB to now) and the
end (projected heat death of the universe).  The narrative
is organized around tipping points where complexity reaches
a critical mass that changes the nature of the universe, and
then later life on earth and eventually us.  This is a
fantastic narrative and is a perfect way of easing people
into the origin story which can be understood like any other
origin story.

The Origin ROC is basically a finer grained version of Big
History that uses the concept of causal propagation (think
Light Cones) to understand that different things change at
different speeds and that all of these things are mixed
together.  It's the embodiment of Gibson's the future is
already here isn't just not evenly distributed.  Brand's
Pace-Layers is a good way of understanding this, as well as
Light Cones and causal propagation of change happening at
the speed of light but making the point that the speed of
light is the maximum speed that things can propagate, most
things are propagating far slower.

--------

Taken together these three models will give us a set of
powerful tools for understanding, planning, building, and
maintaining civilizations.

** Introduction | Points of View



*** Scale

Scale determines POV relative to the distance from a given
frame of reference, the distence determines the LOD from any
given distence.

Scale works separately in space or in time or as one or the
other depending on if your POV is a Process or a Narrative.

Since we use the concept of LOD, rather than any specific
standard of measurement -- it doesn't require an ideal
references meter stick kept in a environmentally stable
vault, or sophisticated light sources and timing equipment
to measure how far light travels in a given period of time.
These are important concepts and tools, but as a universal
means of understanding a POV they don't help.

Is Scale a POV in its own right?


Different things work differently at different scales --
some things scale from small to large like a vector graphic
-- but other things are creatures of specific scales they
only work within narrow ranges.

The importance of being the right size cite:haldane:1928being

things like water tension and gravity relative to mass means
that most things won't scale

Things that can truly scale from very small to very large
are rare but very important -- in fact this is a useful
metric, the larger that something can scale the more usefull
it is.

over and over again, we will see that there are many aspects
about how humans are designed and wired leads us to the
conclusion that sapiens only work within a scale that has a
narrow range -- I would argue that most if not all of the
problems that we face as a species today stem from our
attempts to scale sapiens beyond what we are capable of.

The interesting thing is that it's doubtful that sapiens
would have been able to achieve what we have done today
unless we had so relentlessly tried to scale beyond our
boundries in terms of climatic environments, our social
structures, or cognitive limitations etc.

This is what has made us successful as well as what has
screwed us up so terribly.  In many respects, this work is
an attempt to find a balance for us to be able to live
within those limits, while still pushing the boundries and
expanding those limits.  That's the balanceing act we need
to learn to do better -- that's what keeps us within the
limits of our petri dish, and gives us the time to keep
expanding the size of that petri dish before we overrun it
and destroy ourselves.


*** Narrative

Unlike process, a narrative POV views things as continuum of
snapshots of different states of the present.  Each snapshot
becomes a point in time where the state is frozen.  When you
move forward or backward in time you move to previous or
future frozen states.  When understood this way, the whole
idea of time as a place doesn't work very well.

Entropy gives time a direction, it is a one-way process --
you can't unstir a cup of coffee.

This is where we get the illusion of time as a lie -- we
think in terms of a present relative to a past, an illusion
created my memories of when the present was not the same as
it is now.

Narratives are an effective means of modeling the world
where there are memories of things that are no longer the
same as in the present.

Narratives move in a single direction, from past to present
and from present to future.  You can zoom in and out of
narratives to see more or less LOD, and narratives can be
sped up or slowed down at different rates than the events
are happening in the narrative by zooming in and out to
provide more temporal LOD.

Now -- what about non-linear narritives -- aka arthurian
prose cycles.  these are branching narratives, rhizomatic
structures, which are essentially graphs -- and we need to
think of narratives as a broader set of structures than
beginning middle end.

That might be right -- of the four POVs here we don't have a
graph-based POV -- narratives are stuck with entropic one
way processes but they don't have to be one damn thing after
another they don't have to be Ariadne's thread through the
maze, they can encompass the maze and the threads that weave
through them.

Sapiens are story tellers -- but we are constant riffing on
stories -- there is no one story, we always are looking at
tweaking the story to give different outcomes -- this goes
to the core of how we understand and model the world -- but
today we have the printing press and perfect copies of
things that don't change.  in fact we can be punished if we
change things -- but that's not how things really are or how
things have been -- we are ALL story tellers we tell
stories, not just repeat other people's stories

that is what a narrative really is and this is key to
understanding narrative as a POV!

*** Propagation

Specifically causal propagation -- 

How is Causal Propagation a POV?  That's what we have to
explain here.

Perhaps it is what has or hasn't changed in one place
relative to what has or hasn't changed in another.  So that
from one POV in space in time the observer sees X but on the
other side of the galaxy at the same time but different
place the observer sees Y because change has does not
propagate at the same rate.

Propagation, like timem is a one-way process.

Change is not instantaneous, it is tied to the physical laws
of the universe.  Change can only change as fast as those
physical laws allow.

Propagation is the speed that change moves through time and
space.

  Light Cone

So the maximum ROC at relative scales is limited by the speed of
light.

The exception is quantum entanglement -- but at the moment this isn't
important unless we develop tech that leverages 

Change is also relative to the distance between two things -- the
shorter the distence the faster things change between them -- at
microscopic and atomic scales this is very important.

As we will see in the Pace-Layer model, the maximum ROC
(speed of light) might be important at very large scales,
but there are all sorts of scales -- different things happen
at different temporal scales in a society -- there are
processes that happen slower or faster or even vary,
changing at different rates at different times depending on
what is changing.

*** Process

When thinking of the present as process, you are in the
moment -- there is no past or future -- the past and future
are only real when you have a surplus of time to think about
them -- if you are being chased by a bear, you aren't going
to be thinking about where you are going to eat lunch, you
are too busy not becoming the bear's lunch.

But when thinking of systems we are looking at a process
from a lower LOD.

When we think about something like Moore's Law, we are
looking at ROC at a lower LOD.

We're not very good at thinking of the past as being in the
present, but it is -- the past is still with us, it's just
decayed and overwritten by other things --

the big bang is something that can be understood as one big
present -- because light travels at a fixed speed, when we
look at distant objects we are looking at light that has
taken a long time to get here -- we are effectively looking
at things that happened long in the past -- but there is no
way of seeing how they are now in the present -- and in the
same way, the light from what we are doing now, will travel
through space at a set speed and might be seen by others in
the distant future -- but they will be seeing us as we are
now, not as we are when they see us.


  - Systems as process
  - ERP -- business processes
  - Education as lifelong process

