#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XVII. Stages Abstract 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]


* XVII. Stages Abstract
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/17/abstract.org
:Created:  2018-05-19T10:17@Prek Leap (11.642600N-104.919210W)
:ID:       e6ff856d-459b-4063-a09b-7545e467aa4d
:VER:      579971887.454547033
:GEO:      48P-491193-1287029-15
:BXID:     proj:VBA2-2467
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

In Canto XVI we saw the overall structure of a civilization
level compiled primer with three branches that provide
negative feedback on each other.  But it's not just a matter
of adding money and people to build a civilization.  This is
not a template, it is a generate grammar.  This canto will
show how you get from an individual, or a group of indivuals
who which to found a community to scale up to a full blown
civilization.  W&W provides a number of initial default
parameters that can be used as placeholders until
circumstances and experience determines what those
parameters will need to be to work in a given context. We
will structure this using a succession stage model.

** TL;DR

