#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XVII. Stages Introduction 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* XVII. Stages Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/17/intro.org
:Created:  2018-05-19T10:18@Prek Leap (11.642600N-104.919210W)
:ID:       df175200-3ba5-4668-836b-a29150fe3526
:VER:      579971973.226943007
:GEO:      48P-491193-1287029-15
:BXID:     proj:JLO5-6836
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


XVI gives us an outline of how to run a kernal and organize
a self-correcting disributed civilization -- but it doesn't
tell us how we get from here to there.  In otherwords, we
need a succession model.

Internet Succession model and where it broke

like the internet, it has to start sparse and low bandwidth
(metaphorically) the internet didn't start with TCP/IP over
ethernet on fiber optic networks, it started as UUCP, a
store and forward network running over modems on an analog
phone network.  It then morphed when slip and ppp allowed
people direct connections over a modem, then finally
dedicated connections began to propagate, speed increased,
local wifi appeared, and then ubiquitious 2G 3G and 4G
wireless.  In the next decade several constellations in LEO
will turn wireless truly global and fully broadband.

But that's only talking about the hardware networks, there
was a corresponding social transformation at each stage as
well that was shaped by the interfaces and the speeds and
the computing power and storage.  All went hand in hand.

UUCP and FIDO were viral and grass roots -- like a methodist
preacher coming into town trying to win converts, and not
leaving until he found a handful of people to set up a node
and join the network.  Everything about humans comes down to
community, the group we belong to and how new groups form
and replace the old.

This is where USENET, LISTSERV and BBSes come into the
story.  Email was one to one, but with a LISTSERV if became
one to many which made group conversation possible.  IRC
entered the picture and people could chat in real time.
Groups were relatively small because there weren't a lot of
people on the Net back then, and the people who were, were
technically literate, so interfaces didn't need to be dumbed
down.

It's okay to have an entry level that has a short learning
curve, but that should always lead you to higher and higher
skill levels -- millions do that every day when they play
multi-level computer games.  Why shouldn't the interface and
what you can do with it become more powerful as you move up
a level -- not just more guns and ammo and lives, but a more
sophisticated interface that you have to master, that
require you to think critically, creatively and
reflectively.

That is what our societies need have baked into them.
Industrialization all but wiped out craftsmanship and
care and mastery -- we need to return to that.

The way we interact through social media today is a subset
of what we had back then.  Yes now we have animated emoji
and cat pictures and streaming video and that's mostly
great.  But the underlying systems are designed to addict
you, to turn you into a product, keep you forever engaged
and not leave a site.  That's what you get when things
become centralized, when things become all about
monetization and maximizing shareholder value.  Facebook
doesn't bring people together, it converts them into
consumers which connect to other consumers.

We need to stop this race to the bottom -- user friendly has
become an obscenity, a dumbing down that reduces us to
chumps sitting slack-jawed, pulling levers for sweeties
pouring out of a hole below.  We have sunk to the level of
primate cognitive experiments.  Slot machines are for
determining the cognitive limits of crows and chimps.  I
suppose that on some level that's what Facebook is really
doing.  There is a reason that slot machines are called
one-armed bandits.

Email, USENET and IRC are all networks that have an enormous
variety of different types of software to connect to and
use.  Some of these tools are bordering on sublime.  How
many different tools can you use to access facebook?
Twitter was initially somewhat open and there was a lot of
innovation in building Twitter clients, but Twitter has made
it clear that they are in control and force interfaces to do
things they way they want it done or you get shut out.

People have now become conditioned to think that the
interface is the network.  That like it or not, you have you
use what you have been given or not use the service.

We need more open networks, not closed services.

One thing that set Harry Potter apart from other juvenile
novel series that it started as was that each book grew with
the children reading them.  The first book was perfect for
an eleven year old, and each book reflected each year that
Harry and his friends grew -- the final book was long and
dark and complex and... adult.


** References


