#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   1. Metis Contents
#+LINK: lib   ~/proj/chenla/hoard/lib/ 
#+LINK: bib   ~/proj/chenla/hoard/bib.bib
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 1. Mētis Contents
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/01/01/index.org
:Created:  2018-05-26T09:17@Prek Leap (11.642600N-104.919210W)
:ID:       af9c5a0c-e79e-46e0-8e37-08aa3f42b486
:VER:      580573127.183619895
:GEO:      48P-491193-1287029-15
:BXID:     proj:PMK0-6440
:Class:    primer
:Entity:   toc
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

  - Contents
  - [[./abstract.org][Abstract]]
  - [[./ww-definintion.org][Mētis]]

  - "it is as economical and accurate as it needs to be,
    no more and no less, for addressing the problem at
    hand." (p.313). [[pdfview:~/proj/chenla/hoard/lib/scott:1998seeing.pdf::329][p.313]]
  - Knowledge of how, but not why -- why not explored and
    often mapped to local mythology, and a passed-down tradition. 
  - Human scale  -- Within human cognitive limits
  - Level of Separation - single level of separation
  - Map (no key) -- The map borders on being a territory,  
    dense, local map, topographic, social, linguistic, cultural
  - Autochthonic -- native evolved organically
  - Transactive  -- distributed memory, making things
    more opaque.
  - Mētis as mastery -- "an accumulation of many, partly
    redundent signals" ([[pdfview:~/proj/chenla/hoard/lib/scott:1998seeing.pdf::329][p.313]]) reinforced memories from
    doing or seeing the same thing over and over until it
    becomes something close to a learned instinct.


** Notes
  -
  - as defined by Scott SEE p.311



  - An intense idosyncratic wisdom or knowledge of a
    locale, knowledge about how things work in a specific
    place, not in general or globally.  A common farming
    adage I heard as a child growing up in New England,
    was that if corn was "knee high by the fourth of
    July" it indicated an important benchmark that you
    had a good crop.  After several years observation, I
    came to the conclusion that the phrase was not coined
    by a New England farmer.  A brief search on the term
    turned up no origin for the term, but did show that
    for most 19th century farmers in the mid-west United
    States this was a not a bad rule of thumb.  By the
    late 20th century, the introduction of new corn
    varieties and high yield hybrids, corn is more likely
    to be "as high as an elephant's eye"

       Note: “The corn is as high as an elephant’s eye, /
               An' it looks like it's climbin' clear up to the sky"

       "Oh, What a Beautiful Mornin", /Oklahoma!/, Rodgers
       and Hammerstein (1943).  
       SEE: 
       http://www.youtube.com/watch?v=_C6J9gij5SQ
       Wikipedia:  [[https://en.wikipedia.org/wiki/Oklahoma!][Oklahoma!]], [[https://en.wikipedia.org/wiki/Rodgers_and_Hammerstein][Rodgers and Hammerstein]], and
       [[https://en.wikipedia.org/wiki/Oh,_What_a_Beautiful_Mornin%27][Oh What a Beautiful Mornin]]

#+begin_verse
There's a bright golden haze on the meadow
There's a bright golden haze on the meadow
The corn is as high as an elephant's eye
An' it looks like it's climbin' clear up to the sky

Oh, what a beautiful mornin'
Oh, what a beautiful day
I've got a wonderful feelin'
Every thing's goin' my way

All the cattle are standin' like statues
All the cattle are standin' like statues
They don't turn their heads as they see me ride by
But a little brown maverick is winkin' his eye

Oh, what a beautiful mornin'
And oh, what a beautiful day
I've got a wonderful feelin'
Every thing's goin' my way

All the sounds of the earth are like music
All the sounds of the earth are like music
The bees are so busy they don't miss a tree
And an old weepin' willow is laughin' at me

Oh, what a beautiful mornin'
Oh, what a beautiful day
I've got a wonderful feelin'
Every thing's goin' my way now

Oh, what a beautiful day
Beautiful day

— "Oh, What a Beautiful Mornin", /Oklahoma!/, Rodgers and Hammerstein (1943)
#+end_verse



     - 
#+begin_quote
The kind of knowledge required in such endeavors is not
deductive knowledge from first principles but rather what
Greeks of the classical period called mētis, a concept to
which we shall return. Usually translated, inadequately, as
"cunning," mētis is better understood as the kind of
knowledge that can be acquired only by long practice at
similar but rarely identical tasks, which requires constant
adaptation to changing circumstances.

— Scott, Seeing Like A State 
  cite:scott:1998seeing, [[pdfview:~/proj/chenla/hoard/lib/scott:1998seeing.pdf::177][p.178]]
#+end_quote


#+begin_quote
With distinct communities and incommensurable beliefs, the
layers seem to fall apart like decaying plywood; if they are
significantly disconnected—if there are distinct communities
using terms like “mass” and “energy” in significantly
different ways—then the continuity of one level would hardly
bolster discontinuity at another.

— Peter Galison, Image and logic: a material culture of
  microphysics (1997)
  cite:galison:1997image-logic, [[pdf:galison:1997image-logic.pdf::404][p.783]]
#+end_quote


** References

  - Detienne, M., & Vernant, J. P., Cunning intelligence in
    greek culture and society (1991), : University of
    Chicago Press.
    cite:detienne:1991cunning-greek 
  - Alexander, S., /Book review: seeing like a state/ (2017).
    cite:alexander:2017seeing-state-review 
  - Rao, V., /A Big Little Idea Called Legibility/ (2010).
    cite:rao:2010big-little-idea 
  - Scott, J. C., /The trouble with the view from above / (2010).
    cite:scott:2010trouble 
  - Keep, L., /Man as a rationalist animal/ (2017).
    cite:keep:2017rationional-animal 
  - Scott, J. C., Seeing like a state: how certain schemes
    to improve the human condition have failed (1998), :
    Yale University Press.
    cite:scott:1998seeing 


  - Kuhn, T. S., Second thoughts on paradigms, The structure
    of scientific theories, 2(), 459–482 (1974).
    cite:kuhn:1974second
  - Kuhn, T. S., The essential tension: selected studies in
    scientific tradition and change (1977), : University Of
    Chicago Press.
    cite:kuhn:1977essential
  - Kuhn, T. S., The structure of scientific revolutions
    (1970), : The University of Chicago Press.
    cite:kuhn:1970sci-revolutions
  - Kuhn, T. S., The structure of scientific revolutions:
    50th anniversary edition (2012), : The University of
    Chicago Press.
    cite:kuhn:2012sci-revolutions

  - Keep, L., /Man as a rationalist animal/ (2017).
    cite:keep:2017rationional-animal 
  - Keep, L., /Science Under High Modernism/ (2018).
    cite:keep:2018science-high-modernism
