#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Definition 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Definition
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/01/01/ww-definintion.org
:Created:  2018-05-26T11:09@Prek Leap (11.642600N-104.919210W)
:ID:       f433214c-eaa1-4e06-9010-a33d1f80d847
:VER:      580579812.680497971
:GEO:      48P-491193-1287029-15
:BXID:     proj:DVQ5-4124
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


 Mētis is a greek word, Μῆτις which is commonly translated in english
 as "wisdom," or "cunning," but also embraces concepts of local
 knowledge, mastery through long practice and the ability to "think on
 one's feet," and adapt to changing circumstances.

 Odysseus who 

#+begin_quote
This brings us to the second type of reason for the
difficulties and—we believe—the interest of our undertaking.
Although mētis operates within so vast a domain, although
it holds such an important position within the Greek system
of values, it is never made manifest for what it is, it is never
clearly revealed in a theoretical work that aims to define it.
It always appears more or less below the surface, immersed
as it were in practical operations which, even when they
use it, show no concern to make its nature explicit or to
justify its procedures. To this extent modern Greek scholars,

cite:detienne:1991cunning-greek, [[pdf:detienne:1991cunning-greek.pdf::8][p.3]]

#+end_quote
