#   -*- mode: org; fill-column: 60 -*-

#+TITLE: ARC Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* ARC Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/07/37/intro.org
:Created:  2018-05-04T18:59@Prek Leap (11.642600N-104.919210W)
:ID:       4b5a6b32-9d93-4c59-82a5-0a6273b6e083
:VER:      578707206.538612127
:GEO:      48P-491193-1287029-15
:BXID:     proj:NKM4-0886
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR

Arcs are designed to be both /distributed/ and agressively
/antifragile/ in order to protect recorded knowleddge from
the primary types of loss:

  - Corruption
  - Mistakes
  - Catastrophe
  - Benign Neglect
  - Temporary Insanity

Arc content is designed as a pragmatic regime of very long
retention, hundreds and thousands of years.  This is done
using a succession stage model based on Level of Detail
relative to Length of Storage.  This is neccessary as a
practical solution to the Map-Territory relationship.

This is a problem that large intelligence gathering
organizations which until recently were State enterprises.
These include "three letter agencies" like the United
State's National Security Agency (NSA) and Central
Intelligence Agency (CIA) and seemingly the entire Chinese
State which is transforming the entire State into an
information gathering organization.  Today that list
includes private intelligance gathering organizations that
rival and threaten to dwarf State agencies including Google,
Facebook and Amazon.

In each case, these groups are hoovering up so much
information that they are already approaching a threshold
where the information collected no longer is a map, but is
becoming a territory in it's own right.  As we have
discussed in Volume XXX, maps are useful tools, but when
the more information they include, the less useful the map
becomes.  China, the United States and the big tech
companies are building territories rather than maps.  Over
time this will result in diminishing returns where
processing power required to find patterns and search for
information becomes greater than the utility derived from
it.  They will also begin to approach limits on that
processing power as it will take larger and larger amounts
of resources to obtain ever smaller increases in utility.
This is the same thing that happened in the
telecommunications industry during the copper era before
fiber optics replaces copper as the primary means of
transmitting information.  Copper is very noisy, it
introduces a great deal of error when transmitting a
signal.  So error correction systems were put into place to
increase the capacity of information that could be sent down
a wire.  At the time this was done, using very smart and
expensive switches.  As time went by, the switches became
more and more complex and expensive for ever smaller
increases in capacity.  In effect, this is the map-territory
problem.

It's impossible to know when information is created and
stored, what information will have value and what won't.
And this is true for non trivial amounts of time.
Historians today would love if all sorts of data collected
in past historical eras had been collected and retained.
They would love to have comprehensive collections of
everything from dna samples to human and animal poop.  Not
all of it, but enough representitive samples to be able to
build more accurate models of how things change over time
and what life was like at different times in the past.

So the lowest succession stage will be 1 solar cycle; a day.
We save everyting (or more accurately our devices do so on
our behalf) as we go through our daily lives, but it quickly
piles up.  So at the end of each day, duplicates are
discarded, and highly detailed metrics are tabulated and
stored.

The next stage could be one earth orbit; a year.  In which
the same process of eliminating duplicates is done, but
still retaining an impressively large amount of information
-- from video feeds, to biometric health information, to
written and spoken communications etc.  But there is a lot
of room for redundancies -- a recorded conversation from a
telephone call can be searched for patterns and common
phrases, or even patterns can be compressed so that they are
no retained as audio recordings, but as data patterns that
could be recreated with great accuracy -- a call that is
literally nothing more than saying something like "I'll be
late for dinner" could be analyzed for stress and audio
levels and then saved as an annotated transcript that could
be recreated if necessary.

The next stage could be a decade; ten years.  This process
continues again, but more aggressively and with greater loss
of detail.

The next stage could be a century, where massive reduction
of redundancies can take place.  For those who have died,
this would include creating concise archives of a person's
life that is relative to the amount of activity of that
person over their lifetime.

Centuries can then be condensed every millennia with many of
those archives being compressed further or all but deleted.
We've used a person's life as an example but the same process
will take place for events, organizations, creative works
etc.  At the millennial level we can likely then freeze
these records until there is a time that there is a need
they would need to be reduced more.  We can leave those
descions for our ancestors

*** Components

Arc is made of three parts:

**** Content
All content is maintained in /lossless/ /machine
understandable/ formats.  Everything is Woven together using
both using a catalog based on an FRBR enity model, and a
detailed set of semantic relationship between the contents
of each item in the Arc to all the other items.

**** Rulesets
The final part of Arc is a set of what we call cascading rule sets
which contain the logic for processes that index, catalog and map
collections in a format that is independent of any specific software
that is used to manage an Arc.  The software will use machine-learning
and graph databases to maintain and access collections.

**** Map
This catalog and metadata constitutes a map or graph which can be
managed and accessed in a graph database.

*** Organization

  Copies of Arcs
are divided into three different tiers, Dark Arcs only contain
archival copies of content, maps and processes.  They are not meant to
be directly accessible by end-users but rather by the second tiers
called Repos.  Plausible deniability is maintained by repos so that in
the event that a civilization reverts to a period of /temporary
insantity/ and willfully attempts to destroy Arcs, the Dark Arcs will
be able to keep content safe until a civilization returns to its
senses and libraries are established to retore that has been
destroyed.

Repos maintain complete working copies of an Arc, and only
communicates with Dark Arcs when they need to restore something that
has been lost, or to upload new material that is added to the Arc.
Archives are where more of the work and processing takes place.  New
content is converted into archival formats, cataloged and indexed.
End-user formats are generated which are then sent to the top most
Tier which is a Library.  Libraries are any traditional physical or
online library, repository or collection.  They can be anything from a
city, town, university or secondary school library or a collection
that only is available over the Internet.  Libraries maintain an
end-user version of the catalog and map and manage collections of
content in the most recent and popular formats.  Today these formats
would include html, epub and pdf for text, jpeg and png for images
etc.  If a library doesn't have or has lost an item, they request a
copy from the Library Tier above them.

** References





