#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Standards Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Standards Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/02/13/intro.org
:Created:  2018-05-06T16:13@Prek Leap (11.642600N-104.919210W)
:ID:       f773c71e-fe61-469f-9abb-511987c3eba5
:VER:      578870053.051189268
:GEO:      48P-491193-1287029-15
:BXID:     proj:IIS3-3847
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

Standards are the bedrock of interoperability as well as State
legibility.  Tax collecting is behind an enormous amount
standardization.  This became an enormous advantage in
industrialization and in trade.  If everyone uses the same standards
of measurement it becomes far easier to exchange things with others.

Standards have now become part of nearly every part of industrialized
and technologically advanced civilization.

Over time, standards have become increasingly fine-grained.  Time
keeping is a good example....

Another example is the epic story of the man who standardized srew and
bolt threads....

The metric system....

The great power of standards is that they make many things machine
legible that otherwise would be beyond the ability for most
machine-cog to understand.

There are still holdovers from preindustrial eras -- a major one is
physical address formats which are so diverse and riddled with
inconsistencies that they are nightmare for humans to parse, let along
software systems.  GPS coordinates are machine understandable, but not
very human friendly.  room, floor, building, street, town, state,
country addresses are powerful in that they can contain far more
information and context than a lat-lon-elevation address can convey,
but that context is often so local, that even people living an hour's
drive away may not be able to navigate it without help from a local.
This is where "you can't get there from here" comes from.


** TL;DR



** Data Structures

I suppose we can talk about narratives -- linear structures,
rhizomatic structures where everthing is connected to
everything, which I suppose is a graph, and then
hierarchical structures which are tress.

Humans think all three ways -- we think linearly as stories and
we think as paths snaking through rhizomatic structures

and I think this is how we need to put it:

  - complexity is best suited to rhizomatic structures
  - sets are lists for threads winding through those
    structures these are ideal for modeling deterministic
    processes. lists can be:
    - bag -- intentionally unordered -- the order is not significant.
    - seq -- ordered -- the order may be by time, number,
      alphabet, magnitude or class.
    - alt -- which is a branching list in which only a
      single item can be chosen -- this is taken from user
      interfaces but also multiple choice tests etc.
  - trees for creating hierarchies -- which are nature for
    pack animals -- trees are partial rhizomes that show a
    specific set of causal, command and control type
    structures.  



