#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Identity Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Identity  Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/05/01/abstract.org
  :Created:   2018-05-29T16:33@Prek Leap (11.642600N-104.919210W)
  :ID:        405c4130-e65f-47fd-8fba-a0733634d1a4
  :VER:       580858479.543540755
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:WOH2-0450
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope



** TL;DR


What is the history of identity models -- how did they
evolve, extend and externalize?

Was a person's identity different before speech?
What was a person's identity in the oral tradition?  

We have always had muliple roles -- personal, as parent, as
child, as specialist, as member of a tribe.

How does state legibility impact identity?
  - names -- legible names
  - changing names becomes difficult
  - changing family identity with a shared history and
    geneology
  - tie property to an identity
  - tie liability to an identity
  - tie wealth to an identity 

Why didn't we develop an identity model for the Internet
before?  Mostly because we still use an industrial-era
identity model where all records were stored on physical
media that wasn't easily copied, so there were only handful
of copies, which were difficult to locate and get access
to.  Not because of any great barriers put into place as
protection, but simply because they were scattered, and you
had to physically travel to a place and negotiate access
each place according to local rules.  And even then all
information was in a variety of organizational schemes.
