#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Identity Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]


* Identity Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/05/15/intro.org
:Created:  2018-05-02T19:46@Prek Leap (11.642600N-104.919210W)
:ID:       5820f0b9-5575-45a5-9bc2-d42545298fb1
:VER:      578537235.441931968
:GEO:      48P-491193-1287029-15
:BXID:     proj:OGR5-1388
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

#+begin_quote
“I am large, I contain multitudes.”

– Walt Whitman
#+end_quote

Identities are complex.  They are so complex and so deeply part of
what we are that they are difficult to understand.  We are social
creatures whether we like it or not.  And identity is only important
as a means of defining where one ends and another begins.  Other
people determine our identities, even though at first blush this seems
wrong.  But without other people there is no identity, there is only
the self which doesn't require a name, or relationships to other
people or obligations or rights or much of anything.  Without other
people there is only the distinction between you and the outside world
and how you determine what is trying to kill you, or will help you
survive.  You don't need an identity for that, only a concept of self
as being distinct from the rest of the world, and perhaps some drive
for self preservation.

Since we have different relationships to different people and
different groups of people, and belong to different places within the
social order depending on what your relationship is, we do not have a
single identity.  Before the Internet, this was normal.  We all play
different roles, that have different requirments that wall off
different apsects of our lives depending on what we are doing and who
we are doing it with.  If you had a role as college student, that role
was separate from the role as daughter or sister, or church member, or
as the drummer in a punk band, or as party animal on holiday during
spring break.  We had a reasonable expectation that what happened in
Vegas stayed in Vegas.  And that unless you diliberately told people
about something you did in a different role, you had a reasonable
expectation that most people wouldn't find out about it, unless you
did something really stupid that transcended role boundries.  Your
school could probably find out what you did on Spring Break, but it
would require more than a little effort and resources to do so.  And a
decade later when you had become a manager in a software company, it
wouldn't even occur to most people to try to find out what you had
done as an undergrad.  In fact our first reaction would be, that it's
none of the schools business what happened so long as it didn't impact
your role as employee.

The Internet changed all of that, not because people changed, but the
fences between roles no longer existed, because those who built social
media and other services never bothered to develop an identity model
that reflected how people really live.  What you did on Spring Break
was all lumped together with your Physics homework, and what music you
listen to, and who you are dating, and the school and your parents and
the state all see it as if it were part of each of those separate roles.

Social Media forces us to live in a [[https://en.wikipedia.org/wiki/Panopticon][Panopticon]] that has no privacy, no
walls no boundries.  This is a perverse way to live.  It has stripped
us of our freedom, our dignity and any way of living a normal life.

 Identity
     |
   Stage of Life
        |
        `-> Persona
               |
               `-> Role
               
* Identity

Is a concept, which, like a work in FRBR only exists as a concept.  In
practical terms, an identity will be the sum total of the personas and
roles that a person has.

We can create a container for all of this to be collected into a
single place but perhaps we couldn't.  Perhaps an identity is really
just a concept.  If there is a root place where all of the parts of
your identity are collected, it becomes centralized and subject to the
$5 Wrench Law.  Just knowing that it exists compromises you.

* Persona 

A persona is actually little more than a namespace which is used by
all of the roles that are played in that namespace.  A persona has a
backstory, reputation, property, assets etc.

It's actually difficult to live multiple personas at the same time
without leaking between them.  This is not a normal thing to do and if
you try to do it, it is very difficult.  But this doesn't mean that
personas are not important becuase our lives are never lived out in a
single persona, but broken into different personas that correspond to
different stages of your life.

* Role

Every person's life is made up of many different, overlapping roles
that we play.  Each role has a different set of relationships with
other people, and groups.  A role may have different responsibilities
and obligations, different access right and privileges.  Roles often
overlap with each other often we do things in more than one role at
the same time.  Roles can be owned by an organization, such as a job
title, which the person playing is just one of many.  A CEO of a large
company had other persons play that role in the past and others who
will play it in the future.  While you are in that role there are a
wide range of things that come with it, from access, power, money and
time constraints which will be lost when you are no longer playing
that role.

* Instance

An instance of a role (I don't like the name) is typically something
like a bank account, email address, account on social media, a drivers
licence, an educational degree or certification, citizenship etc.

* =============


Refs

   - [[http://www.slideshare.net/padday/bridging-the-gap-between-our-online-and-offline-social-network][Bridging the gap between our online and offline social network]]
   - [[http://www.sitepoint.com/an-introduction-to-google-plus/][An Introduction to Google]]

   - [[http://nautil.us/issue/9/Time/why-we-procrastinate][Why We Procrastinate]] | Issue 9: Time - Nautilus

   - [[bib:parfit:1984reasons][Reasons and Persons]] | Derek Parfit
   - [[https://en.wikipedia.org/wiki/Derek_Parfit][Derek Parfit]] | Wikipedia
   - [[https://en.wikipedia.org/wiki/Reasons_and_Persons][Reasons and Persons]] | Wikipedia
   

* Identity & Roles as Namespaces

The more I think about it, there is no way of separating a
shared role from a namespace -- each of our roles is part of
a collective, even if that is just two people.

We are not individuals -- we are corporate identities, even
to ourselves -- a loose overlapping ever changing collection
of roles, some internal, some external.

If you are the CEO of a company -- that is a role that you
represent in that company, it is not you, or even owned by
you.  In fact it doesn't even have to be a person at all, it
could be a piece of software.

Many if not most of our roles are not defined by us, they
are accepted (willingly or not) to be played by us, but they
are not us, and we don't own them.

So it makes sense that roles are defined by corporate bodies
and that while you take on that role, you will have a
name within a corporate namespace that is associated with you.

So your account on twitter or reddit, are in a sense, roles
within those communities.  A role is not the same as an
account but can be, it could also be a job title,
citizenship, membership in a party or church.  So far so
good.

But none of these roles are interoperable in a useful way to
the individual.  

What is needed is a reasonable level of privacy combined
with transparency.  When you are 30 years old you don't want
your boss to be able to easily find pictures of you at a keg
party in freshman year in uni, nor your uni schoolmates to
see your emo stage content you wrote in HS.  And you don't
want a master switch that unlocks it all by a guy with a $5
wrench aimed at your head.

So first -- all content should have a TTL that matches
different stages in your life.  And even within those stages
there should be a TTL.

In fact the TTL shouldn't be based on the content, but on
the role itself.  Your HS role will bleed over in the first
months you are at College, your single role will bleed over
to your engaged role and then into your married role and
then split into parent and married roles, but only for a set
period, and then things get archived under past roles.
Humans mark different stages of their lives within the
social groups they belong to.  This is natural.

Your role as programmer is a title owned by the corporation
-- but is not the same as your semi-private role as
colleague with others in the company while you worked there.
The boss has the right to data when you are in a corporate
role, but not to the data as a colleague even though most of
the interactions take place on company time and in company
facilities.  If you share a picture of your dog with the
girl at the desk across from yours, it is not owned by the
company and can not be seen by the company unless both
parties agree.  So if you slag off the boss -- you and the
person you told this to would have to agree to open this up
for the boss to see.  And there is no reason to disclose
that those roles exist to the company and there should be
plausible deniability when you create a role.

For this to work, shared roles should be created
automatically based on the context of what you are doing,
not only as an explicit act.  Then we can provide all sorts
of ways to consolidate roles like we do in version control.
Merge, squash etc.  So if a romance evolves from a
friendship, the two parties can squash a bunch of small
roles into a more formal private role.  You can also invite
people into a group, as well as kick them out (and make the
distinction of cutting them off from content they previously
had access to, or cutting off access to any content in the
group made after they had been kicked out).

Again, this is not a panacea -- it will still largely have
the same holes and be as messy as our real lives, but it
will provide a means of establishing reasonable behavior and
boundries we can live with.

This does not stop a three letter agency or a google or
facebook from hoovering up everything and keeping it
forever.

Then there is the problem of bad actors that make such
systems illegal or for a state to require backdoors, or to
provide wiretap access to any role.  I hope we can develop
the system so that states who do this, will have a handicap
that ultimately works against them. This is not something that
will be easy, or will be obvious.  I do think that this is
possible though.  If the system is not secure -- then it
can't be trusted.  

Remember, this identity system will be part of a larger
transaction system that is transparent and trustless.  

A bad state still has their $5 wrench -- which should be
enough.

And there is also facial recognition and other ways of
determining if the same person is the same in two different
roles.

But it will take some effort to do so -- and should require
non-trivial amounts of resources, just the same in the old
days that an investigator could go to your home town
library, and look up your yearbook, or go through county
records, or other public records and piece a lot things
together.  

There is no technological way of safeguarding such things --
it will have to be done through enforceble rules and laws,
and there should be requirements for warrants to have to be
issued to obtain access to different roles.

I strongly disagree with the idea of the right to be
forgotten as it stands now -- that is erasing things from
the public record and if it is clear what is private and
what is public then when something is made public, it should
stay public.

If you are a senator having an affair -- you and whoever you
are with can form a corporate joint identity that requires
any picture that is sent by either of you in that role to 
require consent from both parties to be shared.  This makes
dick pics a bit more difficult to leak into your public role
as senator, or your private role as father, or parent.

It will not prevent one of the parties from forking the
photo and making that public, but when that happens the
other party should be informed of the fork.  And even then,
you can do a screen capture of the picture that bipasses the
role as well, unless we lock down our applications to make
this difficult.  I don't know how I feel about that yet...

This will require more than a little bit of a learning curve
for us.  To keep roles from leaking too much.

It will also require that everything is encrypted --
everything -- and that we will have to do our own indexing
and generate our own metadata locally and then choose who
has access to what.

So when does something, in a shared role, become part of
that role?  When you mark something as shared?  When you said
it?  Can you edit your own content without the other party's
consent?  What about copy and paste something from one role
to another?  In order for this to work, we will need
the equiv of git for identities and roles.

When you buy a phone or camera -- you should first be asked
to create a key pair, that encrypts everything done on the
phone -- and you should be able to then check that the
software on the phone and the hardware hasn't been tampered
with by checking against a trusted authentication
source.... but that is a whole subject in its own right and
outside of the identity model.


---

myrole: deerpig

    private key
    public key

   - /u/deerpig  stamp  --> role-hash --> signed
   - @deerpig    stamp  --> role-hash --> signed 


* Roles as institutional intermediation

  - [[https://www.brookings.edu/wp-content/uploads/2017/05/more-professionalism-less-populism.pdf][more-professionalism-less-populism.pdf]] | brookings institute


* Context Crash
:PROPERTIES:
:ID:       b73bb864-bf93-43ea-bac9-355a8158dafe
:END:

#+begin_quote
 "technology exacerbates human misery as individuals become
 increasingly controlled by what they fail to understand."

 — Debra Howcroft and Brian Fitzgerald
   cite:howcroft:1998utopia

#+end_quote


#+begin_quote
In everyday life, we tend to have different sides of
ourselves that come out in different contexts. For example,
the way you are at work is probably different from the way
you might be at a bar or at a church or temple.

Sociologist Erving Goffman used concepts of theatre to
explain these different aspects of our identities, for
example, front stage and back stage.

But on Facebook, all these stages or contexts were mashed
together. The result was what internet researchers called
context collapse. People were even getting fired when one
aspect of their lives was discovered by another (i.e. their
boss!).

— Kate Raynes-Goldie
  [[https://phys.org/news/2018-01-secret-history-facebook-depression.html][The secret history of Facebook depression]] | Particle @phys.org
#+end_quote

#+begin_quote
In 2008, I found myself speaking with the big boss himself,
Facebook CEO Mark Zuckerberg. I was in the second year of my
Ph.D. research on Facebook at Curtin University. And I had
questions.

Why did Facebook make everyone be the same for all of their
contacts? Was Facebook going to add features that would make
managing this easier?

To my surprise, Zuckerberg told me that he had designed the
site to be that way on purpose. And, he added, it was
"lying" to behave differently in different social
situations.

Up until this point, I had assumed Facebook's socially
awkward design was unintentional. It was simply the result
of computer nerds designing for the rest of humanity,
without realising it was not how people actually want to
interact.

The realisation that Facebook's context collapse was
intentional not only changed the whole direction of my
research but provides the key to understanding why Facebook
may not be so great for your mental health.

— Kate Raynes-Goldie
  [[https://phys.org/news/2018-01-secret-history-facebook-depression.html][The secret history of Facebook depression]] | Particle @phys.org
#+end_quote

WTF "Facebook's context crash was intentional"!!! 


** References

 - [[https://boingboing.net/2018/01/22/facebook-is-sad.html][Social scientists have warned Zuck all along that the Facebook theory of interaction would make people angry and miserable]] | Boing Boing
 - [[https://phys.org/news/2018-01-secret-history-facebook-depression.html][The secret history of Facebook depression]] | Particle @phys.org

 Howcroft, D., & Fitzgerald, B., From utopia to dystopia: the
 twin faces of the internet, In , Information Systems:
 Current Issues and Future Changes, Proceedings of IFIP WG8
 (pp. 49–70) (1998). : . cite:howcroft:1998utopia

 Raynes-Goldie, K., The secret history of facebook
 depression, Particle (phys.org), (), (2018).
 cite:raynes-goldie:2018secret-history

 Raynes-Goldie, K. S., Privacy in the age of facebook:
 discourse, architecture, consequences (Doctoral
 dissertation) (2012). Curtin University, Perth, Australia.
 cite:raynes:2012privacy

* Dramaturgy & Spoiled Identity

** References
:PROPERTIES:
:ID:       70a468c9-8fa5-459a-9a04-26335c610a7a
:END:

Goffman, E., Stigma: notes on the management of spoiled
identity (1986), : Touchstone.
cite:goffman:1986stigma

Goffman, E., The presentation of self in everyday life
(2008), : Anchor Books [u.a.
cite:goffman:1986stigma

contributors, W., /Dramaturgy (sociology) --- wikipedia, the
free encyclopedia/ (2018).
cite:wiki:2018dramaturgy

contributors, W., /Erving goffman --- wikipedia, the free
encyclopedia/ (2018).
cite:wiki:2018erving-goffman



* An Identity Model
** Introducion

The identity model we develop for BMF has to be able to work not only
today, but a hundred years from now.  This may sound impossible, but
human beings change only very very slowly, and the way our brains are
wired has not changed much over the last 10,000 years.

We can get this right -- but it will take a lot of careful thought.

---

While @Padday's slide deck is brilliant -- he only really deals with
social network spaces and not so much about roles and identity.

Notes from:

http://www.slideshare.net/padday/the-real-life-social-network-v2

** Personal Social Networks

  - Different groups, based on different stages of your life,
    permanent groups like family, friends based on activities,
    interests and location.
  - Within these groups are people with Strong Ties and Weak Ties.
  - The number of Strong Ties is 4-6
  - The number of Weak Ties within a group is 4-15
  - Total Number of people the mind can keep track of is 150
  - There is another catagory of relationship which are Temporary Ties
    -- which are made up of people who you may only have one
    interaction with.

  Google+ Circles is designed to break up everyone into groups -- but
  perhaps it would be better to have circles within circles -- so you
  have an inner circle of people in a group with strong ties.

  They should also have different types of circles -- a news circle,
  social circles, and then circles for Temporary Ties.

  In this way we can then design a system that makes it possible for
  people to send status updates about what they eat to people with
  strong ties, and then more general updates, announcements to the
  broader circle.

  - I would also like to see a more dynamic element to how we map our
    circles -- this would freak people out today but will eventually
    be accepted.  

    You should be able to view your circles as:

    - composed -- or defined by you
    - relative to where you are and the context of that location --
      eg. on a train, in a restaurant with your wife (very different
      if you are in a restaurant with your mistress), at work, at your
      desk at work, in a meeting at work -- in a bar with friends at
      home, in a bar with strangers on holiday.
    - relative to what role you're in at the moment.
    - 

Telephones need to deal with this especially -- your role when
answering a call could/should trigger a bunch of different changes in
settings automatically -- and this will be very big -- Apple, Google
and Facebook will all try to corner this space and force people to use
their Identity models and services for communications -- but what is
needed is a general set of standards that everyone follows so that it
is interoperable between networks, so that someone using Google can
interact with the social graph of someone on Facebook.

So an application needs to do different things -- like logging work
related calls/messages to a work folder so that calls can be
logged/recorded for legal, billing or project management.

Identity -- is made up of how we want to be percieved

Question: Profiles -- how to create profiles that show different
things to different people depending on the context of that
relationship?


----

Now that we have that out of the way, let's start thinking about what
an identity model will look like.

** Person
*** Introduction
Before we get into what an identity is, it's useful to consider
entities that might have identities attatched to them.

*** Identity

Identity is the perception of the fact of being and what that person
is.  This is different depending on an individual's the point of view
relative to themselves and others. 

People have a constantly evolving perception of what they believe
they are (inner identity), which is different from how you try
to shape the way that others see us (projected identity).  This will
differ from how others percieve us which can vary wildly depending on
the context that a person is in.

From the perspective of a Police database, an identity includes
information that identifies that person, id or drivers licence or
social security numbers, physical description, gender, height, built,
eye and hair color, scars or tattoos.  The other side is of course the
record that the Police have on an individual.  This includes parking
or speeding tickets, criminal, immigration or drug violations etc.
From the perspective of a police database, a person's identity is the
perception of that person as being dangerous, or prone to violating
laws or not.  Unless a person is under investigation, the police
are not generally concerned with any other aspects of that person.
This is a fairly narrow and limited concept of an identity.

There are any number of equally narrowly defined concepts of identity
held by tax departments, banks, credit card companies, schools, the
military or any other type of employers.

In each case, each  are only interested in specific aspects of a
person's identity.  A doctor or hospital is interested in your blood
pressure, but not your love of LOL Cats.  A school is interested in
your attendance record, your grades and your course-load, but not your
hatred of Woody Allen films.  But these aspects of your life are of
very real importance to your family and close friends.

You present yourself differently depending on the context of the
relationship that you have with other people or groups.

And how you present yourself (your appearance and behavior) depends on
the relationships we have others.  These relationships and how they
are percieved are shaped by events and transactions between
individuals and groups.  This could be anything from having a flat
tire, to buying a house in a particular neighborhood, or going to a
specific restaurant, a phone call, email, comment on a social media
site.  But they also depend on events that are outside of an
individual or groups control.  A typhoon, earthquake, a summer shower,
a food poisoning scare, a flu epidemic, an accident that causes an
injury.  It also depends on age, cultural beliefs, social or econmic
class, education, intelligence, talent etc.

In short, identities are fluid and really really complicated.

Until the last few years, this has been all but ignored with online
manifestations of people's identities.  There have been a few
tentative steps towards addressing these issues, but we are still in
very early days.

What will eventually be needed is a general model for describing
online identities and how software and services can be organized in
order for people's online identities to accurately mirror their
identities in life.

*** Roles
**** Introduction
What is abundently clear is that there is no such thing as a single
identity for any person.  An individuals or groups identity are broken
into a variety of overlapping roles that define different aspects of a
person's identity such as student, friend, girlfriend, daughter etc.

Groups including corporations, goverments, religious organizations etc
also have any number of different roles including, vendor,
customer, litigant, employer, developer, sponsor, signatory, aggressor,
defender, contractor, vassel, colony, member.

**** Types of roles

Most roles often are manifest in a couple of types of
relationships.  This section is very much a work in progress and will
likely change as the different types of roles are better understood.

  - hierarchical :: One important relationship is hierarchial pairs
  where the role is relative to someone who is higher or lower than
  you in a hierarchy.  Examples of this include parent/child,
  teacher/student, employer/employee, celebrity/fan.
  - equivalence :: are equality pairings or groups where two or more
  people in the same role are of equal status within a relationship.
  These include coworker or colleague, spouse, team-mate, friend,
  spectator, lover, alumni, retiree, citizen, voter, patron.
  - generic :: a generic relationship describes a kind of class
  membership role.  These include retiree, victim, patient, addict,
  tourist, consumer.  There is a fine line between equivilant and
  generic roles.  For example, a voter can be viewed in one context as
  generic, but in another, where a voter is registered in a specific
  voting district, the relationship can be described as more
  equivilent.

Members within groups may be dominant or have higher status than
others.  For example, in a sports team, everyone on the team is a
teammate even though one member might also be captain of the team with
higher status and a leadership role.

**** Persistent and temporary roles

From the list of examples it's obvious that some roles are more
important and extend for longer periods than others.  A neighbor role
might last a lifetime if you live in the same place your whole life,
or it might last a few hours when you are sitting next to someone on a
plane, or get to know a family living in a bungalow next to yours when
you are on holiday for a couple of days.

While a temporary role may seem to be two brief to be defined in an
Identity model (no one is going to define a role before they purchase
a roll of toilet paper at Seven-Eleven) they are still important from
a generic transactional perspective.  You're role as a customer at
seven-eleven overlaps with your roles as Spouse, Father, Biological
Creature.  But unlike those other roles, a customer takes part in a
financial transaction, which carries with it certain responsibilities,
liabilities and other consequences, which processing software can help
provide in a particular context.  This can be done if the processing
application understands that you are a customer when you buy toilet
paper as well as a biological creature who needs to wipe their arse.
 
**** Internal/projected roles

Each role we have in our lives is made up of both an internal and
projected identities which include different titles, access
priviledges, responsibilities, modes of behavior and dress.

For Persistent roles, internal/projected aspects of our roles are
dynamic and constantly changing, using rule sets that dynamically
generate a snapshot of how we see ourselves or how we wish others to
see us.

For temporary roles, a ruleset is overkill and internal/projected
roles can easily be represented as a list of hierarchical
relationships and key/value pairs which define attributes that define
each role.

**** Roles cascade

The most important thing about roles is that they overlap, which will
not always the case when we begin talking about circles later on.
People get phone calls from their spouses when I work, requiring the
person to switch roles momentarily.  You might, for instance buy
Christmas presents for people who belong to circles in different roles
at the same time.

In order to reflect this, roles can be represented hierarchically in a
cascading structure where roles can be defined that inherit or share
aspects of other roles.

**** Roles and state

In a markup language or data structure, a key/value pair can be seen
as an attribute of what is being defined.  But that same key/value
pair when defined as a variable being executed in a software
application can be a boolean (true or false) which determines if an
action takes place or not.

This is important to point out because in order for this to work, an
application needs to determine which roles are active and which ones
are not.  If a role is active then things can happen.

If you are at work and recieve a call from your spouse, your phone
should be able to switch off your work role which is logging your
calls and time for billing purposes, and switch you into a privacy
mode where others aren't privy to the conversation.

If you are in a driver mode, your car computer system should tell your
phone to route calls to the hands free phone system built into the
car, adjust the seat for your height and weight and que up the podcast
that you were listening to when you left your desk.



*** Ties & Circles

A core part of Identity which is just as important as Roles is how we
map ourselves, in different roles at different times, in different
places with other people, groups and devices that we have ties with.

We all divide the people and groups we interact with into what Google
calls Circles.

**** Network of Devices 

You will have Circles for interacting with all of the network aware
devices that you own or control.

**** Proximity

Proximity -- when I am in Hong Kong, my circles are going to be very
different from when I am in Udon or in San Diego.  When you are on
holiday, you will have a very different set of temporary ties, and may
even establish short term strong and weak ties as well which will fade
and more often than not disappear as soon as you go back home.  The
same is true with time -- you might end up talking with some people at
different times of day because they are morning people, or because of
working hours or time zones.


** Horcrux

=Ghost= (as in the ghost in the machine) are digital cognitive
extensions of a biological, legal or corporate entity.  Ghosts are
made up of =Horcruxes= which are quasi-independent shards of ghost which
provide different contextual roles that a Ghost must operate in.  A
Ghost is a composite of its horcruxes.  And like in Harry Potter, a
Ghost can not die unless all of its Horcruxes have been destroyed.

  - Ghost
    - horcrux
    - horcrux 
    - horcrux
    - horcrux

A horcrux is a shard (contextual role) of a Ghost.  A ghost is an
individual cognitive entity, or a corporate (group entity).

Corporate Ghosts can be anything from a friendship between two people,
a workgroup a scopic shop, a guild, a government etc.

Our identities are the whole that only we can see -- it is inside our
heads.  We only show overlapping aspects of that whole -- it is
impossible for anyone to know the whole except the ghost in the
machine.

Incoming information needs to be identified, put into context and
become part of the world-view/map of the ghost.

Horcruxes define permissions; what is visable to other horcruxes, what
is visable to other ghosts and what is visable publically.  Incoming
information can be owned by multiple horcruxes, which can write and
execute -- or only be visable to some and only can be executable to
others.

A ghost is a composite distributed entity that is spread over many
instances -- and requires a consensus between a majority of instances
to make a decision.

A corporate ghost has members that also must reach a collective
consensus by voting.  Voting rights may be weighted so that some
members votes count for more than others.

A lot of what makes up Ghosts and their component horcruxes is by
looking for patterns in incoming information and figuring out what
they are, and how they fit into the meta-world-map that makes up the
Ghost's understanding of the external world.

This is done through an external service -- sort of a cognitive
indexing service -- you send incoming information to the service and
it will figure out what it is, (pattern recognition) and then a much
smaller local cognitive stack will find where it belongs in the
ghost's =meta-world-map= (MWM).  Once that happens, every query to the
MWM triggers another cascade of pattern recognition, and hopefully a
best =guess= -- which is the closest thing the system can come to an
answer.  A guess has associated values of match/no-match, degree of
certainty, and magnitude.  The higher these values, the more the ghost
can trust the match and broader, narrower, related and equiv links to
other concepts.  If there is no matching concept to a guess, a new
concept is established and given a place within the MWM that can
change over time as new information comes in.

The Ghost daemon determines what role a ghost is in at any given
moment -- which determines who sees what, and the context of what the
ghost is doing at at any one time.



** References

*** Dunbar Number

- Dunbar, R. I., Neocortex size as a constraint on group
  size in primates, Journal of human evolution, 22(6),
  469–493 (1992).
  http://dx.doi.org/10.1016/0047-2484(92)90081-J
  cite:dunbar:1992neocortex
- Wikipedia, , /Dunbar's number --- wikipedia, the free
  encyclopedia/ (2017).
  cite:wiki:2017dunbars-number

*** Original References (not in bib.bib)

 - [[http://www.nypost.com/p/news/national/buddy_brain_drain_n03pXeF8wGS5EEfCEOtKoI][Buddy Brain Drain]] | Robin Dunbar, New York Post, 2010/01/25
 - [[http://harvardmagazine.com/2010/05/networks-neolithic-now?page=all][Networks Neolothic to Now]] | Elizabeth Gudrais, Harvard Magazine, 2010/May-June
 - [[http://harvardmagazine.com/2010/05/networked][Networked]] | Robin Dunbar
 - [[http://www.lifewithalacrity.com/2004/03/the_dunbar_numb.html][The Dunbar Number as a Limit to Group Sizes]] | Christopher Allen
   Life With Alacrity (Blog), 2004/03/10
 - [[http://en.wikipedia.org/wiki/Dunbar's_number][Dunbar number]] | Wikipedia (accessed 2011/08/26)


 - [[http://en.wikipedia.org/wiki/Interpersonal_ties][Interpersonal ties]] | Wikipedia (accessed 2011/08/26)
 - [[http://www.stanford.edu/dept/soc/people/mgranovetter/documents/granstrengthweakties.pdf][The Strength of Weak Ties]] | Granovetter, Mark S. (1973). 
   Amer. J. of Sociology, Vol. 78, Issue 6, May 1360-80.
 - [[http://www.si.umich.edu/~rfrost/courses/SI110/readings/In_Out_and_Beyond/Granovetter.pdf][The Strength of the Weak Tie: Revisited]] | Granovetter, Mark S. (1983)
   Sociological Theory, Vol. 1, 201-33.
 - [[http://www.connectedthebook.com/][Connected: The Surprising Power of Our Social Networks and How They Shape Our Lives]] |
   Nicholas Christakis & James Fowler
   http://www.amazon.com/Connected-Surprising-Power-Social-Networks
 - [[http://www.digitalcenter.org/pages/site_content.asp?intGlobalId=20][Digital Future Report]] | Annual report 2000-2011
   Center for the Digital Future
 - [[http://www.hpl.hp.com/research/idl/papers/facebook/facebook.pdf][Rhythms of Social Interaction: Messaging within a Massive Online Network]] |
   Scott A. Golder, Dennis Wilkinson and Bernardo A. Huberman. 
   3rd International Conference on Communities and Technologies
   (CT2007). East Lansing, MI. June 28-30, 2007.
   http://www.hpl.hp.com/research/idl/papers/facebook/index.html (abstract)
 - [[http://www.thoughtcrumbs.com/publications/burke_chi2010_sns_and_wellbeing.pdf][Social Network Activity and Social Well Being]] | Burke, M.,
   Marlow, C., and Lento, T. (2010)
   ACM CHI 2010: Conference on Human Factors in Computing Systems, 1909-1912
 - Burke has a lot of other papers listed at http://www.thoughtcrumbs.com/
 - [[https://www.escholar.manchester.ac.uk/uk-ac-man-scw:2g20][The problem of conflicting social spheres]]
   Binder, Jens; Howes, Andrew; Sutcliffe
   AlistairIn: Boston, MA, USA. 2009. p. 965-974.
 - [[http://www.cs.ucsb.edu/~ravenben/publications/pdf/interaction-eurosys09.pdf][User Interactions in Social Networks and Their Implications]]
   Christo Wilson, Bryce Boe, Alessandra Sala, Krishna P. N. Puttaswamy 
   Ben Y. Zhao, ACM EuroSys, 2009
   http://www.cs.ucsb.edu/~ravenben/publications/abstracts/interaction-eurosys09.html (abstract)
 - [[http://www.ted.com/talks/stefana_broadbent_how_the_internet_enables_intimacy.html][Stefana Broadbent: How the Internet enables intimacy]] | TED
   Global 2009, filmed Jul 2009, posted Nov 2009
 - [[http://pewinternet.org/Reports/2010/Teens-and-Mobile-Phones.aspx][Teens, Cell Phones and Texting]] 
   Amanda Lenhart, Senior Research Specialist 
   Pew Internet & American Life Project, April 20, 2010
   http://pewresearch.org/pubs/1572/teens-cell-phones-text-messages (summary)
 - [[http://www.pewinternet.org/~/media//Files/Reports/2009/PIP_Tech_and_Social_Isolation.pdf][Social Isolation and New Technology]] | 
   Keith Hampton, Lauren Sessions Goulet, Eun Ja Her, Lee Rainie
   Pew Internet & American Life Project, Nov 4, 2009
 - [[http://pewinternet.org/Reports/2010/Social-Media-and-Young-Adults.aspx][Social Media & Mobile Internet Use Among Teens and Young Adults]]
   Amanda Lenhart, Kristen Purcell, Aaron Smith and Kathryn Zickuhr, 
   Pew Internet & American Life Project, February 3, 2010
   http://pewresearch.org/pubs/1484/social-media-mobile-internet-use-teens-millennials-fewer-blog (summary)
 - [[http://www.pewinternet.org/~/media//Files/Reports/2009/PIP_Twitter_Fall_2009web.pdf][Twitter and Status Updating]], Fall 2009 | Susannah Fox, Kathryn Zickuhr, Aaron Smith,
   Pew Internet & American Life Project, Oct 21, 2009.
 - [[http://www.amazon.com/Rethinking-Friendship-Hidden-Solidarities-Today/dp/0691127425][Rethinking Friendship: Hidden Solidarities Today]] | Liz Spencer, Ray Pahl
   Princeton University Press, August 21, 2006
 - [[http://en.wikipedia.org/wiki/Cognitive_bias][Cognitive bias]] | Wikipedia
 - [[http://en.wikipedia.org/wiki/List_of_cognitive_biases][List of cognitive biases]] | Wikipedia
 - [[http://en.wikipedia.org/wiki/Bounded_rationality][Bounded rationality]] | Wikipedia
 - [[http://en.wikipedia.org/wiki/The_Tipping_Point][The Tipping point]] | Wikipedia
 - [[tp://www.amazon.com/Six-Degrees-Science-Connected-Age/dp/0393041425/][Six Degrees: The Science of a Connected Age]] | Duncan J. Watts, 
   W. W. Norton & Company; 1st edition, February 2003
 - [[http://bear.warrington.ufl.edu/weitz/mar7786/Articles/Goldenberg%20et%20al%202009%20hubs.pdf][The Role of Hubs in the Adoption Process]]
   Jacob Goldenberg, Sangman Han, Donald R. Lehmann, & Jae Weon Hong 
   Journal of Marketing 3/1/2009 
   http://www.marketingpower.com/AboutAMA/Pages/AMA%20Publications/AMA%20Journals/Journal%20of%20Marketing/TOCs/SUM_2009.2/role_of_hubs_adoption_process.aspx (summary)
 - [[http://marketing.wharton.upenn.edu/documents/research/Npd.pdf][Opinion Leadership and Social Contagion in New Product Diffusion]] 
   Raghuram Iyengar, Christophe Van den Bulte, and Thomas Valente, 
   2008 [08-120]
 - [[http://www.danah.org/papers/][Danah Boyd's]] Publications
 - [[http://ieeexplore.ieee.org/abstract/document/1579411/][Profiles as Conversation: Networked Identity Performance on Friendster]] 
   Boyd, Danah & Jeffrey Heer
 - [[http://www.danah.org/papers/HICSS2006.pdf][In Proceedings of the Hawai'i International Conference on System]]
   Sciences (HICSS-39), Persistent Conversation Track. Kauai, 
   HI: IEEE Computer Society. January 4 - 7, 2006.
 - [[http://research.yahoo.com/files/p2393-gross.pdf][Addressing Constraints: Multiple Usernames, Task Spillage and Notions of Identity]]
   Gross, B.; Churchill, E.F.
   Source: CHI 2007, ACM Press, San Jose, CA, USA, p.2393-2398 (2007)
   http://research.yahoo.com/node/2171 (abstract)
 - [[http://bengross.com/pubs/ieee-sc09/ieee-sc09.pdf][Names of Our Lives]] | Ben Gross
   CSE ’09. International Conference on Computational Science and Engineering, 
   volume 4, pages 747–752, Vancouver, Canada, August 29–31, 2009.
 - [[http://bengross.com/publications/][Ben Gross]]'s Publications
 - [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.108.986&rep=rep1&type=pdf][Trust and nuanced profile similarity in online social networks]] | 2006
   Jennifer Golbeck
   http://dl.acm.org/citation.cfm?id=1594174 (abstract)
 - [[http://www-personal.umich.edu/~ladamic/papers/trust/TengTrustWOSN2010.pdf][I rate you. You rate me. Should we do so publicly?]]
   Chun-Yuen Teng, Debra Lauterbach, and Lada A. Adamic
 - [[http://www.heinz.cmu.edu/~acquisti/papers/privacy-facebook-gross-acquisti.pdf][Information Revelation and Privacy in Online Social Networks]] (The Facebook case)
   Pre-proceedings version. ACM Workshop on Privacy in the Electronic Society (WPES), 2005
   Ralph Gross, Alessandro Acquisti, H. John Heinz III
 - [[http://www.pewinternet.org/~/media//Files/Reports/2010/PIP_Reputation_Management_with_topline.pdf][Reputation Management and Social Media]]
   Mary Madden, Aaron Smith
   Pew Internet & American Life Project, May 26, 2010
 - [[hoofnagle:2010different][How Different are Young Adults from Older Adults When it Comes to Information Privacy Attitudes and Policies?]]
   Hoofnagle, Chris Jay, King, Jennifer, Li, Su and Turow,
   Joseph, (April 14, 2010). 
   Available at SSRN: http://ssrn.com/abstract=1589864
 - [[http://www.bcs.org/upload/pdf/ewic_hc08_v1_paper11.pdf][Strategies and struggles with privacy in an online social networking community]]
   Katherine Strater, Heather Richter Lipford
   Proceeding BCS-HCI '08 Proceedings of the 22nd British HCI Group 
   Annual Conference on People and Computers: Culture, Creativity, 
   Interaction - Volume 1
 - [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.157.7401&rep=rep1&type=pdf][Expandable grids for visualizing and authoring computer security policies]]
   Robert W. Reeder, Lujo Bauer, Lorrie Faith Cranor, Michael K. Reiter, 
   Kelli Bacon, Keisha How, Heather Strong
