#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 2.10.2 Entity Model
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [[[./intro.org][prev]]] [[[./03-ontologies.org][next]]]

* 2.10.2 Entity Model
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-entities.org
:Created:  2018-03-27T19:33@Prek Leap (11.642600N-104.919210W)
:ID:       674a5f75-68c9-4362-9092-684ef90d4b8f
:VER:      575426074.504527788
:GEO:      48P-491193-1287029-15
:BXID:     proj:HLM3-7344
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Table of Contents
 - What is an Entity Model
 - FRBR
 - FRAD

** TL;DR

First, FRBR/FRAD are designed for third party organizations
to establish bibliographic data of published information and
establish relationships to the different forms those works
take and place them in context with people, corporate
bodies, objects, events, concepts and places.

 - Work
   - Expression
     - Manifestation
       - Instance

 - person
 - family
 - corporate body

 - object
 - event
 - concept
 - place

Out goal here is to establish a conceptual model that can be
used for creating externalized world models.  We are trying
to create maps of the world.  So the scope is much broader,
but it also must be far more flexible.  After banging my
head against the wall on this for about 20 years, it's clear
that there way that a detailed model can be constructed that
will even remotely do the job -- so we need a framework that
anyone can use to create their own entity groups and ensure
that any group created by anyone can be interoperable or at
least map to any other group that is describing the same
things.

Second, our goals is that these are not external records
about external things -- meta data -- literally data that
describes data, objects, people etc.  But that there is no
functional difference in many context between them.  Our
metadata for Charles Dickens is all that is left of the man
except whatever mortal remains still exist in his grave.  So
the metadata we have about him is as close and you can get
to him -- everything recorded or written about him or by him
are external and from different POVs and LODs.
