#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 2.10.5 Succession Model
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [[[./04-pace-layers.org][prev]]] [[[./06-goldilocks.org][next]]]

* 2.10.5 Succession
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-succession-model.org
:Created:  2018-03-22T12:02@Prek Leap (11.642600N-104.919210W)
:ID:       1a0e2740-9b50-4db2-9c17-7e3601374b2d
:VER:      574967007.402589543
:GEO:      48P-491193-1287029-15
:BXID:     proj:TNA7-1268
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

The principle is that if the conditions are right,
self-organizing systems tend to go from lesser to greater
complexity.

There are limits to complexity imposed by the size of the
carrying capacity.

Increasing complexity can extend carrying capacity.

When complexity can no longer increase carrying capacity,
systems collapse and revert to lower levels of complexity,
which creates opportunities for increasing complexity again.
This is often cyclical and has been seen repeatedly from
major extinction events on earth, to the collapse of complex
societies.  The tendency is, that after a collapse, the new
system that emerges from the ashes has "learned" from it's
previous mistakes and is replaced by a more robust and even
more complex system -- so that the system is cyclical in
nature, but is also iterative and increases in complexity
with each new cycle.

The most dramatic of these cycles in in major extinction
events.

** Table of Contents
 - Succession models
   - Number of Niche/Specialties determine complexity
   - Niches and specialities can be divided or consolidated.
   - Number of niches is determined by size of territory 
 - Reversibility
   - upgrade & degrade
 - Keystones
   - species
   - concepts
   - niches
   - specializations
   - standards
   - designs
 - Stages
   - ecological
   - economic
   - technological
   - cultural
   - [[./ww-ages-of-man.org][Ages of Man]]

 - Succession stacks
   use POC so that succession is treated as a stack, not
   one stage replacing another.  This is useful to apply LOD
   to a text, so that you can read a layer at a low LOD (say
   for beginners, and then move down to progressively more
   detailed and more advanced material.
    
** Succession Models

This works the same as in [[https://en.wikipedia.org/wiki/Ecological_succession][ecological succession]] but for
civilization:

  - terrestrial 
    - nomadic hunter-gather
    - semi-nomadic
    - sedantary 
      - agricultural -> villages and towns
      - industrial   -> cities and states
      - info-network 
      - machine-cog  -> machine-cognition controlling machines
  - extra-terrestrial
    - nomadic -> exploritory  -> robotic then human
    - sedantary
      - stations
      - colonies
      - solar civilizations 
  - extra-solar

Sucession can be linear or cyclical.  Any stage can move on
to the seceeding stage or revert to previous stages.  It's
possible to jump stages -- but as a general rule this should
be avoided.  Just as a human embyro passed through different
evolutionary stages in the womb, jumping to an advanced
stage directly is both difficult and runs the risk that it
will not be complete.  This holds for both ecological
succession as well as societal succession and technological
succession.  It's not a good idea for human societies to try
and jump stages -- the changes are too traumatic and will
result in disruption that will cause irreparable damage to
the society.  The same is true of humans, but is a different
way.  People can only change so much in a lifetime, unless
they have been able to learn to internalize change massive
change.  And even then it's limited.


stages of the primer will provide generative grammars for
each layer as well as all of the knowledge needed to build
that stage and lay the groundwork for the next stage.

The primer is focused on expressions of civilization rather
than manifestions or instances.

In this respect, the primer is prescriptive more than
descriptive.

The primer will include specific recomendations for
standards -- weights and measures, standard things like
screw and bolt thread specifications, guages of wire etc.

It will provide keystone designs for things like electrical
sockets, hinges, electric motors.

It will provide keystone designs for processes and keystones
for building them for different succession layers.

*** Terms

- succession stage --
- keystone designs -- reference designs 
** Reversibility

When possible everything in the primer should at least try
to be capable of gracefully degrading, so that if there is a
problem that knocks you back to a previous stage, you are
not screwed.

If this is designed into the system from day one, then some
interesting things become possible -- we can provide
keystone designs which can be upgraded years or decades
later.

    Let's use a washing machine as an example. An agitating
    clothes washer can be build that will work mechanically,
    with any power source from using water or even a biycle
    as well as an electrical motor.  Controls for the
    washing machine can be mechanical, or electronic.  You
    could also create an API and a network interface and
    install sensors in the washing machine so that the
    machine could me controlled remotely via software or
    machine-cog.  Since washing machines can have used to be
    built that lasted decades with little or no maintenance,
    there is no reason why we can't have design where you
    can upgrade a machine for electricity then electronics
    and then network controllable.  And this should then
    work in reverse.  If the network is down, it should work
    electronically, if the electronics are down it should
    work mechnically with electricity, if electricity is
    down you should be able to reconnect the belt to a
    mechanical power source.

Such designs are not as easy to build as designs that are
built for a single succession stage -- but because a washing
machine, if well designed and built, should easily last a
half century, then it makes sense to take the extra effort
to make it both upgradable and degradable
