#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 2.10.8 World Models
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [prev]

* 2.10.8 World Models
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/02/10/08-world-models.org
:Created:  2018-04-22T10:15@Prek Leap (11.642600N-104.919210W)
:ID:       b3233769-7496-4258-983b-d7301720ea8f
:VER:      577638986.816974098
:GEO:      48P-491193-1287029-15
:BXID:     proj:MLT0-7470
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Table of Contents

 - 01 Worldview
 - 02 Consciousness
 - 03 Global Workspace Theory
 - 04 Externalized Worldviews

** TL;DR

Break into three parts.


** Worldview

We start with the traditional concept of a worldview which
is a mental model of the world.

#+begin_quote
worldview is the fundamental cognitive orientation of an
individual or society encompassing the whole of the
individual's or society's knowledge and point of view. A
world view can include natural philosophy; fundamental,
existential, and normative postulates; or themes, values,
emotions, and ethics.

— cite:wiki:2018worldview
#+end_quote

Worldviews provide a framework for placing what you know
about the world through sensual experience, and cognitive
inductive and deductive reasoning with what is unknown or
unknowable.  Worldviews provide a shared model of the world
that make it possible not only to communicate but to
cooperate with each other.

Worldviews are externalized and manifested in folk-epics
like Homer's /Iliad/ which Eric Havelock describes as a
cultural encyclopedia for a
civilization. cite:havelock:1963preface 

** Consciousness

** Global Workspace Theory

We can then dig deeper and see if worldviews are a
fundemental part of how the brain works. This becomes a bit
tricky territory because is involves neuroscience work on
the nature of consciousness as defined in Global Workspace
Theory cite:wiki:2018global-workspace-theory

#+begin_quote
The cognitive neuroscientist Stanislas Dehaene and his
collaborators have argued that consciousness functions as a
“global workspace” or “blackboard” representation.41 The
blackboard metaphor refers to the way that a diverse set of
computational modules can post their results in a common
format that all the other modules can “see.” Those modules
include perception, memory, motivation, language
understanding, and action planning, and the fact that they
can all access a common pool of currently relevant
information (the contents of consciousness) allows us to
describe, grasp, or approach what we see, to respond to what
other people say or do, and to remember and plan depending
on what we want and what we know. (The computations inside
each module, in contrast, like the calculation of depth from
the two eyes or the sequencing of muscle contractions making
up an action, can work off their own proprietary input
streams, and they proceed below the level of consciousness,
having no need for its synoptic view.) This global workspace
is implemented in the brain as rhythmic, synchronized firing
in neural networks that link the prefrontal and parietal
cerebral cortexes with each other and with brain areas that
feed them perceptual, mnemonic, and motivational signals.

— cite:pinker:2018enlightenment p.695
#+end_quote

What I find exciting about workspace theory is that it not
only gives us some empirical understanding of consciousness
as a cognitive mechanism.  I would say that workspace theory
fits will with Daniel Dennet's "multiple draft" model. 

#+begin_quote
Dennett puts forward a "multiple drafts" model of
consciousness, suggesting that there is no single central
place (a "Cartesian Theater") where conscious experience
occurs; instead there are "various events of
content-fixation occurring in various places at various
times in the brain". The brain consists of a "bundle of
semi-independent agencies"; when "content-fixation" takes
place in one of these, its effects may propagate so that it
leads to the utterance of one of the sentences that make up
the story in which the central character is one's
"self". Dennett's view of consciousness is that it is the
apparently serial account for the brain's underlying
parallelism.

— cite:wiki:2018consciousness-explained
#+end_quote

** Externalized Worldviews

The third part will explore how we can use directed-graphs
that connect recorded information to create a
machine-cognitive worldview which is an analog to both a
human/societal worldview and a global workspace that
provides a contextual framework.  Put simply that our
externalized recorded information that extends our memory
and cognition can become an externalized worldview in it's
ownright and that this has the potential of becoming a
cornerstone of machine-cognition and human-machine
interaction.

At a larger societal level, organizations, for the first
time will be able to maintain worldviews that are clearly
defined and are independent of the members of that
organization.  Groups and organizations from workgroups, to
subcultures, to corporations and states have all had
worldviews which existed on paper, and as a sort of a
distributed hive-mind made up of the individuals mental
model of that worldview in each of their brains.

This will make it possible for externalized organizations
such as corporations, who are legally persons in some
states, to actually become at least semi-autonomous agents
in their own right with lesser or greater ability to be
self-directing within narrow ranges of tasks.  In effect it
would constitute a kind of consciousness.  I would like to
stress that these are not human-like intelligences.

This is exactly the scienario that scares the living shit
out of a lot of people.  But I would argue that Charles
Stross got it right:

#+begin_quote
Corporations are cannibals; they consume one another. They
are also hive superorganisms, like bees or ants. For their
first century and a half they relied entirely on human
employees for their internal operation, although they are
automating their business processes increasingly rapidly
this century. Each human is only retained so long as they
can perform their assigned tasks, and can be replaced with
another human, much as the cells in our own bodies are
functionally interchangeable (and a group of cells can, in
extremis, often be replaced by a prosthesis). To some extent
corporations can be trained to service the personal desires
of their chief executives, but even CEOs can be dispensed
with if their activities damage the corporation, as Harvey
Weinstein found out a couple of months ago.

Finally, our legal environment today has been tailored for
the convenience of corporate persons, rather than human
persons, to the point where our governments now mimic
corporations in many of their internal structures.

— cite:stross:2017dude
#+end_quote


** References
  - Dehaene, S., & Changeux, J., Experimental and
    theoretical approaches to conscious processing, Neuron,
    70(2), 200–227 (2011).
    http://dx.doi.org/10.1016/j.neuron.2011.03.018
    cite:dehaene:2011experimental
  - Dehaene, S., /Signatures of consciousness--a talk by
    stanislas dehaene/ (2009).
    cite:dehaene2009signatures
  - Dehaene, S., Towards a cognitive neuroscience of
    consciousness: basic evidence and a workspace framework,
    Cognition, 79(1-2), 1–37 (2001).
    http://dx.doi.org/10.1016/s0010-0277(00)00123-2
    cite:dehaene:2001framework
  - Dennett, D. C., Consciousness Explained (1992), : Back
    Bay Books.
    cite:dennett:1992consciousness-explained
  - Gaillard, R., Dehaene, S., Adam, C., Clémenceau, S.,
    Hasboun, D., Baulac, M., Cohen, L., …, Converging
    intracranial markers of conscious access, PLoS Biology,
    7(3), 1000061 (2009).
    http://dx.doi.org/10.1371/journal.pbio.1000061
    cite:gaillard:2009converging
  - Pinker, S., Enlightenment now: the case for reason,
    science, humanism, and progress (2018), : Viking.
    cite:pinker:2018enlightenment
  - Rothman, J., /Daniel dennett’s science of the soul: a
    philosopher’s lifelong quest to understand the making of
    the mind./ (2017).
    cite:rothman:2017daniel-dennett 
  - Sire, J. W., Naming the elephant: worldview as a concept
    (2004), : IVP Academic.
    cite:sire:2004naming-elephant
  - Sire, J. W., The universe next door: a basic worldview
    catalog, 5th edition (2009), : IVP Academic.
    cite:sire:2009universe-next-door
  - Stross, C., /Dude, you broke the future!/ (2017).
    cite:stross:2017dude
  - Underhill, J. W., Creating worldviews : metaphor,
    ideology and language (2011), : Edinburgh University
    Press.
    cite:underhill:2011creating-worldviews 
  - Underhill, J., Humboldt, worldview, and language
    (2009), : Edinburgh University Press.
    cite:underhill:2009humbolt
  - Wikipedia, , /Global workspace theory --- Wikipedia, the
    free encyclopedia/ (2018).
    cite:wiki:2018global-workspace-theory
  - Wikipedia, , /World view --- Wikipedia, the free
    encyclopedia/ (2018).
    cite:wiki:2018worldview
  - Wikipedia, , /Consciousness explained --- Wikipedia, the
    free encyclopedia/ (2017).
    cite:wiki:2018consciousness-explained

