#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Bits Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Bits Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/ww01/abstract.org
  :Created:   2018-09-22T10:35@Prek Leap (11.642600N-104.919210W)
  :ID:        837b9ead-050b-4c5f-921b-f7932ddc60ce
  :VER:       590859374.265950660
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:QIQ5-2521
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope

The problem of where to begin is always vexing.  Beginnings
are arbitrary and subject to where you happen to be in
relation to what you happen to be looking at.  There are no
absolute beginnings -- you can always add or subtract
something to or from a set.  The best you can do is start
with what is known while knowing that we step into a river
that can never be stepped in twice.

We need to agree on a set of first facts, while being
mindful that we won't all agree on some, and in time many
will be replaced.

So we wipe the slate clean, collect our first facts and
starting from first principles begin to frame a narrative of
who and where we are, where and when we came from, our
strengths and weaknesses and how to go about building a
sound foundation for a civilization that will serve
Mankind's needs for the next century and beyond.

** TL;DR

Our objective here is positivist but not as part of any
specific scientific paradigm, discipline or tradition.
Rather, this is an attempt at building a consistent general
model of the world that is consistent with evidence, thought
and discourse across the sciences, arts, crafts and
cultures. Our purpose is to create a common inclusive
framework for Mankind, as individuals, societies and the
constantly evolving civilzation we live our lives in.

We start with first facts and build from first principles
the best we can; obviate what separates us from ourselves,
each other and clouds the mind and senses.  We Sapiens are
but one species in a vast continuum of life spanning
billions of years and trillions of species ranging in size
from the micro to megascopic living in a shared biosphere.

The strong force ... the weak force ... gravity gives us
place to stand with an an up and down and keeps things from
flying apart and at the right distence from the sun to keep
water liquid, an atmosphere thick enough to sheild us from
being cooked by cosmic and solar radiation and light enough
for photosynthesis and to navigate using a narrow band of
the electromagnetic spectrum.

We are not /one with nature/.  We are simply a subset of
time, space matter and energy, not outside, not apart. The
ghost and the machine are but tiny motes of complexity in
the vastness of the heavens our ancestors saw in the broad
swath of the Milky Way on clear starry nights amid the
cacophanic nocturn of insects and creatures about their
business in the darkness.

For this to work, our common narrative must necessarily be
loose, yet spun from the toughest fibers into threads that
become stronger over time ra, conceptional framework that is
resistent to being frozen into dogma and ideological roach
motels.  Owning up to our ignorance also means being honest
enough to admit that even our most cherished beliefs about
the world must be challenged and periodically overturned
without threatening our identity, dignity and moral
compass. We live but an exceedingly brief time and will be
dead forever after. To live is to change and we must embrace
and celebrate that change and work to ensure that change
leads to a larger and better world for ourselves and those
who come after us.


