#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Bits Abstract
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Bits Abstract
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/ww01/abstract.org
  :Created:   2018-09-22T10:35@Prek Leap (11.642600N-104.919210W)
  :ID:        837b9ead-050b-4c5f-921b-f7932ddc60ce
  :VER:       590859374.265950660
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:QIQ5-2521
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope

Human's can't grasp infinities.  We loose grip, and are lost
in things without end.  We do know madness all to well.
Deep down we know our limits, limits of knowing, limits of
seeing, limits of feeling when we stray too far from the
narrow scope of human scale.

Best thing is to start with what is known while knowing we
are stepping into a river that can never be stepped in
twice.  So define variables and constants and set them as
first facts, ever mindful that we won't all agree on some,
and that in time, many others will be replaced by those who
see further than ourselves.

Now wipe the slate clean, collect these, our first facts,
and starting from first principles, frame a narrative of who
and where we are, where and when we came from, our strengths
and weaknesses and how to go about setting the cornerstones
for a civilization that will serve Mankind's needs for the
next century and beyond.

** TL;DR

Our objectives are positivistic, but not as part & parcel of
any one paradigm, discipline or tradition.  Rather, this is
an attempt at building a general model of the world that is
consistent with evidence, thought and discourse across the
sciences, arts, crafts and cultures. Our purpose is to
create a common inclusive framework for Mankind, as
individuals, societies and the constantly evolving
civilzation we live our lives in.

Starting from first facts we build from first principles the
best we can and obviate that which clouds the mind and
senses that separate us from ourselves, and each other.

The strong force ... the weak force ... gravity gives us a
place to stand with an up and down and keeps things from
flying apart in an orbit at the right distance from the sun
to keep water liquid, an atmosphere that keeps us from being
cooked by cosmic and solar radiation and light enough for
photosynthesis and to navigate using a narrow band of the
electromagnetic spectrum.

As Sagan said, we are stardust, every atom of every one of
us, a subset of time, space, matter and energy, not outside,
not apart. The ghost and the machine are but tiny motes of
complexity in the vastness of the heavens our ancestors saw
in the broad swath of the Milky Way on clear starry nights
amid the cacophanic nocturn of insects and creatures about
their business in the darkness.

We Sapiens are but one species in a vast continuum of life
spanning billions of years and trillions of species ranging
in size from the micro to megascopic living in a shared
biosphere.



For this to work, our common narrative must necessarily be
loose, yet spun from the toughest fibers into threads that
become stronger over time, a conceptional framework that is
resistent to being frozen into dogmatic and ideological
roach motels.  Owning up to our ignorance means being honest
enough to admit that even our most cherished beliefs about
the world must be challenged and periodically overturned
without threatening our identity, dignity and moral
compass. We live but an exceedingly brief time and dead
forever after. The time we have needs to count.  Life, as is
any dynamic complex system, is by definition in constant
motion, forever in the process of becoming something else.
We embrace and celebrate that process and work to ensure
/that/ change leads to a larger and better world for
ourselves and those who come after us.


