#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Bits Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Bits Introduction
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/ww01/intro.org
  :Created:   2018-09-23T09:01@Prek Leap (11.642600N-104.919210W)
  :ID:        ff1b7867-bf2e-4f8e-9be6-9c803d594c6f
  :VER:       590940148.683874232
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:XCF5-1347
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:


** A Bead Game
Cross discipline synthesis and universality - a kind of meta narrative
or paradigm that provides interoperability between traditions,
theoretical frameworks, vocabularies and cultures.

This makes it possible for people from different disciplines,
traditions and cultures making cross-discipline cooperation.

** It from Bit
Informational basis of the universe.

** Information
What is information

** Human & Machine Legibilty

** Symbols
Binary bits grouped into bytes representing symbols. or in reverse, we
encode symbols using bytes.

and bytes grouped into compound symbols (words).

Symbols can then be broken down into different datatypes -- symbols,
strings, numbers (integers, floats etc), lists.

** Grammar
Rules for manipulate symbols

Requirements:

  - homoiconicity
  - unambiguous
  - datatypes
  - s-exps
** Relationships
We now have a symbol system but 

** Tuples
N-Quads

** Graphs

Graphs treat the relationships between things as just as
important as the information that they link to.

 - data        :: /list/, an random set of symbols and
                  numbers.

 - information :: /key-value pair/, a structured and labeled
                  set of symbols and numbers.

 - knowledge   :: /directed-graph/, a map of relationships
                  of information in a set. 

---------

This does not belong here:

 - insight     :: recognition of a correlation between two
                  or more pieces of or classes of
                  information and relationships.

 - wisdom      :: or /wise-reasoning/ a multi-facet process
                  that synthesizes of multiple graphs
                  representing different LOC and POV and
                  employ compound algorithmic queries.
                  SEE: cite:grossmann:2016wise  
                  — [[https://www.psychologytoday.com/us/blog/the-athletes-way/201606/what-is-wisdom-wise-reasoning-has-three-specific-facets][wise-reasoning]], Psychology Today, 2016-6-9.


**** Fnords

** Mechanisms
  - form
  - chunking
  - process
  - propagation
*** Chunking
LOD

gives us:
  - complexity
  - wholes
  - heirarchies
  - holons and holarchies
  - patterns
  - maps
  - sets

*** Form
matter
differentiation of space
*** Process
energy
things becoming something else
entropy -- second law of thermodynamics
motion
time

*** Propagation
Time
ROC

** Systems
** References

Hesse, H., Magister Ludi (1957), : F. Ungar Pub. Co.
cite:hesse:1957magister-ludi
