#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Bits Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Bits Introduction
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/ww01/intro.org
  :Created:   2018-09-23T09:01@Prek Leap (11.642600N-104.919210W)
  :ID:        ff1b7867-bf2e-4f8e-9be6-9c803d594c6f
  :VER:       590940148.683874232
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:XCF5-1347
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

#+begin_quote
Service to others is the rent you pay for your room here on
earth.

— Muhammad Ali, Time (Feb. 27,1978) 
#+end_quote

The Chenla Institute is dedicated to research, publication,
and consulting, on how to build a sustainable, distributed,
human scale civilization, with a focus on profitable
innovations for alleviating extreme poverty and providing a
reliable path for moving up the economic ladder to form a
new kind of sustainable middle-class with a standard of
living and quality of life & work that is only rarely
experienced even in developed economies today.  This is
accomplished through /research/ and publication focused on a
specific long-term vision for the future, while focusing
/development/ on implemention of short and medium term
projects which will materially improve the lives of people
today.  Put simply, think and plan for a better world
tomorrow while building that future, brick-by-brick from the
bottom up, today.

** A Bead Game
Cross discipline synthesis and universality - a kind of meta
narrative or paradigm that provides interoperability between
traditions, theoretical frameworks, vocabularies and
cultures.

This makes it possible for people from different
disciplines, traditions and cultures making cooperation
possible across disciplines.

cite:hesse:1957magister-ludi,alexander:1968bead,grabow:1983christopher

In the end, any map is what is observed after a territory
collapses and becomes legible.

Make no mistake, we're willfully tinkering with the
World-System here, lobbing out generative grammars and
observing the aftermath of each iteration to see how much
you can push the world before some nameless horror in the
void takes notice and begins to push back.



** First Facts

Six numbers determine that we live in a universe that
supports life.

  - ε — Episilon = 0.007
    Relative Amount of hydrogen that converts to Helium via
    Fusion in the big Bang
  - N=10^36
    Strength of the electric force divided by the strength
    of gravity
  - Ω — Omega
    Relative Density of the Universe
  - Λ — Lambda
    Cosmological Constant
  - Q
    Amplitude of Irregularities in the CMB
  - D 
    Number of Spatial Dimensions  


cite:rees:1999six-numbers,radford:2012six-numbers

- [[https://www.cheatography.com/davidpol/cheat-sheets/just-six-numbers/][Just Six Numbers Cheat Sheet]] by Davidpol

** It from Bit
Informational basis of the universe.

cite:deutsch:2002it-to-qubit,wheeler:1992itfrombit

** Information
What is information

cite:floridi:2010information,gleick:2011information

** Human & Machine Legibilty

** Symbols
Binary bits grouped into bytes representing symbols. or in reverse, we
encode symbols using bytes.

and bytes grouped into compound symbols (words).

Symbols can then be broken down into different datatypes -- symbols,
strings, numbers (integers, floats etc), lists.

** Grammar
Rules for manipulate symbols

Requirements:

  - homoiconicity
  - unambiguous
  - datatypes
  - s-exps
** Relationships
We now have a symbol system but 

** Tuples
N-Quads

** Graphs

Graphs treat the relationships between things as just as
important as the information that they link to.

 - data        :: /list/, an random set of symbols and
                  numbers.

 - information :: /key-value pair/, a structured and labeled
                  set of symbols and numbers.

 - knowledge   :: /directed-graph/, a map of relationships
                  of information in a set. 

---------

This does not belong here:

 - insight     :: recognition of a correlation between two
                  or more pieces of or classes of
                  information and relationships.

 - wisdom      :: or /wise-reasoning/ a multi-facet process
                  that synthesizes of multiple graphs
                  representing different LOC and POV and
                  employ compound algorithmic queries.
                  SEE: cite:grossmann:2016wise  
                       cite:weststrate:2016wisdom
                  — [[https://www.psychologytoday.com/us/blog/the-athletes-way/201606/what-is-wisdom-wise-reasoning-has-three-specific-facets][wise-reasoning]], Psychology Today, 2016-6-9.


**** Fnords

** Mechanisms
  - form
  - chunking
  - process
  - propagation
*** Chunking
LOD

gives us:
  - complexity
  - wholes
  - heirarchies
  - holons and holarchies
  - patterns
  - maps
  - sets

*** Form
matter
differentiation of space
*** Process
energy
things becoming something else
entropy -- second law of thermodynamics
motion
time

*** Propagation
Time
ROC

** Systems
** References

Hesse, H., Magister Ludi (1957), : F. Ungar Pub. Co.
cite:hesse:1957magister-ludi
