#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Epigraph
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Epigraph
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-epigraph.org
:Created:  2018-04-10T10:05@Prek Leap (11.642600N-104.919210W)
:ID:       fbc18a28-627d-4498-a77d-25e18b9abfd7
:VER:      576601600.674855099
:GEO:      48P-491193-1287029-15
:BXID:     proj:WAS1-1404
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Epigraph: Warp & Woof

#+begin_verse
    MAXIMUS, TO HIMSELF

    I have had to learn the simplest things
    last. Which made for difficulties.
    Even at sea I was slow, to get the hand out, or to cross
    a wet deck.
            The sea was not, finally, my trade.
    But even my trade, at it, I stood estranged
    from that which was most familiar. Was delayed,
    and not content with the man’s argument
    that such postponement
    is now the nature of
    obedience,

            that we are all late
            in a slow time,
            that we grow up many
            And the single
            is not easily
            known


    It could be, though the sharpness (the achiote)
    I note in others,
    makes more sense
    than my own distances. The agilities


            they show daily
            who do the world’s
            businesses
            And who do nature’s
            as I have no sense
            I have done either


    I have made dialogues,
    have discussed ancient texts,
    have thrown what light I could, offered
    what pleasures
    doceat allows

            But the known?
    This, I have had to be given,
    a life, love, and from one man
    the world.
            Tokens.
            But sitting here
            I look out as a wind
            and water man, testing
            And missing
            some proof


    I know the quarters
    of the weather, where it comes from,
    where it goes. But the stem of me,
    this I took from their welcome,
    or their rejection, of me

            And my arrogance
            was neither diminished
            nor increased,
            by the communication

    2

    It is undone business
    I speak of, this morning,
    with the sea
    stretching out
    from my feet 

— SEE: [[ https://www.brainpickings.org/2012/12/27/charles-olson-reads-maximus-to-himself-1963/][Recording of Olson's reading poem in 1963]]
#+end_verse 

** Epigraph: Volume 1

#+begin_quote
1. warp and woof(Noun)

   The threads in a woven fabric, comprised of the warp
   (threads running lengthwise) and woof (threads running
   crosswise) to create the texture of the fabric.

2. warp and woof(Noun)

   The fundamental structure of any process or system.

— [[http://www.definitions.net/definition/warp%20and%20woof][warp and woof]] | definitions.net
— [[https://en.wiktionary.org/wiki/warp_and_woof][warp and woof]] | Wiktionary
#+end_quote



