#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Introduction Volume I
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Introduction Volume I Foundations
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-intro-vol-1.org
:Created:  2018-04-11T18:19@Prek Leap (11.642600N-104.919210W)
:ID:       bef42709-757a-4e2e-873c-41175c9c456a
:VER:      576717614.262601171
:GEO:      48P-491193-1287029-15
:BXID:     proj:DIM5-7235
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

The first volume lays out the broad foundation for the work,
what is civilization, how did it emerge, what forms has it
taken throughout history, what are the driving forces behind
it.  This lays the groundwork for understanding different
ways that civilization might work in a technologically
advanced post-scarcity future that we are starting to see
the beginnings of today which we will get into in detail in
Volume III.

*** 01. Civilis



*** 02. Ab Initio

Then what do we mean by first principles? In a word, it is
what Paul Graham called, when describing the design of the
programming laguage Arc, that theree would be "no onions in
the varnish":

#+begin_quote
In /The Periodic Table/,[fn:1] Primo Levi tells a story that
happened when he was working in a varnish factory. He was a
chemist, and he was fascinated by the fact that the varnish
recipe included a raw onion. What could it be for? No one
knew; it was just part of the recipe. So he investigated,
and eventually discovered that they had started throwing the
onion in years ago to test the temperature of the varnish:
if it was hot enough, the onion would fry.

We're going to try not to include any onions in Arc.

— [[http://www.paulgraham.com/arcll1.html][Arc at 3 Weeks]] | Paul Graham, 2001
#+end_quote

This is not meant to discard the past, as much as ensure
that what is included from the past is fully understood and
has a purpose that is no longer have any meaning or use.
We can accuse many things in traditional cultures of being
onions, and this has been used as an excuse to toss out
everything and begin clean, /tabla rasa/  This is not our
intention at all.  There are very good reasons for many
traditions and rituals that have been carried
down the centuries and millennia to the present.  Many of
these practices connect ground us in a shared cultural
narrative that grounds us, and connects us to the land and
to each other.  It's important that these things are not
lost.  However there are many onions that should be at least
understood if they are to be retained, and discard them if
they do more harm than good.

The practice in the sciences of starting from first
principles is that many times we are led down false paths
from the initial assumptions that they are based on.  For
this reason we must ensure that the civilization we build is
on a solid rational and empirical foundation.

#+begin_quote
A sound house needs a firm foundation, a good roof, and
tight walls.  No amount of rennovation will compensate for a
crumbling foundation.  It makes absolutely no sense to
remodel the interior of a house without first making sure
that the house stands on solid ground....

Structural work is the starting pint of a logical chain.
For example, changing the foundation will affect any work
done inside the house.  Wall finishes will crack, doors and
windows will stick or skew open, partitions and loors will
go out of level and plumb.  Also, structural work frequently
results in the exposure of the vitals of the house to the
elements....

[A] psychological factor... must never be underestimated. An
unwholesome amount of drudge labor and great sums of money
can be poured into a mud-filled fondation hole.  When the
job is finished and the hole is backfilled after weeks of
had work, nothing has visibly changed.  Of course you have
the satisfaction of knowing that at least your house will
stand safely and that whatever else you do rests on a firm
footing.  But it isn't /dramatic/ enough.

— Old Houses: A Rebuilder's Manual | George Nash
  cite:nash:1980old-houses p.24-25
#+end_quote

This is challange that Warp & Woof takes up, to have put in
the "drudge labor" needed to set things on a solid footing.
If at times as you labor through these seemingly
interminable six volumes that it will never end, imagine the
effort it took to put this together.  But just as you can't
rebuild an old house without replacing a rottom foundation,
we must take stock of our civilization an its foundations
and ensure that they are placed on a strong and durable
footing.

*** 03. Nature of Order

We will then explore what Christopher Alexander called, in
his monumental work, /The Nature of Order/ which at its
heart attempts to place the idea of /quality/, what
Alexander calls "quality without a name" (QWAN).  QWAN is no
less than an attempt to understand the fundemental nature of
self-organizing matter, which in it's electro-chemical form
we know as Life.  But biological life is only a subset of
the larger concept of life in the universe.  We are hard-wired,
to recognize living structures and see them as things of
transcendent beauty and spirit.  This is not mere
aesthetics, or decoration, or a veener that makes something
attractive.  It goes to the very bones of the nature of the
universe itself and is difficult to discuss or understand
without sounding spiritual, because it /is/ spiritual but it
is not subjective.  The beauty or living order that results
in organization that is larger than the sum of it's parts,
that can hold back the inexorible law of entropy should be
considered to be transcendent and spiritual.

*** 04. Estrangement

The problem is that since the development of spoken written
languages Sapiens have become increasingly estranged from the
world in which they belong.  This estrangement is a rift
which since 1800 is widening into a a canyon and threatens
to become a continental divide if we can not find a way of
healing this estrangement and creating societies and
buildings and modes of living in which we can feel
cormfortable and at home in again.  This is the foundation
work which will be the most difficult to do, but everything
depends on us getting this right.  And if we can get this
right, and mend the rift a lot of other things will fall
into place.


*** 05 Bondries

From here we can then begin to discuss the limitations of
Sapiens and of the greater Mankind.  There are no shortage
of planned utopian visions for the future of Mankind.  Most
are build on little more than cardboard foundations, or are
little more than flights of fancy.  As thought experiments
such uttopian visions are both useful and illustrative
tools.  But every so often some of these Utopian visions
have been taken quite literally to be built verbatim,
dogmatically constructing them according the letter of
whatever visionary scripture they were based on.  Most have
been religious, but some secular utopias which are one -ism
or another are often even worse.  In each case, the utopian
vision was not built on a solid foundation that made
allowances for and respected man's nature.  We are clever
apes, who in evolutionary terms have barely left the
savvanah from where we evolved and the ecological niche we
are designed to inhabit through blind evolutionary forces.
We are capable of being rational, but all too often are
not.  We have the capacity for great empathy, love and
compassion but easily give in to primal instincts based on
fear and threat through fight or flight.  We still are in
the very early stages of beginning to discover what we are,
our weaknesses and strengths, our bias's and cognitive and
phyisical limitations.  In short, we are very much a work in
process and are not capable of living in any Paradise or
Utopia no matter how pleasant -- we'll manage to screw it
up.  So we must constantly strive to understand ourselves
better, and to design social structures which take these
hard facts about ourselves into account and protect
ourselves from our less than noble natures.

*** 06. Principles

This brings us to the final part of the first volume which
explores the principles on which we can build societies and
a civilization for mankind that has a solid foundation that
gives us a place within a world that is both beautiful,
natural and fulfills that spiritual dimension of our ability
to see and understand patterns of living-order in the world
around us, that takes into account our strengths and
weaknesses and allows us to make progress and a better world
for ourselves and our children.

** Table of Contents
 - [[./ww-epigraph.org][Epigraph]]
 - [[./ww-intro.org][Introduction]]
 - 00. [[../wip/wip-plan.org][Plan of the Work]] - prolegomenon
 - 00. [[../wip/wip-ww-synopsis.org][Synopsis]]
 - 00. Contents Volume I
 - 00. [[./ww-intro-vol-1.org][Introduction]] Volume I
 - 01. [[./ww-civilization.org][Civilis]]
 - 02. [[./ww-ab-initio.org][Ab initio]] 
 - 03. [[./ww-order.org][Nature of Order]]
 - 04. [[./ww-estrangement.org][Estrangement]]
 - 05. [[./ww-boundries.org][Boundries]]
 - 06. [[./ww-principles.org][Principles]]


** References

  - Levi, P., The Periodic Table (1995), : Schocken.
    cite:levi:1995periodic-table
  - Nash, G., Old houses, a rebuilder's manual (1980), :
    Prentice Hall Direct. p.24-25
    cite:nash:1980old-houses 


* Footnotes

[fn:1] "I started to tell the story of the onion in the
boiled linseed oil. This, in fact, was a dining room for a
company of varnish manufacturers, and it is well known that
boiled linseed oil has for many centuries constituted the
fundamental raw material of our art. It is an ancient art
and therefore noble: its most remote testimony is in Genesis
6:14, where it is told how, in conformity with a precise
specification of the Almighty, Noah coated (probably with a
brush) the Ark’s interior and exterior with melted
pitch. But it is also a subtly fraudulent art, like that
which aims at concealing the substratum by conferring on it
the color and appearance of what it is not: from this point
of view it is related to cosmetics and adornment, which are
equally ambiguous and almost equally ancient arts (Isaiah
3:16). Given therefore its pluri-millenial origins, it is
not so strange that the trade of manufacturing varnishes
retains in its crannies (despite the innumerable
solicitations it modernly receives from kindred techniques)
rudiments of customs and procedures abandoned for a long
time now.  So, returning to boiled linseed oil, I told my
companions at table that in a prescription book published
about 1942 I had found the advice to introduce into the oil,
toward the end of the boiling, two slices of onion, without
any comment on the purpose of this curious additive. I had
spoken about it in 1949 with Signor Giacomasso Olindo, my
predecessor and teacher, who was then more than seventy and
had been making varnishes for fifty years, and he, smiling
benevolently behind his thick white mustache, had explained
to me that in actual fact, when he was young and boiled the
oil personally, thermometers had not yet come into use: one
judged the temperature of the batch by observing the smoke,
or spitting into it, or, more efficiently, immersing a slice
of onion in the oil on the point of a skewer; when the onion
began to fry, the boiling was finished.  Evidently, with the
passing of the years, what had been a crude measuring
operation had lost its significance and was transformed into
a mysterious and magical practice.

— Levi, P., The Periodic Table (1995), : Schocken.
  cite:levi:1995periodic-table

