#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   APPL Prototype Patterns Contents
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* APPL Prototype Patterns Contents
  :PROPERTIES:
  :CUSTOM_ID:
  :Name:      /home/deerpig/proj/chenla/warp/proto/index.org
  :Created:   2018-09-11T08:39@Prek Leap (11.642600N-104.919210W)
  :ID:        584e8cf7-98e2-446a-a4b0-b970969549c1
  :VER:       589902024.668915974
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:XEN1-1557
  :Class:     primer
  :Entity:    toc
  :Status:    wip 
  :Licence:   MIT/CC BY-SA 4.0
  :END:



  - Lifetime Pattern Language

    - General Character
    - Birth
    - Early Years
    - Childhood
    - Adolescence
    - Education/Apprenticeship
    - Journeyman
    - Marriage
    - Children
    - Master
    - Sabbatical
    - Second Master
    - Retirement
    - Final Years
    - Death


  - Education
    - Tree Planting Ceremony (hardwoods for when you become master)
      the trees planted will be harvested two generations later, the
      trees harvested when becoming a master were planted two years
      before.

    - Trivium
    - Laurea
    - Apprentice and complete Laurea
    - Join Domus Cluster -- Bamboo Planting Ceremony
    - Journeyman
    - Make starter House from bamboo
    - Join Shop
    
    - Leave Shop
    - Master
      harvest upgrade house and   




  - *Domus Cluster*
    - *General Character* a cluster of 12 houses with 3-5 primary
      shops which might be a storefront, a workshop, office, and 5 or
      more secondary shops that are run as seasonal and or part time
      work.  The cluster shares a common power grid, potable water,
      sewage and ideally a transportation pool.  Each cluster provides
      daycare and preschool for children (until the age of 11 when
      children begin taking the Trivium).

    - *Housing for Guests & Journeymen Vistors* Each cluster will
      provide journeyman apartments for outside staff, journeyman etc.

    - Each house is called a domus which is a multigenerationl so that
      any one domus might have any combination of children,
      adolescents, masters, retired/sabbatical and elderly
      individuals, couples and families.  Houses are designed to grow
      and adapt over time as different members of the house hold join,
      leave or raise children, or retire.

    - *Common Property* clusters consolidate tools and other things
      that are only used occasionally, so it will be common for a
      cluster to have a workshop, and food processing and preservation
      kitchen that anyone can use, a walk-in fridge for storing
      cluster produce and meat, drying, smoking and grain store -- a
      day care center, a community garden, perhaps even a swiming
      pool.  There will be areas that can be used for large events
      like weddings, funerals, holiday parties and for holding regular
      communal meals.  There will be cluster owned cooking equipment,
      a PA, Sound system, stage, plates, dishes, pots, pans, jumbo
      rice cookers etc.

    - *Cluster Forest* Each cluster will have a forest, with a mix of
      hardwoods and quick growing bamboo and pioneer spieces that will
      hold plantings for specific people in the cluster that mark
      birth, graduation from laurea, and death.  These trees and
      bamboo will act as sort of saving banks for everyone in the
      community.  For urban clusters, these food forests might be
      located outside the urban area, but also act as a retreat with a
      pond or lakefront housing to recompress from urban life and
      recharge.

    - *Sister Clusters* every rural cluster should have a sister
      cluster in an urban area and every rural cluster should have a
      sister cluster in an urban area.  Some people are content to
      live their entire lives in either an urban or rural environment,
      but mankind's earliest forms of civilization was a cross between
      sedentary and nomadic.  During certain seasons people forages,
      or managed flocks or hunted and then came together to form ad
      hoc settlements sometimes for brief periods, or perhaps a whole
      season.  Many of the problems of the sedentary life of the
      farmer or city dweller is that it cuts us off that we need to
      remain healthy, both psychologically, physically and socially.
      Isolation breeds ignorance and fear of outsiders.  Urban life is
      stressful and intensive, with too little contact with nature or
      space to relax, think and play.  A combination of both is
      important for all people.  This pattern should provide the
      ability for rural people to become metropolitan and ideally
      cosmopolitan and for metropolitan people keep grounded and feel
      their connectedness with the world outside of the things of man
      -- the immensity of the land the sky and the stars.  This
      pattern is one possible solution to the town-gown problem.
      
