#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XVI. Branches Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] [[[./index.org][up]]]

* XVI. Branches Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/16/intro.org
:Created:  2018-04-30T21:55@Prek Leap (11.642600N-104.919210W)
:ID:       7e6907b1-4665-42c6-8e7b-7c34fa1f6e66
:VER:      578372195.868142072
:GEO:      48P-491193-1287029-15
:BXID:     proj:KJV2-1414
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

A Civilization is not a state, though at several times in
history the distinction has gotten blurry.

Civilization is a system that emerges when a complexity
threshold that is a mixture of population, culture,
commerce, and technology has been reached.  Civilizations
have no governance, no monuments, no leaders, they have
gods, and heroes and narratives.

Culture is at bottom, holding the narrative threads like
reins on a team of horses, pulling back here and letting out
there to keep everyone pulling as one.  You can no more
overthrow a civilization than you can tame a sea.  The
nations and states that make up civilization blaze brightly
for a while, then flicker and go dark with civilization
hardly taking notice.  Civilization works at timescales slow
enough that they will eventually be seen by the even slower
evolutionary processes that govern life, if only it can
survive long enough.  With only ten thousand years under its
belt civilization is still an infant.  Evolution will take
notice in another ten or twenty thousand years when we've
been around long enough to begin our adolescence.  It might
take hundreds of thousands of years more before we enter early
adulthood.

After the two World Wars cleared the last vestiages of
pre-industrial power stuctures, the basic building block has
been the nation state, fusing national cultural identity
with state institutions and power structures backed up by
guns.  The territories each nation-state controls have
become sacrosanct, the sovereignty claimed in the name of
the nation (not the state) is coached in secularized terms
that echo the claims of earlier monarchs claiming their
their power was sanctioned by God.

It's all a social construct, a story we tell to each other
so we as a species can cooperate with each other.  No where
is this more clear than in the image made of the Earth on
the 7th of December 1972 by the crew of Apollo 17.  For the
first time in Mankind's history, the whole of the planet was
taken into one frame of reference, a beautiful blue marble,
basking in the sunlight in the black emptiness of space.  In
that image there are no state borders, no nations, no racial
demarcations or ideologies.  There is only the blue water,
the white clouds and polar ice, the brown deserts and the
green forests and grasslands.

I say all of this to remind myself of the magnitude of what
I am about to propose.  That the only way our speices and
civilization is to survive and flourish will be to take the
reins of civilization and lay down more imaginary lines on
our fragile blue marble.

With every year all of the key control points of
Nation-States, save one is fading, transporation, knowledge,
communication and commerce increasingly ignore borders,
leaving behind only territorial borders and guns (lots and
lots of guns), like the smile of the Cheshire Cat.

The old stories that built an industrialized world are being
forgotten, to be replaced by new stories.  It may not feel
like this has happened and that the nation-state is still in
firm control of the reins but this is only because
governance and culture are on slower pace layers and haven't
yet caught up with Infrastructure, Commerce and Fashion.
The cracks in governance and culture are already starting,
and in some places have grown to become fissures, in others
they will remain little more than hairline cracks easily
overlooked and ignored for decades to come.

As the nation-state fades, its place in the human ecosystem
will need to be filled.

The longer have considered these thing the more I am
inclined to think that a world order is nearly apon us,
though we can't yet see it's final shape or form.  I don't
think that we have reached an inevitibility threshold but we
are very close.

We need to understand what as the nation-state erodes, some
of it's functions are being displaced, such as
transporation, international commerce, the flow of
information as communications, news and knowledge and the
flow of wealth as currency, resources, energy and goods.

As mentioned the one thing that nation-states still have
control over is physical borders of the territories they
control.  But the also control large parts of public
infrastructure and national and local governance.

The dichotomy of human activity into public and private
spheres are built on top of common definition of property is
becoming increasingly dysfunctional. The concept of
property, commons, and separation of public and private
sectors needs to be rethought.

The old concept of the Commons as sort of possitive-sum DMZ
is under increasing assult from both public and private
spheres both idea and practice is where I think what needs
to be addressed.

The biggest challenge will be to decentralize both public
and private spheres and move power from the center to the
edges.  This will ensure that distribution of resources and
wealth better meets the majority of people's needs.  It will
also make our overall civilization more resiliant and
flexible when dealing with catastrophes.

This is best done if we can merge public and private
together into a scalable decentralized framework.  No,
this is not the public sphere nationalizing the private or
the private sphere privitizing the public.  Both of those
approaches have been tried and both have failed in
spectacular fashion.  Rather I see the concept of a
corporate body that has a dual nature that can be seen as
public in one context and private in another as a viable
alternative to the present system.  For this to work we need
to rethink the underlying system where nearly everything is
treated as Property, and an ever shrinking Commons.

I would argue that private property can not exist unless
there is a functional Commons acting as a counter weight.

The commons is not simply a community owned form of
property.  The Commons is not a subset of Property.  It is
in a different category all together.

But to understand why this is true we must first understand
what property really is.  The concept of property evolved
from the concept of an individual's personal possessions,
the cloths on your back, and the tools in one's bag.  The
Inuit buried their dead with their personal tools so that in
the afterlife they would be able to hunt and fish.  This
belief has been expressed in one way or another in most if
not all cultures through history.  The greate dynastic
Chinese emperors being buried with entire terracotta armies,
tools and livestock.  The Egyptian King's tombs contain a
treasure trove of everything the King would need in the
afterlife. 

But in each case, these things were possessions -- it was
only later as man became increasingly sedantary that the
concept of posessions became enshrined as property, because
agricultural land had to be divided into plots and
cultivated and the wealth produced by those plots became
property as well.  At that time all wealth was physical, and
was protected by threat of physical force.  Over time, as
societies became increasingly complex, wealth became
increasingly symbolic with currencies using precious metals
used as a means of storing wealth and as a intermediate step
in trading.  So that direct barter trade of goods was
replaced with exchange of goods and services for currency
which could then be used anywhere to obtain anything.

By the end of the twentieth century, wealth had made the
transition from being symbolic to being pure information.
This was followed by the digitalization of all types of
information which had previously been stored on physical
media which could be copied and sold as a kind of property.
When the Internet crossed its own critical threshold in the
last ten years of the 20th century, the process of
converting all information into formats that could be
represented as binary digital data went into high gear.
Some thirty years later that process is largely complete.
But this displaced the value of information as a form of
physical property that could be bought and sold.  Copyright
law, which had been created to control the creation of
physical artifacts that contained copies of recorded
information tried to jettison the physical media and place
ownership on the disembodied information that had been
encoded on it.  This has not worked very well because
information and knowledge is not a possession, you possess
what is in your hand and that can be taken away from you.  

The knowledge in your head is not a possession it is, in
effect part of you.  When you pass on that knowledge to
someone else you still have that same knowledge in your
head.  And where did that knowledge come from?  Everywhere,
from the winter winds, to the crunching sweetness of the
first Autumn apples, to the first time you learned to write
your name, ride a bicycle, or swim across a pond.  The song
you hum to yourself on the train on the commute to work is
not property, it has been woven into becoming what you are.
It can not be owned.

As Issac Newton famously said, "if I have seen farther, it
is because I have stood on the shoulders of giants."  Until
the nineteenth century most knowledge was thought of as
being a part of our culture.  In that sense, the
historically recent term, "intellectual property" is not
only ludicrious but obscene.  Since the sixteenth century
man has moved away from the concept of humans as groups made
up of individuals to individuals who belong to different
groups.  We have fractured into a world of more than seven
billion sovereign monarchs of our personal kingdoms.  A few
percent of those kingdoms contain 80% of all the property
and wealth and the rest get by they best they can on the
margins.

The Commons is not owned.  It belongs to everyone, because
everyone past and present, the dead and the living, have
incrementally contributed to them.  Every life, every hour
of toil and suffering, every innovation be it the spoken and
written languages that we use to communicate, a joke told at
the local pub, an incremental improvement of a tool that has
been in use long before the cultural revolution.  Something
as simple as a spade is expressed today by monster
industrial scale earth moving machines.  Those machines are
made up of parts that are based on other parts and ideas and
discoveries that date back to Man's earliest existence and
would not exist or could never be built without all the
efforts of countless people over thousands of generations
that came before.  No one owns these things, they are not
and can not be considered property.

** References
