#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XVI. Branches Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] [[[./index.org][up]]]

* XVI. Branches Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/16/intro.org
:Created:  2018-04-30T21:55@Prek Leap (11.642600N-104.919210W)
:ID:       7e6907b1-4665-42c6-8e7b-7c34fa1f6e66
:VER:      578372195.868142072
:GEO:      48P-491193-1287029-15
:BXID:     proj:KJV2-1414
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

A Civilization is not a state, though at several times in
history the distinction has gotten blurry.

Civilization is a system that emerges when a complexity
threshold is crossed that is a mixture of population,
culture, commerce, and technology has been reached.
Civilizations have no governance, no monuments, no leaders.
They have their gods, heroes and narratives that provide
context, locality and meaning.  Everyone has their own gods
and as Drumbledore said, “of course it is happening inside
your head... but why on earth should that mean that it
is not real?”

Culture is at bottom, holding the narrative threads like
reins on a team of horses, pulling back here and letting out
there to keep everyone pulling as one.  You can no more
overthrow a civilization than you can tame a sea.  The
nations and states that make up civilization blaze brightly
for a while, then flicker and go dark with civilization
hardly taking notice.  Civilization works at timescales slow
enough that they will eventually be seen by the even slower
evolutionary processes that govern life, if only it can
survive long enough.  With only ten thousand years under its
belt civilization is still an infant.  Evolution will take
notice in another ten or twenty thousand years when we've
been around long enough to begin our adolescence.  It might
take hundreds of thousands of years more before we enter early
adulthood.

After the two World Wars cleared the last vestiages of
pre-industrial power stuctures, the basic building block has
been the nation state, fusing national cultural identity
with state institutions and power structures backed up by
guns.  The territories each nation-state controls have
become sacrosanct, the sovereignty claimed in the name of
the nation (not the state) is coached in secularized terms
that echo the claims of earlier monarchs claiming their
their power was sanctioned by God.

It's all a social construct, a story we tell to each other
so we as a species can cooperate with each other.  No where
is this more clear than in the image made of the Earth on
the 7th of December 1972 by the crew of Apollo 17.  For the
first time in Mankind's history, the whole of the planet was
taken into one frame of reference, a beautiful blue marble,
basking in the sunlight in the black emptiness of space.  In
that image there are no state borders, no nations, no racial
demarcations or ideologies.  There is only the blue water,
the white clouds and polar ice, the brown deserts and the
green forests and grasslands.

I say all of this to remind myself of the magnitude of what
I am about to propose.  That the only way our speices and
civilization is to survive and flourish will be to take the
reins of civilization and lay down more imaginary lines on
our fragile blue marble.

With every year all of the key control points of
Nation-States, save one is fading, transporation, knowledge,
communication and commerce increasingly ignore borders,
leaving behind only territorial borders and guns (lots and
lots of guns), like the smile of the Cheshire Cat.

The old stories that built an industrialized world are being
forgotten, to be replaced by new stories.  It may not feel
like this has happened and that the nation-state is still in
firm control of the reins but this is only because
governance and culture are on slower pace layers and haven't
yet caught up with Infrastructure, Commerce and Fashion.
The cracks in governance and culture are already starting,
and in some places have grown to become fissures, in others
they will remain little more than hairline cracks easily
overlooked and ignored for decades to come.

As the nation-state fades, its place in the human ecosystem
will need to be filled.

The longer have considered these thing the more I am
inclined to think that a world order is nearly apon us,
though we can't yet see it's final shape or form.  I don't
think that we have reached an inevitibility threshold but we
are very close.

We need to understand what as the nation-state erodes, some
of it's functions are being displaced, such as
transporation, international commerce, the flow of
information as communications, news and knowledge and the
flow of wealth as currency, resources, energy and goods.

As mentioned the one thing that nation-states still have
control over is physical borders of the territories they
control.  But the also control large parts of public
infrastructure and national and local governance.

The dichotomy of human activity into public and private
spheres are built on top of common definition of property is
becoming increasingly dysfunctional. The concept of
property, commons, and separation of public and private
sectors needs to be rethought.

The old concept of the Commons as sort of possitive-sum DMZ
is under increasing assult from both public and private
spheres both idea and practice is where I think what needs
to be addressed.

The biggest challenge will be to decentralize both public
and private spheres and move power from the center to the
edges.  This will ensure that distribution of resources and
wealth better meets the majority of people's needs.  It will
also make our overall civilization more resiliant and
flexible when dealing with catastrophes.

This is best done if we can merge public and private
together into a scalable decentralized framework.  No,
this is not the public sphere nationalizing the private or
the private sphere privitizing the public.  Both of those
approaches have been tried and both have failed in
spectacular fashion.  Rather I see the concept of a
corporate body that has a dual nature that can be seen as
public in one context and private in another as a viable
alternative to the present system.  For this to work we need
to rethink the underlying system where nearly everything is
treated as Property, and an ever shrinking Commons.

We will call these dual-nature corporate entities /Shops/,
as in a workshop, or a shop where things are placed on
display for sale.  So a shop can be any combination of
workspace, place of production, or retail sales.  People
ususally think of a shop as being smaller as a store.  The
term big-box store, a cavernous building with very high
ceilings to create a single large room for selling
mass-produced goods.  But the word shop invokes images of
sunny corner bakeries infused with the smell of fresh-baked
bread, deli's selling long strings of dark red sausages and
a long list of sandwhiches, and tea shops with walls lined
high with ancient wooden drawers, labeled with cryptic
chinese characters holding all manne of exotic teas from
distant shores.  Shops are human scale that are part of a
community.  You've probabaly known the shop keeper since you
were a child and they know you.  Contrast this with the
modern chain-store, which are all identical copies of each
other, with bored teens wearing uniforms manning the
counters and cash registers. 

I would argue that private property can not exist unless
there is a functional Commons acting as a counter weight.

The commons is not simply a community owned form of
property.  The Commons is not a subset of Property.  It is
in a different category all together.

But to understand why this is true we must first understand
what property really is.  The concept of property evolved
from the concept of an individual's personal possessions,
the cloths on your back, and the tools in one's bag.  The
Inuit buried their dead with their personal tools so that in
the afterlife they would be able to hunt and fish.  This
belief has been expressed in one way or another in most if
not all cultures through history.  The greate dynastic
Chinese emperors being buried with entire terracotta armies,
tools and livestock.  The Egyptian King's tombs contain a
treasure trove of everything the King would need in the
afterlife. 

But in each case, these things were possessions -- it was
only later as man became increasingly sedantary that the
concept of posessions became enshrined as property, because
agricultural land had to be divided into plots and
cultivated and the wealth produced by those plots became
property as well.  At that time all wealth was physical, and
was protected by threat of physical force.  Over time, as
societies became increasingly complex, wealth became
increasingly symbolic with currencies using precious metals
used as a means of storing wealth and as a intermediate step
in trading.  So that direct barter trade of goods was
replaced with exchange of goods and services for currency
which could then be used anywhere to obtain anything.

By the end of the twentieth century, wealth had made the
transition from being symbolic to being pure information.
This was followed by the digitalization of all types of
information which had previously been stored on physical
media which could be copied and sold as a kind of property.
When the Internet crossed its own critical threshold in the
last ten years of the 20th century, the process of
converting all information into formats that could be
represented as binary digital data went into high gear.
Some thirty years later that process is largely complete.
But this displaced the value of information as a form of
physical property that could be bought and sold.  Copyright
law, which had been created to control the creation of
physical artifacts that contained copies of recorded
information tried to jettison the physical media and place
ownership on the disembodied information that had been
encoded on it.  This has not worked very well because
information and knowledge is not a possession, you possess
what is in your hand and that can be taken away from you.  

The knowledge in your head is not a possession it is, in
effect part of you.  When you pass on that knowledge to
someone else you still have that same knowledge in your
head.  And where did that knowledge come from?  Everywhere,
from the winter winds, to the crunching sweetness of the
first Autumn apples, to the first time you learned to write
your name, ride a bicycle, or swim across a pond.  The song
you hum to yourself on the train on the commute to work is
not property, it has been woven into becoming what you are.
It can not be owned.

As Issac Newton famously said, "if I have seen farther, it
is because I have stood on the shoulders of giants."  Until
the nineteenth century most knowledge was thought of as
being a part of our culture.  In that sense, the
historically recent term, "intellectual property" is not
only ludicrious but obscene.  Since the sixteenth century
man has moved away from the concept of humans as groups made
up of individuals to individuals who belong to different
groups.  We have fractured into a world of more than seven
billion sovereign monarchs of our personal kingdoms.  A few
percent of those kingdoms contain 80% of all the property
and wealth and the rest get by they best they can on the
margins.

The Commons is not owned.  It belongs to everyone, because
everyone past and present, the dead and the living, have
incrementally contributed to them.  Every life, every hour
of toil and suffering, every innovation be it the spoken and
written languages that we use to communicate, a joke told at
the local pub, an incremental improvement of a tool that has
been in use long before the cultural revolution.  Something
as simple as a spade is expressed today by monster
industrial scale earth moving machines.  Those machines are
made up of parts that are based on other parts and ideas and
discoveries that date back to Man's earliest existence and
would not exist or could never be built without all the
efforts of countless people over thousands of generations
that came before.  No one owns these things, they are not
and can not be considered property.

Wealth was one of the the first things to become symbolic,
and then pure information.  But now that all information has
been digitized and transmitted using a positive-sum
mechanism, information has become the most flexible and
powerful form of wealth and that all forms of physical
wealth are expressions of information.  As the physicist
John Weaver said, the entire universe is an expression and
actualization of information, literally it from bit.

Our present everything-is-property model is based on an
increasingly outmoded concept of all property being
physical.  Information has been freed from the physical
media that it was encoded on and is not longer property.

But if everything is information, and even the physical
world is simply a way of compiling information into matter
then the old property model is no longer a viable means of
measuring and distributing wealth as goods and services.

The solution is to return variation of the ancient concept
of the division of possessions and knowledge.  With
knowledge being the most important and embodied in the
concept of the Commons.  Property then needs to be demoted
somewhat and become something closer to what our distant
ancestors would be considered as personal property.

So we can now start to put this all together, with a new
concept of a civilization that is made up of distributed
human-scale corporate bodies, where each corporate body has
a dual public-private nature and that this is built on top
of the expression of knowledge as being a part of the
Commons with material goods being possessions, not
accumulated material weatlh.

This concept is neither capitalist nor communist and in a
post-scarcity world domainated by disembodied information
that is largely an extension of mind, but incresingly
externalized cognitive processes that can autonomously
control machines to produce material goods and services.

Second, in many respects, things will go on as they do
today, people will continue to live much as they always have
when they have a relatively high standard of living, freedom
and safety.  People are largely okay with the structure of
daily life, so long as they have the resources to have a
good life.  There will still be markets, schools, companies,
jobs (for those who want them) and money, but underneath the
surface things will be substantially different.

Third, this is no Utopia that we are envisioning.  Life
always has been and always will be a messy affair and
nothing a bunch of clever hairless apes do are going to
change that.  The system is designed to make allowances for
human nature, our cognitive limitations and biases.  What
makes us human also ensures that we will always screw things
up, no matter how good things are, and there will always be
a restless few who can't or won't be able to accept living
in the system staying in or leaving is an option which the
system must not only allow but respect and aide in any way
we can, so long as what they want does not violate the
welfare, freedom and safety of others.

But we're still missing a few important pieces of the larger
puzzle.  Civilization requires a significant amount of
things that can not be done at human-scales.  These are
critical functions that the present system provides
that the system I have so far outlined can't provide.  

We need a common meta-origin story which any local culture
can map their cultural mythos onto.  That meta-origin story
then becomes the foundation for a universal set of humanist
principles which ensure that everyone is treated fairly.
This only works if everyone places by the same rules and
those rules are apply to and are applied fairly to everyone
in the same manner.

We still need a means of coordinating propagation of
information and the coordination of large numbers of small
public-private corporate bodies to be able to come together
in an adhocracy to achieve goals that can only be done today
at scale using large centralized infrastructure.

And we need a means of creating negative feedback loops that
ensure that the system doesn't drift and change into
something that does not adhere to the core humanist
principles that ensures that we are living in a positive-sum
civilization of all humanity, and not revert back into an
atomized mob of personal kingdoms.

To provide this, I propose establishing, for want of a
better term, branches of civilization that provide these
functions for all of Mankind.

These are somewhat similar to the different branches of a
government which are meant to a) gain consensus, b) provide
direction, and c) maintain the system and make corrections
to keep it on course.

Today those three branches are typically, executive,
legislative and judical.  Each branch is designed to be
independent of the other branches and whose job is to
provide negative feedback mechanisms that keep the other
branches in check.

Our system will use these same concepts but in a different
configuration that reflects the system that they are
managing that is made up of human-scale public-private
corporate bodies built on a concept of a Commons with
personal possessions.

Before we introduce the three branches it needs to be clear
that these are no branches in same sense as today's
government branches, this is no bureaucracy or president or
legislative bodies.  These branches are distributed, and are
part of the public nature side of every corporate body,
which in aggreagte functions as if they were government
branches, but only manifest these functions physically as
ad-hoc processes that self-destruct, or rather, disband
themselves when a process has been completed.

These branches are not owned or controlled by anyone, but
are directed and mantained by everyone as part of day to day
life.  The branches emerge from the running kernal that has
been compiles from source code built on patterns which are
based on universally agreed apon first principles.

We call these branches (with a tip of the hat to Ian Banks),
Middle, Scope and Culture.

First, the three branches operate at different rates of
change, with Middle being the largest and fastest changing
and Culture being the slowest but most powerful.  The slower
layers act as guidance and provide limits on the faster
layers.

Second, each branch is independent of the others, and have
some authority to force the other branches to make
corrections when necessary.

Third, branches propagate at different speeds and adapt
locally.  Fuck ACID, that's not how things work, different
things change at different speeds, and only when they are
ready in their own good time.  We must reject the tyranny of
the instant, the immediate, and return to the expectation
that the world is neither uniform nor retrograde.  We need
to remember how to live in a spectrum of different presents,
each with its own character and state.  This gives us a
stability that we have nearly lost.  We need to remember
that that the the present is a spectrum rather than an
absolute.  This provides space for people to adapt and much
needed continuity especially between generations.  But just
as important, it slows us down and reminds us that we all
live in a present which is different in different places.

*** Sketching out the system

The atomic unit of Middle is the /shop/ and /domus/ which
belong to a /polis/ and or /nomes/ that ideally encpmpasses
a bioregion.  Each shop and domus is a corporate entity that
has a dual public/private nature.  Middle links shops and
domus' to form adhoc processes that are sometimes public in
nature and other times private in nature.  The majority of
an individual's wealth is held as equity in shops and domus'
that they belong to.  In the same way each shop and domus
has an equity stake in the /polis/ and or /nomes/ that they
are members of.  A nomes is basically the bioregion that a
polis is located in and provides the same services and
protection of rights, equity and possessions for the their
citizens.  Many polis will predominately belong to a larger
cultural and ethnic nation.  Nations may or may not be
organized and have networks of their own, but they will not
be States in the same way that Nation-States are today.
Ideally, no Nation would be a state or control a territory.
Separation of nation and governance ensures that no one
nation can impose itself on another and place a check on
less desireable aspects and manifestion of human tribal
instincts.  The modern concept of politics will be replaced
with distributed semi-automated governance where most
bureaucracy will be handled using a trustless consensus
mechanism by Middle.  Leadership will become another form of
ad hoc process that will be assembled for a specific purpose
and then disbanded when finished.  Leadership will no longer
be a full time job and a means of consolidating social power
and wealth in a small elite.  There will be many shops who
will specialize in providing public services that today are
provided by governments.  But even those shops will also
have a private nature as well, and might take on public jobs
one week, and consulting work the next.  The system is
designed to be democratic but in most cases, people will not
be formally voting for leaders or laws or inititatives but
instead patterns of people's wants and needs that are
captured in what Google recently called the selfish-Ledger
which are expressed in their daily lives will be used to
establish overall consensus and to guide public services to
meet those needs and express consensus views.

Is such a system actually feasible or even possible?  Not
yet, but soon.  It's important to understand that this is
not a kitchen table startup that will be launched as a
complete soup-to-nuts solution on day one.  

Rather it is an initial vision of what such a system could
look like but will radically evolve over time as we find
what works and what doesn't.  This is not not a race, or
even a marathon, but a life-long journey towards an unknown
destination.

At first different components of the system will be launched
as network services that overlap and overlay existing
political and economic systems.  As more and more pieces of
the system come on line they may displace and retire
existing systems when the time is right and it makes sense
to all those effected.  This will take a long time,
generations, in fact.  Small pockets will emerge that make
full use of the system to run their own company, or a
village co-op or perhaps a housing development.  But for
most people ad hoc processes will simply be one more revenue
stream for a company, or a management system for a
government agency or department.  

Students will join the network as part of a life-long
learning program and use the personal information framework
to form ad hoc social media groups, organize events and
eventually after graduation to use their own personal
knowledge workshop as Engelbart called it, as both their
resume and portfolio but also as an extension and
externalization of their own knowledge and skills in the
workplace.

So, keeping in mind that this is not so much a design, or
even a proposal, but a thought experiment and vision of how
such a system might work in practice.

*** Citizen

We start with the concept of person as citizen.  This
concept of citizen differs somewhat from the most common
concept of nation-state citizenship.  First, citizenship is
choice, not a birth right.  People have birth-rights and an
equity position in the domus and polis they are born into
which is held in trust until they come of age and choose to
become a citizen, or to trade their equity with another
domus and polis to become a citizen there.  This makes it
easier for people to live and work where they are most
comfortable, which may or may not be where they were born,
and which will likely change several times at different
stages of their lives.

Citizens have rights and duties to the shops, domus and
polis they belong to.  The most important duty is to master
information literacy and the cognitive tools they will need
to take part in a community.  There is no one-size fits all
here, everyone takes part in different ways at different
times in their lives.  At some stages a citizen might take a
very active part in the community and at other times to
largely disengage and seek solitude.  So long as they have
mastered information literacy and can make rational
descisions based on creditble evidence they are free to lead
the life they choose.

*** Domus

A domus is a group of households that share facilities,
ownership of the property where it is located, which is an
independent coporate semi-autonomous entity in which members
have an equity holding.  There will be any number of
different ways to /buy-in/ and join a domus, but in all
cases there must be a majority consensus of other members to
join.  Sometimes joining will be through marriage, birth,
adoption or by moving into a new polis/nomes.  When you
leave a domus to join another, equity is swapped between the
two domus which will be managed by Middle.  This will be a
difficult thing to develop because there will be some domus
which are richer and others poorer, and different people
will have built up different equity stakes over their
lives.

*** Shop

Many if not most shops will be owned by the domus it is
located in.  Citizens will hold equity stakes in the shops
they work in.  Shops are not allowed to have members that
exceed Dunbar's number.  But it's expected that when the
majority of work is automated, that an ad-hoc process
economy will give more advantage to smaller shops than
large.

It is hoped that when-ever possible that shops are
integrated with domus at many different levels.

Shops are very flexible in their structure.  And we envision
that there will be part-time shops which only operate at
specific times of the day, or even only during certain
seasons and then shut down the rest of the time.  Other
shops will be full time, permanent operations.  This will
make it easier for people to join and work in shops that fit
their stage of life.  Some people may prefer to only work in
part-time shops when their children are still small.  Others
may spread their time across several part-time shops.  Or as
part-time members of full-time shops.  It is desirable to
mix domus and shops as much as possible to make it easier
for children to participate in adult activities.  Children
need to be integrated into daily life, not sequestered
during working hours as a kind of day-care.  Day-care is
needed for the care of young children while parents work
nearby, but as soon as children reach a certain age they
should be able to particiapte in the workplace.  This is
not child labor, it is part of their education, helping in
shops is a way for them to apply what they learn in their
studies and prepare them for their transition into
adulthood.  This is a far better and more constructive use
of their time than to fill all their time outside of studies
with largely pointless invented scheduled activities. If a
child wishes to learn to play a musical instrument or join a
sports team or some other activity that needs to be
encouraged.  But participating in their parents workplace is
equally important.  The primary purpose of traditional
classrooms is not education but conditioning children to
learn self-discipline, stay in one place and do what your
are told, especially if what you are told to do is the same
thing over and over and over.  These are stills for factory
assembly lines.  Those skills will not be needed in a
post-scarcity civilization where most industrial processes
have been automated.  The skills that will be needed are
literacy in written languages, numeracy and the ability to
work with numbers and symbol systems, programcy (is that a
word?  it is now) and the ability to write code that
automates tasks and can be executed by machines.  This makes
it possible for people to control and customize the
computational environment they live in, not just learn how
to use point-and-grunt interfaces.  Everything around you
should be customizable at the deepest level unless there is
a very good reason not to.  And finally students need
information literacy, the skills to find and evaluate
information logically and rationally.  Children need places
where practice is not an abstract exercise in a lesson, but
contributes something to their family and the shops they
work in and to society at large.

Middle will help shops connect to customers and to join
ad-hoc processes and manage the processes chains and
transations so that each shop can concentrate on spending
most of their time doing what they were established to do,
rather than have lage numbers of members in executive,
administrative, marketing or sale roles.

*** Polis

We can divide settlements roughly into the rural
village/hamlets surrounding towns and the urban which are
large metropolitan cities.

Large metropolitan areas don't have to be monolithic
top-down systems.  They can be divided into adjoining
semi-autonomous neighborhoods each with their own culture,
character and a large degree of self-determination. A group
of such neighborhoods constitute a burrough-polis, which is
an autonomous polis that has no surrounding nomes.

A special type of neighborhood will be controlled by Culture
and managemed by Middle that is set aside as a downtown
which contains public facilities for events, and instutional
structures such as libraries, museums, hotels, concert halls
and structural infrastructure for ad-hoc governments to be
assembled that can accomidate a large number of people to
come together for short periods of time to accomplish
something before disbanding.

A nomes-polis is a bioregion with a large town or small city
at it's center with the areas outside the city made up of a
patchwork of villages or hamlets that in turn are made up of a
number of different domus.

*** Nomes

As mentioned, a nomes is the territory surrounding a polis,
which we define as a bioregion.  This is a natural way of
dividing things as lifestyle, culture, language, dress and
our relationship to natural environment is shaped by
climate, and the flora and fauna in the ecosystem that we
live in.  Since a bioregion shares the same climate and
ecosystem is can be taken as a unit that we have to live
within and take actions to protect and manage.  The
bio-region we live in forms an important part of our
personal identity.  If a polis-nomis is a smaller unit than
a bioregion, then more than one polis will be responsible
for resources that are shared between different political
entities, so decisions made by one polis that effect another
polis must be made by consent of both polis-nomes this is
certainly possible but not desirable and takes away some of
the autonomy of the polis.  This is important if we are to
keep things at human scales.

#+begin_quote
A bioregional association is an association of the residents
of a natural and identifiable region.  This region is
sometimes defined as a watershed, sometimes by remnant or
existing tribal language boundries, at time by town
boundries, suburban streets, or districts and at times by
some combination of the above factors.  Many people identify
with their local region or neighbourhood and know its
boundries.

There is no obvious conflict between the need to live in a
region in a responsible ay (beoregional centrality) and the
need to integrate with other people in other places (global
outreach).  We need not only to "think globally and act
locally", but to "act and things globally and locally".

The region is our ome address, the place where we develop
our culture, and take part in bioregional networks.  Through
global associations and "families of common interest" we
cross not only the regional but also state and national
borders to set up multicultural alliances.

Just as bioregions need a federal congress periodically, so
do they occasionally need global congresses; socieities or
families also need global meetings to break down the idea of
defended regional boundries to humanity.  Ethis and
principles of self-goverance, interdependence, and voluntary
simplicity or restriction of human numbers on earth still
apply at regional and outreach levels.  Intermarriage,
visits, mutual trade and aid, skills exchange, and
educational exchange between regions of very different
cultures enriches both.  This is the antithesis of
"integration" (bureaucratic genocide) that is promulgated by
majority groups who disallow language use and cultural life
to minorities.  In particular, reciprocal education calues
/both/ sets of knowledge and world concepts, and respects
other's lifestyles.

Tribal maps often defined bioregions very well; totems and
"skins" (clan groups) of tribes might take, as their totemic
mothers, a particular tree or animal, which itself was
limited in distribution by the sum of topographic and
climatic factors.  Other groups occupoed ecologies of
grasslands, stony deserts, swamps, or mountain ridges.
Today, minority language groups (Saamen, Basque,
Pitjatjantjara) claim territories that are ancient, and
specific to their life mode.  Obviously, cites break up into
different, often occupational or income, districts, each
with it's own dialect and ecology, consumption spectrum, and
morality.  The acid test of a bioregion is that it is
recognized as such by its inhabitants.

— Bill Mollison, Permaculture Designers Manual (1988)
cite:mollison:1988designers, [[pdfview:~/proj/chenla/hoard/lib/mollison:1988designers.pdf::546][p.510]]
#+end_quote

*** Tribes

In my earlier outline I had not included tribes, as in this
system they are just another type of corporate body.  But
they aren't /just/ another corporate body, they represent
something very deeply ingrained in humans and are an
important cultural unit.

There is nothing wrong with tribes as being cultural units,
but something goes a bit wonky when you also make them a
state.  Look at the Jews, a highly successful cosmopolitan
diaspora that has survived intact around the world, but once
they established a nation state it didn't work out very
well.  In 1993 Joel Kotkin wrote:

#+begin_quote
More disturbing, with the recovery of the historic homeland
in Palestine, some Jews have reverted to a racially tinged
kind of tribalism.  At times the advocates of such measures
as the "removal" of Arabs from the West Bank, or even
pre-1967 Isreal reintroduce the most brutish aspects of the
biblical conquest of Palestine under Joshua.  Religious
fundementalism, hostility to outsiders and racism within
contemporary Israel represent the dark obverse of the
cosmopolitanism characteristic of the diaspora; unchecked,
they could lead not only to the continued cycle of endless
war, but will impair the Jewish experence as a cosmopolitan
global Tribe.

—  Joel Kotkin, Tribes
   cite:kotkin:1993tribes
#+end_quote

As I write this in 2018, Kotkin's prediction is still
as true now was it was in 1993.  This is not meant to single
out the Jews, it seems to be true for a number of different
Nations who have done very well as a cosmopolitan diaspora
but not very good as a nation state.  It appears that this
is, in part a scaling issue, but it's also a sedantary
issue.  Tribes work well at certain scales, and when broken
into a diaspora they function better than they do back home.
Stateless nations pine aways for a return of or creation of
a homeland.  In a world that is dominated by the
nation-state system this is not an unreasonable wish, as
many stateless nations are treated abysmally and often face
hostility and repression that spills into genocide.

But if the nation-state system was replaced with a
stateless system where all nations are a kind of diaspora,
and safe from persecution and free to live their lives as
they wish we all might get along a lot better.
Nation-states reinforce tribal nationalism which is brings
out the worst in our species.  In many respects this is
the single biggest drawback to the nation-state system
which in many other respects has been a great success.  

The second biggest drawback of nation-state system is that
territories have become frozen, which blocks natural
migration of people over time during economic downturns,
drought, disease, famine and war.  Nation-states are making
immigration increasingly difficult, and this as resulted in
tremendous pressure being placed on them from other parts of
the world where populations know they have to leave in order
to survive.  But increasingly there is no where for people
to go.  Before WWII it was relatively easy to travel
internationally without a passport. States are now national
monocultures, which increasingly look inward, and see those
outside as /the other/.  When people from these same
cultures live in a cosmopolitan environment where everyone
is safe, and everyone is safe and free to live according to
their cultural traditions, people get along, or at least are
better at getting along.

Neal Stephenson's novel /The Diamond Age/
cite:stephenson:2000diamond is set in a stateless future
where there are no nation-states and all nations, which are
called /phyles/ are scattered around the planet and urban
areas are divided into areas for different phyles.  Each of
these areas have a sort of diplomatic immunity within the
walls of their area and govern themselves.  This vision is a
Stateless system where the diaspora have created enclaves
which reinforce the same bad behavior as the nation-state
system encouraged and there is little to no cosmopolitanism
in these metropolitan areas, and people who do not belong to
a phyle are left with no protection or community.  This is
what happens when everyone follows their own rules.  It's
only when everyone has to live together under the same rules
that a comopolitan egalitarianism is possible.


*** Middle 
Middle can be thought of as an autonmous distributed
adhocracy that includes the governance, infrastructure and
commerce pace-layers.  Middle takes over a large part of
what government, utilities, logistics, and the financial
sector do today.



*** Culture

CULTURE operates at the slowest pace-layer, and maintains
continuity, long term thinking and planning and things that
are too slow for human scales.  CULTURE is civilization's
long term memory.  This is where the dark-Arcs will be
managed, quietly and out of sight.  

Culture doesn't only store the past, it serves the
institutional function of /remembering/ the past and
ensuring that the present is aware of it.  In this sense
Culture will do something similar to the Lorites in Neal
Stephenson's /Anathem/:

#+begin_quote
*Lorite:* A member of an Order founded by Saunt Lora, who
believed that all of the ideas that the human mind was
capable of coming up with had already been come up
with. Lorites are, therefore, historians of thought who
assist other avout in their work by making them aware of
others who have thought similar things in the past, and
thereby preventing them from re-inventing the wheel.
#+end_quote

Culture maintains and operates long term plans, it is always
trying to think twenty chess moves ahead of each move based
on the Law of Conservation of Energy.  Every action we take
has consequences.  If you build an house in one location,
how will that impact the local water tables over the next
thirty years?  How will the wood used to build the house be
replaced?  How many children will be born in this house and
how will that effect the local school and daycare system?
Every birth should trigger all kinds of long term processes
that start making preparations for later stages of that
person's life, including health and education and ensure
that preparation for providing them basic-income when they
come of age.

*** Scope

SCOPE.  Scope is outside the pace-layers.  Where Culture and
Middle are highly distributed, SCOPE is global.  Scope has
great power, but is kept on a short leash.  Scope ensures
that the distributed system stays connected and doesn't
fracture and fork.  Scope is the interface with anything
outside of The Culture, both in terms of diplomacy, trade
and security.  Scope is divided into a number of subsections
which we won't get into here.


** References

 CITY

  - Kotkin, J., The city: a global history (2007), : Modern
    Library.
    cite:kotkin:2007city
  - Kotkin, J., The human city: urbanism for the rest of us
    (2016), : Agate Publishing.
    cite:kotkin:2016human-city
  - Brand, S., Whole Earth Discipline (2010), : Penguin Books.
    cite:brand:2010whole-earth-discipline


TRIBES and NATIONS

  - Kotkin, J., Tribes: how race, religion, and identity
    determine success in the new global economy (1993), :
    Random House.
    cite:kotkin:1993tribes
  - 
    

 BIOREGIONALISM

  - Aberley, D., Interpreting bioregionalism,
    Bioregionalism, (), 13–42 (1999).
    cite:aberley:1999interpreting
  - Anderson, W. T., /There's no going back to nature/
    (1996).
    cite:anderson:1996theres
  - Berg, P., What is bioregionalism?, Trumpeter, 8(1),
    (1991).
    cite:berg:1991bioregionalism
  - Glotfelty, C., & Quesnel, E., The biosphere and the
    bioregion: essential writings of peter berg (2014), :
    Routledge.
    cite:glotfelty:2014bioregion 
  - Joshua Lockyer, J. R. V., Environmental anthropology
    engaging ecotopia: bioregionalism, permaculture, and
    ecovillages (2013), : Berghahn Books.
    cite:lockyer:2013ecotopia
  - Lipschutz, R. D., Bioregionalism, civil society and
    global environmental governance, In (Eds.),
    Bioregionalism (pp. 115–134) (2005). : Routledge.
    cite:lipschutz:2005bioregionalism
  - Lockyer, R. L. T., Lifeplace: bioregional thought and
    practice (2003), : University of California Press.
    cite:theyer:2003lifeplace
  - Mollison, B., Permaculture: a designers' manual
    (1988), : Tagari.
    cite:mollison:1988designers
  - Mcginnis, M., Bioregionalism (1998), : Routledge.
    cite:mcginnis:1998bioregionalism 
  - McGinnis, M. V., A rehearsal to bioregionalism, In
    (Eds.), Bioregionalism (pp. 15–24) (2005). : Routledge.
    cite:mcginnis:2005rehearsal
  - Thomashow, M., Toward a cosmopolitan bioregionalism, In
    (Eds.), Bioregionalism (pp. 135–146) (2005). :
    Routledge.
    cite:thomashow2005toward
  - Toffler, A., The third wave (1981), : Bantam Books.
    cite:toffler:1981third
