#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XVI. Branches Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] [[[./index.org][up]]]

* XVI. Branches Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/16/intro.org
:Created:  2018-04-30T21:55@Prek Leap (11.642600N-104.919210W)
:ID:       7e6907b1-4665-42c6-8e7b-7c34fa1f6e66
:VER:      578372195.868142072
:GEO:      48P-491193-1287029-15
:BXID:     proj:KJV2-1414
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

A Civilization is not a state, though at several times in
history the distinction has gotten blurry.

Civilization is a system that emerges when a complexity
threshold is crossed that is a mixture of population,
culture, commerce, and technology has been reached.
Civilizations have no governance, no monuments, no leaders.
They have their gods, heroes and narratives that provide
context, locality and meaning.  Everyone has their own gods
and as Drumbledore said, “of course it is happening inside
your head... but why on earth should that mean that it
is not real?”

Culture is at bottom, holding the narrative threads like
reins on a team of horses, pulling back here and letting out
there to keep everyone pulling as one.  You can no more
overthrow a civilization than you can tame a sea.  The
nations and states that make up civilization blaze brightly
for a while, then flicker and go dark with civilization
hardly taking notice.  Civilization works at timescales slow
enough that they will eventually be seen by the even slower
evolutionary processes that govern life, if only it can
survive long enough.  With only ten thousand years under its
belt civilization is still an infant.  Evolution will take
notice in another ten or twenty thousand years when we've
been around long enough to begin our adolescence.  It might
take hundreds of thousands of years more before we enter early
adulthood.

After the two World Wars cleared the last vestiages of
pre-industrial power stuctures, the basic building block has
been the nation state, fusing national cultural identity
with state institutions and power structures backed up by
guns.  The territories each nation-state controls have
become sacrosanct, the sovereignty claimed in the name of
the nation (not the state) is coached in secularized terms
that echo the claims of earlier monarchs claiming their
their power was sanctioned by God.

It's all a social construct, a story we tell to each other
so we as a species can cooperate with each other.  No where
is this more clear than in the image made of the Earth on
the 7th of December 1972 by the crew of Apollo 17.  For the
first time in Mankind's history, the whole of the planet was
taken into one frame of reference, a beautiful blue marble,
basking in the sunlight in the black emptiness of space.  In
that image there are no state borders, no nations, no racial
demarcations or ideologies.  There is only the blue water,
the white clouds and polar ice, the brown deserts and the
green forests and grasslands.

I say all of this to remind myself of the magnitude of what
I am about to propose.  That the only way our speices and
civilization is to survive and flourish will be to take the
reins of civilization and lay down more imaginary lines on
our fragile blue marble.

With every year all of the key control points of
Nation-States, save one is fading, transporation, knowledge,
communication and commerce increasingly ignore borders,
leaving behind only territorial borders and guns (lots and
lots of guns), like the smile of the Cheshire Cat.

The old stories that built an industrialized world are being
forgotten, to be replaced by new stories.  It may not feel
like this has happened and that the nation-state is still in
firm control of the reins but this is only because
governance and culture are on slower pace layers and haven't
yet caught up with Infrastructure, Commerce and Fashion.
The cracks in governance and culture are already starting,
and in some places have grown to become fissures, in others
they will remain little more than hairline cracks easily
overlooked and ignored for decades to come.

As the nation-state fades, its place in the human ecosystem
will need to be filled.

The longer have considered these thing the more I am
inclined to think that a world order is nearly apon us,
though we can't yet see it's final shape or form.  I don't
think that we have reached an inevitibility threshold but we
are very close.

We need to understand what as the nation-state erodes, some
of it's functions are being displaced, such as
transporation, international commerce, the flow of
information as communications, news and knowledge and the
flow of wealth as currency, resources, energy and goods.

As mentioned the one thing that nation-states still have
control over is physical borders of the territories they
control.  But the also control large parts of public
infrastructure and national and local governance.

The dichotomy of human activity into public and private
spheres are built on top of common definition of property is
becoming increasingly dysfunctional. The concept of
property, commons, and separation of public and private
sectors needs to be rethought.

The old concept of the Commons as sort of possitive-sum DMZ
is under increasing assult from both public and private
spheres both idea and practice is where I think what needs
to be addressed.

The biggest challenge will be to decentralize both public
and private spheres and move power from the center to the
edges.  This will ensure that distribution of resources and
wealth better meets the majority of people's needs.  It will
also make our overall civilization more resiliant and
flexible when dealing with catastrophes.

This is best done if we can merge public and private
together into a scalable decentralized framework.  No,
this is not the public sphere nationalizing the private or
the private sphere privitizing the public.  Both of those
approaches have been tried and both have failed in
spectacular fashion.  Rather I see the concept of a
corporate body that has a dual nature that can be seen as
public in one context and private in another as a viable
alternative to the present system.  For this to work we need
to rethink the underlying system where nearly everything is
treated as Property, and an ever shrinking Commons.

I would argue that private property can not exist unless
there is a functional Commons acting as a counter weight.

The commons is not simply a community owned form of
property.  The Commons is not a subset of Property.  It is
in a different category all together.

But to understand why this is true we must first understand
what property really is.  The concept of property evolved
from the concept of an individual's personal possessions,
the cloths on your back, and the tools in one's bag.  The
Inuit buried their dead with their personal tools so that in
the afterlife they would be able to hunt and fish.  This
belief has been expressed in one way or another in most if
not all cultures through history.  The greate dynastic
Chinese emperors being buried with entire terracotta armies,
tools and livestock.  The Egyptian King's tombs contain a
treasure trove of everything the King would need in the
afterlife. 

But in each case, these things were possessions -- it was
only later as man became increasingly sedantary that the
concept of posessions became enshrined as property, because
agricultural land had to be divided into plots and
cultivated and the wealth produced by those plots became
property as well.  At that time all wealth was physical, and
was protected by threat of physical force.  Over time, as
societies became increasingly complex, wealth became
increasingly symbolic with currencies using precious metals
used as a means of storing wealth and as a intermediate step
in trading.  So that direct barter trade of goods was
replaced with exchange of goods and services for currency
which could then be used anywhere to obtain anything.

By the end of the twentieth century, wealth had made the
transition from being symbolic to being pure information.
This was followed by the digitalization of all types of
information which had previously been stored on physical
media which could be copied and sold as a kind of property.
When the Internet crossed its own critical threshold in the
last ten years of the 20th century, the process of
converting all information into formats that could be
represented as binary digital data went into high gear.
Some thirty years later that process is largely complete.
But this displaced the value of information as a form of
physical property that could be bought and sold.  Copyright
law, which had been created to control the creation of
physical artifacts that contained copies of recorded
information tried to jettison the physical media and place
ownership on the disembodied information that had been
encoded on it.  This has not worked very well because
information and knowledge is not a possession, you possess
what is in your hand and that can be taken away from you.  

The knowledge in your head is not a possession it is, in
effect part of you.  When you pass on that knowledge to
someone else you still have that same knowledge in your
head.  And where did that knowledge come from?  Everywhere,
from the winter winds, to the crunching sweetness of the
first Autumn apples, to the first time you learned to write
your name, ride a bicycle, or swim across a pond.  The song
you hum to yourself on the train on the commute to work is
not property, it has been woven into becoming what you are.
It can not be owned.

As Issac Newton famously said, "if I have seen farther, it
is because I have stood on the shoulders of giants."  Until
the nineteenth century most knowledge was thought of as
being a part of our culture.  In that sense, the
historically recent term, "intellectual property" is not
only ludicrious but obscene.  Since the sixteenth century
man has moved away from the concept of humans as groups made
up of individuals to individuals who belong to different
groups.  We have fractured into a world of more than seven
billion sovereign monarchs of our personal kingdoms.  A few
percent of those kingdoms contain 80% of all the property
and wealth and the rest get by they best they can on the
margins.

The Commons is not owned.  It belongs to everyone, because
everyone past and present, the dead and the living, have
incrementally contributed to them.  Every life, every hour
of toil and suffering, every innovation be it the spoken and
written languages that we use to communicate, a joke told at
the local pub, an incremental improvement of a tool that has
been in use long before the cultural revolution.  Something
as simple as a spade is expressed today by monster
industrial scale earth moving machines.  Those machines are
made up of parts that are based on other parts and ideas and
discoveries that date back to Man's earliest existence and
would not exist or could never be built without all the
efforts of countless people over thousands of generations
that came before.  No one owns these things, they are not
and can not be considered property.

Wealth was one of the the first things to become symbolic,
and then pure information.  But now that all information has
been digitized and transmitted using a positive-sum
mechanism, information has become the most flexible and
powerful form of wealth and that all forms of physical
wealth are expressions of information.  As the physicist
John Weaver said, the entire universe is an expression and
actualization of information, literally it from bit.

Our present everything-is-property model is based on an
increasingly outmoded concept of all property being
physical.  Information has been freed from the physical
media that it was encoded on and is not longer property.

But if everything is information, and even the physical
world is simply a way of compiling information into matter
then the old property model is no longer a viable means of
measuring and distributing wealth as goods and services.

The solution is to return variation of the ancient concept
of the division of possessions and knowledge.  With
knowledge being the most important and embodied in the
concept of the Commons.  Property then needs to be demoted
somewhat and become something closer to what our distant
ancestors would be considered as personal property.

So we can now start to put this all together, with a new
concept of a civilization that is made up of distributed
human-scale corporate bodies, where each corporate body has
a dual public-private nature and that this is built on top
of the expression of knowledge as being a part of the
Commons with material goods being possessions, not
accumulated material weatlh.

This concept is neither capitalist nor communist and in a
post-scarcity world domainated by disembodied information
that is largely an extension of mind, but incresingly
externalized cognitive processes that can autonomously
control machines to produce material goods and services.

Second, in many respects, things will go on as they do
today, people will continue to live much as they always have
when they have a relatively high standard of living, freedom
and safety.  People are largely okay with the structure of
daily life, so long as they have the resources to have a
good life.  There will still be markets, schools, companies,
jobs (for those who want them) and money, but underneath the
surface things will be substantially different.

Third, this is no Utopia that we are envisioning.  Life
always has been and always will be a messy affair and
nothing a bunch of clever hairless apes do are going to
change that.  The system is designed to make allowances for
human nature, our cognitive limitations and biases.  What
makes us human also ensures that we will always screw things
up, no matter how good things are, and there will always be
a restless few who can't or won't be able to accept living
in the system staying in or leaving is an option which the
system must not only allow but respect and aide in any way
we can, so long as what they want does not violate the
welfare, freedom and safety of others.

But we're still missing a few important pieces of the larger
puzzle.  Civilization requires a significant amount of
things that can not be done at human-scales.  These are
critical functions that the present system provides
that the system I have so far outlined can't provide.  

We need a common meta-origin story which any local culture
can map their cultural mythos onto.  That meta-origin story
then becomes the foundation for a universal set of humanist
principles which ensure that everyone is treated fairly.
This only works if everyone places by the same rules and
those rules are apply to and are applied fairly to everyone
in the same manner.

We still need a means of coordinating propagation of
information and the coordination of large numbers of small
public-private corporate bodies to be able to come together
in an adhocracy to achieve goals that can only be done today
at scale using large centralized infrastructure.

And we need a means of creating negative feedback loops that
ensure that the system doesn't drift and change into
something that does not adhere to the core humanist
principles that ensures that we are living in a positive-sum
civilization of all humanity, and not revert back into an
atomized mob of personal kingdoms.

To provide this, I propose establishing, for want of a
better term, branches of civilization that provide these
functions for all of Mankind.

These are somewhat similar to the different branches of a
government which are meant to a) gain consensus, b) provide
direction, and c) maintain the system and make corrections
to keep it on course.

Today those three branches are typically, executive,
legislative and judical.  Each branch is designed to be
independent of the other branches and whose job is to
provide negative feedback mechanisms that keep the other
branches in check.

Our system will use these same concepts but in a different
configuration that reflects the system that they are
managing that is made up of human-scale public-private
corporate bodies built on a concept of a Commons with
personal possessions.

Before we introduce the three branches it needs to be clear
that these are no branches in same sense as today's
government branches, this is no bureaucracy or president or
legislative bodies.  These branches are distributed, and are
part of the public nature side of every corporate body,
which in aggreagte functions as if they were government
branches, but only manifest these functions physically as
ad-hoc processes that self-destruct, or rather, disband
themselves when a process has been completed.

These branches are not owned or controlled by anyone, but
are directed and mantained by everyone as part of day to day
life.  The branches emerge from the running kernal that has
been compiles from source code built on patterns which are
based on universally agreed apon first principles.

We call these branches (with a tip of the hat to Ian Banks),
Middle, Scope and Culture.

First, the three branches operate at different rates of
change, with Middle being the largest and fastest changing
and Culture being the slowest but most powerful.  The slower
layers act as guidance and provide limits on the faster
layers.

Second, each branch is independent of the others, and have
some authority to force the other branches to make
corrections when necessary.

Third, branches propagate at different speeds and adapt
locally.  Fuck ACID, that's not how things work, different
things change at different speeds, and only when they are
ready in their own good time.  We must reject the tyranny of
the instant, the immediate, and return to the expectation
that the world is neither uniform nor retrograde.  We need
to remember how to live in a spectrum of different presents,
each with its own character and state.  This gives us a
stability that we have nearly lost.  We need to remember
that that the the present is a spectrum rather than an
absolute.  This provides space for people to adapt and much
needed continuity especially between generations.  But just
as important, it slows us down and reminds us that we all
live in a present which is different in different places.


MIDDLE includes the governance, infrastructure and
commerce pace-layers.

CULTURE operates at the slowest pace-layer, and maintains
continuity, long term thinking and planning and things that
are too slow for human scales.  CULTURE is civilization's
long term memory.  This is where the dark-Arcs will be
managed, quietly and out of sight.  

Culture doesn't only store the past, it serves the
institutional function of /remembering/ the past and
ensuring that the present is aware of it.  In this sense
Culture will do something similar to the Lorites in Neal
Stephenson's /Anathem/:

#+begin_quote
*Lorite:* A member of an Order founded by Saunt Lora, who
believed that all of the ideas that the human mind was
capable of coming up with had already been come up
with. Lorites are, therefore, historians of thought who
assist other avout in their work by making them aware of
others who have thought similar things in the past, and
thereby preventing them from re-inventing the wheel.
#+end_quote



SCOPE.  Scope is outside the pace-layers.  Where CULTURE and
MIDDLE are highly distributed, SCOPE is global.  SCOPE has
great power, but is kept on a short leash.  SCOPE ensures
that the distributed system stays connected and doesn't
fracture and fork.  SCOPE is the interface with anything
outside of The Culture, both in terms of diplomacy, trade
and security.  SCOPE is divided into a number of subsections
which we won't get into here.


** References

  - Toffler, A., The third wave (1981), : Bantam Books.
    cite:toffler:1981third
