#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 4. Pace-Layer Model Abstract 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 4. Pace-Layer Model Abstract
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/04/04/abstract.org
:Created:  2018-05-18T09:12@Prek Leap (11.642600N-104.919210W)
:ID:       78e79a33-69f7-4452-a7d1-2b35842965f5
:VER:      579881589.893434990
:GEO:      48P-491193-1287029-15
:BXID:     proj:XQC0-2851
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
** TL;DR

My original idea was to use pace-layers as the primary
organizational scaffolds for w&w.  Then it all drifted into
being a massive linear narrative -- too massive.  the whole
fucking thing is too complex on two many levels to be a
long-form linear narrative.  So let's return to a looser
framework that combines sort of a whole earth catalog
approach with the original loose-leaf binder concept behind
APL.

Cantos are no longer narratives -- but rather an
introductory essay that provides a narrative and then a
mashup of supporting patterns, parameters, events, people
etc that create a kind of map for the introduction -- that
taken together is a whole, though many of the different
parts might also belong to other Cantos (tho at different
LOD/POV etc.)

This is actually what I was trying to get at with the TL;DR
idea but was thinking of them at that time as being sidebar
rabbit-holes.  The whole earth approach is far better.



** References


