#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Introduction Volume VIII Lingua Franca
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] [[[./index.org][up]]]

* Introduction Volume VIII Lingua Franca
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/08/intro.org
:Created:  2018-04-27T09:49@Prek Leap (11.642600N-104.919210W)
:ID:       7fa6dfa4-4ac3-4730-b9ac-2e58851d5103
:VER:      578069424.218391470
:GEO:      48P-491193-1287029-15
:BXID:     proj:JXG0-6014
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

Mythos is the foundation for languages -- you can't have one
without the other. Lingua francas are always based on
networks and in particular empires which are more or less,
networks.

** TL;DR

On the face of it, the story of the fall of the Tower of
Babel is a pourquoi story, providing a backstory for why
there are so many different human languages.  The story has
always captured people's imagination, if for no other reason
that in the story, God is not so much punishing Man, but
making a premptive strike against man, who had eaten from
the tree of knowledge and was then ejected from the Garden.
In the destruction of the Tower God shows that he (the Old
Testement always potrays their God as masculine) what he was
scared of most was what Man would do with that knowledge --
cooperate.  And by cooperating Man collectively would be
able to challenge God.  The implication is that the source
of God's power is knowledge. By detroying the Tower and
fragmenting a single common language into many, it would
make the type of cooperation needed to challenge God's
knowledge and power impossible.




** References

  - Gordin, M. D., Scientific babel: how science was done
    before and after global english (2015), : University Of
    Chicago Press.
    cite:gordin:2015scientific-babel
  - Nye, M. J., /Speaking in tongues: science’s
    centuries-long hunt for a common language/ (2016).
    cite:nye:2016speaking-tongues
  - Jenkins, J., Global englishes: a resource book for
    students (2014), : Routledge.
    cite:jenkins:2014global-english
  - Horobin, S., How english became english: a short history
    of a global language (2015), : Oxford University Press.
    cite:horobin:2015how_english
  - Northrup, D., How english became the global language
    (2013), : Palgrave Macmillan US.
    cite:northrup:2013how-english
  - Crystal, D., English as a global language (2003), :
    Cambridge University Press.
    cite:crystal:2003english-global
  - Mair, C., The politics of english as a world language:
    new horizons in postcolonial cultural studies (cross
    cultures 65) (2003), : Rodopi.
    cite:mair:2003politics-english

