#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Introduction Volume VIII Lingua Franca
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] [[[./index.org][up]]]

* Introduction Volume VIII Lingua Franca
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/08/intro.org
:Created:  2018-04-27T09:49@Prek Leap (11.642600N-104.919210W)
:ID:       7fa6dfa4-4ac3-4730-b9ac-2e58851d5103
:VER:      578069424.218391470
:GEO:      48P-491193-1287029-15
:BXID:     proj:JXG0-6014
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

Mythos is the foundation for languages -- you can't have one
without the other. Lingua francas are always based on
networks and in particular empires which are more or less,
networks.

** TL;DR

#+begin_quote
1 And the whole earth was of one language, and of one speech.

2 And it came to pass, as they journeyed from the east, that
  they found a plain in the land of Shinar; and they dwelt
  there.

3 And they said one to another, Go to, let us make brick,
  and burn them throughly. And they had brick for stone, and
  slime had they for morter.

4 And they said, Go to, let us build us a city and a tower,
  whose top may reach unto heaven; and let us make us a name,
  lest we be scattered abroad upon the face of the whole
  earth.

5 And the Lord came down to see the city and the tower,
  which the children of men builded.

6 And the Lord said, Behold, the people is one, and they
  have all one language; and this they begin to do: and now
  nothing will be restrained from them, which they have
  imagined to do.

7 Go to, let us go down, and there confound their language,
  that they may not understand one another's speech.

8 So the Lord scattered them abroad from thence upon the
  face of all the earth: and they left off to build the city.

9 Therefore is the name of it called Babel; because the Lord
  did there confound the language of all the earth: and from
  thence did the Lord scatter them abroad upon the face of all
  the earth.

— Genesis 11:1–9, King James Version
  https://en.wikisource.org/wiki/Bible_(King_James)/Genesis#11
#+end_quote


On the face of it, the story of the fall of the Tower of
Babel is a pourquoi story, providing a backstory for why
there are so many different human languages.  The story has
always captured people's imagination, if for no other reason
that in the story, God is not so much punishing Man, but
making a premptive strike against man, who had eaten from
the tree of knowledge and was then ejected from the Garden.
In the destruction of the Tower God shows that he (the Old
Testement always portrays their God as masculine) what he was
scared of most was what Man would do with that knowledge --
cooperate.  And by cooperating Man collectively would be
able to challenge God.  The implication is that the source
of God's power is knowledge. By detroying the Tower and
fragmenting a single common language into many, it would
make the type of cooperation needed to challenge God's
knowledge and power impossible.

This fits well with the Christian concept of time as
unwinding since The Fall, because at Babel God showed his
hand and that he was actively putting barriers in Man's way
after ejection from the Garden.  So in a sense, Babel
becomes a pourquoi story that explains entropy as a process
guided by God's hand. The Enlightenment turned this on it's
head and introduced the vision of time as progress and Man's
progression from savagery to
civilization. cite:thompson:1978darkness

The ability for us to progress is directly proportionate to
how well we can cooperate with each other, and cooperation
is founded on communication.  For all the richness, beauty
and variety of the spectrum of different human languages,
there is no getting around that mankind's greatest
achievements throughout history were made when there there
were lingua francas, often in the form of second languages,
such as Greek, Arabic, Latin and Mandarin which were used to
bridge communication between different cultures, speed the
propagation of information including news, scientific
discovery and even religious belief systems.  All of the
major monotheistic religeons were held together for most of
their history because of the continuity of a common language
over several millennia.  In this sense, the lingua franca
minimized the introduction of errors through translation.
Since each language is build on a cultural mythos,
translating a sacred text to a different language inevitably
introduces subtle shifts of meaning, no matter how careful
the translator attempts to stay true to the original text.
Once you change the surrounding context of something, you
change the meaning as well.

The dark side of most Lingua Francas is that they have
largely been used as tools of oppression, of empire,
imperialism and as a tool of cultural genocide. 

Lingua franca's are an important part of any state to make
it's people legible.cite:scott:1998seeing



** References

  - Gordin, M. D., Scientific babel: how science was done
    before and after global english (2015), : University Of
    Chicago Press.
    cite:gordin:2015scientific-babel
  - Nye, M. J., /Speaking in tongues: science’s
    centuries-long hunt for a common language/ (2016).
    cite:nye:2016speaking-tongues
  - Jenkins, J., Global englishes: a resource book for
    students (2014), : Routledge.
    cite:jenkins:2014global-english
  - Horobin, S., How english became english: a short history
    of a global language (2015), : Oxford University Press.
    cite:horobin:2015how_english
  - Northrup, D., How english became the global language
    (2013), : Palgrave Macmillan US.
    cite:northrup:2013how-english
  - Crystal, D., English as a global language (2003), :
    Cambridge University Press.
    cite:crystal:2003english-global
  - Mair, C., The politics of english as a world language:
    new horizons in postcolonial cultural studies (cross
    cultures 65) (2003), : Rodopi.
    cite:mair:2003politics-english
  - Scott, J. C., Seeing like a state: how certain schemes
    to improve the human condition have failed (1998), :
    Yale University Press. 
    cite:scott:1998seeing 
  - Thompson, W. I., Darkness and scattered light: four
    talks on the future (1978), : Anchor Books.
    cite:thompson:1978darkness 
