#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Economic Infrastructure Introduction 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Economic Infrastructure Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/11/05/intro.org
:Created:  2018-05-08T19:22@Prek Leap (11.642600N-104.919210W)
:ID:       6e8e65a6-a6ab-454c-8d00-dc3a71c498ae
:VER:      579054199.588426045
:GEO:      48P-491193-1287029-15
:BXID:     proj:YPU6-3124
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
Economic infrastructure makes possible the complex exchange of goods
and services between a large group.

There are a lot of assumptions about economic infrastructure today
that are based on our present free-market economy.  But this system
took centuries to evolve and to assume that the present system will
remain in its present form isn't even paying attention to current
events.  The world has moved away from currencies backed by stores of
material goods such as gold and silver to be replaced by fiat
currencies which are nothing more than information which is backed by
the threat of physical force by a State.  Even these currencies could
be eventually be replaced with trustless crypto-currencies.  However,
this is doubtful because the majority of cryto-currencies are still
fiat-currencies whose value is based on belief of their value as a
medium of exchange relative to other currencies.  Micro-trading has
transformed stock exchanges and turned them into little more than
speculative casinos that are being used less and less for their
intended purpose of financing commercial and even public enterprise.

Economic infrastructure is presently at the beginning of
transformation into a post-scarcity civilization in which markets,
money and investments will be radically transformed. 

This section will create a generalized model for economic
infrastructure and it's requirements that work across all succession
stages, past, present and future.

** TL;DR
** References


