#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 1.2.1 Ab Initio Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[./index.org][up]]] [next]


* 1.2.1 Ab Initio Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/02/intro.org
:Created:  2018-04-21T17:04@Prek Leap (11.642600N-104.919210W)
:ID:       21c2adbb-30d9-475f-ba9f-f80612467e67
:VER:      577577122.409021248
:GEO:      48P-491193-1287029-15
:BXID:     proj:VRM2-4234
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:


** TL;DR

What does it mean to start from first principles?


** Civilization from First Principles

#+begin_quote
I should have desired, in the first place, to explain in it what
philosophy is, by commencing with the most common matters, as, for
example, that the word philosophy signifies the study of wisdom, and
that by wisdom is to be understood not merely prudence in the
management of affairs, but a perfect knowledge of all that man can
know, as well for the conduct of his life as for the preservation of
his health and the discovery of all the arts, and that knowledge to
subserve these ends must necessarily be deduced from first causes; so
that in order to study the acquisition of it (which is properly called
[284] philosophizing), we must commence with the investigation of
those first causes which are called Principles. Now these principles
must possess two conditions: in the first place, they must be so clear
and evident that the human mind, when it attentively considers them,
cannot doubt of their truth; in the second place, the knowledge of
other things must be so dependent on them as that though the
principles themselves may indeed be known apart from what depends on
them, the latter cannot nevertheless be known apart from the
former. It will accordingly be necessary thereafter to endeavor so to
deduce from those principles the knowledge of the things that depend
on them, as that there may be nothing in the whole series of
deductions which is not perfectly manifest.

— Decartes, Preface, Principles of Philosophy (1644)
#+end_quote

Why civilization, let alone rethink it from first priniple?

  - exponential increase in rate of change is forcing slower
    pace-layers to change at rates they are not good at.
    This does not end well.
  - we are undergoing systemic changes that normally would
    have centuries to play out that are now happening in a
    decade or less that we don't even understant let along
    be able to percolate down to the lower layers before
    another systemic shock to the system comes along, and
    then another -- global-value chain, internet, biotech
    and soon ai and robotics.
  - we are fast approaching the edge of the petri dish, and
    in doing so have impacted the climate to the extent that
    we will see systemic change to the planets environment
    -- things are about to get far more chaotic, less
    predictable and this will result in massive shock after
    shock after shock.  This will require a significant
    amount of our surpluss resources to mitigate that needs
    to be spent on ensuring that a planet with 10 billion
    people can be fed and live at an acceptable standard of
    living.
  - in less than a 100 years, if nothing else goes wrong
    that 10 billion population will start to shrink,
    dramatically and there is no way of knowing what that
    will mean -- some projections put the population 200
    years from now at being as low as half of what it is
    today.  that large population is responsible for
    exponential change, but also in expoential discovery and
    innovation.  what happens when we return to a population
    that we haven't seen since the 1950's but still have all
    of the same problems that demand solutions that require
    a far higher percentage of people innovating than we
    have today?    cite:kremer:1993population
  - progress in terms of human civilization is measured in
    the number of specializions that a society requires to
    function.  the larger the territory of an ecosystem, the
    larger the capacity it has to increase the complexity of
    that ecosystem -- civilization is a kind of ecosystem,
    and we have now run out of space for that ecosystem to
    expand on earth.  if we plateau then that marks the
    highwater mark and we will only be able to tread water,
    but the thing is, systems are never static, they are
    always dynamically changing and if you aren't growing,
    you are dying.  we either progress or adjust our
    expectations for humanity and give in to the inevitable.


-----

Next, what do we mean by building from first principles --

  - start with no assumptions, only what can be observed and
    repeated and understood

  - build on what we have learned along the way -- don't
    throw away the baby with the bathwater.  so no zero-day
    tabla rasa, instead we start from scratch and decide
    what works and what hasn't and then build from there.

  - don't be hasty -- we can only change so quickly, and
    change is measured in generations, not decades, we can
    not give in to half-baked schemes that don't work, and
    then when they don't work because the assumptions they
    were based on were wrong, try to change people to fit
    the model, rather than changing the model to fit people.

  - be consistent, persistent and resiliant -- many changes
    take time, sometimes very long periods of time to take
    hold and work -- keep at it, even though you may not see
    the desired results in your lifetime, or even dramatic
    results in your children's lifetime -- playing the long
    game means playing for a very long time -- you and i
    will not see the promised land, and our fate is to
    wander the desert -- that's not an easy thing to say to
    a generation that is used to instant gratification.  the
    reward is that a lot of interesting things happen while
    wandering the desert -- paradise, as well as utopias are
    overrated, they are a horizon and you can never reach a
    horizon because it's constantly retreating.  So cherish
    the challenges in front of you today and that lie ahead
    and forget the destination, it will never live up the
    the hype anyway.


-----

Finally, what is this good for?  The idea of someone
spending a lifetime to work out a generate grammar's for
human civilization sounds so arcane and and removed from day
to day life that it sounds absurd to even consider it.

But consider this, civilization has emerged, evolving on its
own, without us conciously creating it.  And since evolution
is a messy process, civilizations have repeatedly risen and
fallen, and from the ashes new civilizations have emerged
that are a bit stronger and more resilient than the ones
they replaced.  But all of this could only happen because
until the last century, there was always more than one
civilization on the planet.  If one civilization blew up or
faded away, another civilization was there to reboot it.

So this work in an attempt to build a scaffolding that can
be used to build any number of civilizations, it is not
meant to build any one civilization -- in that sense w&w and
appl and even the primer are somewhat neutral.  the hoard,
however will be our attempt to apply w&w, appl and primer to
build a civilization, first to ensure that it works, and to
act as an example of how to apply the grammar.  It's
important that we keep this in mind as we complete this work
and not get too cocky and think that the hoard we build is
/the one/ ultimate hoard that will build an ideal
civilization.  We'll be lucky if we get more than a few
things right, but we hope that it will be good enough learn
from and build whatever does become a stable anti-fragile
human civilization.

Second, the scaffold will be designed to try and keep us
honest and act as a filter that will identify half-baked
ideas, blatently dogmatic systems based on belief systems
etc.

Finally, it will act as a standard that can be used to hold
up against other scaffolds to that future scaffolds progress
and improve rather then degenerate and lead to destruction.


-------- expanded -------

In a sense, this is what happened as recently as in the
America's.  Civilization emerged in the America's completely
independently from Europe and Asia -- there was practically
zero contact, that was any consequence until the end of the
15th century.  Contact did more than simply pit
civilizations against each other, they introduced and mixed
all sorts of bacteria and viruses together from the
different hemispheres that had never been in contact with
each other before.  In part this is likely one reason that
the megafauna in South America was largely replaced by the
North American Megafauna -- as well as any number of other
factors.  The North American species won and replaces many
South American species and filled their ecological niches.

When Europeans made substantial contact with the Americas
they introduced very hardy diseases that had been fighting
it out between Africa, Europe and Asia for millenia and
human's were still largely helpless against them even in the
rest of the world.  The Americas didn't stand a chance --
80-90% of people's on the two continents were wiped out in a
generation.  The Europeans took advantage of this and
replaced filled those ecological niches.

Does this justify what Europeans have done to indigenous
peoples in the Americas, Austrailia and the Pacific and to a
lesser extent in Africa?  No.  But in the larger scheme of
things it can be understood as a consequence of evolutionary
processes that have governed all life on the planet since
life began on earth some 3.5 billion years ago.

It also doesn't get Europeans off the hook either,
civlization had advanced to the point by the middle of the
17th century that blind evolutionary processes were no
longer our Masters and that we knew enough to know better
and to do better by each other.  It's interesting that it
rook another century before these new ideas had been able to
take hold enough to change the behavior of societies as a
whole, but by then it was too late.  By the the last half of
the 18th century and early 19th century when these ideas had
finally taken hold and begun to stay people's hand, that it
was too late.

If first contact had happened two centuries later -- which
is in the realm of the possible if European civilization had
evolved into something more inward looking as happened in
China.  China had made contact in the Americas as well, but
didn't see anything that interested them, and returned home
and never returned.  The Indian subcontinent was not so much
insular as it was distributed.  In Asia it was only the
Mongols that had the same ruthless insatiable wanderlust as
the Europeans -- and if the Mongols had spent as much energy
rebuilding what they conquered as they had in conquering in
the first place, Europe would never have stood a chance and
the world today would be unrecognizable.  But the Mongols
were not culitvators, they were herders and hunters.
Europeans, on the other hand were as much farmers as they
were herders and hunters.  

Even so, modern China as we know it, would not have been
possible without the unification that the Mongol conquerors
-- the mongol chinese rulers combined the paddy with the bow
and arrow as can be literally seen in the chinese ideogram
for country.  If not for the Mongols, China would likely
have fallen as completely to Europeans as did India.




