#   -*- mode: org; fill-column: 60 -*-

#+TITLE: A Narrative Synopsis
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

* A Narrative Synopsis
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/03/ww-narrative-synopsis.org
:Created:  2018-04-08T10:22@Prek Leap (11.642600N-104.919210W)
:ID:       6f150e05-954c-4cac-a155-a5eebf85169b
:VER:      576429803.946697214
:GEO:      48P-491193-1287029-15
:BXID:     proj:PLY1-5537
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** TL;DR

The very term /civilization/ has so many different
definitions, connotations, misdirections, and assumptions
that it's become increasingly common for professionals in
the sciences and academia to shy away from the word
altogether and use terms such as "complex societies" that
don't carry the semantic and ideological baggage and the
attending myriad of agendas that has been associated with
the word at any given time in history.

But rather than playing it safe, we feel that these other
terms are either too watered down or specific to encompass
the diversity, enormity and complexity that the concept of
civilization includes.  Better that we embrace the entire
messy history of the word and provide a clear and concise
narrative that lays out how /we/ understand it and how it
will be used throughout /this/ work.

This chapter is /not/ intended to be an origin story. We
will present an origin story in all the gory detail that it
deserves, but this properly belongs in the /Primer/, and not
here in /The Warp & Woof/.  So this chapter will sketch out
our attempt at a broad narrative that the work can hang it's
hat on, and then detail the origin story in the /Primer/
after the foundational concepts for building a civilization
have been laid out here in w&w and then identify the core
patterns for building a civilization from first principles
in /A Pace-Layer Pattern Language/.


** Human Civilization in a Nutshell

Humans don't scale, we are pre-programed to live in packs
(bands) which are spaced far enough apart to not compete
with each other.  The closer these groups get to each other
the more competition and violence between them.

Pack animals need to coordinate and specialize -- with the
development of Sapien's large cerebral cortext we were given
the processing power to become goal oriented -- something
even our close primate cousins can not do.

Goals in groups require a finer-grained means of
communicating intent than primates had before -- the
evolution of spoken language filled that need.

It's still unclear why Sapiens developed such a large
cerebral cortex and other subspecies of Man did not.  One
theory is that this took place roughly at the same time as
Dog split off from it's cousins the wolf and formed a
symbiotic relationship with humans.  At this point, Sapiens
began to transform from being a single species to the
broader concept of Mankind, which includes other species who
are interdependent with Sapiens and act as an extension and
externalization of our senses, mind, memory and muscle.  We
will frame the evolution of Mankind as a series of
progressive succession of mechanisms and innovations that
extend and externalize our Minds.

   It has been proposed that because of this partnership
   between man and dog, parts of the brain that are
   dedicated to processing sight and smell were not needed
   as much, as dog became both a hunting partner, and an
   early warning system for approaching danger.

   To date, these theories have little evidence to directly
   support them and are little more than educated
   conjecture, they provide a mechanism for the development
   of spoken languages and for the development of a large
   cerebral context.



When Man became sedentary, and settlements were established
too close to each other that they competed for resources,
conflict was inevitable and 10,000 years pretty much
unending warefare ensued.

Small settlements found that if they merged (by one
conquering another) the larger settlement had an edge the
smaller ones.  But humans are not good at living together in
sizes larger than a band, so hierarchies were established
which placed a few people at the top, controlling all of the
land in the settlement and any wealth created, and the rest
under them, were treated as property themselves with any
wealth they created auto-propagating to those at the top.
This was the beginning of slavery.

If each band is a petri dish, and two petri dishes come into
contact with each other, one will win and other other loose
and the resources of the looser become part of the winner's
petri dish.

But a curious thing happened.  The surpluses controlled by
the few at the top gave them free time to think and spend
time doing things that were not directly related to
survival.  The larger a settlement became the more
specializations were required to maintain it.  So just below
the elite at the top another small group emerged who were
given enough wealth to do nothing but think and come up with
ideas and solve problems.  This could not have happened
without slavery.

Slavery, in it's most basic form, treats people as draft
animals that can think.  But not think too much because they
are too busy doing physical labor with little more than hand
tools.  All institutional slavery is based on hard physical
labor using human muscle.

When machines evolved from tools with power sources that did
not depend on human muscle, the old slavery model didn't
work any longer.  You needed people with minimal education
literacy and numerancy to be able to operate the machines.
So slavery was quickly replaced with employees who had
minimum education and had been conditioned to do what they
were told and stay in one place for very long hours and do
the same task over and over.  These workers didn't have to
be treated as property, they did more than slaves did, and
didn't run away because they had the illusion of being free,
when for all practical purposes they had no choice but work
as an industrial slave, or work in the fields far harder in
the countryside.  The factory was a better life than
subsistence farming.  Everything was standardized so workers
and machines were interchangeable so iif a worker ran away,
there was no shortage of people from the countryside to
replace them.

Machines transformed slavery and gave the slaves a better
life, though they were still effectively slaves.  But
because of the man-machine duo, each person could produce
vastly more wealth than before.  This made it possible to
increase the size of the intellectual class who think and
solve problems, this unleashed the beginning of an age of
innovation and discovery that is growing exponentially.  The
more problems solved, the better the lives of the slaves
have become.

The next thing that happened was almost as strange.
Production had become so efficient that it outstripped need.
It soon became obvious to the elites that their slaves were
the best market for all of this extra production capacity --
so slaves were conditioned to buy not just what they needed,
but what they desired.  This kept them happy slaves and
created even more wealth for the elite and increased the
thinking class even more.

This created the conditions for making most wars and
violence something that hurt the elites instead of
increasing their wealth.  If everyone agreed not to kill
each other everyone could accrue far more wealth and the
slaves could increase their wealth a bit more and expect
that their position would increase, slowly, but would
improve so long as they played the game and agreed to stay
slaves.

This brings us up to where we were about 20 years ago.  But
things are set to change again as dramatically as they did
when slaves became workers.

First, all of the petri dishes have effectively become one
-- we're run out of desirable territory to populate.  So
we've created a nation state system which is effectively
frozen for the time being.

Next we learned to communicate at very long distances at
speeds which effectively makes the entire planet from the
perspective of communication and news propagation the same
as if everything was living next door to each other,

Next we have learned to make machines think -- not think as
well as us (yet) but they can think well enough to control
machines and decrease the number of people needed to operate
machines.  This is happening so fast, and machines are
learning to think better and better that it's likely in a
few decades that most machines will not require people to
operate them.  In other words, a hell of a lot of slaves
(billions of them) will be out of the slave business.  But
they will still be in the consumption business.  Without
anyone to consumer what is produced, there is no reason to
produce it.  So we'll take the surplus wealth created by
thinking machines operating our machines that create wealth
and give that wealth to the former slaves and most of the
wealth will still go to the elites.



