#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Distribution Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Distribution Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/05/09/intro.org
:Created:  2018-05-03T09:31@Prek Leap (11.642600N-104.919210W)
:ID:       a7e36f57-f50d-492a-825a-d57d9181065a
:VER:      578586765.937645717
:GEO:      48P-491193-1287029-15
:BXID:     proj:GGA3-3828
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

Economics as a propagation mechanism

** TL;DR
** Epigraph
#+begin_quote
If a universal mind existed, of the kind that projected
itself into the scientific fancy of Laplace – a mind that
could register simultaneously all the processes of nature
and society, that could measure the dynamics of their
motion, that could forecast the results of their
inter-reactions – such a mind, of course, could a priori
draw up a faultless and exhaustive economic plan, beginning
with the number of acres of wheat down to the last button
for a vest. The bureaucracy often imagines that just such a
mind is at its disposal; that is why it so easily frees
itself from the control of the market and of Soviet
democracy. But, in reality, the bureaucracy errs frightfully
in its estimate of its spiritual resources. In its
projections it is necessarily obliged, in actual
performance, to depend upon the proportions (and with equal
justice one may say the disproportions) it has inherited
from capitalist Russia, upon the data of the economic
structure of contemporary capitalist nations, and finally
upon the experience of successes and mistakes of the Soviet
economy itself. But even the most correct combination of all
these elements will allow only a most imperfect framework of
a plan, not more.

— Leon Trotsky, The Soviet Economy in Danger (1932)
  cite:trotsky:1933soviet
  #+end_quote


** References
  - Trotsky, L., & ZINOV'EV, G. E., /Soviet economy in
    danger. the expulsion of zinoviev/ (1933).
    cite:trotsky:1933soviet
