#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Introduction Volume XII
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]]  [[[./index.org][up]]]

* Introduction Volume XII
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/13/intro.org
:Created:  2018-04-30T20:04@Prek Leap (11.642600N-104.919210W)
:ID:       bf8149f9-89de-4472-a096-80df1a9bca77
:VER:      578365516.879777662
:GEO:      48P-491193-1287029-15
:BXID:     proj:BEG4-1235
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

This volume outlines the requirements of both the Culture Pace-Layer
as well as CULTURE, one of the three branches of civilization.

Culture is the slowest layer of civilization.  It works at time scales
which are measured in generations, not single lifetimes.  Ensuring
that there is continuity between all generations that are alive at any
given time is important.  When aspects of culture becomes splintered
and there are different cultures for different generations things
don't work well.

For many people this will sound like a call for returning to
traditional ways of life that are out of sync with the way things are
at any given present.  When generations began to stratify into
different subcultures the concept of a "generation gap", "youth
culture" and other demarcations between people at different stages of
life became something that was assumed to be a natural part of modern
life.  This is largely because many aspects of life that were
traditionally part of culture shifted to the fashion pace-layer.  As
Stewart Brand said, the young are obsessed with fashion, but it bores
the hell out of older people because they've already lived through it
and just seen it as ephemeral and largely pointless.  The
fashion-layer is where you try out new ideas, experiment, break
things.  The things that work become absorbed by the slower layers,
but most of it is the same things that don't work, repackaged again
and again because each generation has to learn by making the same
mistakes that everyone does when they are young.



** TL;DR
** References

