#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Ideologies 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Ideologies
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/04/08/ww-ideologies.org
  :Created:   2018-07-03T08:12@Prek Leap (11.642600N-104.919210W)
  :ID:        6f2f1fe2-7811-47fd-bdb8-599abbafd6d0
  :VER:       583852428.297494690
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:MON5-2852
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope
** TL;DR

#+begin_quote
I think of Marxism as the Creationism of Economics. Derives it's
self-importance from an outdated but still venerable source of
knowledge. Defends that source rather than tests it. Emphasizes parts
their source happened to get right while glossing over the ones where
it completely failed. Maintains that there's still a controversy even
after everyone outside their bubble knows they lost the factual debate
long ago.

— partoffuturehivemind | /r/slatestarcodex
  https://www.reddit.com/r/slatestarcodex/comments/8v7iux/the_opium_of_the_intellectuals/e1lgucg/
#+end_quote

Until recently I had dismissed ideologies as being maps that once
served a purpose but taken on religious meaning and frozen; Medusa's
gaze turning it into dogmatic stone.

Dogma is a mechanism to reduce copying errors which becomes a problem
when a religion scales beyond a certain size.  When errors are
introduced, religious factions inevitably emerge which come into
conflict with the parent belief system.  There is good reason for
religions to place heresy, which at base is nothing more than
asserting statements that do not align with the normative encoding of
the belief system, as a existential danger and act accordingly.  It's
not surprising that monothesistic religions all emerged after the
widespread adoption of writing systems, and that literacy becomes one
of the primary tools used to spread adoption of those systems.  Large
pantheistic systems were too flexible and make peace with the inherent
uncertainty, and ambiguitiy of the world to be able to scale.
Monothesisms were simple inter-connected clouds of memes designed for
maximum propagation.  In that sense the origins of monothesistic
religions are populist in nature, beginning as, or later evolving into
groups seeking independence from or the overthrow of elites.

All of this applies equally to ideologies.

I had no intention of using an entire chapter to ideologies but they
keep popping up were they are least expected or wanted, barring the
way to free rational discourse.  When you cross an ideologue or
religious zelot you trigger knee-jerk violent responses.

#+begin_quote
I came to realize that ideologies had a narrative structure – that
they were stories, in a word – and that the emotional stability of
individuals depended upon the integrity of their stories. I came to
realize that stories had a religious substructure (or, to put it
another way, that well-constructed stories had a nature so compelling
that they gathered religious behaviors and attitudes around them, as a
matter of course). I understood, finally, that the world that stories
describe is not the objective world, but the world of value – and that
it is in this world that we live, first and foremost. … I have come to
understand what it is that our stories protect us from, and why we
will do anything to maintain their stability. I now realize how it can
be that our religious mythologies are true, and why that truth places
a virtually intolerable burden of responsibility on the individual. I
know now why rejection of such responsibility ensures that the unknown
will manifest a demonic face, and why those who shrink from their
potential seek revenge wherever they can find it.

This all may appear as something far removed from the original
problem, but that is true only in appearance. I have learned what it
is that makes the tyrant, and how attractive it can be to participate
in that process. I have come to understand what it is that our stories
protect us from, and why we will do anything to maintain their
stability. I now realize how it can be that our religious mythologies
are true, and why that truth places a virtually intolerable burden of
responsibility on the individual. I know now why rejection of such
responsibility ensures that the unknown will manifest a demonic face,
and why those who shrink from their potential seek revenge wherever
they can find it. I learned what I wanted to know – at least enough so
that my nightmares disappeared.

It is my hope that the transmission of this knowledge will help those
who receive it withstand the forces of ideological possession, and
that this will in consequence aid in some small way the establishment
of a long and conscious peace.

— Jordan Peterson
  https://jordanbpeterson.com/maps-of-meaning/ 
#+end_quote



** References


  - Aron, R., Opium of the intellectuals (1962), : W. W. Norton &
    Company.
    cite:aron:1962opium
  - Kimball, R., /The opium of the intellectuals/ (2005).
    cite:kimball:2005opium-review
  - Peterson, J. B., Maps of meaning: the architecture of belief
    (2000), : Routledge.
    cite:peterson:2000maps-meaning
