#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Boundries
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] | [[[./index.org][index]]]

* Boundries
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-boundries.org
:Created:  2018-03-21T18:48@Prek Leap (11.642600N-104.919210W)
:ID:       d12d937d-7901-4cbe-b165-1cbea44f0526
:VER:      574904971.750844647
:GEO:      48P-491193-1287029-15
:BXID:     proj:KDF6-1478
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Table of Contents

 - 00. Systems Boundries
   - Carrying Capacity (general concepts)
   - Petri Dish
     - positive feedback loops
     - negative feedback loops
   - Being the Right Size cite:haldane:1928being
   - People Don't Scale
 - 00. Physical Boundries (physics)
   - Speed of Light (propagation)
   - Computation
   - Memory Storage
 - 00. Planetary  cite:steffen:2015planetary
   - Climate change
   - Biosphere
       - functional diversity
       - genetic diversity
   - Biodiversity loss
   - Biochemical Flows
       - Carbon Cycle
       - Nitrogen cycle
       - Phosphorus
   - Ocean
       - acidification
   - Land use
   - Freshwater
   - Ozone depletion
   - Atmosphere
     - aerosols
   - Chemical pollution
 - 00. Sapiens (species specific)
   - Physiological
     - Size
     - Sleep
     - Rest (not same as sleep)
     - Light (and diurnal cycles)
     - Energy Requirements
       - Calories
       - Nutritional Requirements
       - Water
   - Environmental
     - Atmosphere 
       - composition
       - pressure
       - temperature
       - radiation
     - Gravity & Acceleration
   - Psychological
     - Human nature
       SEE: cite:pinker:2003blank 
     - Cognitive Limits and Bias
   - Sociological
     - Dunbar
 - 00. Civilization

--- Not Boundries ---

 - World Models
   - Individual
   - Group 
   - Culture
** TL;DR

Boundries define the limits that our planet, all of life,
our species, civilization and ourselves as individuals must
work within.  They include hard physical limits that systems
need to work within or collapse.  They include limits that
societies need to stay within or decline and collapse.  They
include human cognitive limits and bias of which there are
many.

Boundries mostly come down to the fact that most things are
designed to work at certain scales.  We don't see dragonflies
that are several meters long any longer because insects take
in oxygen through their skin (they don't breath with lungs
or gills) and monster dragonflies were only possible because
the percentage of oxygen in the atmosphere allowed insects
to scale far larger than they can today.

Overall having a lower level of oxygen in the atmosphere is
a good thing.  Oxygen is a very dangerous element because it
reacts with so many things.  Oxygen burns, it reacts with
metals like iron can causes rust.  The astronauts in the
Apollo space died because of a flash fire caused by a spark
because the capsule was using pure oxygen instead of mixing
it with an inert gas such as nitrogen which makes up the the
bulk of earth's atmosphere.

So it's important that we are aware of all of these
boundries that, well, bound us.  Some of these bondries
benifit and others limit and work against us.  But either
way we can't get around them and we must design systems that
work within them.


** References
 - Carey, S., The origin of concepts (2009), : Oxford
   University Press, USA.  cite:carey:2009origin
 - Haldane, J. B. S., On being the right size, Harpers, (),
   (1928).
   cite:haldane:1928being
 - Pinker, S., The blank slate: the modern denial of human
   nature (2003), : Penguin Books.
   cite:pinker:2003blank
 - Steffen, W., Richardson, K., Rockstr\"om, Johan, Cornell,
   S. E., Fetzer, I., Bennett, E. M., Biggs, R., …,
   Planetary boundaries: guiding human development on a
   changing planet, Science, 347(6223), 1259855 (2015).
   cite:steffen:2015planetary 
   cite:rockstrom:2009safe
 - Wikipedia, , /Planetary boundaries --- wikipedia, the free encyclopedia/ (2017).
   cite:wiki:2017planetary-boundries
