#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 08. Cultural Infrastructure Introduction 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 08. Cultural Infrastructure Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/13/08/intro.org
:Created:  2018-05-08T19:51@Prek Leap (11.642600N-104.919210W)
:ID:       3e75a5f9-4206-4685-89d6-91fdae639934
:VER:      579055982.692733356
:GEO:      48P-491193-1287029-15
:BXID:     proj:BEU6-6825
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
Cultural in terms of physical structures and processes, but also the
institutions that use them.

Cultural infrastructure is all about entropy and information.  As
things change over time, watershed events, keystone people in history,
structures, and artifacts that range from great art, to preservation
of instances of objects from material life are a critical part of
civilization.  The knowledge of how people lived in the past, and to
ensure that the knowledge that they used to live at different times in
the past must be preserved so that if it is needed again in the
future, be it how to make a flint arrowhead to manufacturing processes
for cathode-ray tubes could be critical to the surival of future
generations.  We don't know what will be needed in the future -- which
is why it's called the future.

The Library of Congress is considered to be a strategic resource by
the United States government.  Works like Websters unabridged
dictionary, the Oxford English dictionary and until recently
encyclopedias such as Britanica are part of cultural infrastructure.
And yet, national library infrastructures are being scaled back and
are not being treated as critical parts of a civilization's
infrastructure because of the Internet.  The Internet did not replace
library infrastructure and does not perform most of the roles that
libraries do for society.  This is a failure in understanding their
importance and teaching people of how they are vital to socieites.

The other side of cultural infrastructure is for the practice of day
to day culture, from maintaining stadiums and concert halls, to
maintaining stores of decorations used for various cultural events,
and festivals.

Finally we come to structures of historial importance, from buildings
that preserve past architectual styles, to great momuments such as the
temple complex at Angkor Wat.  The United Nations World Heritage Sites
(which replace the older idea of the 7 Wonders of the World) are a
good example of how to recognize such important cultural and natural
artifacts.  But it is also a good example of how few resources are
given to their preservation.  Many sites on the UN list are in
developing countries who do not have the resources to maintain and
preserve these sites and many are in danger of being lost because
there are no funds to maintain them.

** TL;DR
** References


