#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Transactive Memory & Cognition (chapter) 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Transactive Memory & Cognition (chapter)
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/01/02/05/ww-transactive.org
  :Created:   2018-05-31T09:06@Prek Leap (11.642600N-104.919210W)
  :ID:        6306eea6-574a-4287-9e85-a18180f48ad6
  :VER:       581004452.760551639
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:MCA7-3003
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Scope
** TL;DR
** Body



** QUOTE <2013-10-06 Sun 13:06> Blackwell Ency of Social Psych: Transactive Memory

#+begin_quote
*** Transactive Memory
:PROPERTIES:
:ID:       684cf577-2428-4ca3-96bb-fb485b5c0be5
:END:

A system shared among group members for encoding, storing, and
retrieving information such that detailed memories are available to
group members without actual physical possession (Wegner, 1986;
Wegner, Giuliano, & Hertel, 1985). It is defined in terms of two
components representing a structure-process distinction:

    (1) an organized store of knowledge that is contained entirely in
    the individual memory systems of the group members; and

    (2) a set of knowledge-relevant transactive processes that occur
    among group members.  These two components distinguish transactive
    memory from the group mind concept popular early in the century –
    first, because the thought processes of transactive memory are
    completely observable, and second, because previously ignored
    communication processes among group members are proposed as a key
    source in producing the distinction between the group mind and the
    minds of individual members.  Although transactive memory resides
    entirely in the individual memory systems of group members, it is
    transactive in the sense that group members can easily access
    information stored by other members.  Three types of information
    in personal memory define the organization of transactive memory:
    lower- order information, higher-order information, and location
    information. Lower-order information consists of specific facts or
    details – for example, a recipe, mortgage amount, or phone
    number. Higher- order information is the topic or label for some
    set of items of lower-order information, such as cooking or
    bills. Location information is a directory associating
    higher-order topics with group members such that lower-order
    information can be found in the group.

To the extent that group members have mutual higher-order and location
information, they maximize their access to the lower-order information
available from individual members.  In communicating and updating
others about their areas of knowledge, each member cultivates the
others as external memory aids and in so doing becomes part of a
larger system.  The less overlap of lower-order information among
members, the more differentiated is the transactive structure.
Differentiation typically increases the efficiency and amount of
information available in the group as long as members have access to
the location of that information. When groups use communication to tie
different lower-order items under a common higher-order topic, the
transactive structure becomes more integrated. Integration increases
the likelihood groups will combine existing information in new and
creative ways. A balance between differentiation and integration helps
create an optimal transactive memory.

The organization of the transactive memory structure is likely to
change over the course of the relationship. In early stages of a
relationship, members may rely on stereotypes or social categorization
as default indicators of the types of information the others are
likely to know. As members become more familiar, they may establish
their directories or location information through explicit negotiation
(i.  e., "if you remember this, I'll remember that"), or through more
implicit means, such as perceptions of the relative expertise of group
members in different knowledge domains, or knowledge of another's
access to information. Ultimately, the organized structure becomes a
critical basis for the group's interaction, facilitating its memory
performance as compared to that of groups that do not have a structure
in place (Wegner, Erber, & Raymond, 1991).

Equally as important as the transactive memory structure are the
transactive processes that occur as a group encodes, stores, or
retrieves information. Transactive encoding occurs in group
discussions about a memory topic as it is encountered. Individual
perceptions will often differ, and the discussion will lead to a new
understanding, or new memory, by one or more members. Even if
perceptions are similar, discussion increases the likelihood that
memories will become more elaborately encoded, and that they will
therefore be more likely to be available for later retrieval. In these
ways, the information that is stored by the individuals may differ as
a result of group communication processes.  Transactive storage may
produce still more modification of originally encoded information
because of the iterative effects that occur in the process of
communication. In discussing past events, for example, group members
may simplify or elaborate originally stored information in an attempt
to make their individual accounts more consistent or understandable to
others. The resulting memory may be more or less accurate than the
original, but it will almost certainly be different.

Finally, transactive processing may occur in retrieval. A group may
retrieve some target item through interactive cuing, for instance, as
members retrieve relevant items of information that serve as cues for
others's retrieval of more relevant items, and eventually cue
retrieval of the target. Context effects could account for another
aspect of transactive retrieval. Information encoded in the presence
of a group member would subsequently be retrieved more effectively in
the presence of the group member. The participation or mere presence
of group members, then, is likely to affect the retrieval process.
Transactive memory has applications in several domains, including
intimate relationships, health behavior, instructional psychology, and
organizational management (Wegner, 1986). In the case of intimate
relationships, for example, the operation of transactive memory has
important implications for the quality of a relationship. Although
differentiation leads to efficiency, it can also lead to
overconfidence about one's access to knowledge or a lack of common
discussion topics. And the dependence on another for integration could
result in complete devastation when the relationship comes to an
end. Although a smoothly functioning transactive memory can infinitely
benefit its members, problems with faulty information or
miscommunication can have damaging impact. The notion of transactive
memory is useful, in sum, for understanding how groups process and
store information in structured ways that both depend upon and
transcend individual memory.

See also: GROUP PROCESSES; INTIMACY; SOCIAL REMEMBERING.

*** Bibliography
:PROPERTIES:
:ID:       d168860e-6a8a-42cc-bd02-4e9414c4de5f
:END:

Wegner, D. M. (1986). /Transactive memory: A contemporary analysis of
the group mind/. In B. Mullen & G. R. Goethals (Eds.), Theories of
group behavior (pp. 185–208). New York: Springer-Verlag.

Giuliano, T., & Hertel, P. (1985). /Cognitive interdependence in close
relationships/. In W. J. Ickes (Ed.), Compatible and incompatible
relationships (pp. 253–76). New York: Springer-Verlag.  Erber, R., &
Raymond, P. (1991).

/Transactive memory in close relationships/. Journal of Personality
and Social Psychology, 61, 923–9.

TONI G. WEGNER

DANIEL M. WEGNER

-- Blackwell Encyclopedia of Social Psychology

#+end_quote

** References
  - Oshri, I., Fenema, P. V., & Kotlarsky, J., Knowledge
    transfer in globally distributed teams: the role of
    transactive memory, Information Systems Journal, 18(),
    (2008).
    http://dx.doi.org/10.1111/j.1365-2575.2007.00243.x
    cite:oshri:2008transfer
  - Hollingshead, A. B., Communication, learning, and
    retrieval in transactive memory systems, Journal of
    Experimental Social Psychology, 34(), (1998).
    http://dx.doi.org/10.1006/jesp.1998.1358
    cite:hollingshead:1998transactive
  - Moreland, R. L., Transactive memory: learning who knows
    what in work groups and organizations, Shared Cognition
    in Organizations: The Management of Knowledge, (), 3–31
    (1999).
    cite:moreland:1999transactive
  - Moreland, R. L., & Myaskovsky, L., Exploring the
    performance benefits of group training: transactive
    memory or improved communication?, Organizational
    Behavior and Human Decision Processes, 82(1), 117–133
    (2000).
    cite:moreland:2000exploring
  - Sparrow, B., Liu, J., & Wegner, D. M., Google effects on
    memory: cognitive consequences of having information at
    our fingertips, Science, 333(6043), 776–778 (2011).
    cite:sparrow:2011google
  - Wegner, D. M., Erber, R., & Raymond, P., Transactive
    memory in close relationships., Journal of personality
    and social psychology, 61(6), 923 (1991).
    cite:wegner:1991transactive
  - Wegner, D. M., Transactive memory: a contemporary
    analysis of the group mind, In (Eds.), Theories of group
    behavior (pp. 185–208) (1987). : Springer.
    cite:wegner:1987transactive 

