#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 8. Iteration Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 8. Iteration Introduction
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/warp/06/08/intro.org
  :Created:   2018-06-05T09:32@Prek Leap (11.642600N-104.919210W)
  :ID:        20713a91-e354-4019-966f-cdd454f0f84c
  :VER:       581438036.973362517
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:MYJ5-5015
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

#+begin_quote
/Take small steps/. In an experimental approach to social
change, presume that we cannot know the consequences of our
interventions in advance. Given this postulate of ignorance,
prefer wherever possible to take a small step, stand back,
observe, and then plan the next small move. As the biologist
J. B. S. Haldane metaphorically described the advantages of
smallness: "You can drop a mouse down a thousand-yard
mineshaft; and on arriving at the bottom, it gets a slight
shock and walks away. A rat is killed, a man broken, a horse
splashes."

 — cite:scott:1998seeing, [[pdf:scott:1998seeing.org::362][p.345]]
#+end_quote

#+begin_quote
According to Lowdermilk, erosion control in Japan is like a
game of chess.  The forest engineer, after studying his
eroding valley, makes his first move, locating and building
one or more check dhms. He waits to see what Nature’s
response is. This determines the forest engineer’s next
move, which may be another dam or two, an increase in the
former dam, or the construction of side retaining
walls. After another pause for observation, the next move is
made and so on until erosion is checkmated. The operation of
natural forces, such as sedimentation and re-vegetation,
are guided and used to the best advantage to keep down costs
and to obtain practical results. No more is attempted than
Nature has already done in the region.

— cite:howard:1945agricultural, [[pdf:howard:1945agricultural.pdf::171][p.144]]
  SEE: cite:scott:1998seeing, [[pdf:scott:1998seeing::344][p.327]]
#+end_quote


** References


  - DeMarco, T., & Lister, T., Peopleware: productive
    projects and teams (3rd edition) (2013), :
    Addison-Wesley Professional.
    cite:demarco:2013people
  - Haldane, J. B. S., On being the right size, Harpers, (),
    (1928).
    cite:haldane:1928being
  - Graham, P., /Programming bottom-up/ (1993).
    cite:graham:1993bottom-up
  - Larman, C., & Basili, V., Iterative and incremental
    developments. a brief history, Computer, 36(6), 47–56
    (2003).  http://dx.doi.org/10.1109/mc.2003.1204375
    cite:larman:2003iterative
  - Raymond, E. S., The art of unix programming (2003), :
    Addison-Wesley Professional.
    cite:raymond:2003art-unix
  - Raymond, E. S., The cathedral and the bazaar : musings
    on linux and open source by an accidental revolutionary
    (2001), : O'Reilly.
    cite:raymond:2001cathedral
  - Scott, J. C., Seeing like a state: how certain schemes
    to improve the human condition have failed (1998), :
    Yale University Press.
    cite:scott:1998seeing
