#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Systems
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w&w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] | [[[./index.org][index]]]

* Systems
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/ww-systems.org
:Created:  2018-04-11T23:17@Prek Leap (11.642600N-104.919210W)
:ID:       20ea1ca3-d723-431d-9c8e-7b1b83b01430
:VER:      576735489.296135798
:GEO:      48P-491193-1287029-15
:BXID:     proj:UCV1-1046
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Table of Contents

*** Systems Primer
 - Observing Systems : Second-Order Cybernetics
 - Systems Thinking
   - Relationships between different parts of a system
   - flows of energy and resources, needs and opportunities

   - processes that can be thought of as a series of steps
     in which the result of one event triggers another event
     etc.  In computer science this is called Input and
     Output.  Input introduces something into a process that
     does something with the input and the output is then
     fed into another process which does does something that
     produces an output until the process is complete, or
     loops back to start again.  If there is a loop, a
     feedback system is then required to determine if or
     when a loop is terminated.

   - positive feedback loops reinforce unchecked growth

   - negative feedback loops have upper and lower boundries
     and a trigger (sensor) that trips if growth should
     start or stop in order to remain within those
     boundries.
 - positive vs negative space
   - in architecture 
     -- negative is what surrounds what is built
     -- positive is what is built
     -- we move through negative spaces
     -- we dwell in positive spaces
   - in ecology
     -- negative is where there are no resources 
     -- positive is where resources are distributed
     -- species fill ecological niches through adaptation to
        dynamics of the niche, climate, how to access
        resources, shelter, countermeasures against
        predators etc.
   - in cooperative social systems
     -- positive is created by breaking up knowledge and
        tasks into sizes that an individual can handle.  The
        more complex the task, the more knowledge and skills
        required to complete the task.  As systems scales,
        the need for a task is larger than a single person
        can fill, so the task is duplicated so that more than
        one person is filling the same task.
     -- negative is created between knowledge and skill
        domains which require different skills,  tools
        resources and knowledge.
   - in market economies
     -- negative is where there are no needs or opportunities
     -- positive is where there are opportunities to fill
        needs
     -- people develop methods to fill needs to survive
        where there is less competition, if the people
        filling a need outnumber the demand for the need
        then the cost (reward) goes down through competition
     -- markets are a flexible means of distributing
        specialization because they don't require
        hierarchical coordination -- planned economies fail
        because of top-down command and control which is not
        flexible enough to meet the needs of unpredictible
        complexity.
- Specializations & niches
  - the larger the territory of a system, the higher the
    number of specializations -- this is because as things
    scale more variations are introduced between the
    different specializations that fill niches (needs) in
    a system so the system adapts by creating variations
    that specialize in meeting the needs in local
    variations.
  - when two systems come into contact with each other,
    the more interaction between the two systems (the less
    that each system is isolated from each other) the
    tendency of two systems to merge into a single
    homogeneous system.
  - when systems merge, specializations that fill the same
    niche in the previous separate systems begin to
    compete  for the same niche.  The speialization that
    is better adapted to fill the combined niches will
    tend replace the other specialization.

*** Structure
 - Top Down
 - Bottom Up
 - Centralized
 - Distributed

*** Stability
 - Robust (redundancy)
 - Sustainabile
 - Resilient
 - Antifragile


** TL;DR

I'm starting to envision this to be in three broad parts:

  - use Meadows summary as guild for introduction to systems
    thinking for civilization
  - use concept of positive and negative space in
    architecture to understand specialization: ecological,
    social and economic.
  - second-order cybernetics as a means of understanding
    systems and undestanding understanding because this is
    the framework we will use for building systems code that
    Middle can use to automatic the middle bits.

---

A civilization is a human system so we must first and
foremost understand civilizations using systems thinking, or
systems theory.  It's important to understand that
civilization is not an isolated system, it is simply a layer
that acts as a separate system which is part of local
ecological, global biospheric system which includes hydro and
atmospheric systems build on top of a lithosphere (literally
rock) which is the physical planet, as well the the
heliospheric system (the sun) which which is at the heart of
the solar-system.  The solar system is, in turn part of a
galactic system which on geological timescales directly
impact life on our planet as our sun orbits the galaxy and
at different times is closer or further proximity to other
stellar systems, radiation, gas and matter that our star
passes through.  When our sun has a close brush with another
star, the Oort Clouds of both systems will pass through each
other and we will exchange asteriods, some of which will
become comets.  This has happened many times in the history
of our solar system though we have no idea how many times or
how it has effected us.  The more we can examine objects
from the Oort cloud the more we will learn about these
things.  There is even the possibility that life on earth,
which has been trapped in the ice of a comet could have been
captured by a passing star and seeding life to other solar
systems.  And obviously the reverse could be true as well
and life on earth could have first evolved in another system
that infected us!

how we divide things and increase complexity

*** Systems

systems are made up of different components that are filled
by specialized sub-processes.  The larger the system, the
more it tends to become more complex, by larger processess
to become finer-grained in order to adapt to variations in
the larger territory/population.

A sub process could be a plant or animal in an ecosystem, or
it could be a specialization in a society/civilization.

*** Specializations

Several things happen to specialists -- first, the domain of
a specialist process is called a niche.  If the specialist
that fills that niche dies or the parameters for that niche
change so that the specialist no longer has the ability to
fulfill the needs of that process you get an empty niche
which eventually is filled by a new specialist that evolves
to fill that niche.

when two ecosystems come into contact and effectively merge,
and there are now two different specialists that fill the
same niche, over time, one of the two specialists is found
to be better than the other and takes over that niche.  We
see this over and over in natural history and in societies.

** Meadows Summary

#+begin_quote
*Systems*

  - A system is more than the sum of its parts.
  - Many of the interconnections in systems operate through
    the flow of information.
  - The least obvious part of the system, its function or
    purpose, is often the most crucial determinant of the
    system’s behavior.
  - System structure is the source of system
    behavior. System behavior reveals itself as a series of
    events over time.

*Stocks, Flows, and Dynamic Equilibrium*

  - A stock is the memory of the history of changing flows
    within the system.
  - If the sum of inflows exceeds the sum of outflows, the
    stock level will rise.
  - If the sum of outflows exceeds the sum of inflows, the
    stock level will fall.
  - If the sum of outflows equals the sum of inflows, the
    stock level will not change — it will be held in dynamic
    equilibrium.
  - A stock can be increased by decreasing its outflow rate
    as well as by increasing its inflow rate.
  - Stocks act as delays or buffers or shock absorbers in
    systems.
  - Stocks allow inflows and outflows to be de-coupled and
    inde- pendent.

*Feedback Loops*

  - A feedback loop is a closed chain of causal connections
    from a stock, through a set of decisions or rules or
    physical laws or actions that are dependent on the level
    of the stock, and back again through a flow to change
    the stock.
  - Balancing feedback loops are equilibrating or
    goal-seeking structures in systems and are both sources
    of stability and sources of resistance to change.
  - Reinforcing feedback loops are self-enhancing, leading
    to exponential growth or to runaway collapses over time.
  - The information delivered by a feedback loop—even
    nonphysical feedback—can affect only future behavior; it
    can’t deliver a signal fast enough to correct behavior
    that drove the current feedback.
  - A stock-maintaining balancing feedback loop must have
    its goal set appropriately to compensate for draining or
    inflowing processes that affect that stock. Otherwise,
    the feedback process will fall short of or exceed the
    target for the stock.
  - Systems with similar feedback structures produce similar
    dynamic behaviors.

*Shifting Dominance, Delays, and Oscillations*

  - Complex behaviors of systems often arise as the relative
    strengths of feedback loops shift, causing first one
    loop and then another to dominate behavior.
  - A delay in a balancing feedback loop makes a system
    likely to oscillate.
  - Changing the length of a delay may make a large change
    in the behavior of a system.

*Scenarios and Testing Models*
 
  - System dynamics models explore possible futures and ask
    “what if ” questions.
  - Model utility depends not on whether its driving
    scenarios are realistic (since no one can know that for
    sure), but on whether it responds with a realistic
    pattern of behavior.

*Constraints on Systems*

  - In physical, exponentially growing systems, there must
    be at least one reinforcing loop driving the growth and
    at least one balancing loop constraining the growth,
    because no system can grow forever in a finite
    environment.
  - Nonrenewable resources are stock-limited.
  - Renewable resources are flow-limited.

*Resilience, Self-Organization, and Hierarchy*

  - There are always limits to resilience.
  - Systems need to be managed not only for productivity or
    stability, they also need to be managed for resilience.
  - Systems often have the property of self-organization—the
    ability to structure themselves, to create new
    structure, to learn, diversify, and complexify.
  - Hierarchical systems evolve from the bottom up. The
    purpose of the upper layers of the hierarchy is to serve
    the purposes of the lower layers.

*Source of System Surprises*

  - Many relationships in systems are nonlinear.
  - There are no separate systems. The world is a continuum.
    Where to draw a boundary around a system depends on the
    purpose of the discussion.
  - At any given time, the input that is most important to a
    system is the one that is most limiting.
  - Any physical entity with multiple inputs and outputs is
    surrounded by layers of limits.
  - There always will be limits to growth.
  - A quantity growing exponentially toward a limit reaches
    that limit in a surprisingly short time.
  - When there are long delays in feedback loops, some sort
    of foresight is essential.
  - The bounded rationality of each actor in a system may
    not lead to decisions that further the welfare of the
    system as a whole.

*Mindsets and Models*

  - Everything we think we know about the world is a model.
  - Our models do have a strong congruence with the world.
  - Our models fall far short of representing the real world fully.


— cite:meadows:2009thinking  pg.188-1991
#+end_quote


** References

  - Meadows, D. H., Dancing with systems, The Sustainability
    Institute, (), (2002).
    cite:meadows:2002dancing
  - Meadows, D. H., Leverage points: places to intervene in
    a system, The Sustainability Institute, (), 21 (1999).
    cite:meadows:1999leverage
  - Meadows, D. H., & Wright, D., Thinking in systems: a
    primer (2009), : Earthscan.
    cite:meadows:2009thinking
  - Brand, S., /Pace layering: how complex systems learn and
    keep learning/ (2018).
    cite:brand:2018pace-layering
  - Weinberg, G. M., An introduction to general systems
    thinking (2001), : Dorset House.
    cite:weinberg:2001systems-thinking
  - Baumard, N., Hyafil, A., & Boyer, P., What changed
    during the axial age: cognitive styles or reward
    systems?, Communicative \& integrative biology, 8(5),
    1046657 (2015).
    cite:baumard:2015changed
  - Gell-MannMurray, M., Complexity and complex adaptive
    systems, In , Santa Fe Institute Studies In The Sciences
    Of Complexity-Proceedings (pp. 177–177) (1992). : .
    cite:gell-mann1992complexity-adaptive
  - Gell-Mann, M., Complex adaptive systems, In , Santa Fe
    Institute Studies In The Sciences Of
    Complexity-Proceedings (pp. 11–11) (1994). : .
    cite:gell-mann:1994complex 
  - Wiener, N., Cybernetics, second edition: or the control
    and communication in the animal and the machine
    (1965), : MIT. 
    cite:wiener:1965cybernetics-2nd-ed 
  - Wiener, N., God and golem: a comment on certain points
    where cybernetics impinges on religion (1964), : The
    M.I.T. Press.
    cite:wiener:1964god-golem
  - Wiener, N., The human use of human beings: cybernetics
    and society (1989), : Free Assciation Books.
    cite:wiener:1989human
  - Engelbart, D. C., Augmenting human intellect: a
    conceptual framework (1962), : Stanford Research
    Institute.
    cite:engelbart:1962augmenting
  - M\"uller, K, The new science of cybernetics: a primer,
    Journal of Systemics, Cybernetics and Informatics,
    11(9), 32–46 (2013). 
    cite:muller2013new
  - Foerster, H. V., Understanding understanding: essays on
    cybernetics and cognition (2002), : Springer.
    cite:foerster:2002understanding

  - Bateson, M. C., /How to be a systems thinker: a
    conversation with mary catherine bateson/ (2018).
    cite:bateson:2018how-systems-thinker
