#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 1. Metis > Episteme Abstract 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]


* 1. Metis > Episteme Abstract
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/01/abstract.org
:Created:  2018-05-22T19:40@Prek Leap (11.642600N-104.919210W)
:ID:       23459d70-e1b3-4388-88e7-e48f2f50dcf4
:VER:      580264916.186497697
:GEO:      48P-491193-1287029-15
:BXID:     proj:IHD1-4121
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope

Metis is a complex concept, but can crudely be understood as
a local map of a place, but also the people, landscape,
history and the complexity of human relationships in that
place.  These maps tend to be accurate but, illegible to
anyone outside of the community that shares it.   Metis is
small because it is a detailed and complex map of complexity.
The brain can only keep so much information in play at any
given time, so we employ transactive memory in local
communities, where collective memory is organically kept
alive by having different people remember different things.
Sort of like a organic cultural version of Fahrenheit 451.
Part of that map is how to tap into the collective memory
and know which people know what things.  This is largely
impossible for an outsider.  And since the local map is
intinimately tied to the local, it takes a lifetime to learn
and maintain.

Episteme is a little more straightforward concept of using
data derived from rational and empirical observation to
create simplified maps that are codified into paradigms.  A
peradigm is similar to episteme except it is a formalized
framework for understanding something that can be tested
against.  The data is more often than not, very incomplete
because it has only been collected for a short period.  This
is in contrast to metis which is built on generations of
observation.  The difference between metis and episteme is
that metis is concerned with how things work and the process
of knowing how to do things where episteme is concerned with
why things work and refining what is found to understand new
things.  Episteme is meant to be global, no tied to a
specific locality and context so the only way to make it
legible, is through simplication.  Simplified models
identify patterns in complexity that are intelligible.
Stack enough of these patterns together into a
interconnected framework and you get a model of something.
At this point, the data melts away and you are left with
what can be a thought of rational version of metis, a
paradigm.  This isn't something you can understand by
reading a description, or even a book or two on the subject.
In order to work within the paradigm you must master the
patterns through repitition, not simply memorize a list of
facts and rules.  It's only after you have looked at the
same thing from many different perspectives and done the
experiments and the equations yourself does the paradigm
become a part of you, which again, is a kind of metis where
the transactive collective memory is spread among practicing
scientists as well as in monographs, interviews, notes,
correspondance and books.  A scientific paradigm is meant to
be an externalized metis.  As students you are constantly
reminded that something is not an experiment unless it has
been recorded and published.  In science if an observation
has been recorded, it doesn't exist.

The problem with episteme is that it is an impoverished map,
that trades rich complexity that fulfills a broad spectrum
of human physical, economic and psychological needs with far
more simple map that can be used almost anywhere and opens
up a larger world that local metis can not provide.

Many believe that the local and global are mutually
exclusive and are polar opposites that can not be
reconciled.  But this does not need to be true.  Episteme
has only been around since the Enlightenment, and science
has been practiced by a very select few up until even a few
decades ago.  An eternalized episteme that centers arond
different paradigms that have had time to mature and reach a
level of complexity that can match local metis will
eventually evolve.  As Lou Keep mentioned, the monumental
failures of high modernism that Scott gives in /Seeing Like
a State/ are all of young sciences.  It is only recently
that complexity and that scientific paradigms have become to
cross disciplinary lines.

The problem is, that specialization in the sciences which
then became sub-specialties of spealties made it possible
for individuals to keep a paradigm loaded in their heads but
left the larger body of knowledge fragmented so that no one
had the big picture of how it all fit together. This is
starting to change, but has a long ways to go.

The advantage of local metis is that the whole thing can fit
in each person's head, it's a whole, rather than a bunch of
disconnected fragments.

The whole point of local metis is that it is transactive and
human scale.  Science needs to move from a patchwork of
disciplines to merge all specialties into a more
comprehensive paradigms and then employ a more serviceable
form of transactive memory than the monograph.

Every metis has a:

  - territory
  - transactive community
  - paradigm
  - vocabulary & grammar
  - mythos & origin story

In the w&w introduction I talk of reconciling local metis
with global metis, but now I'm starting to think that this
is almost a side effect, and that the real advantage to an
global metis is being able to take control of the paradigms
we live in.  Local metis is not consciously constructed or
designed, it emerges from the local complexity.  In a sense
you are trapped in it, it can only change very slowly over
generations and it is not transferable to other places.

An epistemic metis is all about intentionally finding
holes in the existing paradigm and then when the holes are
big enough to see through you can begin to see the next
paradigm that will replace it.  Then repeat the process.

In large part Alexandar was trying to develop a grammar that
people from our simplistic epistic metis could use to create
their own local metis, but high modernism striped people of
the ability to understand the idea of local metis, they
no longer recognize what they are estranged from and why
they are so miserable.

** TL;DR

 - rules>paradigm  cite:keep:2018science-high-modernism
   cite:keep:2017rationional-animal
   concrete>abtract

   start with list of observations
   then list of rules
   a perfect rule system is never created
   then a theory that everyone get's behind which becomes a
   paradigm

   when anomolies in the paradigm become too much and people
   are reduced to frantic rule-based theorizing

   if what we are trying in w&w is to describe a paradigm,
   with no rules, then we must do so by laboriously
   exhaustively go through examples that eventually explain
   the paradigm

   this creates models and results that can be tested
   against, not theory

   then go into case-law

   and finally the problem of making our new paradigm
   machine understandable  --- fuck me....
   -- I think that it boils down to algorthms for matching
   patterns rather than logical step-wise rules.

   Alexander uses patterns as a way of describing a
   paradigm, but few people really /got it/ because his
   paradigm hadn't been accepted by the community he was
   trying to convince -- mostly because they didn't engage
   with him.  

   This is an imporant lession -- if you can't people to
   engage in your paradigm you are fucked and will be
   forgotten.

   Nature of Order was an attempt to correct this, but came
   off as a list of rules that should have been the
   precursor to APL -- it didn't work either, but laid the
   groundwork for a much deeper and substantial paradigm
   which he could only partially articulate.

   Mollison's back-of-book outline for a new civilization is
   given as a list of rules -- he had already done an
   excellent job teaching the permaculture paradigm as
   patterns and examples, the end of the book was just a
   starting point for what I'm doing and what will have to
   be done by others who come after me.

   Perhaps if APL was vastly expanded so that each pattern
   had an exhaustive list of examples showing what almost
   works and what works and how others fail when trying to
   use the pattern would have made it more useful than
   Nature of Order --  Nature of Order moved is almost an
   entirely different paradigm from APL -- is APL metis?

   Soleri gave us a paradigm with little to no map to
   understand it, let alone test against it.

   I think this is where Engelbart fell down as well -- he
   was too far ahead of everyone that they couldn't
   understand how to engage, let alone test against --
   Engelbart took the Bush essay and built a framework to
   build it in the 20th century using networked computers --
   it just completely went over people's heads and still
   does today....


#+begin_quote 
Though history is unlikely to record their names, some men
have undoubtedly been driven to desert science because of
their inability to tolerate crisis. Like artists, creative
scientists must occasionally be able to live in a world out
of joint—elsewhere I have described that necessity as “the
essential tension” implicit in scientific research.

— kuhn
#+end_quote


