#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 1. Metis > Episteme Introduction 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 1. Metis > Episteme Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/01/intro.org
:Created:  2018-05-22T19:41@Prek Leap (11.642600N-104.919210W)
:ID:       dd8a9a7c-8ff6-43c6-8501-ee370f6bed41
:VER:      580264970.855289854
:GEO:      48P-491193-1287029-15
:BXID:     proj:JSR8-4465
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scopic Terminology

We need to get our jargon straight here because we're going
to be using terms used by different authors and from
different fields that are often a very close fit to how
we use it, but is still different because the paradigm we
are using has a different scope, from a specialized POV with
different LOD, ROC, LOA, LOC and

  - episteme            : 
  - metis               : 
  - local               : 
  - global              : 
  - local metis         : 
  - global metis        : 
  - scientific paradigm : kuhn
  - paradigm            : 
  - epiphenomenom       : colateral side effects (loopholes?) 
  - territory           :
  - legibility          : comprehensible, measurable,
                          synoptically mappable (Scott)
  - context             :
  - cardinal persepctives

** Learning a Paradigm

Something that Big History teachers need to better
articulate when you learn something from a historical
perspective, by understanding the prior work that the
present state of the art is built on, it is not just to make
work for the students.  This because you are learning a
paradigm which is made as much by implicit rules as explicit
rules.

#+begin_quote
Scientists, it should already be clear, never learn concepts, laws, and
theories in the abstract and by themselves. Instead, these intellectual
tools are from the start encountered in a historically and pedagogically
prior unit that displays them with and through their applications. A new
theory is always announced together with applications to some concrete
range of natural phenomena...

-- cite:kuhn:1970sci-revolutions [[pdfview:~/proj/chenla/hoard/lib/kuhn:1970sci-revolutions.pdf::58][p.46]]
#+end_quote

In a very real sense a teacher is introducing not only the
scientific concept, fact, or law, but the larger paradigm it
is part of and the enough of the paradigms that preceeded
it.  You need to have a firm grasp of Newtonian Physics
before you can understand Einsteinian Relativity which is
needed to understand Bohr's Quantum mechanics.  Everything
is built on top of the other and many things you will
encounter in Quantum mehanics assume fluency in Newtonian
Physics.  And teaching the biographical details about the
the people behinds these paradigms and the story of how
these discoveries took place creates a narrative structure
that provides us a way of anchoring and reinforcing these
concepts both cognitively and in our memories.

But this not only applies to the sciences, 

indeed, it could be argued this is what history is filling
in the assumptions that weree known but not said, that are
inherited from our ancestors.  This establishes a causal
chain that is much larger than the sum of it's parts.  The
more you learn and internalize this causal chain the deeper
your understanding of the present.  This is what metis
really is, this long causal chain of generations building
layers of assumptions about the world that are built on top
of those who came before us.  Any form of metis, local, or
global depends on the learner to not only hear or read about
this causal chain, but to experience it through repeated
exposure, exercises, practice until it is mastered, which is
to say that it has been woven into your internal world model
to the point where it can be accessed underneath conscious
proccessed.  This is how we cheap the small amount of
working memory that our brains provide us.  Metis is not
conscious it is as deeply embeded into our cognitive
processes on a level that approaches instinctual.  Such
habituated memory is a reprogramable extension of the limbic
system provided by the cerebral cortex, which we share with
all other mammals.

The amount of information that is stored in local metis
likely approaches the natural limits.  A cultural mythos
which is made up of an oral tradition of stories provide the
same cognitive framework that are used to teach the sciences
and pass them from one generation to the next.  But oral
traditions are prone to copying errors which result in
limiting the size of the territory that a local metis can
cover.  The more that something is copied and passed on to
someone else the more cumulitive errors are introduced into
the message.  This is the primary limiting factor in how
large a community both in terms of population and physical
area can be.  Within that threshold, the copying errors are
corrected and changes slowly over generations.  Once you
have passed beyond that territorial threshold copying errors
are compounded and evolve into something altogether
different.

Anyone who has played the game /Chinese whispers/ (known as
/telephone/ in the United States) has experienced this.
Players form a circle, and the first player whispers a
message to the ear of the person next to them. The next
person repeats the message to the next person and so on
until the circle has been complete.  The last person
announces the message to the group and compares it to the
original message by the first person.  Invariably the two
messages are wildly different.

A few culturals developed means of extending those limits of
an oral tradition to span territories which today would be
considered nation-states.  Eric Havelock's theory that epic
narratives such as the works of Homer, which were originally
part of the oral tradition comprised a cultural encyclopedia
that was mnemonically encoded in verse in a way, that when
accompanied by a musical instrument such as a harp, could
virtually eliminate copying errors between generations.  The
Hindu xxx is still passed down the same way.  This greatly
extended the territory that local metis could encompass.
This extended the range of local metis but was pushing the
limits that the oral tradition could be extended.

These techniques required a great deal of coordination, time
and practice.  They are the Oral equivilent of the Clipper
ship, which was the short liced technological pinnacle for
long distance sail boats.  Such technicalogical achievements
are typically at the end of a paradigm's lifespan.  Steam
power was in development before the first Clippers were
built.  Soon after the Clippers were introduced steam
powered ships became feasible and soon after practical and
the era of trans ocean sailing was over.

The invention of writing systems put an end to the
techniques the Greeks and Hindus used to extend metis and
were replaced by written transcriptions of these texts and
paved the way 


Writing systems externalized metis


** References

- Scott, J. C., Seeing like a state: how certain schemes to
  improve the human condition have failed (1998), : Yale
  University Press.
  cite:scott:1998seeing
- Kuhn, T. S., The structure of scientific revolutions: 50th
  anniversary edition (2012), : The University of Chicago
  Press.
  cite:kuhn:2012sci-revolutions
- Alexander, S., /Book review: seeing like a state/ (2017).
  cite:alexander:2017seeing-state-review 
- Rao, V., /A Big Little Idea Called Legibility/ (2010).
  cite:rao:2010big-little-idea 
- Scott, J. C., /The trouble with the view from above/ (2010).
  cite:scott:2010trouble 
- Keep, L., /Man as a rationalist animal/ (2017).
  cite:keep:2017rationional-animal 
- Keep, L., /Science Under High Modernism/ (2018).
  cite:keep:2018science-high-modernism 
