#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 1. Metis > Episteme Introduction 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* 1. Metis > Episteme Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/01/01/intro.org
:Created:  2018-05-22T19:41@Prek Leap (11.642600N-104.919210W)
:ID:       dd8a9a7c-8ff6-43c6-8501-ee370f6bed41
:VER:      580264970.855289854
:GEO:      48P-491193-1287029-15
:BXID:     proj:JSR8-4465
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scopic Terminology

We need to get our jargon straight here because we're going
to be using terms used by different authors and from
different fields that are often a very close fit to how
we use it, but is still different because the paradigm we
are using has a different scope, from a specialized POV with
different LOD, ROC, LOA, LOC and

  - episteme            : 
  - metis               : 
  - local               : 
  - global              : 
  - local metis         : 
  - global metis        : 
  - scientific paradigm : kuhn
  - paradigm            : 
  - epiphenomenom       : colateral side effects (loopholes?) 
  - territory           :
  - legibility          : comprehensible, measurable,
                          synoptically mappable (Scott)
  - context             :
  - cardinal persepctives

** Learning a Paradigm

Something that Big History teachers need to better
articulate when you learn something from a historical
perspective, by understanding the prior work that the
present state of the art is built on, it is not just to make
work for the students.  This is because you are learning a
paradigm which is made as much by implicit rules as explicit
rules.

#+begin_quote
Scientists, it should already be clear, never learn
concepts, laws, and theories in the abstract and by
themselves. Instead, these intellectual tools are from the
start encountered in a historically and pedagogically prior
unit that displays them with and through their
applications. A new theory is always announced together with
applications to some concrete range of natural phenomena...

-- cite:kuhn:1970sci-revolutions [[pdfview:~/proj/chenla/hoard/lib/kuhn:1970sci-revolutions.pdf::58][p.46]]
#+end_quote

In a very real sense a teacher is introducing not only the
scientific concept, fact, or law, but the larger paradigm it
is part of and the enough of the paradigms that preceeded
it.  You need to have a firm grasp of Newtonian Physics
before you can understand Einsteinian Relativity which is
needed to understand Bohr's Quantum mechanics.  Everything
is built on top of the other and many things you will
encounter in Quantum mehanics assume fluency in Newtonian
Physics.  And teaching the biographical details about the
the people behinds these paradigms and the story of how
these discoveries took place creates a narrative structure
that provides us a way of anchoring and reinforcing these
concepts both cognitively and in our memories.

But this not only applies to the sciences, 

indeed, it could be argued this is what history is filling
in the assumptions that weree known but not said, that are
inherited from our ancestors.  This establishes a causal
chain that is much larger than the sum of it's parts.  The
more you learn and internalize this causal chain the deeper
your understanding of the present.  This is what metis
really is, this long causal chain of generations building
layers of assumptions about the world that are built on top
of those who came before us.  Any form of metis, local, or
global depends on the learner to not only hear or read about
this causal chain, but to experience it through repeated
exposure, exercises, practice until it is mastered, which is
to say that it has been woven into your internal world model
to the point where it can be accessed underneath conscious
proccessed.  This is how we cheap the small amount of
working memory that our brains provide us.  Metis is not
conscious it is as deeply embeded into our cognitive
processes on a level that approaches instinctual.  Such
habituated memory is a reprogramable extension of the limbic
system provided by the cerebral cortex, which we share with
all other mammals.

-------

The amount of information that is stored in local metis
likely approaches the natural limits.  A cultural mythos
which is made up of an oral tradition of stories provide the
same cognitive framework that are used to teach the sciences
and pass them from one generation to the next.  But oral
traditions are prone to copying errors which result in
limiting the size of the territory that a local metis can
cover.  The more that something is copied and passed on to
someone else the more cumulitive errors are introduced into
the message.  This is the primary limiting factor in how
large a community both in terms of population and physical
area can be.  Within that threshold, the copying errors are
corrected and changes slowly over generations.  Once you
have passed beyond that territorial threshold copying errors
are compounded and evolve into something altogether
different.

Anyone who has played the game /Chinese whispers/ (known as
/telephone/ in the United States) has experienced this.
Players form a circle, and the first player whispers a
message to the ear of the person next to them. The next
person repeats the message to the next person and so on
until the circle has been complete.  The last person
announces the message to the group and compares it to the
original message by the first person.  Invariably the two
messages are wildly different.

A few culture developed means of extending the limits of
the oral tradition to span territories which today would be
considered nation-states.  Eric Havelock's theory that epic
narratives such as the works of Homer, which were originally
part of the oral tradition comprised a cultural encyclopedia
that was mnemonically encoded in verse in a way, that when
accompanied by a musical instrument such as a harp, could
virtually eliminate copying errors between generations.  The
Hindu xxx is still passed down the same way.  This greatly
extended the territory that local metis could encompass.
This extended the range of local metis but was pushing the
limits that the oral tradition could be extended.

These techniques required a great deal of coordination, time
and practice.  They are the Oral equivilent of the Clipper
ship, which was the short liced technological pinnacle for
long distance sail boats.  Such technicalogical achievements
are typically at the end of a paradigm's lifespan.  Steam
power was in development before the first Clippers were
built.  Soon after the Clippers were introduced steam
powered ships became feasible and soon after practical and
the era of trans ocean sailing was over.

The invention of writing systems put an end to the
techniques the Greeks and Hindus used to extend metis and
were replaced by written transcriptions of these texts and
made it possible to increase the number of narratives so
that the cultural encyclopedia expanded into a cultural
library.  

The new system also had built in limits as well.  Making
physical copies was expensive.  The early media used to make
copies included clay, stone, metal and even wax.  But these
were impractical for long texts and in the case of wax were
too impermanent.  Papyrus, a writing material made from the
papyrus plant, /Cyperus papyrus/ solved many of these
problems and was cheap and easy to produce but was fragile
and tended to crack when rolled into scrolls.  The invention
of the codex which bound cut sheets of writing material
helped but not much.  Papyrus was displaced by was
parchment, a writing material prepared from untanned skins
of sheep calves and goats.

Copies were made by making copies by hand and required great
skill, time and patience.  Even the best copies introduced
copying errors.  Taken together this limited number of
copies, and the number of people who could access them.
Writing became the domain of a small educated elite, the
clergy, the governing class and some of the mechant classes.
Everyone else was remained within a local oral tradition
that was part of a network of literate elites who
synchronized regional metis to local groups.

This only changed in xxxx with Gutenberg's press that used
moveable type to make exact copies on much cheaper and
easily produced paper, made from pressed vegitable fibers

This made it possible to make mass numbers of exact copies.
This eventually spread literacy down to working classes
which made it possible to fuel the industrial revolution
which required workers with at least remedial literacy and
numeracy skills.

Up until this point, writing systems were little more than
much betters forms of the Greek epic narratives.  They
extended local metis so that many local metis could form
larger sized units of polity that became the state and
eventually the modern nation-state system.  Gradually, local
metis, which was becoming increasingly out of sync with the
ever expanding but simplified global metis.  The industrial
revolution physically uprooted people, broke up families and
moved individuals to distant metropolitan areas where the
factories were.  This process is still going on in much of
the world.  And in every case it has resulted in an
estrangement between the local and the new global.  Those
who had made the move from the rural to the metropolitan
needed to change and broaden their worldview to survive in
their new circumstances.

This transition is perhaps best seen in Charles Dicken's
novella, /A Christmas Carol/ which single handedly
established the modern traditional of Christmas in the
industrial age.  The Bob Cratchet, the protagonist in the
story is the head of an industrial metropolitan nuclear
family.  There is no mention of grandparents or ancestrial
villages.  When the antagonist (who transforms into the
protagonist at the end of the story) is given a tour of
present day christmas celebrations by the Ghost of Christmas
Present Scrooge is shown middle class couples celebrating
Christmas at home, it showed people isolated in ships at
sea, but nowhere did it show extended families or past
generations.  That was gone, part of a past that was already
fading when Scrooge was a yound apprentice working away from
home.  This vestige of the past was clearly shown to be an
exitinct part of the past, as it was shown as a shadow of
the past by the Ghost of Christmas Past.  The marvelous
christmas party thrown each year for his staff by the
merchant Fezziwig echoed the old Yule Tide manoral festivals
that were the precursors to the Dickens' modern version of
the holiday.  Another past Christmas showed Scrooge spending
the holiday alone at school, while all of his classmates had
gone home to celebrate with his family.  The story comprises
a cultural encyclopedia for and industrial-era culture build
around the nuclear family.

This marked a new kind of global metis, that was more
universal, but at the same time more simple and impovershed
in comparison to traditional rural metis.  In large part
this is because the new industrial metis was not built on
top of anything that came before it.  It was a brutal
dislocation and reductionist subset of human social
interaction, community and needs.  This represented a rift,
and an estrangement of modern man from the world around him
that we are still living with today.  A hundred fifty years
is a very brief period of time to build a culture that has
no past.  This has been compounded by the problem that the
new industrial metis had no scope -- there was seemingly no
end to it.  Human's need psychological borders, a proscribed
space around them where they feel belong, are accepted and
can expect support and reciprocity from those around them.

Industrial metis had little of that, only the workplace, the
State and the tiny vulnerable island that comprised the
nuclear family.  Even that small island couldn't withstand
and in developed countries is in the process of fragmenting
down to lone individuals.  This is clearly a crappy
existence.  States have become too large for people to have
any connection to themselves as individuals, and so state
services that provide social saftey nets that used to
replace rural local communities feel impersonal, uncaring
and souless.  The architecture of the state projects power,
authority, and control but not agency, empathy,
inclusiveness and safety.

We need to find ways or restablishing these things in our
lives.  The state can not do this.  Religion has provided
something of this, but the ideological and dogmatic overlay
they provide to connect us together is impossible to
reconcile with the empirical world around us.  Their maps
are too far out of sync with the world as it is.  The
worldwide trend is away from organized religions and it's
nearly certainly is not going to reverse.  There is no going
back, and few people would even if they could.  The larger
post-industrial world has too many things going for it that
older modes of living and community could not provide.  So
we must go forward, to find ways to heal the rift between
those of us on the planet who are sitll living in various
stages of older manifestations of local metis.  Next, we
need a way of unboarding people from the old into the
new. There are still literally billions of people on the
planet who have not made the transition and the process
doesn't have to be a brutal and dehumanizing as it is today.
Finally, for those of us who have already made the
transition from rural to metropolitan, and to the growing
population who are moving from metropolitan to cosmopolitan
we need to humanize industrial metis.  This means giving
people local agency and control over their lives, not
distant uncaring institutional cookie-cutter services that
are provided today.  We need to move away from industrial
educational systems that prepare people for a life of
servitude and monotonous repetitive work on the assembly
line and office cubicles and give the cognitive tools to
think, evaluate information and not be manipulated by
others.  And finally we need to create the post-industrial
equivilant to rural living environments where people can
live at human scales that makes us feel secure, healthy,
accepted and in control of our lives and the time we have on
this planet.


** References

- Scott, J. C., Seeing like a state: how certain schemes to
  improve the human condition have failed (1998), : Yale
  University Press.
  cite:scott:1998seeing
- Kuhn, T. S., The structure of scientific revolutions: 50th
  anniversary edition (2012), : The University of Chicago
  Press.
  cite:kuhn:2012sci-revolutions 
- Kuhn, T. S., The structure of scientific revolutions
  (1970), : The University of Chicago Press.
  cite:kuhn:1970sci-revolutions
- Alexander, S., /Book review: seeing like a state/ (2017).
  cite:alexander:2017seeing-state-review 
- Rao, V., /A Big Little Idea Called Legibility/ (2010).
  cite:rao:2010big-little-idea 
- Scott, J. C., /The trouble with the view from above/ (2010).
  cite:scott:2010trouble 
- Keep, L., /Man as a rationalist animal/ (2017).
  cite:keep:2017rationional-animal 
- Keep, L., /Science Under High Modernism/ (2018).
  cite:keep:2018science-high-modernism 

- Masterman, M., The nature of a paradigm, In (Eds.),
  Criticism and the Growth of Knowledge (pp. 59–89)
  (1970). : Cambridge University Press.
  cite:margaret:1970nature
- Lakatos, I., & Musgrave, A., Criticism and the growth of
  knowledge (1970), : Cambridge University Press.
  cite:lakatos:1970criticism-growth
- Kuhn, T. S., Second thoughts on paradigms, The structure
  of scientific theories, 2(), 459–482 (1974).
  cite:kuhn:1974second
- Galison, P., Image and logic: a material culture of
  microphysics (1997), : University of Chicago Press.
  cite:galison:1997image-logic 

