#   -*- mode: org; fill-column: 60 -*-

#+TITLE: 5. Succession Abstract 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]


* 5. Succession Abstract
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/04/05/abstract.org
:Created:  2018-05-18T09:23@Prek Leap (11.642600N-104.919210W)
:ID:       73eebcd9-85ad-4c31-8441-d06e7fc9876c
:VER:      579882254.599156362
:GEO:      48P-491193-1287029-15
:BXID:     proj:JMJ2-3164
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

** Scope
This chapter describes what succession models are and how
they work.

---

The principle is that if the conditions are right,
self-organizing systems tend to go from lesser to greater
complexity.

There are limits to complexity imposed by the size of the
carrying capacity.

Increasing complexity can extend carrying capacity.

When complexity can no longer increase carrying capacity,
systems collapse and revert to lower levels of complexity,
which creates opportunities for increasing complexity again.
This is often cyclical and has been seen repeatedly from
major extinction events on earth, to the collapse of complex
societies.  The tendency is, that after a collapse, the new
system that emerges from the ashes has "learned" from it's
previous mistakes and is replaced by a more robust and even
more complex system -- so that the system is cyclical in
nature, but is also iterative and increases in complexity
with each new cycle.

The most dramatic of these cycles in in major extinction
events.

** TL;DR

** References


