#   -*- mode: org; fill-column: 60 -*-

#+TITLE: XIV. Economy Introduction
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../index.org][top]]] [[[./index.org][up]]]

* XIV. Economy Introduction
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/warp/14/intro.org
:Created:  2018-04-29T17:21@Prek Leap (11.642600N-104.919210W)
:ID:       f79d80a5-4060-4e2a-b60a-fcc7e90a55e7
:VER:      578269330.325224032
:GEO:      48P-491193-1287029-15
:BXID:     proj:BVD2-8622
:Class:    primer
:Type:     work
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

No where is the distinction between quantitative and
qualitative more clear than in the field of economics.

Economic's domain used to be relatively narrow 

#+begin_quote
Economics is a study of man in the ordinary business of
life. It enquires how he gets his income and how he uses
it. Thus, it is on the one side, the study of wealth and on
the other and more important side, a part of the study of
man.

— Lionel Robbins (1932)
  cite:backhouse:2009retrospectives  
#+end_quote

But this rapidly changed until pretty much everything in
human society came to be seen in economic terms,

till today, anything that can not be treated as private
property is ignored, it no longer exists.  This is
especially true of the climate.  Climate is not included in
economic consideration because it can't be bought or sold on
the open market.  The remarkable thing is, Cap and Trade is
exactly that, turning the atmosphere and climate into a
commodity that can be traded, bought and sold.  That
greenhouse gasses and potentially any kind of pollutant that
threatens life is a commodity.  The absurdity of such a
thing is lost on us.  We can no longer see things any other
way.  


#+begin_quote
Economics, moreover, deals with goods in accordance with
their market valué and not in accordance with what they
really are. The same rules and criteria are applied to
primary goods, which man has to win from nature, and
secondary goods, which presuppose the existence of primary
goods and are manufactured from them. All goods are treated
the same, because ths point of view is fundamentally that of
prívate profit-making, and this means that it is inherent in
the methodology of economics to ignore man's /dependence on
the natural world/.

Another way of stating this is to say that economics deals
with goods and services from the point of view of the
market, where willing buyer meets willing seller. The buyer
is essentially a bargain hunter; he is not concemed with the
origin of the goods or the conditions under which they have
been produced. His sole concern is to obtain the best valué
for his money.

The market therefore represents only the surface of society
and its significance relates to the momentary situation as
it exists there and then. There is no probing into the
depths of things, into the natural or social facts that lie
behind them. In a sense, the market is the
institutionalisation of individualism and
non-responsibility. Neither buyer ñor seller is responsible
for anything but himself.

— cite:schumacher:1975small [[pdf:schumacher:1975small.pdf::44][p.43]]
#+end_quote

Schumacher notes the one exception to that
non-responsibility which is not to buy stolen goods because
this would threaten the system.  In the same way, anything
that threatens the principle that everything is property and
can be bought and sold is a threat to the system.  Even
human life is a commidity in market economics, which becomes
painfully clear when dealing with insurance claims, or when
taking someone to court for injuring or killing someone.
Courts place monetary values to people according to their
age, gender and wealth relative to others.

#+begin_quote
It's like this. A dead plaintiff is rarely worth as much as
a living, severely-maimed plaintiff. However, if it's a long
slow agonizing death, as opposed to a quick drowning or car
wreck, the value can rise considerably. A dead adult in his
20s is generally worth less than one who is middle aged. A
dead woman less than a dead man. A single adult less than
one who's married. Black less than white. Poor less than
rich. The perfect victim is a white male professional, 40
years old, at the height of his earning power, struck down
in his prime. And the most imperfect? Well, in the calculus
of personal injury law, a dead child is worth the least of
all.

— Jan Schlichtmann, A Civil Action (1998)
  https://www.imdb.com/title/tt0120633/quotes/?tab=qt&ref_=tt_trv_qu
#+end_quote

Though most of us prefer not to believe it, yes, it really
is that bad.  Human life, let alone human well-being or
happiness is subjugated to the sanctity of private property.
If that doesn't bother you, then there is something very
wrong.  That's now how we raltionalize it.  Of course that
doesn't apply to ourselves or our family and children. It
only applies /other/ people, and even then only when in the
context of business or civil court proceedings.  But this
argument doesn't hold up to scrutiny.  You think it doesn't
apply to you or /your/ family, but from from another person
or business or court's perspective it /does/ apply to you.
Our modern market-based system is based on the belief that
everything, including human life, has a monetary value and
therefore is considered to be property.  Nothing is
/priceless/ in this system, everything has a value and can
be bought and sold. /Everything/ is property.

#+begin_quote
In the market place, for practical reasons, innumerable
qualitative distinctions which are of vital importance for
man and society are suppressed; they are not allowed to
surface.  Thus the reign of quantity celebrates its greatest
triumphs in "The Market." Everything is equated with
everything else. To equate things means to give them a price
and thus to make them exchangeable. To the extent that
economic thinking is based on the market, it takes the
sacredness out of life, because there can be nothing sacred
in something that has a price.  Not surprisingly, therefore,
if economic thinking pervades the whole of society, even
simple non-economic values like beauty, health, or
cleanliness can survive only if they prove to be "economic."

— cite:schumacher:1975small [[pdf:schumacher:1975small.pdf::53][p.45]]
#+end_quote




#+begin_comment
I'm hesitating to commit to this outline because the model
that is emerging is bluring the line between private and
public sectors -- private is becoming more public and public
more private.  If the private sector falls under the same
rules and the public, and the governance mechanisms are
distributed so that power naturally propagates to the edge
rather than collect into pools at the center.

If so, an economy that is close to what we have today will
not be the same over time.

Part of the reason in a free-market based economy that
government is so big is that there are so many things that a
free-market doesn't do well.  Without a profit motive
free-markets won't do anything.  And if you try to turn
public sector functions you get mixed results because many
things have to be done without trying to make a profit.
This then becomes a distribution problem as much as anything
else.

---

Was just scanning through all of the different economic
models that have been tried or proposed, and I find it
striking that they are almost all completely top town, and
based on clear and simple rules that don't leave much room
when things go wrong, or, like anarchism and
market-captialism are completely free of rules and are based
on the belief that economic systems are self-organizing and
regulating.  There isn't a lot of creative thinking going on
here.  Their models of human nature, limitations and
cognitive bias are equally simplistic.  I suspect that they
mostly assume that these models can scale to any size, and
that different models might work at specific scales and
their corresponding level of complexity but not at smaller
or greater scales.

Regulated Capitalism is sort of the best of the worst
because it is based on a flexible bottom-up model that can
adapt to chaotic unpredictible systems.  But it is also
requires large bureaucratic infrastructure and state-owned
services which can fill in the gaps that markets are not
good at filling. 

There are bits and pieces in most of the systems that are
worth adapting and incorporating.

So let's start by coming up with a basic list of things that
people seem to require because of the ecolological niche we
were designed to fill.

We can only keep a limited number of things in our heads at
one time, two is fine, three is pushing it, more than that
is impossible without using some kind of system like writing
to store more items so we can load and unload different
parts of the problem and work towards a solution that would
otherwise be impossible.  This places a limit on how many
relationships we can maintain with other people.  Above
these limits such as Dunbar's number, things break down.
We're not good at scaling, except for brief periods for an
event, festival, or to accomplish a group activity like
seasonal Mastadon or caribou hunts.  During such events,
resources are plentiful and there is less competitive
pressure between people.  But it doesn't last long, and if
we don't disband and move away from each other things fall
apart.  Our inability to keep more than a few things in our
working memory at a time also limits how much we can
cooperate and how abstract trading resources can become
without externalizing them.

We are pack animals which naturally create hierarchies
within groups -- leaders, followers etc.  We leverage our
large cerebral cortex so that we use a transactional system
so that different members maintain different specialized
knowledge.

We are territorial, we establish territories as individuals
and as groups.  This leads to conflict when more than one
group is competing for the same resources.  This problem was
compounded by the agracultural revolution because our
territories became fixed an inflexible.

We instinctively collect more than we need as a buffer for
when resources are scarce.  Like squirels saving nuts for
the winter.  That instinct leads to hoarding and greed at
the expense of others in the group or other groups.

We are not good at planning for time scales larger than
human life times.  We have sometimes managed to create
systems that can be passed down to many generations which
are stable, but the actions and decsions are still short
term and within living memory.  We feel strong connection to
our grand parents and on the other side, our grandchildren,
but not much farther in the past or into the future.

So some forms of property seem to be unavoidable, but
property can be owned indivudally or collectively.  So long
as people feel in control of the property that they interact
with, even if it is for short periods of time, we seem to do
okay.

Currencies seem to be unavoidable, but because they are
universal tokens that can be used to obtain any kind of
resource they are naturally hoarded.  Is it possible to
build currency systems that, when combined with group
ownership and other feedback systems that ensure that
hoarding is not needed because there is no danger of
scarcity?

Nomadic cultures keep posessions to a minimum, and feel more
secure in some respects because they know that if resources
are scarce in one place they can go somewhere else to find
them.  Sedantary pastorial agricultural cultures that later
concentrate into cities are stuck where they are, and can't
move when resources are scarce so stocks are the only way to
compensate for that.  Nomadic cultures are based around
flows.

Man seems to be designed to be a little of both, no one or
the other.  We like to stay put when things are comfortable
and plentiful, but get bored if we stay for too long and end
up fighting with each other.  Routines which are too regular
and are continued too long are not healthy.  One good thing
about pastorial agrictulture and nomads is that seasons
bring variety of diet and activities.  Industrial
civilization has made everything available everywhere year
round -- this is not healthy.

#+end_comment


An economy cuts a pretty broad swath of a civilization:

#+begin_quote
An economy is an area of the production, distribution, or
trade, and consumption of goods and services by different
agents. Understood in its broadest sense, 'The economy is
defined as a social domain that emphasizes the practices,
discourses, and material expressions associated with the
production, use, and management of resources.

....

A given economy is the result of a set of processes that
involves its culture, values, education, technological
evolution, history, social organization, political structure
and legal systems, as well as its geography, natural
resource endowment, and ecology, as main factors. These
factors give context, content, and set the conditions and
parameters in which an economy functions. In other words,
the economic domain is a social domain of human practices
and transactions. It does not stand alone.

-- Economy | Wikipedia
   https://en.wikipedia.org/wiki/Economy
#+end_quote

Different kinds of economies achieve this in different ways.
Market economies use barter or a medium of exchange (money)
to achieve this according to supply and demand.  The
assumption is, that if there is a need for something,
someone will find a way of filling that need through
production of goods and services.  All in all this system is
messy and leaves a great deal of room for abuse, but is
better than the alternatives because it is at base, a bottom
up approach where the purpose of production is to meet
needs.  In a command-based an authority (usually political)
controls how things are produced and distributed.  Because
of the complexity of even fairly small economies, it is for
all all intents and purposes impossible to anticipate needs,
plan production and coordinate distribution anywhere close
to as well as market-based economies can do.  This doesn't
mean that market-economies are perfect, far from it, but to
date it's better than the alternatives that have been tried.
Market-eonomies which are regulated to ensure that the
markets are both free and fair minimize the worst in
market-economies which quickly go off the rails if there is
not substantive regulation.  Unregulated market-economies
are called free-markets, and they are as bad and in some
ways worse than command-economies.  This has not stopped
many people believing that free-economies supply and demand
is a self-regulating system, and that if all regulation was
removed it would result in a capitalist self-regulating
utopia.  What they forget is that at the beginning of the
industrial revolution mass production created just this kind
of self-regulated system and it resulted in truly horrible
behavior.

Unfortunately, economies today assume that anything bartered
or traded must be either goods or services.  All goods are a
form of property which has an owner.  The word property also
means land, which under the present system also has an
owner, even if that owner is a diety.

Services, on the other hand, treat work-done on behalf of
someone else as a kind of property as well.  Work is energy
expended to do something.  Services are usually measured in
increments of time, and the value of a service is determined
by how easy or difficult the work done is.

The problem with this system is that it doesn't account for
information, which until a few decades ago could only be
used as physical goods that stored information, such as a
book, musical recording or video tape.  Information could
also be treated as a service in the form of transmission
information, or in the form of a performance such as a
concert.

The digital revolution made it possible for the cost of
storing and transmitting information so cheap that for all
practical purposes it became free.  Treating information as
either goods or services was not a very good fit.  So, the
concept of copyright and design patents were invented to
treate specific arrangements of information as property in
their own right.  This worked well when physical recordings
the norm because you weren't selling information, just an
object whose value came from the information recorded on the
object.

When all of these objects were replaced by digitized
information transmitted essentially for free over the
Internet there was no way to monetize information beause
transmission of information makes no distinction of what is
being transmitted.  Transission works fine as a service, but
without physical objects to sell, the producers of
information no longer had means of earning a living from it.

Copyright literally means the right to copy, but that was
when what was copied was a physical object which is property
with an owner.  If you take away my copy of physical object
then I no longer have that object, that object as wealth has
been taken or transfered to a different owner.  But digital
copies that are not permanent physical objects can be copied
and transmitted for free without depriving the person the
copy was made from of their copy.  Ownership is a zero-sum
process that tranfers one thing from one owner to another.
If something is not a zero-sum transfer, then it no longer
functions as property.  So the concept of copyright changed
to mean that the person who owned the original copy also
effectively owned all copies made of it, whether they were
physical or not.  This has not worked out very well.

As more and more wealth becomes information that is not tied
to a physical object, the base assumption of
market-economies based on zero-sum transfer of work and
goods becomes increasingly unstable.

This is set to become even more complicated as AI systems
become smart enough to autonomously control machines.  Does
a self-driving car need an owner?  The entire assumption
that all agents are human beings because only human beings
are capable of being autonomous and self-directing becomes
as unstable as treating information as property.

Newspapers are an interesting case, because they are both
goods and services.  The physical printed paper are goods.
Advertisements are an announcement service that broadcasts
messages to large numbers of people, a one-to-many service.
Newspapers as businesses are just announcement services
where money is made by those who want to broadcast
announcements.  The news iself is also a broadcast service
without a monitizaton model.  With little to no money, one
small company, called Craig's List wiped out the majority of
tranditional newspaper's revenue, classified ads.

----

[2018-06-02 Sat 09:58] Advertising is a crutch -- it's at
the edge of the economy, we need to move away from the
Internet as being part of Media & Content to being at the
core of daily activities, and supply and production chains.
Entertainment is one sphere, publishing is another, but that
is the model that all of these technology companies are now
based on -- they are not part of.

The internet should be thought of as logistics for
information, there is /it/ logistics, and /bit/ logistics.

If it is from bit, then /bits/ are at the core of all /its/
including /it/ logistics.

We need to move away from marketing, to a model where your
needs determine what is manufactured, not manipulate your
desired to convince you to buy what is being manufactured.  

Then all content and the internet is a means of delivering
needs, and will take over most of logistics and information
producers will no longer be sidelined, they will be at the
heart of the system and there will be no divsion between
physical and virtual.

Another BIG problem here is that our by-default-property,
needs to change to by-default-commons.  The market needs to
return to filling people's needs, not filling people's
manipulated desires.

Our system today is designed to create demand to match
production, not match production to meet demands.  This is
bat-shit crazy.  150 years ago this was not the case, and
there is no reason why we can't go back to that model.

The system today is designed to be wasteful, create crap
that has to be replaced every xx months/years and you burn
up resources that does not improve people's lives, only
makes money for a small group of people, creates an instable
production chain that leads to monopolies, squanders
resources and contributes to pollution and climate change.

The selfish ledger could well become the heart of this --
it's actually a very good idea, so long as it's not being
controlled by a consumer economy and production chain.


** References

  - Backhouse, R. E., & Medema, S. G., Retrospectives: on
    the definition of economics, Journal of Economic
    Perspectives, 23(1), 221–233 (2009).
    http://dx.doi.org/10.1257/jep.23.1.221
    cite:backhouse:2009retrospectives
  - Barnes, P., Capitalism 3.0: a guide to reclaiming the
    commons (2006), : Berrett-Koehler Publishers.
    cite:barnes:2006capitalism-3-0
  - Commons transition: policy proposals for an open
    knowledge commons society (2015), : P2P Foundation.
    cite:troncoso:2015commons
  - Kelly, K., New rules for the new economy: 10 radical
    strategies for a connected world (1999), : Penguin.
    cite:kelly:1999new-rules
  - Marglin, S. A., Premises for a new economy, Development,
    56(2), 149–154 (2013).
    http://dx.doi.org/10.1057/dev.2013.20
    cite:marglin:2013premises
  - Mauss, M., The gift : the form and reason for exchange in archaic
    societies (2001), : Routledge.
    cite:mauss:2001gift
  - Mauss, M., The gift : the form and reason for exchange
    in archaic societies (2001), : Routledge.
    cite:mauss:2001gift 
  - Schumacher, E. F., Small is beautiful: economics as if
    people mattered (1975), : Harper Perennial.
    cite:schumacher:1975small
  - Smith, A., The wealth of nations - an inquiry into the
    nature and causes of the wealth of nations (1977), :
    University Of Chicago Press.
    cite:smith:1977wealth
  - Trotsky, L., & ZINOV'EV, G. E., /Soviet economy in
    danger. the expulsion of zinoviev/ (1933).
    cite:trotsky:1933soviet
  - Sutherland, R., /This Thing For Which We Have No Name/
    (2014).
    cite:sutherland:2014no-name
  - Foster, N., /The selfish ledger, internal video/ (2016).
    cite:foster:2016selfish-ledger
  - Levitt, S. D., & Dubner, S. J., Freakonomics: a rogue
    economist explores the hidden side of everything (p.s.)
    (2009), : Harper Perennial.
    cite:steven:2009freakonomics
  - Polanyi, K., The great transformation: the political and
    economic origins of our time (2001), : Beacon Press.
    cite:polanyi:2001great-transformation 
  - Hazlitt, H., Economics in one lesson: the shortest and
    surest way to understand basic economics (1988), : Three
    Rivers Press.
    cite:hazlitt:1988one-lesson
  - Friedman, M., Capitalism and freedom: fortieth
    anniversary edition (2002), : University Of Chicago
    Press.
    cite:friedman:2002capitalism 
  - Tilly, C., Coercion capital and european states a d
    990-1990 (1990), : Blackwell Pub.
    cite:tilly:1990coercion
  - Kropotkin, P., Kropotkin: ’the conquest of bread’ and
    other writings (1995), : Cambridge University Press.
    cite:kropotkin:1995bread
  - Graeber, D., Debt: the first 5,000 years (2011), :
    Melville House.
    cite:graeber:2011debt
  - Heilbroner, R. L., The worldly philosophers. the lives
    times and ideas of the great economic thinkers (2011), :
    Touchstone / Simon & Schuster.
    cite:heilbroner:2011worldly-philosophers
  - Mankiw, N. G., Principles of microeconomics (2014), :
    Cengage Learning.
    cite:mankiw:2014microeconomics
  - Mankiw, N. G., Brief principles of macroeconomics, 5th
    edition (2008), : South-Western College Pub.
    cite:mankiw:2008macroeconomics
  - Mankiw, G., Principles of economics (2007), : Thomson
    Southwestern.
    cite:mankiw:2007principles
  - Thaler, R. H., Quasi Rational Economics (1991), :
    Russell Sage Foundation.
    cite:thaler:1991quasi-rational
  - Thaler, R. H., Misbehaving: the making of behavioral
    economics (2015), : W. W. Norton & Company.
    cite:thaler:2015misbehaving
